### ISSUE TITLE
[RSS] RSS Reader as a sidebar widget feature

### ISSUE THREAD

**Issue by spaeps** [QupZilla/qupzilla#1007]
History and Bookmarks can be displayed both in a separate window (Library) and as a sidebar widget. This does not happens actually for the RSS reader.

It would be nice an RSS sidebar for a fast and paned consultation (Midori style).

Thanks

**Comment by GreenLunar** [comment]
> RSS is there just as a bonus feature

This is unfortunate to know.  If this is the case, please realize RSS abilities into a QupZilla plugin.  In any way, do not entirely drop RSS.

[RSS Is Dying, and You Should Be Very Worried](http://camendesign.com/blog/rss_is_dying)
[Why Big Media Wants to Kill RSS, and Why We Shouldn’t Let It](http://www.newsome.org/2011/01/why-big-media-wants-to-kill-rss-and-why-we-shouldnt-let-it/)

**Comment by GreenLunar** [comment]
For your information, on machine startup, I have LibreOffice (Office), Psi (IM), Sylpheed (Email) and Liferea (RSS), whereas Liferea is the desktop applications that provides me updates instead of wasting precious time searching for updates, while gazing at pictures, using a web browser.
