### ISSUE TITLE
Adress string and Wikipedia pages

### ISSUE THREAD

**Issue by AlexTalker** [QupZilla/qupzilla#1095]
Link to page: https://ru.wikipedia.org/wiki/Сияние_(фильм)

And in string(adress page) it non-russian symbols.WTF?

e.g.:

https://ru.wikipedia.org/wiki/������_(�����)
![adress_string](https://f.cloud.github.com/assets/3531127/1644692/2f9a7894-58eb-11e3-8f13-029ee8a010f8.png)

**Comment by srazi** [comment]
@nowrep: It seems Firefox  (and also Chrome) doesn't decode a URL if its decoded version contains Latin1 characters.
