### ISSUE TITLE
Fullscreen not working - Youtube - html5

### ISSUE THREAD

**Issue by ghost** [QupZilla/qupzilla#1127]
Hello
I just testing the brand new 1.6.0 version.
Everything was working great until I tried to play Youtube without flashplugin (only with html5).
Fullscreen on Youtube is not working.

I am running:
- Up-to-date Archlinux
- qupzilla v1.6.0
- qt5-webkit 5.2.0
- Qt 5.2.0
- KDE 4.12.0

**Comment by The-Compiler** [comment]
I reported this upstream here: https://bugreports.qt-project.org/browse/QTBUG-43625

**Comment by JHooverman** [comment]
@The-Compiler: Thank you! I have added this to our [Upstream Bugs](https://github.com/QupZilla/qupzilla/wiki/Bug-Reports#5-upstream-bugs).

**Comment by sydneyjd** [comment]
I am having the exact same issue on a number of diferent machines, all up to date, one with ubuntu, another with debian, and a third with Arch. If i use Adobe Flash they full screen fine, but once i switch to HTML5 in youtube, i cannot fullscreen. My browser does pass all the fullscreen tests you have linked.

**Comment by sydneyjd** [comment]
Ok, doing some more testing. Ive created a fresh profile to the same avail.
Im using: 
qupzilla 1.8.9
qt5-webkit 5.5.1

**Comment by innermous** [comment]
@sydneyjd dude, it was said: it's upstream bug, still not fixed. What's the point?

**Comment by sydneyjd** [comment]
Im sorry for the annoyance, and i do realize that, but i figured it might help if they had more than one person report that they had it. Im sorry.

**Comment by JHooverman** [comment]
@sydneyjd: Unfortunately it will not help, if you add reports to this QupZilla issue. But you could register with [qt-bugs](https://bugreports.qt.io/secure/Dashboard.jspa) and add yourself to the watchers (you will be notified, if this upstream issue is fixed) and vote for this issue.

![img1](http://i.imgur.com/fJKHd6e.png)

If there are many votes, this upstream issue will hopefully get some more attention.

**Comment by sydneyjd** [comment]
Already done. ;)

**Comment by Martii** [comment]
Apologies for the additional noise on this one... https://bugreports.qt.io/browse/QTBUG-43625 is the new url without the warning of [the old URI](https://bugreports.qt-project.org/browse/QTBUG-43625) with untrusted connection.

**Comment by josephg5** [comment]
youtube full-screen still not working! clicking on the icon pops-up message "Full screen is not available. Find out more"
Mozilla/5.0 (X11; Linux i686) AppleWebKit/538.1 (KHTML, like Gecko) QupZilla/1.8.9 Safari/538.1

**Comment by Gibbz** [comment]
same issue as above
