### ISSUE TITLE
Portable edition doesn't even start up...

### ISSUE THREAD

**Issue by highend** [QupZilla/qupzilla#1181]
I've tried v1.6.1 on Windows Server 2012 R2 (x64, german)

and i get this window immediately:

![unbenannt](https://f.cloud.github.com/assets/687706/2013533/f5ac920e-8796-11e3-892d-f18a9a54f11e.png)

**Comment by JHooverman** [comment]
Closing this issue due to lack of response. If you have new information, please feel free to re-open.
