### ISSUE TITLE
No thumbnail preview for pictures and/or videos - portable version

### ISSUE THREAD

**Issue by floppyx** [QupZilla/qupzilla#1196]
I need a plugin or some workaround to be able to see thumbnails while searching images and videos on the web. 

This is the only issue for me. Qupzilla is the best alternative to Firefox, and it is a decent browser for low-end machines. One of the best choices for Linux, for sure. I am still testing it under Windows, and so far the only complaint I have is that i can't see the thumbnails while using the portable version of Qupzilla 161.

![screenshot001](https://f.cloud.github.com/assets/6582915/2074616/e9568252-8d7d-11e3-8580-685a26d497fb.jpg)
![screenshot002](https://f.cloud.github.com/assets/6582915/2074617/e95e6b8e-8d7d-11e3-95be-a4ce844e6635.jpg)

**Comment by JHooverman** [comment]
This issue does not appear with the latest windows release
Application version: 1.8.9
Qt version: 5.5.1
WebKit version: 538.1
Platform: Windows 7

Please upgrade your installation to the latest version. If this issue still occurs, then please re-open this issue.
