### ISSUE TITLE
Bookmark toolbar folders don't show icons....

### ISSUE THREAD

**Issue by badtlc** [QupZilla/qupzilla#1215]
This is occuring in linux mint via debian install files and the repository installation method.  It appears to also be a problem in the portable windows version.  It looks like the bookmarks menu is not showing icons, either, at least in Linux.

The bookmark icons show up for bookmarks located directly on the toolbar, but not in a folder on the toolbar.  The bookmark icons also show up properly in the bookmark organizer.

Bookmarks for me in win7 and win8 appear to be working fine.

**Comment by ninetyfivenorth** [comment]
lol this is a an adderoll rat race nascar style vr00mmmm. I came here seeking answers /to this very question/ for this /exact browser issue/ but... I must say that the issue is [RESOLVED] and was made certainly {CLEAR-ENOUGH} lol 

xox
