### ISSUE TITLE
Source viewer improvements

### ISSUE THREAD

**Issue by beastie1** [QupZilla/qupzilla#1243]
The source viewer is a great tool that I like a lot, especially the ability to edit and reload the modifications.

I'd like to share 2 improvement requests:
1. Integrate it as a tab
2. Change the "line selection" highlight color: there should be more contrast in the colors because the dark-blue background makes it very difficult to read the black text.

Thank you in advance and keep up the great work.

**Comment by nowrep** [comment]
Internal source viewer in tab is now used with QupZilla 2.
