### ISSUE TITLE
REQUEST: For Plugin Support - MaskMe & DownThemAll

### ISSUE THREAD

**Issue by ghost** [QupZilla/qupzilla#1281]
If at all possible I'd like to make a request to add in support for DownThemAll and the MaskMe plugin developed by Abine; 

http://www.abine.com/
https://addons.mozilla.org/en-US/firefox/addon/maskme/

This is one of the better plugins out there for;

disposable/masked emails
masked phones
masked credit cards
encrypted passwords

I personally only use this for making masked emails and it works really great in Firefox...

I've looked at a lot of different choices out there and MaskMe is one of the best if not best.

I truly hope this can be added into QupZilla...

THANKS for your consideration! :)

**Comment by moulei** [comment]
Hi Guys,

How's this looking for 2015?

thank you
