### ISSUE TITLE
The right-click menu is away from my mouse, Mac OS X

### ISSUE THREAD

**Issue by tibounise** [QupZilla/qupzilla#1300]
I tried QupZilla (official build, version 1.6.3), and when I do a right click, the menu is away from my pointer :

![bildschirmfoto 2014-04-18 um 23 18 29](https://cloud.githubusercontent.com/assets/1449723/2746041/4bc971f6-c73f-11e3-8f87-cd4cba4606d4.png)
(on this example, my mouse was ~400px below the menu)

I'm running Mac OS X 10.9.2, and using a mouse as a pointing device.

**Comment by nowrep** [comment]
Fixed in latest version.
