### ISSUE TITLE
Userscripts don't install but just load as JavaScript text in window

### ISSUE THREAD

**Issue by duanemoody** [QupZilla/qupzilla#1302]
Despite there being a Greasemonkey plugin in the app folder, clicking Install from userscripts.org doesn't install the userscript, it just shows the text of the script itself. No prompt shown or other confirmation. Version 1.6.3, OS X 10.9.2 Mavericks.

**Comment by nowrep** [comment]
Fixed in latest version.

**Comment by duanemoody** [comment]
userscripts still load as text in current.

**Comment by ke7ofi** [comment]
@duanemoody What's wrong with ~/.config? We're still trying to get people to move *to* that on Linux.

**Comment by The-Compiler** [comment]
@ke7ofi `~/.local/share` is defined in the [same standard](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) as `~/.config`, so same thing, just for different kind of files.

**Comment by ke7ofi** [comment]
@The-Compiler I'd never seen the standard itself before, but that makes sense, so thanks.
