### ISSUE TITLE
Delete browsing history does not delete browsing history

### ISSUE THREAD

**Issue by gelignite** [QupZilla/qupzilla#1316]
When I press CRTL+Shift+Del the browsing history deletion dialog comes up. But even if I enable everything I still can move forwards/backwards in the browser navigation. I have to right-click on the arrows and delete the browsing history there.

I'd expected the navigation history to be deleted when I say "delete browsing history".

**Comment by Arnaudv6** [comment]
Then again, you have to quit a relaunch trojita for links to stop appearing as "visited".

**Comment by Arnaudv6** [comment]
I should like to see an option in preferences to clear all history on exit.

Note : checking this option + "delete cookies on exit" option produces a different effect from private navigation because it remebers (only) open tabs... Which is very handy.

**Comment by cranes-bill** [comment]
> I should like to see an option in preferences to clear all history on exit.

QupZilla already have this option:
**Menu » Preverences » Navigation »** ` 'Local storage (tab)'`
:ballot_box_with_check: **Deleate History on Exit**

**Comment by Arnaudv6** [comment]
Agreed: option is there. It actually does not work for me : history gets remembered anyway.
steps to reproduce : activate session restoration on lauch, and google for 'test', 
open any result in a new tab, close freshly opened tab, quit and then re-launch trojita.
The linked you'ved clicked appears as visited (violet), even though
Menu » Preverences » Navigation » 'Local storage (tab)' » Delete History on Exit is checked.

**Comment by Arnaudv6** [comment]
That is `Visited Links` file is not purged.
