### ISSUE TITLE
Display RSS feeds info in human readable format

### ISSUE THREAD

**Issue by ekianjo** [QupZilla/qupzilla#1361]
Clicking on a RSS feed from the browser will show the contents of the feed but it is in no way formatted to be readable. Chrome formats it nicely by splitting the info line by line so that someone can actually see the structure and the contents. Could qupzilla reapply that idea?

**Comment by GreenLunar** [comment]
Is not this a QWebKit (now it is QtWebEngine) issue?

**Comment by sjehuda** [comment]
I have made a few XSLT stylesheets to handle this task.
https://cloud.githubusercontent.com/assets/19249089/20603865/29eb6344-b26c-11e6-9b9b-f062f635205a.png (1MB)

This is still under work-in-progress stages, yet most of the features that users would expect for, including enclosures (i.e. file attachments) and even geographically encoded objects, are ready.

Open issues at https://github.com/sjehuda/syndication4humans/issues

**Comment by sjehuda** [comment]
It is ready for testing. https://github.com/sjehuda/syndication4humans-qupzilla

**Comment by sjehuda** [comment]
Live demo https://sjehuda.github.io/blog.qupzilla.com.atom

**Comment by nowrep** [comment]
@sjehuda That looks great, I'll see if I can integrate it in QupZilla.

**Comment by GreenLunar** [comment]
Off Topic

> Chrome formats it nicely by splitting the info line by line so that someone can actually see the structure and the contents. Could qupzilla reapply that idea?

@ekianjo are you sure your statement is correct?
For some reason, Chrome does not format the live demo https://sjehuda.github.io/blog.qupzilla.com.atom
