### ISSUE TITLE
Segfault when I open my corporative mail

### ISSUE THREAD

**Issue by kulti** [QupZilla/qupzilla#1387]
Hi all!

I cannot use my corporative mail with qupzilla. Tommorow it was open successfully, but today it crash qupzilla evrytime.

I have qupzilla and qtwebkit with debug symbols and I paste all bactraces here http://pastebin.com/y0SkG5LV

**Comment by ndegruchy** [comment]
I am getting a crash in Qupzilla on OWA/Office 365.

Running it from the console gives me a couple of strange errors:

~~~
~ $ qupzilla 
QupZilla: 2 extensions loaded
SpellCheck: Language = "en_US" "UTF-8" (QupZilla: Crashed :( Saving backtrace in /home/ndegruchy/.config/qupzilla/crashlog ...
Backtrace successfuly saved in /home/ndegruchy/.config/qupzilla/crashlog/Crash-2015-08-31T14:19:36.txt
fish: “qupzilla” terminated by signal SIGABRT (Abort)
~~~

I've posted the crash log to this gist: https://gist.github.com/ndegruchy/5c0d613a52702a9353ad
