### ISSUE TITLE
Instagram not work properly in QupZilla

### ISSUE THREAD

**Issue by kulti** [QupZilla/qupzilla#1394]
I've found, that some pages not properly open in QupZilla. So, I create a simple QtWebKit application(https://bitbucket.org/kulti/qtb) to test, that is QtWebKit issue or not.

I cannot open user instagram page. E.g. http://instagram.com/vvromanov is blank (works fine with QtWebKit test browser).

**Comment by potholiday** [comment]
@cranes-bill I am also having the same problem with qupzilla appimage. It just show a blank page.

**Comment by cranes-bill** [comment]
This issue is pretty old and should not affect newer QupZilla versions.
Did you try with clean profile?

**Comment by potholiday** [comment]
@cranes-bill  I am using the latest version Application version 2.1.2, QtWebEngine version 5.8.0, Ubuntu 14 when I visit instagram site it gives a blank page.

A second problem is with reddit in private browsing. I can login but cant post threads or replys in private browsing.

**Comment by cranes-bill** [comment]
Once again: Did you try with clean profile?
Appimage works to me:
![capture du 2017-08-20 07 34 38](https://user-images.githubusercontent.com/5161278/29497297-5e8e66e0-85ee-11e7-83db-ab8dcd8352d0.png)

**Comment by potholiday** [comment]
Sorry initially I didnt get what you are mentioning as **clean profile**. I thought default profile is the clean profile then I created a new profile and open instagram in it; instagram works in that. I think some add ons or plugins in my default profile broke instagram. any ways thanks for the reply.
