### ISSUE TITLE
Feature: Password export/import

### ISSUE THREAD

**Issue by fcore117** [QupZilla/qupzilla#144]
Hello, thank you so much for developing ultralight pure QT Chrome/Firefox alternative, but i am so much need for feature that is exporting passwords to xml like Firefox has extension(development paused).

My whole life is connected with this feature in Firefox because then i can export passwords to secret places like TrueCrypt containers(even my bank codes is in passwords). I really hope you can code this feature in very light way to QupZilla.

**Comment by johnnyl33** [comment]
but.. what happened? o_O

**Comment by nowrep** [comment]
@johnnyl33 What?
