### ISSUE TITLE
Another issue with transifex

### ISSUE THREAD

**Issue by smarquespt** [QupZilla/qupzilla#1467]
How to reproduce:
1 - Log in (log in is ok)
2 - Click anywhere (eg: dashboard)

Expected behaviour:

Dashboard is opened

Current behaviour:

Login page is shown again. We need to get back user and password. After putting this info transifex dashboard is shown.

I´m using 1.8.0 in windows 7.

**Comment by smarquespt** [comment]
This issue is back in 1.8.6 windows release.

**Comment by JHooverman** [comment]
My Step-by-Step procedure:

(1) Go to https://www.transifex.com/projects/p/qupzilla/
(2) Login with username & password
(3) Click on a language to translate
(4) Click `Translate` in the following dialog
(5) Access the translation page

This works for both:

QupZilla
Application version: 1.9.0 (ee80b04a11)
Qt version: 5.4.2 (git)
WebKit version: 538.1
Build time: Feb 8 2015 10:30:39
Platform: openSUSE Tumbleweed (Linux)

QtTestBrowser
Qt version: 4.8.6
WebKit version: 537.21

Maybe transifex made an API change on their pages.

**Comment by smarquespt** [comment]
he I try to do your steps, between steps I always go back to login page. But if I login afterwards I´m redirected to last step. 

In QtTestBrowser windows release it works fine.

**Comment by JHooverman** [comment]
I do not know, if this matters, but could you check your AdBlock- and Cookie-settings? These are mine:

![adb](http://i.imgur.com/utFdOzb.png)

![cookie](http://i.imgur.com/umolcpk.png)

**Comment by smarquespt** [comment]
@JHooverman 

Yes it works now with my settings just like yours. Thanks
