### ISSUE TITLE
Request: Spellcheck in input fields

### ISSUE THREAD

**Issue by ghost** [QupZilla/qupzilla#1470]
While I'm at it, one of the things I'm missing in Qupzilla is a tool for checking spelling in <textarea> and <input type="text"> fields. Should be able to use the dictionaries already installed on the OS, like in Thunderbird (I think that's how it works). And then the option the switch between dictionaries, as well as turning spelling on/off. This last thing would be the least important.

**Comment by fbobraga** [comment]
How can I enable spellchecking here (QupZilla 1.8.6 / Fedora 22)?

Some more info from my envoirment:
> $ hunspell -D
> SEARCH PATH:
> .::/usr/share/hunspell:/usr/share/myspell:/usr/share/myspell/dicts:/Library/Spelling:/home/fbobraga/.openoffice.org/3/user/wordbook:.openoffice.org2/user/wordbook:.openoffice.org2.0/user/wordbook:Library/Spelling:/opt/openoffice.org/basis3.0/share/dict/ooo:/usr/lib/openoffice.org/basis3.0/share/dict/ooo:/opt/openoffice.org2.4/share/dict/ooo:/usr/lib/openoffice.org2.4/share/dict/ooo:/opt/openoffice.org2.3/share/dict/ooo:/usr/lib/openoffice.org2.3/share/dict/ooo:/opt/openoffice.org2.2/share/dict/ooo:/usr/lib/openoffice.org2.2/share/dict/ooo:/opt/openoffice.org2.1/share/dict/ooo:/usr/lib/openoffice.org2.1/share/dict/ooo:/opt/openoffice.org2.0/share/dict/ooo:/usr/lib/openoffice.org2.0/share/dict/ooo
> AVAILABLE DICTIONARIES (path is not mandatory for -d option):
> /usr/share/myspell/en_US
> /usr/share/myspell/pt_AO
> /usr/share/myspell/pt_PT
> /usr/share/myspell/pt_BR
> LOADED DICTIONARY:
> /usr/share/myspell/pt_BR.aff
> /usr/share/myspell/pt_BR.dic
> Hunspell 1.3.3

... and no "Speller::initialize()" output when running qupzilla from terminal

**Comment by JHooverman** [comment]
Just to be sure: Did you install the [qtwebkit-plugin](https://github.com/QupZilla/qtwebkit-plugins)?

If so, you will have to enable spell-checking as seen in this image:

![im1](http://i.imgur.com/IUE4EFY.png)

**Comment by nowrep** [comment]
You don't need to install the QupZilla/qtwebkit-plugins , it is included in QupZilla.

**Comment by fbobraga** [comment]
@JHooverman this item don't exists here

**Comment by fbobraga** [comment]
It can be related: https://ask.fedoraproject.org/en/question/69449/spell-checking-doesnt-work-in-fedora-kde-22-plasma5/ (but I don't use KDE: the problem is occurrin here in two machines with gnome-shell and lxde, both with Fedora 22)

**Comment by nowrep** [comment]
You need to have QupZilla built with Hunspell.
