### ISSUE TITLE
Please unbundle qftp, qtsingleapplication and make them external deps.

### ISSUE THREAD

**Issue by Coacher** [QupZilla/qupzilla#1503]
Hello.

Currently qupzilla bundles qftp and qtsingleapplication. The first one is a part of QtNetwork module and the second one is available from here https://qt.gitorious.org/qt-solutions/qt-solutions/ and can be packaged as well. These packages are common in popular distros. Though qtsingleapplication is absent from Debian and friends (Ubuntu, Mint).

Maybe it is possible to unbundle at least qftp and use bundled qtsingleapplication only when there is no system-wide installation?

Thanks.

**Comment by rapgro** [comment]
You should derive and instantiate your own class from QtSingleApplication and implement there a new constructor with private storage of AppId. That's more accordingly to OOD and does not avoid unbundling.

**Comment by Coacher** [comment]
Reopen maybe?

**Comment by nowrep** [comment]
It's not possible to replace it with system QtSingleApplication. The `sysInit()` function is private and it also modifies private variables.
There is no way to use system QtSingleApplication with possibility to change `appId` after calling constructor. At least it's not possible without actually rewriting half of QtSingleApplication itself again ...

Also, we can't workaround it, as @srazi already pointed out.
