### ISSUE TITLE
1.8.3 & QT 5.3.2 - Menu Buttons Missing

### ISSUE THREAD

**Issue by ghost** [QupZilla/qupzilla#1510]
Hi,

My Specs;

```
Slackware 14.1 x86_64
QupZilla 1.8.3
QT 5.3.2
WebKit version 538.1
```

I noticed with 1.8.3 and QT 5.3.2 the menu buttons don't appear, here's a screen shot;

http://i.imgur.com/VU776nC.jpg

**Comment by moulei** [comment]
in 1.8.6 everything seems to be working ok, not sure if I did anything to improve this or not...
