### ISSUE TITLE
Preference Window - Won't Maintain Width When Adjusted...

### ISSUE THREAD

**Issue by ghost** [QupZilla/qupzilla#1514]
Hi,

Specs;
1.8.4
QT 5.3.2
WebKit version 538.1

I noticed the preferences always has a scroll bar on the bottom and if you widen the window, then close it, it opens back up to a default smaller size.

Can you please make it so it maintains size after it's been reisized and closed?

Here's a screen shot showing the scrollbar, also how text on the right is always cut off too;

http://i.imgur.com/eZeHCMa.png

Thank you...

**Comment by moulei** [comment]
It appears to look nice now in 1.8.6 :)
