### ISSUE TITLE
portable version still creates folder in Local AppData

### ISSUE THREAD

**Issue by PNBRQK** [QupZilla/qupzilla#1534]
Hi,

I have tested the portable version for Windows for a while to find it leaves a folder "Qupzilla\tmp" in "%USERPROFILE%\Local Settings\Application Data".  (I am using WinXP SP3) 

I have examined the configuation file but found no idea to fix this. Is there something I missed?

Sincerely
Yi Zili

**Comment by nowrep** [comment]
This should be fixed with latest version.
