### ISSUE TITLE
Make it compile with just kwallet

### ISSUE THREAD

**Issue by demmm** [QupZilla/qupzilla#1545]
To build the kwalletplugin, at this stage, it is still needed to have kdelibs (kde 4) available, but with the move to frameworks 5, it would be nice it is no longer needed to use kdelibs too.
A simple sed line made this possible here one a pure frameworks 5/Qt 5 build:
https://github.com/KaOSx/apps/blob/master/qupzilla/PKGBUILD#L37

Possible to use this already?  Using ifdef for when either kdelibs or kwallet is found?

**Comment by berot3** [comment]
I just installed version 1.8.6 from ppa:nowrep/qupzilla in vivid with kf5 and noticed that there is no kwallet-extension. 
Is there a way to get/activate it?

**Comment by nowrep** [comment]
You must build it yourself because that ppa still uses Qt 4.

**Comment by nowrep** [comment]
@demm Is that patch still needed?

**Comment by berot3** [comment]
Oh ok, thank you.
Or is there a qt5-ppa so I don't have to compile? ;)

**Comment by nowrep** [comment]
No

**Comment by demmm** [comment]
@nowrep 
Build fails with:
    /usr/lib/qt5/bin/uic sbi_settingsdialog.ui -o build/ui_sbi_settingsdialog.h
    In file included from kwalletplugin.cpp:19:0:
    kwalletpasswordbackend.h:22:30: fatal error: KDE/KWallet/Wallet: No such file or directory
   #include <KDE/KWallet/Wallet>
                                                     ^
   compilation terminated.
 When build on a pure Qt5/Frameworks 5 setup, kwallet dep added
Apply the patch, builds fine (tried with latest 1.8 branch checkout & 1.8.6 release tar)
To build the plugin as is, kdelibs 4 needs to be present.
