### ISSUE TITLE
Offer Configuration Option for Deleting Cookies at Exit.

### ISSUE THREAD

**Issue by ghost** [QupZilla/qupzilla#1550]
Qupzilla currently has a configuration option for deleting every stored cookie when closing the browser. Unfortunately, this option can be only enabled when the option for allowing cookies is enabled too.

The problem is there could be cookies stored by the browser even if the configuration ollow is set to not enabling them (for example, if you have cookies in your white list). It would be desirable that the option for deleting cookies at exit was active regardless of the status of the option that enables cookie use.

**Comment by Martii** [comment]
See also:
* #2173
* #1901
