### ISSUE TITLE
Youtube html5 video flicker

### ISSUE THREAD

**Issue by espressodrinker** [QupZilla/qupzilla#1551]
Besides the top search bar qtwebkit flickering thing 
The html5 video also flickers perhaps this is another qt / gstreamer problem? 
It happens both on intel and nvidia systems on a slower intel system it was noticeable that it flashes to a color inverted image. 

Application version 1.8.4
WebKit version 538.1
Arch linux

**Comment by The-Compiler** [comment]
There was now a patch posted to the bug: https://codereview.qt-project.org/#/c/102971/

Allan Sandfeld Jensen (the QtWebKit maintainer) said he thought it was only an optimisation but it might fix the issue - is there anyone here who can easily compile QtWebKit with that patch and try if it goes away? I don't really have the toolchain ready to do that easily at the moment.

**Comment by JHooverman** [comment]
I regret, this is beyond my capabilities.
