### ISSUE TITLE
Latest qupzilla build doesn't install to correct location on FreeBSD

### ISSUE THREAD

**Issue by willbprog127** [QupZilla/qupzilla#1564]
Latest qupzilla doesn't install to correct location on FreeBSD 10.1.  Currently it's installing to /usr/bin, /usr/share, etc when it should be installing to /usr/local/bin, /usr/local/share, etc.

--

:information_source:
Application version: `1.9.0`
Qt version: `4.8.6`
WebKit version: `534.34`
Build time: `Dec 23 2014 13:04:42`
Platform: `BSD 4.4`
Browser Identification:
`Mozilla/5.0 (X11; BSD Four) AppleWebKit/534.34 (KHTML, like Gecko) QupZilla/1.9.0 Safari/534.34`

**Comment by pejakm** [comment]
If I understand correctly, everything on BSD is installed to /usr/local?

**Comment by nowrep** [comment]
Because you are using wrong command to build, it should be:

```
QUPZILLA_PREFIX=/usr/local /usr/local/lib/qt5/bin/qmake "CONFIG+=release"
```

**Comment by willbprog127** [comment]
@nowrep You are so right, I apologize, however even with the correctly-issued commend, QupZilla is still looking for hunspell in the wrong spot on FreeBSD:
```
SpellCheck: Dictionaries for "/usr/share/hunspell/en_US" doesn't exists! (plugins/qtwebkit/spellcheck/speller.cpp:87, void Speller::initialize())
```
@pejakm Yes, all non-system-related software, such as QupZilla, PCManFM, LibreOffice, etc are all installed in `/usr/local`

**Comment by anordal** [comment]
Default prefix should be /usr/local/ on Linux too!

**Comment by willbprog127** [comment]
@anordal Yes, I agree...that is correct.

I have filed a separate issue for hunspell here: https://github.com/QupZilla/qupzilla/issues/1588
