### ISSUE TITLE
Profiles are not removed permanently

### ISSUE THREAD

**Issue by JHooverman** [QupZilla/qupzilla#1570]
Please try the following step-by-step procudure:

(1)  Start QupZilla
(2)  Go to `Preferences -> General -> Profiles -> Create New`
(3)  Enter a profile name, here "ZZZZZZ"
(4)  Hit `Ok`
(5)  "ZZZZZZ" is now startup profile
(6)  Restart QupZilla
(7)  Go to `Preferences -> General -> Profiles -> Startup Profile`
(8)  Select "default"
(9)  Restart QupZilla
(10) Go to `Preferences -> General -> Profiles -> Delete`
(11) Select "ZZZZZZ"
(12) Confirm with `Yes`
(13) "ZZZZZZ" is removed from the list
(14) Restart QupZilla
(15) Go to `Preferences -> General -> Profiles -> Delete`

Observation:
* "ZZZZZZ" is back in the list
* `$HOME/.config/qupzilla/profiles` still contains a folder "ZZZZZZ"

Expected behaviour:
* "ZZZZZZ" should be removed the list of available profiles permanently
* "ZZZZZZ" should be removed from the folder `$HOME/.config/qupzilla/profiles` permanently

Tested with:

Application version: 1.9.0 (3511e0401b)
Qt version: 5.4.1
WebKit version: 538.1
Build time: Dec 26 2014 10:55:47
Platform: openSuSE Tumbleweed (Linux)

**Comment by mariarti** [comment]
Patch does not fix bug

**Comment by JHooverman** [comment]
As already stated by @mariarti: This issue still persists with

Application version: 1.9.0 (80dd3a8f85)
Qt version: 5.4.2
WebKit version: 538.1
Build time: Jan 19 2015 20:29:21
Platform: openSuSE Tumbleweed (Linux)

**Comment by JHooverman** [comment]
Fixed with:

Application version: 1.9.0 (ee80b04a11)
Qt version: 5.4.2
WebKit version: 538.1
Build time: Jan 25 2015 16:47:02
Platform: openSuSE Tumbleweed (Linux)
