### ISSUE TITLE
Message display and composition does not work properly on Hotmail / Outlook.com email

### ISSUE THREAD

**Issue by willbprog127** [QupZilla/qupzilla#1576]
Hotmail / Outlook.com email cannot be used because the text that should display for message composition and display of previous emails does not display in QupZilla (see attached picture).

![qupzilla-hotmail-issue-01](https://cloud.githubusercontent.com/assets/1296250/5590636/98185e3a-90ef-11e4-8cdb-da8fd0523491.png)

-

:information_source:
Build 42ebb227c671be2e7cf9080eb0c0f4245508bfc5
Application version: `1.9.0`
Qt version: `5.3.2`
WebKit version: `538.1`
Build time: `Dec 31 2014 09:15:46`
Platform: `BSD 4.4`
Browser Identification:
`Mozilla/5.0 (X11; FreeBSD) AppleWebKit/538.1 (KHTML, like Gecko) QupZilla/1.9.0 Safari/538.1`

**Comment by JHooverman** [comment]
Happy New Year!

This is the result with QtTestBrowser compiled against Qt-5.4.1 + qtwebkit 538.1

![out1](http://i.imgur.com/oiRi1hc.png)

So, outlook.com works here.

Could you please download [QtTestBrowser](http://cloud.qupzilla.com/public.php?service=files&t=15d78bb1cf2b813aa5a496c0a8b063a7) and compile it on your system (I really hope, that this can be easily done on BSD)? Then please try to reproduce your issue with QtTestBrowser.

**Comment by willbprog127** [comment]
Happy New Year to you! :D

I tried with QtTestBrowser and it's identical to my attempt in QupZilla...those fields are empty.  It's possible it's a Qt5 issue on FreeBSD...

**Comment by willbprog127** [comment]
I also noticed just now that QupZilla issues this on the command-line when I try to use 'compose' on outlook:
```
WOFF support requires QtWebKit to be built with zlib support. (/wrkdirs/usr/ports/www/webkit-qt5/work/qtwebkit-opensource-src-5.3.2/Source/WebCore/platform/graphics/qt/FontCustomPlatformDataQt.cpp:60, WebCore::FontCustomPlatformData *WebCore::createFontCustomPlatformData(WebCore::SharedBuffer *))
```

**Comment by willbprog127** [comment]
I have written to the maintainers of the Qt5-Webkit port/package and will let you know:

> To: kde@FreeBSD.org
> CC: ports@FreeBSD.org
> Subject: FreeBSD Port: qt5-webkit-5.3.2_2
> 
> Dear Maintainers,
> 
> Happy New Year!
> 
> Browsers such as QupZilla and Rekonq use Qt5-Webkit for their 
> functionality.
> 
> There are websites that use WOFF (Web Open Font Format) however 
> FreeBSD's Qt5-Webkit package appears to have an issue, which causes the 
> websites to not display text at all.
> 
> Please see the notice message below, which is displayed on the 
> command-line when sites using WOFF are loaded:
> 
>  > WOFF support requires QtWebKit to be built with zlib support.
>  > 
> (/wrkdirs/usr/ports/www/webkit-qt5/work/qtwebkit-opensource-src-5.3.2/Source/WebCore/
>  > platform/graphics/qt/FontCustomPlatformDataQt.cpp:60, 
> WebCore::FontCustomPlatformData
>  > *WebCore::createFontCustomPlatformData(WebCore::SharedBuffer *))
> 
> Is it difficult or impossible to enable zlib support?  I would really 
> like to use QupZilla with sites such as Outlook.com which currently 
> doesn't work because of this issue.
> 
> Thank you for your time !
> 
> --
> 
> Will Brokenbourgh
> 
> [ Send from my FreeBSD desktop ]

**Comment by willbprog127** [comment]
Is there any information about why this is now resolved?  Also @nowrep thanks for all of your hard work...looks like you're kicking the bug-fixing into high gear lately :smile_cat:

**Comment by nowrep** [comment]
I closed all bugs that are clearly QtWebKit bugs, including this one.

**Comment by willbprog127** [comment]
Ah okay.  For clarification, does that mean the issues are resolved, or are they unresolved and upstream's problem?

**Comment by nowrep** [comment]
Some may be resolved in newer QtWebKit versions, some of them are just upstream problem.
