### ISSUE TITLE
[Feature request] Switch AdBlock for µBlock

### ISSUE THREAD

**Issue by ToKrCZ** [QupZilla/qupzilla#1578]
Hi fellow czech developer ;),

how about ditching AdBlock for the sake of µBlock? Seems to be more lightweight & performant, which is exactly what you are aiming for with your project as well.

https://github.com/gorhill/uBlock

Just a quick idea, µBlock has impressed me. The best adblocker I have ever used.

Měj se, díky za dobrou práci ;-)

**Comment by GreenLunar** [comment]
Is µBlock that lean? :-o

**Comment by dd0slash** [comment]
Apart from performance gains what I like about it is "dynamic filtering" feature. You can selectively blacklist or whitelist things like 3rd party scripting and specific domains locally or globally. It's like RequestPolicy but better.
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide

**Comment by meuwe** [comment]
Problem is there seems to of been a split...

Now there's uBlock & uBlocko, gorhill seems to of left uBlock and is continuing on with uBlocko, talk about confusing... :(

**Comment by ff2000** [comment]
If nothin changed dramatically QupZillas "AdBlock" has nocthin to do with AdBlock Plus or other wellknown Plugins. It's an own implementation in C++, so it should be (and is) really fast. It only uses AdBlock lists to get up-to-date block rules. So I think this could be closed.

**Comment by nowrep** [comment]
Exactly as @ff2000 said. If you miss some additional features from uBlock, please open a specific issue for it.

**Comment by meuwe** [comment]
Oh my bad, didn't realize this is QupZilla's fork on an Adblock version...

Problem is, most users know of ABP, so when you say Adblock they assume this, plus you have the same looking icon as ABP...

The DEVs should change the name and look of the icon... :)

**Comment by ff2000** [comment]
meuwe wrote:
> Oh my bad, didn't realize this is QupZilla's fork on an Adblock version...
It not even is a fork - it is just a program with similar functionality. (Good old Opera also wasn't a fork of Mozilla)

> Problem is, most users know of ABP, so when you say Adblock they assume this, plus you have the same looking icon as ABP...
Adblock is just the term that describes the functionality in the most appropriate way. Come up with a different naming that still shows that this thing is blocking ads ;)

And TBH this was the first time in qupzillas long life that I heard someone thought qupzilla actually shipped AdBlockPlus.

> The DEVs should change the name and look of the icon... :)
Well, this is Open Source. If YOU think QupZilla needs a different Icon for Adblock design one and create a pull request.

**Comment by meuwe** [comment]
First I'm not a coder, designer, developer, just an end-user...

Yes the icon should be changed, it's the same Stop Sign look, why even make something look somewhat similar? That's not good from a marketing standpoint of; ```Distinction```...

Here's some new names;

AdBlockIt
AdBlocker
AdBlocking
BlockAds
