### ISSUE TITLE
Unable to establish secure connection with TLS 1.0

### ISSUE THREAD

**Issue by pejakm** [QupZilla/qupzilla#1579]
Example page: https://blog.protonmail.ch/protonmail-beta-v1-11-release-notes/

I presume this is caused by the commit https://github.com/QupZilla/qupzilla/commit/0ccc759e1f58d949e3fbfc0e49aa1424ef3fb109. Could we keep TLS 1.0/1.1 enabled?

**Comment by cranes-bill** [comment]
That's a Qt 5 or QtWebkit issue.
Trying opening page with Qt 5.4.0; QtWebkit 538.1, i get this:
![-echec lors du chargement de la page - qupzilla](https://cloud.githubusercontent.com/assets/5161278/5601815/8f02b462-9324-11e4-8af4-4068204bac3c.png)

But with Qt4.8.6; QtWebkit 537.21, get this:
![-protonmail beta v1 11 release notes - protonmail blog - qupzilla](https://cloud.githubusercontent.com/assets/5161278/5601818/c7481ac4-9324-11e4-981b-a30b39f8e9f7.png)

**Comment by JHooverman** [comment]
@cranes-bill: If you start QupZilla compiled against qt-4.8.6, `Disable SSL3` checked or unchecked?

**Comment by cranes-bill** [comment]
@JHooverman -it is checked, that's by default.

**Comment by JHooverman** [comment]
Two further web-pages, that show the same behavior:

https://software.opensuse.org/search [does not work with Disable SSL3 unchecked]
https://bugreports.qt-project.org/browse/QTBUG [works with Disable SSL3 unchecked]

**Comment by pejakm** [comment]
@JHooverman What do you get for TLS 1.1 and TLS 1.0 with qt4 and qt5 Qz versions? (Qualys SSL Labs test.)

**Comment by JHooverman** [comment]
@pejakm: I have added references to my previous post to show, which version have been used for the Qualys SSL Test:

(1) QupZilla 1.8.5, Qt version 4.8.6, WebKit version 537.21, `Disable SSL3` checked
(2) QupZilla 1.9.0 (c1901cd), Qt version 5.4.1, WebKit version 538.1, `Disable SSL3` unchecked
(3) QupZilla 1.9.0 (c1901cd), Qt version 5.4.1, WebKit version 538.1, `Disable SSL3` checked

I hope, this will properly describe the test.

**Comment by cranes-bill** [comment]
I have that, in case you are interested:

QupZilla 1.9.0; Qt version 5.4.0; WebKit version 538.1
```
Protocols
TLS 1.2	Yes
TLS 1.1	No
TLS 1.0	No
SSL 3	No
SSL 2	No
```

QupZilla 1.9.0; Qt version 4.8.6; WebKit version 537.21
```
Protocols
TLS 1.2	No
TLS 1.1	No
TLS 1.0	Yes
SSL 3	No
SSL 2	No
```

**Comment by pejakm** [comment]
@JHooverman, I was thinking on what @cranes-bill just commented. :)

**Comment by JHooverman** [comment]
@pejakm: I guessed, that you're gonna say that ;-)

**Comment by pejakm** [comment]
This is what I'm talking about:

https://a.pomf.se/dctiyv.png

QtTestBrowser has *TLS 1.0*, *TLS 1.1* and *TLS 1.2* enabled, while QupZilla has only *TLS 1.2* enabled. I'm not sure what's the status with 1.0 and 1.1, but if they're still safe, I think they need to be enabled in QupZilla.

**Comment by JHooverman** [comment]
@pejakm: TLS 1.0 is affected by the [BEAST](https://community.qualys.com/blogs/securitylabs/2013/09/10/is-beast-still-a-threat) attack

**Comment by nowrep** [comment]
Uncheck the "Disable SSLv3" checkbox. I will make it disabled by default.

**Comment by pejakm** [comment]
@JHooverman Yes, but as I understand, it is a client side vulnerability (and I think qtwebkit already addressed it). I'll build QupZilla with only TLS 1.0 and test it.

**Comment by JHooverman** [comment]
@nowrep: If `Disable SSL3` is unchecked, the Qualys Test reveals, that TLS 1.0 and SSL3 are active.

![tls](http://i.imgur.com/6bnR8YJ.png)

To my mind it should be possible to enable/ disable SSL3, enable/ disable TLS 1.0 and TLS1.1/ 1.2 separately - if possible. Please note that checking `Disable SSL3` in QupZilla compiled against Qt-4.8.6+qtwebkit 537.21 does not seem to work.

**Comment by pejakm** [comment]
> and I think qtwebkit already addressed it

It looks like it didn't, according to https://www.howsmyssl.com:

http://a.pomf.se/ywqpgu.png

**Comment by JHooverman** [comment]
So, I think of two options for implementing of SSL/ TLS configuration:

(1) Checkbox for each protocol
enable/ disable SSL3
enable/ disable TLS 1.0
enable/ disable TLS1.1/ 1.2
I personally like this, but for most of our users this might be too complicated.

(2) "Mode"-based

Compatibility mode: Same as current implementation `Disable SSL3` unchecked (activate TLS1.2+1.1+1.0+SSL3). However, we should inform the users, that this mode is unsecure and dangerous (BEAST + POODLE)
Secure mode: Same as current implementation `Disable SSL3` checked (activate TLS1.2). Maybe we can enable TLS1.1 + 1.2 in this case.

**Comment by nowrep** [comment]
Yeah well, the issue is that it is not possible...

**Comment by cranes-bill** [comment]
I'm lost here...
How you can enabled and disabled in the source, but this affected Qt 5 only!?
And is it not possible, V 1.2 to be enabled on Qt 4 as well?

**Comment by pejakm** [comment]
> And is it not possible, V 1.2 to be enabled on Qt 4 as well?

Qt4 only supports TLS 1.0.

**Comment by cranes-bill** [comment]
But if i uncheck „Disable SSL3“, „SSL Labs test“ reports: „TLS 1.2 Yes“ !?!?!

**Comment by pejakm** [comment]
> But if i uncheck „Disable SSL3“, „SSL Labs test“ reports: „TLS 1.2 Yes“ !?!?!

With Qt4?

**Comment by cranes-bill** [comment]
Yes, when „Disable SSL3“ is unchecked, that's showing:
```
Protocols
TLS 1.2	Yes
TLS 1.1	Yes
TLS 1.0	Yes
SSL 3	Yes
SSL 2	No
```

**Comment by pejakm** [comment]
That's expected.

**Comment by JHooverman** [comment]
@pejakm: This is confusing for me. From the previous posts I got this information:

* @pejakm: Qt4 only supports TLS 1.0
* QupZilla compiled against Qt-4.8.6 and `Disable SSL3` unchecked gives TLS 1.0/ 1.1/ 1.2 `yes` on Qualys verified by @cranes-bill
* @pejakm: That' expected

I would expect, that Qualys reports TLS 1.0 `yes` in case Qt4 only. Do I miss something?

**Comment by pejakm** [comment]
@JHooverman My bad, somehow I misread cranes-bill's comment. :D That's very strange, actually, I thought Qt4 only supports TLS 1.0...

**Comment by cranes-bill** [comment]
Yeah, that's what i failed  to understand and i asked [above](https://github.com/QupZilla/qupzilla/issues/1579#issuecomment-68605161). How it is possible both to give the same result when `Disable SSL3` __unchecked__, but to gives __quite different result when it checked__!? Both are compiled from the same source.

**Comment by nowrep** [comment]
Uncheck the "Disable SSLv3" checkbox. I will make it disabled by default.

**Comment by JHooverman** [comment]
@nowrep: Do you have an idea, why the Qualys SSL test gives TLS 1.2 support = `yes` with Qt4, although, Qt4 does not support TLS 1.1/ 1.2?

Second: If `Disable SSLv3` is unchecked by default, you might think about renaming this option maybe to "Compatibility mode". Users will probably not understand, why `Disable SSLv3` is unchecked (this parameter is supposed to avoid POODLE attacks).

**Comment by cranes-bill** [comment]
JHooverman said:
>Do you have an idea, why the Qualys SSL test gives TLS 1.2 support = yes with Qt4, although, Qt4 does not support TLS 1.1/ 1.2?

That's the question, that i also still need a answer! And if really Qt4 can support TLS V.1.2, is it possible to be the same as Qt5 as `Disable SSL3` is __checked__, or in other worlds, to allow __V.1.2 only__?

**Comment by nowrep** [comment]
Both Qt4 and Qt5 supports TLS 1.2, because it is provided by OpenSSL.
By default, both Qt4 and Qt5 will try to use best protocol supported by the server (that is TLS 1.2 -> 1.1 -> 1.0 -> SSLv3).
But the difference is that Qt 4 only allows to force TLS 1.0, and Qt 5 allows to force all versions of TLS.

Anyway, forcing the specific version of TLS is not good solution at all, because if the server doesn't support this specific version, the secured connection would fail.
In other words, there is no support in Qt simply to "disable SSLv3".

**Comment by cranes-bill** [comment]
OK, thank you!

**Comment by pejakm** [comment]
I suggest closing this issue as **wontfix**.

**Comment by JHooverman** [comment]
It seems, that a safe way is strongly limited by the Qt-capabilities. 

For me the current implementation is reasonable with QupZilla-qt5. Checking `Disable SSLv3` will provide secure access to web-pages, unchecking it will enable SSL3 and TLS1.0, thus make QupZilla vulnerable for the BEAST and POODLE attack.

If I understood correctly, then setting `Disable SSLv3` checked or unchecked - will allow to access the specific web-page in both cases with QupZilla-qt4. However, unchecking `Disable SSLv3` will make QupZilla-qt4 vulnerable for the BEAST attack, checking it will make it vulnerable for the POODLE attack. So, in case Qt4 QupZilla is vulnerable anyway. This does not make feel comfortable.
