### ISSUE TITLE
[Question]About QtWebEngine and Plugin

### ISSUE THREAD

**Issue by RyanBram** [QupZilla/qupzilla#1582]
Hi, Qupzilla Developers,
I have 2 questions related to current Qupzilla features:

1. With migration from QtWebkit to QtWebEngine, does it mean Qupzilla will have bigger chance for supporting Chrome extension which currently isn't supported according to the FAQ?

2. About Videoner plugin, is it possible to use this plugin for downloading streamed video over internet, such as youtube.com? 

Regards

**Comment by pejakm** [comment]
[1] Unlikely.
[2] Yes (have a look at [wiki](https://github.com/QupZilla/qupzilla-plugins/wiki/Videoner).) For example, you could use `youtube-dl` for downloading directly or to pass URL to another program (the `-g` option).

**Comment by JHooverman** [comment]
In addition to @pejakm I would like to give you some more information.

1. In case, that QtWebEngine will support chrome-extensions, then the answer is in principle "yes". However, we will have to check the effort it will take to integrate them to QupZilla once QtWebEngine is usable for this. As you might have noticed QtWebengine is still under heavy development and it is hardly to predict, when this will be possible.

2. The Videoner-extension only enables the menu item `Videonize!` and passes the URL of a page to an external media-player. Thus, the extension cannot be directly used for downloading streamed content. However, as @pejakm stated, you might use an external application for this. Please consult the documentation of for example [youtube-dl](http://rg3.github.io/youtube-dl/documentation.html).

**Comment by RyanBram** [comment]
Hi, Pejaković and Jonathan,
Thanks for answering my questions.

Currently I am using Windows 7-64 bit. I tried to follow the instruction in [General Configuration wiki](https://github.com/QupZilla/qupzilla-plugins/wiki), but didn't find any way to install external plugins. If Videoner is built-in in Qupzilla, then I cannot find it in my Portable Qupzilla v1.8.5.

![no_videoner](https://cloud.githubusercontent.com/assets/4508389/5644843/9f0df686-969a-11e4-8215-3847bceb9a02.jpg)

**Comment by JHooverman** [comment]
@RyanBram: The videoner-extension is currently not built-in in QupZilla and will probably according to the main developer never be. If you had a linux-system the videoner-extension can be easily compiled and added to QupZilla- on windows this is a challenging task.

**Comment by RyanBram** [comment]
@JHooverman :
Ok, I understand that Videoner extension will never become built-in feature in Qupzilla. But I still hope the plugin will be provided as pre-build .dll binary to enrich Qupzilla extension library (Maybe http://addon.qupzilla.com will become good place).

**Comment by JHooverman** [comment]
@RyanBram: If it is fine with you, I will add the provisioning of a pre-build Videoner-extension as a feature request to qupzilla-plugins and close this issue. O.k.?

**Comment by RyanBram** [comment]
Of course it is perfectly fine.
Thanks, Jonathan for your attention to my questions and request. You may close this thread.

Best regard,
Ryan Bram

**Comment by JHooverman** [comment]
Closing this issue now.
