### ISSUE TITLE
Yet another theme

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#1583]
## [HERE](https://yadi.sk/d/mFx6fFtRdr7C9)
First of all, i have no very good skills with that so, sorry if i'm did something wrong!
Also it seems standard fonts path rule is not applicable here, so to be looking as on the screen shots, you must install the font, contained in subfolder „fonts“.
Enjoy!
![a propos de qupzilla](https://cloud.githubusercontent.com/assets/5161278/5666119/febb6fde-9765-11e4-8aee-958658c77886.png)
![0khqvdc40lzqutcwcg](https://cloud.githubusercontent.com/assets/5161278/5666123/04f08c7c-9766-11e4-8b29-7cd2301a1aef.png)
![0khqvdc40lzqutcwltek](https://cloud.githubusercontent.com/assets/5161278/5666126/085ae876-9766-11e4-8f76-982387f3cb5c.png)
![0khqvdc40lzqutcwltik](https://cloud.githubusercontent.com/assets/5161278/5666133/0c601f18-9766-11e4-9ef6-27037cb441bc.png)
TARBALL MD5 SUM: `a2a00f46dd9e83c7cf61e7506fb82739`

**Comment by srazi** [comment]
:+1:  Thanks

**Comment by JHooverman** [comment]
Looks very good! The forward and back buttons only appear, if there is a history for the specific tab. Very nice feature. Merci beaucoup!

@nowrep: Is it o.k. to add this theme to the themes section (qupzilla-plugins)?

**Comment by srazi** [comment]
@cranes-bill: What is the license of `Dexter.ttf`?

**Comment by nowrep** [comment]
@JHooverman Yes, that's what that repo is for. Of course, if @cranes-bill won't mind :-)

**Comment by cranes-bill** [comment]
You are welcome! I'm glad you like it! Appreciate it.
I've tested the theme few days before upload here, but on GTK2 - Gnome2 system only, so i have no idea how it will looks on different system (GTK3, KDE etc. {I don't care about Windows ;D} ), so i'm expects errors there.

@srazi: Actually i was downloaded this font from [here](http://www.ph4.ru/fonts_fonts.ph4), but was not looking for license information.

@nowrep: Did you read the license? ;-)
Seriously: feel free to do what you need with this theme.

**Comment by JHooverman** [comment]
I have added the theme to [qupzilla-plugins](https://github.com/QupZilla/qupzilla-plugins/tree/master/themes).
@cranes-bill: Thank you for your work. Please verify the licensing and the descriptions.

**Comment by cranes-bill** [comment]
Thank you very much! No verification needed. I'm sure you know what you are doing.

**Comment by JHooverman** [comment]
Please let me know, which images exactly (write down the names) you do not own and from which sources/ themes you took them from. Thank you!

**Comment by cranes-bill** [comment]
All symbols over the „buttons“ and standalone „png icons“ are from „Faenza icon theme“. I hope not full list is needed!? 
„`flashstart.png`“ are also from there, but i've changed the background and the name.
Few images are persist from nowrep's „Mac theme“.
„`brushed_metal.png`“ changed from me to „brushed_metal-l.png“, is from Nautilus „patterns“ - now owned by Mate.
And „navigation buttons“ background, i've used (also with changes) from „Audacity project“, which actually inspired me to make this theme.
As i understand from the licenses, i can do that, but as probably you already noticed, my English is very bad, so i hope i'm not missing something!

**Comment by cranes-bill** [comment]
Just to be clear. I've checked and those images are from previous theme, but they are also contained in more of the themes:
```
gotoaddress.png
search-icon.png
semi-transp.png
siteicon-bg.png
transp.png
```
Please tell me if have a problem with any other images and i will replace it.

**Comment by nowrep** [comment]
It should be ok, don't worry ;)
