### ISSUE TITLE
Encoding in Hovered link text

### ISSUE THREAD

**Issue by SafaAlfulaij** [QupZilla/qupzilla#1584]
Sorry for the bad title, I don't know what's the name of this small label at the bottom of the browser.
![qupzillahovering](https://cloud.githubusercontent.com/assets/3509617/5746773/43305a80-9c43-11e4-99c1-6fe761225d2f.png)
The text should be the same in the link tooltip. The address linetext shows the Arabic characters correctly.

**Comment by srazi** [comment]
There was a fix 5d48edc7a3bf78514238349b8afa2d9c96aeeb3e but it was reverted as a workaround for #1095.

**Comment by nowrep** [comment]
Actually, this "bug" is in various places, because what you see is a url encoded string.
But I agree that the hovered link tooltip should show decoded url (just like locationbar).

**Comment by nowrep** [comment]
And also this is already fixed with QtWebEngine.
