### ISSUE TITLE
Gmx.com webmail problem

### ISSUE THREAD

**Issue by abda11ah** [QupZilla/qupzilla#1585]
Hi,

After logged into gmx.com webmail, nothing is displayed under "file storage" and "organizer" tabs
my version: QUPZILLA 1.8.5 / WEBKIT 537.21

**Comment by JHooverman** [comment]
You can try two things:

(1) Change the user agent to Mozilla/5.0 (Windows 7; rv:24.0) Gecko/20131101 Firefox/24.1.0 via `Preferences -> Other -> User Agent Manager`
Some issues (please see #1507) can be solved this way.

(2) Try to update your qt/ qtwebkit to 5.4/ 538.1, please see #1473.

**Comment by JHooverman** [comment]
Closing this issue due to lack of response. Please feel free to re-open, if you have new information.

**Comment by abda11ah** [comment]
Works fine on qtwebkit 538.1 / Qupzilla 1.8.3

**Comment by JHooverman** [comment]
Thank you for reporting back!
