### ISSUE TITLE
Double Quotes (") interpreted to %22 when searching using URL Bar

### ISSUE THREAD

**Issue by frames** [QupZilla/qupzilla#1587]
When trying to search in the URL bar instead of the search bar, Qupzilla interprets double quotes (") as %22.  For example, when search, "media source extension", Google will search: %22media source extension%22'

Using latest Qupzilla version 1.8.5 in Manjaro Linux.

**Comment by JHooverman** [comment]
Confirmed.

Application version: 1.9.0 (c1901cd81d)
Qt version: 5.4.1
WebKit version: 538.1
Build time: Dec 28 2014 15:49:07
Platform: openSuSE Tumbleweed (Linux)

**Comment by cranes-bill** [comment]
Tested, that's one more Qt 5 issue.

**Comment by The-Compiler** [comment]
This is not a Qt issue most likely. I don't have time to look at the qupzilla code at the moment - but I'm developing my own Qt5-based browser, and searching for something with quotes works just fine here.

**Comment by nowrep** [comment]
This is NOT Qt issue, but it only occurs with Qt 5.
