### ISSUE TITLE
QupZilla is looking for hunspell in wrong place on FreeBSD

### ISSUE THREAD

**Issue by willbprog127** [QupZilla/qupzilla#1588]
On FreeBSD QupZilla looks for hunspell in the wrong place:

```
SpellCheck: Dictionaries for "/usr/share/hunspell/en_US" doesn't exists! (plugins/qtwebkit/spellcheck/speller.cpp:87, void Speller::initialize())
```
It should be looking in `/usr/local/share/hunspell`

QupZilla built with the following command:
```
QUPZILLA_PREFIX=/usr/local qmake -r "CONFIG+=release" "INCLUDEPATH+=/usr/local/include" "LIBS+=-L/usr/local/lib"
```

-

:information_source:
Build: 744a1d15be316770af153bdaf51413a245c374ce
Application version:  `1.9.0`
Qt version:  `5.3.2`
WebKit version:  `538.1`
Build time:  `Jan 20 2015 19:01:04`
Platform:  `BSD 4.4`
Browser Identification:
`Mozilla/5.0 (X11; FreeBSD) AppleWebKit/538.1 (KHTML, like Gecko) QupZilla/1.9.0 Safari/538.1`

**Comment by nowrep** [comment]
You can change it in spellcheck settings (right click in page at input element -> spellcheck -> settings)

**Comment by nowrep** [comment]
The path can't be always correct. Different linux distros are also using different path.

**Comment by nowrep** [comment]
Also, it does not make sense to use PREFIX for dictionaries path, because you might want to just install QupZilla to its own prefix while dictionaries are still in `/usr/share/`

**Comment by willbprog127** [comment]
@nowrep Thanks.  I found the settings under "right-click input element -> Language -> Settings"
