### ISSUE TITLE
Runs error Qupzilla 1.8.6 on Mageia linux x86_64

### ISSUE THREAD

**Issue by xlin** [QupZilla/qupzilla#1593]
Qupzilla not start on mageia 4 x86_64

[xlin@xlin-netbook ~]$ qupzilla %u
qupzilla: symbol lookup error: qupzilla: undefined symbol: _ZN2Qz7VERSIONE
[xlin@xlin-netbook ~]$ sudo ld /usr/bin/qupzilla
ld: ошибка в /usr/bin/qupzilla(.eh_frame); таблиц .eh_frame_hdr создана не будет.
ld: warning: cannot find entry symbol _start; defaulting to 0000000000402460

On mageia 4 i586 runs without errors. On this same system the previous version worked fine.

**Comment by JHooverman** [comment]
Did you compile QupZilla from sources or did you use a package provided by your distribution?

**Comment by xlin** [comment]
I took the finished spec file from the distribution and collected rpm package.

**Comment by cranes-bill** [comment]
Try to add ` QMAKE_LFLAGS+="-Wl,--as-needed"` after `%qmake_qt4` macro in spec file and see if something will change!

**Comment by xlin** [comment]
Added key that you suggested. The error persists. = (
qupzilla: symbol lookup error: qupzilla: undefined symbol: _ZN2Qz7VERSIONE

**Comment by cranes-bill** [comment]
Download [precompiled packages](http://packages.mageialinux.ru/mageia4/construct/RPMS/x86_64/) and see what's going on!

**Comment by xlin** [comment]
I am the system administrator of this repository =) And there are my packages. You are invited to download me what I myself did.

**Comment by JHooverman** [comment]
@xlin: Could you please post the spec-file on gist.github.com?

**Comment by xlin** [comment]
@JHooverman https://gist.github.com/xlin/c0746325310f6cc7da52

**Comment by JHooverman** [comment]
@xlin: Could you please post link, where you have downloaded QupZilla? Tomorrow I will compile & build QupZilla against Qt4 and I would like to make sure to have the same source.

**Comment by cranes-bill** [comment]
@JHooverman [That's](http://packages.mageialinux.ru/mageia4/construct/SRPMS/qupzilla-1.8.6-2.mga4.mrc.src.rpm) his source package, but i tried and it works to me. My guess that's an compiler or linker issue, or something in rpm utilities configuration is wrong.

@xlin
I'm wonder, why you provided in repository package, which failed to starts! Also i'm noticed just now (first post) - what you try to do with __ld__ on executable binary!? Do you actually understand what __ld__ does!? Perhaps you meant to use __ldd__, not __ld__!? No matter...

You can try [this](https://gist.github.com/anonymous/3ef51dee137505771342) spec file. This is just for testing. Please do not build source package with this file!

**Comment by xlin** [comment]
@cranes-bill I was wrong. Wanted to use it ldd. I'll try your spec file and write the result.

**Comment by cranes-bill** [comment]
@xlin
Now i remembered two more possible reason by this issue:
You might have two versions of some package installed on your system - check it!
And also, did you compiled QupZilla as root? If true, don't do that anymore! 
Perhaps, you already solved the problem, but missing to report here is not quite fair!
@JHooverman
In any cases, the problem is not in QupZilla, so in my opinion this issue can be closed.

**Comment by xlin** [comment]
The question is not yet settled. Not enough time to check.

**Comment by JHooverman** [comment]
Closing this issue due to lack of response. Please feel free to re-open, if you have new information.

**Comment by sevenfish** [comment]
Because it is linked to the system libQupZilla.so.1, try to remove it first.
sudo apt-get remove qupzilla
sudo apt-get autoremove
