### ISSUE TITLE
qmake error prevents building on FreeBSD

### ISSUE THREAD

**Issue by willbprog127** [QupZilla/qupzilla#1595]
QupZilla previously would build from git on FreeBSD with Qt5, however as of today, it does not build.  The error is:
```
Reading /usr/home/will/Downloads/qupzilla-git/qupzilla/src/lib/lib.pro
Project MESSAGE: ===========================================
Project MESSAGE: Using following defines:
Project MESSAGE: QUPZILLA_SHAREDLIBRARY QUPZILLA_VERSION=\"1.9.0\" QT_NO_URL_CAST_FROM_STRING QT_USE_QSTRINGBUILDER USE_QTWEBKIT_2_2 USE_QTWEBKIT_2_3 USE_LIBPATH=\"/usr/local/lib\" USE_DATADIR=\"/usr/local/share/qupzilla\" QZ_WS_X11
Project ERROR: Unknown module(s) in QT: webenginewidgets
```

The build commands (which worked previously):
```sh
export QUPZILLA_PREFIX=/usr/local

/usr/local/lib/qt5/bin/qmake -r "CONFIG+=release" \
                                "LIBS+=-L/usr/local/lib" \
                                "INCLUDEPATH+=/usr/local/include"
```
--

:information_source: 
Qt version: 5.3.2
Git version: c35b27e5906be54a236e3399f07b130fdcf3b331
OS: FreeBSD 10.1 - AMD 64

**Comment by willbprog127** [comment]
It appears that Qt WebEngine Widgets isn't available in Qt 5.3.2, so maybe adding more precision to the Qt version tests might help with this...?  Looks like this new feature appeared in Qt 5.4: http://doc.qt.io/qt-5.4/qtwebenginewidgets-module.html

**Comment by JHooverman** [comment]
Just to be sure: Did you try to build/ compile QupZillas qtwebengine branch? As you stated qtwebengine was introduced in Qt-5.4, thus it can not be compiled against your Qt-5.3.2.

**Comment by willbprog127** [comment]
@JHooverman I only built / compiled against the master branch.

**Comment by nowrep** [comment]
Please use v1.8 branch, master is now for QtWebEngine (you need Qt 5.4 for that)

**Comment by willbprog127** [comment]
@nowrep Thanks, I will do that.
