### ISSUE TITLE
crash when opening an etherpad-lite site

### ISSUE THREAD

**Issue by dora71** [QupZilla/qupzilla#1599]
QupZilla crashes when opening an internet site that hosts an etherpad lite installation, e. g. http://pad.trolug.de/trolug-2015-02. It is possible to open the start page, but if you try to start a pad, then it crashes. etherpad-lite is hosted on github here: https://github.com/ether/etherpad-lite

**Comment by The-Compiler** [comment]
What Qt version are you on? (See Help > About Qt)

No issues here on Archlinux with Qt 5.4.

**Comment by dora71** [comment]
It is the Qt version 4.8.1, OS: Linux Mint 13 (Maya) with MATE Desktop. Qupzilla is version 1.8.6, got it from the launchpad Repository of nowrep as there has been no packages in the Mint repos for Qupzilla.

I tested it on Linux Mint 17, there are packages available already in the installed repos and it runs without problems. Qt-Version: 4.8.6, Qupzilla version: 1.6.0.

**Comment by dora71** [comment]
Here is the Crashlog, hope it helps:

Time: Fri Jan 30 10:54:41 2015
Qt version: 4.8.1 (compiled with 4.8.1)
QupZilla version: 1.8.6
WebKit version: 534.34

============== BACKTRACE ==============
#0: qupzilla() [0x804a852]
#1: [0x926400]
#2: /usr/lib/i386-linux-gnu/libQtCore.so.4(_ZN9QIODevice4readEPcx+0x2a) [0x5e981a]
#3: /usr/lib/i386-linux-gnu/libQtCore.so.4(_ZN9QIODevice4readEx+0x1ca) [0x5ea1ca]
#4: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xec4027) [0x1d1e027]
#5: /usr/lib/i386-linux-gnu/libQtCore.so.4(_ZN9QIODevice4readEPcx+0x159) [0x5e9949]
#6: /usr/lib/i386-linux-gnu/libQtCore.so.4(_ZN9QIODevice4readEx+0x1ca) [0x5ea1ca]
#7: /usr/lib/i386-linux-gnu/libQtCore.so.4(_ZN16QIODevicePrivate4peekEx+0x45) [0x5ea2b5]
#8: /usr/lib/i386-linux-gnu/libQtCore.so.4(_ZN9QIODevice4peekEx+0x36) [0x5eb286]
#9: /usr/lib/i386-linux-gnu/libQupZilla.so.1(_ZN14NetworkManager13createRequestEN21QNetworkAccessManager9OperationERK15QNetworkRequestP9QIODevice+0x307) [0x285fb7]
#10: /usr/lib/i386-linux-gnu/libQupZilla.so.1(_ZN19NetworkManagerProxy13createRequestEN21QNetworkAccessManager9OperationERK15QNetworkRequestP9QIODevice+0x6f) [0x28e32f]
#11: /usr/lib/i386-linux-gnu/libQtNetwork.so.4(_ZN21QNetworkAccessManager4postERK15QNetworkRequestP9QIODevice+0x28) [0x29b3a98]
#12: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xec3628) [0x1d1d628]
#13: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xec5e19) [0x1d1fe19]
#14: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xec4a8a) [0x1d1ea8a]
#15: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xec4af3) [0x1d1eaf3]
#16: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xec5444) [0x1d1f444]
#17: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xebfe3d) [0x1d19e3d]
#18: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xd66478) [0x1bc0478]
#19: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xcab189) [0x1b05189]
#20: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xcb1309) [0x1b0b309]
#21: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xcb193f) [0x1b0b93f]
#22: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0x1167f22) [0x1fc1f22]
#23: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0x116ac04) [0x1fc4c04]
#24: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0x116b0d4) [0x1fc50d4]
#25: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xcb7174) [0x1b11174]
#26: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xea7036) [0x1d01036]
#27: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0xea7a95) [0x1d01a95]
#28: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0x984a63) [0x17dea63]
#29: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(_ZN7WebCore37jsXMLHttpRequestPrototypeFunctionSendEPN3JSC9ExecStateE+0x6f) [0x168744f]
#30: [0x331e349]
#31: /usr/lib/i386-linux-gnu/libQtWebKit.so.4(+0x124a81f) [0x20a481f]

**Comment by JHooverman** [comment]
@dora71: Thank you for your backtrace. However, qtwebkit-534.34 (equals 2.2) has been superseded by qtwebkit-537.21 (equals 2.3)/ Qt4 and qtwebkit-538.1/ Qt5 respectively. Thus, it is very unlikely, that is issue will be solved upstream - even in case it will be reported.

I recommend, that you upgrade your system at least to

QupZilla-1.8.6 + Qt-4.8.6 + QtWebKit-537.21/ 2.3
better would be
QupZilla-1.8.6 + Qt-5.4.1 + QtWebKit-538.1

I am closing this issue.
