### ISSUE TITLE
Issues with and questions about QtWebengine

### ISSUE THREAD

**Issue by AcarBurak** [QupZilla/qupzilla#1600]
Free feel to close this if you (understandably) don't want be bothered by noise about an unstable/experimental version. If not:

I've successfully installed the qupzilla-webengine-git from AUR on Manjaro Linux editing the pkgbuild and removing kde/gnome dependencies and related building options. After all why install gtk (let alone gnome) while there're already two fully featured browsers depending on it (Firefox and Chromium)? And why install KDE since I only need a qt web browser for my (thanks to lightweight WMs/DEs) unbloated, minimalistic, functional and stable desktop. Now aside from this rant:

1. Some entries in Preferences are greyed out: Browsing, Fonts, Password Manager, Privacy, Extensions and Other.

2. Obviously I can't use password manager. In future releases will this change or will Qupzilla-Webengine be dependant on kde/gnome for such features from now on?

3. I don't know what to do with flash content (haven't tried yet the videonizer, but some interactive flash content requires flash) as the related entry in Preferences is greyed out and qupzilla:about and qupzilla:config pages aren't loaded. Besides I'm not sure if/how it's possible to use chromium-pepper-flash?

4. After I open and close the Preferences window Qupzilla refuses to load any wep pages leaving me with a black browser window.

5. Will QtWebengine make it possible to edit bookmarks in line, i.e. adding, deleting, moving bookmark by right-clicking on or dragging the bookmark in the drop down windows? And will alternative bookmark sortings be possible (latest added first, for instance)?
Thank you.

**Comment by AcarBurak** [comment]
Embarrassed by the info from FAQ;

>Please keep in my mind, that this branch is experimental and not every feature, that you might know from QupZilla 1.8.x, is available. Due to this fact please do not open issues for this branch on the issue tracker!

Please close this.

**Comment by JHooverman** [comment]
Just some remarks:

@AcarBurak wrote: After all why install gtk (let alone gnome) while there're already two fully featured browsers depending on it (Firefox and Chromium)?

_As far as I know, the gnome dependancy is caused by libflashplayer. Just type_ `ldd /path/to/libflashplayer.so` _in a terminal on your system and you will discover a dependancy to  libgtk for example._

@AcarBurak wrote: And why install KDE since I only need a qt web browser for my (thanks to lightweight WMs/DEs) unbloated, minimalistic, functional and stable desktop.

_The KDE dependancy is needed, when you use the [KWalletPasswords-Extension](https://github.com/QupZilla/qupzilla-plugins/wiki/KWallet-Passwords)._

**Comment by AcarBurak** [comment]
Yes, they're meant to do something, but the stable Qupzilla (with Webkit) doesn't depend on them and works. They can only be optional dependencies; it's up to the user if s/he wants to use and install flash. I know no other browser except Chromium (with built-in flash) depends on it or kwallet, but I should tell this to the maintainer of the AUR package.

And libflashplayer.so doesn't require GTK; it does if one installs it from the repo, but not if s/he just downloads flash archive and after uncompressing puts it in the relevant place(es). This is how I've used it with Firefox (and Qupzilla I guess), but now, since yesterday I use Chromium in absence of an improved QtWebengine.

**Comment by nowrep** [comment]
It's okay to open bugreports for QtWebEngine branch. But please don't open issues for every feature missing, only if you really think you found a bug. Thanks

**Comment by JHooverman** [comment]
@nowrep: Which of the issues (1) to (5) is considered as a bug? Probably (4)?

**Comment by nowrep** [comment]
Yes, definitely 4. But I can't reproduce it myself.

**Comment by AcarBurak** [comment]
I can't reproduce it any more myself as well.

**Comment by nowrep** [comment]
I am now working on it and I think this issue can be closed. Basic password manager is now working.

**Comment by AcarBurak** [comment]
Thank you.
