### ISSUE TITLE
Full screen HTML5 video is missing controls

### ISSUE THREAD

**Issue by Sami-Perkele** [QupZilla/qupzilla#1602]
HTML5 videos ([this](http://www.jwplayer.com/html5/fullscreen/) for an example) play fine in full screen, but there is no controls visible. Controls are visible when not full screened.

Up-to-date Manjaro Linux (testing) with:
qupzilla (qt5) 1.8.6
qt5-webkit 5.4.0

Also, when the full screen mode is enabled (clicking the full screen button on the video controls) without the video playing, the browser starts to hang.

**Comment by JHooverman** [comment]
@The-Compiler: I was able to reproduce this issue with

Application version: 1.9.0 (ee80b04a11)
Qt version: 5.4.2
WebKit version: 538.1
Build time: Feb 7 2015 13:56:17
Platform: openSUSE Tumbleweed (Linux)

And yes, full screen mode with html5 works for me with the [link](http://www.jwplayer.com/html5/fullscreen/) provided above.
This is contrary to downstream bug #1127 and upstream bug [#43625](https://bugreports.qt.io/browse/QTBUG-43625).

What would you suggest? Close upstream bug [#43625](https://bugreports.qt.io/browse/QTBUG-43625) and create a new one? Attach this downstream issue?

Does full screen mode work for you?

Thank you for your advise.
