### ISSUE TITLE
Crash everytime after sleeping under win8.1 since 1.8.x

### ISSUE THREAD

**Issue by jiuzhege** [QupZilla/qupzilla#1608]
1.8.1 to 1.8.6 has the same problem on my laptop crashing everytime after sleeping for all night.

I have to downgrade to 1.6.6 to ‘solve' the crashing problem.

How can I know what exactly happened during the sleeping?

**Comment by nowrep** [comment]
This should be fixed in 1.8.8. If not, please reopen the issue.
