### ISSUE TITLE
Trouble compiling Qupzilla development branch since Initial port to QtWebEngine

### ISSUE THREAD

**Issue by slicer69** [QupZilla/qupzilla#1609]
I download the Qupzilla 1.9.0 development branch about once a month, build and install it. Since the "Initial port to QtWebEngine" commit at the end of January, I have been unable to build Qupzilla from source code. Since that commit, when I perform a "make clean && make" in the qupzilla directory I receive the following error message

cd src/lib/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/jesse/Code/qupzilla/src/lib/lib.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory `/home/jesse/Code/qupzilla/src/lib'
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile lib.pro
Project MESSAGE: ===========================================
Project MESSAGE: Using following defines:
Project MESSAGE: QUPZILLA_SHAREDLIBRARY QUPZILLA_VERSION=\"1.9.0\" QT_NO_URL_CAST_FROM_STRING QT_USE_QSTRINGBUILDER USE_QTWEBKIT_2_2 USE_QTWEBKIT_2_3 USE_LIBPATH=\"/usr/lib/x86_64-linux-gnu\" USE_DATADIR=\"/usr/share/qupzilla\" GIT_REVISION=\"7f27f95a1a\" QZ_WS_X11
Project ERROR: Unknown module(s) in QT: webenginewidgets
make[1]: *** [Makefile] Error 3
make[1]: Leaving directory `/home/jesse/Code/qupzilla/src/lib'
make: *** [sub-src-lib-make_first] Error 2

If I revert to the January 21, 2015 commit, titled "Import TabManager plugin from qupzilla-plugins", then Qupzilla builds and runs without any problems.

I a building Qupzilla on a 64-bit Ubuntu 14.04 LTS installation. If any further information can be of use, please let me know. For now, I'd appreciate knowing if there is a new library dependency I am missing? It seems the "make" process is dying before we get to the compiling phase, so I suspect I'm missing a Qt5 library. Any suggestions on how to resolve the above error would be appreciated.

**Comment by nowrep** [comment]
Use `v1.8` branch.

**Comment by slicer69** [comment]
Thank you, I will try that.
