### ISSUE TITLE
Cursor blink on unexpected place inside page

### ISSUE THREAD

**Issue by kulti** [QupZilla/qupzilla#1615]
Steps to reproduce:
Open google.com and click near left search button.

Actual:
Cursor disappear from search input field.
Cursor appear on the left side of search button.

Expected:
Cursor disappear from search input field and not appearing on other place inside page

Tested with:
Application version 1.8.6
WebKit version 538.1

Simple webkit browser works fine

**Comment by JHooverman** [comment]
Would you please provide a screen-shot, where to click exactly? I am currently not able to reproduce your issue.

**Comment by kulti** [comment]
@JHooverman  You can also try to click issue name on this page (e.g. on word 'unexpected') to see cursor. If nothing happened - try to switch tab and turn back.

Sample video: https://yadi.sk/i/fxzlreTqf3Nr8

**Comment by JHooverman** [comment]
Once my ffmpeg will work again, I will create a screencast, which reveals, that I do not have this issue - which unfortunately will not solve your issue. Will it be possible for you to change the cursor/ mouse theme for testing?

**Comment by kulti** [comment]
@JHooverman I believe, that you cannot reproduce this issue. I looks like all elements on page is texedit widget with disabled editing. If you have not any idea about reason of this behavior - please close this issue as CANNOTDUP.

**Comment by JHooverman** [comment]
@all: Is maybe someone else able to reproduce this issue?

@kulti: Did you try to change the cursor/ mouse theme for testing?

**Comment by kulti** [comment]
@JHooverman It's not about mouse cursor. It's editing cursor.

Also I have another problem with edit cursor:
Sometimes it's not showed inside textedit, and appear after switch tabs.

**Comment by srazi** [comment]
@kulti: It seems to me that you have `Caret Browsing` enabled. (`View->Caret Browsing` or press F7)

**Comment by kulti** [comment]
Wow! Really strange feature for me =) Thanks.
