### ISSUE TITLE
BookmarksToolbarButton Is Style Unfriendly.

### ISSUE THREAD

**Issue by tsujan** [QupZilla/qupzilla#1617]
I'm a Linux user and use theme engines for styling Qt4/Qt5 apps.

BookmarksToolbarButton in QupZilla-1.8.6 is a QPushButton but has incomplete and incorrect hard-coded style. Incorrect because it uses QStyle::PE_PanelButtonTool, which is for toolbuttons. Incomplete because, even if the behavior of an auto-raised toolbutton is expected from it, it is NOT an auto-raised toolbutton, it refers to QStyle::PE_PanelButtonTool only when under the cursor (while all states are considered with QStyle::PE_PanelButtonTool) and its text is empty (b->text().isEmpty() returns true).

As a result, it cannot be correctly styled by theme engines. It may seem OK with Qt's default style plugin or with theme engines that don't use different text colors for different widget states but if the theme engine uses different background and text colors for different button states (normal, pressed, under cursor), problems arise.

Why not subclassing QToolButton in a consistent way instead?

**Comment by nowrep** [comment]
Because this way it looks best in the majority of styles (including Windows that was the biggest pain).
I don't really remember what exact issues were there, but it was a lot of work to find a good compromise across all styles.

**Comment by tsujan** [comment]
Thank you for the quick reply! And I fully understand what you mean by "pain" and "a lot of work".
This issue is not a big deal; I just wanted to pinpoint it.

**Comment by tsujan** [comment]
I close this issue because I implemented a simple workaround for such cases in my theme engine (KNotes also drew its close pushbutton as toolbutton).

**Comment by nowrep** [comment]
Thanks. 
I'd be more than happy to fix it properly, but as I said above, unfortunately the current code is what seems to work best with most of the styles.
