### ISSUE TITLE
RSS feed at bookmarks toolbar?

### ISSUE THREAD

**Issue by sspphheerraa** [QupZilla/qupzilla#1620]
Hello,
Is it possible to make rss feeds customizable like in firefox? I mean pop-up menu at bookmarks toolbar:
http://i.piccy.info/i9/2501c3c0e8c7d9baca63fa4b76308417/1425751677/51368/789906/8.png

**Comment by GreenLunar** [comment]
I think not, but I am interested in such feature.

**Comment by JHooverman** [comment]
Unfortunately there will be no more enhancements added to the RSS module, see #1007.

**Comment by GreenLunar** [comment]
Do reconsider this!

On recent versions 40 and above updates Mozilla has omitted the ability for end-users to see what is the actual address of a Live Bookmark bookmark; Mozilla will remove RSS support entirely, for money makes it go round and round ;-)

Do a serious reconsideration.
