### ISSUE TITLE
QupZilla is vulnerable for Freak

### ISSUE THREAD

**Issue by psyca** [QupZilla/qupzilla#1621]
https://freakattack.com/
shows that Qupzilla is vulnerable for the Freak securityhole.

**Comment by jschuck** [comment]
I got the same report on the newest windows version.

Version 1.8.6
WebKit- Version 537.21

However my linux version is not vulnerable:
QupZilla-Version: 1.8.6
WebKit-Version: 538.1

The problem does not lie with QupZilla per se, but rather with an older webkit version packaged with it.

For Windows that probably means a newer Download bundled with newer Qt libraries. Linux probably fixes itself if it hasn't already.

**Comment by nowrep** [comment]
This should be fixed with newer OpenSSL, not QtWebKit.

**Comment by jschuck** [comment]
My bad.

**Comment by psyca** [comment]
Ok. I tested it with another distribution version and it says its ok.

**Comment by psyca** [comment]
Woops. Reopen becouse Comment #2

**Comment by nowrep** [comment]
Will be fixed in new build.
