### ISSUE TITLE
Double-byte white space containing phrase can't do well in address bar search.

### ISSUE THREAD

**Issue by matcha-zaq** [QupZilla/qupzilla#1622]
This bug can reproduce in the following way.
1. Put phrase "日本　観光" in address bar and press Enter key.
2. You will get "Server not found" instead of expected search results.

I think this bug occurred because that phrase contains double-byte white space "　".
This idea comes from the following trial.
1. Put phrase "日本 観光" in address bar and press Enter key.
2. You can get expected search results.

This result suggests double-byte white space cause this problem.

This issue occurred in both Google search and DuckDuckGo search.

My environment is Linux(openSUSE 13.2 32bit) with KDE in Japanese and using QupZilla version is 1.86.
I confirm that this bug also happens in both Windows7(32bit Japanese) and Windows8.1(64bit Japanese) through PortableApps.com Platform.

**Comment by JHooverman** [comment]
Which key(s) do you press to generate a double-byte white space?

**Comment by matcha-zaq** [comment]
I think English keyboard doesn't have such a key and most people in the world aren't familiar with a double-byte white space without  installing IME (Input method editor).
In Japanese keyboard, there is a "半角/全角" key which enables us to switch the input method single-byte one or double-byte one.

So I suggest copy and paste and show examples of search words below.

" "       <--- this is a single-byte white space.
"　"     <--- this is a double-byte white space.
"日本 観光"  <--- this is a search phrase which contains a single-byte white space.
"日本　観光" <--- this is a search phrase which contains a double-byte white space.

**Comment by nowrep** [comment]
Thanks for the report.
