### ISSUE TITLE
Qupzilla unexpectedly terminated

### ISSUE THREAD

**Issue by divyamuthyala** [QupZilla/qupzilla#1623]
Crashed :( Saving backtrace in /.config/qupzilla/crashlog ...
Backtrace successfuly saved in /.config/qupzilla/crashlog/Crash-2015-03-13T10:40:39.txt

**Comment by JHooverman** [comment]
Please let us know about your QupZilla version & OS and what you did before QupZilla crashes. As a reference please use our [bug-reports-wiki](https://github.com/QupZilla/qupzilla/wiki/Bug-Reports).

**Comment by divyamuthyala** [comment]
my qupzilla version is 1.8.6 and i just opened following url
http://tsdevop4.bitlasoft.com/offlinetest/userprint.html


when iam trying to open this url and saving file qupzilla is terminating...plz give a solution to this issue...

**Comment by JHooverman** [comment]
Could you please post the content of /.config/qupzilla/crashlog/Crash-2015-03-13T10:40:39.txt to gist.github.com?

**Comment by cranes-bill** [comment]
I [can](https://gist.github.com/anonymous/2212026a40cd67264b37) :-D

**Comment by JHooverman** [comment]
I have filed an upstream bug for this, see https://bugreports.qt.io/browse/QTBUG-45142

**Comment by divyamuthyala** [comment]
how can overcome this issue......how url wrk with qupzilla....can u give me a complete solution to this ????
Thanku in advance.....

**Comment by JHooverman** [comment]
@divyamuthyala: This issue is caused by an upstream bug in QtWebKit, which cannot be solved in QupZilla. To overcome this issue you might want to upgrade to Qt-5.4, which is not affected.

**Comment by divyamuthyala** [comment]
how to enable icu package for  qt5.4.0  configuration for arm version?????

**Comment by cranes-bill** [comment]
You should append `-icu` option, when run `./configure` script.

**Comment by divyamuthyala** [comment]
I did  by appending icu while configuring ......but icu was not enabling.......my error is.....
ICU disabled.
The ICU library support cannot be enabled.
I configured by .....
./configure -opensource -confirm-license -opengl es2 -device linux-imx6-g++ -directfb -eglfs -device-option CROSS_COMPILE=/u01/freescale/usr/local/gcc-4.6.2-glibc-2.13-linaro-multilib-2011.12/fsl-linaro-toolchain/bin/arm-none-linux-gnueabi- -sysroot /u01/rootfs -no-gcc-sysroot -I/u01/rootfs/usr/include  -L/u01/rootfs/usr/lib -lz -qt-freetype -qt-xcb  -licuuc -licule -icu -v


plz give me solution  that, how to enable icu library support while qt5 configuration.......

Thanks in advance...........

**Comment by cranes-bill** [comment]
It seems you have missing any ICU development files installed.

**Comment by divyamuthyala** [comment]
I compiled ICU source for arm version and  I copied lib  and include directories   to rootfs,then how can i miss ICU development files installed...........can u explain in deatail how to configure qt5.4.0 with webkit module ?????

Thanks in advance........

**Comment by cranes-bill** [comment]
Check [this](http://thebugfreeblog.blogspot.de/2013/05/cross-building-icu-for-applications-on.html) thread might help!

**Comment by divyamuthyala** [comment]
i followed your thread to install......still it was getting ICU disabled....
Can you please solution  to this problem????
Thanks in advance

**Comment by divyamuthyala** [comment]
Iam configuring ICU for arm version.....ICU version is  6.2.14 ........iam configuring by 
"./configure --prefix=/root/device-icu/arm_icu_installed --exec-prefix=/root/device-icu/arm_icu_installed --host=arm-none-linux-gnueabi --with-cross-build=/root/device-icu/arm_icu_installed"....
Problem uiam facing while doing make.......Error iam facing is "LD_LIBRARY_PATH=../lib:../stubdata:../tools/ctestfw:$LD_LIBRARY_PATH  ../bin/genpname -d ./out/build/icudt32l
../bin/genpname: 1: ../bin/genpname: Syntax error: word unexpected (expecting ")")
make[1]: *** [out/build/icudt32l/pnames.icu] "

Can you please  give me a solution to this problem ??????
Thanks in advance............

**Comment by divyamuthyala** [comment]
Now i successfully   build ICU for arm by  browsing......
I copies llib folder and include folder in rootfs and iam trying to configure Qt-5.4.0 with ICU,during make iam  facing with error that is 
"tools/qtimezoneprivate_icu.cpp:145:49: error: 'ucal_clone' was not declared in this scope"....
"ucal_clone" was name of API which was already defined and declared.....issue is  it is not linking with that......
please find a solution to this???????
Thanks in advance.......

**Comment by JHooverman** [comment]
Since we have currently some activities upstream:

@divyamuthyala & @cranes-bill: Do you have any browser plug-ins installed? If so, which ones?

**Comment by HymiR** [comment]
Clicking at "download" on following link kills qupzilla-1.8.6 too.
http://box-look.org/content/show.php/Breeze-ob?content=169136
