### ISSUE TITLE
[File][Send Link...] Saves file instead of opening mail client

### ISSUE THREAD

**Issue by VikOlliver** [QupZilla/qupzilla#1625]
To reproduce go to any valid web page. Click "file" then in the drop-down menu click "Send Link..." .  The "Save As" file dialog will be displayed. It would be expected that the default e-mail client would be launched, with the URL of the current page in the e-mail body.

This is probably because in src/lib/app/mainmenu.cpp 
176:	void MainMenu::sendLink()

Invokes
178     if (m_window) {
179	        m_window->weView()->savePageAs();
180	    }

instead of

void WebView::sendLinkByMail()

**Comment by JHooverman** [comment]
Confirmed.

Application version: 1.9.0 (ee80b04a11)
Qt version: 5.4.2
WebKit version: 538.1
Build time: Feb 8 2015 10:30:39
Platform: openSUSE Tumbleweed (Linux)

**Comment by javierllorente** [comment]
Fix is now on v1.8 and master.
