### ISSUE TITLE
SAML request redirects time out

### ISSUE THREAD

**Issue by benklop** [QupZilla/qupzilla#1626]
Navigating to "https://vmware-com.socialcast.com/" fails to produce a login prompt in Qupzilla. I'm not certain why exactly - all other browsers I have tried redirect to the login dialog.  in QupZilla I get through a couple redirects and then eventually the connection times out redirecting the final time.

Note that you don't need to log in to the site to see this problem - the problem occurs while trying to display the login page.

**Comment by The-Compiler** [comment]
FWIW, I can't reproduce this with QupZilla 1.8.6 with Qt 5.4.1.

**Comment by benklop** [comment]
@The-Compiler really - I was using 5.4.1... maybe I hadn't done a git pull recently enough. I'll make a fresh build and try again. If I can isolate the actual commit that fixed this though, I'd be very pleased since my own Qt app is doing the same thing.

**Comment by The-Compiler** [comment]
Maybe you could use Wireshark or tcpdump to take a look at what's happening.

**Comment by benklop** [comment]
@The-Compiler that's a possibility, but the traffic is all ssl encrypted so if I want to see anything more than the fact that a connection occurred I will need to pass it through an sslbump proxy like http://wiki.squid-cache.org/Features/SslPeekAndSplice and capture the traffic there.

**Comment by JHooverman** [comment]
Works for me as well:

![im1](http://i.imgur.com/MqtrXlQ.png)

Did you try to change your user agent?
