### ISSUE TITLE
adx - addressbook.xml does not work

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1629]
On opening file addressbook.xml (when adx2html_phonelist.xsl is in same folder) I get the following message in QupZilla.

> IF YOU CAN READ THIS IN YOUR WEB BROWSER THEN XSL TRANSFORMATION IS DISABLED OR NOT SUPPORTED. PLEASE GO TO http://adx.elektronengehirn.net TO SEE SUPPORTED WEB BROWSERS.

http://adx.elektronengehirn.net
http://sourceforge.net/projects/adx/

**Comment by JHooverman** [comment]
Did you try the same with Firefox? What is the result?

**Comment by GreenLunar** [comment]
Yes, and it did work with Firefox.

**Comment by JHooverman** [comment]
Now it works for me in Firefox as well, I had to disable NoScript. What is your qt- and qtwebkit -version?

**Comment by GreenLunar** [comment]
Qt 4.8.5-i486-2 of Slackware 14.1.

Configuration Information
Information about version
Application version
1.8.6
Qt version
4.8.5
WebKit version
534.34
Build time
Mar 6 2015 14:14:03
Platform
Linux

**Comment by GreenLunar** [comment]
Is status *Waiting for feedback* still valid?

**Comment by nowrep** [comment]
XSLT is not supported in QtWebKit.
