### ISSUE TITLE
Setting as default browser

### ISSUE THREAD

**Issue by stheno** [QupZilla/qupzilla#1632]
When I click set as default it pops  awarning dialog off screen and I can't move it in view.
Pressing tab any number of times and enter does not set it as default.
I moved one of my monitors around in my monitor setting to see if I could locate the window and used Windows key shortcut to see if I could move the window itself. Nothing appeared.

(Windows 7 SP1 5 monitors)

**Comment by nowrep** [comment]
Can you please send screenshot with the issue?

@srazi Do you have any idea about this?
