### ISSUE TITLE
problemas para instalar qupzilla en Xubuntu

### ISSUE THREAD

**Issue by funcia** [QupZilla/qupzilla#1633]
Ejecutando apt-get update:
Err http://ppa.launchpad.net utopic/main i386 Packages                         
  404  Not Found
W: Imposible obtener http://ppa.launchpad.net/jon-severinsson/ffmpeg/ubuntu/dists/utopic/main/binary-i386/Packages  404  Not Found
E: Algunos archivos de índice fallaron al descargar. Se han ignorado, o se han utilizado unos antiguos en su lugar
_________________
Instalando qupzilla:

intentando sobreescribir `/usr/lib/i386-linux-gnu/qupzilla/libPIM.so', que está también en el paquete libqupzilla1 1.6.6-1
dpkg-deb: error: el subproceso copiado fue terminado por la señal (Tubería rota)
Se encontraron errores al procesar:
 /var/cache/apt/archives/qupzilla_1.8.6-1~utopic_i386.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Solution please?

**Comment by cranes-bill** [comment]
https://launchpad.net/~nowrep/+archive/ubuntu/qupzilla

**Comment by JHooverman** [comment]
Did you try to install QupZilla from the mentioned ppa? Does this work for you?

**Comment by funcia** [comment]
No he podido instalar qupzilla.
No funciona.

2015-04-10 12:14 GMT+02:00 Jonathan Hooverman <notifications@github.com>:

**Comment by JHooverman** [comment]
You did not let us know, what does not work for you. Please give some more details and describe them in English.

**Comment by JHooverman** [comment]
Closing this issue due to lack of response. Please feel free to re-open, if you have new information.
