### ISSUE TITLE
qupzilla 1.8.6 often crash on windows with many tabs

### ISSUE THREAD

**Issue by marakew** [QupZilla/qupzilla#1635]
some time just scroll page, or switch to an other page
some time it just runtime error

is it possible to get a debug build with pdb for debugging ?

**Comment by JHooverman** [comment]
You might want to look [here](https://github.com/QupZilla/qupzilla/wiki/FAQ#9-how-do-i-debug-qupzilla-in-case-of-a-crash). Many distributions already provide debug-builds, for example openSuSE. Please consult the documentation of your distribution.

**Comment by marakew** [comment]
sorry, but use the windows 7,
i can get backtrace under windows, but without debug symbol of qupzilla, it have no sense
so, i wish to get  build of qupzilla with debug symbols as pdb, but i can't build qupzilla under windows

**Comment by marakew** [comment]
without debug symbols, i catch 'access violation' indside QtWebKit4
VirtualAlloc return 0, and GetLastError ERROR_NOT_ENOUGH_MEMORY
in task manager i see, qupzilla take over 1.5Gb memory
may be memory leak ?

**Comment by JHooverman** [comment]
Maybe similar to #1605?

**Comment by srazi** [comment]
@marakew: Maybe it's about window handle limit per process that is 10,000. ([see](http://blogs.msdn.com/b/oldnewthing/archive/2007/07/18/3926581.aspx))

**Comment by marakew** [comment]
no #1605  because iam not use the search
no 10,000 limit, its much more :) only within ~30 tabs
i try to find which tabs produce this issue

**Comment by marakew** [comment]
well, it seems Global Social Dating Service http://mamba.ru/en/ produce this issues, i just search on site, and look at people
but memory always grow, at 1.4G qupzilla terminated
so under windows version of qupzilla 1.8.6, WebKit 537.21
may be developers  need to upgrate of webkit for windows build of qupzilla?
