### ISSUE TITLE
Analyze This ;-)

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#1636]
Hi, i'm here, again :blush:

So, due to my English, it will be very difficult to explain the problem and might be more difficult for you to understand me, but i will try:
So much time i was wonder the „KEY“ icon, where must showing and few days ago i got it - absolutely accidentally it was there, in the address bar. But it was never showing before, even i have two or more account for some sites. Trying to find a clue by this behavior, i only noticed that the web address where the „KEY“ icon was showed, do not ending in slash. So, is there any reason by that my guess, or i'm talking a quite nonsense?
Sorry, if the above is unreadable for you and do not hesitate to tell me!

**Version de l'application 1.8.6
Version de Webkit 537.21**

**Comment by JHooverman** [comment]
Would you please provide a screen-shot and at least one link, that will allow us to reproduce your issue?

**Comment by cranes-bill** [comment]
That is the problem. Browsing trought the history i can't find the page where the „KEY“ was appeared.
Nevertheless, now i can see i'm was wrong about the slash, because [this](http://zamunda.net/login.php) page (picture below), not ending in slash, but the „KEY“ also missing (i have two „login names“ there).

BTW, i decide to change the theme and here's what happened:
First selecting „Linux default“ and refreshing the page caused the „KEY“ to appears, but on the next refresh it disappeared again and does not appears anymore. So perhaps it's related to cache or .....!?

![zamunda net - qupzilla](https://cloud.githubusercontent.com/assets/5161278/7110382/a537758c-e1b8-11e4-8284-fc89f2bb46b5.png)

**Comment by cranes-bill** [comment]
It seems that's only to me issue, so it's no sense to stay open.
