### ISSUE TITLE
Updating Adblock?

### ISSUE THREAD

**Issue by meuwe** [QupZilla/qupzilla#1637]
Hi,

How long does it typiclly take for Adblock to update itself?

Also for the 'Update Subscriptions' you can click on, it would be nice if there was some type of progress shown for this, to know what it is going on.

Fanboy's Lists is shown for May 2013, I can't believe it's this old, something must be wrong here?

**Comment by nowrep** [comment]
Subscriptions should be updated every 5 days (https://github.com/QupZilla/qupzilla/blob/v1.8/src/lib/adblock/adblockmanager.cpp#L279). You can also force update with Options button -> Update subscription in AdBlock dialog.

If your subscription can't be updated, that would probably mean that the url of subscription is invalid.

**Comment by meuwe** [comment]
I don't use QupZilla that much, so when I open it, how long should it take before they are updated?

I also tried the; Options button -> Update subscription in AdBlock dialog., but you have  no way to know as an end-user what is going on...

I just have the Default Subscriptions; ```EasyList``` ```EasyPrivacy``` ```Fanboy's List``` 

Can you please tell me the dates on yours?

```EasyList``` = 27 March 2015
```EasyPrivacy``` = 27 March 2015
```Fanboy's List``` = 17 May 2013

**Comment by nowrep** [comment]
That means you either have wrong (old) url or Fanboy's List is no longer updated.

You will actually see if update was successful or not in subscription name ("error" or "updated" will be apended to the name).

**Comment by meuwe** [comment]
Technically speaking you can't say ```You``` have wrong URL because I don't have anything, because this is QupZilla and I haven't toched anything, QupZilla has wrong URL then...

So whatever is going on needs to be looked at by the Devs.

By the way, off topic here, but ABP sold out, and it's slower, taking up more resources as a browser addon...

Not sure what's happening with uBlock, no spilting off into uBlocko...

Also in Linux, I'm just getting tired of all these adblock addons, and all I'm using at the moment is just NoScript and I personally don't see any ad problems only using this addon.

PLEASE do not add in Adblock to QupZilla, Firefox or Chrome doesn't do this, you need to leave this up to the end-user to add it if they want it.

OR for those compiling from source a --disable-adblock, so it's not installed at compile time.

**Comment by kuraga** [comment]
:+1: for AdBlock disable option

**Comment by nowrep** [comment]
You can disable AdBlock in settings.

**Comment by JHooverman** [comment]
@kuraga: Please go for `Tools -> AdBlock` to enable/ disable AdBlock:

![adb](http://i.imgur.com/LO4Nd5r.png)

**Comment by JHooverman** [comment]
@meuwe: QupZilla uses this link as Fanboy subscription:

`http://www.fanboy.co.nz/adblock/fanboy-adblock.txt`

Visiting this link reveals, that this subscription has not been updated since April 2013:

![im1](http://i.imgur.com/aLf5U4b.png)

However, `https://www.fanboy.co.nz/` offers some new subscriptions you might want to add manually if required:

![im2](http://i.imgur.com/6V66q8O.png)

@nowrep. We should think about removing the Fanboy list or replacing it. What do you think?

**Comment by nowrep** [comment]
@JHooverman Yes, we should probably just remove it.

**Comment by meuwe** [comment]
I'm not taking about Disabling it in the settings.

Sorry, I'm just one of these compiling from source fanatics, meaning, one of the greatest benefits, given the options is to enable/disable at compile time. This is what I'd like to have the ability, a ```disable-adblock``` option;

```configure --disable-adblock```

This should not be a difficult request, and one I hope the DEVs will please fill. I do not want adblock built into QupZilla and installed at compile time...

thank you

**Comment by kuraga** [comment]
Yes, this is I was talked about, too.

**Comment by meuwe** [comment]
@kuraga, yes I understand, I was talking to nowrep who mentioned just turning off the option in the preferences.

**Comment by nowrep** [comment]
Well, there is no build option to disable AdBlock, and also there won't be one because it would be lot of unnecessary #ifdefs

**Comment by kuraga** [comment]
> It aims to be a lightweight web browser

and

> it would be lot of unnecessary #ifdefs 

really?

**Comment by The-Compiler** [comment]
I... really don't get this. What do you get from disabling Adblock at compile time, apart from your binary being a few bytes smaller, which hardly matters at all?

**Comment by kuraga** [comment]
My reply: I just was suprised. When I saw "lightweight" I thought either modular approach is implemented or... well, is planed maybe. Yes, "lightweight" is not equal to "modular" but I was suprised to read so confidenced declining idea of modular AdBlock.

**Comment by nowrep** [comment]
Yes, lightweight is not equal to modular and also not equal to less lines of code.
