### ISSUE TITLE
Absolute Profile Path?

### ISSUE THREAD

**Issue by arch-salix** [QupZilla/qupzilla#1642]
'qupzilla -p=/tmpfs/QupZilla' creates a relative profile directory in '~/.config/qupzilla/profiles' instead of at '/tmpfs/QupZilla'.  How to set an absolute profile path? Is there an option we can set in '~/.config/qupzilla/profiles/profiles.ini'? One workaround is 'qupzilla -p=../../../../../tmpfs/QupZilla' but that is not very elegant. 1.8.6 + Qt 5.4.1.

**Comment by nowrep** [comment]
This option is for specifying the profile to use by its name, not for setting an absolute path of profile.

**Comment by nowrep** [comment]
You can link the whole config dir `~/.config/qupzilla` to tmpfs
