### ISSUE TITLE
Can't access QupZilla preferences from menu (OSX)

### ISSUE THREAD

**Issue by devential** [QupZilla/qupzilla#1643]
The standard menu button for preferences as well as the keyboard sortcut (command + , ), opens the configuration information page (at qupzilla:config) instead of opening a preferences window. I am unable to change any preferences from that page, so this does not look intended. If there is an alternate way of accessing the preferences window or a way to edit preferences through configuration files, I'd also like to know. Thank you!

**Comment by JHooverman** [comment]
Duplicate to #1332?

@devential: Would you please let us know about QupZilla, Qt and QtWebkit-version (`Help -> Configuration information`)?

**Comment by nowrep** [comment]
This should be fixed in current git code, but unfortunately there haven't been any new build since then.

**Comment by devential** [comment]
apologies for the late reply, I'm running Version 1.8.2, WebKit version 538.1. I could do the build myself, if anyone could assist me how? I'm not too experienced with this.

**Comment by nowrep** [comment]
Fixed in latest version.
