### ISSUE TITLE
F12 or Ctrl + Shift + i doesn't close Web Inspector

### ISSUE THREAD

**Issue by LinkedList** [QupZilla/qupzilla#1645]
Hi, 
I am using QupZilla v1.8.6 with WebKit version 537.21 on Kubuntu 
and after Web Inspector is opened, F12 doesn't close it (or Ctrl + Shift + i).

Sometimes (I can't reliably reproduce it) the X button to close it is missing for me so there is no way for me to close developer tools other than closing the tab.

**Comment by nowrep** [comment]
Hmm, it would really help if you could find a reliable way to reproduce it.

**Comment by LinkedList** [comment]
I know it would but I can't find out how it happens. I think it has something to do with switching tabs.

However I found out about the missing X only because F12 doesn't close opened tools. I'd rather have it as a toggle (it's like that in FF and Chrome) than to close it with a mouse.
