### ISSUE TITLE
Question: Browser Information?

### ISSUE THREAD

**Issue by ghost** [QupZilla/qupzilla#1646]
Hi,

I was doing some online browser testing and I noticed these strings:

```Browser Information```
navigator.vendor: Apple Computer, Inc.
Info browser: name	safari

```Browser Capability Information```
Browser	Safari
Comment	Safari Generic
Parent	Safari Generic

userAgent with safari listed...

Using QupZilla in Linux, does it need to be reporting this information to work online correctly, Safari and Apple?

I personally don't get why ```navigator.vendor: Apple Computer, Inc``` or ```Info browser: name	safari```, why these need to be used in Linux?

**Comment by cranes-bill** [comment]
This is due to QtWebkit engine. If you want to change it, you should use „User Agent Manager“
![default](https://cloud.githubusercontent.com/assets/5161278/7323605/6b9494a0-eab8-11e4-9ac1-9b4e02267620.png)

**Comment by meuwe** [comment]
So what does QtWebkit engine have to do with calling things Apple and Safari?

QT is cross platform, but this is not looking very Cross Platform at all, more user specfic, like we're using a Apple product, and it's not...

Hmm

**Comment by cranes-bill** [comment]
I failed to understand what is your problem. The sites which detect QtWebkit engine, themselves recognize it any browser with this engine as Apple-Safari instead if this is not especially determined as different, which as i already said, you can do it in „User Agent Manager“
Anywhere in the QupZilla source is not written Apple or Safari.
Furthermore, QtWebkit engine as part of Qt actually is owned by Microsoft.

**Comment by JHooverman** [comment]
@meuwe: In what way did you "some online browser testing"? Did you call a page like `whatismyuseragent.com`?

**Comment by The-Compiler** [comment]
> Furthermore, QtWebkit engine as part of Qt actually is owned by Microsoft.

Uhm, no. Microsoft doesn't really have to do anything with (Qt)WebKit. Apple does though.

**Comment by nowrep** [comment]
That comes from WebKit and can't be changed.
