### ISSUE TITLE
QupZilla does not detect RSS feeds from cgit instances

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1647]
QupZilla does not detect web feeds from cgit instances, whereas Liferea does by inserting/suscribing to any of the following addresses:
http://git.fluxbox.org/fluxbox.git/ turns to http://git.fluxbox.org/fluxbox.git/atom/?h=master
http://slackbuilds.org/cgit/slackbuilds/ turns to http://slackbuilds.org/cgit/slackbuilds/atom/?h=master

**Comment by nowrep** [comment]
RSS support is no longer developed. See #1007
