### ISSUE TITLE
client certificate is not sent...

### ISSUE THREAD

**Issue by pierrenopicnic** [QupZilla/qupzilla#1648]
I'm not sure if it's a bug or a missing feature...
when I try to connect to my web site admin, in https, which required a client certificate, I get dumped with  a "connection untrusted" message. 
server-side, I use a self signed certificate. it works with firefox, IE, chrome, safari,... from linux, windows and mac for 15 years now!

with quppzilla, I have added my CA, (it appears well in the trusted CA list), and my client certificate to "local certificates". But I'm not sure "local certificates" means "clent certificate"!!!!

with other browsers, when I connect for the first time, I have a popup window asking which certificate I want to use.  here I have nothing. and server side, appache complains : "peer did not return a certificate"

so my question is : is quptzilla able to manage client side certificate?
and if yes,  how you do that?

ps I use  qupzilla 186 webkit 538.1 qt 5.4.1

**Comment by nowrep** [comment]
This is unfortunately impossible with QtWebKit (not sure about QtWebEngine though...)
