### ISSUE TITLE
cant compile qupzilla

### ISSUE THREAD

**Issue by neonano** [QupZilla/qupzilla#1649]
this is the log

dpkg-shlibdeps: failure: couldn't find library libQupZilla.so.1 needed by debian/qupzilla/usr/lib/qupzilla/libPIM.so (its RPATH is '').
Note: libraries are not searched in other binary packages that do not have any shlibs or symbols file.
To help dpkg-shlibdeps find private libraries, you might need to set LD_LIBRARY_PATH.
dh_shlibdeps: command returned error code 512
make: *** [binary-arch] Error 1
dpkg-buildpackage: failure: debian/rules binary gave error exit status 2

**Comment by nowrep** [comment]
There is no support to build with `dpkg-buildpackage`.
