### ISSUE TITLE
Browser crashing unexpectedly

### ISSUE THREAD

**Issue by shadow-warrior** [QupZilla/qupzilla#1650]
Problem . www.facebook.com  Crashes every time
procedure go to above address, log in, as page starts loading browser crashes
reproducable ...yes
 backtrace.......  http://pastebin.com/JxekUFd2

Application version 1.8.6
WebKit version 537.21
 qt4 version    4.8.6-5
 qtwebkit version 2.3.4-1  ( may be a conflict)
 kernel......... Linux manjaro 3.19.4-1-MANJARO

I don't have any problems using other browsers. 

I believe this started happening after a recent upgrade so maybe something in here caused it
http://pastebin.com/RYK0whWC

**Comment by JHooverman** [comment]
Please have a look [here](https://github.com/QupZilla/qupzilla/wiki/FAQ#15-i-have-problems-with-the-facebook-web-page-how-can-i-fix-it).
