### ISSUE TITLE
QupZilla for Mac does not support PowerPC

### ISSUE THREAD

**Issue by Y-H** [QupZilla/qupzilla#1651]
QupZilla for Mac cannot run on OS X 10.5 with PowerPC architecture.

**Comment by JHooverman** [comment]
Would you please give some more details about versions, error messages?

**Comment by nowrep** [comment]
PowerPC is not supported by recent Qt versions. If you want to run it on PPC, you need to build yourself with older Qt version (I think 4.7 may work, not sure though)
