### ISSUE TITLE
cannot log into Sourceforge under Haiku

### ISSUE THREAD

**Issue by danboid** [QupZilla/qupzilla#1652]
I'm running Qupzilla 1.8.6 under Haiku 49132 and it doesn't successfully log into Sourceforge.

I go to sf.net, click 'Log In', enter my credentials but then I'm just returned to the sf page I started on and I'm not logged in but nor do I get an error message saying my login attempt failed.

**Comment by JHooverman** [comment]
It works with

Application version: 1.8.6 (61ef93396b)
Qt version: 5.4.2
WebKit version: 538.1
Build time: Jun 4 2015 12:22:05
Platform: openSUSE Tumbleweed (Linux)

Please let us know about your configuration (`Menu -> Configuration information`).

**Comment by nowrep** [comment]
Please report this to Haiku maintaners.

**Comment by nowrep** [comment]
Can you please provide a link to a recent Haiku build so I can update it on qupziila.com ? Thanks
