### ISSUE TITLE
bulk updating of greasemonkey scripts

### ISSUE THREAD

**Issue by OlafLostViking** [QupZilla/qupzilla#1653]
I like the greasemonkey support in qupzilla and use it f.ex. on github. But always checking manually on openuserjs.org for updates is tiresome and errorprone. And to be honest, I only do this when I recognise problems on a website.

Perhaps Qupzilla could check all installed scripts for new versions automatically or upon user request (if you don't want qupzilla to change something behind your back) and install/update the ones selected by the user.

**Comment by nowrep** [comment]
Script updating is actually on my todo.

**Comment by trnkava1** [comment]
Hi, I would like to try implement this feature. Would it be possible?

**Comment by nowrep** [comment]
@trnkava1 Sure, patches welcome ;)

**Comment by nowrep** [comment]
This is now partly fixed. It is now possible to update scripts that have `@downloadUrl` in metadata, but it must be done manually from GreaseMonkey settings.
