### ISSUE TITLE
adblock crash program when block popup window

### ISSUE THREAD

**Issue by vsegdaskray** [QupZilla/qupzilla#1654]
Gentoo Linux x86_64 \ QupZilla 1.8.6
Sorry for my poor english
On each block popup window program call `AdBlockIcon::popupBlocked`. In this function we create AdBlockRule object, with m_regExp as pointer and not defined copy constructor.
Inside `m_blockedPopups.append(pair)` we create "copy" object with default copy constructor. He don't create new "'regExp" for m_regExp, just copy pointer from "rule". On exit from `append()` we destruct "copy" and we have 2 AdBlockRule objects( "rule"  and appended to vector inside QPair) with pointer to invalid "regExp", and when destructor for "rule" called we have segfault.
As i think this problem can be fixed by defined copy constructor with create new regExp object for each copy
[debug output](https://paste.kde.org/ph0boqh2r/dgsxwq)
[test page with popup from EasyList](http://dabblet.com/gist/6e555e5d0e7602c797e7)
[fix patch for me](https://paste.kde.org/pnkqcd7a4/dfgfpg)
I'm not tested this patch on other OS, only gentoo.

**Comment by nowrep** [comment]
Good catch, but we should also define an assignment operator.
