### ISSUE TITLE
Gmail rendering is off

### ISSUE THREAD

**Issue by FoxSays** [QupZilla/qupzilla#1656]
I have no idea if this is fault of Qupzilla or Google...

But every time I go to Gmail using Qupzilla (1.8.6 portable, Windows 7 and XP), the page is rendered very small. Zooming does make it larger, but some elements are magnified much more than others, resulting in a broken (and unusable, IMHO) layout. 

Interestingly enough, other Google products don't seem to have this issue. Search, Drive, Maps, etc renders just fine. 

![screenshot_7](https://cloud.githubusercontent.com/assets/9268172/7698024/ecfcb7a0-fe47-11e4-8c60-89301999d9b8.png)
This screenshot is gmail rendered in Qupzilla

![screenshot_8](https://cloud.githubusercontent.com/assets/9268172/7698034/001f9622-fe48-11e4-890c-53751620d769.png)
...and this is the same page rendered in Firefox.

**Comment by ff2000** [comment]
Seems like QtWebKit (qt4, isn't it?) doesn't support web fonts. For a quick test open google.com/fonts in different browsers. Be aware of e.g. firefox' noscript blocking webfonts by default, so you may need to allow that.

**Comment by nowrep** [comment]
Yes, that is QtWebKit issue.
