### ISSUE TITLE
doesn't run on wayland

### ISSUE THREAD

**Issue by stozi** [QupZilla/qupzilla#1658]
Apparently "qupzilla is using Xlib manually, even when on wayland"

Even qupzilla-git built with export NO_X11="true" crashes when trying to load in weston.

Otter browser and Midori load in weston, I think qupzilla really should.

**Comment by nowrep** [comment]
Can you please provide backtrace?

**Comment by stozi** [comment]
version from Arch repos:

    Time: Thu May 21 18:17:42 2015
    Qt version: 5.4.1 (compiled with 5.4.0)
    QupZilla version: 1.8.6
    WebKit version: 538.1
    
    ============== BACKTRACE ==============
    #0: qupzilla() [0x403423]
    #1: /usr/lib/libc.so.6(+0x33540) [0x7f103ea12540]
    #2: /usr/lib/libX11.so.6(_XSend+0x2b) [0x7f103e48701b]
    #3: /usr/lib/libX11.so.6(_XFlush+0x15) [0x7f103e4874d5]
    #4: /usr/lib/libX11.so.6(_XGetRequest+0x55) [0x7f103e489fa5]
    #5: /usr/lib/libX11.so.6(XChangeProperty+0x59) [0x7f103e464579]
    #6: /usr/lib/libX11.so.6(XSetClassHint+0xa8) [0x7f103e4819c8]
    #7: /usr/lib/libQupZilla.so.1(_ZN7QzTools10setWmClassERK7QStringPK7QWidget+0x65) [0x7f1042b92015]
    #8: /usr/lib/libQupZilla.so.1(_ZN13BrowserWindowC1EN2Qz17BrowserWindowTypeERK4QUrl+0x336) [0x7f10429e52d6]
    #9: /usr/lib/libQupZilla.so.1(_ZN15MainApplication12createWindowEN2Qz17BrowserWindowTypeERK4QUrl+0x4f) [0x7f10429f060f]
    #10: /usr/lib/libQupZilla.so.1(_ZN15MainApplicationC2ERiPPc+0x1577) [0x7f10429f66a7]
    #11: qupzilla() [0x402a1b]
    #12: /usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f103e9ff800]
    #13: qupzilla() [0x402d80]

qupzilla-git from AUR with export NO_X11="true"

    Time: Thu May 21 18:19:11 2015
    Qt version: 5.4.1 (compiled with 5.4.1)
    QupZilla version: 1.9.0
    WebKit version: QtWebEngine
    
    ============== BACKTRACE ==============
    #0: qupzilla() [0x4033c3]
    #1: /usr/lib/libc.so.6(+0x33540) [0x7fe665942540]
    #2: /usr/lib/libQt5WebEngineCore.so.5(+0x2b449df) [0x7fe65fe709df]
    #3: /usr/lib/libQt5WebEngineCore.so.5(+0x52fd53) [0x7fe65d85bd53]
    #4: /usr/lib/libQt5WebEngineCore.so.5(+0x5300fd) [0x7fe65d85c0fd]
    #5: /usr/lib/libQt5WebEngineCore.so.5(_ZN18WebContentsAdapterC2EPN7content11WebContentsE+0x25) [0x7fe65d8544b5]
    #6: /usr/lib/libQt5WebEngineWidgets.so.5(+0xfe38) [0x7fe665284e38]
    #7: /usr/lib/libQt5WebEngineWidgets.so.5(_ZN14QWebEnginePageC1EP7QObject+0x32) [0x7fe665285602]
    #8: /usr/lib/libQupZilla.so.1(_ZN7WebPageC2EP7QObject+0x26) [0x7fe6673c4186]
    #9: /usr/lib/libQupZilla.so.1(_ZN6WebTabC1EP13BrowserWindow+0x143) [0x7fe6673d0123]
    #10: /usr/lib/libQupZilla.so.1(_ZN9TabWidget7addViewERK11LoadRequestRK7QStringRK6QFlagsIN2Qz18NewTabPositionFlagEEbib+0xf1) [0x7fe667396a51]
    #11: /usr/lib/libQupZilla.so.1(_ZN9TabWidget7addViewERK11LoadRequestRK6QFlagsIN2Qz18NewTabPositionFlagEEbb+0x44) [0x7fe667396f44]
    #12: /usr/lib/libQupZilla.so.1(_ZN9TabWidget12restoreStateERK7QVectorIN6WebTab8SavedTabEEi+0x1bf) [0x7fe66739bf1f]
    #13: /usr/lib/libQupZilla.so.1(_ZN15MainApplication14restoreSessionEP13BrowserWindow7QVectorIN14RestoreManager10WindowDataEE+0x586) [0x7fe667280c16]
    #14: /usr/lib/libQupZilla.so.1(_ZN13BrowserWindow10postLaunchEv+0x83b) [0x7fe667272c1b]
    #15: /usr/lib/libQupZilla.so.1(+0x2a93ed) [0x7fe6673e43ed]
    #16: /usr/lib/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0xfa) [0x7fe666494d5a]
    #17: /usr/lib/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x497) [0x7fe666a3c897]
    #18: /usr/lib/libQt5Widgets.so.5(_ZN11QMainWindow5eventEP6QEvent+0x16b) [0x7fe666b50c1b]
    #19: /usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c) [0x7fe6669f93dc]
    #20: /usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x3a0) [0x7fe6669fe820]
    #21: /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0xdb) [0x7fe6664639eb]
    #22: /usr/lib/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x1eb) [0x7fe666465a2b]
    #23: /usr/lib/libQt5Core.so.5(+0x2e49f3) [0x7fe6664bb9f3]
    #24: /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x24d) [0x7fe6634dc9fd]
    #25: /usr/lib/libglib-2.0.so.0(+0x49ce0) [0x7fe6634dcce0]
    #26: /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7fe6634dcd8c]
    #27: /usr/lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x57) [0x7fe6664bbde7]
    #28: /usr/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x112) [0x7fe666461482]
    #29: /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x9c) [0x7fe666468e5c]
    #30: qupzilla() [0x4029ec]
    #31: /usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7fe66592f800]
    #32: qupzilla() [0x402d29]

**Comment by nowrep** [comment]
The first one crashes because it is not built with NO_X11, the second one because apparently QtWebEngine is not ready to run on Wayland.

**Comment by stozi** [comment]
ok, my bad, qupzilla-qt5-webkit-git works with NO_X11. sweet beans.pl
