### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by elioqoshi** [QupZilla/qupzilla#1659]
Hey there,

I was wondering whether there are any plans for a logo rehaul?
Would love to help on that, I have been contributing at Mozilla a lot with design and think we could something solid here :)

**Comment by nowrep** [comment]
Hi,
I'm open for new design ideas, and honestly would love a new logo! 
The current one is really old and not particularly great.

**Comment by elioqoshi** [comment]
Superb! Happy to help there.
Some of my stuff is on portfolio.elioqoshi.me 
Will send in a few proposals soon

**Comment by varlesh** [comment]
![qupzilla](https://cloud.githubusercontent.com/assets/8083855/9317357/ba3de18e-4543-11e5-8b7d-a21ab957bcde.png)

**Comment by juancarlospaco** [comment]
Qupzilla's Pet should be a Ram, since is the only browser that dont eat it.
https://www.google.com/search?q=ram+animal&tbm=isch

Think of a project pet, like Krita's Kiki Squirrel: https://www.google.com/search?q=kiki+krita&tbm=isch

:smiley_cat:

**Comment by srazi** [comment]
As this issue came up, I want to share my idea, well I'm not a designer and also I use Gimp rarely for my photo editing purposes.

![qupzilla_512x512](https://cloud.githubusercontent.com/assets/1328454/10682145/9302f62a-793e-11e5-842e-0747a2d29e5f.png)

**About design**
In this design you can see the word `QupZilla`, the image of earth is in public domain and downloaded from [here](http://www.publicdomainpictures.net/view-image.php?image=31895&picture=earth-in-high-definition) and I used it both as (a big) dot for `i` and as symbol of `WWW` that is surrounded by `Q` and other letters of word `QupZilla`. I wrote the word `QupZilla` in green color because it consumes less RAM/CPU than other browsers and can be considered as a green software.

P.S.: Indeed I also can see the word `Czech` in my design :D

**Comment by GreenLunar** [comment]
This is not an attempt to troll.  This message will be deleted immediately after is published.

@juancarlospaco, at least promote an open source search engine that would benefit to our privacy ;-)

https://searx.me/?q=ram+animal
https://searx.me/?q=kiki+krita

Please consider to replace them by the above I just posted.

**Comment by nowrep** [comment]
With the logo, I decided to use 

![logo](https://4.bp.blogspot.com/-YeZApZB4lqw/VfMc7ltU7PI/AAAAAAAAAcI/_7ZeRZ6RC5o/s1600/qupzilla_sail_the_world.png)

The main reason for it is that this logo is simple yet good looking. And also from all the designs it is the most "modern" logo (as in Windows 10 / Plasma 5 / Android 5 flat icons)

**Comment by juancarlospaco** [comment]
:+1:

**Comment by elioqoshi** [comment]
@nowrep it's actually a good concept, but there are still too many unneeded details (the continent for example) Can you send me the source files so you I can have a try?

**Comment by nowrep** [comment]
@elioqoshi Sure, here it is, I hope SVG is enough: 
http://cloud.qupzilla.com/public.php?service=files&t=f070ad32616a8e6e0da86f2883b0a3bd

I agree with you. less details would only help.

**Comment by elioqoshi** [comment]
![logo-01](https://cloud.githubusercontent.com/assets/5436686/10709949/dab1fe4a-7a41-11e5-92d0-5f5b448c091d.jpg)
![logo-02](https://cloud.githubusercontent.com/assets/5436686/10709950/dab30948-7a41-11e5-9845-624f931fe3cd.jpg)

Here we go, what do you think?

**Comment by JHooverman** [comment]
I prefer the upper one.

**Comment by elioqoshi** [comment]
The one in the bottom is monochrome, it's not an option, just an alternative when you need to have a monochrome logo (for example, you cannot use the full color logo on a blue background.

**Comment by nowrep** [comment]
The monochrome variant looks great.

The normal variant looks good, but maybe a little different shade of blue for main circle color? (to be close to the color from monochrome variant).

**Comment by elioqoshi** [comment]
![logo-01](https://cloud.githubusercontent.com/assets/5436686/10709997/8533c8e8-7a43-11e5-9d93-7a0333c16dae.jpg)
![logo-02](https://cloud.githubusercontent.com/assets/5436686/10709998/8534f934-7a43-11e5-85a0-fae8f49f208e.jpg)

How about this?

**Comment by nowrep** [comment]
Yes, that's indeed better.

**Comment by nowrep** [comment]
I like it, if there's no better design I'll use this one.

Before I can use it, I'll need to adjust this one image:

![qz](https://raw.githubusercontent.com/QupZilla/qupzilla/master/src/lib/data/icons/other/about.png)

that is used on qupzilla:home page:

![qupzilla:home](http://www.qupzilla.com/screens/kde_window.png)

and also in about dialog.

So that means a text QupZilla with matching colors to the logo. For the about dialog, it could even be just logo and text besides, but for the home page, that won't work.
Also if you have other ideas, just say!

**Comment by cranes-bill** [comment]
I see that this thread is continued just right now...
@nowrep,  maybe something like this:
![8534f934-7a43-11e5-85a0](https://cloud.githubusercontent.com/assets/5161278/10870893/d36da626-80df-11e5-94e9-704771a60413.jpg)
#### NOTE: This is just quick example and has no pretension to be quality!!!

**Comment by nowrep** [comment]
@elioqoshi Can you please post SVG source for the logos?

@cranes-bill Yeah, *something* like that, but not quite this :D

**Comment by elioqoshi** [comment]
Do you need to have also the Wordmark in the logo? I can see what I can do about that.
Will upload the SVG's today later @nowrep

**Comment by nowrep** [comment]
Wordmark would be great, but it's really up to you :). Thanks

**Comment by elioqoshi** [comment]
Hey @nowrep sorry for being late. Here is the full package:
https://dl.dropboxusercontent.com/u/62482708/qupzilla.zip

Hope you like them!
![qupzilla-01](https://cloud.githubusercontent.com/assets/5436686/11021020/2facdcbe-8634-11e5-9002-1ad20a477933.png)
![qupzilla-02](https://cloud.githubusercontent.com/assets/5436686/11021021/2fc7afa8-8634-11e5-9891-9572b7d98701.png)
![qupzilla-03](https://cloud.githubusercontent.com/assets/5436686/11021022/2fec1b2c-8634-11e5-9ca4-617f086257b4.png)
![qupzilla-04](https://cloud.githubusercontent.com/assets/5436686/11021025/2fedfc1c-8634-11e5-9283-f95027ad342b.png)
![qupzilla-05](https://cloud.githubusercontent.com/assets/5436686/11021026/2fef5e04-8634-11e5-9ec7-8cb28f23e578.png)
![qupzilla-06](https://cloud.githubusercontent.com/assets/5436686/11021024/2fed31c4-8634-11e5-8fb0-3a04a5dfcab7.png)
![qupzilla-07](https://cloud.githubusercontent.com/assets/5436686/11021023/2fed0dc0-8634-11e5-8b8a-026a5b962254.png)

**Comment by nowrep** [comment]
@elioqoshi Thanks a lot! No problem at all, it was worth the wait :)

But there is one little issue, it is QupZilla with capital Z :D So if you could fix that, or just tell me the font name and I'll fix it myself.

**Comment by nowrep** [comment]
Well, no .. font name won't work :D 

Quick & dirty fix: https://i.imgur.com/qGzXX3H.png

**Comment by elioqoshi** [comment]
Hey @nowrep , let me do these changes for you :)
The font name is Fira Sans Medium btw.

I prefer the looks of Qupzilla, but that's my opinion.

**Comment by elioqoshi** [comment]
@nowrep here we go:
https://dl.dropboxusercontent.com/u/62482708/qupzilla.zip

![qupzilla-01](https://cloud.githubusercontent.com/assets/5436686/11021663/f3b302c2-8649-11e5-8cae-e0481f622daf.png)


![qupzilla-02](https://cloud.githubusercontent.com/assets/5436686/11021664/f3b3b2b2-8649-11e5-852f-b613e0c6c62b.png)


![qupzilla-03](https://cloud.githubusercontent.com/assets/5436686/11021666/f3b7aade-8649-11e5-936c-6f12627722ce.png)


![qupzilla-04](https://cloud.githubusercontent.com/assets/5436686/11021667/f3b9fd16-8649-11e5-8b22-b7cdab2f6d42.png)


![qupzilla-06](https://cloud.githubusercontent.com/assets/5436686/11021668/f3ba03f6-8649-11e5-9ef7-d9efe7260978.png)


![qupzilla-07](https://cloud.githubusercontent.com/assets/5436686/11021665/f3b621b4-8649-11e5-991b-d4e057996dbf.png)

**Comment by nowrep** [comment]
Awesome, thanks again!

I agree that it looks better as Qupzilla in the logos, but everywhere else I prefer the QupZilla form.

**Comment by nowrep** [comment]
@elioqoshi One last thing, are you ok with showing your e-mail (from github account, or whatever you prefer) in authors section in QupZilla?

**Comment by elioqoshi** [comment]
@nowrep yes sure! ping@elioqoshi.me please :)

**Comment by nowrep** [comment]
Closed with 8b2e6bf9b68211f7c8e001df5ae5cf653fd31e25

**Comment by srazi** [comment]
@elioqoshi Wow... thank you for you hard work, it has a nice and modern look :+1:

**Comment by ke7ofi** [comment]
>Fira Sans

@elioqoshi using another browser's fonts?

**Comment by nowrep** [comment]
@ke7ofi Why not, as long as it is free and good looking :)

**Comment by elioqoshi** [comment]
@ke7ofi Yes, I did over 50 logos for Mozilla in the last 3 years and learned to appreciate the beauty of Fira Sans :)

**Comment by ke7ofi** [comment]
That was a joke; it's a great font. @elioqoshi thanks for doing the logo.

**Comment by elioqoshi** [comment]
Sure, appreciated! :)

**Comment by GreenLunar** [comment]
> I agree that it looks better as Qupzilla in the logos, but everywhere else I prefer the QupZilla form.

I like Qupzilla more than QupZilla.  Please do change it, gradually.

**Comment by elioqoshi** [comment]
@GreenLunar I kind of agree. @nowrep maybe we can make a poll?

**Comment by ke7ofi** [comment]
:+1: to @GreenLunar's idea.

**Comment by GreenLunar** [comment]
This is not my idea.  I am the third one here who agrees on it.
1. https://github.com/QupZilla/qupzilla/issues/1659#issuecomment-154855264
2. https://github.com/QupZilla/qupzilla/issues/1659#issuecomment-154852235
3. Myself
4. https://github.com/QupZilla/qupzilla/issues/1659#issuecomment-156478281

**Comment by ke7ofi** [comment]
Oh, sorry. In that case, :+1: to @elioqoshi's idea.

**Comment by GreenLunar** [comment]
Please refer to #1765 (QupZilla vs. Qupzilla)
