### ISSUE TITLE
Support for multi-part downloading

### ISSUE THREAD

**Issue by xylosper** [QupZilla/qupzilla#1660]
Is it possible for QupZilla to support multi-part downloading?
The only blocker keeping me from QupZilla is missing of this feature.
In Firefox, it's accomplished through DownThemAll! plugin.
I do know there's already a feature request for DownThemAll! plugin (https://github.com/QupZilla/qupzilla-plugins/issues/9) but I can't see any progress.

Instead, I suggest to implement some key features of DownThemAll! in QupZilla:

* Multi-part downloading
* Download links in the page (Maybe this is already supported, but I can't find it either)

Because QupZilla already has download manager, writing new download manager as a plugin would be a overkill and not desirable.
Also, I think multi-part downloading is good feature enough to be included in QupZilla rather than separated plugin.
This is especially good to speed-up for low downloading rate.
The second feature may already exist. If it does, please let me know.

Thank you for great application!

**Comment by nowrep** [comment]
Download links from the page is a good idea, but multi-part downloading is a WONTFIX.
It would probably be possible with QtWebKit (it won't be easy), but there is no way to do it with QtWebEngine.

**Comment by JHooverman** [comment]
You might want to try an external downloader like [uget](http://ugetdm.com/downloads):

![uget](http://i.imgur.com/ejw7lCG.png)
