### ISSUE TITLE
Modal menu with javascript in github doesn't display

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [QupZilla/qupzilla#1662]
Hi !

When I want to see the different branches in github.com, the button doesn't display anything.
The web inspector on this button record errors when clicking :
~~~~~
TypeError: undefined is not a function (evaluating '$(e).fire')
TypeError: undefined is not a function (evaluating '$(n).fire("focusin:delay",function(){e.set(n,!0),$(n).trigger("focusin:delayed")})')
~~~~~

Many other javascript buttons doesn't work...

**Comment by JHooverman** [comment]
Are you talking about this?

![im](http://i.imgur.com/Phumm20.png)

**Comment by schyzophrene-asynchrone** [comment]
Yes.
Impossible to see it, I have to start Iceweasel if I want to.

**Comment by schyzophrene-asynchrone** [comment]
Yes.
Impossible to see it, I have to start Iceweasel if I want to.

**Comment by schyzophrene-asynchrone** [comment]
Yes.
Impossible to see it, I have to start Iceweasel if I want to.

**Comment by schyzophrene-asynchrone** [comment]
Yes.
Impossible to see it, I have to start Iceweasel if I want to.

**Comment by schyzophrene-asynchrone** [comment]
Yes.
Impossible to display it, I need to start Iceweasel if I really want to.

**Comment by JHooverman** [comment]
It will work with

Qt version: 5.4.2
WebKit version: 538.1

Probably, you will have to update your Qt-framework

**Comment by schyzophrene-asynchrone** [comment]
To me :
Qt Version: 5.3.2
Webkit version: 538.1

I'll wait for the Debian team to update the Qt-Framework in the official repository.
Thanks.

**Comment by JHooverman** [comment]
You might want to have a look at [this](https://github.com/QupZilla/qupzilla/issues/1350) issue as well.

**Comment by cranes-bill** [comment]
I have a workaround about that:
Click **BACK** button (off course you should have previously visited page), then click **FORWARD** to return back on this page, so the branches should be showing now.
Sorry for my bad English!
