### ISSUE TITLE
Renew request

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#1664]
Hi again :smiley:
Something about [that](https://github.com/QupZilla/qupzilla/issues/1236)?
Just to be clear - i'm not asking for a quite „session manager“, i just would like the function „Restore previous session“ (which already exists by me), to could be launched from the menu.
Regards!

**Comment by srazi** [comment]
Hi @cranes-bill 
I'm implementing it, I hope you'll see it soon. :smile:

**Comment by cranes-bill** [comment]
Hi, you are incredibly fast, thank you, very, very much!
I'm sure, i'll see it soon. :thumbsup:

**Comment by cranes-bill** [comment]
Yes, typing on the terminal when i decide to restore the old session has ended [today](https://github.com/QupZilla/qupzilla/commit/755ec16598656776e94dbaae9de25f514a592b53). :smiley: 

## THANK YOU VERY MUCH !
