### ISSUE TITLE
QupZilla is not using my native icon theme

### ISSUE THREAD

**Issue by ikem-krueger** [QupZilla/qupzilla#1666]
I'm using Linux Mint Debian with the MATE desktop environment (a Gnome 2.x fork).

When I run QupZilla it's not using my icon theme.

A workaround is to start QupZilla with:

    DESKTOP_SESSION=gnome qupzilla

The thing is, that causes other issues:

The navigation bar icons are not scalled very well. (My icon theme consist of svg icons.)

And the font aliasing is very ugly!

**Comment by ikem-krueger** [comment]
Here is a screenshot of what I mean:

![Screenshot] (http://fs2.directupload.net/images/150609/6txbgley.png)

**Comment by JHooverman** [comment]
Did you put your theme in the directory `~/.config/qupzilla/themes ` and load it from there?

**Comment by ikem-krueger** [comment]
I didn't. I use the QupZilla "Linux Default" theme.

**Comment by cranes-bill** [comment]
I think QT can't reed `svg` icons. But even if that's not true, i think Qupzila only looking in Gnome and Kde settings about the icon theme (nowrep might tell that).
By the way, what returns the following commands:
```
gconftool-2 --get /org/gnome/desktop/interface/icon-theme
gconftool-2 --get /org/mate/desktop/interface/icon-theme
dconf read /org/gnome/desktop/interface/icon-theme
dconf read /org/mate/desktop/interface/icon-theme
```
if some results don't matches with your icon theme name, change them!

**Comment by nowrep** [comment]
Qt can read icons, the problem is just that Qt doesn't know where to find preferred icon theme for "other DEs".

**Comment by ikem-krueger** [comment]
@cranes-bill, this is the output of the commands:

    $: gconftool-2 --get /org/gnome/desktop/interface/icon-theme
    No value set for `/org/gnome/desktop/interface/icon-theme'

    $: gconftool-2 --get /org/mate/desktop/interface/icon-theme
    No value set for `/org/mate/desktop/interface/icon-theme'

    $: dconf read /org/gnome/desktop/interface/icon-theme
    [No output]

    $: dconf read /org/mate/desktop/interface/icon-theme
    'Mint-Box'

I changed all the values to 'Mint-Box', but that didn't changed a bit.

**Comment by ikem-krueger** [comment]
The problem is, that are three problems in one:

1. QupZilla is not picking up my icon theme, unless run with "DESKTOP_SESSION=gnome qupzilla".
2. When I run QupZilla like that, it's using the correct icon theme, but the wrong icon resolution (16x16 instead of 24x24 or 32x32).
3. When I run QupZilla like that, the font anti-aliasing is worse then without.

**Comment by ikem-krueger** [comment]
Okay, I found the cause for problem 2.

My icon theme didn't provided icons in a 32x32 resolution.

So QupZilla is using the 16x16 resolution icons.

I fixed it by creating a symbolic link to the 24x24 and naming it 32x32.

But why is QupZilla not using the next lower resolution (which would be 24x24) on default?

**Comment by cranes-bill** [comment]
**Look [what](https://wiki.archlinux.org/index.php/Cinnamon#QGtkStyle_unable_to_detect_the_current_theme) i found accidentally**.

I found this during trying to resolve my Qt related issue and i hope you don't mind to explain it here!
So, a few weeks ago i switched (finally :smiley:) to newer version of my OS, but noticed that [dead keys](https://en.wikipedia.org/wiki/Dead_key) does not works in Qt apps. Perhaps i'm missing something, but fail to find what is it, so any help will be appreciated.

**Comment by nowrep** [comment]
This is issue with all Qt apps and not specific to QupZilla.
