### ISSUE TITLE
Problem on GitHub to attach image by drag & drop or by selecting them

### ISSUE THREAD

**Issue by ikem-krueger** [QupZilla/qupzilla#1668]
When I reported my last issue, I couldn't attach an image to the report.

When I drag and dropped the image, it showed in tab.

By clicking on "selecting them", I could select them, but it didn't got uploaded.

**Comment by ikem-krueger** [comment]
I think that has to do with some javascript functions which are not (properly) implemented.

If I try to upload images on imgur.com the picture selecting dialog isn't working.

(When I hover over the upload button, it shows "javascript:". It does nothing when I click on it.)

If I use directupload.net it's working.

**Comment by nowrep** [comment]
This is issue with old WebKit that comes with QtWebKit.
This will be fixed with QtWebEngine.
