### ISSUE TITLE
Problem on GitHub to edit title or comment after submitting an issue

### ISSUE THREAD

**Issue by ikem-krueger** [QupZilla/qupzilla#1669]
I made a mistake with one of my issues I reported and I wanted to edit them.

When I tried to edit the title by clicking on "Edit", nothing happens.

Same happened when I clicked on the little edit icon near my comment.

**Comment by JHooverman** [comment]
Please try to update your qt/ qtwebkit to at least 5.4.x/ 538.1 as this issue does not appear:

![im2](http://i.imgur.com/NfxmWPM.png)

Please see #1204, #1662

**Comment by ikem-krueger** [comment]
I don't know how to do that.

**Comment by cranes-bill** [comment]
@JHooverman, i have not problem with this with *QtWebkit 537.21; Qt 4.8.5.*

**Comment by ikem-krueger** [comment]
I'm using QupZilla 1.8.6; QtWebKit 534.34; Qt 4.8.6.

**Comment by cranes-bill** [comment]
It seems, the problem dissapears from QtWebKit 537.21 and above...

**Comment by The-Compiler** [comment]
Either way - it seems to be an upstream QtWebKit issue which is fixed already - so there's not much @ikem-krueger can do except upgrading their QtWebKit :smile:
