### ISSUE TITLE
Crash on Linux x64 Qt5 version 1.8.6-1 webkit 538.1

### ISSUE THREAD

**Issue by bvbfan** [QupZilla/qupzilla#1670]
Page http://www.phoronix.com/scan.php?page=news_item&px=AMD-R7-A10-7870K-Pre
======= Backtrace: =========
/lib/libc.so.6(+0x71a1e)[0x7f3788e13a1e]
/lib/libc.so.6(+0x76e7e)[0x7f3788e18e7e]
/lib/libc.so.6(+0x7765b)[0x7f3788e1965b]
/usr/lib/qt5/plugins/platforms/libqxcb.so(_ZNK13QFontEngineFT9loadGlyphEPNS_9QGlyphSetEj6QFixedN11QFontEngine11GlyphFormatEb+0x647)[0x7f377d1eec37]
/usr/lib/qt5/plugins/platforms/libqxcb.so(_ZN13QFontEngineFT12loadGlyphForEj6QFixedN11QFontEngine11GlyphFormatERK10QTransformb+0x11d)[0x7f377d1f151d]
/usr/lib/qt5/plugins/platforms/libqxcb.so(_ZN13QFontEngineFT16alphaMapForGlyphEj6QFixedRK10QTransform+0x4f)[0x7f377d1f28ef]
/usr/lib/libQt5Gui.so.5(_ZN11QFontEngine22lockedAlphaMapForGlyphEj6QFixedNS_11GlyphFormatERK10QTransformP6QPoint+0x2d)[0x7f378a8502bd]
/usr/lib/qt5/plugins/platforms/libqxcb.so(_ZN13QFontEngineFT22lockedAlphaMapForGlyphEj6QFixedN11QFontEngine11GlyphFormatERK10QTransformP6QPoint+0xd1)[0x7f377d1f2441]
/usr/lib/libQt5Gui.so.5(_ZN18QRasterPaintEngine16drawCachedGlyphsEiPKjPK11QFixedPointP11QFontEngine+0x680)[0x7f378a9d1ce0]
/usr/lib/libQt5Gui.so.5(_ZN18QRasterPaintEngine18drawStaticTextItemEP15QStaticTextItem+0x31f)[0x7f378a9d3faf]
/usr/lib/libQt5Gui.so.5(+0x335bc9)[0x7f378a9efbc9]
/usr/lib/libQt5Gui.so.5(_ZN8QPainter12drawGlyphRunERK7QPointFRK9QGlyphRun+0x19b)[0x7f378a9f016b]
/usr/lib/libQt5WebKit.so.5(+0x8a7b0a)[0x7f378b492b0a]
/usr/lib/libQt5WebKit.so.5(+0x8a8a32)[0x7f378b493a32]
/usr/lib/libQt5WebKit.so.5(+0x88ee1b)[0x7f378b479e1b]
/usr/lib/libQt5WebKit.so.5(+0x890f3e)[0x7f378b47bf3e]
/usr/lib/libQt5WebKit.so.5(+0x1154d4d)[0x7f378bd3fd4d]
/usr/lib/libQt5WebKit.so.5(+0x11763f5)[0x7f378bd613f5]
/usr/lib/libQt5WebKit.so.5(+0x117696b)[0x7f378bd6196b]
/usr/lib/libQt5WebKit.so.5(+0x115c61e)[0x7f378bd4761e]
/usr/lib/libQt5WebKit.so.5(+0x1483efb)[0x7f378c06eefb]
/usr/lib/libQt5WebKit.so.5(+0x148419d)[0x7f378c06f19d]
/usr/lib/libQt5WebKit.so.5(+0x1487f8e)[0x7f378c072f8e]
/usr/lib/libQt5WebKit.so.5(+0x1437ef6)[0x7f378c022ef6]
/usr/lib/libQt5WebKit.so.5(+0x1149361)[0x7f378bd34361]
/usr/lib/libQt5WebKit.so.5(+0x13bfce2)[0x7f378bfaace2]
/usr/lib/libQt5WebKit.so.5(+0x117b1a6)[0x7f378bd661a6]
/usr/lib/libQt5WebKit.so.5(+0x148bda4)[0x7f378c076da4]
/usr/lib/libQt5WebKit.so.5(+0x14180b0)[0x7f378c0030b0]
/usr/lib/libQt5WebKit.so.5(+0x1440faf)[0x7f378c02bfaf]
/usr/lib/libQt5WebKit.so.5(+0x14dffa8)[0x7f378c0cafa8]
/usr/lib/libQt5WebKit.so.5(+0x14e0c20)[0x7f378c0cbc20]
/usr/lib/libQt5WebKit.so.5(+0x14e1bb2)[0x7f378c0ccbb2]
/usr/lib/libQt5WebKit.so.5(+0x14e0366)[0x7f378c0cb366]
/usr/lib/libQt5WebKit.so.5(+0x14e0c20)[0x7f378c0cbc20]
/usr/lib/libQt5WebKit.so.5(+0x14e0e08)[0x7f378c0cbe08]
/usr/lib/libQt5WebKit.so.5(+0x841f3f)[0x7f378b42cf3f]
/usr/lib/libQt5WebKit.so.5(+0x912cfe)[0x7f378b4fdcfe]
/usr/lib/libQt5WebKit.so.5(+0xadff1b)[0x7f378b6caf1b]
/usr/lib/libQt5WebKit.so.5(+0xae040a)[0x7f378b6cb40a]
/usr/lib/libQt5WebKit.so.5(+0x898198)[0x7f378b483198]
/usr/lib/libQt5WebKit.so.5(+0x14a9e72)[0x7f378c094e72]
/usr/lib/libQt5WebKit.so.5(+0x144c817)[0x7f378c037817]
/usr/lib/libQt5WebKit.so.5(+0x148bda4)[0x7f378c076da4]
/usr/lib/libQt5WebKit.so.5(+0x148c081)[0x7f378c077081]
/usr/lib/libQt5WebKit.so.5(+0x13fdaa1)[0x7f378bfe8aa1]
/usr/lib/libQt5WebKit.so.5(+0x14a7830)[0x7f378c092830]
/usr/lib/libQt5WebKit.so.5(+0x14a7c1c)[0x7f378c092c1c]
/usr/lib/libQt5WebKit.so.5(+0x1483efb)[0x7f378c06eefb]
/usr/lib/libQt5WebKit.so.5(+0x148419d)[0x7f378c06f19d]
/usr/lib/libQt5WebKit.so.5(+0x1487f8e)[0x7f378c072f8e]
/usr/lib/libQt5WebKit.so.5(+0x1437ef6)[0x7f378c022ef6]
/usr/lib/libQt5WebKit.so.5(+0x13da69a)[0x7f378bfc569a]
/usr/lib/libQt5WebKit.so.5(+0x13da838)[0x7f378bfc5838]
/usr/lib/libQt5WebKit.so.5(+0x1484144)[0x7f378c06f144]
/usr/lib/libQt5WebKit.so.5(+0x1487f8e)[0x7f378c072f8e]
/usr/lib/libQt5WebKit.so.5(+0x1437ef6)[0x7f378c022ef6]
/usr/lib/libQt5WebKit.so.5(+0x13da69a)[0x7f378bfc569a]
/usr/lib/libQt5WebKit.so.5(+0x13da838)[0x7f378bfc5838]
/usr/lib/libQt5WebKit.so.5(+0x1484144)[0x7f378c06f144]
/usr/lib/libQt5WebKit.so.5(+0x1487f8e)[0x7f378c072f8e]
/usr/lib/libQt5WebKit.so.5(+0x1437ef6)[0x7f378c022ef6]
/usr/lib/libQt5WebKit.so.5(+0x13da69a)[0x7f378bfc569a]

**Comment by The-Compiler** [comment]
This is a [Qt bug](https://bugreports.qt.io/browse/QTBUG-44812) which is fixed in Qt 5.5.
