### ISSUE TITLE
Re-enable a plugin is not possible

### ISSUE THREAD

**Issue by srazi** [QupZilla/qupzilla#1671]
My configuration: Qt4, Windows XP. Branch: 1.8

Step to reproduce:
1- Go to preferences dialog and enable some of plugins, for example TestPlugin.
2- Restart QupZilla. (TestPlugin is now loaded on start-up)
3- Go to preferences dialog and disable TestPlugin.
4- Now again enable it... QupZilla crashes*

*: Well crash disappears if we call `plugin->pluginLoader->load()` before `plugin->pluginLoader->instance()`, but again `plugin->pluginLoader->instance()` returns NULL.

**: If plugin is disabled at start up then we can enable or disable it without any issue.

**Comment by cranes-bill** [comment]
Yep, the same behavior on Linux.

**Comment by srazi** [comment]
It is not reproducible with Qt-5.4.2.
