### ISSUE TITLE
Download dialog 

### ISSUE THREAD

**Issue by jornmo** [QupZilla/qupzilla#1674]
Hi!

When downloading an image from Facebook (right click -->Save image as) the image is downloaded, but the download manager stops at 0%. Then, when I close the browser I have to "cancel the download" (that is actually finished) to be able to shutdown Qupzilla...
![qupzilla](https://cloud.githubusercontent.com/assets/6152248/8268454/d51c29ec-1786-11e5-989d-674033dc77f8.png)

**Comment by JHooverman** [comment]
Closing this issue as duplicate to #1606.
