### ISSUE TITLE
Reading mode

### ISSUE THREAD

**Issue by jornmo** [QupZilla/qupzilla#1675]
Reading mode like that one of Firefox would be nice :)

**Comment by cdbennett** [comment]
I have used the Firefox reading mode a few times.  But can you share for me and also others who haven't used Firefox's mode, what your request specifically entail?   Possibly:  text is reflowed a certain way, images are removed??, style sheet changes??

I liked using reading mode a few times when a web page had a noisy, clumsy layout, or a distracting background, etc.

**Comment by ke7ofi** [comment]
Here's an screenshot.

![](http://i.imgur.com/PZUGe4r.png)

Here's the settings dialog.

![](http://i.imgur.com/5dQOPVL.png)

It would be nice to adjust things like width, font, etc. if possible.

(Sorry, @nowrep. I feel like I've been continuously throwing bug reports and feature requests at you for the last day or so.)

**Comment by abrowne** [comment]
This is one feature that keeps me sticking with Firefox.

I wonder if Mozilla's [Readability.js library](https://github.com/mozilla/readability) could be used for article parsing?

**Comment by nowrep** [comment]
Using Mozilla's Readability.js directly could probably work.

**Comment by jbambas** [comment]
I will try to implement this feature. @nowrep What's your idea about method of implementation? Into core or as plugin?

**Comment by nowrep** [comment]
@jbambas I'd like to see it as a plugin first.

**Comment by jbambas** [comment]
@nowrep @ke7ofi I have already sent a pull request with the plugin. Any informations how to use it is described in wiki of plugins repository, [here](I have already sent a pull request).

**Comment by GreenLunar** [comment]
Very nice!
