### ISSUE TITLE
Fail to build on Mac OS X

### ISSUE THREAD

**Issue by krlp** [QupZilla/qupzilla#1676]
Hi! I wanted to build the latest versión (1.8.6) and followed the instructions:
./mac/macdeploy.sh

This is the output:
cp: directory QupZilla.app/Contents/MacOS does not exist
mkdir: QupZilla.app/Contents/Resources: No such file or directory
cp: directory QupZilla.app/Contents/Resources/plugins does not exist
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: QupZilla.app/Contents/MacOS/QupZilla (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: QupZilla.app/Contents/Resources/plugins/*.dylib (No such file or directory)
./mac/macdeploy.sh: line 36: macdeployqt: command not found
./mac/macdeploy.sh: line 40: ./create_dmg.sh: No such file or directory

Thanks in advance.

**Comment by srazi** [comment]
Hi,
You should compile it before deploying.
```pro
$ qmake
$ make
```

**Comment by krlp** [comment]
-bash: qmake: command not found

**Comment by srazi** [comment]
Then Qt is not installed on your system or "qmake" is not in your PATH. [Download link](http://www.qt.io/download-open-source/) of open source version.
