### ISSUE TITLE
Request JonDOYNM IP Check...

### ISSUE THREAD

**Issue by Geyup** [QupZilla/qupzilla#1677]
Hi,

Thank you for QupZilla, I have a request, has anyone seen the JonDONYM IP check website?

This site shows some interesting browser features, and I'd like to request if the developers can figure out how to protect QupZilla to get 'Green' on all the checks.

http://ip-check.info/?lang=en

Please click 'Start Test' to see this...

While this is not the only things to accomplish for better security and reducing the browser fingerprint, it is a very good start. 

I hope the developers will really consider this, this would greatly improve browser security.

My concerns for now, are only on the Linux platform, since QupZilla is cross platform, I don't know if this is going to be more difficult to implement for all platforms.

thank you

**Comment by The-Compiler** [comment]
Many of those checks seem to be more of an advertisement for their software than anything else...

Turn off Javascript, cookies and referer, and most of it will be either green, irrelevant, or most likely not fixable. Also, most websites will be broken.

**Comment by Geyup** [comment]
@The-Compiler how long have you studied Browser Fingerprinting?

From what I've studied over the years, this isn't just advertisment.

There's a lot more to it, then just turning off ```Javascript, cookies and referer``` to get more green.

What's interesting is QupZilla has the Authenticaion ID green, I'd like to be able to do this also in Firefox.

**Comment by nowrep** [comment]
This is out of scope. If you want high privacy, use some specialised browser eg. TorBrowser.
