### ISSUE TITLE
Tools won't work ,bookmarks do not open,history won't open visited sites

### ISSUE THREAD

**Issue by robertsable** [QupZilla/qupzilla#1678]

**Comment by JHooverman** [comment]
Please let us know about your configuration (`Menu -> Configuration information`) as shown in the following example:

Application version: 1.9.0 (ee80b04a11)
Qt version: 5.4.2
WebKit version: 538.1
Build time: Jan 25 2015 16:47:02
Platform: openSUSE Tumbleweed (Linux)

In addition you are kindly asked to describe shortly what do you do to open bookmarks/ history.

**Comment by madmedix** [comment]
Possibly related, Running on a <gasp!> win8 pc the browser crashed after visiting and saving numerous bookmarks. Upon relaunch, no bookmarks, history, temp/cache files to go on, nothing.


Configuration Information
Information about version
Application version
1.8.6
Qt version
4.8.5
WebKit version
537.21
Build time
Jan 27 2015 20:48:20
Platform
Windows 8
Browser Identification
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) QupZilla/1.8.6 Safari/537.21

Paths
Profile
C:/Users/madmedix/AppData/Local/QupZilla/profiles/default
Settings
C:/Users/madmedix/AppData/Local/QupZilla/profiles/default/settings.ini
Saved session
C:/Users/madmedix/AppData/Local/QupZilla/profiles/default/session.dat
Pinned tabs
C:/Users/madmedix/AppData/Local/QupZilla/profiles/default/pinnedtabs.dat
Data
C:/Program Files (x86)/QupZilla
Themes
C:/Program Files (x86)/QupZilla/themes
Translations
C:/Program Files (x86)/QupZilla/locale
Build Configuration
Debug build
Disabled
Windows 7 API
Enabled
Portable build
Disabled
Extensions
Name	Version	Author	Description
Access Keys Navigation	0.4.3	David Rosca <nowrep@gmail.com>	Provides support for navigating in webpages by keyboard shortcuts
AutoScroll	0.1.5	David Rosca <nowrep@gmail.com>	Provides support for autoscroll with middle mouse button
Flash Cookie Manager	0.3.0	Razi Alavizadeh <s.r.alavizadeh@gmail.com>	You can easily view/delete flash cookies stored on your computer. This is a solution for having more privacy.
GreaseMonkey	0.5.2	David Rosca <nowrep@gmail.com>	Provides support for userscripts (www.userscripts.org)
Mouse Gestures	0.4.0	David Rosca <nowrep@gmail.com>	Provides support for navigating in webpages by mouse gestures
PIM	0.1.2	Mladen Pejaković <pejakm@autistici.org>	Adds ability for Qupzilla to store some personal data
StatusBar Icons	0.2.0	David Rosca <nowrep@gmail.com>	Adds additional icons and zoom widget to statusbar
Tab Manager	0.4.1	Razi Alavizadeh <s.r.alavizadeh@gmail.com>	Adds ability to managing tabs and windows
Google Update	Google Update
VLC Web Plugin	VLC media player Web Plugin
Silverlight Plug-In	5.1.40416.0
Shockwave Flash	Shockwave Flash 18.0 r0
Preferences
Option	Value
[AdBlock]
disabledRules	"empty"
enabled	true
lastUpdate	2015-07-08T01:43:20
useLimitedEasyList	true
[Bookmarks]
showOnlyIconsInToolbar	false
[Browser-Tabs-Settings]
TabsOnTop	true
[Browser-View-Settings]
LocationBarWidth	1027
SideBarWidth	250
WebSearchBarWidth	300
WebViewWidth	2000
WindowGeometry	QByteArray
WindowMaximised	false
[BrowsingLibrary]
historyState	QByteArray
size	"empty"
[ClickToFlash]
Enabled	true
whitelist	"empty"
[SSL-Configuration]
CACertPaths	"empty"
DisableWeakCiphers	true
IgnoreAllSSLWarnings	false
[SearchEngines]
DefaultEngine	DuckDuckGo
activeEngine	DuckDuckGo
[SessionRestore]
isRunning	true
[SpeedDial]
background	"empty"
backsize	auto
pages	url:"http://www.qupzilla.com"|title:"QupZilla";url:"http://blog.qupzilla.com"|title:"QupZilla Blog";url:"https://github.com/QupZilla/qupzilla"|title:"QupZilla GitHub";url:"https://duckduckgo.com"|title:"DuckDuckGo";
pagesrow	4
sdcenter	0
sdsize	231
[Web-Browser-Settings]
AutomaticallyOpenProtocols	"empty"
BlockOpeningProtocols	"empty"
This page contains information about QupZilla's current configuration - relevant for troubleshooting. Please include this information when submitting bug reports.

Cheers,
Andy

**Comment by cranes-bill** [comment]
I tryed, but failed to reproduce that with [Qupzilla Portable Edition](http://www.qupzilla.com/startdownload?windows_portable) on **Windows 10 x64**, running on virtual machine. Perhaps it's a hardware related issue....
