### ISSUE TITLE
SpeedDial: Background Issues

### ISSUE THREAD

**Issue by omicron56** [QupZilla/qupzilla#1680]
When installing scenic background from "MY Pictures"......works fine until I exit or quit.....then when I go back in Qupzilla.....the background is blank.....how do I fix this....

**Comment by nowrep** [comment]
What do you mean with "scenic background"?

**Comment by cranes-bill** [comment]
I also have not idea what is „_scenic background_“, but have the same issue with background setting. I also tried to set it manually in settings file, but QupZilla just don't read it.
**======================
Latest 1.8.6 commit
QtWebkit 537.21
Qt 4.8.5
=======================**

**Comment by nowrep** [comment]
@cranes-bill Background in speed dial?

**Comment by cranes-bill** [comment]
Yes, yes...
Sorry about that omission! :flushed:
