### ISSUE TITLE
Android and IOS? 

### ISSUE THREAD

**Issue by abigdreamer** [QupZilla/qupzilla#1683]
Does this browser run on Android and IOS? I understand some issues with Android, but what about IOS?

**Comment by Brli** [comment]
There is much enough browsers on both platforms IMO.
Using Qt on both platforms won't make the browser any lighter than their native way of browsing

**Comment by GreenLunar** [comment]
@abigdreamer why would you want QupZilla for portable devices?

**Comment by wbsgit** [comment]
I'd like one to sync bookmarks between devices.
