### ISSUE TITLE
Qupzilla fails to display webpages on KDE Plasma 5

### ISSUE THREAD

**Issue by Dialga** [QupZilla/qupzilla#1686]
Running from the command line I get the following output as is, terminating at (. System is Linux x64 using KDE Plasma 5, built from the latest commit in the master branch.

$ qupzilla 
QupZilla: 0 extensions loaded
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined (

An attempt to load any website fails, and leaves the window blacked out.

I can confirm this is KDE specific.

**Comment by nowrep** [comment]
Can you try with current master?

**Comment by Dialga** [comment]
Problem still exists with master

$ qupzilla
QupZilla: 2 extensions loaded
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
E 0: The 'options' directive has been replaced with 'unsafe-inline' and 'unsafe-eval' source expressions for the 'script-src' and 'style-src' directives. Please use those directives instead, as 'options' has no effect. (http://html5test.com/)
I 3350: IndexedDB: starting tests (http://html5test.com/scripts/6/engine.js)
I 3356: IndexedDB: delete existing database (if exists) (http://html5test.com/scripts/6/engine.js)
E 0: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'unsafe-inline' *". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
 ()
I 3506: IndexedDB: starting tests (http://html5test.com/scripts/7/engine.js)
I 3512: IndexedDB: delete existing database (if exists) (http://html5test.com/scripts/7/engine.js)
E 0: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'unsafe-inline' *". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
 ()
E 3061: WebSocket connection to 'ws://./' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED (http://html5test.com/scripts/6/engine.js)
E 3217: WebSocket connection to 'ws://./' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED (http://html5test.com/scripts/7/engine.js)

**Comment by Dialga** [comment]
branch v1.8 is working fine though

**Comment by nowrep** [comment]
What about with `qupzilla -style fusion`?

**Comment by Dialga** [comment]
Latest master run with the command `qupzilla -style fusion` seems to be working fine, no more blackout. Without it, the problem still exists though.

**Comment by nowrep** [comment]
What about with current master? I've added `QtWebEngine::initialize()`, but not sure if it helps. What style are you using (Breeze?) and which version?

**Comment by Dialga** [comment]
I'v just tried with master, blackout still occurs without `-style fusion`. I'm using the Oxygen desktop theme with the Zion reversed colour scheme. Changing to a different theme has no effect.

**Comment by Dialga** [comment]
Output of latest run:
<pre>$ qupzilla -style fusion
QupZilla: 3 extensions loaded
QOpenGLWidget cannot be used as a native child widget. Consider setting Qt::AA_DontCreateNativeWidgetAncestors and Siblings.
QupZilla: Crashed :( Saving backtrace in /home/acer/.config/qupzilla/crashlog ...
Backtrace successfuly saved in /home/acer/.config/qupzilla/crashlog/Crash-2015-09-01T13:37:24.txt
Aborted (core dumped)</pre>

Output of backtrace:
<pre>
Time: Tue Sep 1 13:37:24 2015
Qt version: 5.5.0 (compiled with 5.5.0)
QupZilla version: 1.9.0
Rendering engine: QtWebEngine

============== BACKTRACE ==============
#0: qupzilla() [0x4035f3]
#1: /usr/lib/libc.so.6(+0x33680) [0x7f6023721680]
#2: /usr/lib/libQt5Widgets.so.5(+0x20b5bd) [0x7f60249225bd]
#3: /usr/lib/libQt5Widgets.so.5(_ZNK11QProxyStyle9baseStyleEv+0xd) [0x7f6024922ebd]
#4: /usr/lib/libQupZilla.so.1(_ZNK15MainApplication9styleNameEv+0x29) [0x7f6025351fd9]
#5: /usr/lib/libQupZilla.so.1(_ZN8TipLabel11resizeEventEP12QResizeEvent+0x35) [0x7f6025414875]
#6: /usr/lib/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0xcbe) [0x7f60248d655e]
#7: /usr/lib/libQt5Widgets.so.5(_ZN6QFrame5eventEP6QEvent+0x1e) [0x7f60249d4f6e]
#8: /usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c) [0x7f602489300c]
#9: /usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x256) [0x7f60248984e6]
#10: /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0xdb) [0x7f60242c589b]
#11: /usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate30sendPendingMoveAndResizeEventsEbb+0x201) [0x7f60248ceac1]
#12: /usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate30sendPendingMoveAndResizeEventsEbb+0xc4) [0x7f60248ce984]
#13: /usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate15prepareToRenderERK7QRegion6QFlagsIN7QWidget10RenderFlagEE+0x5b) [0x7f60248d2c4b]
#14: /usr/lib/libQt5Widgets.so.5(_ZN7QWidget6renderEP8QPainterRK6QPointRK7QRegion6QFlagsINS_10RenderFlagEE+0x4cf) [0x7f60248d37ff]
#15: /usr/lib/libQt5Widgets.so.5(_ZN7QWidget6renderEP12QPaintDeviceRK6QPointRK7QRegion6QFlagsINS_10RenderFlagEE+0x4b) [0x7f60248d3b8b]
#16: /usr/lib/libQt5Widgets.so.5(_ZN7QWidget4grabERK5QRect+0x144) [0x7f60248d47a4]
#17: /usr/lib/qt/plugins/styles/oxygen.so(+0x50b1a) [0x7f5f1bd7bb1a]
#18: /usr/lib/qt/plugins/styles/oxygen.so(+0x49a93) [0x7f5f1bd74a93]
#19: /usr/lib/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0xa3) [0x7f60242f4e63]
#20: /usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c) [0x7f602489300c]
#21: /usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x256) [0x7f60248984e6]
#22: /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0xdb) [0x7f60242c589b]
#23: /usr/lib/libQt5Core.so.5(_ZN14QTimerInfoList14activateTimersEv+0x52d) [0x7f602431b05d]
#24: /usr/lib/libQt5Core.so.5(+0x2f1561) [0x7f602431b561]
#25: /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x24d) [0x7f601bd3b9fd]
#26: /usr/lib/libglib-2.0.so.0(+0x49ce0) [0x7f601bd3bce0]
#27: /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7f601bd3bd8c]
#28: /usr/lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f) [0x7f602431c23f]
#29: /usr/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x10a) [0x7f60242c326a]
#30: /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x9c) [0x7f60242cb20c]
#31: qupzilla() [0x402b84]
#32: /usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f602370e610]
#33: qupzilla() [0x402f09]</pre>

**Comment by nowrep** [comment]
This seems to be similar to this https://bugreports.qt.io/browse/QTBUG-48130
