### ISSUE TITLE
Keyboard shortcuts for in-site search

### ISSUE THREAD

**Issue by sebix** [QupZilla/qupzilla#1688]
The in-site search is missing some essential shortcuts.

* <kbd>Ctrl+F</kbd> is working, but the other very widespread is <kbd>/</kbd>, which does not work.
* <kbd>Ctrl+G</kbd> for forward / next search result
* <kbd>Ctrl+Shift+G</kbd> for backward / previous search result
* The buttons `Highlight` and `Case sensitive` do not have shortcuts (using <kbd>Alt</kbd>)

**Comment by nowrep** [comment]
<kbd>/</kbd> can be enabled in Preferences -> Shortcuts -> single key shortcuts
