### ISSUE TITLE
Version 1.8.6 - Speed Dial and statusbar icon problems

### ISSUE THREAD

**Issue by SJ-Diamond** [QupZilla/qupzilla#1689]
Having here Windows 8, 64 Bit running. Using the portable Qupzilla version. Tried to change speed dial size and add a speed dial background.

After a restart of the browser, settings are forgotten. Speed dial size is back to default and background image is gone.

Can be repeated.

Something similar for the additional Status bar buttons - a while they are staying but suddenly after a fresh browser start they are gone.

**Comment by nowrep** [comment]
Do you have write access to the `profile` directory? (It's in the same directory as `qupzilla.exe`)

**Comment by SJ-Diamond** [comment]
Of course, i have also tried various installation locations, started the
browser also with admin rights, always the same trouble.

2015-09-01 21:54 GMT+02:00 David Rosca <notifications@github.com>:

> Do you have write access to the profile directory? (It's in the same
> directory as qupzilla.exe)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QupZilla/qupzilla/issues/1689#issuecomment-136840807>.
>



-- 
---------- Wikus Van De Merwe was right - Fookin' Planet!!! ----------
