### ISSUE TITLE
Can't edit or delete Speed Dail entrys

### ISSUE THREAD

**Issue by IMbackK** [QupZilla/qupzilla#1692]
Im on Arch Linux x64 
Qupzilla version 1.8.6
WebKit version 538.1

recently I deleted the user profile ~/.config/qupzilla. Since then I can not eddit or delete speed dail entrys. Hovering over the buttons gives the expected tooltip, but clicking the buttons simply dose nothing. entrys can be added, and the oder can be changed with no problems. Global speed dail settings also work. I have tryed deleting the profile agin, but this has not changed the behavior.

**Comment by tastyminerals** [comment]
Having the same issue without deleting ~/.config/qupzilla. Speed dial page buttons do not respond upon clicking.

**Comment by cranes-bill** [comment]
I can't reproduce it. Perhaps it's __Qt5__ related....

«««««««««««»»»»»»»»»»
_Qupzilla 1.8.6
QtWebkit 537.21
Qt 4.8.5_
«««««««««««»»»»»»»»»»

**Comment by nowrep** [comment]
What version do you have?

**Comment by cranes-bill** [comment]
@nowrep, In case that the question is to me, mine is latest commit.

**Comment by IMbackK** [comment]
Im on QT 5.5.0

**Comment by IMbackK** [comment]
I confirm that it is qt related, with qt4 I can delete Speed dail entrys. Back in qt5 land: No dice.

**Comment by nowrep** [comment]
QtWebEngine port is experimental (https://github.com/QupZilla/qupzilla/tree/master check README), and it is known that speed dial, among other things, does not work properly.

**Comment by IMbackK** [comment]
Damn, I schould file a bug agenst Arch for changeing the default to the qt5 version then.

**Comment by JHooverman** [comment]
@IMbackK: Qupzilla 1.8.x series (git branch v1.8) compiled with qt < 5.5 will work reliable.

**Comment by IMbackK** [comment]
Aperantly Arch still useses qtwebkit see: https://bugs.archlinux.org/task/45998 . so this bug is valid?

**Comment by nowrep** [comment]
Yes, this is not about QtWebEngine, sorry.

Can you please take a look in JavaScript console for any errors when trying to modify speed dials?

**Comment by IMbackK** [comment]
Theres nothing in the javascrip console

This is somehow strangely related to the WM. 

I use enlightenment, It works under twm, and it works if i delete my enlightenment profile.

strange.

**Comment by tastyminerals** [comment]
I have `qt5-base 5.5.0-1 (qt qt5) [installed]`.
I am using awesome wm.

**Comment by nowrep** [comment]
That's really strange (window manager shouldn't make any difference at all), perhaps can you test with Qt 5.4?

**Comment by IMbackK** [comment]
This bug nolonger exists with qwebengine (for me)
