### ISSUE TITLE
Speeddial page buttons do not work

### ISSUE THREAD

**Issue by tastyminerals** [QupZilla/qupzilla#1693]
I am running **Qupzilla 1.8.6** on Linux machine. There are four default pages available on a speed dial. 
3 page buttons: **edit**, **reload**, **remove** do not respond upon clicking. I cannot remove, refresh or edit the default speed dial pages. I can add a new page but then again, the above mentioned buttons do not work.

**Comment by JHooverman** [comment]
Are you using qt-5.5?

**Comment by tastyminerals** [comment]
yes
