### ISSUE TITLE
System volume reset to 100% everytime an HTML5 video starts playing

### ISSUE THREAD

**Issue by argymeg** [QupZilla/qupzilla#1694]
First of all congratulations on an amazing browser. However, this issue is something of a blocker - it happens on any video site I tried, though not on Flash. Tested on KDE, Cinnamon, LXDE and LXQt so this looks like a QupZilla issue, although it doesn't happen on plain Openbox. I am using Arch Linux with Pulseaudio installed.

**Comment by nowrep** [comment]
This looks like pulseadio issue, try using `flat-volumes = no` in pulseaudio daemon.conf.
