### ISSUE TITLE
[Feature request] Turn Adblock into uBlock and add a uMatrix addon

### ISSUE THREAD

**Issue by mark-owen** [QupZilla/qupzilla#1695]
Hello,

I know this has been discussed in the past and I understand that Qupzilla's adblock has nothing to do with Adblock Plus or any other Firefox addon with a similar name. Now, I find that what's missing from Qupzilla is the ability to block anything I want on a webpage which uBlock Origin gives me on Firefox.

As uBlock Origin's maintainer, Gorhill, says: uBlock is not an adblocker, it's a general purpose blocker. Would it be possible to add such a feature to Qupzilla? Along with an improved way to manage adblock's filters.

On a final note, a port of uMatrix to Qupzilla's addon library would be a great thing which would attract a lot of privacy-minded users.

Thank you for taking my questions into account.

**Comment by nowrep** [comment]
QupZilla uses own AdBlock implementation, so turning it into uBlock does not makes sense.

**Comment by GreenLunar** [comment]
uMatrix Qupzilla/qupzilla-plugins/issues/51

**Comment by ke7ofi** [comment]
QupZilla/qupzilla-plugins/issues/51 sounds good to me.

**Comment by t33rex** [comment]
> QupZilla uses own AdBlock implementation, so turning it into uBlock does not makes sense.

Actually it makes a lot of sense because uBlock + uMatrix work as an application firewall, much more powerful than a mere ad blocker.
