### ISSUE TITLE
Menu on github's website to switch branches is partly missing

### ISSUE THREAD

**Issue by MEL27** [QupZilla/qupzilla#1696]
Qupzilla version: v1.8.6 portable, official binary
OS: Windows 10 x64

Steps to reproduce:
1. Visit https://github.com/QupZilla/qupzilla
2. Press the button above the list. At present, the caption reads "Branch: v1.8"
3. The menu shows up and does not function properly. See the screenshot

![screenshot](https://cloud.githubusercontent.com/assets/10842148/9560467/e761a896-4e47-11e5-9d5e-bf7d8b40b7f7.png)

**Comment by MEL27** [comment]
Some additional information.
Webkit version: 537.21
Qt version: 4.8.5

**Comment by cranes-bill** [comment]
You can se [here](https://github.com/QupZilla/qupzilla/issues/1662) and [here](https://github.com/QupZilla/qupzilla/issues/1350) including references as well.

**Comment by MEL27** [comment]
Thanks for the references.
From what I read, it is a upstream Qt bug that had been fixed.

So, in this case, I would like to ask, is there a possibility that the build on the official website be updated?
The official win32 build portable edition is still using Qt 4.8.5, which is the problematic one that I'm using.

**Comment by nowrep** [comment]
Yes, I'll try to build next version (1.8.7) with latest Qt 5.5 on Windows.
