### ISSUE TITLE
[Enhancement Request] TDE Wallet

### ISSUE THREAD

**Issue by chaotickjg** [QupZilla/qupzilla#1698]
I compiled Qupzilla recently and noticed it has a build flag for enabling support for KWallet. I am currently using Trinity Desktop Environment (a fork off of KDE 3.5). TDE retains KWallet (rebranded TDE Wallet) from it's KDE predecessor. I'd like to see it get support.

**Comment by nowrep** [comment]
You can write your own plugin for that. But if TDE is using Qt 3, that's not going to be easy.

As far as from my side, I'm sorry but I won't write the plugin.
