### ISSUE TITLE
AdBlock doesn't block 'https'?

### ISSUE THREAD

**Issue by sspphheerraa** [QupZilla/qupzilla#1703]
AdBlock doesn't block 'https'?
For example, http://rutracker.org has ad (image link https://storage.googleapis.com/728x90/rutrackerStatic.jpg). If I add it to custom rules, adblock doesn't block it anyway. While usual http works fine.

**Comment by cranes-bill** [comment]
It's blocked to me (_perhaps from_ „**Easy List**“), without writing extra rules...
![2015-09-12 11 54 47](https://cloud.githubusercontent.com/assets/5161278/9830830/1a3ac5b4-5946-11e5-90c0-f7e5a810d67c.png)

**Comment by sspphheerraa** [comment]
But another is not. You have: http://i.piccy.info/i9/5e15e5d6a4f6e2f96abbf2b39002eaff/1442058990/307900/949161/02.png
And seems that you use only EasyList subscription.
I am trying to block all ads, so I add all embedded subscriptions. And that's I have: http://i.piccy.info/i9/362ac527ca11bb35fb24518f2d0773a3/1442058977/210261/949161/01.png
The ads on the left I can block by custom rules, but the middle (top) one I can't.

So, try to add all subscriptions and test it.

**Comment by cranes-bill** [comment]
Я могу заблокировать все :stuck_out_tongue_winking_eye:
![2015-09-12 15 53 30](https://cloud.githubusercontent.com/assets/5161278/9831637/009f9d88-5968-11e5-86b4-52bdd7d6658b.png)

**Comment by sspphheerraa** [comment]
What subscriptions did you add?
And what's your custom rules?

**Comment by cranes-bill** [comment]
All the rules are in „**( )**“ on the picture. The custom are: `static2` and `ad.adriver`, but writing like that, everything from those domains will be blocked everywhere (_incl. the tracker logo here_, but it is good for me). [Here](https://adblockplus.org/filters) , you can read more about writing rules.
As i said, the middle ad has blocked from **EasyList**. If you starts QupZilla from new profile, i'm sure that will works to you as well, so probably you have any custom rule which conflicts with it.
By the way, something like that `||googleapis.com^$third-party` should disable the middle ad as well...
P.S.: Sorry for my bad English!

**Comment by sspphheerraa** [comment]
All right. It's not a bug.
I will ask at https://forums.lanik.us/index.php
Thanks.

**Comment by nowrep** [comment]
It's also possible there is an exception rule for https that could explain why it only works for http.
