### ISSUE TITLE
QupZilla looking for some SSL certificates in non-existing location

### ISSUE THREAD

**Issue by willbprog127** [QupZilla/qupzilla#1706]
With some (not all) webpages or secure content within webpages, QupZilla is looking for certificates in a non-existing location.  For example, when I visit...
`http://www.marketplaceleaders.org/tgif2/`
...the certificate exception dialog comes up and I choose to always accept this certificate, but the following error message displays on the command-line
```
NetworkManager::addLocalCertificate cannot write to file:  "/usr/home/will/(1).config/qupzilla/profiles/default/certificates/crt" (network/networkmanager.cpp:656, void NetworkManager::addLocalCertificate(const QSslCertificate &))
```
...and I always have to answer "Yes" each time I visit the site.

It appears to be looking for a directory called "(1).config" which does not exist in my home directory.

Thanks in advance! :smile: 

--

:information_source: 
Build: 4aee21c29b005308059215d03138360d73026a28
Application version: `1.8.6`
Qt version: `5.4.1`
WebKit version: `538.1`
Build time: `Sep 13 2015 12:21:36`
Platform: `BSD 4.4` _(FreeBSD 10.2 - amd64)_

**Comment by nowrep** [comment]
I noticed this in last log you sent, I'l look into it.

**Comment by willbprog127** [comment]
> I noticed this in last log you sent, I'l look into it.

Thank you! :smile:

**Comment by willbprog127** [comment]
@nowrep Thank you
