### ISSUE TITLE
Non-free logos

### ISSUE THREAD

**Issue by spotrh** [QupZilla/qupzilla#1708]
The icons in src/lib/data/icons/browsers are pretty clearly taken from other browsers, and their use is not in compliance with the trademark use policies of the other browser projects. I'm not entirely sure why they're here, to be honest, but they should not be.

**Comment by The-Compiler** [comment]
They seem to be there for the bookmark import dialog.

How would you know their use is not in compliance with their use policies if you don't know where they're used?

**Comment by spotrh** [comment]
Ah. I hadn't been able to come up with a valid reason for them to be used here, but this is pretty close. It could be argued that the bookmark import dialog does not need the logo mark when the word mark is sufficient, but that's enough of a gray area that I'll just close this ticket out.

**Comment by willbprog127** [comment]
@spotrh I know you closed the issue already, but I think if the other browser projects cared, they would have said something by now.

Are the logos in question really that big of an issue?  I think they are there just to help users quickly identify which option is which.

Lennart didn't send you, did he? :confounded:

**Comment by spotrh** [comment]
No, Lennart didn't send me. Also, trademark enforcement is not an issue of "caring". If I was feeling evil (which I am not), I would have simply informed them of the potential infringement.
As a distributor (Red Hat/Fedora), we take responsibility for not infringing upon others trademarks. 

Like I said though, this seems to be an acceptable use of the marks, though, it could be argued that use of the logo is not necessary if the wordmark will suffice.

**Comment by willbprog127** [comment]
> As a distributor (Red Hat/Fedora), we take responsibility for not infringing upon others trademarks.

That's understandable, and thank you for not being evil. :+1:

**Comment by nowrep** [comment]
Thanks for the notice. I am really no expert in licensing, so if use of those icons really would be a problem, I will remove them.

But those icons are there for a long time already and no distribution had any objections so far.

**Comment by spotrh** [comment]
Trademarked logos are tricky. It can be argued that they are non-free because you cannot practically modify those logos without risking trademark infringement. A bit of crossing the streams between copyright and trademark law.

Our rule of thumb at Red Hat is not to use other people's logos unless it is absolutely necessary.

**Comment by willbprog127** [comment]
And I'm sorry if I talked 'out of turn'.  I'm not part of the QupZilla team, but I'm passionate about the project and don't want to see anything bad happen to it.
