### ISSUE TITLE
On start, home page becomes DuckDuckGo search term

### ISSUE THREAD

**Issue by jamesqf** [QupZilla/qupzilla#1710]
As the title says, I want to start with my preferred home page ("www.google.com/webhp?complete=0").  To do this, in Preferences/General, I set the "After Launch" (sic) field to "Open homepage" (Note that home page is properly two words, not one.), and set the "Homepage" field to the address.  On closing and re-starting the browser, it beomes a somewhat mangled search term for DuckDuckGo: "https://duckduckgo.com/?q=www.google.com%2Fwebhp%3Fcomplete%3D0&t=qupzilla".

If I enter the Google address in the address bar, I sometimes get sent to the UK Google page, not the US one.

I'm using version 1.8.6 on OpenSuSE 13.1.

**Comment by cranes-bill** [comment]
You should type as follow:
`http://www.google.com/webhp?complete=0`

**Comment by jamesqf** [comment]
That works, but I'd call it a workaround, not a solution.  Seems to me that the fact that anything entered into a field which is supposed to be a URL somehow gets turned into a search engine query is symptomatic of a larger problem in the code.  Surely the correct behavior would be to either use the text as URL, or generate some sort of error message?
