### ISSUE TITLE
[RTL] Fixing order of address displayed

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1713]
URL is always LTR, because it always starts with `ftp://` or `http://`.

In RTL locale mode, address such as `http://www.qupzilla.com/`
would appear like `/http://www.qupzilla.com`.

To correct this, an `LRM` character must be added after address displayed.

@srazi please try it yourself or send me a patch that does the above and I will post screenshots.

**Comment by GreenLunar** [comment]
I want to test this change.  Is it still possible to compile QupZilla with Qt4?

**Comment by nowrep** [comment]
Yes it is.

**Comment by GreenLunar** [comment]
With what flag?

**Comment by nowrep** [comment]
With Qt4 qmake.

**Comment by GreenLunar** [comment]
This is the only one I have.  I do not have Qt5 installed.

```
  inflating: qupzilla-master/translations/zh_TW.ts  
   creating: qupzilla-master/windows/
  inflating: qupzilla-master/windows/AllAssociation.nsh  
  inflating: qupzilla-master/windows/install.ico  
  inflating: qupzilla-master/windows/installer.nsi  
  inflating: qupzilla-master/windows/languages.nsh  
  inflating: qupzilla-master/windows/uninstall.ico  
  inflating: qupzilla-master/windows/welcome.bmp  
Project ERROR: QupZilla requires at least Qt 5.5!
build() failed.
```

**Comment by nowrep** [comment]
You must build `v1.8` branch

**Comment by GreenLunar** [comment]
Thank you.

@srazi thank you very much, URL in status bar seems proper with the LRE characters you positioned :)

**Comment by srazi** [comment]
@GreenLunar You're welcome.
Just for record: I'm not expert about bidi algorithm but as I remember in some situations `LRM` is not enough but `LRE` forces text engine to render line as `LTR`

**Comment by GreenLunar** [comment]
I am using Unicode Control Characters for several years; according to my experience __with plain text__ (not code), to solve the above issue, we merely need a single `LRM` characters after URL, as long as URL always starts with an `LTR` character; my test environment is Leafpad, a simple GTK+ 2 text editor.

I might be wrong, and even if I am correct, your solution is great either way.

**Comment by srazi** [comment]
@GreenLunar: Well I think you can not see the difference because currently status-bar didn't show RTL characters and instead it shows percent encoded version that is always LTR.

But for example when URL ends with a strong RTL character:
https://fa.wikipedia.org/wiki/مجید_سمیعی
===> ‫https://fa.wikipedia.org/wiki/مجید_سمیعی
Then LRM can't reorder it.

**Comment by GreenLunar** [comment]
Yes, it is able to reorder it, due to the first character which is LTR (f)tp or h(ttp).  If the first character could have be an RTL character, then your solution is the best solution.

I am almost certain that the solution I originally proposed can fix this too.  I have tested strings that explicitly end with an RTL character, too, with Leafpad.

Again, I rely on tests on a plain text editor.

**Comment by GreenLunar** [comment]
On the other hand, you might be right, if the reversed layout of Qt has the same or a similar effect to inserting an RLM or RLE character at the start of the string we discuss on.

**Comment by srazi** [comment]
@GreenLunar I can think of two options:
1) You tested it wrongly
2) Leafpad has bug in its bidirectional algorithm implementation (but as it uses GTK+ and as I think GTK+ uses fribidi then this should not be the case)

And for closing this discussion: I tested it with Firefox-41.0.2, Windows Notepad and QupZilla.

**Comment by GreenLunar** [comment]
> 2) Leafpad has bug in its bidirectional algorithm implementation (but as it uses GTK+ and as I think GTK+ uses fribidi then this should not be the case)

Only if I put an RLM or RLE at start of line, RLM seems to be ineffective in correcting URLs that either explicitly end with an RTL or a neutral character.

GTK+, as far as I am concerned has the best BiDi algorithm implementation, next would be Qt with some very slight differences.

**Comment by srazi** [comment]
> Only if I put an RLM or RLE at start of line, RLM seems to be ineffective in correcting URLs that either explicitly end with an RTL or a neutral character.

Oops then its bug of Leafpad because RLM should just work locally i.e. for the character after/before it and not the whole line, it seems Leafpad internally changes RLM to RLE and LRM to LRE.

**Comment by GreenLunar** [comment]
No, Leafpad (GTK+) manifests Unicode Control Characters properly; this whole thing is very confusing, and we probably interpret each other wrongly, especially myself.

I think that RTL languages on digital mediums should have, until today, be always written from left-to-write, like English, and be outputted (e.g. in paper print, wysiwyg, gui) reversely.
