### ISSUE TITLE
Handle certificate files (.crt) from QupZilla

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1714]
When clicking on http://example.org/filename.crt QupZilla opens download dialog instead of offering user ways to install certificate file.

http://www.autistici.org/static/certs/ca.crt
http://www.autistici.org/en/ca/index.html
http://www.inventati.org/en/index.html

**Comment by nowrep** [comment]
It was already reported, this is not supported in QtWebKit.

**Comment by GreenLunar** [comment]
Why does it depend on QtWebKit?
