### ISSUE TITLE
JavaScript issues

### ISSUE THREAD

**Issue by chaotickjg** [QupZilla/qupzilla#1715]
I've noticed that some stuff on sites that utilize JavaScript don't seem to work, such as menus and dialog boxes that appear within the web page. I've noticed this on GitHub when working with my one repositories, with things like adding an SSH key or clicking the "profile menu" in the top-right corner of the page. This *might* be related to issue #1668 , as that is exactly an issue I had with GitHub shortly after noticing the other JavaScript-related problems.

**Comment by nowrep** [comment]
This is issue with old WebKit that comes with QtWebKit.
This will be fixed with QtWebEngine.
