### ISSUE TITLE
Qupzilla doesn't handle system volume settings

### ISSUE THREAD

**Issue by cicku** [QupZilla/qupzilla#1716]
OS: Fedora
DE: GNOME 3
Sound server: Pulseaudio

I often listen to music online ([Exp: This one](http://music.163.com/)), and I find the annoying part is, even if I have set global volume, qupzilla still modifies the settings and blasts my ear.

I'm not sure why I meet this ONLY in qupzilla but not Google Chrome, perhaps they've handled this by some implementions inside before hitting pulseaudio.

In common, modifying the global volume proportionally adjusts the volume of applications, but qupzilla certainly doesn't follow the rule. I hope this can be fixed/wrapped as soon as possible.

**Comment by The-Compiler** [comment]
QupZilla (or QtWebKit rather) adjusts its own application volume, and PulseAudio thinks [it's a good idea](https://www.reddit.com/r/linux/comments/2rjiaa/horrible_decisions_flat_volumes_in_pulseaudio_a/) to link the system volume to that.

Turn off `flat-volumes` in your `~/.config/pulse/daemon.conf` or `/etc/pulse/daemon.conf` and it should be much more sane.

**Comment by cicku** [comment]
i know, and I've done this.

Recently in Fedora devel, there is a debate about this: 

https://lists.fedoraproject.org/pipermail/devel/2015-September/214720.html

So might be a fault from distro package? (to not disable it as default)

**Comment by cranes-bill** [comment]
I did that as well and it's better now, but from time to time it still increase the volume level to 100% and i fail to locate the reason about that. In general, the Pulsaudio volume control is a quite bad working from any Qt application to me.

**Comment by The-Compiler** [comment]
> So might be a fault from distro package? (to not disable it as default)

IMHO, it's a problem with PulseAudio (having this stupid and harmful default), and with each distro package which doesn't disable it :wink:

I've talked to the QtWebKit maintainer about this, and it's unlikely Qt/QtWebKit can easily do anything to make this situation better.

Either way, I don't think QupZilla can do anything about this, as it's handled by QtWebKit. It might be better with the QtWebEngine backend though?

**Comment by nowrep** [comment]
Sorry, there's nothing to do. I hope QtWebEngine handles it better.

(I am myself using pulseaudio with disabled flat-volumes for a long time and never had this issue again :)

**Comment by cicku** [comment]
I'd ask Fedora maintainer to switch off flat as default. Thank you all for this nice conversation.
