### ISSUE TITLE
webhittestresult.h is missing

### ISSUE THREAD

**Issue by HJarausch** [QupZilla/qupzilla#1718]
I can't compile qupzilla on my Gentoo system anymore.
The command

x86_64-pc-linux-gnu-g++ -c -mtune=native -O2 -msse3 -pipe -Wall -W 
-D_REENTRANT -fPIC -DQUPZILLA_VERSION=\"1.8.7\" -DNONBLOCK_JS_DIALOGS 
-DUSE_QTWEBKIT_2_2 -DQT_NO_URL_CAST_FROM_STRING -DQT_USE_QSTRINGBUILDER 
-DUSE_QTWEBKIT_2_3 -DUSE_LIBPATH=\"/usr/lib64\" 
-DUSE_DATADIR=\"/usr//share/qupzilla\" -DGIT_REVISION=\"eda5a64de1\" 
-DQZ_WS_X11 -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WEBKITWIDGETS_LIB -DQT_WIDGETS_LIB 
-DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB 
-I. -I../../lib/3rdparty -I../../lib/adblock -I../../lib/app 
-I../../lib/autofill -I../../lib/bookmarks -I../../lib/cookies 
-I../../lib/downloads -I../../lib/history -I../../lib/navigation 
-I../../lib/network -I../../lib/notifications -I../../lib/opensearch 
-I../../lib/other -I../../lib/plugins -I../../lib/popupwindow 
-I../../lib/preferences -I../../lib/rss -I../../lib/session 
-I../../lib/sidebar -I../../lib/tabwidget -I../../lib/tools -I../../lib/webkit 
-I../../lib/webtab -isystem /usr/include/qt5 
-isystem /usr/include/qt5/QtWebKitWidgets -isystem /usr/include/qt5/QtWidgets 
-isystem /usr/include/qt5/QtWebKit -isystem /usr/include/qt5/QtGui 
-isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore 
-Ibuild -I/usr/lib64/qt5/mkspecs/linux-g++ -o build/copytitle.o copytitle.cpp

fails with

copytitle.cpp:24:30: fatal error: webhittestresult.h: No such file or directory
I have qt-5.5.9999 installed here.

**Comment by nowrep** [comment]
Use `v1.8` branch of qupzilla-plugins
