### ISSUE TITLE
Facebook chat does not show conversation

### ISSUE THREAD

**Issue by nerdouille** [QupZilla/qupzilla#1722]
Using 1.8.7 built on debian, facebook works almost flawlessly except when I try to open a conversation: http://s28.postimg.org/47vi7kdpp/bug.png the blue progression thingy loops endlessly and the conversation area stays empty. Any ideas?

**Comment by JHooverman** [comment]
Did you try [this](https://github.com/QupZilla/qupzilla/wiki/FAQ#15-i-have-problems-with-the-facebook-web-page-how-can-i-fix-it)? What is your qt- & qtwebkit-version?

**Comment by nerdouille** [comment]
Ah thanks JHooverman, it works with the user agent trick. Should have browsed the FAQ now I feel stupid :p
