### ISSUE TITLE
Native Icon not in use (Xubuntu 15.04 64 bits, qupzilla 1.8.6)

### ISSUE THREAD

**Issue by cedorfgt** [QupZilla/qupzilla#1725]
Hi,

I installed qupzilla 2 minutes ago, the Icon is nowhere in the upper bar of my OS to see (attachment is a shot of the upper left part of my screen, the firefox icon can be seen, instead of the qupzilla icon there is a generic icon
![zzzz](https://github-cloud.s3.amazonaws.com/assets/11744808/10565163/5a5664dc-75ca-11e5-8909-49c1e9bff3a6.png)
). Plus, if I want to watch youtube videos I need to reload the page twice. Is that normal? I watch videos not behind a proxy.

**Comment by cranes-bill** [comment]
The following should help:
`sudo gtk-update-icon-cache /usr/share/icons/hicolor/`
About Youtube, probably you are using Flash and you have extension **Click to Flash** active!?

**Comment by nowrep** [comment]
Can you check if the icon is correct in window switcher (alt + tab)?

**Comment by cedorfgt** [comment]
Checked. And no, all I see is the generic icon
    
    On 10/19/2015 04:43 PM, David Rosca
      wrote:
    
    
      Can you check if the icon is correct in window switcher (alt +
        tab)?
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
looking forward to hearing from you
ich freue mich auf deine Antwort

**Comment by cedorfgt** [comment]
I did that, sudo gtk-update-icon-cache
      /usr/share/icons/hicolor/ , and there are no changes
    
    On 10/19/2015 07:30 AM, cranes-bill
      wrote:
    
    
      The following should help:
        sudo gtk-update-icon-cache /usr/share/icons/hicolor/
        About Youtube, probably you are using Flash and you have
        extension Click to Flash active!?
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
looking forward to hearing from you
ich freue mich auf deine Antwort

**Comment by cranes-bill** [comment]
May be you should wait a David's answer, because when he ask you for _window switcher_, might have something on mind!
Nevertheless, my guess that is similar as #1666, so you can try something like [that](http://mikemcquaid.com/2011/12/01/make-qt-use-the-gtk-style-on-xfce-or-xubuntu/)
P.S.: regarding to my previous post here, i'm assuming you have installed Qupzilla in prefix `/usr`, if not, you should replace it!

**Comment by nowrep** [comment]
Hmm, I have no idea. There is a check when setting window icon if the icon from theme is null, and if it is null then a built-in icon is used. So it should not fail.

What about other icons in application?

**Comment by cedorfgt** [comment]
curiously upgrading to 1.8.8 solved the issue
    
    On 10/22/2015 04:54 PM, David Rosca
      wrote:
    
    
      Hmm, I have no idea. There is a check when setting window icon
        if the icon from theme is null, and if it is null then a
        built-in icon is used. So it should not fail.
      What about other icons in application?
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
looking forward to hearing from you
ich freue mich auf deine Antwort

**Comment by nowrep** [comment]
Cool :D

**Comment by BethAr** [comment]
I'm getting the same problem on Xubuntu 16.04, Qupzilla 1.8.9.
