### ISSUE TITLE
QupZilla with the WebKit in the future

### ISSUE THREAD

**Issue by anseki** [QupZilla/qupzilla#1726]
Hi, thank you for nice app!

I have a question.
I read the information about QupZilla with the QtWebEngine in FAQ.
So, does QtWebKit be not supported in the near future?
I use QupZilla to test the web page or web app with WebKit on Windows. I think that there is no good WebKit-browser for Windows except QupZilla.

**Comment by nowrep** [comment]
The future is `v1.8` branch, that is only bugfixes with minor new features.

**Comment by anseki** [comment]
Ok, thanks :smiley:
