### ISSUE TITLE
Compilation error: QWebEngineUrlRequestInfo: No such file or directory

### ISSUE THREAD

**Issue by mithat** [QupZilla/qupzilla#1729]
I am trying to compile from the QupZilla repo using Qt version 5.5.1 in aptosid Linux (Debian sid derivative). I am getting the following error:
```
In file included from adblock/adblockurlinterceptor.h:22:0,
                 from adblock/adblockurlinterceptor.cpp:19:
network/urlinterceptor.h:23:36: fatal error: QWebEngineUrlRequestInfo: No such file or directory
```

Qt has been installed from upstream and the following are on my PATH:
```
$HOME/Qt/Tools/QtCreator/bin
$HOME/Qt/5.5/gcc/bin
```

Any ideas?

**Comment by mithat** [comment]
My mistake. The master branch appears to require Qt5.6. I'll try the qt5.5 branch and report back.

**Comment by nowrep** [comment]
Yes, that's correct.
