### ISSUE TITLE
[i18n] qupzilla:config should not be subjected to translation

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1733]
I think that page *qupzilla:config* should not be subjected to translation, except first and last lines *Configuration Information* and *This page contains information about QupZilla's current configuration - relevant for troubleshooting. Please include this information when submitting bug reports.*

**Comment by nowrep** [comment]
Why not?

**Comment by GreenLunar** [comment]
Because it is sent to QupZilla developers.  Do you, or any of the other developers need that page in languages other than English?

**Comment by pejakm** [comment]
What and how is being sent to developers?

**Comment by nowrep** [comment]
Settings entries [key, value] are not translated, and that's the only thing that matters.

**Comment by GreenLunar** [comment]
> What and how is being sent to developers?

Sorry, I mean that it is intended for QupZilla developers.

> Settings entries [key, value] are not translated, and that's the only thing that matters.

Indeed.  Perhaps I should have asked to set table direction from left-to-right.
