### ISSUE TITLE
Replace StartPage by searx/Seeks

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1734]
[Remove Startpage](https://github.com/nylira/prism-break/issues/1251) due to privacy risks such as advertisements and unwanted results by geo IP.

Add [searx](https://github.com/asciimoo/searx/wiki/Searx-instances) (includes StartPage and [many more](https://github.com/asciimoo/searx/tree/master/searx/engines), and i18n support) or [Seeks](https://github.com/beniz/seeks/wiki/List-of-Web-Seeks-nodes) which do not search according to geo IP of user, and have no advertisements.

**Comment by GreenLunar** [comment]
Unless the people who run it pay to QupZilla, then , of course, keep it. [THIS COMMENT BE DELETED]

**Comment by nowrep** [comment]
StartPage is there only because someone requested it, I get no advertisement revenue at all (and probably the ads are also blocked?).

**Comment by GreenLunar** [comment]
I assume the advertisements are blocked.  As long as StartPage don't pay you money, remove it; there are better alternatives.

I guess the person who requested it to be included, would like searx much more.  searx also can be configured to use only one search provider.

**Comment by pejakm** [comment]
StartPage does respect privacy, AFAIK.

**Comment by nowrep** [comment]
Can you send url of searx?

**Comment by GreenLunar** [comment]
Name | Value
------------ | -------------
URL | https://searx.me/
Post info | q=%s

There are more nodes at https://github.com/asciimoo/searx/wiki/Searx-instances

**Comment by cicku** [comment]
Honestly being as a user, I have no interests on so-called safe engines. You could set this as the default engine though.

**Comment by GreenLunar** [comment]
> Honestly being as a user, I have no interests on so-called safe engines.

I might agree with your opinion; but even if I certainly do, would not it be good to market a proxy and meta search engine that enhances users privacy?

**Comment by GreenLunar** [comment]
By the way, searx developers knows that my preferred search engine is [Seeks](https://beniz.github.io/seeks/).  My considerations to ask to add searx to QupZilla are end-user friendliness, localization, active development and a bigger variety of search engines.

Perhaps some of this reasons are amongst the reasons of why the main developer of Seeks has recently contributed patches to searx.

**Comment by cicku** [comment]
NVM, I was just elucidating my opinion, that users only want to get info they want as soon as possible, privacy is the second thing they will handle.

I agree that homepage is a bit slanted to qupzilla upstream, I personally don't like the style. But still don't have idea what it should be if we really want to make a change on it. 

btw I should say that no matter how great these engines are, they will be blocked in my country finally. Duckduckgo sucks now.

**Comment by GreenLunar** [comment]
> btw I should say that no matter how great these engines are, they will be blocked in my country finally. Duckduckgo sucks now.

Proxy search engines such as Seeks, searx, MySearch and YaCy are good solutions to circumvent censorship and unwilling result personalization.

**Comment by GreenLunar** [comment]
This is why

You --> searx node in country x --> Results
You --> searx node in country y --> Results
You --> searx node in country z --> Results

Country x is subjected to censorship; countries y and z are not.

**Comment by ke7ofi** [comment]
@cicku What's wrong with DDG?

**Comment by cicku** [comment]
@ke7ofi DDG has already been blocked in our country.

**Comment by ke7ofi** [comment]
@cicku Wouldn't that mean the government, rather than DDG, sucks? (and could you get in trouble for saying so?)

**Comment by cicku** [comment]
DDG still sucks, it's better than bing only, not even startpage.com. Google is still the best.

**Comment by ke7ofi** [comment]
I don't mean to get into a holy war (I didn't know people had those over search engines!), but I find that interface matters more to me than algorithm, so the bangs and customisation win out for me.

**Comment by GreenLunar** [comment]
I think searx has "bangs", too.  searx also has a plugin system.

@asciimoo, please correct me if I am wrong.

**Comment by ke7ofi** [comment]
Searx has its own “bangs” and inherits all the features of DDG; I just don't find it any better, and it's still just as dependent on closed-source software. Also, the downside of inheriting features is that there are now two or three ways to do “bangs”, each with their own set of available sites.

If someone wanted to set up an instance on a VPS or something, that could be fixed a bit, but I don't see the point in using something besides DDG unless it's YaCy or seeks, but neither of those build for me and they're not very actively developed.

**Comment by juancarlospaco** [comment]
Please add SearX as search engine. :+1:
