### ISSUE TITLE
Problem with vanishing Status bar icons - Windows, latest Qupzilla version

### ISSUE THREAD

**Issue by SJ-Diamond** [QupZilla/qupzilla#1736]
Hi!

As the topic says, i have problems with the status bar icons. In fact the only one which works flawless are the additional icons options - if i add something like tab manager or one of the other built in extensions, all icons vanish out of the statusbar.

If i let alone the option Status Bar Icons activated, after a restart these icons still are shown. Seems, when activating one of these other built in extensions, Qupzilla forgets what was set in the options and resets this selection by itself the next browser start.

**Comment by SJ-Diamond** [comment]
Happened right now again, only that i changed the global user agent. Saved, exit the browser, fresh restart, status bar icons gone! There is clearly some kind of bigger conflict which refuses to let the Status bar icons and extensions work in a proper way under certain conditions and in certain combinations.

**Comment by JHooverman** [comment]
This is a reproducible test case for me:

(1) Disable all extensions
(2) Restart QupZilla
(3) Enable `StatusBarIcons`-Extension
(4) Restart QupZilla
(5) Enable `Access Keys Navigation`-Extension
(6) Restart QupZilla

Result: The Status Icon Bar is disappeared, the Checkbox in `Preferences -> Extensions` is unchecked. This result is reproducible, with step (5) =

Enable `Auto Scroll`-Extension
Enable `Grease Monkey`-Extension
Enable `Auto Scroll`- & `Access Keys Navigation`-Extension

Probably there might be other combinations, which lead to the behaviour as described above.

Tested with:
Application version: 1.8.9
Qt version: 5.5.1
WebKit version: 538.1
Platform: Windows 7

**Comment by nowrep** [comment]
This should be fixed in QupZilla 2.
