### ISSUE TITLE
Ctrl-Enter sucks

### ISSUE THREAD

**Issue by cicku** [QupZilla/qupzilla#1737]
Hi folks,

I'd say comparing to Google Chrome, qupzilla sucks on this at least. I intended to visit www.github.com, I typed github and url box returned github.com automatically, that's great.

But when I pressed Ctrl-Enter, qupzilla entered github.com.com, an advertising website with junks instead.

Well, this is not expected :joy: Qupzilla shouldn't handle it in this way.

**Comment by nowrep** [comment]
And why did you press Ctrl+Enter instead of just Enter?

**Comment by cicku** [comment]
It's been a habit for at least a decade, IE and thus Google Chrome use Ctrl-Enter to let users go to .com websites quickly, now Microsoft Edge and Firefox have adopted this for a long time. Safari has adopted this as well for a long time but it uses Command+Enter.

Ctrl-Enter does:

```One enters `XYZ` in URL box and press Ctrl-Enter, then the browser will go to www.XYZ.com.```

Even more specific, IE will return `XYZ.com.cn` if current locale is Chinese back to IE6 era.
