### ISSUE TITLE
Adblock not working

### ISSUE THREAD

**Issue by droserasprout** [QupZilla/qupzilla#1738]
Here is two screenshots of [this] (http://www.angelfire.com/alt2/entertainment/ad_block_test.html) page: opened in [Pale Moon with uBlock Origin] (http://i.imgur.com/4AQ1lFu.png) and in [Qupzilla with same subscriptions] (http://i.imgur.com/3E9Piiw.png). I use git version of Qupzilla v1.8.0.r142.g8d7cfb0-1 on Arch Linux.

**Comment by nowrep** [comment]
That's because AdBlock only works with QtWebEngine 5.6+
