### ISSUE TITLE
Crashes when I unplug the USB mouse

### ISSUE THREAD

**Issue by ltworf** [QupZilla/qupzilla#1741]
Or when I plug it. It's really weird to be honest. But there it is. It happens very often but not always.

I am using it on Debian Sid.

**Comment by nowrep** [comment]
Can you post backtrace?

**Comment by The-Compiler** [comment]
This was a Qt bug which was fixed in Qt 5.4 or so as far as I know.

**Comment by ltworf** [comment]
Well I have Qt 5.5

**Comment by ltworf** [comment]
Hod do I get a backtrace? Do I need to recompile?

**Comment by cranes-bill** [comment]
It should be in ~/.config/qupzilla/crashlog
Copy and paste it [here](https://gist.github.com/)! _(Try with middle button :smile:)_
Do you sure that your mouse is not damaged!?

**Comment by ltworf** [comment]
https://gist.githubusercontent.com/ltworf/5592a0fb4afbaa6d8a05/raw/6013f79496785ea3e48704c24b9f8b3fc5ed6613/gistfile1.txt

However it is from 2 days ago, no other logs were created for the more recent crashes.

Dmesg doesn't report any complaints about my mouse, and it works fine with everything else except qupzilla. It would be a really weird malfunction.

**Comment by ltworf** [comment]
Also, this bug also occurs upon suspend/resume, with no external USB mouse involved.

**Comment by nowrep** [comment]
I would suggest you to rebuild with latest Qt.

But this is not issue in QupZilla.
