### ISSUE TITLE
Middle click doesn't work

### ISSUE THREAD

**Issue by ltworf** [QupZilla/qupzilla#1742]
Pasting with the middle button doesn't work.

This is EXTREMELY annoying.

**Comment by nowrep** [comment]
Works here. What plugins are you using?

**Comment by ltworf** [comment]
Tab manager is enabled.

**Comment by ltworf** [comment]
Ok upon further testing, it is in specific input areas that it doesn't work.

For example in https://gist.github.com/ it won't work, but ctrl+v will.

**Comment by nowrep** [comment]
No problems here, works as expected.

**Comment by ke7ofi** [comment]
@ltworf Is this a QupZilla thing or a clipboard thing?

**Comment by nowrep** [comment]
Actually my comment was to different issue, sorry :D 
I can experience the issue on gist.github.com also with Firefox.

**Comment by nowrep** [comment]
It works, but it uses clipboard instead of selection for pasting to textarea.

**Comment by nowrep** [comment]
And even Chrome has issues with pasting to that textarea, so it is github's issue.
