### ISSUE TITLE
Decorative gradient in bookmarks, RSS, etc.

### ISSUE THREAD

**Issue by ke7ofi** [QupZilla/qupzilla#1743]
It's not customisable and doesn't match the Qt theme. Is there any practical way to kill it?

**Comment by cranes-bill** [comment]
If you mean that it's marked on the following picture, you can just change the images!?
![capture du 2015-11-04 21 03](https://cloud.githubusercontent.com/assets/5161278/10949374/42c842f8-833b-11e5-955a-4c6e55f563cf.png)

**Comment by ke7ofi** [comment]
@cranes-bill Yes, how?

**Comment by nowrep** [comment]
Yes, you can edit it in stylesheet.

**Comment by ke7ofi** [comment]
@nowrep As far as I can tell, they're in `usr/share/qupzilla/themes/linux/images` (matching `library*`). Is there any plan to make that more theme-dependent (maybe a solid color taken from the Qt theme?)?

**Comment by cranes-bill** [comment]
There is a few more themes [here](https://github.com/QupZilla/qupzilla-plugins/tree/master/themes), so you might like some of them.

**Comment by ke7ofi** [comment]
I see; that makes sense. It seems, however, like it would make more sense to consistently stick with either the “You edit the files.” approach or the “Click something from a menu.” approach, but I see a lot of both.

The first would be more Unixy, but the second is more standard. My recommendation (speaking, of course, as someone who does no programming outside of shell scripts) would be to at least consistently provide text boxes to specify paths, as that would indicate that they're meant to be changed.

**Comment by nowrep** [comment]
Everything is configurable to some point, be it changing it in preferences, changing it in text file or changing it in source code and recompiling.

If you don't like the gradient, you can change it in stylesheet. However, this is not "officially" configurable.
