### ISSUE TITLE
Network access is disabled.

### ISSUE THREAD

**Issue by ke7ofi** [QupZilla/qupzilla#1744]
When I try to load a page (in this example, DuckDuckGo) after suspending (I assume the issue is reconnecting to the internet.), I get the following message.

> Network access is disabled.

> QupZilla can't load page from ddg.gg.

> * Check the address for typing errors such as ww.example.com instead of www.example.com

> * If you are unable to load any pages, check your computer's network connection.

> * If your computer or network is protected by a firewall or proxy, make sure that QupZilla is permitted to access the Web.

Restarting QupZilla solves the problem, but it's quite irritating.
![screenshot]()

**Comment by nowrep** [comment]
https://bugreports.qt.io/browse/QTBUG-46323

**Comment by ke7ofi** [comment]
@nowrep Sorry about #1745, I thought I could edit the name without changing issue number.

**Comment by mathieujobin** [comment]
that Qt Bug is closed, and it links to this https://codereview.qt-project.org/#/c/121724/
which got merged into 5.5, I have Qt 5.6.1

networkAccessibilityChanged signal supposed to be emitted

**Comment by troffasky** [comment]
Still a problem on Qt 5.7.1. To rub salt into the wound, it even resolves the host [look at the status bar] before telling you that there's no internet access to connect to it with!
