### ISSUE TITLE
Putting bangs in the address bar (ex: for DDG) just makes everything go away.

### ISSUE THREAD

**Issue by ke7ofi** [QupZilla/qupzilla#1746]
In Firefox, typing “foobar!w” in the address bar takes me to https://duckduckgo.com/?q=foobar!w. In Qupzilla, the same action empties the address bar. I'm not sure why.

**Comment by ke7ofi** [comment]
If it helps at all, ^Z doesn't restore it.

**Comment by cranes-bill** [comment]
@nowrep, i hope the following will help a little bit:

It works if have whitespace between `bang` and the word as i always used it so far.
Also on **qupzilla:start** page it works only if `bang` is after the word. If before, go to search, but with `bang` alongside...

**Comment by nowrep** [comment]
With `master` it works fine. With `v1.8` it works in qupzilla:start, but not in locationbar.
