### ISSUE TITLE
C-Tab behavior is strange

### ISSUE THREAD

**Issue by ke7ofi** [QupZilla/qupzilla#1747]
I typed Alt instead of Control in the video, but here's what I'm seeing (running `qupzilla-git`, updated last night, from the AUR/here):

[It seems to only cycle through alternating tabs, rendering half of them unreachable without mouse/Alt+# when there are an even number.](https://u.teknik.io/8KyzCx.webm)

**Comment by ke7ofi** [comment]
…and the non-default framerate somehow made it look very, very long. It's not.

**Comment by nowrep** [comment]
No problems here, works as expected.

**Comment by ke7ofi** [comment]
Maybe it has to do with tab settings? The only one I have checked is “Hide tabs when there is only one tab”. (Can anyone else reproduce it? I'm running Application version 1.9.0 (32fe733af7)
QtWebEngine version 5.5. on Arch.)

**Comment by ke7ofi** [comment]
I went back to the official repo version (1.8.8), and the problem's gone. Is there anything tab-related that's changed since then?

**Comment by nowrep** [comment]
`master` does not build with QtWebEngine 5.5

**Comment by ke7ofi** [comment]
Sorry to bug (pun initially unintended) you with something you already knew. Should I close this, or do you want to label it as an upstream problem?

**Comment by nowrep** [comment]
No, I'm not aware of this issue, I'm just saying that `master` does not build with QtWebEngine 5.5 so I'm not sure what version you are really running.

That being said, it is possible that this bug is actually valid. I didn't test it yet.

**Comment by ke7ofi** [comment]
I was running 1.9.0.

**Comment by nowrep** [comment]
Only `master` (1.9.x) was affected.
