### ISSUE TITLE
Bad formatting on some sites with Qt 4

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#1751]
What might be the reason of this difference:
#### QT 4
![capture du 2015-11-07 13 05 07](https://cloud.githubusercontent.com/assets/5161278/11014981/539b7274-8554-11e5-8582-a7c7c37874c1.png)
#### QT 5
![capture du 2015-11-07 13 06 46](https://cloud.githubusercontent.com/assets/5161278/11014983/64d2c51a-8554-11e5-9fdd-70421af9019b.png)

[This](http://www.formula1.com/) is not the only one site, where i see this issue.
I was testing many variants as changing the fonts, Adblock disabling, a quite new profile, but had no change.

QT 4        |  QT 5
------------ | -------------
1.8.8 (b19dc84) | 1.8.8 (94d89e4)
Webkit 537.21 | Webkit 538.1

**Comment by nowrep** [comment]
Just bug in older version of QtWebKit, nothing to do about it.

**Comment by cranes-bill** [comment]
As i was guessing, thank you!
