### ISSUE TITLE
HTML 5 video play full screen crash

### ISSUE THREAD

**Issue by ademcal** [QupZilla/qupzilla#1754]
I have my crash file 
.config/qupzilla/crashlog/Crash-2015-11-09T00:42:49.txt

Time: Sun Nov 1 12:41:58 2015
Qt version: 5.5.1 (compiled with 5.5.1)
QupZilla version: 1.8.8
WebKit version: 538.1

============== BACKTRACE ==============
#0: /usr/bin/qupzilla() [0x403483]
#1: /usr/lib/libc.so.6(+0x33680) [0x7f4bae757680]
#2: /usr/lib/mozilla/plugins/libflashplayer.so(+0x6513ae) [0x7f4a58ff93ae]
#3: /usr/lib/libpthread.so.0(+0x74a4) [0x7f4bac0284a4]
#4: /usr/lib/libc.so.6(clone+0x6d) [0x7f4bae80d13d]

I tried run on terminal

Vector smash protection is enabled.
void QWindow::setTransientParent(QWindow*) QWidgetWindow(0x65dc340, name = "TabbedWebViewClassWindow") must be a top level window.
void QWindow::setTransientParent(QWindow*) QWidgetWindow(0x65dc340, name = "TabbedWebViewClassWindow") must be a top level window.
The program 'qupzilla' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 30 error_code 3 request_code 3 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by nowrep** [comment]
Sorry, this is crash in flashplayer.

**Comment by ademcal** [comment]
it's weird I tried in Firefox it isnot problem

**Comment by nowrep** [comment]
Unfortunately QtWebKit integration with npapi plugins (and flash especially) is not ideal.

**Comment by ademcal** [comment]
I don't understand these Firefox use same flash player version it's nearly perfect

**Comment by nowrep** [comment]
Well, this is not Firefox.

Anyway, this will be fixed with QupZilla 2.0 that will use QtWebEngine.

**Comment by ademcal** [comment]
Thanks. I am thinking I installed Chrome it has not problem with HTML5 HD videos it doesn't with Flash Player according to me  I will check in 2.0 version. 

On the other hand I have one problem about compability it is particularly about shopping sites

**Comment by ademcal** [comment]
for example I will choose product specs, the mini window opens left upper side
