### ISSUE TITLE
QupZilla 1.8.8 - Buttons on Github Not Working

### ISSUE THREAD

**Issue by Geyup** [QupZilla/qupzilla#1756]
I've had this same problem in the past, where clicking on the Edit button, or my drop down for my user's preferences on github, these do not work in 1.8.8 in Linux.

I compiled in Slackware with QT 4.8.7 
WebKit version 534.34

Seems like QupZilla keeps going around in circles with the same bugs reappearing over and over... :(

**Comment by JHooverman** [comment]
Please have a look [here](https://github.com/QupZilla/qupzilla/issues/1669). Your issue is QtWebkit-related.

**Comment by Geyup** [comment]
The README file needs to be updated or changed to reflect to use QT5...

I compiled against QT4...

**Comment by JHooverman** [comment]
@Geyup: Generally speaking, QupZilla might be compiled against Qt4 and Qt5. However, the browsing experience is much better with Qt5. We already had a similar discussion about this [here](https://github.com/QupZilla/qupzilla/issues/1504). Maybe you want to have a look at it.

@nowrep: Would you mind, if I modify the README in branch [v1.8] to

Before you start compiling, make sure that you have installed the Qt (>=4.7) development libraries and you have read the BUILDING information. We recommend to use Qt-5.4 to allow a better web experience.

**Comment by Geyup** [comment]
Slack includes DEV stuff as it relates to 4.7...

I compiled it this time against QT 5.5.0 which gives; ```WebKit version 538.1```

**Comment by JHooverman** [comment]
@Geyup: Is your issue solved after compiling QupZilla against Qt-5.5.0?
