### ISSUE TITLE
Broken Site - imgur.com doesn't work with QupZilla

### ISSUE THREAD

**Issue by Geyup** [QupZilla/qupzilla#1757]
In Linux, for the past 3 versions of QupZilla, and now using 1.8.8, I've never been able to get this site to work.

If I log in, all it does is show their loading icon, trying to load the site and it never loads, just sits there spinning around...

**Comment by JHooverman** [comment]
Please see #1756. Your QtWebkit-534.34 is very old and will prevent some sites from being loaded correctly. Try to upgrade QtWebkit to a more recent version or try to make use of QtWebengine.

**Comment by Geyup** [comment]
My webkit is ONLY old because whoever wrote the README is telling people to compile with QT4.

So does the README need to be updated to compile against QT5 instead?
