### ISSUE TITLE
Downloading file problem

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#1758]
*Regarding to my comments in #1755, i'm moving them as new issue here.*

Trying to download [this](http://packages.slackonly.com/pub/packages/current-x86_64/desktop/awoken-icon-theme/awoken-icon-theme-2.5-noarch-1_slack.txz), i'm getting the following error:

```
WebPage::UnsupportedContent  QUrl( "http://packages.slackonly.com/pub/packages/current-x86_64/desktop/awoken-icon-theme/awoken-icon-theme-2.5-noarch-1_slack.txz" )  ProtocolUnknowError 
WebPage::UnsupportedContent  QUrl( "http://packages.slackonly.com/pub/packages/current-x86_64/desktop/awoken-icon-theme/awoken-icon-theme-2.5-noarch-1_slack.txz" )  ProtocolUnknowError 
WebPage::desktopServicesOpen Url  QUrl( "http://packages.slackonly.com/pub/packages/current-x86_64/desktop/awoken-icon-theme/awoken-icon-theme-2.5-noarch-1_slack.txz" )  has already been opened!
```
^^^^^^^^^^^^^^^^^ THE ABOVE HAS 3 TIMES REPEATED ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 `Ignoring it to prevent infinite loop!`
 plus this from Qt 5 `(../../../src/lib/webkit/webpage.cpp:439, void WebPage::desktopServicesOpen(const QUrl&))`

@nowrep says: [Well, that's fine unless it doesn't stop.](https://github.com/QupZilla/qupzilla/issues/1755#issuecomment-155097446)

**Then i'm said:** It stops, but does not downloading the archive!
**And now continue:**
When marking the link and hit "Follow the web address" it opens two empty pages.
I have a very simple QtWebKit browser «(even can't remember where i was downloaded it from), and it downloading the file without returning the errors, so i'm excluding QtWebKit issue here.

**EDIT:** The mentioned above simple browser: [:package:](https://yadi.sk/d/BiVmvosLkMtHM)

**Comment by cranes-bill** [comment]
Even i did not understand is that only to me occurs....
No matter, i'm just closing it.

**Comment by nowrep** [comment]
No, it's just that this is QtWebKit bug...

**Comment by cranes-bill** [comment]
I'm able to triggering a crash with **Qt 5**, when build with `DOWNMANAGER_DEBUG` flag.
[This](https://gist.github.com/cranes-bill/aaf5f2393c2572162f3b) is a log file from crash reports folder.
And [this](https://gist.github.com/cranes-bill/bb47fdb09501b9ea6ca4) is backtrace from **GDB**.
Please close this issue again, if the above has nonsense!

**Comment by nowrep** [comment]
It crashes in `WebCore::FrameLoaderClientQt::convertMainResourceLoadToDownload` so this is upstream crash.
