### ISSUE TITLE
[v1.8] HTML 5 video crash

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#1764]
This is probably an system issue, but just to be sure:
Qupzilla (Qt4) crashing any time and (Qt5) sometimes, when i'm trying to visit [this](http://www.w3schools.com/HTML/html5_video.asp) site.
The same with Qt4 TestBrowser
»»»»»»»»»»»»»»» [BACKTRACE](https://gist.github.com/anonymous/e278d73220766f989a16) «««««««««««««««
______________________________
Qt version: 4.8.5 (compiled with 4.8.5)
QupZilla version: 1.8.9 (9de5275)
QtWebKit version: 537.21

**Comment by nowrep** [comment]
That's crash in GStreamer.
