### ISSUE TITLE
Yahoo problems - delete does not work for mail, cannot preview news stories

### ISSUE THREAD

**Issue by mrjacque** [QupZilla/qupzilla#1770]
When I either check the box and click DELETE or am reading an email and hit DELETE, the mail remains on my list. 
When viewing the news stories, on other browsers when I hover over a picture in the news pictures, that picture shows above the preview with additional information. In Qupzilla, stays on first picture.

**Comment by JHooverman** [comment]
Please let us know about your configuration (`Menu -> Configuration information`) as shown in the following example:

Application version: 1.9.0 (ee80b04a11)
Qt version: 5.4.2
WebKit version: 538.1
Build time: Jan 25 2015 16:47:02
Platform: openSUSE Tumbleweed (Linux)

**Comment by mrjacque** [comment]
Information about version
Application version
1.8.9
Qt version
4.8.5
WebKit version
537.21
Platform
Linux

**Comment by JHooverman** [comment]
These types of issues typically occur, when the qt and/ or qtwebkit version is too old - as in your case. Please try to update your qt-version at least to 5.4.2.
You can also try to change your user agent (`Preferences -> Other -> User Agent Manager`).

Which distro are you using?

**Comment by mrjacque** [comment]
Am using OpenSUSE. YAST does not offer anything above QT version 4. Went on web trying to find out how to load later version without success. 
Also tried to change the user agent to others available on the select list and none of the optrions will allow me to go to my.yahoo.com. All take me to www.yahoo.com in an unrecognizable format.

**Comment by JHooverman** [comment]
Which openSuSE-version?

**Comment by mrjacque** [comment]
Using 13.1.
Loaded the latest QupZilla from your link but do not know what of the files I need from the repo for QT 5.4.

**Comment by JHooverman** [comment]
It seems, that 13.1 legacy repos do not support qupzilla-qt5. I found [this](repositories/home:/NickLion:/qt5/KDE_Qt5_openSUSE_13.1) unstable repo. Please install qupzilla-qt5 and zypper will resolve the dependencies.

**Comment by mrjacque** [comment]
Yast will not let me install qupzilla-qt5.

**Comment by JHooverman** [comment]
Which error message is displayed?

**Comment by mrjacque** [comment]
It says required dependencies are not available on the OpenSUSE http.

**Comment by JHooverman** [comment]
Did you add [this](http://download.opensuse.org/repositories/KDE:/Qt54/) repo to the software repositories?

**Comment by mrjacque** [comment]
as http://download.opensuse.org/repositories/KDE:/Qt54/openSUSE_13.1/ but says server not available. Where is qupzilla-qt5 located or what files do I need from this distro?

**Comment by JHooverman** [comment]
You will have to add two repos via Yast:

1. The one, that contains qupzilla-qt5
http://download.opensuse.org/repositories/home:/NickLion:/qt5/KDE_Qt5_openSUSE_13.1/

2. The one, that contains libqt5
http://download.opensuse.org/repositories/KDE:/Qt54/openSUSE_13.1/

Then install qupzilla-qt5 via Yast and all dependencies will be resolved.

**Comment by mrjacque** [comment]
I give up on Qupzilla in OpenSUSE. Tried loading those files repos. Qupzilla-qt5 says no response from servers. Thanks for your help but giving up on Qpzilla in Opensuse. Works fine in Ubuntu so will use there.
