### ISSUE TITLE
Localization issues:

### ISSUE THREAD

**Issue by smarquespt** [QupZilla/qupzilla#1776]
Strings not uploaded to transifex:

Spellcheck settings
Spellcheck (button in preferences)

In transifex but not loaded:

Preferences->Privacy->certificate manager->Settings tab

All certificates...

**Comment by nowrep** [comment]
So is the string on transifex or not?

I've added it only 2 days before 1.8.9 release, so it wasn't translated when releasing it.

**Comment by smarquespt** [comment]
>All certificates...

is on transifex, and it is translated in my language. But in 1.8.9 qupzilla shows english strings.

Other 2 aren't at transifex.

**Comment by nowrep** [comment]
Sorry, there was wrong URL for translations. It should be fixed in next Transifex sync.

I have also changed all translations to master branch (2.0).

**Comment by smarquespt** [comment]
@nowrep 

Hi David,

Transifex was updated but strings were not uploaded correctly. For my language (Portuguese), I still have 100% completed but I notice that commit added some strings.
