### ISSUE TITLE
Improve High DPI support

### ISSUE THREAD

**Issue by wujinghe** [QupZilla/qupzilla#1778]
The web page becomes very small in high resolution. What settings can be adjusted?
<img width="1278" alt="qupzilla_in_high_resolution" src="https://cloud.githubusercontent.com/assets/9344427/11292251/1c5c9680-8f86-11e5-9a8f-e09f206d51e3.png">

**TODO**:
Make sure to use high resolution pixmaps everywhere.

**Comment by cranes-bill** [comment]
<kbd>Ctrl</kbd>**+**<kbd>+</kbd> = ZOOM IN
<kbd>Ctrl</kbd>**+**<kbd>-</kbd> = ZOOM OUT
or <kbd>Ctrl</kbd>**+** **Mouse**/**TP Scroll** for the both above
<kbd>Ctrl</kbd>**+**<kbd>0</kbd> = RESET

@nowrep maybe will fix it in style sheet as **favicon** as well :stuck_out_tongue_winking_eye:

**Comment by wujinghe** [comment]
use the zoom in or out: (1) the user experience is not good; (2)some web pages will show incorrect.
I will try to use style sheet. And I do not know how effective.

**Comment by nowrep** [comment]
Some info for high dpi in KDE apps (apply also to Qt apps) http://blog.davidedmundson.co.uk/blog/kde_apps_high_dpi

Especially:
```
    Change the DPI under system settings -> font -> force font DPI to 192
    Set the environment variable QT_DEVICE_PIXEL_RATIO=2
```

**Comment by wujinghe** [comment]
Excellent, you are right.
Thanks a lot!

**Comment by nowrep** [comment]
I'll leave this issue here edited to "Improve high dpi"

**Comment by zhulik** [comment]
Another related issue: smooth scroll performance on hidpiscreen. I have laptop with 4k display, and fullscreen scroll in qupzilla isn't smooth. When qupzilla windowed on square of my screen i have really smooth scroll. Really smooth, macos-like scroll will be a killer feature!

Can you improve scroll performance? Some hacks like rendering in reduced resolution while scrolling or something like this.

**Comment by mathieujobin** [comment]
i don't know how related to HighDPI it is... but while CTRL+[-+] shortcuts works great...
using the wheel mouse is way too fast... its goes from way too small, to way too big.

my resolution is 2560x1440 on a 13", so I use zooming a lot, in kate, konsole, chrome, but in qupzilla its very annoying. I guess I will get used to the keyboard shortcuts in the mean time.
should I create a new issue for this? or ...?

**Comment by klundry** [comment]
Is there any update on this issue?  The high dpi scaling still is non functional.  I'm using Plasma 5.8.5 on arch and I can scale my whole desktop but qupzilla doesn't seem to scale at all.  All pages are tiny. I created the issue about the default zoom level not sticking, which is fixed in the next version, but that's just a work around for actually scaling with the rest of the desktop.

**Comment by nowrep** [comment]
Yes, HighDPI support is done - everything should work just fine (with Linux theme).

**Comment by klundry** [comment]
So I just add that as an environment variable?

**Comment by klundry** [comment]
Alright after some expirimentation the high dpi support is still not working correctly for me.  I'm on a 1920x1080 11.6" screen.  So my dpi is somewhere in the middle.  Doing nothing makes everything too small. using QT_SCALE_FACTOR=2 makes everything way too big and messes up my plasma menus and window decorations.

Setting "xrandr --dpi 120 makes everything look just right but doesn't scale qupzilla enough.

**Comment by nowrep** [comment]
So you want bigger fonts or proper scaling? Setting higher DPI will only result in bigger fonts.

You can use QT_SCALE_FACTOR with non-integer value too (eg. `1.5`), but it is not officially supported by Qt.

**Comment by klundry** [comment]
Yeah, I've tried using numbers between 1 and 2 and qupzilla looks like this when I do that.
![screenshot_20170120_132310](https://cloud.githubusercontent.com/assets/15848724/22179862/c7523c58-e024-11e6-958b-daba02164f5b.png)

**Comment by nowrep** [comment]
Ah right, you need QtWebEngine 5.8 for scaling to work. But even then, it doesn't work well with non-integer scaling (you will get pixelated web content).

**Comment by klundry** [comment]
So there is no way to get qupzilla to look right with my screen?  Either too small or crappy pixelation?

**Comment by nowrep** [comment]
Unfortunately yes, as long as QtWebEngine doesn't work with non-integer scaling.
