### ISSUE TITLE
User agent update

### ISSUE THREAD

**Issue by fabastrid** [QupZilla/qupzilla#1779]
Whatever agent I set, whatsapp.web and google drive sites ask me to update the browser. Any suggestion?

**Comment by nowrep** [comment]
Use custom user-agent.

**Comment by fabastrid** [comment]
This happens when I set the custom user-agent, with each of them.

**Comment by nowrep** [comment]
I mean, use "custom" custom user-agent - that is edit the one of offered (or use completely different).

eg. `Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0`

**Comment by JHooverman** [comment]
It will work with user agent string

`Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36`

**Comment by fabastrid** [comment]
Thank you. Now I can see the QR Code, but on the phone the message is that it's impossible to scan it. We're quite close...

**Comment by JHooverman** [comment]
Works for me on a Nexus 5, Android 6.0, Whatsapp 2.12.361

**Comment by fabastrid** [comment]
It doesn't for me, I'm so disappointed! (with whatsapp). Asus Zenfone 2, Android 5.0, Whatsapp 2.12.317 (that is last update for me). You have any idea? Oh, I forgot, I do love Qupzilla!

**Comment by JHooverman** [comment]
Google gives some hints, but unfortunately I have no clue.

[Hint 1](https://www.youtube.com/watch?v=QRXpNlEmqPM)
[Hint 2](http://www.whatsapp360.com/how-to-fix-whatsapp-web-qr-code-scanning-error/)
[Hint 3](http://android.stackexchange.com/questions/96546/why-i-cant-scan-the-whatsapp-qr)

**Comment by fabastrid** [comment]
Yes, I know all that, but on the same pc and OS (kutuntu 32bit) with FF it's immediate. I was thinking about something related to the string... But ok, for me, having gogle drive is good.
