### ISSUE TITLE
One-word queries in Address Bar do not search

### ISSUE THREAD

**Issue by toastercup** [QupZilla/qupzilla#1780]
When building from the `qt5.5` branch, typing a one-word query in the Address Bar does not trigger a search using the default search engine even if 'Search with Default Search Engine' is enabled in Tab Behaviour. Multi-word queries (with spaces delimiting words) work fine and will use the search engine.

**Comment by ke7ofi** [comment]
Is this related to #1746?

**Comment by nowrep** [comment]
This is now working fine.
