### ISSUE TITLE
Prevent HTML5 videos autoplay

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#1783]
I need alternative of **Click to Flash**, which prevent HTML5 videos autoplay.
I will appreciate any solution (workaround).

**Comment by JHooverman** [comment]
I did not try them, but maybe [here](https://greasyfork.org/en/scripts/search?q=html5) you will find a solution.

**Comment by cranes-bill** [comment]
I can adding different domains in the first script, so that's a good solution.
Thank you very much!

**Comment by JHooverman** [comment]
@nowrep: Do you think about implementing a configuration option or plugin for this purpose?

**Comment by ke7ofi** [comment]
It seems like it could be done as a JS script, though the same could be said of adblocking and click-to-Flash.
