### ISSUE TITLE
Little annoyances...

### ISSUE THREAD

**Issue by quphub** [QupZilla/qupzilla#1784]
QUPZILLA 1.8.9
WINDOWS XP2 PRO

1) Download Manager always says "REMAINING FEW SECONDS"

2) Tools>Preferences>Other>SpellCheck settings
Hidden window.

3) Can't open automatically Bookmark in new tab.

**Comment by JHooverman** [comment]
Regarding 1): Please see #1606
Regarding 2): Please see #1777

**Comment by quphub** [comment]
Thanks for the kind and speedy answer !

QupZilla smells as a great browser !   :)

**Comment by cranes-bill** [comment]
Regarding 3): There is no settings option to open bookmarks in new tab, so that's not a bug, but you can use middle click instead.

**Comment by quphub** [comment]
Thanks for your answer !
General behavior of middle click on my pc is 'close app'...
"Open history and bookmarks in new tab" in Preferences>Tabs could be useful.

**Comment by nowrep** [comment]
Then use Ctrl+Left Click

**Comment by quphub** [comment]
Bingo ! nowrep, that does the trck !
Thanks, bro.!

**Comment by JHooverman** [comment]
Closing this issue as solved (3) and as duplicate (1) + (2).
