### ISSUE TITLE
Links Stop Working in 1.8.9

### ISSUE THREAD

**Issue by Geyup** [QupZilla/qupzilla#1788]
These are my specs;

Slackware 14.1 x86_64
QT5 5.5.0
QupZIlla 1.8.9 (WebKit version 538.1)

When I surf a site, many times after clicking some links, later when I try to click links again, QupZilla does nothing, clicking on links has no effect.

**Comment by JHooverman** [comment]
Could please provide a reproducible test procedure? I have tried it various times on different web-sites, but this issue did not occur.

**Comment by Geyup** [comment]
It happens on any site I visit, not just some sites in particular...

**Comment by Vistaus** [comment]
Doesn't seem to be a problem here on Antergos with Qt 5.5, but it wasn't a problem either a few days ago on Mint 17.3 with Qt 5.2.1 and also not with Qt 5.2.1 on Linux Deepin 2014.

**Comment by nowrep** [comment]
Same as the other issue, please try with QtTestBrowser.

**Comment by Geyup** [comment]
@nowrep 

Browser segfaults, see https://github.com/QupZilla/qupzilla/issues/1787
