### ISSUE TITLE
QupZilla hangs on converting translations during building

### ISSUE THREAD

**Issue by Vistaus** [QupZilla/qupzilla#1794]
I've never ever had this before in the few years that I've been using QupZilla now, so I don't know what exactly causes it. I clean installed Antergos yesterday (over Mint 17.3) and have every build requirement installed. But for some reason, make hangs on converting the translations.

vistaus@vistaus-lemur:~/Downloads/qupzilla$ make -j3
/usr/lib/qt/bin/qmake -o Makefile QupZilla.pro
cd src/lib/ && ( test -e Makefile || /usr/lib/qt/bin/qmake /home/vistaus/Downloads/qupzilla/src/lib/lib.pro -o Makefile ) && make -f Makefile 
make[1]: Map '/home/vistaus/Downloads/qupzilla/src/lib' wordt binnengegaan
/usr/lib/qt/bin/lrelease -silent ../../translations/ar_SA.ts -qm /home/vistaus/Downloads/qupzilla/translations/../bin/locale/ar_SA.qm
/usr/lib/qt/bin/lrelease -silent ../../translations/bg_BG.ts -qm /home/vistaus/Downloads/qupzilla/translations/../bin/locale/bg_BG.qm
/usr/lib/qt/bin/lrelease -silent ../../translations/ca_ES.ts -qm /home/vistaus/Downloads/qupzilla/translations/../bin/locale/ca_ES.qm

It doesn't get past that point. What is wrong and how can I solve it? Using Antergos (clean install) with Qt 5.5

**Comment by nowrep** [comment]
You can try remove the `-silent` flag in `translations/translations.pri:46` and see what is going on (if it really hangs in lrelease)

**Comment by Vistaus** [comment]
Thanks! I will try that again if the error pops up again, but it seems to be gone for now :)
