### ISSUE TITLE
Qupzilla 1.8.9 cannot be opened because of a problem on Mac OS X

### ISSUE THREAD

**Issue by hexalys** [QupZilla/qupzilla#1795]
This is on Mac OS X 10.6.8. with Qupzilla 1.8.9 (Qupzilla 1.8.2 was working)

The relevant log I get is: 

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /Applications/Browsers|WebClients/QupZilla.app/Contents/MacOS/../Frameworks/QtWebKitWidgets.framework/Versions/5/QtWebKitWidgets
  Reason: image not found

Binary Images:
    0x7fff5fc00000 -     0x7fff5fc3be0f  dyld 132.1 (???) <29DECB19-0193-2575-D838-CF743F0400B2> /usr/lib/dyld

**Comment by nowrep** [comment]
So you don't have `/usr/lib/libc++.1.dylib` on your system?

**Comment by hexalys** [comment]
Correct. I have used the Download version.

**Comment by nowrep** [comment]
Then you should install the library (if at all possible) or I guess you have too old system.

**Comment by nowrep** [comment]
Or you will need to build it yourself (which is quite easy actually).

**Comment by hexalys** [comment]
Ok. I'll have to do that. Thanks

**Comment by hexalys** [comment]
I wish i could. But I can't understand the deploy command and why it fails. I am trying to build 1.8.6 based on the source (which should work with my system).

When I use:
./mac/macdeploy.sh

I get:
cp: directory QupZilla.app/Contents/MacOS does not exist
mkdir: QupZilla.app/Contents/Resources: No such file or directory
cp: directory QupZilla.app/Contents/Resources/plugins does not exist
install_name_tool: can't open file: QupZilla.app/Contents/MacOS/QupZilla (No such file or directory)
install_name_tool: can't open file: QupZilla.app/Contents/Resources/plugins/*.dylib (No such file or directory)

Could you clarify why it can't find this file? And where it should be?

**Comment by nowrep** [comment]
Use current code from `v1.8` branch and it should work just fine.

**Comment by hexalys** [comment]
Well that's what I am doing. But there are no `QupZilla.app/Contents/MacOS` in that directory that I can see. Is that supposed to be the one in the DMG template?
If not where is that `QupZilla.app/Contents/MacOS` supposed to be located at?

**Comment by nowrep** [comment]
You must first build it with `qmake && make`

**Comment by hexalys** [comment]
Ok my bad. The README somewhat reads as if this part fell under Windows only and Not MacOS X. Got that part wrong. Thanks
