### ISSUE TITLE
Add option to force popup windows to be opened in tabs

### ISSUE THREAD

**Issue by digi-owl** [QupZilla/qupzilla#1796]
Various sites open new windows for some reason or other.

Was wondering if it was possible add a option that would send these windows to tabs in the main window instead.

**Comment by nowrep** [comment]
Do you mean popup windows? Because everything (except javascript popup windows) is being opened in new tab. You should not see a full browser window opened from the webpage (only you as user can do it with `Open in new window` actions).

**Comment by digi-owl** [comment]
yep, popup windows. The term slipped my mind for some reason.

Various pages have some content rich popup windows, and thus it would be nice if they could be handled as tabs rather than windows.

**Comment by GreenLunar** [comment]
I propose such tabs to be opened in background, and not force focus on such tabs.
