### ISSUE TITLE
[master] Missing header

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#1798]
Finally i built and installed Qt 5.6, but have the following error now:
```
In file included from ../../../src/lib/app/mainapplication.cpp:49:0:
../../../src/lib/network/schemehandlers/qupzillaschemehandler.h:21:69: erreur fatale: QtWebEngineWidgets/private/qwebengineurlschemehandler_p.h : Aucun fichier ou dossier de ce type
 #include <QtWebEngineWidgets/private/qwebengineurlschemehandler_p.h>
                                                                     ^

```
Even i can't find this file in the all of git cloned Qt source.

**Comment by nowrep** [comment]
This is not master: https://github.com/QupZilla/qupzilla/blob/master/src/lib/network/schemehandlers/qupzillaschemehandler.h#L23

**Comment by cranes-bill** [comment]
OK, sorry!
I thought it clones `master` by default, so i cloned it without specifying a branch.

**Comment by nowrep** [comment]
It should, `master` is default branch.

**Comment by cranes-bill** [comment]
Perhaps different commit!?
That's not a first time when my git clones a older branch then current.
What might be the reason....!? 0:
