### ISSUE TITLE
Rendering and scroll issue on twitter timeline, Linux

### ISSUE THREAD

**Issue by zhulik** [QupZilla/qupzilla#1799]
Please, try to read twitter on linux with qupzilla, top panel shakes while scrolling

**Comment by JHooverman** [comment]
This issue is maybe similar to [this](https://github.com/QupZilla/qupzilla/issues/1506) one. Which Qt-version are you using?

**Comment by zhulik** [comment]
@JHooverman 
qt5-webkit 5.5.1-5 
qupzilla 1.8.9-2
ArchLinux

**Comment by innermous** [comment]
I got that aswell under archlinux plus pixelated fonts on some websites. No troubles at qt5.5 branch.
I guess, that's just webkit trouble.
