### ISSUE TITLE
Question: Backing Up Bookmarks?

### ISSUE THREAD

**Issue by Geyup** [QupZilla/qupzilla#1800]
To backup and replace bookmarks, all we need to do is just copy and replace the bookmarks.json?

thanks

**Comment by cranes-bill** [comment]
Yes, that works, but you also can use **Bookmarks Manager**:
_**MENU**: **Bookmarks** -> **Organize Bookmarks (** <kbd>Ctrl</kbd>**+**<kbd>Shift</kbd>**+**<kbd>O</kbd> **)**-> **Import and Export**_

**Comment by Geyup** [comment]
thanks
