### ISSUE TITLE
Can't add Adblock list

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#1801]
My guess that is because of the **apostrophe** in the file name.
Steps to reproduce:
Go to [this](http://www.kiboke-studio.hr/i-dont-care-about-cookies/) page
Click on **Add to Adblock Plus** link
Click :ok: on confirmation dialogue
The result is the following:
![capture du 2015-12-10 21 20 30](https://cloud.githubusercontent.com/assets/5161278/11726315/b6bcd04a-9f86-11e5-80e8-232ccd87a708.png)

No problem with this with _V1.8 Qt4_

**Comment by nowrep** [comment]
And I don't care about the apostroph :D Does it work if you use different subscription title?

**Comment by cranes-bill** [comment]
:laughing:
Yes, it works.

**Comment by cranes-bill** [comment]
This is a Qt5 bug, because it's the same with V1.8 - Qt 5.5, but has no problem with V1.8 - Qt 4.8, so i also don't care. :smile:

**Comment by nowrep** [comment]
No it's not.

**Comment by innermous** [comment]
The problem is just displaying %27t instead apostrophe? I don't get it.
