### ISSUE TITLE
No way to create new (sub)directory in Bookmarks?

### ISSUE THREAD

**Issue by jamesqf** [QupZilla/qupzilla#1805]
I imported existing bookmarks from Opera (after some problems).  The imported bookmarks also have a number of QupZilla links, which I'd like to move into their own "QupZilla" directory.  However, I can find no way to add a new directory (other than editing the bookmarks.json file, which is kind of a pain).  Am I just missing something obvious, or is this something that needs to be added?

I'm using version 1.8.9 on OpenSuSE.

**Comment by cranes-bill** [comment]
What about right click in **Bookmarks Manager** !!??

![capture du 2015-12-12 10 14 14](https://cloud.githubusercontent.com/assets/5161278/11761053/a14005ee-a0bb-11e5-9471-22103796c107.png)

**Comment by JHooverman** [comment]
In addition to @cranes-bill comment: The Bookmarks Manager can be accessed via `Bookmarks -> Organize Bookmarks`

**Comment by jamesqf** [comment]
Thanks, the right click works.  I have to say that it's really not obvious, though.  I would never have found it on my own.
