### ISSUE TITLE
Back Button No Color, Not Sure If Can Go Back...

### ISSUE THREAD

**Issue by Geyup** [QupZilla/qupzilla#1808]
In QupZilla 1.8.9 compiled against QT5 5.5.1 in Linux, I noticed with certain grey colored iconsets, ```NouveGnomeGray``` & ```AwOken```

http://www.deviantart.com/art/nouveGnomeGray-300365158

http://www.deviantart.com/browse/all/?section=&global=1&q=awOken

There is no changing of the backbutton to a greyed out look, or dark enough to tell you can't go back.

What I noticed with an iconset that has color, the back button appears grey when it doesn't work to go back, so for iconsets that are grey in color by design this doesn't help.

**Comment by cranes-bill** [comment]
There is a thousands different icon sets for Linux.
Please tell me - do you really expects that the developers should adjusts their software to any one theme!?

**Comment by Geyup** [comment]
@cranes-bill of course not, so let's not sound ridiculous about such a notion.

But what is resaonable to expect is that no matter what iconset/color you have the buttons are faded, or changed in some manner to be able to see.

**Comment by cranes-bill** [comment]
Active:
![capture du 2015-12-14 00 50 49](https://cloud.githubusercontent.com/assets/5161278/11770026/38f3cd52-a1fd-11e5-8433-c33cdfb2a9f4.png)
Inactive:
![capture du 2015-12-14 00 49 43](https://cloud.githubusercontent.com/assets/5161278/11770029/4fc46faa-a1fd-11e5-8a20-32f88cd2a023.png)

**Comment by Geyup** [comment]
I know how it looks, but I said, ```no matter what iconset/color you have```

**Comment by Geyup** [comment]
Basically we could flip the conversation around to say, everything works as long as you don't use something grey. Which means it's excluding, and it shouldn't matter what color you have...

**Comment by Geyup** [comment]
Ok I just went back and looked at Firefox and realized it uses it's own iconset, but it's more greyed out.

I think the solution to make this easy for the developers is to have the icons really whited out, more faded and faint looking to stand out better.

**Comment by nowrep** [comment]
Not a bug in QupZilla. The button is correctly set as disabled, it depends on your Qt style what to do with it (grey out the icon, ...).

**Comment by Geyup** [comment]
Oh sorry, didn't realize the theme handles this, hmm...
