### ISSUE TITLE
Url string 20% ist not decoded 

### ISSUE THREAD

**Issue by JHooverman** [QupZilla/qupzilla#1810]
Please try the following:

(1) Go to http://data.madisoncity.k12.al.us/Documents/Employment/
(2) Do a right-click on the file `403(b) Plan Eligibility Notice.pdf`
(3) Select `Save link as ...`

The dialog will offer to save the file `403(b)%20Plan%20Eligibility%20Notice(1).pdf`

It seems, that the url strings  `20%` are not decoded into a `space`.

Tested with:
Application version: 1.9.99 (65362d6eeb)
QtWebEngine version: 5.6.0

**Comment by innermous** [comment]
Gonna fix that in the morning.

**Comment by innermous** [comment]
It's just Qt 5.6.0 trouble. QupZilla code has nothing to do with that triggerPageAction call.

**Comment by nowrep** [comment]
It is probably bug in QtWebEngine downloading, but we still may try to decode it from percent encoding.

**Comment by innermous** [comment]
Yep, if we just implement it avoiding QtWebEngine brand new downloading.

**Comment by nowrep** [comment]
No, that's not a solution. We can't use QNetworkReply for downloads, because it won't share the session data with QtWebEngine pages.

Solution is to rename (percent decode) the suggested file name when starting downloads.

**Comment by innermous** [comment]
More than that, I can't change name of file in Save file menu. It just forces downloading it with pre-defined name.
