### ISSUE TITLE
Some icons not use system style

### ISSUE THREAD

**Issue by varlesh** [QupZilla/qupzilla#1811]
Icons hardcoded, it's spoils style
![2015-12-15 17 14 50](https://cloud.githubusercontent.com/assets/8083855/11812919/bc329448-a34f-11e5-9323-54473ab81a28.png)
For example use other (based on Oxygen icon theme):
rss - application-rss+xml
![application-rss xml](https://cloud.githubusercontent.com/assets/8083855/11813266/82cef1cc-a351-11e5-9220-1068e0c6f9d0.png)
star - bookmarks 
![bookmarks](https://cloud.githubusercontent.com/assets/8083855/11813283/99fac970-a351-11e5-9bb7-9ccc6b945df8.png)
tab-close - tab-close (why not use system icons?). dialog-close better variant
![tab-close](https://cloud.githubusercontent.com/assets/8083855/11813293/a7972b8c-a351-11e5-9e1a-538fb014e174.png)
menu - format-justify-fill
![format-justify-fill](https://cloud.githubusercontent.com/assets/8083855/11813298/b1e4a420-a351-11e5-942a-ffa1dccd0064.png)

**Comment by nowrep** [comment]
Tab close button is using icon from style (`QStyle::PE_IndicatorTabClose`).
The other ones you listed are not good candidates:

application-rss+xml is for file type, not for general rss icon
bookmarks is for bookmarks, not for general star icon (it may be a book, which won't look good)
format-justify-fill is absolutely different thing

**Comment by nowrep** [comment]
Actually, both application-rss+xml and bookmarks may not actually be too bad choices (it will look different, maybe worse .. but using the icon theme is indeed better).

**Comment by varlesh** [comment]
But icons hardcoded, i create rss, star and etc icons but they not used :(
See, it's fine (create on Gimp)
![2015-12-15 17 34 43](https://cloud.githubusercontent.com/assets/8083855/11813625/8c6b6132-a353-11e5-8604-8b3f05f461ed.png)

**Comment by nowrep** [comment]
Yes, those are hardcoded. You can change it in theme though.

**Comment by varlesh** [comment]
It's spoils style :(

**Comment by varlesh** [comment]
But other icons used system style. Why this 4 icons can not use system style? Ok, rss and bookmarks not available, but they hardcoded.

**Comment by varlesh** [comment]
You can add option on Linux/main.css use system icons for rss, star, tab-close and menu?

**Comment by varlesh** [comment]
For example:
If icon not available - use skin icon
icon available - use system icon

**Comment by nowrep** [comment]
It's done already like that, for the rest of the icons.

**Comment by varlesh** [comment]
You mean https://github.com/QupZilla/qupzilla/blob/master/bin/themes/linux/rtl.css ?
But why you can not add rss, star and menu?
```
#locationbar-bookmarkicon
{
    qproperty-themeIcon: "star";
    qproperty-fallbackIcon: url(images/star.png);
}
```

**Comment by cranes-bill** [comment]
Such a big problem........
But why you can not _**symlinks**_ the icons which you want!?

**Comment by varlesh** [comment]
If you change  icon theme - you must change again symlinks. It's not solution and uncomfortably

**Comment by ke7ofi** [comment]
I'm going to vote for out-of-box DE integration here. There's no good reason to force users to do it themselves; consistency should be a goal so long as it's not going to eat everyone's time to make it work.

**Comment by nowrep** [comment]
So bookmarks is the only left. But the problem is that we need 2 icons - one that will indicate the site *is not* bookmarked (empty star) and one that site *is* bookmarked (yellow star), which is not available in icon themes.

**Comment by nowrep** [comment]
Used icons
menu: `application-menu`
rss: `feed-subscribe`

**Comment by varlesh** [comment]
For bookmarks can use (Oxygen):
draw-star
![draw-star](https://cloud.githubusercontent.com/assets/8083855/12536783/bab645c0-c2c0-11e5-966e-b5645a8e09c8.png)

bookmarks
![bookmarks](https://cloud.githubusercontent.com/assets/8083855/12536784/c040cd58-c2c0-11e5-8dde-cdc8c096f806.png)

**Comment by nowrep** [comment]
Those are two different stars, and also completely different icon names. Not to mention that some icon themes (eg. breeze) may not use star for bookmarks icon at all.

**Comment by varlesh** [comment]
For breeze best use 
rating-unrated 
![rating-unrated](https://cloud.githubusercontent.com/assets/8083855/12536842/fad68f24-c2c1-11e5-994f-bac4f583e3c8.png)
rating
![rating](https://cloud.githubusercontent.com/assets/8083855/12536844/051aeb42-c2c2-11e5-9175-2f23941100c7.png)
It's realy better that hardcoded icons
For oxygen (default) and other theme use fallback icons:
```
#locationbar-bookmarkicon[bookmarked="true"]
{
    qproperty-themeIcon: "rating";
    qproperty-fallbackIcon: url(images/star-a.png);
}
```

**Comment by cranes-bill** [comment]
The following should works:
``` css
#locationbar-bookmarkicon
{

    qproperty-themeIcon: bookmark-new; /* << Here you can use „unstared“ as well.*/
}

#locationbar-bookmarkicon[bookmarked="true"]
{
    qproperty-themeIcon: starred;
}
```

**Comment by varlesh** [comment]
@nowrep Yo say:
"Those are two different stars, and also completely different icon names. Not to mention that some icon themes (eg. breeze) may not use star for bookmarks icon at all."
But Qupzilla use hardcoded STAR icon! And rating and rating-unrated better variant for bookmarks, i think

**Comment by nowrep** [comment]
Yes, those are hardcoded. But that also means that it will always look like that - and that's okay.

But some styles may have `rating` icon that looks nothing like a star. And if it does, it will be displayed in QupZilla which will only confuse the user.

**Comment by varlesh** [comment]
Oxygen icons "rating" -  use star
Breeze icons "rating" -  use star
Numix  icons "rating" -  use star
etc...
Hardcoded icons spoil style

**Comment by nowrep** [comment]
Alright, what about gnome (adwaita)?

**Comment by varlesh** [comment]
Qupzilla Qt-app and use Breeze and Oxygen theme as standard.
Other icon themes use  fallback icons - "star" and "star-a"

**Comment by nowrep** [comment]
No, those icons will be used either with all icon themes or not at all.

**Comment by varlesh** [comment]
Adwaita have only symbolic icons:
non-starred-symbolic
starred-symbolic
But on Breeze and Oxygen this icons not available :(

**Comment by nowrep** [comment]
Ok, I'm probably going to use the `rating/rating-unrated` icons. But I'll think about it some more first.

**Comment by cranes-bill** [comment]
My suggestion is according to Gnome icon theme, which is used as fallback icon theme in Gtk

**Comment by cranes-bill** [comment]
@varlesh : Adwaita have only symbolic icons...
You are a quite wrong here!

**Comment by ke7ofi** [comment]
`rating`-type is the way to go in my opinion.
