### ISSUE TITLE
Option to stretch tabs

### ISSUE THREAD

**Issue by jurf** [QupZilla/qupzilla#1819]
Hey, it would be cool to have tabs stretchable (to use the full width of the window) like in GNOME Web:

![snimka obrazovky z 2015-12-19 16-34-29](https://cloud.githubusercontent.com/assets/7472425/11913730/9447f9d8-a66e-11e5-9852-86042db9ee19.png)

Thanks.

**Comment by ke7ofi** [comment]
If so, definitely make it optional.

**Comment by DoctorJellyface** [comment]
Of course, that goes without question.

**Comment by nowrep** [comment]
Hmm, that really sux :D But here is the patch:

```diff
diff --git a/src/lib/tabwidget/tabbar.cpp b/src/lib/tabwidget/tabbar.cpp
index 6c88f3c..4c3c644 100644
--- a/src/lib/tabwidget/tabbar.cpp
+++ b/src/lib/tabwidget/tabbar.cpp
@@ -266,7 +266,7 @@ int TabBar::comboTabBarPixelMetric(ComboTabBar::SizeType sizeType) const
         return 100;
 
     case ComboTabBar::NormalTabMaximumWidth:
-        return 250;
+        return 999999;
 
     case ComboTabBar::ExtraReservedWidth:
         return m_tabWidget->extraReservedWidth();
```

**Comment by GreenLunar** [comment]
I guess this would be useful to what is known as "touch screen".

**Comment by nowrep** [comment]
It's now configurable 678b513820f57fbfc75fcb6facf34020f6e70733
