### ISSUE TITLE
Cross-domain requests are not supported by the "Userscripts for QupZilla" extension.

### ISSUE THREAD

**Issue by sebma** [QupZilla/qupzilla#1821]
Hi,

If I add the Viewtube script to the "Userscripts for QupZilla" extension, this video does not load:

https://www.youtube.com/watch?v=5OGreASOd4c because it's encrypte.

However this one does because it's not encrypted: https://www.youtube.com/watch?v=ctq2w5qGKfE

FYI : Both videos load correctly in Firefox using the "real" Greasemonkey extension.

Can you fix this ?

**Comment by nowrep** [comment]
No, QtWebKit doesn't support privileged JavaScript execution.
