### ISSUE TITLE
Chinese font have problem

### ISSUE THREAD

**Issue by jtliaw** [QupZilla/qupzilla#1822]
Chinese font overlap

![2015-12-24-133418_1366x768_scrot](https://cloud.githubusercontent.com/assets/4332185/11990131/fd423a9c-aa43-11e5-9659-15e28ce10983.png)
How can i fix it?

**Comment by JHooverman** [comment]
Please let us know about your configuration (`Menu -> Configuration information`) as shown in the following example:

Application version: 1.9.0 (ee80b04a11)
Qt version: 5.4.2
WebKit version: 538.1
Build time: Jan 25 2015 16:47:02
Platform: openSUSE Tumbleweed (Linux)

In addition, please provide a link for testing.

**Comment by jtliaw** [comment]
Information about version
Application version
1.8.9
Qt version
5.2.1
WebKit version
537.21
Platform
Linux
Browser Identification
Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.21 (KHTML, like Gecko) QupZilla/1.8.9 Safari/537.21

**Comment by JHooverman** [comment]
Would you please provide a link to a web-page, which gives reproducible results of your issue? Please keep in mind, that we will not be able to decide, what is meant by Chinese font overlap - we are not familiar with the letters of your language.

**Comment by jtliaw** [comment]
http://www.google.com/search?client=qupzilla&q=qupzilla%20%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93%E9%87%8D%E5%8F%A0
![_001](https://cloud.githubusercontent.com/assets/4332185/12013559/058f399e-ad54-11e5-89bc-21f0cd7c6f00.jpg)

**Comment by jtliaw** [comment]
https://linux.cn/

**Comment by jtliaw** [comment]
https://github.com/LiuLang/bcloud

![_004](https://cloud.githubusercontent.com/assets/4332185/12013617/d64202d2-ad55-11e5-9f24-a67aaf01be1e.jpg)

**Comment by jtliaw** [comment]
https://linuxtoy.org/

**Comment by cranes-bill** [comment]
I think that's a system settings (or fonts) issue, but not of QupZilla.

**Comment by jtliaw** [comment]
I have install qupzilla on 3 lubuntu system all have this same problem. firefox, google chrome, slimjet no this problem!

**Comment by JHooverman** [comment]
@jtliaw: None of the browsers you have mentioned are QtWebkit based. So, the result of their rendering capabilities is not comparable.

@cranes-bill: Are you using QupZilla compiled against qt-5.5 & QtWebkit (branch 1.8)? If so, you could test the example links and post and compare the result here.

**Comment by cranes-bill** [comment]
@JHooverman, sorry! I upgraded my system, so this configuration is no more available on it. But i tested on my oldest system with **QupZilla v1.8 Qt 5.4** and the problem doesn't exists there.

@jtliaw, i'm just supporting JHooverman's answer. Perhaps that's a general Qt 5.5 and above issue. In my case, Qt 5.6 applies the GTK theme, but does not respect the menu and fonts settings. As you can see on the screen-shot, the font looks a bit ugly. I don't have problem with **QupZilla v1,8 Qt4**. The font also looks well (i think) with **QupZilla v1.8 Qt 5.4**.

#### QupZilla master Qt 5.6
![screenshot from 2015-12-28 12-35-39](https://cloud.githubusercontent.com/assets/5161278/12018972/fb4d9b5a-ad72-11e5-90ec-dfd8ee00fb07.png)
#### QupZilla v1.8 Qt 5.4
![qupzilla_1 8 qt 5 4 0](https://cloud.githubusercontent.com/assets/5161278/12018990/4428d9d4-ad73-11e5-9675-a6169894ebc6.png)
#### QupZilla v1.8 Qt4
![qupzilla_1 8 qt4](https://cloud.githubusercontent.com/assets/5161278/12019005/6eb8faa8-ad73-11e5-8718-8a3817e6e68d.png)

**Comment by jtliaw** [comment]
Ok! Thank!

**Comment by JHooverman** [comment]
@jtliaw: Your issue cannot be reproduced with qt-5.5.1 & qtwebkit 538.1, see the following screenshot:

![img1](http://i.imgur.com/ypoNCym.png)

So, this is obviously an qtwebkit issue, related to your system installation. I recommend, that you upgrade at least to qt-5.4. I am closing this issue as resolved upstream.
