### ISSUE TITLE
Back & Forward Buttons Are Reversed...

### ISSUE THREAD

**Issue by Geyup** [QupZilla/qupzilla#1823]
Specs;

Slackware 14.1 86_64
QT5 5.5.1
QupZilla 1.8.9 - WebKit version 538.1

I noticed that the ```Back``` & ```Forward``` buttons are working in reverse...

An arrow pointing to the left in a browser is the ```Back``` button, and arrow pointing to the right is the ```Forward``` button, but QupZilla's buttons for me are reversed... 

Pointing to the right is going back and pointing to the left is going forward.

Have a look at the screen shot, the blue arrow is the back button...

![qup_buttons](https://cloud.githubusercontent.com/assets/13072581/12008884/aa4b6792-ac54-11e5-9a75-9db09c86b731.jpg)

**Comment by JHooverman** [comment]
Which theme are you using?

**Comment by cranes-bill** [comment]
:santa::bell::christmas_tree:   _Merry Christmas of all!_  :christmas_tree:  :bell::santa:

@Geyup, you are awesome! I'm nominating you for **Most invalid issues reporter** here.
Congratulations! :grinning:

**Comment by nowrep** [comment]
That's weird, icons are reversed only if you use RTL layout (which you don't seem to, from the screenshot). Maybe is your icon theme wrong?

**Comment by cranes-bill** [comment]
@nowrep, it sounds unbelievable @Geyup to has an icons problem. Most likely QupZilla source is completely confused.  :stuck_out_tongue_winking_eye:

**Comment by Geyup** [comment]
Enough of the spamming Cranes!

Alriight so I didn't check the themeset shoot me LOL...

Vibrancy Colors is a recent iconset so I didn't consider it;

http://www.ravefinity.com/p/vibrancy-colors-gtk-icon-theme.html

**Comment by nowrep** [comment]
Can you test with different icon theme?

**Comment by cranes-bill** [comment]
![capture du 2016-01-02 21-23-59](https://cloud.githubusercontent.com/assets/5161278/12075866/17d59862-b198-11e5-8df7-865e6bfa0890.png)

**Comment by nowrep** [comment]
Ok, we found the issue :D thanks @cranes-bill
