### ISSUE TITLE
Turn off popup when hovering over some links?

### ISSUE THREAD

**Issue by jamesqf** [QupZilla/qupzilla#1824]
QupZillia has an annoying behavior in some forums &c (though not all, and oddly enough, not here).  If I hover the mouse pointer over a thread for a couple of seconds, a popup will appear with some info.  On some forums, it's the first line or two of a thread; on Stackexchange (here, for instance: http://stackexchange.com/ ) it's the thread's number of "hotness points".  This is a really annoying visual distraction: how can I stop it from happening?

QupZilla 1.8.9 on OpenSuSE 13.1.

**Comment by JHooverman** [comment]
This popup is caused by this title element of the page source code (example):

![img1](http://i.imgur.com/kP0yJoo.png)

I am not sure, if this popup might be avoided by a suitable adblock [filter](https://adblockplus.org/filter-cheatsheet), but you might give it a try.
Does anybody else have a suggestion for solving this?

**Comment by jamesqf** [comment]
From what I've read since posting the question, I now think it (or at least some of it) might be due to the use of the CSS :hover attribute.  (Or perhaps an equivalent in Javascript.)  But that makes me wonder why the popups don't happen in the other browsers I use (Opera and Firefox)?  I've tried to decipher some of the web page code in order to pin it down, but no luck so far.

Maybe it would be possible to use a user style to turn off the hover entirely, but I haven't figured out how to do it yet.

**Comment by nowrep** [comment]
You'll need userscript that removes all `title` arguments from page.
