### ISSUE TITLE
Clarify tab preferences?

### ISSUE THREAD

**Issue by jamesqf** [QupZilla/qupzilla#1825]
In Preferences->Tabs, one item is "Activate last tab when closing last tab".  I'm not quite sure what is meant by "last" here: is it the last (that is, rightmost) tab in the list, or the most recently active tab?  

The latter is what I'd like to happen: if I have several tabs open, one of which is for instance Google News, and I click on an article (opening a new tab with the article contents), when I close that tab I'd like to be returned to the Google News tab.  Instead, I usually seem to go either to the rightmost tab, or to the tab to the right of the closed tab.  Do I just not understand the wording correctly?

**Comment by ke7ofi** [comment]
:+1:

**Comment by cranes-bill** [comment]
... _when I close that tab I'd like to be returned to the_ ...
:+1:

**Comment by JHooverman** [comment]
Closing this issue as solved. Please re-open, if you have additional questions or remarks.
