### ISSUE TITLE
https://app.tutanota.de/#notSupported

### ISSUE THREAD

**Issue by Geyup** [QupZilla/qupzilla#1826]
SIte not supported...

Linux
QupZilla 1.8.9
WebKit version 538.1
QT 5.5.1

![site](https://cloud.githubusercontent.com/assets/13072581/12103619/ace46af6-b33b-11e5-9819-05c91754a597.jpg)

**Comment by cranes-bill** [comment]
Change the **User Agent** !

**Comment by jamesqf** [comment]
Err... To what?  There is a "User Agent Manager" under Preferences, but it's just blank, and there's no clue (that I can find) as to what would be appropriate values.

**Comment by cranes-bill** [comment]
@jamesqf, what about to select from drop-down list or just to type manually!?
In @Geyup's  case, it can be done as on the picture below for example:
![capture du 2016-01-05 22-11-25](https://cloud.githubusercontent.com/assets/5161278/12126528/62e05338-b3fa-11e5-8b3b-fe225a1f0168.png)

**Comment by jamesqf** [comment]
But there's nothing in the drop-down list, at least on mine.
![qz](https://cloud.githubusercontent.com/assets/14325193/12127011/9541ccb8-b3a9-11e5-9597-203bbe6aba8d.jpg)

**Comment by cranes-bill** [comment]
You must check the checkbox :white_medium_square: !

**Comment by jamesqf** [comment]
Oh?  It would be nice if there was something, somewhere, to tell you this :-)

Come to that, it would be nice if there was an actual manual or something.  I like QupZilla (it's become my browser of choice for a lot of things), but I do get tired of having to figure things out by trial & error.

**Comment by JHooverman** [comment]
@Geyup: Does the solution provided by @cranes-bill solve your issue? Thank you for reporting back.

**Comment by Geyup** [comment]
SORRY guys, I forgot about this with QupZilla... :(

Yeah all good now!

THANKS
