### ISSUE TITLE
Installing Applications //ru.savefrom.net/

### ISSUE THREAD

**Issue by Kpvt** [QupZilla/qupzilla#1828]
How to install a popular application?
This download videos and music.  http://ru.savefrom.net/

**Comment by innermous** [comment]
I bet they just don't support QupZilla yet.

**Comment by JHooverman** [comment]
@Kpvt: When I hit the big download button I am landing on this page:

![img1](http://i.imgur.com/QQk1Hx2.png)

Here I am asked to create an account, probably for playing some multimedia content. Which application exactly would you like to install?

**Comment by cranes-bill** [comment]
Activate **Crease Monkey** plugin first, then go to the bottom of [page](http://ru.savefrom.net/user.php) and click over [установить скрипт](https://download.sf-helper.com/chrome/helper.user.js?ts=1452098941776)!
Voilà.

**Comment by JHooverman** [comment]
@cranes-bill: Thank you for working this out!
@Kpvt: Please check, if this works for you and report back.

**Comment by JHooverman** [comment]
Closing this issue due to lack of response. Please feel free to re-open, if you have new information.
