### ISSUE TITLE
Fail to load 

### ISSUE THREAD

**Issue by bounceQSF** [QupZilla/qupzilla#1829]
Win7
QupZilla 1.8.9_portable
Fail to load https://www.blend4web.com/apps/webplayer/webplayer.html?load=../../assets/capri/vehicles/mi_34s1/mi_34s1_demo_scene.json&autorotate&compressed_textures&v=20151223130029
QupZilla crashed halfway while loading this site. I also tried a simple demo with qtwebengine and so did it. I assume that the chromium kernel does not fully support WebGL.

**Comment by cranes-bill** [comment]
About the WebGL, perhaps you might find an answer [here](http://doesmybrowsersupportwebgl.com/), but if not support, you should see a massage on the screen, but not a crash.

**Comment by z19940413** [comment]
Well, I can hardly distinguish whether if failed to load WebGL, but it seems it crashed while loading and unfortunately I dont know how to deal with it.

**Comment by JHooverman** [comment]
This issue does not occur on my linux system:

![img1](http://i.imgur.com/d4mnzGf.png)

So, maybe this is windows specific.

My system:
Application version: 1.8.9
Qt version: 5.5.1
WebKit version: 538.1
Platform: openSuSE Tumbleweed (Linux)

**Comment by srazi** [comment]
I will close this as it works on Windows 10 and version 2.1.99 26540819127a0faecf3f9a2cd76aed4e1493ef19. Maybe it is a webkit related bug.

![capture](https://cloud.githubusercontent.com/assets/1328454/24709105/1b7ca0dc-1a2e-11e7-85c8-eab4e78cf6de.PNG)
