### ISSUE TITLE
Add "print" function to right click menu

### ISSUE THREAD

**Issue by sydneyjd** [QupZilla/qupzilla#1837]
Hello all,
This is mainly a feature request, but it is something i can do in quite a few browsers which i find handy.
Im wondering if you can make it so we(any user) can right click on a page and select "print" to allow us to print the whole page, or to select some text, then right click on that text allowing us to print only the selected text, etc.
Its helpfull for printing text only from websites if you don't want all the images. 
Just thought i would throw the idea out there, since it is handy and a real ink-saver. :)

Thanks guys!

-Sydney

**Comment by innermous** [comment]
What happened with Ctrl+P shortcut?

**Comment by sydneyjd** [comment]
That works to print the whole page, but doesn't allow you to print only selected text or images, ect.

**Comment by nowrep** [comment]
That's not possible, sorry.
