### ISSUE TITLE
Wrong link at "Report Issue" help page

### ISSUE THREAD

**Issue by flongbox** [QupZilla/qupzilla#1839]
The "send" button on the "Report Issue" help page results in a error message:
Server not found
QupZilla can't load page from www.qupzilla.comreportbug.php.

When I tried to load the page with the slash inserted, as
www.qupzilla.com/reportbug.php
I get another error message:
"All fields are required!"

**Comment by nowrep** [comment]
What version do you have and how did you build it?

**Comment by JHooverman** [comment]
I am able to reproduce it with the latest windows version (1.8.9/ 5.5.1/ 538.1).
According to the crashlog in issue #1838 flongbox seems to have version 1.8.9/ 5.4.2/ 538.1.

**Comment by nowrep** [comment]
Bad redirect on qupzilla.com server.

**Comment by nowrep** [comment]
Disabled the http -> https redirect on qupzilla.com.
