### ISSUE TITLE
Building on Windows fails to due too many subtargets?

### ISSUE THREAD

**Issue by Vistaus** [QupZilla/qupzilla#1851]
For an experiment, I'm trying to get the latest Git version to work on Windows (my dad lets me use his PC for this). Installed all that's necessary but make fails :(

```
C:\Users\Frits\Downloads\qupzilla>C:\Users\Frits\Downloads\make.exe -j5         "C:\Program Files\Qt\Qt5.6.0\5.6\msvc2015_64\bin\qmake.exe" -o Makefile qupzilla.pro                                                                            "C:\Program Files\Qt\Qt5.6.0\5.6\msvc2015_64\bin\qmake.exe" -o Makefile qupzilla.pro                                                                            cd src\lib\ && ( if not exist Makefile "C:\Program Files\Qt\Qt5.6.0\5.6\msvc2015_64\bin\qmake.exe" C:\Users\Frits\Downloads\qupzilla\src\lib\lib.pro -o Makefile ) && C:/Users/Frits/Downloads/make -f Makefile                                 make[1]: Entering directory 'C:/Users/Frits/Downloads/qupzilla/src/lib'         Makefile:75: *** multiple target patterns.  Stop.                               make[1]: Leaving directory 'C:/Users/Frits/Downloads/qupzilla/src/lib'          makefile:42: recipe for target 'sub-src-lib-make_first' failed                  make: *** [sub-src-lib-make_first] Error 2
```

How do I get it to build?

**Comment by nowrep** [comment]
You should use QtCreator.

**Comment by Vistaus** [comment]
Oh, I thought I needed to use that because the readme said so. I've now imported it into QtCreator but upon configuring it says that the QupZilla project uses the "invalid kit Desktop" and won't continue past that and I don't know exactly what kit I should choose instead (I'm not familiar with Qt Creator).

**Comment by nowrep** [comment]
You need to have it correctly setup. It should work fine right after install if you install the whole SDK.

**Comment by Vistaus** [comment]
I did install the whole SDK, it's a fresh install. Tried again today, but it still gives the same error :(

**Comment by Vistaus** [comment]
I investigated a bit more and it seems that it can't find the right compiler. Installed MingW and added the MingW Compiler in the project options, but it refuses to accept the compiler. What else can I try?

**Comment by Vistaus** [comment]
Anyone? :(

**Comment by nowrep** [comment]
Just use msvc, but correctly set the build kit. It's in Preferences, also make sure it is correct in Project tab (on the left).

**Comment by Vistaus** [comment]
I've set everything correctly in Qt Creator and used mdvc, but Build & Run now says "No compiler can produce code for this Qt version." What to do now?

**Comment by Martii** [comment]
@Vistaus 

Doing a little reversing from AppVeyor I was able to compile a 32 bit build of QupZilla... but not much beyond that just yet:

* Have Visual Studio 2015 installed
* Install Qt Unified Installer and using these options *(the ones below the "Qt Data Visualization" are normally selected but at the very least "Qt WebEngine" should be selected)*:
![1851](https://cloud.githubusercontent.com/assets/114709/24496671/17daab96-14f6-11e7-9ae6-28d53139614b.png)
* Install openSSL binaries from https://slproweb.com/products/Win32OpenSSL.html *(they do have the 64 bit binaries too)*
* Install git-scm 
* Hardcode some PATHs in the System settings *(this is temporary for me but may not be for others)* Using `C:\Qt\5.8\msvc2015\bin;C:\Qt\Tools\QtCreator\bin;C:\OpenSSL-Win32\bin;` prepended to the Path variable.
* Checkout QupZilla

Then I ran this from the command line *(cmd)*:

``` cmd
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
qmake CONFIG+=release INCLUDEPATH+="C:\OpenSSL-Win32\include" LIBS+=-LC:\OpenSSL-Win32\lib QupZilla.pro
call jom
```

Some parameters may not be needed but remember I'm using AppVeyor as a template for human instructions to test. And recall that I haven't gotten past compiling *(building)* yet.

Misc notes: 
* Interesting that Git Bash couldn't checkout the repo here... said it didn't know how to handle https so I popped into native `cmd.exe` and it works.
* `jom.exe` works like `make` e.g. `> jom clean` and `> jom distclean` works for cleaning up.

Hope this helps you get jump started. :smile_cat:

**Comment by Martii** [comment]
Flipped everything to 64 bit architecture and paths... and it built too... dependencies via installation are another story yet to be discovered as well as packaging.

**Comment by srazi** [comment]
> I've set everything correctly in Qt Creator and used mdvc, but Build & Run now says "No compiler can produce code for this Qt version." What to do now?

1- You have to install the newest version of Qt compiled using MSVC. For example [qt-opensource-windows-x86-msvc2015-5.8.0.exe](http://download.qt.io/official_releases/qt/5.8/5.8.0/qt-opensource-windows-x86-msvc2015-5.8.0.exe) that needs MSVC2015 Update 3 (3 GB + 7 GB)
2- The error means what it says! You are using MSVC compiler but installed Qt is compiled using MinGW.

P.S. I think this issue is a general Qt question and should be closed. As AppVeyor [reports](https://ci.appveyor.com/project/srazi/qupzilla-utoeb) there is no issue with building on Windows.

**Comment by Vistaus** [comment]
I don't have access to a Windows machine anymore so I can't look into this anymore. Will close, but the discussion can go on, if you guys want to.
