### ISSUE TITLE
No spellchecker

### ISSUE THREAD

**Issue by francoism90** [QupZilla/qupzilla#1852]
I don't have any spellchecker settings (e.g. In Preferences => Other and on input fields).
I'm using the master branch with Qt5.6 on Arch Linux.

Thanks.

**Comment by nowrep** [comment]
Because master branch has no spellcheck support. Spellcheck will be back in QtWebEngine 5.7

**Comment by francoism90** [comment]
Thanks @nowrep for the update.
Seems there's still a lot of work to do (WebEngine vs WebKit).

Keep up the good work! :)
