### ISSUE TITLE
WebExtensions support

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1855]
Mozilla is making some concessions with what it calls [WebExtensions](https://wiki.mozilla.org/WebExtensions), which is really switching to Chromium extension system.

For the sake of promoting Qupzilla, I suggest to add support either for WebExtensions or Chromium extensions.   For stability, I would like to have this proposed WebExtensions extension system to allow running each WebExtensions extension in a different PID.

Maybe this extension system should be provided as an extension.

**Comment by JHooverman** [comment]
Did you have a look at the [FAQ](https://github.com/QupZilla/qupzilla/wiki/FAQ#13-does-qupzilla-support-firefox-and-or-chrome-extensions)? However, WebExtensions have not been discussed yet.

**Comment by GreenLunar** [comment]
No, I did not.  I think, it would be better to stick with WebKit.  I suggest to close this issue.

**Comment by ke7ofi** [comment]
How heavy would it make things? Maybe have WebExtensions support available as a plugin (if architecture permits)? It would definitely make the browser less suckless, but that's not the goal, is it?

**Comment by GreenLunar** [comment]
> It would definitely make the browser less suckless, but that's not the goal, is it?

I think you are correct.  I, myself, use only four extensions (one of them is available for Qupzilla) with Mozilla, and I am certainly not interested in Qupzilla to consume more resources; this is why I suggest this feature to run WebExtensions in separate processes.

The reason I suggest this is to get Qupzilla more popular; __then again__, if a variety of extensions would really make a difference, Mozilla would not have been changing its extension system API so frequently as it does.

AMO and Android Market are really no difference, they both have spam and useless applications more so than useful and meaningful applications.

I am solely using F-Droid, which does not have hundred of thousands of applications, for mobile software.

**Comment by nowrep** [comment]
Unless it's supported in QtWebEngine, it won't be in QupZilla.

**Comment by GreenLunar** [comment]
Another [rant](http://www.downthemall.net/the-likely-end-of-downthemall/) that realizes the uselessness of popular extension repositories.

The likely end of DownThemAll?
August 21, 2015

> Mozilla just announced their intent [to deprecate so called XUL-based add-ons](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/) in favor of what they call the WebExtensions API within the next year or two. The WebExtensions API is supposed to be mostly compatible to Chrome/Safari extension APIs.

> What does this mean for DownThemAll!? Well, for starters, DownThemAll! will be dead if XUL-based add-ons with XPCOM access are gone. Simple as that. The new APIs would only allow for a severely limited in functionality, severely stripped down DownThemAll! at best.

> Gone with DownThemAll! will be add-ons that e.g. let you change major bits about the Firefox user interface (e.g. tabs tree add-ons), add-ons that allow you to do more “advanced” stuff than just showing or slightly altering websites, such as e.g. restarting the browser upon click (unless mozilla kindly provides an API for that, which won’t be compatible with Chrome, of course). Add-ons like NoScript will be severely limited in their feature set as well. Say byebye to Greasemonkey and hello to Tampermonkey, with it’s limitations. Want that add-on that lets you change the new tab page for something else or enhances that page? Maybe it will be available, maybe not, depending on if and when mozilla kindly provides WebExtensions APIs for such things. And of course, depending on if there will be an author creating this entirely new add-on from scratch.

> What this also means: Almost all your existing add-ons will be broken, entirely, save for some Add-on SDK add-ons, namely those that don’t do anything fancy. Sure, even today, lots of add-ons break, and some add-ons will not get updated when they do and there are no suitable replacements. However, with this change, almost every add-on will be completely broken and in need of major updating by the extension authors. Good luck with that.

> It is safe to say, that Firefox will not be Firefox anymore as far as extensions go, but instead will become yet another Chrome-clone.

> To be clear: I was furious when the extension signing stuff was announced and then actually implemented, which effectively created yet another Walled Garden, but regarding this announcement **I am just sad**. Right now, it feels like I just learned my dear old friend Firefox is going to die.

**Comment by alekksander** [comment]
it's been two years. any changes on the subject?

**Comment by nowrep** [comment]
My comment still stands: Unless it's supported in QtWebEngine, it won't be in QupZilla.

Falkon now supports Python extensions and may also get support for JavaScript/QML extensions, but that's it.
