### ISSUE TITLE
Some languages are missing in Windows Installer

### ISSUE THREAD

**Issue by s8321414** [QupZilla/qupzilla#1860]
As title says, like zh-TW for example.
Affected version: at least 1.8.8 and 1.8.9

**Comment by s8321414** [comment]
Still not fixed in 2.0.0, I can't see zh_TW translation in Qupzilla on Windows

**Comment by s8321414** [comment]
And still missing in 2.0.1, I don't know why.

**Comment by nowrep** [comment]
Installer needs to be adjusted: https://github.com/QupZilla/qupzilla/blob/master/windows/installer.nsi#L441 - like this

**Comment by s8321414** [comment]
@nowrep could you fix it? or we should make PR?

**Comment by nowrep** [comment]
PR woudl be great. I will fix it if I don't forget it again, sorry.

**Comment by s8321414** [comment]
hmm... I don't have time to do it recently...

**Comment by s8321414** [comment]
@nowrep could you fix it? seems it lacks so much languages in our windows binary...
