### ISSUE TITLE
Add QupZilla to OpenUserJS

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1866]
I don't think doing so without consulting would be appropriate.  I would like to see QupZilla under `openuserjs.org/about/`. Below is a proposed description.

> QupZilla is a new and very fast QtWebEngine browser. It is actively developed and uses open standards (so it's easier for programmers to work with it). It aims to be a lightweight web browser available through all major platforms.

> This project has been originally started only for educational purposes. But from its start, QupZilla has grown into a feature-rich browser. The very first version of QupZilla has been released in December 2010 and it was written in Python with PyQt4 bindings. After a few versions, QupZilla has been completely rewritten in C++ with the Qt Framework.

> QupZilla ships with its own port of Greasemonkey as an extension.

https://openuserjs.org/about/Userscript-Beginners-HOWTO
https://openuserjs.org/about/QupZilla

**Comment by ke7ofi** [comment]
Actually, since we've been talking about ways of handling extensions, I have a question. What can the current extension implementation do that generic JavaScript can't? What if "installing" a script just entailed copying it to a directory the browser reads out of?

**Comment by nowrep** [comment]
I don't think the second paragraph in description makes sense (the history one). Also I think it will be better to replace QtWebEngine with just Qt.

**Comment by GreenLunar** [comment]
> I don't think the second paragraph in description makes sense (the history one). Also I think it will be better to replace QtWebEngine with just Qt.

This is a merely a proposed description.  Do you have a better description?

I want QupZilla appear at https://openuserjs.org/about/QupZilla

**Comment by GreenLunar** [comment]
I have made a pull request at https://github.com/OpenUserJs/OpenUserJS.org/pull/909

**Comment by GreenLunar** [comment]
The page has been created.  The second paragraph, which, I think, gives a good impression, has been submitted.  If you want to change something, please feel free to do so or ask me to do so.
