### ISSUE TITLE
Greasemonkey queries

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1869]
Below are several questions by @Martii of OpenUserJs.

1. Why such an old version Greasemonkey? e.g. is it ported from that version of GM or is it the native version for 1.8.9
2. I just installed two of my scripts and neither one is working... and I know that they are very vanilla ECMAScript5 with no special '@grants'. I'll try it under Windows and see if I have any better luck.
3. Description of Greasemonkey says 'Provides support for userscripts (www.userscripts.org)'... USO is no longer around so that may be confusing.. although I did notice the hyperlink in settings.
4. Where's the debugger?

From: https://github.com/OpenUserJs/OpenUserJS.org/pull/909

**Comment by Martii** [comment]
To quote myself :)

> Ahh found the "Console" *(<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>i</kbd>)*... although not real specific on "SyntaxError: Parser error"

**Comment by nowrep** [comment]
1. The version of plugin in QupZilla has nothing to do with Firefox Greasemonkey addon versions.
2. It works fine with `master` (= QtWebEngine). QtWebKit versions may have issues with old web engine, but it generally works fine there too.
3. Link points to openuserjs.org in `master`
4. With QtWebEngine it provides much better debug info also with exact line in userscript where the error occurred.

**Comment by Martii** [comment]
@nowrep 
Thanks... but the description of the plugins says USO.

See [`f46364b`/src/plugins/GreaseMonkey/gm_plugin.cpp#L42](https://github.com/QupZilla/qupzilla/blob/f46364bc556466d74815a6725f86eff2f4f2971f/src/plugins/GreaseMonkey/gm_plugin.cpp#L42)

**Comment by nowrep** [comment]
Yeah, that should be changed.

**Comment by Martii** [comment]
Let me see if my Hello World script works... that is about as reduced case as it gets... but the debugger isn't really helping me see what is up with Meta View and JsBeautify scripts.

**Comment by nowrep** [comment]
What OS do you test it on?

**Comment by Martii** [comment]
Linux ROSA... that's why I said I'll try it under Windows... perhaps the package is corrupt in their repo.

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) QupZilla/1.8.9 Safari/538.1`
Ahh I see it's Safari based.


https://openuserjs.org/scripts/Marti/RFC_2606§3_-_Hello,_World! is the Unit Test

**Comment by Martii** [comment]
Hmmm no support for [IIFE](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression) it seems... that's a bummer.

**Comment by nowrep** [comment]
That's not correct, this script works fine with QtWebEngine and also should with QtWebKit (which you have).

**Comment by nowrep** [comment]
Actually the problem is that the metadata header is not at the top of the file. Didn't seem to be issue with other scripts and yours script is the first one that I see places the metadata header in the middle of the file.

**Comment by Martii** [comment]
Well it's definitely not working with Hello, World... the Console isn't helping much... removed the IIFE and it works... I'll try Google style IIFE instead of Moz's.

**Comment by Martii** [comment]
> Actually the problem is that the metadata header is not at the top of the file

That should be fixered as per the UserScript metadata block spec I think. :) Kewl... thanks for the solution... I'll go ahead and merge his PR... will need some TLC and some screenshots but at least I got a script working on it. :)

**Comment by Martii** [comment]
@nowrep 

Awesome and many thanks... look forward to this in the wild with my distro package manager. Unfortunately I'm shy on the Qt requirements of this project *(=5.5)* and recompiling Qt to a newer version takes too much time in my already thin schedule.

Btw this is the fastest browser I've ever seen... tested out YouTube and the video started playing before I could switch tabs. ;) Very nice project you have here... when I have some more available time I'll do some more testing and possible issue reports if needed... including outside of the GreaseMonkey plugin.

**Comment by innermous** [comment]
@Martii you can always use snapshots, if you have no time for manual compiling :thumbsup:
