### ISSUE TITLE
Broken SSL for some sites (Google, maybe some other)

### ISSUE THREAD

**Issue by NickLion** [QupZilla/qupzilla#1870]
When I'm trying to open Google sites (*.google.com) using QtWebEngine version (master, Qt 5.6) I got SSL connection error:
ERR_SSL_PROTOCOL_ERROR

QtWebKit version worked fine. Other sites (like this one, bugs.kde.org, duckduckgo.com, etc) looks ok. Any ideas? BTW, is there certificate manager in new verision?

PS: OS — Linux (openSUSE Leap 42.1 x86_64)

**Comment by demmm** [comment]
This is a well known issue with anything based on chromium below 47 and nss 3.21 and newer.
Example bug report:
https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1520568
Either go back to nss 3.20 or you need to patch qtwebengine to include the new ways that are now implemented in chromium 47, example of a working patch for qtwebengine 5.6.0RC:
https://github.com/KaOSx/main/blob/master/qtwebengine/nss321.diff

**Comment by NickLion** [comment]
Thanks for information!
