### ISSUE TITLE
"Default zoom on pages" doesn't work properly

### ISSUE THREAD

**Issue by innermous** [QupZilla/qupzilla#1871]
This can be reproduced only in master branch.
You can go into Preferences->Browsing->Set "Default zoom on pages" option to whatever, say, 30%.
Open new tab - it will be 100% zoom. Same applies to zoomed pages, if you load another URL via address bar - zoom is set back to 100%.
In webkit branch it works as intended.

**Comment by nowrep** [comment]
If you switch to other tab and then switch back, the correct zoom will be used :D

**Comment by nowrep** [comment]
This needs to be reported upstream.

**Comment by innermous** [comment]
@nowrep I knew! I know it must be upstream! I checked code several times, nothing could be broken!
I forgot QtWebEngine is still in development and has a bunch of bugs.
:smiling_imp:

**Comment by innermous** [comment]
This is working now.
