### ISSUE TITLE
User agent manager doesn't seem to work?

### ISSUE THREAD

**Issue by jamesqf** [QupZilla/qupzilla#1874]
I'm having a problem with a particular site, www.chase.com (which unfortunately you can only access if you have a credit card account with them).  They have the security "feature" (I'd call it a bug, myself) which lets the site remember which browser I use.  I want to change from my old browser (Opera) to qupzilla, but their security page says I must use one of four browsers (IE, Chrome, Safari, or Firefox).  I tried setting the user agent identification to each of the 3 Mozilla options listed in the User Agent Manager window, but it still says I'm not using an accepted browser.  How can I get qupzilla to tell it the right magic words?

(FWIW, the site still works perfectly well with my old Opera 11.60, except for the annoying "please upgrade your browser" banner message".)

I'm using qupzilla 1.8.9 on OpenSUSE 13.1.

**Comment by nowrep** [comment]
It should work. You can check it eg. at http://whatsmyuseragent.com/

**Comment by jamesqf** [comment]
It works now.  Seems as though the problem must have been on their site, as it's changed a bit since I tried it.  And thanks for the user agent link, it'll be useful in the future.
