### ISSUE TITLE
qt theme issue

### ISSUE THREAD

**Issue by th1rd** [QupZilla/qupzilla#1875]
Debian jessie, qt 5.3.2 qupzilla 1.8.9. qt theme qtcurve set by qt5ct (QT_QPA_PLATFORMTHEME="qt5ct").

Whe qupzilla starts I see problems with drawing some GUI elements. Main menu, address bar, search bar and add empry tab button.

![1](https://cloud.githubusercontent.com/assets/17023663/13522859/22736eac-e203-11e5-8ec6-67a0998c4b36.png)

After I open Preferences dialog (edit->preferences) and just click apply without any changes I see correct drawing UI.

![2](https://cloud.githubusercontent.com/assets/17023663/13522860/227744e6-e203-11e5-9f60-b042aca0c4de.png)

**Comment by nowrep** [comment]
Does it happen with other Qt styles?

**Comment by th1rd** [comment]
Yes. With other qt styles and with other qupzilla styles.

**Comment by nowrep** [comment]
And without qt5ct?

**Comment by th1rd** [comment]
Without qt5ct I can't set qt theme and only qt fusion works. But it
looks correct.

**Comment by nowrep** [comment]
So if Fusion is broken with qt5ct then it is qt5ct bug.

**Comment by nowrep** [comment]
Btw you can change style with eg. `qupzilla -style qtcurve`

**Comment by th1rd** [comment]
Hm. Maybe. But whit qupzilla looks correct after press apply without
changes in the preferences dialog?

And other applications looks correct too.

**Comment by th1rd** [comment]
Thanks for help. I will try to contact with qt5ct developers to solve this problem and let you know if any solutions will be found.

**Comment by nowrep** [comment]
I don't want to add workarounds, so that would be best. Thanks.

**Comment by th1rd** [comment]
Now qt5ct is fixed and checked. Thanks for help.
