### ISSUE TITLE
roundcube (kolab) shortens filenames when archiving mails if it contains /

### ISSUE THREAD

**Issue by brbauer** [QupZilla/qupzilla#1876]
when you want to save emails as a file locally (.eml) in roundcube (kolab3) the filename is shortened to the rest of the title from the last / to the end.
If the filename contains a colon (:) , this is removed ok - should do the same with / or better change all occurences to _
Iceweasel (firefox) works ok under debian (jessie,sid) and changes : and / to _ because : and / are not aalowed in filenames.

**Comment by nowrep** [comment]
I don't really understand. Can you please provide some example?
Is this about saving (downloading) files?

**Comment by brbauer** [comment]
Out of the imap-server of kolab you want to save the email locally as a file with the ending .eml. The filename will be the title of the mail, which can contain non-alphabetic characters. Those, who are forbidden in filenames have to be removed or changed before saving the .eml file.
This works for : in qupzilla but not for / .
AW: GZ 43154/15 C - Lageplan § 24 TBO Muresan Gst.Nr. 3788/2 KG Kirchberg - 82005
should become
AW_ GZ 43154_15 C - Lageplan § 24 TBO Muresan Gst.Nr. 3788_2 KG Kirchberg - 82005.eml
ok?
At the moment it becomes       2 KG Kirchberg - 82005.eml  in qupzilla

**Comment by brbauer** [comment]
hurrah, seems to be repaired in version 2.0.2 (debian sid), filenames are full length - ok now!
