### ISSUE TITLE
can't acces to the ssl site

### ISSUE THREAD

**Issue by th1rd** [QupZilla/qupzilla#1877]
can't access to site https://ihelper.mts.by/selfcare
qupzilla 1.8.9

sorry for reopen issue, just miss the  button.

**Comment by The-Compiler** [comment]
Seems like the server is only offering TLSv1 (rather than 1.2) and OpenSSL doesn't like that.

**Comment by th1rd** [comment]
I have another one internal resource in office like this and I shoud use these services :( firefox works

**Comment by nowrep** [comment]
Sorry, there is nothing to do. QtWebEngine will fix it.
