### ISSUE TITLE
Support of <!DOCTYPE svn>?

### ISSUE THREAD

**Issue by johanneshau** [QupZilla/qupzilla#1880]
HI, I am new to QupZilla and GitHub and the forum here. I hope this is the right place for my question. If not please excuse and point me to the correct location.

I recently discovered QupZilla and I like it because it is not so bloated like other browsers ...
I have to work with SVN repositories. Some of them just show an empty page when opened with QupZilla, some others do work. The source of pages, which do not show any content, are similar to this:

`<?xml version="1.0"?>`
`<?xml-stylesheet type="text/xsl" href="/svnindex.xsl"?>`
`<!DOCTYPE svn [`
`  <!ELEMENT svn   (index)>`
`  <!ATTLIST svn   version CDATA #REQUIRED`
`                  href    CDATA #REQUIRED>`
`  <!ELEMENT index (updir?, (file | dir)*)>`
`  <!ATTLIST index name    CDATA #IMPLIED`
`                  path    CDATA #IMPLIED`
`                  rev     CDATA #IMPLIED`
`                  base    CDATA #IMPLIED>`
`  <!ELEMENT updir EMPTY>`
`  <!ELEMENT file  EMPTY>`
`  <!ATTLIST file  name    CDATA #REQUIRED`
`                  href    CDATA #REQUIRED>`
`  <!ELEMENT dir   EMPTY>`
`  <!ATTLIST dir   name    CDATA #REQUIRED`
`                  href    CDATA #REQUIRED>`
`]>`
`<svn version="1.6.17 (r1128011)"`
`     href="http://subversion.tigris.org/">`
`  <index rev="5" path="/application" base="project">`
`    <updir />`
`    <file name="Makefile" href="Makefile" />`
`    <file name="source_file.c" href="source_file.c" />`
`    <file name="header.h" href="header.h" />`
`    <file name="main.c" href="main.c" />`
`  </index>`
`</svn>`

I am able to view these SVN pages from within Firefoy and Google Chrome.
I expect that the SVN server can be configured to show <!DOCTYPE html> pages as well, but the repositories in question are not within my control.
Is it even possible to view these pages with QupZilla? Is there a configuration item or a Plugin or anything?

I am using QupZilla 1.8.9 on Windows 7, 64bit.

Thanks a lot!

Johannes

**Comment by nowrep** [comment]
QtWebKit doesn't support XML StyleSheets. Will be fixed in QtWebEngine (QupZilla 2.0).
