### ISSUE TITLE
`responseURL` =: `undefined`

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla#1884]
So was updating [one of my Userscripts in this section](https://github.com/Martii/UserScripts/blob/84b35dc5bfce13b6aca00816919db2be6954376f/src/oujs/Meta%20View/oujs%20-%20Meta%20View.user.js#L254-L267) for every browser *(that I test on)* and it appears that [`responseURL`](https://developer.mozilla.org/docs/Web/API/XMLHttpRequest/responseURL) is `undefined` at the conclusion of a [`XMLHttpRequest`](https://developer.mozilla.org/docs/Web/API/XMLHttpRequest).

**Q**: Is there an older property name to be used?

``` sh-session
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) QupZilla/1.8.9 Safari/538.1
```

[Search of issues resulted in nothing here related yet](https://github.com/QupZilla/qupzilla/search?utf8=%E2%9C%93&q=responseURL).

Thanks so much for the look. :)

**Comment by Martii** [comment]
Btw.... forgive the educated guess here on where the issue lays...

@nowrep [wrote](https://github.com/QupZilla/qupzilla/issues/1871#issuecomment-189721273):
> This needs to be reported upstream.

Where exactly is that?

**Comment by nowrep** [comment]
QtWebKit uses too old WebKit version. It should work fine with QtWebEngine.

**Comment by Martii** [comment]
@nowrep 
**Q**: And how do I go about getting the QtWebEngine version of QupZilla instead of the QtWebKit? 

My repo package manager is only giving me this one and I'm shy on Qt version to build the project manually... most precompiled bins don't work in ROSA/OpenMandriva because it's one of the lesser known *(but more stable imho)* of all the *nix distro's. It's been many years since I've last developed in Qt so the "snapshots" comment that was mentioned to me a few weeks back is greek to me atm. I'd love to contribute here more but not at the cost of stability of my distros on dev stations... plus I'm out of machines to add another distro with bleeding edge versions. :\

**Comment by nowrep** [comment]
Use `master` branch of QupZilla with Qt 5.6 that was released today.
