### ISSUE TITLE
Option to force user-selected fonts for all websites

### ISSUE THREAD

**Issue by Nicky726** [QupZilla/qupzilla#1886]
Suggestion: Add optional configuration which would enforce usage of user-selected fonts on all websites. Although user-selected fonts are configured in QupZilla (Linux Libertine/Biolinum in my case), preferences of websites are prefered.

**Comment by jamesqf** [comment]
Can't you already do this with a user CSS?  Seems to work for me, as this bit copied from mine:

[code]* 
{
  color: white !important;
  background-color: black !important;
  background-image: black !important;
  font: 18px/1.4em normal normal Sassoon, Arial, Helvetica, sans-serif !important;
  text-align: left                    !important;
}
[/code]

**Comment by Vistaus** [comment]
This is a duplicate of: https://github.com/QupZilla/qupzilla/issues/1240
