### ISSUE TITLE
Few issues (questions)

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#1893]
1. Can't start *Web Inspector*.
2. If any image can be zoom in/out, the cursor still looks as arrow, but not as magnifier.
3. Why **master** uses both Qt4 and Qt5 libraries?

_______________
91e6c2e  Qt 5.6

**Comment by cranes-bill** [comment]
4 .  _Printing_ also does not works: `QMetaObject::invokeMethod: No such method BrowserWindow::printPage()`

**Comment by nowrep** [comment]
1. You must set remote debugging port (`export QTWEBENGINE_REMOTE_DEBUGGING=12345`)
2. Probably QtWebEngine bug
3. It uses only Qt 5 (>= 5.6)

**Comment by cranes-bill** [comment]
Thanks for the answer!
About the Q1, can i set that permanently in QupZilla before compilation?
About the Q2, as my guess, so maybe @JHooverman would like to inform them as opening an issue!? :blush:
About the Q3, but my not:
```	
	libQtWebKit.so.4 => /lib64/libQtWebKit.so.4 (0x00007fcc5c228000)
	libQtDBus.so.4 => /lib64/libQtDBus.so.4 (0x00007fcc5bfaa000)
	libQtScript.so.4 => /lib64/libQtScript.so.4 (0x00007fcc5bb65000)
	libQtSql.so.4 => /lib64/libQtSql.so.4 (0x00007fcc5b925000)
	libQtGui.so.4 => /lib64/libQtGui.so.4 (0x00007fcc5ac4a000)
	libQtNetwork.so.4 => /lib64/libQtNetwork.so.4 (0x00007fcc5a903000)
	libQtCore.so.4 => /lib64/libQtCore.so.4 (0x00007fcc5a418000)
	libQtOpenGL.so.4 => /lib64/libQtOpenGL.so.4 (0x00007fcc4ef88000)
	libQtXml.so.4 => /lib64/libQtXml.so.4 (0x00007fcc4ed43000)

```
 Initially i thought that's my fault, but then i checked [this](http://download.opensuse.org/factory/repo/oss/suse/x86_64/qupzilla-1.8.9-1.1.x86_64.rpm) (WebKit version) and [this](http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/q/qupzilla-1.9.99-0.9.20160225gitff0a8898616e1.fc25.x86_64.rpm) (WebEngine) and noticed that it's the same
About the Q4 It was most likely to get an attention :smile:

**Comment by nowrep** [comment]
1. No, you can set it in `.profile`, but I wouldn't recommend that.
3. Then something is wrong or you are running `ldd` on wrong library.

**Comment by cranes-bill** [comment]
Have no idea how to find the reason why **ldd** looking for those libraries, but i'm closing that....
Thanks!

**Comment by nowrep** [comment]
If you are using QtWebEngine, there is no way that it loads Qt 4 libraries (it would crash).

**Comment by cranes-bill** [comment]
I „hid“ `libQtGui.so.4` and **ldd** reported _it not found_, but even though QupZilla starts normally, so probably **ldd** „lying“ by any odd reason.... :anguished:
