### ISSUE TITLE
overlapping bookmarks on the bookmarks toolbar

### ISSUE THREAD

**Issue by r-a-v-a-s** [QupZilla/qupzilla#1896]
Version: 1.9.99
OS X 10.11.4 / retina display

<img width="446" alt="screen shot 2016-03-27 at 11 38 31 am" src="https://cloud.githubusercontent.com/assets/12013378/14067118/f118bab2-f411-11e5-8925-116afac2618e.png">

**Comment by nowrep** [comment]
Same bug is also on non-retina screen.

**Comment by ke7ofi** [comment]
I can't replicate it on Linux.
