### ISSUE TITLE
Running qupzilla in single instance mode?

### ISSUE THREAD

**Issue by idomeneo1** [QupZilla/qupzilla#1899]
Is there currently any setting that allows you to open all new web pages into an existing instance?

This doesn't work at all if you have --private-browsing as a default (in .bashrc in Linux). Qupzilla opens a new window every time, even with --new-tab.
Plus, using --new-tab opens up TWO tabs when it opens a new fresh browser instance - it opens up the web page, plus a blank tab on top of it.

**Comment by nowrep** [comment]
Private browsing is separate instance, so it won't work like you want. You must run QupZilla in normal mode (eg. no private browsing) to get single instance mode.

**Comment by idomeneo1** [comment]
There should a setting for running Qupzilla as a single instance. 
There is a setting to force a new instance (--no-remote), but not for maintaining just one instance and one window.

The workaround is the "new-tab" switch, but if you try to set 'qupzilla --new-tab' as a default (such as in .bashrc in Linux), or try to run a script with it:
1) it opens double tabs every time it opens a new window, and
2) there's no way to prevent Qupzilla from opening a zillion windows if you want to use "private-browsing" as your default, or in your scripts, or on your toolbar.

**Comment by nowrep** [comment]
Yes, private browsing is not meant to be used as "default".

**Comment by idomeneo1** [comment]
There is still the double tab problem with the "new-tab" default.

And also "private-browsing" would not be a bad thing for people to default to.
