### ISSUE TITLE
GreaseMonkey: `GM_UrlInterceptor::interceptRequest` too aggressive

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla#1903]
Currently when using `XMLHttpRequest()` to gather the meta routine via a .user.js it prompts to install in a Userscript. *UNEXPECTED BEHAVIOR*

Some possible solutions *(logic wise)*:

1. Check for an `Accept` request header present of `text/x-userscript-meta` and don't trigger the url interceptor with an install as per current specs.
2. If a query string e.g. `?blahA=1&blahB` or empty e.g. `?`and/or a hash e.g. `#yaddaying` or empty `#` are present it shouldn't trigger the url interceptor with an install as per current specs.

Ideally any `XMLHttpRequest()` with no query string and hash in a .user.js should never trigger an install UI action too.

Affected versions:
* `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QupZilla/1.9.99 Chrome/45.0.2454.101 Safari/537.36`  with items 1 and 2, and also in the address bar.
* `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) QupZilla/1.8.9 Safari/538.1` with item 2 only, and also in the address bar.

Related:
* #1653

Refs:
* [`7191729`/src/plugins/GreaseMonkey/gm_urlinterceptor.cpp#L27-L33](https://github.com/QupZilla/qupzilla/blob/7191729eb90d9cba1c9d89d15a64cb84a9d5fcb7/src/plugins/GreaseMonkey/gm_urlinterceptor.cpp#L27-L33)
* http://doc.qt.io/qt-5/qwebengineurlrequestinfo.html#navigationType
    * http://doc.qt.io/qt-5/qwebengineurlrequestinfo.html#NavigationType-enum
    * http://doc.qt.io/qt-5/qwebengineurlrequestinfo.html#ResourceType-enum *(esp. `QWebEngineUrlRequestInfo::ResourceTypeXhr`)*
* http://doc.qt.io/qt-5/qnetworkrequest.html#hasRawHeader *(or similar since doesn't appear in [knownHeaders](http://doc.qt.io/qt-5/qnetworkrequest.html#KnownHeaders-enum) ... class not visibly present in argument vectors at this referenced code point)*
    * http://doc.qt.io/qt-5/qnetworkrequest.html#rawHeader
* [oujs - Meta View](https://openuserjs.org/scripts/Marti/oujs_-_Meta_View) Unit Test

P.S. Until I get a little more versed with ArchLinux, the Code base here, and get a working VNC Server *(which ever one I end up with since that machine is quite a ways away)* ... it's going to be a bit slow for me to do PR's... sorry... but this is my guess where a fix might be applied. :)

TIA.

**Comment by nowrep** [comment]
Can you please post link to the specs?
Also, the second case (2.) should not trigger downloading userscript as there is a `endsWith(".user.js")` check which would fail.

**Comment by Martii** [comment]
> Can you please post link to the specs?

It's been rewritten a bazillion times for Moz's e10s but the base code upstream is [currently here](https://github.com/greasemonkey/greasemonkey/blob/fe737c78f61a83273eb2031a143c541b409d02eb/modules/installPolicy.js#L18)

I haven't tried GH .user.js http pages yet either as described at greasemonkey/greasemonkey#1049 such as https://github.com/Martii/UserScripts/blob/master/src/oujs/Meta%20View/oujs%20-%20Meta%20View.user.js which also requires a Content-Type check... looks like at least 1.8.9 tries to install it.. with a mangled UserScript metadata block too. I'll issue that in a bit after I run into the other room and recheck it on 1.9.99.

> Also, the second case (2.) should not trigger downloading userscript as there is a `endsWith(".user.js")` check which would fail.

Visit https://openuserjs.org/scripts/Marti/oujs_-_Meta_View/source and click Raw Source... e.g. that's a hash terminated url which doesn't trigger installation with GM / GM Port... but in QupZilla it tries to install it or says it's already installed. It's possible that the back-end for QupZilla is dropping the hash altogether but even if I were to change that back to a query string empty e.g. `?` it still triggers an install UI intercept with QupZilla and every Qt so far.

**Comment by nowrep** [comment]
>  it still triggers an install UI intercept with QupZilla and every Qt so far.

Fixed with the linked commit too.

**Comment by Martii** [comment]
> EDIT: Actually it was working fine before too, because the url is ...user.js#

Your right... mixing up my versions during testing a bit... and I'm quite brain fried from getting ArchLinux configured. :smile_cat: 

> Fixed with the linked commit too.

Recompiling... must remember not to use `$ make clean`... habit I have with *node* upgrades.

1.9.99 *(before this commit history in this issue)* still triggers an install with a `Content-Type` of `text/html; charset=utf-8` though from https://github.com/Martii/UserScripts/blob/master/src/oujs/Meta%20View/oujs%20-%20Meta%20View.user.js . For maximum compatibility it should only "intercept" when the `Content-Type` header is `text/javascript; charset=utf-8` and of course output it as UTF-8... not just specify that it is... don't know how this project handles UTF-16 and larger yet... or other encodings.

**Comment by Martii** [comment]
After recompiling 5 times to get the current HEAD of 99dc966 *(appears there is a git issue with git itself and/or the make file created with qmake with uninstal where I had to reclone the entire project and start over from scratch)*... it is still trying to install it.

Visit https://openuserjs.org/scripts/Marti/oujs_-_Meta_View , install the .user.js with the blue Install button and then refresh the page... then click Meta next to Source Code ... comes back with a failure to retrieve and the OSD *(I don't use system notifications)* says it's already installed. :\

**Comment by Martii** [comment]
@nowrep
I would suggest reverting that commit and using at minimum:

``` cpp
    if (info.resourceType() == QWebEngineUrlRequestInfo::ResourceTypeXhr)
        return;
```

... which allows the .user.js to complete as expected.

With 385f10e345d5333146cee180cd4745a22a0a51fc it blocks off url addresses completely with copy/paste, etc. and form requests... which some sites may do. We currently just serve a link via a GET but not everyone does.

**Comment by nowrep** [comment]
Why? It now installs user script only when user clicks on the link with user script. That's afaiu the only way the user script should be installed.

**Comment by Martii** [comment]
Because it's not working here in this brand spanking clean install of ArchLinux with it's Qt 5.6... it still tries to install it when there is a `XMLHttpRequest` to a .user.js with the `Accept` header set for the meta routine.

I've actually tested the current HEAD now and it doesn't fix the issue. I added that code in its place and the "Meta" nav-tab completes the `XMLHttpRequest` instead of intercepting it. I did a `$ sudo pacman -Syu` too just to be sure there wasn't some lingering update in the last 6 hours.

**Comment by Martii** [comment]
If you need the code reference it's [Martii/UserScripts `84b35dc`/src/oujs/Meta View/oujs - Meta View.user.js#L226-L230](https://github.com/Martii/UserScripts/blob/84b35dc5bfce13b6aca00816919db2be6954376f/src/oujs/Meta%20View/oujs%20-%20Meta%20View.user.js#L226-L230).

This is my most heavily tested feature on OUJS with every browser in my test suite e.g. daily to make sure deps are good and someone hasn't found a weakness in *pegjs* or a coding issue on our end... plus it's nice to see when someone has the UserScript metadata block scattered throughout the file with code in between.

**Comment by nowrep** [comment]
Sorry, should be fixed now.
In any case, this looks like QtWebEngine bug.

**Comment by Martii** [comment]
> In any case, this looks like QtWebEngine bug.

Yah I'm thinking that's the case too... this is why I wanted to at least be able to test things. We all make mistakes... still loving your project though. :)
