### ISSUE TITLE
Help->About QupZilla window steals focus

### ISSUE THREAD

**Issue by jamesqf** [QupZilla/qupzilla#1904]
Minor issue, but I noticed just now that, when I wanted to copy version info from the help->about window into a comment, the popup window steals the focus back from the main window.  That is, I move the window so it's not over the main one, click in the comment box, the main window gets focus for a second or so, then it returns to the popup.  

This isn't true of all menu windows.  For instance, I can keep Edit->preferences open while working in the main window.

**Comment by Martii** [comment]
> the popup window steals the focus back from the main window... This isn't true of all menu windows.

That's a modal window/dialog vs non-modal window/dialog

**Comment by jamesqf** [comment]
@Martii: OK, that's WHY it happens (which should make it easier to fix), the problem is that it DOES happen but IMHO shouldn't.

**Comment by nowrep** [comment]
The About popup should block input on main window. If your window manager switch the focus to main window for a sec and then back to about dialog, then it's bug of your window manager. It works correctly with KWin.

**Comment by jamesqf** [comment]
I think you missed my point.  Whatever the WM does is irrelevant: the problem is that I can't do anything else with qupzilla, such as copy info from the About window into a comment, while it is displayed.  This may not be a bug in the sense of an unintended behavior, but it is a usability flaw.
