### ISSUE TITLE
Web-Inspector doesn't start (Qupzilla 2.0.0 portable, Win 10 x64)

### ISSUE THREAD

**Issue by RaSla** [QupZilla/qupzilla#1905]
Web-Inspector does not start either by hotkey (CTRL + SHIFT + I) or by clicking on the "Мenu -> Tools -> Web-Inspector".

Qupzilla 2.0.0 portable, OS: Win 10 x64 - this bug.
Qupzilla 1.8.9 - works fine on the same PC

**Comment by cranes-bill** [comment]
https://github.com/QupZilla/qupzilla/issues/1893#issuecomment-201825813  (first one)

**Comment by nowrep** [comment]
Yes, that's correct: You must set remote debugging port in env variable (eg. `export QTWEBENGINE_REMOTE_DEBUGGING=12345` on Linux)
But even though after that it doesn't work 100% reliably.

Anyway, I will hide the actions from menu when the debugging port is not set as you will not be able to open the inspector.
