### ISSUE TITLE
Download-manager doesn't refresh background (Qupzilla 2.0.0 portable, Win 10 x64)

### ISSUE THREAD

**Issue by RaSla** [QupZilla/qupzilla#1906]
![download-window-bug](https://cloud.githubusercontent.com/assets/7755989/14166111/b1fd9a3a-f729-11e5-9293-4b04b5cab3da.jpg)

Download-manager window:
"status string" - Doesn't refresh background,
so every next string drawing OVER previous one

(screenshot is attached)

**Comment by nowrep** [comment]
This only happens on Windows 10.

**Comment by nowrep** [comment]
Not sure what might be wrong, works fine on Linux.

@ravas Can you try with latest commit (572b39cd2a), it's the only thing that seemed wrong at the first look.

**Comment by r-a-v-a-s** [comment]
Sigh... apparently the MinGW version doesn't have the WebEngine, and the msvc version requires downloading visual studio, which I'm not going to do.
I'm going to replace Windows with PCBSD & Lumina soon.

**Comment by RaSla** [comment]
![qup201_dl_bug](https://cloud.githubusercontent.com/assets/7755989/16707901/fe9120ec-45f8-11e6-86e4-d0ad5b6912cc.png)
Qupzilla 2.0.1, Windows 10 x64 - bug still present

**Comment by smarquespt** [comment]
>>This only happens on Windows 10.

Sorry to disagree but it also happens in Windows 7.
