### ISSUE TITLE
Disable smooth page scrolling entirely

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1907]
It seems that GTK+ 3 and Qt 5 are being adapted more to what is known as "touch screens" and so scrolling using "touch pads" is always smooth, with both of these toolkits, even in cases where smooth scrolling is not enabled.

Once smooth scrolling with typical mouse is disabled, disable any other smooth scrolling (e.g. touch pad, touch screen etc.).

**Comment by nowrep** [comment]
Touchpads are usually high-resolution - that is they scroll by pixels and not by jumps as normal wheel on mouse. So there is no way to disable that.

**Comment by GreenLunar** [comment]
GTK+ 2 and Qt 4 do not smooth scroll on touch pad input, once smooth scroll is disabled, and sometimes even by default.

**Comment by nowrep** [comment]
If disabling animated scrolling in settings doesn't work for you, then I'm sorry. There is no way to disable the behavior you are describing in Qt.

**Comment by GreenLunar** [comment]
QupZilla for Qt4 absolutely has no smooth page scrolling, even when scrolling using a touch pad, once smooth scrolling is disabled.

**Comment by GreenLunar** [comment]
I guess there is a way to customize scrolling.  See Playlist of SMPlayer.  If not for webpages then at least for Library dialog.

**Comment by nowrep** [comment]
What should I see in SMPlayer's playlist?

**Comment by GreenLunar** [comment]
When scrolling, next entries are being entirely displayed, not in between.  See attached animations.

Scrolling with UI scroll bar
![smplayer_playlist_scrollbar](https://cloud.githubusercontent.com/assets/2053884/14496203/1be1a65a-019b-11e6-8706-985b7fee0139.gif)

Scrolling with a laptop touch pad
![smplayer_playlist_touchpad](https://cloud.githubusercontent.com/assets/2053884/14496218/25ab0852-019b-11e6-853c-314fcbade4ec.gif)

I figured this would be appropriate for GreaseMonkey, Library and also for webpages.

Actually, the Fonts drop-down menu, and Certificates and Cookies dialogs are not scrolled smoothly, and are reminiscing the above scrolling style of SMPlayer playlist.

**Comment by nowrep** [comment]
This is only possible in item views, it is `QAbstractItemView::ScrollPerItem` option.
But personally, I don't like it and in QupZilla most of the views are `QAbstractItemView::ScrollPerPixel`

**Comment by GreenLunar** [comment]
I would love to be able to use `QAbstractItemView::ScrollPerItem` for anything in QupZilla by disabling smooth scrolling.
