### ISSUE TITLE
No update to 2.0.0 on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by rvwsak** [QupZilla/qupzilla#1908]
I currently use Qupzilla version 1.8.9. When opening the browser I get a notification saying that a new version is available. So I start the terminal and write:

sudo add-apt-repository ppa:nowrep/qupzilla
sudo apt-get update
sudo apt-get install qupzilla

But after the install command I only get the message "qupzilla is already the newest version.

Any ideas?

**Comment by cranes-bill** [comment]
quote of @nowrep:
> QupZilla is now available in repositories of all major distributions. From now on, I will stop providing Linux builds. This also means that my Ubuntu PPA will not get any new releases. I will still provide Windows builds.

[source](http://blog.qupzilla.com/)

**Comment by rvwsak** [comment]
I see, thanks for the quick reply. It's a pity. I really liked Qupzilla.

**Comment by nowrep** [comment]
Qt 5.6 is not in any Ubuntu version yet. So even if I wanted to build the package, I couldn't.
