### ISSUE TITLE
netflix won't play videos

### ISSUE THREAD

**Issue by r-a-v-a-s** [QupZilla/qupzilla#1917]
Version 2.0.0

> Netflix Video Player Unavailable
> 
> We're having trouble playing Netflix on your browser. Please make sure you are on an official version of Chrome.

https://help.netflix.com/en/node/22952

For those that don't know:

> QtWebEngine integrates chromium's fast moving web capabilities into Qt.
> Our goal is to bring the latest and best implementation of the web platform into the universe of Qt. It is not just a port of the core HTML/CSS rendering engine, it is the entire Chromium platform. 

I found: http://unix.stackexchange.com/questions/172364/netflix-works-on-chrome-but-not-chromium

If we would need to add "Widevine Content Decryption Module"
I guess that means we would need to modify Qt in order to modify chromium, 
which would introduce new licensing issues.
I haven't researched it that much...

**Comment by The-Compiler** [comment]
QtWebEngine [should detect Widevine soon](https://bugreports.qt.io/browse/QTBUG-50132) in some future version

**Comment by bvbfan** [comment]
Is this works now? web.spotify.com now uses drm to play songs, so widevine from Chrome can be used or not?

**Comment by nowrep** [comment]
Yes, it should work with latest QtWebEngine (or at least it did work at some time).

**Comment by sjukfan** [comment]
Yes it's working. What is extra nice is that it detects it even if you like me have ripped libwidevinecdmadapter.so and libwidevinecdm.so from the Chrome installer and copied them to /usr/lib/chromium 

bvbfan: yes it works with Spotify.
