### ISSUE TITLE
Is webengine inherently memory hungry?

### ISSUE THREAD

**Issue by AcarBurak** [QupZilla/qupzilla#1922]
With half a dozen tabs loaded QupZilla's memory usage can rise to 1.2GB (in a pure Qt Arch Fluxbox system). I recall Chromium too was memory hungry in my little experience of that browser. So, Is that normal for webengine?

Otherwise it works beautifully. Thank you.

**Comment by nowrep** [comment]
Yes, it uses Chromium so unfortunately have the same "feature".

**Comment by AcarBurak** [comment]
All right, no problem; a nice "feature", making one feel powerful!
