### ISSUE TITLE
[RTL] Bookmarks bar buttons

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1923]
Bookmarks bar buttons are reversed.
Icons should be at right of a button, text should be at left of a button, so it is when bookmarks are displayed via QupZilla menus.

**Comment by innermous** [comment]
Could you provide some more information?

**Comment by GreenLunar** [comment]
Order or each bookmark button on bookmarks bar is this:

[icon] [text], [icon] [text], [icon] [text]

In RTL (`qupzilla -reverse`) it should be like this:

[text] [icon], [text] [icon], [text] [icon]

Perhaps @srazi could explain this more eloquently than I do.
