### ISSUE TITLE
speed dial information

### ISSUE THREAD

**Issue by r-a-v-a-s** [QupZilla/qupzilla#1925]
The default speed dial entries all have "unable to load" as the title.
Newly created entries will have the same issue, and also will not show an image.

v2.0.0 & OS X

**Comment by cranes-bill** [comment]
Can you connect to the network, when that's occurs?

**Comment by r-a-v-a-s** [comment]
Yes. Clicking on one will take me to the associated web page.

**Comment by cranes-bill** [comment]
I remembered that initially i had a similar behavior, but i was not able to connect to the network until i changed the proxy configuration...

**Comment by nowrep** [comment]
Works fine on Linux.
It uses QQuickWidget with `Qt::WA_DontShowOnScreen` widget attribute (tools/pagethumbnailer.cpp), so maybe not working on OS X?

**Comment by r-a-v-a-s** [comment]
I setup my pc today (Windows 7). I downloaded the 2.0.0 Windows installer.

At first it will show the titles, but not the images... so the reverse of on OS X.
Then if I double-click in the tab area to create a new tab, 
it will show 'unable to load' as the title and still no image.
This behavior persists, and can be reproduced by creating a new profile.

**Comment by nowrep** [comment]
It's because it is missing QML imports. On Windows it should go to `qml` directory.

**Comment by Martii** [comment]
Just a note... this is happening in latest bult HEAD with OS X 10.11.14

**Comment by Martii** [comment]
@nowrep
Another note OS X 10.11.5 with Qt 5.7.0 now no longer shows speed dial entries at all with a dirty profile *(migrated)*, and is far upper left in clean *(new)* profile. This is the HEAD for the 2.0.1 release and not the current development HEAD of 198bfae88fe590d8d08f0ee18ccc34bbe5be9493

Will try the current dev HEAD in a bit to see if it's visible/working and report back after this sentence.

See also:
* https://github.com/Martii/qupzilla/releases/tag/v2.0.1%2B521d058 *(additional dmg uploaded)*

**Comment by Martii** [comment]
With https://github.com/QupZilla/qupzilla/commit/f0e2b938ba9fa6b6881c805c0bb32b10c55ee7fc it's back to the original issue of:

> ... and also will not show an image.

> v2.0.0 & OS X

![speeddial f0e2b93](https://cloud.githubusercontent.com/assets/114709/16391581/0881a04c-3c65-11e6-814b-0c79edcd08df.png "2.0.99.f0e2b93)

Misc notes:
* Sometimes the spinner isn't present but the label text is.
* Clicking on one does take you to that referenced url
