### ISSUE TITLE
Cannot right-click links when zoom is higher than 100% (Qupzilla 2.0)

### ISSUE THREAD

**Issue by slicer69** [QupZilla/qupzilla#1927]
When running Qupzilla 2.0 with a zoom setting higher than 100% I am unable to right-click on links to bring up th link context menu. (The menu which allows us to copy the link to the clipboard or open the link in a new tab.) I am also unable to CTRL-Click on links to open them in a new tab when zoomed in more than 100%.

Steps to reproduce:
1. Visit any page with text hyper-links.
2. Zoom in on the page to more than 100%
3. Attempt to right-click on link. The link's context menu does not appear.
4. Restore zoom level back to 100%.
5. Can now right-click on link to raise context menu.

Note: When using CTRL-click to open a link in a new tab, if there are multiple links on a page, sometimes the wrong link opens. For example, If I have three links in a list:

Link-A
Link-B
Link-C

then CTRL-clicking on Link-A will open Link-C in a new tab when the zoom level is greater than 100%.

Qupzilla version: 2.0
Platform: Debian Linux 8.0 64-bit

**Comment by nowrep** [comment]
Can you show me example page for the Ctrl+click link issue?
