### ISSUE TITLE
[Extensions] Python API

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1930]
Add support for writing extensions in Python, just like Liferea (written in C) has.
http://lzone.de/How+to+write+GObject+Introspection+based+Plugins
https://github.com/lwindolf/liferea#creating-plugins

**Comment by nowrep** [comment]
If anything, I'll think about QML/JavaScript.

**Comment by GreenLunar** [comment]
QML sounds good.

What about PyQt?

**Comment by GreenLunar** [comment]
Would it be possible to utilize Python based software such as Weboob and YouTube-DL in QupZilla extensions without a Python API?
