### ISSUE TITLE
overlapping text in the downloads window

### ISSUE THREAD

**Issue by r-a-v-a-s** [QupZilla/qupzilla#1931]
With only a single download in the window:

![overlapping_downloads](https://cloud.githubusercontent.com/assets/12013378/14360191/15e12820-fcaa-11e5-8604-e74bdf5b7b85.png)

The download has finished; therefore, "...few seconds remaining" also seems like a bug.

Windows7 & v2.0.0

**Comment by nowrep** [comment]
Duplicate of #1906

**Comment by Martii** [comment]
@nowrep 
Does the commit hash show up in what you are distributing with the "About QupZilla" menu item? or is that just a build thing here?

**Comment by nowrep** [comment]
Only when you build from git (that is, if you have `.git` directory).

**Comment by Martii** [comment]
Thanks.
