### ISSUE TITLE
still the same problem even with Qupzilla version 2 

### ISSUE THREAD

**Issue by Gamezertruth** [QupZilla/qupzilla#1933]
as I reported before right here https://github.com/QupZilla/qupzilla/issues/1773 it still happen with  Qupzilla version 2 and you didn’t fix this bug ? plus note : I have done so many formatted of my laptop and that’s wasn't a problem on my end !

**Comment by nowrep** [comment]
And why do you open new bug?

**Comment by Gamezertruth** [comment]
because you don’t reply back ?
