### ISSUE TITLE
Qupzilla Does Not Work On Windows XP

### ISSUE THREAD

**Issue by FixitmanArizona** [QupZilla/qupzilla#1934]
Update: AFTER uninstalling and re-installing 1.89 I found David's post:
 Note for Windows XP: You may see warning popup messages on startup, it can be fixed by removing D3Dcompiler_47.dll in directory where you installed QupZilla. 
Don't know if this resolves the problem, but also was getting the same notice about profiles on the 1.89 version now, did NOT remove that file, however, I restored the old settings in the profile folder and that fixed it: 
....restore the old version profile from .db:   Open the profile folder from your file explorer... delete the current browsedata.db and rename the .old or backup to browsedata.db, also you can do the same with session data etc. (anywhere you see a backup or old file and a current one.)
I imagine anyone actually updating to 2.0 will need to remove that D3D compiler however, and start anew with a profile compatible with the new version.

>>>>>>Hi, after updating to Qupzilla 2.0 on Windows XP the program opens after saying my profile is not compatable with the new version, and backed it up as a .db file. Browser opens and I have to configure it to show toolbar, tabs not on top (apparently it's configured like Chrome out of the box but at least can be changed!) Also can configure other items. 
However, even the start page flickers and does nothing. Cannot input to search, nor type in address bar for a new web page. The browsing area just flickers, that's it.
Would have been nice to have known it wouldn't work (Probably just on XP?) before updating.
XP svc pack 3, Zonealarm free 13.3 (newer versions do not work properly on XP) Avast Free 11.1 (Works on XP) 
I notice this is now a Chromium based browser, which defeats the whole point of it being pure QT?> I have Iron installed if I wanted a Chrome-type browser.
With a problem this bad, I'm not even going to expect a fix, will uninstall and go back to a previous version that works, and try to remember never to update it. (This is one reason I HATE UPDATES, such as updating to a new OS like Windows 7 or whatever they're selling now, nothing works.)
Thanks.

**Comment by nowrep** [comment]
Can you please re-download the installer from homepage and try again? I uploaded new builds yesterday that should fix your issue.

**Comment by FixitmanArizona** [comment]
Actually that's the version I tried. Did not want to mess with it any more
so using the older version, which works fine. I'm sure it would be OK with
deleting that one file from the folder, however, don't want to lose all the
profile info and re-do all that again. Thanks anyway!

**Comment by nowrep** [comment]
Works fine for me on Windows XP SP3. I changed the QtWebEngineProcess.exe to make it run on XP.
If that doesn't work for you, I have no idea what else to do.

Windows XP is not officially suported by QtWebEngine (https://doc-snapshots.qt.io/qt5-5.7/qtwebengine-platform-notes.html). so I am closing the issue.

**Comment by Martii** [comment]
@nowrep 

> https://doc-snapshots.qt.io/qt5-5.7/qtwebengine-platform-notes.html

Please be careful with "snapshot" url links to them... at least once mine went away to a different url and I had to go find/fix it ... I think the final resting place is http://doc.qt.io/qt-5/supported-platforms.html

**Comment by nowrep** [comment]
This is correct link https://doc.qt.io/qt-5/qtwebengine-platform-notes.html

**Comment by Martii** [comment]
That link didn't work initially as that is one that I tried... this is the issue over there to watch out for when there is "snapshot" in the link. :) Not sure what qt's logic is over there.

**Comment by FixitmanArizona** [comment]
That computer is GONE now, due to hardware breaking,  built a new one, and using Linux. NO way I was going to deal with the mess that's Windows Vista/7/8./10 . So sorry for people still on XP that is unsupported by most software now, unless they can still get  old versions of programs designed for XP era, that work properly. 
Never expected a fix, but was glad to find an old version that worked!
