### ISSUE TITLE
Qupzilla 2 has problems when there is a high Windows DPI setting

### ISSUE THREAD

**Issue by SJ-Diamond** [QupZilla/qupzilla#1935]
Issue is that UI gets rather big, same as fonts.

QupZilla-Version: 2.0.0
QtWebEngine version 5.6.0

It does not recognize the Windows checkbox for "deactivating scaling when high DPI setting".

**Comment by olantrust** [comment]
How does a user turn HighDPI scaling back on?
There's no preference for that.

**Comment by nowrep** [comment]
Setting `QT_AUTO_SCREEN_SCALE_FACTOR=1` environment variable should do the trick on Windows.

`QT_SCALE_FACTOR=2` should work on Linux (2 - scale 2x)

**Comment by wkg** [comment]
in linux "QT_SCALE_FACTOR=1.25" **bad**! 
how i can use hidpi?
![screen_2017-01-23_11-13-51](https://cloud.githubusercontent.com/assets/1515379/22196803/11380988-e160-11e6-9de4-ef397e11d565.png)

**Comment by nowrep** [comment]
Non-integer scaling is not supported by Qt.

**Comment by wkg** [comment]
ok... why QtWebEngine don't support system DPI setting(plasma) ?
and don't save zoom... i set zoom 200%, after restart qupzilla pages set 100%. after ctrl -/+ and ctrl 0 - sets 200%...
