### ISSUE TITLE
Flash player issue "bug" in Qupzilla 2 

### ISSUE THREAD

**Issue by Gamezertruth** [QupZilla/qupzilla#1936]
will , having a new problem with "Qupzilla 2" where the flash player won’t displayed correctly on a flash gaming website like this http://www.gamezer.com/billiards/ ! it’s a bug ?

![cpwz_007](https://cloud.githubusercontent.com/assets/15893368/14409040/2de836f4-ff14-11e5-9c1f-9e8a99d5a9d7.png)

**Comment by nowrep** [comment]
For Windows, Flash player must be installed in one of these locations:

```
C:\Windows\SysWOW64\Macromed\Flash\pepflashplayer*.dll
C:\Windows\System32\Macromed\Flash\pepflashplayer*.dll
```

**Comment by Gamezertruth** [comment]
can you to give my a Flash download link for Qupzilla ?

**Comment by nowrep** [comment]
You probably need to extract it from Chrome.

**Comment by Gamezertruth** [comment]
how to do this ? any help ?

**Comment by Martii** [comment]
> how to do this ?

1. Install Chrome.
2. Open up a cmd.exe *(Command prompt)*
3. Type `cd \` to get to your C: root
4. Type `dir pepflash* /s` to search for it... this will tell you the location of the dll.
5. Then follow the instructions given to [up here](https://github.com/QupZilla/qupzilla/issues/1936#issuecomment-207948388).

Please note this is probably beyond the scope of the issue as you should know how to open a command line interface *(command prompt)*, should know how to search your computer for files, should know how to install an application, etc.

Thanks.

**Comment by Gamezertruth** [comment]
Well, that also did not help! I've previously installed the 3 types of Flash Player (and I have just extract it from Chrome and copied the dll file on Qupzilla folder)! As you can see in the screenshot, Flash Player is working badly with your browser >(version 20 only)<! But with the other browsers it works great! So there's nothing I can do except get you fixed.

**Comment by Martii** [comment]
Have you tried [this](http://www.answers.com/Q/How_can_you_get_Pepper_Flash_to_load_onto_Chromium_browser_for_Windows_7)?

**Comment by Gamezertruth** [comment]
no ! I haven’t yet tried offline install of flash player and never use it before ! moreover you can check this website on my reply # 1 and then you’ll got it the problem !

I’ll check your link for reading ....

**Comment by Martii** [comment]
@nowrep 
This is the second instance where I've noticed belligerent behavior from @Gamezertruth ... I would suggest banning him. He's going to be banned in our networks as well.

**Comment by nowrep** [comment]
I can't ban users and have no intention to do so without serious reason.
Thanks to @Martii for writing instructions to get the Flash player working on Windows. It would be a good idea to post a clear instructions somewhere on Wiki.

@Gamezertruth You don't need to format your laptop, you just need to follow instructions and you'll get Flash working.

**Comment by Martii** [comment]
@nowrep
> I can't ban users and have no intention to do so without serious reason.

Okay... just thought I'd make a suggestion. The overkilled exclamations and indications that I didn't read his first post is enough for us. I won't be attempting to assist him at all from now on. Thanks.

**Comment by Gamezertruth** [comment]
what’s wrong here ? ban my for what ? I don’t make anything wrong ? why all this Martii ? all I said that I will give a try to make flash player working again !
nowrep @ I will give it that a try and report back !
