### ISSUE TITLE
Transparent Navigation Buttons (QupZilla 1.8.9, Qt 5.6.0, Linux)

### ISSUE THREAD

**Issue by clvgt12** [QupZilla/qupzilla#1941]
After building Qupzilla 1.8.9 against the Qt 5.6.0 libraries, I observed the navigation buttons (home, back, forward, reload, menu) are transparent.   The buttons themselves are still physically present and bound with their respective widgets and functions e.g. left click on menu button still can pull down the menu widget which remains visible, click on home button loads the configured home page, etc...

![screenshot-configuration information - qupzilla](https://cloud.githubusercontent.com/assets/15834506/14495419/5a08679a-015d-11e6-9be0-c18a1d4f9190.png)

**Comment by nowrep** [comment]
Themes must be in "Themes" path as seen on the screenshot.

**Comment by nowrep** [comment]
Either `make install` or build with `NO_SYSTEM_DATAPATH` (see BUILDING)

**Comment by clvgt12** [comment]
I did execute a 'make install' with 'sudo'.   here is a 'ls' of the themes directory on this system:

<pre>
chris@martini:~/Google_Drive$ cd /usr/share/qupzilla/themes
chris@martini:/usr/share/qupzilla/themes$ ls
breathe  chrome  default  linux  mac  windows
chris@martini:/usr/share/qupzilla/themes$ cd linux
chris@martini:/usr/share/qupzilla/themes/linux$ ls
images  main.css  rtl.css  theme.info  theme.png
chris@martini:/usr/share/qupzilla/themes/linux$ cd images
chris@martini:/usr/share/qupzilla/themes/linux/images$ ls
flash.png       navigation-dropdown.png  tab-right-arrow.png
flashstart.png  rss.png                  tabs-list-button.png
goto.png        semi-transp.png          transp.png
key.png         star-a.png               websearch-bg.png
library-bg.png  star.png
menu.png        tab-left-arrow.png
chris@martini:/usr/share/qupzilla/themes/linux/images$ 
chris@martini:/usr/share/qupzilla/themes/linux/images$ ls -l
total 64
-rw-r--r--. 1 root root 3331 Apr 12 16:29 flash.png
-rw-r--r--. 1 root root 1939 Apr 12 16:29 flashstart.png
-rw-r--r--. 1 root root  601 Apr 12 16:29 goto.png
-rw-r--r--. 1 root root  655 Apr 12 16:29 key.png
-rw-r--r--. 1 root root  435 Apr 12 16:29 library-bg.png
-rw-r--r--. 1 root root  244 Apr 12 16:29 menu.png
-rw-r--r--. 1 root root  149 Apr 12 16:29 navigation-dropdown.png
-rw-r--r--. 1 root root  698 Apr 12 16:29 rss.png
-rw-r--r--. 1 root root  110 Apr 12 16:29 semi-transp.png
-rw-r--r--. 1 root root  753 Apr 12 16:29 star-a.png
-rw-r--r--. 1 root root  411 Apr 12 16:29 star.png
-rw-r--r--. 1 root root  127 Apr 12 16:29 tab-left-arrow.png
-rw-r--r--. 1 root root  125 Apr 12 16:29 tab-right-arrow.png
-rw-r--r--. 1 root root  260 Apr 12 16:29 tabs-list-button.png
-rw-r--r--. 1 root root   95 Apr 12 16:29 transp.png
-rw-r--r--. 1 root root  131 Apr 12 16:29 websearch-bg.png
chris@martini:/usr/share/qupzilla/themes/linux/images$ 
</pre>

**Comment by cranes-bill** [comment]
On the screen shot that you posted, QupZilla has a prefix `/usr/local`, but the files where you listed are with prefix `/usr`, so you probably did something wrong or just have other QupZilla version installed.

**Comment by clvgt12** [comment]
Oh!  Ok, will rebuild.
