### ISSUE TITLE
[Print to PDF] Set creator to QupZilla

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1942]
See https://github.com/QupZilla/qupzilla/issues/904#issuecomment-204350692

**Comment by nowrep** [comment]
Please don't open new issue, this is clearly bug in Qt (as the same code works fine in Qt 4).

**Comment by GreenLunar** [comment]
Then at least reopen the old issue.

Please look into commit https://github.com/OtterBrowser/otter-browser/commit/86dfc7d22d147ab75565cd1aa3582869f8b8b811 to see whether this would work for QupZilla too.

**Comment by nowrep** [comment]
It's the same code though.

**Comment by GreenLunar** [comment]
Maybe it does not work.  I did not test it yet.

@Emdek, did you confirm that Otter Browser sets creator field to Otter Browser VERSION?
