### ISSUE TITLE
[FEATURE REQUEST] Native/Better Open File dialog

### ISSUE THREAD

**Issue by guillefar** [QupZilla/qupzilla#1946]
I'm using Qupzilla in Ubuntu with a the latest Cinnamon as desktop, and Qupzilla doesn't show a native Open Menu dialog. Despite preferences, there is very handy functionality in the native dialog, like  bookmarks (I wasn't able to drag a folder to create one), and show the last files used  that make a lot less efficient. 
Now, since Cinnamon is based on Gnome libraries, such compatibility might difficult or not possible to achieve for Qupzilla. 
What I do think the dialog's menus need to add asap, is a way to see previews/thumbnails for images. For many people to upload images (for emails, facebook, CV, in my case, work screenshots, etc), is one of the most performed activities in the browser,   and to not be able to see a preview of the image make it a lot troublesome to use.
Not sure if that is in the roadmap or not, I couldn't see any info related to it.

**Comment by nowrep** [comment]
You need to use appropriate platform plugin for your desktop environment. In your case it would be probably `gtk2`.

Try to run `qupzilla -platform gtk2`

**Comment by guillefar** [comment]
That platform doesn't exist:

`Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.`

The only one that works ok is the default, xcb, so yeah, same dialog.

**Comment by nowrep** [comment]
Sorry, it should be `qupzilla -platformtheme gtk2`

**Comment by guillefar** [comment]
That option seems to not work. I tried gtk2, gtk3  and a random name, and no change and no error displayed.

**Comment by cranes-bill** [comment]
`-platformtheme gtk2` works for me!

**Comment by guillefar** [comment]
No, for the record, I'm using the version from this PPA: https://launchpad.net/~nowrep/+archive/ubuntu/qupzilla, not sure if that have something to do with it

**Comment by nowrep** [comment]
Are you using Qt 5?

**Comment by guillefar** [comment]
The library? Not sure, how to find it out?

**Comment by nowrep** [comment]
Help -> Config info

**Comment by guillefar** [comment]
Information about version:
Application version1.8.9
Qt version 5.4.2
WebKit version 538.1
Platform Linux

**Comment by nowrep** [comment]
That's interesting, it should be installed by default...

Do you have `/usr/lib/qt/plugins/platformthemes/libqgtk2.so`? (adjust accordingly for your distro libdir)

**Comment by guillefar** [comment]
Thanks! No, it was not installed. The file it is actually in the package:  libqt5libqgtk2. 
I installed it, and now with that option I have an almost native dialog, the only thing is that is not showing a preview of the images as the native does, but still is a huge improvement. 
Really appreciate it.
