### ISSUE TITLE
Crash on invalid protocol

### ISSUE THREAD

**Issue by abucodonosor** [QupZilla/qupzilla#1951]
Qupzilla ver 2.0.0
qt5-* 5.6.0

Open qupzilla and type ftp::/ or http::/ , enter .. , watch the crash.

in console I see :

/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
[0419/000322:FATAL:navigation_controller_impl.cc(927)] Check failed: active_entry->site_instance() == rfh->GetSiteInstance().

**Comment by tristan-k** [comment]
I'm having a similar issue. Except qupzilla doesnt crash, rather it spits out a `ERR_SSL_PROTOCOL_ERROR` error for certain sites (like google).

**Comment by nowrep** [comment]
@tristan-k That's issue with libnss and QtWebEngine. Should be fixed by your distribution or in next Qt release.
