### ISSUE TITLE
QtWebEngineProcess configuration

### ISSUE THREAD

**Issue by bvbfan** [QupZilla/qupzilla#1952]
Hi, i want to start QtWebEngineProcess with --enable-accelerated-video-decode and --enable-gpu-compositing. Now the process is started with these 2 flags disabled. QupZilla 2.0 does not match tiny browser any more, Google Blink is huge, fat and has only disadvantages over QtWebkit.

**Comment by nowrep** [comment]
You can now run `qupzilla --enable-accelerated-video-decode --enable-gpu-compositing`

**Comment by bvbfan** [comment]
Ty, David.

**Comment by cranes-bill** [comment]
Just `--help` option is missing now.

**Comment by bvbfan** [comment]
With Qt 5.6 this works perfect. I can't get it work with Qt 5.7. Qupzilla --ignore-gpu-blacklist
