### ISSUE TITLE
If youtube video link is opened from new tab where the source is not from youtube(ex facebook/google) and tab is closed while video is still playing the audio doesnt stop

### ISSUE THREAD

**Issue by bigbadbabybear** [QupZilla/qupzilla#1953]
### Description
If the video link came from google/facebook and is opened to a new tab, when you close it while the video is playing the audio won't stop

### Procedure
1 find link of youtube video from google/facebook **this should open a new tab** (ex. [`https://www.youtube.com/watch?v=hS5CfP8n_js`](https://www.youtube.com/watch?v=hS5CfP8n_js))
2 _[suggest you scroll to last 10secs of video]_ close tab by using Ctrl+W or clicking X on the tab
3 listen to audio still playing even if the tab is closed

### System
QupZilla 2.0.0 - Windows 7 - Disabled TabManager

**Comment by cranes-bill** [comment]
It has been fixed #1949

**Comment by bigbadbabybear** [comment]
thanks for the link, didn't think it was a tab problem
i should really start using middle click rather than ctrl+click
