### ISSUE TITLE
When "Filter 3rd pary cookies" is enabled, cookies storage will be completly disabled

### ISSUE THREAD

**Issue by E-Berry** [QupZilla/qupzilla#1954]
**General**
Windows 10 64 bit
Qupzilla 2.0
Fresh profile

**What version of the application are you using? Which operating system?**
Platform used is not windows 8

Information about version
Application version 2.0.0
Qt Version              5.6.0
Platform                 Windows 8

**What steps will reproduce the problem?**
1. Enable Filter 3rd pary cookies
2.A. Try to log in to github 
2.B Or try to enter kissmanga.com
3.A. Github will display this message "Cookies must be enabled to use GitHub." 
3.B. Kissmanga.com will load infinetly
4.Check cookie manager. No cookies will be stored

**What is the expected behaviour?**
1.A. Github will allow login
1.B. Kissmanga will finish loading
2. github and kissmanga cookies will be stored

This problem does not happen in Qupzilla 1.8.9

**Comment by nowrep** [comment]
Right now on 2.0 the cookies filtering options don't work at all, so I doubt it has any effect at all.
