### ISSUE TITLE
Provide a tutorial to easily install QtWebEngine on Debian based distributions for QupZilla 2.x.

### ISSUE THREAD

**Issue by sebma** [QupZilla/qupzilla#1956]
Hi,

Is QtWebEngine choice is good idea ?

It seems the three most popular linux distributions (according to distrowatch and tecmint) which are Debian based will not support QtWebEngine as Debian will not support it :
[QtWebEngine Poses Problems For Debian, Distribution Vendors](http://www.phoronix.com/scan.php?page=news_item&px=QtWebEngine-Mess-Debian)
and [libqt5webengine does not exist on Debian](https://packages.debian.org/search?keywords=libqt5webengine)

I am using Ubuntu, therefore shall I abandon QupZilla in favor of the unstable Midori ( :-() 

Will you plan to keep on building qupzilla in the nowrep launchpad PPA ?

Or maybe you can provide a tutorial to easily install QtWebEngine on Debian based distributions or even better a QtWebEngine PPA ?

**Comment by abucodonosor** [comment]
Uhm ? Come on.. You know with qt 5.6.0 QtWebkit gone ( officially ) and is replaced by QtWebEngine..

Go and read some docs on how to build packages on Ubuntu or Debian or open an feature request about in their BTS..

**Comment by sebma** [comment]
BTS ?

**Comment by JHooverman** [comment]
BTS = Bug Tracking System

**Comment by JHooverman** [comment]
You might find some help about how to build qt from sources [here](https://github.com/QupZilla/qupzilla/wiki/Knowledgebase).

**Comment by sebma** [comment]
Thank you for the doc.

However, it looks out of date, because QupZilla 2.0.0 sources have been released and QupZilla now depends on QtWebEngine

**Comment by sebma** [comment]
If a Debian Qt maintainer says: ["It's quite a very hard piece of software to package."](http://www.phoronix.com/scan.php?page=news_item&px=QtWebEngine-Mess-Debian)

I don't know how I'm supposed to do better than him.

Ubuntu is designed to be easy to use.

Installing an application that's in the repositories (ubuntu's or launchpad's PPA) is easier than on Windows.

**Comment by sebma** [comment]
Did you manage to build qt5-webengine and qupzilla-2 on Ubuntu ?

If you did, can you please update QupZilla's Knowledgebase ?

**Comment by abucodonosor** [comment]
> If a Debian Qt maintainer says: "It's quite a very hard piece of software to package."

This is NOT about is hard to package but is about Is hard to package "Debian's" *way* .. 

Eg: they do not like QtWebEngine embeds some 3party libs , the rule say : use system libs .. etc
So is all about Distro rules...

QtWebEngine itself is not hard to build ..

**Comment by abucodonosor** [comment]
https://wiki.qt.io/How_to_Try_QtWebEngine#Installing_dependencies_on_Ubuntu

How hard is that ?

**Comment by sebma** [comment]
The `git submodule update --init` takes some time.

As soon as I have finished that and the `make` command, I will answer your question.

**Comment by sebma** [comment]
Not that simple:

```
$ git submodule update --init
Submodule 'src/3rdparty' (git://code.qt.io/qt/qtwebengine-chromium.git) registered for path 'src/3rdparty'
Cloning into 'src/3rdparty'...
remote: Counting objects: 302534, done.
remote: Compressing objects: 100% (200119/200119), done.
remote: Total 302534 (delta 168702), reused 168908 (delta 97574)
Receiving objects: 100% (302534/302534), 601.54 MiB | 1.46 MiB/s, done.
Resolving deltas: 100% (168702/168702), done.
Checking connectivity... done.
Submodule path 'src/3rdparty': checked out '8252b18aa3efa52138e91f9756945afb142a1c8c'
$ qmake -r
WARNING: /home/sebastien/src/qtwebengine/qtwebengine.pro:1: Unable to find file for inclusion qt_build_config
WARNING: /home/sebastien/src/qtwebengine/qtwebengine.pro:2: Unable to find file for inclusion qt_parts
$ echo $?
0
$ make
g++ -m64 -Wl,-O1 -o qtwebengine     -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crt1.o: In function `_start':
/build/buildd/glibc-2.19/csu/../sysdeps/x86_64/start.S:118: undefined reference to `main'
collect2: error: ld returned 1 exit status
Makefile:102: recipe for target 'qtwebengine' failed
make: *** [qtwebengine] Error 1
$ echo $?
2
```

**Comment by abucodonosor** [comment]
You do not need the git part , there are stable tarballs released .. however you can build the code from git if you wish..

**Comment by sebma** [comment]
I see that the git part is not a piece of cake.

Trying the tarball version, shall I download that: http://download.qt.io/official_releases/qt/5.6/5.6.0/qt-opensource-linux-x64-5.6.0.run ?

**Comment by sebma** [comment]
Nobody told that /opt/Qt5.6.0/ would be 1GiB once installed.

I must be motivated to install QupZilla 2 dependencies :-)

But then if I run qmake in the qupzilla cloned git, it says :
`Project ERROR: QupZilla requires at least Qt 5.6!`

**Comment by abucodonosor** [comment]
http://download.qt.io/official_releases/qt/5.6/5.6.0/submodules/qtwebengine-opensource-src-5.6.0.tar.xz

also you may want to ask these guys for an qtwebengine deb / build scripts : 

https://launchpad.net/~ethereum/+archive/ubuntu/ethereum-qt

**Comment by sebma** [comment]
I'm starting to agree with the Debian guy.

Debian distribution is famous for it's stability, but with all these hacks such as a 3rd party application inside: qtwebengine-chromium (which is based on Google by the way).

Am I sure I want the NSA to watch everywhere I surf when I use the new QupZilla (once successfully build :)).

With the nowrep repo., it took me 5 minutes to install QupZilla because David Rosca had done the hard part, but now ...

**Comment by sebma** [comment]
And if I install `libqt5webengine5` from the PPA ppa:ethereum/ethereum-qt, you provided, I just noticed  some of my application have been uninstalled (because I'm starting to get tired because it's late in France):

audacious, calibre, checkbox-qt, hybrid-qt5, notepadqq, python-pyqt5.

This `libqt5webengine5` package is such a pain in the ... !

**Comment by sebma** [comment]
Some plasma widgets were also removed along the way.

I have to figure out which ones.

I couldn't reinstall my applications.

So I had to downgrade the package that were update by the `ethereum-qt` PPA.

I don't thing I'll ever do that again.

I'm using Ubuntu 14.10 by the way, because I don't like plasma5 desktop.

**Comment by sebma** [comment]
That to `/var/log/apt/history.log`, I figured out which packages were removed by `libqt5webengine5` installation.

I think I'll keep using QupZilla 1.8.9 from now on, unless someone proposes PPA to install QupZilla 2 that does not break my system.

I should have taken into account what the Debian Qt maintainer says, the guy knows what he's talking about.

I'm sorry to say this, but installing QupZilla is NOT a piece of cake.

**Comment by abucodonosor** [comment]
Really .. You run an out_of_date system , even maintained and called LTS, is OLD but want the latest software out there ? Heh ..

You agrre with the Debian Qt mainatiner ? Do you even know the Debian packaging rules ? 

I package software from back in 2000 and guess what ? I package qt5 too and even the whole KDE back from KDE'2' !

To compile Qt5-* from source is not hard when you know what you are doing .. I you for sure don't .. 

Anyway this has nothing to do with QupZilla.. I run QupZilla2 with QtWebEngine 5.6.0 and I have to say it is the best Qt browser out there.. Sure it has some bugs but nothing critical..

**Comment by sebma** [comment]
I never said anything about QupZilla bugs.

My Ubuntu is outdated but I managed to handle it so far.

For fresh packages, I use some PPA.

I shouldn't have used `ethereum-qt` PPA, that's all.

Maybe, I should have used the tarball you said.

You might be a hacker, but I'm not one (yet).

I'm just saying it take some hacks to integrate `libqt5webengine5` into Ubuntu 14.04.

You're right, QupZilla is not the pb., but `libqt5webengine5` integration in Ubuntu is.

**Comment by Martii** [comment]
> qtwebengine-chromium (which is based on Google Chrome by the way).

This is backwards... Chrome draws most of it's code from Chromium.

> ... that does not break my system.

My distro uses both 5.5.1 and 5.6.0 ... because a lot of the KDE deps are still the former. Perhaps that would be an avenue to explore when compiling.

> ... QtWebEngine embeds some 3party libs ...

Reminds me of Windows... that is something they should strive to change at Qt if it's capable. Code reuse should always be the norm and has been since *nix was conceived. Qt can be a bit bloated, and unnecessarily, for sure without a proper semver definition *(major, minor, build)*.

**Comment by The-Compiler** [comment]
> Reminds me of Windows... that is something they should strive to change at Qt if it's capable.

They [already did this to the extent it's possible](http://lists.qt-project.org/pipermail/qtwebengine/2015-August/000189.html).

**Comment by nowrep** [comment]
There is no "easy" in building QtWebEngine. You should instead request the Qt 5.6 packages from your distribution.

Or you can also try to use official builds by Qt: https://download.qt.io/official_releases/qt/5.6/5.6.0/

**Comment by sebma** [comment]
Hi, I see only Qt WebKit 5.6 in Debian experimental, I don't see Qt WebEngine.

What shall I do to request thoses packages Qt WebEngine 5.6 to Debian/Ubuntu ?

**Comment by ericcotelnu** [comment]
To slag off one of the major distros out there based upon the simple matter of distribution of software to users strikes me as being very much in the ad hominem category. Google has a tight grip on chromium,  less than chrome, hence it being able to be included in Debian's main. However, it strikes me as laziness on part of upstream to package third party source/libraries internally. It's much easier to just document just what are the software dependencies, and let the distros figure it out from there.

Otherwise we get things like this bug illustrate, and creates frustration.

My opinion and mine alone.

Thanks

**Comment by The-Compiler** [comment]
> To slag off one of the major distros out there based upon the simple matter of distribution of software to users strikes me as being very much in the ad hominem category.

Huh - last I checked a distribution was a thing, and not a human. I think criticizing a distribution for not distributing software many of its users want is quite a valid thing to do :wink:

But fortunately, there's some news - some people started working on QtWebEngine related packages, and at least qt5-webchannel (which is needed for QtWebEngine) got [accepted](http://osdir.com/ml/general/2016-09/msg01994.html) a few days ago.

> However, it strikes me as laziness on part of upstream to package third party source/libraries internally. It's much easier to just document just what are the software dependencies, and let the distros figure it out from there.

No, it's a technical need. QtWebEngine has various patches on top of Chromium to make it work the way it needs it to work, and unfortunately upstream Google doesn't seem very interested in the usage of Chromium outside of their own products. As I mentioned in a comment above, they already [unbundled](http://lists.qt-project.org/pipermail/qtwebengine/2015-August/000189.html) what was possible to unbundle.

**Comment by hosiet** [comment]
FYI, https://tracker.debian.org/pkg/qtwebengine-opensource-src

This should work on Debian 9+ and Ubuntu 17.04+.

**Comment by jamalroger** [comment]
i have the same problem how can slove this i am using qt 4.3. based on qt 5.4.0   with parrotsec
