### ISSUE TITLE
Bookmarks menu appears on different screen.

### ISSUE THREAD

**Issue by jamesqf** [QupZilla/qupzilla#1957]
I use a window manager (FVWM2) that supports multiple virtual screens.  When QupZilla is started, the first time I try to open the Bookmarks menu, it takes 3-4 seconds to appear.  If I switch to another screen during this time, the Bookmarks menu will appear on the new screen, not attached to the main QupZilla window, as I would expect it to be.

I'm using 1.8.9 on OpenSuSE 13.1.

**Comment by cranes-bill** [comment]
This is not a bug, exclude of lag of menu showing, which is known issue.
When the menu is triggered, it just appears on the active screen and that's the normal behaviour...

**Comment by jamesqf** [comment]
May I suggest that perhaps it ought not to be normal behavior, and that menus should be tied to the main window?

**Comment by cranes-bill** [comment]
Yep, if the developers may guess that you can switch the view-port until the menu be shown, which in fact should appears immediately when it has been triggering.
But maybe, you already saw that defined in the Qt source...

**Comment by jamesqf** [comment]
So this is a behavior of Qt in general, not something unique to QupZilla?  I'd never seen it before, but then I don't use many Qt-based programs (AFAIK, anyway), and none of them anywhere near as often.

**Comment by nowrep** [comment]
Your window manager is placing the window on current screen when being displayed, that's expected behavior.
What is not expected is that it takes few seconds to be shown. That is a problem in QupZilla.

**Comment by jamesqf** [comment]
That seems really strange, since I would expect menu windows and such to be owned by the application window, and hence not subject to the window manager at all.  But I know very little about Qt...

**Comment by nowrep** [comment]
It has nothing to do with Qt. When opening a window (any window), would you expect it to be opened on current desktop?

**Comment by jamesqf** [comment]
If it's a child window of an application, such as a menu window, I would expect it to be opened relative to the parent window.  Just as I would expect the window manager not to decorate it with border handles & controls. 

Indeed, take this one logical step further: isn't every item in a menu implemented as a child window of the menu window?  (At least it's so it basic X, IIRC, where each menu item might in turn be a container for icon & text windows.)  So why does the window manager not place & decorate each of those child windows separately?

**Comment by nowrep** [comment]
The same rules apply also for popup menus, moreover the popup menus grabs the mouse so no other application is receiving mouse events. In that case you should see why it opens on your current desktop.

That being said, the main issue is that it takes noticeable time for the menu to open. And that is duplicate issue for #1679
