### ISSUE TITLE
Issues in version 2.0

### ISSUE THREAD

**Issue by rajesh07590** [QupZilla/qupzilla#1959]
I have updated to version 2.0. I am facing some issues like following
1. why there is no inspect element option for developers usage.
2. while scrolling sites are blinking check yahoo mail or gmail and some other sites.
3. for canvas why background color appearing black by default

**Comment by Martii** [comment]
> why there is no inspect element option for developers usage.

See https://github.com/QupZilla/qupzilla/issues/1893#issuecomment-201825813 list item 1

> while scrolling sites are blinking check yahoo mail or gmail and some other sites.

Odd... not doing that here... platform, GPU driver info, and access method *(direct, RDC, VNC, etc)*?

> for canvas why background color appearing black by default

Example page? Not sure if [here](https://github.com/QupZilla/qupzilla/network) would apply but it seems to be working as expected with their canvas.

**Comment by nowrep** [comment]
2. 3. seems to be issues with QtWebEngine (GPU rendering) and likely your drivers.
