### ISSUE TITLE
Speed Dial issues in QupZilla 2.0

### ISSUE THREAD

**Issue by FelisManulus** [QupZilla/qupzilla#1966]
OS: Windows 7

1) QupZilla shows "Unable to load" in a speeddial, but the site name is correct.
There's no preview as well.
If I click on the speed dial, however, it gets me to the desired site.

2) If I open a new tab with speed dials, it loads annoyingly slow, approximately 1-2 seconds, as if it's refreshing all the site previews in the speeddials.

![qupzilla-issue](https://cloud.githubusercontent.com/assets/18376706/14984484/a27d362e-114b-11e6-9ef1-ee7641c24718.png)

**Comment by cranes-bill** [comment]
It was fixed #1925

**Comment by nowrep** [comment]
That's correct, I'll release new version once Qt 5.6.1 is out.
