### ISSUE TITLE
Download manager bar 

### ISSUE THREAD

**Issue by Tnebi** [QupZilla/qupzilla#1968]
Hi I'm using qupzilla portable on Windows 10 64bit with a resolution of 1600x1200 4:3 and I noticed that whenever I download something I can't read my download speed and size because it appears like this. 
![immagine](https://cloud.githubusercontent.com/assets/1217976/15053893/1afd0074-1305-11e6-8ed1-736a63fc4258.png)

Also OT: since I saw your message about the ubuntu ppa why don't you release a version based on the new Snappy system? It should be easier for you and users that love Qupzilla as me

**Comment by Martii** [comment]
#1906
