### ISSUE TITLE
Using kwget as download manager

### ISSUE THREAD

**Issue by Jzarecta** [QupZilla/qupzilla#1969]
How easy is to use kwget with Qupzilla, would be nice to use this instead of the very basic download manager from firefox/qupzilla.

**Comment by cranes-bill** [comment]
Even i did not understand why you closed the issue!?
Seems _**master**_ really has a bug on this option, or that option is incompatible with QtWebEngine, because i can't get it to work on  _**master**_ , but works fine on  _**v1.8**_.....
