### ISSUE TITLE
Cannot enter text in some web forms

### ISSUE THREAD

**Issue by OlafLostViking** [QupZilla/qupzilla#1970]
After updating to Qupzilla 2.0 I cannot enter text into the webforums at phoronix.com anymore (at the end of some discussion thread into the reply field). When using Konqueror with WebKit, it works. (Other forum software I have checked lately seems to work.)

**Comment by bvbfan** [comment]
Looks strange, i test it right now and it works. Distribution?

**Comment by OlafLostViking** [comment]
I am using a compiled version from the AUR (Archlinux). The first version I tried was c0026af63e and I just retried with 4a60521e7d.

**Comment by bvbfan** [comment]
So can you use this configuration -> https://github.com/KaOSx/main/tree/master/qtwebengine it has patches. All works stable as rock, no problems at all. For me, only disadvantage is high memory usage of chromium engine.

**Comment by OlafLostViking** [comment]
With QupZilla 2.1.2 and QtWebEngine 5.9.0 it is possible again to use the input field by default (ArchLinux repositories).
