### ISSUE TITLE
Some downloading issues in v2.0

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#1972]
Regarding to [this](https://github.com/QupZilla/qupzilla/issues/1969), when i set external downloading program, QupZilla still downloading with default one...

When i use _**Save Image As...**_, QupZilla downloads the image directly, without ask me for a place, probably because i have permanently set download directory in _DOWNLOAD MANAGER_, but that should not matter here...

_**Save Page As...**_ missing, when the page is some kind of text file. For example: [1](https://raw.githubusercontent.com/QupZilla/qupzilla/master/README.md), [2](https://raw.githubusercontent.com/QupZilla/qupzilla/master/AUTHORS), [3](https://raw.githubusercontent.com/QupZilla/qupzilla/9d8552aa4baea01f091b945d9826319937649bbc/src/lib/bookmarks/bookmarkstoolbarbutton.cpp), etc....

The all of above issues are working in v1.8 as expected.

**Comment by Thiudans** [comment]
I have the same issue with the download manager. When I tell Qupzilla to use kget as the download manager, it just uses the built in download manager instead, UNLESS I select "Ask every time for download location."
