### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by tristan-k** [QupZilla/qupzilla#1977]
I'm running Xubuntu 16.04 with qupzilla built from git. When browsing specific sites (for example google.com) qupzilla moans about a `ERR_SSL_PROTOCOL_ERROR` error and denies a connection.

Is this realted to https://github.com/QupZilla/qupzilla/issues/1951 ?

```
./bin/qupzilla --version
QupZilla 2.0.0 (5df95e1a9a)
```

```
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```

**Comment by tristan-k** [comment]
Ok, will have to close this. It's a duplicate of https://github.com/QupZilla/qupzilla/issues/1870/. It is really annoying because there's only `Qt WebEngine 5.6.0-1` available from `/opt/Qt/MaintenanceTool`. So what should I do?

**Comment by nowrep** [comment]
You need to wait for Qt 5.6.1 or build it yourself.
