### ISSUE TITLE
Qt bug: Special network configuration prevents network access from working

### ISSUE THREAD

**Issue by Leseratte10** [QupZilla/qupzilla#1978]
I habe encountered a strange bug in all QtWebKit-Browsers (not just in Qupzilla) but I didn't really find a place to report Qt-Webkit bugs themselves. 

My computer has a static route for another subnet, and has two IPs on one network interface to route that subnet: http://pastebin.com/sYZ7kzBL 

However, any Qt-browser can only access localhost (127.x.x.x) pages. Any other requests infinitely run into a timeout and not a single network request shows up in Wireshark. 

Any idea why that might be or what I can do to get this fixed?

**Comment by The-Compiler** [comment]
The Qt bugtracker is https://bugreports.qt.io/

I'd however recommend trying to reproduce it with something using QtNetwork but not using QtWebKit (like their [HTTP client example](http://doc.qt.io/qt-5/qtnetwork-http-example.html)) and then reporting it against QtNetwork, as QtWebKit is deprecated.

**Comment by Leseratte10** [comment]
Reproduced, this HTTP client example is also running into a timeout and not downloading anything. I'll report it there.

**Comment by nowrep** [comment]
Should be fixed in 2.0 as QtWebEngine does not use QtNetwork.
