### ISSUE TITLE
Modal auth window: infinite loop, can't close tab

### ISSUE THREAD

**Issue by ktrace** [QupZilla/qupzilla#1980]
Some pages, for example web management on swith, has infinite auth loop. Auth window is modal and you can't close tab. 

How to fix: limit number of retries, break auth loop on cancel, show "still need auth" message in tab.

QupZilla 2.0.0, Qt 5.6.0

**Comment by Martii** [comment]
Platform please?

**Comment by ugjka** [comment]
Uhhm yeah, try this https://goaccess.ugjka.net/ Warning: You'll be stuck on that page!!!

**Comment by ktrace** [comment]
Linux zzz 4.4.9-calculate #1

**Comment by Martii** [comment]
> https://goaccess.ugjka.net/

Heh... if you are quick enough on the the ESC key and the mouse tab close you can exit the loop but confirmed as well here.

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QupZilla/2.0.0 Chrome/45.0.2454.101 Safari/537.36` and 03193be22cefab8c832aa8992a2a75f3e4283a24

**Comment by ktrace** [comment]
Martii, it's not a game, it's a tool. User must use, not play "nowI'mquicktoclick". And limit - expected action. I think we see bug here.

**Comment by Martii** [comment]
@ktrace 
Didn't say it was a game... weird assumption on your part. Your initial issue creation was quite vague but I do appreciate you filling in a test platform finally.

**Comment by ktrace** [comment]
thank you for understanding :) sorry for poor english :)

**Comment by nowrep** [comment]
QtWebEngine bug - https://codereview.qt-project.org/#/c/161463/

**Comment by nowrep** [comment]
Well, not really bug - just undocumented change of behavior from QtWebKit.
