### ISSUE TITLE
QupZilla freeze, not taking particularly high amount of cpu or memory

### ISSUE THREAD

**Issue by mathieujobin** [QupZilla/qupzilla#1981]
i like QupZilla because it has a very low memory footprint.
I run Plasma 5 under ArchLinux and QupZilla adds a small 150MB of memory usage to my system.
Firefox 45+ usually takes 850MB and Chrome takes all that is available. 

I am looking forward using QupZilla full time but unfortunatelly it still has problems.

I found out on the QupZilla download page you have a version available to OS/2 users.
I did not know there was still OS/2 users. so I searched and found this site... 

http://www.os2world.com/

clicked on the livestream link leading to http://www.warpstock.eu/live-stream

and it freeze there. I had to kill the process 

cheers,

**Comment by cranes-bill** [comment]
Yep, i can confirm that just for _**V1.8**_. I also was faced this issue on some other live stream pages.

**Comment by tsujan** [comment]
I use Qupzilla v2.0.99 (with QtWebEngine) and have encountered many annoying freezes and hang-like behavior. In all such cases, the freeze disappears after several seconds or, sometimes, a few minutes.

**Comment by nowrep** [comment]
Would be great to take a backtrace to see if it hangs inside QupZilla or QtWebEngine.

**Comment by tsujan** [comment]
There's no crash but since I can reproduce this with some saved pages too, I'll see if more info could be gathered.

**Comment by tsujan** [comment]
Opening the [above-mentioned site](http://doc.qt.io/qt-5/qt.html) in two tabs creates a serious hang-like behavior. After CPU usage goes down, closing Qupzilla with those two tabs causes another temporary freeze that may last 20 sec.

**Comment by nowrep** [comment]
You can get backtrace even without crash, just press <kbd>Ctrl+C</kbd> in `gdb` when qupzilla hangs.
The backtrace you sent is a crash inside Qt, what version of Qt do you have?

**Comment by tsujan** [comment]
> what version of Qt do you have?

Qt-5.7

> You can get backtrace even without crash, just press Ctrl+C in gdb when qupzilla hangs.

All right. However, I think you could trace the problem more easily with the above link.

**Comment by cranes-bill** [comment]
@tsujan
> Opening the above-mentioned site in two tabs creates a serious hang-like behavior.............


I can't reproduce it with Qt 5.6. Perhaps one more Qt 5.7 bug, or just some adblock rule causing that....

**Comment by tsujan** [comment]
@cranes-bill 
You mean that you opened that link **in two tabs** and saw neither a temporary freeze nor a high CPU usage for several seconds **after** closing Qupzilla*? Not even if you do the same thing with http://doc.qt.io/qt-5/qwidget.html ?

**Comment by cranes-bill** [comment]
@tsujan, exact :ok_hand:

**Comment by tsujan** [comment]
@cranes-bill 
Strange! I started to use QtWebEngine-based Qupzilla with Qt-5.7. So, my report needs a confirmation by an Arch user.

**Comment by cranes-bill** [comment]
OK, i just added a note :+1:

**Comment by tsujan** [comment]
This may be a Qt issue, as @cranes-bill suggested (*but I'm not sure*) because after an Arch update to Qt-5.7.0-7 and qt5-webengine-5.7.0-6, it became a little better.

**Comment by nowrep** [comment]
@tsujan QtWebEngine 5.7.0 has some issues, you should test it with 5.7.1 or 5.8.0 (whichever is out first).

**Comment by tsujan** [comment]
@nowrep 
Yes, 5.7.0 has some bugs. I wait for a newer version in Arch. Qupzilla is so handy that such issues can't prevent me from using it instead of Firefox :)

**Comment by tsujan** [comment]
I confirm that the freeze like behavior is almost gone with QtWebEngine 5.7.1 :)

**Comment by tsujan** [comment]
The freeze is completely gone but, unfortunately, there's a lot of unneeded CPU usage with some pages -- github commit pages, for example. Since I recompiled the latest QupZilla against QtWebEngine 5.7.1, this should be related to another bug in QtWebEngine.

**Comment by tsujan** [comment]
I get these lines when cpu usage goes high on most github commit pages but I'm not sure they're relevant:
````
gdb qupzilla
....
[New Thread 0x7fff55a77700 (LWP 31596)]                                                                           
"Unexpected reply signature: got \"\", expected \"a{sv}\""                                                        
[New Thread 0x7fff55276700 (LWP 31626)]                                                                           
"Unexpected reply signature: got \"\", expected \"a{sv}\""                                                        
"Unexpected reply signature: got \"\", expected \"a{sv}\""                                                        
"Unexpected reply signature: got \"\", expected \"a{sv}\""
[Thread 0x7fff55276700 (LWP 31626) exited]
"Unexpected reply signature: got \"\", expected \"a{sv}\""
[Thread 0x7fff6141c700 (LWP 31561) exited]
"Unexpected reply signature: got \"\", expected \"a{sv}\""

````

**Comment by nowrep** [comment]
That's error message from DBus. It would be interesting to find what it is about. I think Chromium uses DBus only for geolocation (GeoClue2).

**Comment by tsujan** [comment]
@nowrep 
I found the cause of high cpu usage :) The above messages had nothing to do with it. It's about this message:
````
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
````
I saved a github commit page, that caused a high cpu usage (one of the cores went to 100%), as `mhtml`. Then I opened it with Firefox and saved it as MAF, changed MAF to ZIP, extracted the archive and removed these lines from the page:

      <animate attributeName="y1" values="0%; 100%" dur="1s" repeatCount="indefinite"></animate>
      <animate attributeName="y2" values="100%; 200%" dur="1s" repeatCount="indefinite"></animate>

When I opened the result with qupzilla, there was no high cpu usage anymore. When I restored those lines, cpu usage went high again.

Do you know of any workaround for this problem?

**Comment by tsujan** [comment]
Opened https://github.com/QupZilla/qupzilla/issues/2201 because the above issue isn't related to the current report.

**Comment by mathieujobin** [comment]
Here I am couple of years later,... I will give QupZilla 2.1.2 a try on Kubuntu 17.10 with Qt 5.9.1 and Plasma 5.12.5

Cheers,

will reopen if I experience this issue again
