### ISSUE TITLE
javascript function.toString  add semicolon  when  it has multi  comment 

### ISSUE THREAD

**Issue by tablecell** [QupZilla/qupzilla#1984]
test code 
```
<script type="text/javascript">



function test(){

/*

console.log("some");

*/
	

}



alert(test.toString());

</script>

```
firefox /chrome/opera  result is :
```
function test(){

/*

console.log("some");

*/
}
```
but qupzilla  result is  :
```
function test() {

/*

console.log("some");

*/;
	

} 
``` 
auto add semicolon at  multi line comment end 
	

```

**Comment by nowrep** [comment]
From spec: http://www.ecma-international.org/ecma-262/6.0/#sec-function.prototype.tostring

    The use and placement of white space, line terminators, and semicolons within the 
    representation String is implementation-dependent.

So it is perfectly fine.
