### ISSUE TITLE
[TabManager] TODO Improvements

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1986]
Good News.  Mozilla has eliminated Tab Groups!

It had a buggy, wasteful, ugly and not intuitive (Panorama) tab groups manager, to say the least!
The way Mozilla has implemented it was wasteful to a rate of over 50% to 70% extra memory usage (tested with 150 tabs).

I will test QupZilla TabManager and list suggested improvements.

Extensions to watch on:
https://github.com/traxium/tabtree
https://github.com/char101/tabgroupsmenu
https://github.com/IIUJ-KrzysztofDawidowicz/Tab-Group-Bar
https://addons.mozilla.org/en-US/firefox/addon/tab-group-switch/
https://addons.mozilla.org/en-US/firefox/addon/tabgroups-manager/

---

> **We've removed Tab Groups, but saved your tabs**
> 
> Firefox has bookmarked all your groups so you haven't lost anything.
> Learn about Tab Groups replacement add-ons.
> 
> You can also choose to restore some or all background groups into windows now:

From: chrome://browser/content/aboutTabGroupsMigration.xhtml

**Comment by JHooverman** [comment]
@nowrep: Should this issue be moved to qupzilla-plugins?

**Comment by srazi** [comment]
No issue listed here so I will close it, feel free to reopen it if you want add something.
