### ISSUE TITLE
Font, Icon, and Whitespace

### ISSUE THREAD

**Issue by cmrnt** [QupZilla/qupzilla#1987]
I am running a fully up-to-date OpenSuSE Tumbleweed with plasma 5.6.4 and Qt5.6.  Qupzilla jumped from 1.89 to 2.0 on an HP 820 G2 (Intel i7 Broadwell).  Version 2.0 runs well, but there is something wrong with rendering in the program itself and web pages.  It may be more than one bug, but it looks like it might be a single underlying issue.  None of these issues were present in version 1.89.  The rendering issues with 2.0 show up everywhere.

Case 1:
- Start Qupzilla
- Go general options pull down.
- The text is the correct size and centered on its line.
- There is too much white space above and below the text in the menu.
- The icon that supports the pull-down options is sometimes stretch vertically.
- The icon that supports the pull-down option is not centered vertically so it is misaligned relative to the text.
- (Can't figure out how to do a screen capture of this one).

Case 2:
- Open webpage like www.cnn.com
- Default fonts are at least a factor of two too large.
- Values for font sizes give a rendered font size that is too big.

Case 3:
- Start Qupzilla
- Navigation icons like forward, backward, reload are too
big, roughly by a factor of two.  The icons show pixelation, as well.
- Icons of bookmarked webpages are also too large
- Too much white space around font in menu pull-downs.

Also, way too much white space in the preferences menu.  These screen captures illustrate the rendering issues in general.

![qupzilla-default-profile-cnn](https://cloud.githubusercontent.com/assets/16405396/15538026/98244d0e-2247-11e6-980d-47b56b69597c.jpg)
![qupzilla-preferences-dialogue](https://cloud.githubusercontent.com/assets/16405396/15538028/9dafb6fa-2247-11e6-94e2-6bae2e466f91.jpg)

**Comment by nowrep** [comment]
You probably have HighDPI screen. It is already fixed #1935
