### ISSUE TITLE
No webpage display under Xubuntu 16.04 x86_64

### ISSUE THREAD

**Issue by JujuLand** [QupZilla/qupzilla#1989]
I having completely build QupZilla 2.0.0 with QT 5.6, when I launch it, no display of the webpages. No error too.

I just saw an error in the console, if I launch from terminal :
`alain@Dell-DM061:/opt/TuxPrograms/trunks/QupZilla-2.0.0/bin$ ./qupzilla
QML debugging is enabled. Only use this in a safe environment.
/opt/Qt5/5.6/gcc_64/libexec/QtWebEngineProcess: error while loading shared libraries: libQt5WebEngineCore.so.5: cannot open shared object file: No such file or directory
QupZilla: 0 extensions loaded`
Which was very suprising, as QtWebEngine was checked when installing with Qt5 online installer :
qt-unified-linux-x64-2.0.3-online.run
About QupZilla gives:
`Version de l'application 2.0.0
QtWebEngine version 5.6.0`

Having a look to the Qt5 install logfile; I saw this:
`[126864] addDownloadable "qtwebengine-opensource-src-5.4.2.7z"
[126871] addDownloadable "qtwebengine-opensource-src-5.5.1.7z"
[126874] addDownloadable "qt5_qtwebengine.7z"
[126894] addDownloadable "qtwebengine-opensource-src-5.6.0.7z"
[126895] addDownloadable "qtwebengine-documentation.7z"
[126895] addDownloadable "qtwebengine-examples-5.6.0.7z"
[126897] addDownloadable "qt5_qtwebengine.7z"
[126903] addDownloadable "qtwebengine-Linux-RHEL_6_6-GCC-Linux-RHEL_6_6-X86_64.7z"
[3567837] backup qt.56.doc.lgplv3.qtwebengine operation: Extract
[3567837] \t- arguments: installer://qt.56.doc.lgplv3.qtwebengine/5.6.0-1qtwebengine-documentation.7z, /opt/Qt5
[3567838] perform qt.56.doc.lgplv3.qtwebengine operation: Extract
[3567838] \t- arguments: installer://qt.56.doc.lgplv3.qtwebengine/5.6.0-1qtwebengine-documentation.7z, /opt/Qt5
[3568169] backup qt.56.doc.lgplv3.qtwebengine operation: Settings
[3568170] perform qt.56.doc.lgplv3.qtwebengine operation: Settings
[3576687] backup qt.56.examples.lgplv3.qtwebengine operation: Extract
[3576687] \t- arguments: installer://qt.56.examples.lgplv3.qtwebengine/5.6.0-1qtwebengine-examples-5.6.0.7z, /opt/Qt5
[3576690] perform qt.56.examples.lgplv3.qtwebengine operation: Extract
[3576690] \t- arguments: installer://qt.56.examples.lgplv3.qtwebengine/5.6.0-1qtwebengine-examples-5.6.0.7z, /opt/Qt5
[3581789] backup qt.56.qtwebengine.gcc_64 operation: Extract
[3581789] \t- arguments: installer://qt.56.qtwebengine.gcc_64/5.6.0-1qtwebengine-Linux-RHEL_6_6-GCC-Linux-RHEL_6_6-X86_64.7z, /opt/Qt5
[3581789] perform qt.56.qtwebengine.gcc_64 operation: Extract
[3581789] \t- arguments: installer://qt.56.qtwebengine.gcc_64/5.6.0-1qtwebengine-Linux-RHEL_6_6-GCC-Linux-RHEL_6_6-X86_64.7z, /opt/Qt5
[3589554] backup qt.56.qtwebengine.gcc_64 operation: QtPatch
[3589554] perform qt.56.qtwebengine.gcc_64 operation: QtPatch`

Perhaps the reason, perhaps no, but ...
I have tried the faq 10, but I have some error messages:
`alain@Dell-DM061:/opt/TuxPrograms/trunks/QupZilla-2.0.0/bin$ sudo sysctl kern.ipc.shmmax=67108864
sysctl: impossible d'obtenir les stat de /proc/sys/kern/ipc/shmmax: Aucun fichier ou dossier de ce type`

Thanks
A+

**Comment by cranes-bill** [comment]
Library path should be defined manually. For example:
`LD_LIBRARY_PATH=/opt/Qt5/5.6/gcc_64/lib` < (_or other path where Qt librarys are installed to_)

**Comment by JujuLand** [comment]
Nice, it works.

I have another problem since I uninstall (I think) Qupzilla 1.9:
`alain@Dell-DM061:/opt/TuxPrograms/trunks/QupZilla-2.0.0/bin$ ./qupzilla
QML debugging is enabled. Only use this in a safe environment.
Cannot load theme  "linux" (../../../QupZilla-2.0.0/src/lib/app/mainapplication.cpp:925, void MainApplication::loadTheme(const QString&))
QupZilla: 0 extensions loaded`

And no more toolbar icons ...
I have build again, but same problem.

Another problem, when using a link located  in /usr/local/bin, the qupzilla libs aren't found.
To say it in another way : How to install Qupzilla after building to have a classical install structure?

Thanks
A+

**Comment by cranes-bill** [comment]
Looks like you are running QupZilla from the same folder where you built it (_did not installed_). If you want to keep this, just rebuild with `NO_SYSTEM_DATAPATH` (see [BUILDING](https://github.com/QupZilla/qupzilla/blob/master/BUILDING.md)) and that will solve everithing...

**Comment by JujuLand** [comment]
Yes I run it now from within build folder

In BUILDING, it's said that to build:
qmake
make

Unfortunately, on Xubuntu (and ubuntu) the qt version which is installed is 4.7, and qmake is also 4.7, and it's not possible to use it.
So I use Qtcreator to build. It works, but don't create makefile, and I'm not able to make install

What could be a solution ?

A+

**Comment by nowrep** [comment]
Set in Qt Creator -> Projects -> qmake -> Additional arguments: `DEFINES+=NO_SYSTEM_DATAPATH` and do complete rebuild (Build -> Run qmake + Rebuild)

**Comment by JujuLand** [comment]
Weird too  ...

Finally, I remove qupzilla.pro.user, and clean and build.
Launching from bin, it works, but installing and launching, it fails:

`qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQupZilla.so.2)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQupZilla.so.2)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5X11Extras.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQupZilla.so.2)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQupZilla.so.2)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQupZilla.so.2)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libQupZilla.so.2)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5: version `Qt_5' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5WebEngineCore.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: version `Qt_5' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5WebEngineCore.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5WebEngineCore.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5Widgets.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5Widgets.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: version `Qt_5' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5WebEngineWidgets.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5WebEngineWidgets.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5QuickWidgets.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5: version `Qt_5' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5QuickWidgets.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5QuickWidgets.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5QuickWidgets.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5: version `Qt_5' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5WebChannel.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: version `Qt_5' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5Quick.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5Quick.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5Quick.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5Quick.so.5)
qupzilla: /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5: version `Qt_5' not found (required by /opt/Qt5/5.6/gcc_64/lib/libQt5Quick.so.5)`

I used staticBuild in Qbs and size is greater, but not seems to be a static build ...

For now, it's not the problem I want to solve, I just want to be able to use qupzilla without launching from within build folder.

A+

**Comment by nowrep** [comment]
Well, you must start it from build folder. If you don't want that, then you must install it system-wide.
