### ISSUE TITLE
Speed Dial: warning "Unable to load" may replace title of items

### ISSUE THREAD

**Issue by pmattern** [QupZilla/qupzilla#1992]
Under certain conditions error message "Unable to load" replaces the title of Speed Dial items as set in their configuration dialogue.

The problem takes place when the host running the web server is down but its DNS entry is still working as expected. (So it does *not* happen when the host running the web server is reachable e. g. by ping but just the web server isn't running.)
Under these circumstances the problem can be reproduced 100% here when a Speed Dial item, be it new or preexisting, gets edited to point to the server in question. The problem could also be seen when a Speed Dial topic had been configured to point to the server before and is clicked when the server failure is manifest. But so far I failed to reproduce this. Sometimes there's just that web page informing about the site not being accessible but the Speed Dial topic remains unchanged.
Once manifest the exchange is permanent, that is the warning message remains set as title when the site in question is working normally again.

Seen running 4b6730b on Arch Linux x86_64 or i686.

**Comment by JHooverman** [comment]
Is this really an issue with QupZilla? How should QupZilla handle network and/ or DNS-issues?

**Comment by pmattern** [comment]
As of 59278fa the problem is basically solved but persists if the URL of a Speed Dial item gets modified with "Load title from page" enabled right when the site in question isn't available. It doesn't matter whether an existing item gets edited or a new one is created or whether only the web server doesn't work or its corresponding host isn't reachable while its DNS still exists.
Obviously this  is a somewhat particular use case so I for one am not sure whether this really needs to get addressed.

On a side note I failed to trigger the appearance of the icons discussed in 3ea8521. Could you by any chance give me a hint when and where this icon is expected to come up?

**Comment by pmattern** [comment]
This issue was never meant to address findings made as long as some server failure is manifest but what happens when the server is available again.
This applies to my previous comment, too. When the server is working again the thumbnail gets refreshed as expected while the "Unable to load" message persists. As said before, only a rather particular case is still affected as of 3ea8521 the relevance of which isn't certain. (Personally, I'm certainly *not* affected as I never use option "Load title from page".)
