### ISSUE TITLE
High CPU/RAM usage on youtube

### ISSUE THREAD

**Issue by 397182613121** [QupZilla/qupzilla#1993]
When I play a youtube video, the browser immediately starts using 100% cpu and consuming 20-30MB of memory every second until my computer completely freezes.

Using version 2.0.0 with QtWebEngine 5.6.0 on windows 10.

**Comment by nowrep** [comment]
#1921

**Comment by potuz** [comment]
I know this is closed but I am experiencing the same issue since the update to qtwebengine-5.9.4. Qupzilla version 2.2.5 here on Gentoo.
