### ISSUE TITLE
Updating from 2.0.0 to 2.0.1 did not keep cookies

### ISSUE THREAD

**Issue by darkshram** [QupZilla/qupzilla#1996]
Afer upgrading from 2.0.0 to 2.0.1, all my logins to gmail, facebook, twitter, github, etc., got logged out. Had to sign-in again en every service. Same as when upgrading from 1.8.9 to 2.0.0. I understand it is to be expected when upgrading from 1.8.9 to 2.0.0 because the migration to qtwebkit to qtwebengine, but was unexpected/annoying when upgrading from 2.0.0 to 2.0.1. Using qupzilla in Linux, a custom Fedora-based OS. Qt 5.6.1.

**Comment by nowrep** [comment]
What OS do you use?

**Comment by darkshram** [comment]
Linux. Custom Fedora-based. Qt 5.6.1. Using the gnome-keyring backend, passwords are saved and automatically used when required.

**Comment by nowrep** [comment]
Well, it should work just fine. Did you get the popup saying incompatible profile version detected?

**Comment by darkshram** [comment]
No. That appeared only when upgrading from 1.8.9 to 2.0.0.

**Comment by nowrep** [comment]
So your history, bookmarks, settings, etc.. were all preserved, just the logins on sites (so cookies) were not, correct?

**Comment by darkshram** [comment]
Exactly. Seems only cookies were affected.

**Comment by nowrep** [comment]
Hm, that wasn't my intention and actually there shouldn't be any change in QupZilla code that could cause this.
Did you also update to Qt 5.6.1 at the same time? That might be the reason.

**Comment by darkshram** [comment]
Yes. You are right. I updated Qt from 5.6.0 to 5.6.1.

**Comment by AcarBurak** [comment]
Same here after Qt 5.6.1.

In addition to the old files:

~/.config/qupzilla/profiles/default/Coookies
~/.config/qupzilla/profiles/default/Coookies-journal

there're now these file too (just two "o"s instead of three "o"s)

~/.config/qupzilla/profiles/default/Coookies
~/.config/qupzilla/profiles/default/Coookies-journal

So deleting those two new files and renaming the old ones by just deleting an "o" in each file name seems to have sold the issue.

**Comment by nowrep** [comment]
That's actually bug in QtWebEngine - https://code.qt.io/cgit/qt/qtwebengine.git/commit/?id=4ed08bb0a8195746c333dabbdb9da3400d174296
Apparently, this backwards compatibility with file with typo doesn't work.
