### ISSUE TITLE
Unwatchable HTML5 videos (not all of them)

### ISSUE THREAD

**Issue by mako2580** [QupZilla/qupzilla#1998]
Hi, I'm using Qupzilla 1.8.9 on Arch Linux and some of HTML5 videos (not HD, they're working perfectly) looks like this. I tried to play this exact video from terminal over ffplay and gst-play-1.0 and everything worked.
![screenshot_20160611_223437_crop](https://cloud.githubusercontent.com/assets/2705448/15987362/c5fb54d4-3025-11e6-8613-4c7c8133c52f.png)

**Comment by JHooverman** [comment]
Is the label `QtWebEngine` correct here (version 1.8.9)? Shouldn't it rather be `QtWebkit`?

**Comment by mako2580** [comment]
Yes it should be QtWebkit

**Comment by nowrep** [comment]
Ah sorry, I missed that. In that case, please use latest version (2.0.1) with QtWebEngine.
