### ISSUE TITLE
How to find working user agent string for site?

### ISSUE THREAD

**Issue by jamesqf** [QupZilla/qupzilla#1999]
The site is www.chase.com, where I have an account.  As of today, it is not letting me access the site (and I need to pay a bill in the next couple of days), and giving me a message that I must upgrade my browser, and giving me the choice of IE, Safari, Chrome, or Firefox.  Well, I can't use the Windoze or Mac options, obviously (since I use Linux), won't under any circumstances use Chrome, and detest recent versions of Firefox - and don't see why I should keep a version around just for this one site.  

I want to keep using QupZilla.  I've tried using various user agent strings (the ones in the list, and various ones found with web searches), but always get the same message.  So how can I find a user agent string that will work?  (I'm on 1.8.9, if it matters.)

**Comment by The-Compiler** [comment]
I see no way you could - the server is a blackbox.

**Comment by jamesqf** [comment]
Couldn't someone with a browser that works for that site (latest version of Firefox, maybe?) just obtain its user agent string and post it, so that we could put it into QupZilla's list?  I find a number of sites that will show the string from whatever browser you're using, and some with lists of them.  Unfortunately, I've not found anything that's sorted by date/version, so it's been a matter of more-or-less random trials, none of which have worked - so far, anyway.

**Comment by nowrep** [comment]
`Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0`

**Comment by nowrep** [comment]
I've updated the UA strings in e5de2a240356252384d0f610edebbc99715ab027 , so should be fine now.

**Comment by jamesqf** [comment]
Thanks for the string, but it doesn't work in a quick test: pull up "User Agent Manager", edit site "www.chase.com", paste in that string.  Is there perhaps something else I need to do to make that string be used with the site?  (Also tried the full "https://www.chase.com" as the site, same result.)

(I dunno... I guess those people just don't want any more of my money.  I know I'll be moving the couple of autopay accounts off that card, and putting it in my pile of unused ones.)

**Comment by jamesqf** [comment]
Just an update: That string does work with the Chase.com site (and with Bing maps, which was giving me a similar message) if I make it the global user agent, instead of site specific.  Maybe there's a problem in the code?  (I'm on 1.8.9)  Anyway, thanks again for the help!

**Comment by jamesqf** [comment]
Just an update: That string does work with the Chase.com site (and with Bing maps, which was giving me a similar message) if I make it the global user agent, instead of site specific.  Maybe there's a problem in the code?  (I'm on 1.8.9)  Anyway, thanks again for the help!

**Comment by jamesqf** [comment]
Just an update: That string does work with the Chase.com site (and with Bing maps, which was giving me a similar message) if I make it the global user agent, instead of site specific.  Maybe there's a problem in the code?  (I'm on 1.8.9)  Anyway, thanks again for the help!

**Comment by jamesqf** [comment]
Just an update: That string does work with the Chase.com site (and with Bing maps, which was giving me a similar message) if I make it the global user agent, instead of site specific.  Maybe there's a problem in the code?  (I'm on 1.8.9)  Anyway, thanks again for the help!

**Comment by jamesqf** [comment]
Just an update: That string does work with the Chase.com site (and with Bing maps, which was giving me a similar message) if I make it the global user agent, instead of site specific.  Maybe there's a problem in the code?  (I'm on 1.8.9)  Anyway, thanks again for the help!

**Comment by The-Compiler** [comment]
Aaand you just found out how GitHub doesn't refresh comments when you switch away from the default UA with QtWebKit :wink:

**Comment by jamesqf** [comment]
How nice of GitHub not to do that :-(

I'm beginning to think that I should be more appreciative of the many
web sites that just work, regardless of what browser you happen to be
using.

James
