### ISSUE TITLE
Strange colors in Library

### ISSUE THREAD

**Issue by smarquespt** [QupZilla/qupzilla#2002]
Specs:

Qupzilla 2.0.1 (portable), Windows 7 64 bits

Menu -> Organize bookmarks

It show up attached image? Are these black colors intentioned? The colors were differente before.
![library](https://cloud.githubusercontent.com/assets/1302668/16098859/1801a06a-334d-11e6-9a4f-8661df3313ce.jpg)

**Comment by Martii** [comment]
Black left pane in **QupZilla 2.0.0** and **2.0.1** with top grayish background with Win7x64 actual *(e.g. not portable)*... so this shouldn't be an image opt issue... hopefully the gradient is dynamically rendered. Will upload a screen cap in a bit for comparison.

OS X and Linux show a bluish gradient... upper grayish background does not fill the exact width of the window e.g. left pane top to bottom.

**Comment by nowrep** [comment]
Bug in windows theme.

**Comment by nowrep** [comment]
Fixed in latest builds, please re-download from homepage.
