### ISSUE TITLE
Splelcheck removed in 2.x builds

### ISSUE THREAD

**Issue by smarquespt** [QupZilla/qupzilla#2003]
Not really a bug or feature request but merely a question.

Why was spellcheck removed from 2.x releases? is it not supported anymore? Will it be added in future?

**Comment by francoism90** [comment]
See https://github.com/QupZilla/qupzilla/issues/1852
From what I understand, spellchecking will be back in Qt 5.8.

**Comment by smarquespt** [comment]
Got it. Thanks
