### ISSUE TITLE
Feature Request : Foxyproxy addon

### ISSUE THREAD

**Issue by Ara4Sh** [QupZilla/qupzilla#2006]
Hello 

Please support Foxyproxy or something simillar to manage http proxies . 

thank you # #

**Comment by JHooverman** [comment]
What about using the `StatusBarIcon`-Extension? Here you will be able to manage the proxies with just two clicks:

![img1](http://i.imgur.com/nwFbGs0.png)

![img2](http://i.imgur.com/6uPy3Su.png)

**Comment by Ara4Sh** [comment]
Thank you , that what I exactly want .
