### ISSUE TITLE
Middle click open in new Tab not working!

### ISSUE THREAD

**Issue by IsaiahPatton** [QupZilla/qupzilla#2010]
This effects ALL websites but for example if you goto:
examplesite.com/example 
and thares a link to
examplesite.com/example/page1
on there and you middle click to open it in a new tab insead of going to
examplesite.com/example/page1
it will goto
examplesite.com/example/example/page1

It effects all websites!

**Comment by nowrep** [comment]
Can you post one example site where do you get this bug? It works fine for me.

**Comment by IsaiahPatton** [comment]
On
https://www.spigotmc.org/resources/
