### ISSUE TITLE
[Question] Strange behaviour in SpeedDial's entry icon size

### ISSUE THREAD

**Issue by SafaAlfulaij** [QupZilla/qupzilla#2015]
So, I reinstalled Arch and built QupZilla 2 from source.
I'm getting these small/huge thumbnails in the Speed Dial. Any idea of what can be the cause?
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/16372783/4fd92482-3c57-11e6-8a3f-54c78855f32d.png)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/16372784/4fffe874-3c57-11e6-8355-adb809bc2c71.png)

**Comment by Martii** [comment]
Grouping with [this comment](https://github.com/QupZilla/qupzilla/issues/1925#issuecomment-228570164) as it is similar albeit micro instead of macro.... both seem to be off in spacing.

Which Qt did you build against?

**Comment by SafaAlfulaij** [comment]
Qt5.7! We are on the same track! :smile:

**Comment by nowrep** [comment]
It's regression in QtWebEngine 5.7

**Comment by bvbfan** [comment]
Why is closed? Issue present. Start Qupzilla, make speeddial start page, click on speeddial page, then close tab, speeddial is no showing agin in this tab, click on new tab speedial i again brocken, click home button speeddial is broken agian

**Comment by nowrep** [comment]
@bvbfan Works fine for me, are you sure you run latest master?

**Comment by bvbfan** [comment]
Qt 5.7 
https://github.com/KaOSx/apps/blob/master/qupzilla/PKGBUILD
_commit=f0e2b93
