### ISSUE TITLE
Qupzilla 2.0 no tab to restore after crash

### ISSUE THREAD

**Issue by stefonarch** [QupZilla/qupzilla#2016]
After compiling on arch against qt 5.7 the "restore from crash" feature is broken, the window to restore tab opens but the list is just empty.
```
Qupzilla 2.0.99 (198bfae88f) 

 $ pacman -Qi qt5-webengine 
Nome                      : qt5-webengine
Versione                  : 5.7.0-1
Descrizione               : Provides support 
```

**Comment by pavbaranov** [comment]
I've noticed this same bug. It seems that it's related to profile created by QupZilla build against of qt5-webengine < 5.7 or qt5-webkit. After clear ~/.config/qupzilla/profiles, "restore from crash" works again.

**Comment by nowrep** [comment]
f0e2b938ba9fa6b6881c805c0bb32b10c55ee7fc
