### ISSUE TITLE
Add short command line for more options

### ISSUE THREAD

**Issue by spaeps** [QupZilla/qupzilla#2020]
The switch to [**QCommandLineParser**](http://doc.qt.io/qt-5/qcommandlineparser.html) forced the use of single letter for single dash command line.
So, short options like -pb for private browsing are not allowed anymore.

Since using more than a letter for short options is not possible anymore, i suggest to introduce single letter short options for any (or the most used/complex) command line option.

Ex.:

```
Options:
  -h, --help                   Displays this help.
  -v, --version                Displays version information.
  -a, --authors                Displays author information.
  -p, --profile <profileName>  Starts with specified profile.
  -e, --no-extensions          Starts without extensions.
  -i, --private-browsing       Starts private browsing.
  -o, --portable               Starts in portable mode.
  -r, --no-remote              Starts new browser instance.
  -t, --new-tab                Opens new tab.
  -w, --new-window             Opens new window.
  -d, --download-manager       Opens download manager.
  -c, --current-tab <URL>      Opens URL in current tab.
  -u, --open-window <URL>      Opens URL in new window.
  -f, --fullscreen             Toggles fullscreen.

```
Since there are words starting with the same letter, a less intuitive but working one have to be choosen.
So, using bold letters to clarify the choice:
**h**elp
**v**ersion
**a**uthors
**p**rofile
no-**e**xtensions
pr**i**vate-browsing
p**o**rtable
no-**r**emote
new-**t**ab
new-**w**indow
**d**ownload-manager
**c**urrent-tab <URL>
open-window <**U**RL>
**f**ullscreen

Uppercase letters can be used too.
[Here](https://gist.githubusercontent.com/anonymous/1b9313cccbb697624b274d05564c6c75/raw/1436ebf32ce7f286f59e934f7e4dc6971e44ec95/qupzilla-commandline-short-options.patch) is a working patch.

**Comment by Martii** [comment]
Haven't had a chance to test this yet but is there support concatenation of the switches e.g. `-if` as a multiple switch?

**Comment by spaeps** [comment]
@Martii There's the
void [QCommandLineParser::setSingleDashWordOptionMode(SingleDashWordOptionMode singleDashWordOptionMode)](http://doc.qt.io/qt-5/qcommandlineparser.html#setSingleDashWordOptionMode)
function for setting the parsing mode for single dash words and the
[QCommandLineParser::ParseAsLongOptions](http://doc.qt.io/qt-5/qcommandlineparser.html#SingleDashWordOptionMode-enum) enum that is described as

> -abc is interpreted as --abc, i.e. as the long option named abc. This is how Qt's own tools (uic, rcc...) have always been parsing arguments. This mode should be used for preserving compatibility in applications that were parsing arguments in such a way.

So using multiple letters is allowed, but probably then all options would be usable, e.g. --pb, --private-browsing, -pb, and -private-browsing. I'll have to dig into it.

Now there's a sample patch for my first proposal in the first post.

**Comment by Martii** [comment]
One my personal pet peeves is when a \*nix based program uses single dashes with full length switch names is why I ask... as a benefit with bash *(terminal)* most binaries offer combining certain single letter switches together like `-if` which would be the same as `-i -f` and expanded as `--private-browsing --fullscreen`. Windows `cmd`, powershell, etc. isn't all that good at this so that might be a consideration too. Do like terminal CLI shortcuts a lot.

**Comment by cranes-bill** [comment]
@nowrep
I don't know about above, but what about if some long options are a bit short. For example, personally i'm just using `--private` instead of `--private-browsing`.

**Comment by jamesqf** [comment]
Rather than changing options, wouldn't it be much simpler to drop the QCommandLineParser function in favor of something that works correctly?

**Comment by nowrep** [comment]
@jamesqf What is wrong with QCommandLineParser?

**Comment by jamesqf** [comment]
Isn't that implicit in the OP's statement that "short options like -pb for private browsing are not allowed anymore"?  Of course if you don't want short options like '-pb' to be allowed any more, then QCommandLineParser is ok.

**Comment by nowrep** [comment]
@jamesqf Yes it is, but I don't really see it as a shortcoming. It still works better than my code before.

@spaeps Can you please open pull request with the patch?
