### ISSUE TITLE
can't highlight text with mouse

### ISSUE THREAD

**Issue by gothmog123** [QupZilla/qupzilla#2021]
This is on Arch, with qupzilla package from community-testing.

**Comment by KottV** [comment]
Can confirm with Qt5 Kvantum style engine.

**Comment by ozky** [comment]
Yes i can too i can raise bug in kvantum i use engine and know tsujan is fast to fix things.

**Comment by nowrep** [comment]
This is bug in QtWebEngine 5.7

**Comment by ozky** [comment]
No it's not i have qt5.6 webengine.

**Comment by ozky** [comment]
Also it works with fusion style only kvantum is broken.

**Comment by nowrep** [comment]
Ok, sorry. But there was (is?) a similar issue with QtWebEngine 5.7

**Comment by tsujan** [comment]
> Ok, sorry. But there was (is?) a similar issue with QtWebEngine 5.7

A link to that bug report, please?

**Comment by ozky** [comment]
It works now you can close this bug.

**Comment by nowrep** [comment]
@tsujan Cannot find the bug now, maybe it was just reported on irc channel.
