### ISSUE TITLE
How to keep the 1.8.x history for usage with 2.x?

### ISSUE THREAD

**Issue by R-a-l-f** [QupZilla/qupzilla#2026]
My apologies, #2025 was closed by accident.

Hi,

is there a way to get back important histories after upgrading to qupzilla 2.0.1 on Linux?

Do I need to downgrade qupzilla and restore the data from a backup?

Assumed it should be impossible to import the old histories for usage with 2.0.1, then I need to downgrade to get access to the histories and need to drop qupzilla and use another browser in the future.

$ grep 2016-07-10 /var/log/pacman.log | grep qupzilla
[2016-07-10 08:17] [ALPM] upgraded qupzilla (1.8.9-4 -> 2.0.1-2)

"For those updating from 1.8.x versions: It is advisable to start with new profile as updating profile from 1.8.x to 2.x version is not supported. You can create and remove profiles from preferences." - http://blog.qupzilla.com/

I missed that information before I launched qupzilla for one user. However, for another user I launched qupzilla by command line with

  $ qupzilla --profile update

But when I launched

 $ qupzilla --profile default

I anyway got

"Incompatible profile version has been detected. To avoid losing your
profile data, they were backed up in following file:

/snip/snip/.config/qupzilla/profiles/default/browsedata-backup(1).db"

and lost the important history.

Regards,
Ralf

**Comment by nowrep** [comment]
It can be reopened, instead of creating new issue.

To get your old history, just quit QupZilla and rename the backup file "browsedata-backup(1.).db" to "browsedata.db"

**Comment by R-a-l-f** [comment]
Thank you,

$ mv .config/qupzilla/profiles/default/browsedata-backup\(1\).db \
.config/qupzilla/profiles/default/browsedata.db
$ qupzilla --profile default

and the history is back.

How do I get back speed dial entries, too?

I've seen no option to reopen the issue.

Regards,
Ralf

**Comment by pejakm** [comment]
> How do I get back speed dial entries, too?

`settings.ini` should also be backed up.

**Comment by R-a-l-f** [comment]
Thank you,

unfortunately the content of the mail I received is just:
"> How do I get back speed dial entries, too?  

`settings.ini` should also be backed up."

So I wasn't aware that I should just have copied

$ grep l] -A6 .config/qupzilla/profiles/default/settings.ini 
[SpeedDial]
background=
backsize=auto
pages="url:\"http://www.dict.cc\"|title:\"dict.cc\";url:[snip]

instead I restored settings.ini

$ mv settings-backup.ini settings.ini 
$ qupzilla

this brought back speed dial, but after that the menu bar was lost. Solved by Chromium menu > View > Toolbars > [x] Menu Bar.
It also couldn't connect to the Internet anymore. Solved by Edit > Preferences > Browsing > Proxy Configuration > [x] System proxy configuration.

I couldn't notice any other issues.

Regards,
Ralf
