### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME at localhost

### ISSUE THREAD

**Issue by baddwin** [QupZilla/qupzilla#2028]
When I try to open `localhost:8000` --for example, it throws error `ERR_UNKNOWN_URL_SCHEME`. I need to append `http` before `localhost`. I think it is convenient if we don't have to append `http` first.

**Comment by gauthma** [comment]
This still happens in the latest version... but interestingly enough, if you type 127.0.0.1:8000, it works without the http:// prepended!
