### ISSUE TITLE
No passwords saved

### ISSUE THREAD

**Issue by fdservices** [QupZilla/qupzilla#2030]
Password Manager does not show any saved passwords. Import of passwords from an html file appears to be successful, but Password Manager remains empty.

Qupzilla:
Application version 2.0.1
QtWebEngine version 5.7.0

Linux:
Linux acer 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux

Qt:
5.7.0.1

**Comment by nowrep** [comment]
Bug in Qt 5.7.0, should be fixed in 5.7.1
