### ISSUE TITLE
Tabs position not restored after reboot

### ISSUE THREAD

**Issue by fdservices** [QupZilla/qupzilla#2031]
Steps to reproduce:

Unset "Tabs on Top"
Reboot PC
"Tabs on Top" has been set again.

**Comment by nowrep** [comment]
Should work fine, can you check if the option is correctly saved in $PROFILE/settings.ini? It's in `[Browser-Tabs-Settings] TabsOnTop`

**Comment by fdservices** [comment]
Yes, it is correctly saved, and is now working OK. I have no idea why this went wrong, but I have had other instances of settings not being saved on reboot with other programmes, so it is clearly something in my set up. Sorry to take your time.
