### ISSUE TITLE
Build failed under Ubuntu 14.04

### ISSUE THREAD

**Issue by JujuLand** [QupZilla/qupzilla#2034]
Ubuntu 14.04
QT 5.6.1
Qtcreator 4.0.1

Here is the error:

`../../../QupZilla-2.0.0/src/lib/app/browserwindow.cpp
../../../QupZilla-2.0.0/src/lib/app/browserwindow.cpp:88:26: fatal error: xcb/xcb_atom.h: No such file or directory
 #include <xcb/xcb_atom.h>
                          ^
compilation terminated.
make[1]: *** [../../../QupZilla-2.0.0/build/browserwindow.o] Error 1
make[1]: Leaving directory `/opt/TuxPrograms/trunks/build-QupZilla-Desktop_Qt_5_6_1_GCC_64bit-Debug/src/lib'
make: *** [sub-src-lib-make_first] Error 2
21:39:24: Le processus "/usr/bin/make" s'est terminé avec le code 2.
Erreur lors de la compilation/déploiement du projet QupZilla (kit : Desktop Qt 5.6.1 GCC 64bit)
When executing step "Make"`
In defines.pri, I have these lines:
`d_nox11 = $$(NO_X11)`
and 
`equals(d_nox11, "true") { DEFINES *= NO_X11 }`

Are these lines to be modified, and how ?

Thanks
A+

**Comment by nowrep** [comment]
Do you have `libxcb-dev` installed?

**Comment by JujuLand** [comment]
No, because:

gavroche@XPS-8900:~$ sudo apt-get install libxcb-dev 
[sudo] password for gavroche: 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet libxcb-dev

Haven't be able to fing the good packet name.

A+

**Comment by nowrep** [comment]
libxcb-util-dev

**Comment by JujuLand** [comment]
gavroche@XPS-8900:~$ sudo apt-get install libxcb-util-dev 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: **Impossible de trouver le paquet libxcb-util-dev**

**Comment by nowrep** [comment]
libxcb-util0-dev

**Comment by JujuLand** [comment]
Nice, it builds.

But it would be cool to report it on README.md, to avoid opening an issue for that ;)

Thanks
A+

**Comment by nowrep** [comment]
It's mentioned that you need to have xcb libraries. However, to mention exact package name is not really possible as it is named differently in each distro (and even in different Ubuntu versions).

**Comment by JujuLand** [comment]
Error when launching:

Démarrage de /opt/TuxPrograms/trunks/QupZilla-2.0.0/bin/qupzilla...
/opt/TuxPrograms/trunks/QupZilla-2.0.0/bin/qupzilla: error while loading shared libraries: **libQupZilla.so.2: cannot open shared object file: No such file or directory**
/opt/TuxPrograms/trunks/QupZilla-2.0.0/bin/qupzilla s'est terminé avec le code 127

gavroche@XPS-8900:~$ locate -b libQupZilla.so
/usr/lib/x86_64-linux-gnu/libQupZilla.so
/usr/lib/x86_64-linux-gnu/libQupZilla.so.1
/usr/lib/x86_64-linux-gnu/libQupZilla.so.1.8
/usr/lib/x86_64-linux-gnu/libQupZilla.so.1.8.9

A+

**Comment by nowrep** [comment]
You should either run `make install` or build with `NO_SYSTEM_DATAPATH="true"
qmake -r`. Both is in building info
