### ISSUE TITLE
Scroll position not saved when use back button (QtWebEngine)

### ISSUE THREAD

**Issue by bvbfan** [QupZilla/qupzilla#2035]
You have a view with links and scroll, perform scroll activity and click on link, go back scroll is every time on top level. Regression since QtWebKit, i'm not sure it is Qupzilla issue or QtWebEngine/Blink one.
Example: https://git.reviewboard.kde.org/r/ scroll down, click on link, go back, scroll is at highest level. Works as expected on Webkit.

**Comment by nowrep** [comment]
Fixed in recent QtWebEngine
