### ISSUE TITLE
Cannot disable javascript in private mode

### ISSUE THREAD

**Issue by spaeps** [QupZilla/qupzilla#2037]
In Private Browsing, javascript keeps enabled even if disabled in the settings manager.

Steps to reproduce:
- exec qupzilla --private-browsing
- Preferences -> Browsing -> Uncheck "Allow Javascript" -> OK
- Check http://www.isjavascriptenabled.com/ or similar (still enabled)
- Javascript is still enabled

Also:
- exec qupzilla
- disable javascript via Preferences
- check http://www.isjavascriptenabled.com/ or similar (disabled)
- exit qupzilla
- exec qupzilla --private-browsing
- check "Allow javascript" in Preferences (is already unchecked)
- check http://www.isjavascriptenabled.com/ or similar (still enabled)

I have little time for digging into it, but i'll try soon.

**Comment by nowrep** [comment]
Changing preferences in private mode is disabled.

**Comment by nowrep** [comment]
Fixed now
