### ISSUE TITLE
qupzilla 2.0.1 crash 

### ISSUE THREAD

**Issue by giresun28** [QupZilla/qupzilla#2038]
QupZilla: 0 extensions loaded
*** Error in `qupzilla': double free or corruption (fasttop): 0x00000000060675f0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x6f374)[0x7f8892234374]
/lib64/libc.so.6(+0x74db6)[0x7f8892239db6]
/lib64/libc.so.6(+0x7559e)[0x7f889223a59e]
/usr/lib/dri/nouveau_dri.so(+0x418f8f)[0x7f887d2f4f8f]
/usr/lib/dri/nouveau_dri.so(+0x4191ce)[0x7f887d2f51ce]
/usr/lib/dri/nouveau_dri.so(+0x4194f3)[0x7f887d2f54f3]
/usr/lib/dri/nouveau_dri.so(+0x1f09a2)[0x7f887d0cc9a2]
/usr/lib/dri/nouveau_dri.so(+0x1f09d0)[0x7f887d0cc9d0]
/usr/lib/libQt5Widgets.so.5(+0x1b4ab9)[0x7f8895530ab9]
/usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate17sendComposeStatusEP7QWidgetb+0xc9)[0x7f8895501239]
/usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate17sendComposeStatusEP7QWidgetb+0x87)[0x7f88955011f7]
/usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate17sendComposeStatusEP7QWidgetb+0x87)[0x7f88955011f7]
/usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate17sendComposeStatusEP7QWidgetb+0x87)[0x7f88955011f7]
/usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate17sendComposeStatusEP7QWidgetb+0x87)[0x7f88955011f7]
/usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate17sendComposeStatusEP7QWidgetb+0x87)[0x7f88955011f7]
/usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate17sendComposeStatusEP7QWidgetb+0x87)[0x7f88955011f7]
/usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate17sendComposeStatusEP7QWidgetb+0x87)[0x7f88955011f7]
/usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate17sendComposeStatusEP7QWidgetb+0x87)[0x7f88955011f7]
/usr/lib/libQt5Widgets.so.5(+0x15f5b4)[0x7f88954db5b4]
/usr/lib/libQt5Widgets.so.5(+0x1602ce)[0x7f88954dc2ce]
/usr/lib/libQt5Widgets.so.5(+0x1629e3)[0x7f88954de9e3]
/usr/lib/libQt5Widgets.so.5(+0x162b97)[0x7f88954deb97]
/usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate16syncBackingStoreEv+0x3f)[0x7f88954fbe0f]
/usr/lib/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x318)[0x7f8895512b98]
/usr/lib/libQt5Widgets.so.5(_ZN11QMainWindow5eventEP6QEvent+0x15b)[0x7f889561cadb]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7f88954d14fc]
/usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x226)[0x7f88954d63d6]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x108)[0x7f889350e3b8]
/usr/lib/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x2ca)[0x7f889351019a]
/usr/lib/libQt5Core.so.5(+0x2bd4c3)[0x7f88935604c3]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x287)[0x7f8891071657]
/usr/lib/libglib-2.0.so.0(+0x48888)[0x7f8891071888]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7f889107192c]
/usr/lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7f88935608cf]
/usr/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0xea)[0x7f889350c6ba]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x8d)[0x7f889351476d]
qupzilla[0x402f35]
/lib64/libc.so.6(__libc_start_main+0xf0)[0x7f88921e5710]
qupzilla[0x403229]
======= Memory map: ========
00400000-00405000 r-xp 00000000 08:08 2506587                            /usr/bin/qupzilla
00605000-00606000 rw-p 00005000 08:08 2506587                            /usr/bin/qupzilla
01cae000-06409000 rw-p 00000000 00:00 0                                  [heap]
a3da6000000-a3da6001000 ---p 00000000 00:00 0 
a3da6001000-a3da6002000 rw-p 00000000 00:00 0 
a3da6002000-a3da6004000 ---p 00000000 00:00 0 
a3da6004000-a3da61fc000 rw-p 00000000 00:00 0 
a3da61fc000-a3da6200000 ---p 00000000 00:00 0 
26a5ddc00000-26a5ddc01000 ---p 00000000 00:00 0 
26a5ddc01000-26a5ddc02000 rw-p 00000000 00:00 0 
26a5ddc02000-26a5ddc04000 ---p 00000000 00:00 0 
26a5ddc04000-26a5dddfc000 rw-p 00000000 00:00 0 
26a5dddfc000-26a5dde00000 ---p 00000000 00:00 0 
7f87e8000000-7f87e8022000 rw-p 00000000 00:00 0 
7f87e8022000-7f87ec000000 ---p 00000000 00:00 0 
7f87ec000000-7f87ec021000 rw-p 00000000 00:00 0 
7f87ec021000-7f87f0000000 ---p 00000000 00:00 0 
7f87f0000000-7f87f0021000 rw-p 00000000 00:00 0 
7f87f0021000-7f87f4000000 ---p 00000000 00:00 0 
7f87f6554000-7f87f658b000 r-xp 00000000 08:08 2771820                    /usr/lib/libcroco-0.6.so.3.0.1
7f87f658b000-7f87f678b000 ---p 00037000 08:08 2771820                    /usr/lib/libcroco-0.6.so.3.0.1
7f87f678b000-7f87f678e000 rw-p 00037000 08:08 2771820                    /usr/lib/libcroco-0.6.so.3.0.1
7f87f678e000-7f87f67c3000 r-xp 00000000 08:08 2771827                    /usr/lib/librsvg-2.so.2.40.13
7f87f67c3000-7f87f69c3000 ---p 00035000 08:08 2771827                    /usr/lib/librsvg-2.so.2.40.13
7f87f69c3000-7f87f69c4000 rw-p 00035000 08:08 2771827                    /usr/lib/librsvg-2.so.2.40.13
7f87f69c4000-7f87f69c6000 r-xp 00000000 08:08 2759364                    /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7f87f69c6000-7f87f6bc5000 ---p 00002000 08:08 2759364                    /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7f87f6bc5000-7f87f6bc6000 rw-p 00001000 08:08 2759364                    /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7f87f6bc6000-7f87f6bc7000 ---p 00000000 00:00 0 
7f87f6bc7000-7f87f73c7000 rw-p 00000000 00:00 0                          [stack:2417]
7f87f73c7000-7f87f73c8000 ---p 00000000 00:00 0 
7f87f73c8000-7f87f7bc8000 rw-p 00000000 00:00 0                          [stack:2416]
7f87f7bc8000-7f87f7bca000 r-xp 00000000 08:08 393269                     /lib64/libutil-2.23.so
7f87f7bca000-7f87f7dc9000 ---p 00002000 08:08 393269                     /lib64/libutil-2.23.so
7f87f7dc9000-7f87f7dca000 r--p 00001000 08:08 393269                     /lib64/libutil-2.23.so
7f87f7dca000-7f87f7dcb000 rw-p 00002000 08:08 393269                     /lib64/libutil-2.23.so
7f87f7dcb000-7f87f7dff000 r-xp 00000000 08:08 2773290                    /usr/lib/libbluray.so.1.6.2
7f87f7dff000-7f87f7ffe000 ---p 00034000 08:08 2773290                    /usr/lib/libbluray.so.1.6.2
7f87f7ffe000-7f87f8000000 rw-p 00033000 08:08 2773290                    /usr/lib/libbluray.so.1.6.2
7f87f8000000-7f87f804a000 rw-p 00000000 00:00 0 
7f87f804a000-7f87fc000000 ---p 00000000 00:00 0 
7f87fc000000-7f87fc064000 rw-p 00000000 00:00 0 
7f87fc064000-7f8800000000 ---p 00000000 00:00 0 
7f8800000000-7f8800021000 rw-p 00000000 00:00 0 
7f8800021000-7f8804000000 ---p 00000000 00:00 0 
7f8804000000-7f8804021000 rw-p 00000000 00:00 0 
7f8804021000-7f8808000000 ---p 00000000 00:00 0 
7f8808000000-7f8808021000 rw-p 00000000 00:00 0 
7f8808021000-7f880c000000 ---p 00000000 00:00 0 
7f880c025000-7f880c125000 rw-s 00000000 00:11 22204                      /dev/shm/.org.chromium.Chromium.pHyMG3 (deleted)
7f880c125000-7f880c15b000 r-xp 00000000 08:08 2766599                    /usr/lib/gvfs/libgvfscommon.so
7f880c15b000-7f880c35a000 ---p 00036000 08:08 2766599                    /usr/lib/gvfs/libgvfscommon.so
7f880c35a000-7f880c360000 rw-p 00035000 08:08 2766599                    /usr/lib/gvfs/libgvfscommon.so
7f880c360000-7f880c390000 r-xp 00000000 08:08 2773296                    /usr/lib/gio/modules/libgvfsdbus.so
7f880c390000-7f880c590000 ---p 00030000 08:08 2773296                    /usr/lib/gio/modules/libgvfsdbus.so
7f880c590000-7f880c592000 rw-p 00030000 08:08 2773296                    /usr/lib/gio/modules/libgvfsdbus.so
7f880c592000-7f880c5b8000 r-xp 00000000 08:08 2771715                    /usr/lib/libdbus-glib-1.so.2.3.2
7f880c5b8000-7f880c7b7000 ---p 00026000 08:08 2771715                    /usr/lib/libdbus-glib-1.so.2.3.2
7f880c7b7000-7f880c7b9000 rw-p 00025000 08:08 2771715                    /usr/lib/libdbus-glib-1.so.2.3.2
7f880c7b9000-7f880c8b9000 rw-s 00000000 00:11 22179                      /dev/shm/.org.chromium.Chromium.ZPSCXw (deleted)
7f880c8b9000-7f880c9b9000 rw-s 00000000 00:11 22178                      /dev/shm/.org.chromium.Chromium.eNT10n (deleted)
7f880c9b9000-7f880c9ba000 ---p 00000000 00:00 0 
7f880c9ba000-7f880d1ba000 rw-p 00000000 00:00 0                          [stack:2406]
7f880d1ba000-7f880d56b000 rw-s 00000000 00:05 2457622                    /SYSV00000000 (deleted)
7f880d56b000-7f880d56c000 ---p 00000000 00:00 0 
7f880d56c000-7f880dd6c000 rw-p 00000000 00:00 0                          [stack:2405]
7f880dd80000-7f880ddaf000 r-xp 00000000 08:08 2772826                    /usr/lib/libgconf-2.so.4.1.5
7f880ddaf000-7f880dfaf000 ---p 0002f000 08:08 2772826                    /usr/lib/libgconf-2.so.4.1.5
7f880dfaf000-7f880dfb1000 rw-p 0002f000 08:08 2772826                    /usr/lib/libgconf-2.so.4.1.5
7f880dfb1000-7f880dfb2000 ---p 00000000 00:00 0 
7f880dfb2000-7f880e7b2000 rw-p 00000000 00:00 0                          [stack:2404]
7f880ed4c000-7f880edf8000 r--p 00000000 08:08 5968                       /usr/share/fonts/dejavu/DejaVuSans-Bold.ttf
7f880edf8000-7f880edf9000 ---p 00000000 00:00 0 
7f880edf9000-7f880f5f9000 rw-p 00000000 00:00 0                          [stack:2397]
7f880f5f9000-7f880f5fa000 ---p 00000000 00:00 0 
7f880f5fa000-7f880fdfa000 rw-p 00000000 00:00 0                          [stack:2396]
7f880fdfa000-7f880fdff000 r-xp 00000000 08:08 393244                     /lib64/libnss_dns-2.23.so
7f880fdff000-7f880fffe000 ---p 00005000 08:08 393244                     /lib64/libnss_dns-2.23.so
7f880fffe000-7f880ffff000 r--p 00004000 08:08 393244                     /lib64/libnss_dns-2.23.so
7f880ffff000-7f8810000000 rw-p 00005000 08:08 393244                     /lib64/libnss_dns-2.23.so
7f8810000000-7f8810029000 rw-p 00000000 00:00 0 
7f8810029000-7f8814000000 ---p 00000000 00:00 0 
7f8814000000-7f8814021000 rw-p 00000000 00:00 0 
7f8814021000-7f8818000000 ---p 00000000 00:00 0 
7f8818000000-7f8818021000 rw-p 00000000 00:00 0 
7f8818021000-7f881c000000 ---p 00000000 00:00 0 
7f881c000000-7f881c021000 rw-p 00000000 00:00 0 
7f881c021000-7f8820000000 ---p 00000000 00:00 0 
7f8820000000-7f8820021000 rw-p 00000000 00:00 0 
7f8820021000-7f8824000000 ---p 00000000 00:00 0 
7f8824000000-7f8824021000 rw-p 00000000 00:00 0 
7f8824021000-7f8828000000 ---p 00000000 00:00 0 
7f8828080000-7f882809f000 r--s 00000000 08:08 3034191                    /usr/share/mime/mime.cache
7f882815f000-7f882835f000 rw-s 00000000 00:11 20381                      /dev/shm/.org.chromium.Chromium.O1rzz7 (deleted)
7f882835f000-7f8828360000 ---p 00000000 00:00 0 
7f8828360000-7f8828b60000 rw-p 00000000 00:00 0                          [stack:2393]
7f8829124000-7f88291a5000 rw-s 00000000 08:08 1723126                    /root/.cache/qupzilla/default/Cache/index
7f88291a5000-7f8829ba5000 rwxp 00000000 00:00 0 
7f8829bb2000-7f8829bd1000 r--s 00000000 08:08 3034191                    /usr/share/mime/mime.cache
7f8829bd1000-7f8829bea000 r--p 00000000 08:08 2894832                    /usr/share/locale/tr/LC_MESSAGES/glib20.mo
7f8829bea000-7f8829c2a000 rw-s 107513000 00:06 12819                     /dev/dri/card0
7f8829c42000-7f8829c6a000 rw-s 00000000 00:05 2490388                    /SYSV00000000 (deleted)
7f8829dea000-7f8829df5000 r-xp 00000000 08:08 393246                     /lib64/libnss_files-2.23.so
7f8829df5000-7f8829ff4000 ---p 0000b000 08:08 393246                     /lib64/libnss_files-2.23.so
7f8829ff4000-7f8829ff5000 r--p 0000a000 08:08 393246                     /lib64/libnss_files-2.23.so
7f8829ff5000-7f8829ff6000 rw-p 0000b000 08:08 393246                     /lib64/libnss_files-2.23.so
7f8829ff6000-7f8829ffc000 rw-p 00000000 00:00 0 
7f8829ffc000-7f8829ffd000 ---p 00000000 00:00 0 
7f8829ffd000-7f882a7fd000 rw-p 00000000 00:00 0                          [stack:2381]
7f882a7fd000-7f882a7fe000 ---p 00000000 00:00 0 
7f882a7fe000-7f882affe000 rw-p 00000000 00:00 0                          [stack:2380]
7f882affe000-7f882afff000 ---p 00000000 00:00 0 
7f882afff000-7f882b7ff000 rw-p 00000000 00:00 0                          [stack:2379]
7f882b7ff000-7f882b800000 ---p 00000000 00:00 0 
7f882b800000-7f882c000000 rw-p 00000000 00:00 0                          [stack:2378]
7f882c000000-7f882c021000 rw-p 00000000 00:00 0 
7f882c021000-7f8830000000 ---p 00000000 00:00 0 
7f8830000000-7f8830021000 rw-p 00000000 00:00 0 
7f8830021000-7f8834000000 ---p 00000000 00:00 0 
7f8834000000-7f8834185000 rw-p 00000000 00:00 0 
7f8834185000-7f8838000000 ---p 00000000 00:00 0 
7f8838000000-7f8838021000 rw-p 00000000 00:00 0 
7f8838021000-7f883c000000 ---p 00000000 00:00 0 
7f883c000000-7f883c021000 rw-p 00000000 00:00 0 
7f883c021000-7f8840000000 ---p 00000000 00:00 0 
7f884000e000-7f884008e000 rw-s 104bfb000 00:06 12819                     /dev/dri/card0
7f884008e000-7f8840097000 r-xp 00000000 08:08 2773510                    /usr/lib/qt5/plugins/iconengines/libqsvgicon.so
7f8840097000-7f8840296000 ---p 00009000 08:08 2773510                    /usr/lib/qt5/plugins/iconengines/libqsvgicon.so
7f8840296000-7f8840297000 rw-p 00008000 08:08 2773510                    /usr/lib/qt5/plugins/iconengines/libqsvgicon.so
7f8840297000-7f88402d4000 r-xp 00000000 08:08 2773483                    /usr/lib/qt5/plugins/bearer/libqnmbearer.so
7f88402d4000-7f88404d3000 ---p 0003d000 08:08 2773483                    /usr/lib/qt5/plugins/bearer/libqnmbearer.so
7f88404d3000-7f88404d5000 rw-p 0003c000 08:08 2773483                    /usr/lib/qt5/plugins/bearer/libqnmbearer.so
7f88404d5000-7f88404ea000 r-xp 00000000 08:08 2773485                    /usr/lib/qt5/plugins/bearer/libqgenericbearer.so
7f88404ea000-7f88406e9000 ---p 00015000 08:08 2773485                    /usr/lib/qt5/plugins/bearer/libqgenericbearer.so
7f88406e9000-7f88406ea000 rw-p 00014000 08:08 2773485                    /usr/lib/qt5/plugins/bearer/libqgenericbearer.so
7f88406ea000-7f8840720000 r-xp 00000000 08:08 2773484                    /usr/lib/qt5/plugins/bearer/libqconnmanbearer.so
7f8840720000-7f884091f000 ---p 00036000 08:08 2773484                    /usr/lib/qt5/plugins/bearer/libqconnmanbearer.so
7f884091f000-7f8840921000 rw-p 00035000 08:08 2773484                    /usr/lib/qt5/plugins/bearer/libqconnmanbearer.so
7f8840921000-7f8840922000 ---p 00000000 00:00 0 
7f8840922000-7f8841122000 rw-p 00000000 00:00 0                          [stack:2376]
7f8841122000-7f884114d000 r-xp 00000000 08:08 2772046                    /usr/lib/libvorbis.so.0.4.8
7f884114d000-7f884134c000 ---p 0002b000 08:08 2772046                    /usr/lib/libvorbis.so.0.4.8
7f884134c000-7f884134d000 rw-p 0002a000 08:08 2772046                    /usr/lib/libvorbis.so.0.4.8
7f884134d000-7f8841353000 r-xp 00000000 08:08 2772033                    /usr/lib/libogg.so.0.8.2
7f8841353000-7f8841552000 ---p 00006000 08:08 2772033                    /usr/lib/libogg.so.0.8.2
7f8841552000-7f8841553000 rw-p 00005000 08:08 2772033                    /usr/lib/libogg.so.0.8.2
7f8841553000-7f88415e0000 r-xp 00000000 08:08 2772045                    /usr/lib/libvorbisenc.so.2.0.11
7f88415e0000-7f88417df000 ---p 0008d000 08:08 2772045                    /usr/lib/libvorbisenc.so.2.0.11
7f88417df000-7f88417fb000 rw-p 0008c000 08:08 2772045                    /usr/lib/libvorbisenc.so.2.0.11
7f88417fb000-7f88417fc000 ---p 00000000 00:00 0 
7f88417fc000-7f8841ffc000 rw-p 00000000 00:00 0                          [stack:2377]
7f8841ffc000-7f8841ffd000 ---p 00000000 00:00 0 
7f8841ffd000-7f88427fd000 rw-p 00000000 00:00 0                          [stack:2373]
7f88427fd000-7f88427fe000 ---p 00000000 00:00 0 
7f88427fe000-7f8842ffe000 rw-p 00000000 00:00 0                          [stack:2372]
7f8842ffe000-7f8842fff000 ---p 00000000 00:00 0 
7f8842fff000-7f88437ff000 rw-p 00000000 00:00 0                          [stack:2371]
7f88437ff000-7f8843800000 ---p 00000000 00:00 0 
7f8843800000-7f8844000000 rw-p 00000000 00:00 0                          [stack:2370]
7f8844000000-7f8844083000 rw-p 00000000 00:00 0 
7f8844083000-7f8848000000 ---p 00000000 00:00 0 
7f8848000000-7f884809e000 rw-p 00000000 00:00 0 
7f884809e000-7f884c000000 ---p 00000000 00:00 0 
7f884c000000-7f884c021000 rw-p 00000000 00:00 0 
7f884c021000-7f8850000000 ---p 00000000 00:00 0 
7f8850000000-7f8850021000 rw-p 00000000 00:00 0 
7f8850021000-7f8854000000 ---p 00000000 00:00 0 
7f8854000000-7f8854021000 rw-p 00000000 00:00 0 
7f8854021000-7f8858000000 ---p 00000000 00:00 0 
7f8858000000-7f8858021000 rw-p 00000000 00:00 0 
7f8858021000-7f885c000000 ---p 00000000 00:00 0 
7f885c000000-7f885c021000 rw-p 00000000 00:00 0 
7f885c021000-7f8860000000 ---p 00000000 00:00 0 
7f8860000000-7f8860021000 rw-p 00000000 00:00 0 
7f8860021000-7f8864000000 ---p 00000000 00:00 0 
7f8864016000-7f8864117000 rw-p 00000000 00:00 0 
7f8864117000-7f886418b000 r-xp 00000000 08:08 2772293                    /usr/lib/libFLAC.so.8.3.0
7f886418b000-7f886438a000 ---p 00074000 08:08 2772293                    /usr/lib/libFLAC.so.8.3.0
7f886438a000-7f886438c000 rw-p 00073000 08:08 2772293                    /usr/lib/libFLAC.so.8.3.0
7f886438c000-7f8864390000 r-xp 00000000 08:08 2099110                    /lib/libcap.so.2.25
7f8864390000-7f8864590000 ---p 00004000 08:08 2099110                    /lib/libcap.so.2.25
7f8864590000-7f8864591000 rw-p 00004000 08:08 2099110                    /lib/libcap.so.2.25
7f8864591000-7f88645f2000 r-xp 00000000 08:08 2772301                    /usr/lib/libsndfile.so.1.0.25
7f88645f2000-7f88647f2000 ---p 00061000 08:08 2772301                    /usr/lib/libsndfile.so.1.0.25
7f88647f2000-7f88647f5000 rw-p 00061000 08:08 2772301                    /usr/lib/libsndfile.so.1.0.25
7f88647f5000-7f88647f9000 rw-p 00000000 00:00 0 
7f88647f9000-7f88647fa000 ---p 00000000 00:00 0 
7f88647fa000-7f8864ffa000 rw-p 00000000 00:00 0                          [stack:2369]
7f8864ffa000-7f8864ffb000 ---p 00000000 00:00 0 
7f8864ffb000-7f88657fb000 rw-p 00000000 00:00 0                          [stack:2368]
7f88657fb000-7f88657fc000 ---p 00000000 00:00 0 
7f88657fc000-7f8865ffc000 rw-p 00000000 00:00 0                          [stack:2367]
7f8865ffc000-7f8865ffd000 ---p 00000000 00:00 0 
7f8865ffd000-7f88667fd000 rw-p 00000000 00:00 0                          [stack:2366]
7f88667fd000-7f88667fe000 ---p 00000000 00:00 0 
7f88667fe000-7f8866ffe000 rw-p 00000000 00:00 0                          [stack:2365]
7f8866ffe000-7f8866fff000 ---p 00000000 00:00 0 
7f8866fff000-7f88677ff000 rw-p 00000000 00:00 0                          [stack:2364]
7f88677ff000-7f8867800000 ---p 00000000 00:00 0 
7f8867800000-7f8868000000 rw-p 00000000 00:00 0                          [stack:2363]
7f8868000000-7f8868021000 rw-p 00000000 00:00 0 
7f8868021000-7f886c000000 ---p 00000000 00:00 0 
7f886c000000-7f886c021000 rw-p 00000000 00:00 0 
7f886c021000-7f8870000000 ---p 00000000 00:00 0 
7f8870000000-7f88700e2000 rw-p 00000000 00:00 0 
7f88700e2000-7f8874000000 ---p 00000000 00:00 0 
7f887400f000-7f887402f000 rw-s 00000000 00:11 21111                      /dev/shm/.org.chromium.Chromium.W4JiHJ (deleted)
7f887402f000-7f8874070000 rw-s 00000000 08:08 1445000                    /root/.config/qupzilla/profiles/default/GPUCache/index
7f8874070000-7f88740d0000 rw-s 00000000 00:05 2424853                    /SYSV00000000 (deleted)
7f88740d0000-7f8874189000 r--p 00000000 08:08 5976                       /usr/share/fonts/dejavu/DejaVuSans.ttf
7f8874189000-7f8874204000 r-xp 00000000 08:08 2766498                    /usr/lib/pulseaudio/libpulsecommon-7.1.so
7f8874204000-7f8874403000 ---p 0007b000 08:08 2766498                    /usr/lib/pulseaudio/libpulsecommon-7.1.so
7f8874403000-7f8874406000 rw-p 0007a000 08:08 2766498                    /usr/lib/pulseaudio/libpulsecommon-7.1.so
7f8874406000-7f8874454000 r-xp 00000000 08:08 2772324                    /usr/lib/libpulse.so.0.18.2
7f8874454000-7f8874653000 ---p 0004e000 08:08 2772324                    /usr/lib/libpulse.so.0.18.2
7f8874653000-7f8874655000 rw-p 0004d000 08:08 2772324                    /usr/lib/libpulse.so.0.18.2
7f8874655000-7f8874656000 ---p 00000000 00:00 0 
7f8874656000-7f8874e56000 rw-p 00000000 00:00 0                          [stack:2362]
7f8874e56000-7f8874e57000 ---p 00000000 00:00 0 
7f8874e57000-7f8875657000 rw-p 00000000 00:00 0                          [stack:2361]
7f8875659000-7f8875663000 r-xp 00000000 08:08 2772285                    /usr/lib/libjson-c.so.2.0.1
7f8875663000-7f8875862000 ---p 0000a000 08:08 2772285                    /usr/lib/libjson-c.so.2.0.1
7f8875862000-7f8875863000 rw-p 00009000 08:08 2772285                    /usr/lib/libjson-c.so.2.0.1
7f8875863000-7f8875864000 ---p 00000000 00:00 0 
7f8875864000-7f8876064000 rw-p 00000000 00:00 0                          [stack:2360]
7f8876064000-7f8876065000 ---p 00000000 00:00 0 
7f8876065000-7f8876865000 rw-p 00000000 00:00 0                          [stack:2358]
7f8876865000-7f88768ea000 r--s 00000000 08:08 2898976                    /usr/share/qt5/resources/qtwebengine_resources_200p.pak
7f88768ea000-7f8876f68000 r--s 00000000 08:08 2898977                    /usr/share/qt5/resources/qtwebengine_resources.pak
7f8876f68000-7f8877924000 r--s 00000000 08:08 2898975                    /usr/share/qt5/resources/icudtl.dat
7f8877924000-7f88779ec000 r-xp 00000000 08:08 2769230                    /usr/lib/libsqlite3.so.0.8.6
7f88779ec000-7f8877bec000 ---p 000c8000 08:08 2769230                    /usr/lib/libsqlite3.so.0.8.6
7f8877bec000-7f8877bf1000 rw-p 000c8000 08:08 2769230                    /usr/lib/libsqlite3.so.0.8.6
7f8877bf1000-7f8877bfe000 r-xp 00000000 08:08 2773497                    /usr/lib/qt5/plugins/sqldrivers/libqsqlite.so
7f8877bfe000-7f8877dfe000 ---p 0000d000 08:08 2773497                    /usr/lib/qt5/plugins/sqldrivers/libqsqlite.so
7f8877dfe000-7f8877dff000 rw-p 0000d000 08:08 2773497                    /usr/lib/qt5/plugins/sqldrivers/libqsqlite.so
7f8877dff000-7f8877e04000 r-xp 00000000 08:08 2773535                    /usr/lib/qt5/plugins/imageformats/libqwebp.so
7f8877e04000-7f8878003000 ---p 00005000 08:08 2773535                    /usr/lib/qt5/plugins/imageformats/libqwebp.so
7f8878003000-7f8878004000 rw-p 00004000 08:08 2773535                    /usr/lib/qt5/plugins/imageformats/libqwebp.so
7f8878004000-7f8878009000 r-xp 00000000 08:08 2773538                    /usr/lib/qt5/plugins/imageformats/libqwbmp.so
7f8878009000-7f8878208000 ---p 00005000 08:08 2773538                    /usr/lib/qt5/plugins/imageformats/libqwbmp.so
7f8878208000-7f8878209000 rw-p 00004000 08:08 2773538                    /usr/lib/qt5/plugins/imageformats/libqwbmp.so
7f8878209000-7f8878278000 r-xp 00000000 08:08 2771704                    /usr/lib/libtiffİptal edildi

**Comment by cranes-bill** [comment]
Perhaps similar as: #2033 & #1842
