### ISSUE TITLE
No thumbnail preview for pictures when uploading files in version 2.0.1

### ISSUE THREAD

**Issue by rsmaior** [QupZilla/qupzilla#2050]
I don't know if this should be considered a bug or feature request, but I really like QupZilla and this is a feature that make a big difference when you are uploading many pictures from a directory full of them to sites like facebook etc.

My about:
Application version 2.0.1
QtWebEngine version 5.7.0
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QupZilla/2.0.1 Chrome/49.0.2623.111 Safari/537.36

**Comment by rsmaior** [comment]
With 2.2.0 it is yet not there.

Application version 2.2.0
QtWebEngine version 5.9.1
© 2010-2017 David Rosca
https://www.qupzilla.com
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QupZilla/2.2.0 Chrome/56.0.2924.122 Safari/537.36

**Comment by nowrep** [comment]
File picker is provided by the Qt platform plugin. KDE file picker supports image previews.
