### ISSUE TITLE
Userstyles don't load in most cases

### ISSUE THREAD

**Issue by maxigaz** [QupZilla/qupzilla#2053]
In Qupzilla 2.0.1 (Qt version 5.7.0) under Manjaro Linux, user styles don’t load in many cases. (I installed them by going to userstyles.org and clicking on "install this style as a user script".)

So, for example, the theme [GitHub Dark](https://userstyles.org/styles/37035/github-dark) works when I start the browser, but after a few minutes of browsing, it somehow stops working. I often notice that it works in one tab, even after several page reloads, but it doesn’t work in another (even when the exact same page is displayed in both tabs).

However, other styles like [Vector IM Dark Theme](https://userstyles.org/styles/124155/vector-im-dark-theme) and [Manjaro Forums Dark Theme](https://userstyles.org/styles/128016/manjaro-forums-dark-theme-discourse-wip) never seem to work for me, no matter what I do.

**Comment by nibogd** [comment]
Same thing happens for me. Now trying to figure out, is it incompatibility between userscripts? Because IITC (user-script for ingress.com/intel) always works. Some userstyles work better, some worse.

**Comment by nowrep** [comment]
Should work now, GreaseMonkey compatibility was improved a lot.
