### ISSUE TITLE
QupZilla 2.0.1 crashes shortly after starting on Fedora 24 KDE

### ISSUE THREAD

**Issue by lukasz-r** [QupZilla/qupzilla#2057]
QupZilla crashes each time shortly after being launched on Fedora 24 KDE. This seems to be related to nouveau driver.

Details:
64-bit Fedora 24
QupZilla 2.0.1
qt5-qtwebkit.x86_64 5.6.1-3.b889f46git.fc24
qt5-qtwebengine 5.6.1-3.fc24
plasmashell 5.7.3

Crash log:
https://gist.github.com/lukasz-r/919f23871fe32620b900c54f1b47be9b

System log realted to QupZilla:
https://gist.github.com/lukasz-r/185695363092e3cd42f3170887d8b413

**Comment by benkohler** [comment]
Might be the same as issue 2046 which appears to be an upstream nouveau problem https://bugs.freedesktop.org/show_bug.cgi?id=91632

**Comment by nowrep** [comment]
Workaround is to run `qupzilla --disable-gpu`

**Comment by lukasz-r** [comment]
Thanks a lot for your help. It's indeed nouveau problem.

Few days back I switched to rpmfusion-nvidia driver which blacklisted nouveau, and QupZilla runs flawlessly.
