### ISSUE TITLE
tab switcher

### ISSUE THREAD

**Issue by begin29** [QupZilla/qupzilla#2063]
I love this browser, because it is fast. 
But is it possible to add tab switcher like extension for chrome(see screenshot)? It would be nice to have that one for quick switch between lot of tabs.
![screenshot from 2016-08-24 09-48-16](https://cloud.githubusercontent.com/assets/4425383/17920948/0c7ef5c0-69e0-11e6-873f-033d3b85bf36.png)

**Comment by cranes-bill** [comment]
What about **_Tab manager_**?

**Comment by begin29** [comment]
@cranes-bill  cool plugin, but it doesn't have search and quick switch. All should be done via mouse. Opened issue about that.

**Comment by srazi** [comment]
@begin29  Adding a search-bar to Tab Manager should be enough? And what do you mean by `quick switch`?

**Comment by begin29** [comment]
@srazi, I mean when you can tap key bind -> switch to search field -> search needed tab title -> press Enter -> see that active tab. 
Now I see that I should double click via mouse on each element for open it.

**Comment by begin29** [comment]
@srazi, great work! 
tnx, but how to update my plugin? It is still shows as 0.5 instead (0.6) version.
I tried to purge and install qupzilla again.

**Comment by srazi** [comment]
@begin29 You have to get latest QupZilla source code and compile it or wait until releasing next version.

**Comment by begin29** [comment]
@srazi, great. Tnx a lot!
