### ISSUE TITLE
QupZilla uninstaller appears to scan entire registry

### ISSUE THREAD

**Issue by airways** [QupZilla/qupzilla#2067]
The QupZilla uninstaller appears to scan the system's entire registry (or a massive subset of it) for some reason. This is very inefficient and takes a very, very long time to complete on my machine.

![image](https://cloud.githubusercontent.com/assets/64338/17942722/311d44fe-69fe-11e6-9a55-9ec481bfefd9.png)

It's also unclear what it is actually doing during this scan. Hopefully it is not actually modifying all of these items, though it is a bit alarming that these isn't even a message such as "searching for classes to unregister" which I assume is what it's actually doing.

There must be a better way to remove registered COM classes or perform whatever action it is trying to do than this.

**Comment by nowrep** [comment]
This should now be fixed.
