### ISSUE TITLE
Hide tabs title

### ISSUE THREAD

**Issue by dead-crow** [QupZilla/qupzilla#2071]
Hi,
I'm not sure if its the right place to post , sorry if i did wrong .
I would like to hide the title of tabs to just have the icon left , but there is no extension for this .
I know its possible with firefox's add-on "tab mix plus", but i would like to do it with qupzilla .

Also, i'm newbie at scripting .

**Comment by nowrep** [comment]
You can now change size of tabs 678b513820f57fbfc75fcb6facf34020f6e70733
