### ISSUE TITLE
Crashing and Freezing Almost Immediately

### ISSUE THREAD

**Issue by CaptainKraft** [QupZilla/qupzilla#2075]
When I open Qupzilla, if I do nothing, the browser seems to be fine. If I open a new tab, restore old tabs, start new session and ignore old tabs, navigate to a webpage, move the mouse over some element, etc. the browser either freezes or crashes.

I saved the output from 3 different kinds of crashes to txt files and attached them here. The first is from opening a tab, the second is from going to a website, and the third is from hovering over an option in the 'Windows and Tabs' window after a crash that asks me to restore my tabs.

I have also attached the crashlog that Qupzilla created.

I'm on 64bit Arch Linux with an 'NVIDIA Corporation GM206, GeForce GTX 960 (rev a1)' and an 'Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz'

Note: I have two other machines where Qupzilla works fine. They both use 64bit Arch Linux but one has an AMD CPU and GPU and the other has an Intel CPU and laptop GPU. All three of my machines have nearly the same setup in Arch.

[qupzilla-crash01.txt](https://github.com/QupZilla/qupzilla/files/462617/qupzilla-crash01.txt)
[qupzilla-crash02.txt](https://github.com/QupZilla/qupzilla/files/462616/qupzilla-crash02.txt)
[qupzilla-crash03.txt](https://github.com/QupZilla/qupzilla/files/462615/qupzilla-crash03.txt)
[Crash-2016-09-08T15:21:12.txt](https://github.com/QupZilla/qupzilla/files/462618/Crash-2016-09-08T15.21.12.txt)

**Comment by cranes-bill** [comment]
Workaround provided: #2057 & #2046

Similar: #2033, #2038, #1842

**Comment by CaptainKraft** [comment]
Thanks.
