### ISSUE TITLE
U2F support for universal 2nd factor authentication

### ISSUE THREAD

**Issue by nartamonov** [QupZilla/qupzilla#2076]
Since qupzilla is based on QtWebEngine which is based on Chromium, does qupzilla support [U2F specification](https://www.yubico.com/about/background/fido/), i.e. universal 2nd factor authentication for web applications? U2F becoming popular nowadays and supported by Google services, Dropbox, GitHub, Gitlab, and so on: see [detailed statistics](http://www.dongleauth.info/).

**Comment by The-Compiler** [comment]
QtWebEngine doesn't support U2F - I opened [QTBUG-54720](https://bugreports.qt.io/browse/QTBUG-54720) ~2 months ago requesting it to be added. I suggest you vote for that bug :wink:

**Comment by nartamonov** [comment]
@The-Compiler thanks! Voted :+1:
