### ISSUE TITLE
Speed Dial Not Visible on Refresh

### ISSUE THREAD

**Issue by CaptainKraft** [QupZilla/qupzilla#2078]
When refreshing the speed dial page, links disappear. The settings and + button remain but adding any new speed dial links does nothing.

The only message I get at the console when refreshing the page
- Uncaught ReferenceError: qt is not defined

I'm on Arch Linux 64bit

**Comment by AcarBurak** [comment]
Same here on the same system. And it occurs when I close the last tab as well, instead of speed dial I see a blank page.

**Comment by nowrep** [comment]
Bug in QtWebEngine 5.7

**Comment by nowrep** [comment]
This is now fixed.
