### ISSUE TITLE
Changing qupzilla:start search provider?

### ISSUE THREAD

**Issue by Chromace** [QupZilla/qupzilla#2081]
Is there a way to change the search provider used in QupZilla's default homepage (DuckDuckGo) to alternative ones? Thank-you.

**Comment by cranes-bill** [comment]
**Preferences** »» **Other** »» **Search Engines Manager** 
Or click over search engine icon on the search bar and choose: _Manage Search Engines_
**NOTE**: You can add more search engines.

**Comment by Chromace** [comment]
Apologies, I meant whether it was possible to change the search engine which Qupzilla uses in the image below away from DuckDuckGo (default homepage). I hoped that setting a default search engine would modify it, but unfortunately not...

![screenshot_20160914_012325](https://cloud.githubusercontent.com/assets/16624211/18479978/7d9bde62-79c6-11e6-8af1-3c1d1e32deef.png)

**Comment by Chromace** [comment]
Never mind, there's a way around this. If I set my homepage to the speed-dial, it automatically places my cursor in the address bar, so I get the search engine I prefer rather than clicking on it first (as it is with the original home page).

Apologies for the disruption.

**Comment by cranes-bill** [comment]
Actually i apologise, because i did not read the title and the question carefully, as well as for my very bad English, sorry!

**Comment by nowrep** [comment]
There is no option to change and it won't be. If you really want to change it, you can use custom start page.
