### ISSUE TITLE
Q: External deps, ex. with SSL distribution changes, before a QupZilla release

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla#2085]
@nowrep
Sooo... since I'm currently the OS X compiler... and when OpenSSL or some other external dependencies releases a new release *(like now [here with OpenSSL](https://github.com/openssl/openssl/releases/tag/OpenSSL_1_0_2j))*.. how did you want to handle this with QupZilla?

If updated we should probably do this for all active distributions not just OS X.

**Comment by nowrep** [comment]
I usually update the external dependencies (OpenSSL in Windows builds) with new QupZilla release, unless there is a need to do it sooner.

**Comment by Martii** [comment]
I'm back from vacation now. 

Okee dokee. Will mirror your actions on release for now *(hopefully I don't add my OS X box to any other projects or we'll probably run into some issues if those use newer OpenSSL releases)*... I'll assume at the date of release here to match at or earlier than the release here.

Thanks.

**Comment by Martii** [comment]
Btw XCode is up to v8.0.0 and while I was on vacation I saw a Mac that had a newer OS X minor version... running those updates now.

**Comment by Martii** [comment]
Oh fun... not! https://forum.qt.io/topic/71119/project-error-xcode-not-set-up-properly/2

No solution is working yet... may have to wait till 5.7.1 and/or dig up the old Xcode. Apple really likes to mess things up with EULAs.

**Comment by Martii** [comment]
Retried above link recommendations and it seems to have self healed for compiling from the CLI. QtCreator is still showing the message though.

**Comment by Martii** [comment]
@nowrep 
Looks like Qt 5.6.2 came out about a week ago. Did you want me to rebuild the OS X package at 521d058 ? I still haven't gone to Sierra yet as well but Xcode is at 8 on that machine.

**Comment by Martii** [comment]
@nowrep 
Which Qt do you want for OS X? Qt 5.6.x or Qt 5.7.x

As far as openSSL is concerned brew just install 1.0.2j so that's already been asked.

**Comment by nowrep** [comment]
5.6.2 will be best for now. Thanks
