### ISSUE TITLE
2.0.1 - Win7 - Download Manager - Fonts Unreadable

### ISSUE THREAD

**Issue by Geyup** [QupZilla/qupzilla#2087]
I'm using Windows 7 SP1 x64 with Qupzilla 2.0.1

I noticed the fonts at the bottom of the window for the time, is not legible.

It looks all run together.

Is there something I can do on my end to fix this, maybe a different font in the preferences, if so, which?

![qupzilla](https://cloud.githubusercontent.com/assets/13072581/18936334/08158fb4-85d6-11e6-84ae-4be798c5fd3b.jpg)

**Comment by Geyup** [comment]
After making the post, I went back and started playing with different fonts in the different sections, not sure it's helping, but I did notice a pattern this time.

When I first start the download the fonts are legible., but as the download size and time change, I noticed the fonts starting writing over themselves, this is what causes this blurred look.

Looks like a bug, needs fixing, I hope soon PLEASE!

**Comment by cranes-bill** [comment]
#1906 #1931
