### ISSUE TITLE
Question: Windows Installers?

### ISSUE THREAD

**Issue by Geyup** [QupZilla/qupzilla#2088]
The download section for Windows says this;

32bit and 64bit Windows installers can be downloaded by clicking on links below

The word ```Installers``` caught my attention, there is only one installer, so I'm assuming this is correct for both 32x & 64x?

**Comment by nowrep** [comment]
Yes, there is only one installer now - 32bit. The wording on the site is from the times where there were separate installers.
Site issues should be reported at QupZilla/qupzilla.com
