### ISSUE TITLE
qupzilla plugins

### ISSUE THREAD

**Issue by trazomtg** [QupZilla/qupzilla#2090]
Hi,

i have just downloaded qupzilla and it seems to be very attractive.
But i 'd like to know where i can find some plugins and how to install them.
I have only 8 plugins in Qupzilla preference and no way to find others.
Thanks for your help
TG

**Comment by Martii** [comment]
AFAIK you may build your own plugins in C++... if you want to see if they can be distributed you submit a pull request either [here for main distribution](https://github.com/QupZilla/qupzilla) in [the plugins folder](https://github.com/QupZilla/qupzilla/tree/master/src/plugins) or [here](https://github.com/QupZilla/qupzilla-plugins/tree/master/plugins). If it's simple enough a GreaseMonkey Userscript should do the trick.

**Comment by trazomtg** [comment]
i understand but people have certainly wrotten a lot of plugins, like in Firefox. Do you say we can't load this plugins but we must write our owns plugins?

**Comment by Chiitoo** [comment]
Indeed, it's currently not possible (see for example [FAQ 13](https://github.com/QupZilla/qupzilla/wiki/FAQ#13-does-qupzilla-support-firefox-and-or-chrome-extensions)).

While I believe that was written with QtWebKit in mind, it more or less rings true for the QtWebEngine version of QupZilla as well.

Things might change soon(er or later though), depending on QtWebEngine (see for example [QTBUG-51185](https://bugreports.qt.io/browse/QTBUG-51185)).
