### ISSUE TITLE
Native names for the languages "zh-HK" and "zh-TW"

### ISSUE THREAD

**Issue by hakking** [QupZilla/qupzilla#2091]
I am start working for the "zh-HK" translation of QupZilla at Transifex, and I want to change the page "qupzilla.com/footer.php".

In the part "Available page translations", please add a line:
< li >< a href="?lang=zh-hk" >香港正體字< /a >< /li >

In the part "Available page translations", please also modify the line to:
< li >< a href="?lang=zh-tw" >正體中文< /a >< /li >

If any other part of QupZilla Software shows the native name of languages, please also apply these two native names for "zh-HK" and "zh-TW" respectively.

**Comment by nowrep** [comment]
Can you please open pull request for https://github.com/QupZilla/qupzilla.com ?
Language names are here: https://github.com/QupZilla/qupzilla.com/blob/master/footer.php#L22

**Comment by hakking** [comment]
Sorry, I may not be allowed to open pull at github.com/QupZilla/qupzilla.com. But I posted this issue once again there.

**Comment by nowrep** [comment]
Ok, I'll close the bug here.
