### ISSUE TITLE
Searching "royal palace of madrid" on Google crashes Qupzilla.

### ISSUE THREAD

**Issue by j-koreth** [QupZilla/qupzilla#2096]
I am on openSUSE Linux Tumbleweed and currently have tested out with a few extensions enabled and with a brand new blank profile and have crashed on both.

It crashes everytime on my end.

**Comment by Martii** [comment]
Any particular search engine?

Refs:
* ![royalpalaceofmadridlinux](https://cloud.githubusercontent.com/assets/114709/19326101/6106c470-9086-11e6-8872-e4efbd03057f.png)

**Comment by j-koreth** [comment]
On Wednesday, October 12, 2016 1:16:37 PM CDT Marti Martz wrote:
> Any particular search engine?
> 
> Refs:
> *
> ![royalpalaceofmadridlinux](https://cloud.githubusercontent.com/assets/1147
> 09/19326101/6106c470-9086-11e6-8872-e4efbd03057f.png)

Google (In the Title)
I have switched to duckduckgo right now but I find it rather slow today. Is 
this normal?

**Comment by Martii** [comment]
> I have switched to duckduckgo right now but I find it rather slow today. Is this normal?

Seems speedy to me on my network platforms. I'll d/l Tumbleweed and add it to my VMs for a direct test since Suse isn't one that I normally have.

**Comment by Martii** [comment]
And whoops sorry about the subject line miss... will try there.

**Comment by Martii** [comment]
Test with Google:
* Linux **PASS**
* OS X **PASS**
* Win64 **PASS**

**Comment by j-koreth** [comment]
Well that's odd... Any idea why it is this way for me? I have version 2.0.1 and Qt version 5.7.0. Is there any way I can help?

**Comment by ericjs** [comment]
If you are getting a crash on a particular search term, and not on others, I would assume that it is something in one particular search result (or Google ad) coming back that is causing the crash. Someone else doing the same search may see different results (and ads).

**Comment by Martii** [comment]
@j-koreth 
Can you start QupZilla from the terminal and see if you get any console messages? Debugging symbols aren't usually turned on but at least a trace might be available.

@ericjs
Yah that is my guess too.

**Comment by Martii** [comment]
Bahhh OpenSUSE tumbleweed has a known issue of not working in VMs... time for "Leap"... should have checked this before downloading.

**Comment by Martii** [comment]
@j-koreth 
> Any idea why it is this way for me? I have version 2.0.1 and Qt version 5.7.0.

Building current HEAD with Qt 5.7.0 on OpenSUSE 42.1 "Leap" *(VM)* doesn't crash with Google and that search criteria. It's probably some ad as was already mentioned. I can checkout current release here *(2.0.1 which is older than the current HEAD)* if you would like but it's probably going to be the same results."TumbleWeed" *(a rolling release distro)* is not currently compatible with my current VM version software so this is as close as I can get to your exact platform.

`zypper` tried to install 1.8.9 of QupZilla so that went away rather quickly and I just compiled from source here with Qt's direct Linux universal installer, package development openSSL, and package development xcb.

**Comment by nowrep** [comment]
Can you please post backtrace?

**Comment by j-koreth** [comment]
Sorry to keep you guys waiting.

This crashing is worse than I thought and it happens on various other google pages and one that I seen happen consistently is on gsmarena.com/compare. 

I have tried nuking all Qupzilla found in the config info and reinstalling it; no luck.

Would this be related to an updated Mesa or something else specific to Tumbleweed since it's rolling release?

Backtrace - 
Time: Thu Oct 13 21:34:23 2016
Qt version: 5.7.0 (compiled with 5.7.0)
QupZilla version: 2.0.1
Rendering engine: QtWebEngine

============== BACKTRACE ==============
#0: qupzilla() [0x403912]
#1: /lib64/libc.so.6(+0x34650) [0x7f177d560650]
#2: /usr/lib64/libQt5WebEngineCore.so.5(+0x681d76) [0x7f177f42dd76]
#3: /usr/lib64/libQt5WebEngineCore.so.5(+0x1363931) [0x7f178010f931]
#4: /usr/lib64/libQt5WebEngineCore.so.5(+0x12e006d) [0x7f178008c06d]
#5: /usr/lib64/libQt5WebEngineCore.so.5(+0x1365b3a) [0x7f1780111b3a]
#6: /usr/lib64/libQt5WebEngineCore.so.5(+0x1261b76) [0x7f178000db76]
#7: /usr/lib64/libQt5WebEngineCore.so.5(+0x1262d32) [0x7f178000ed32]
#8: /usr/lib64/libQt5WebEngineCore.so.5(+0x1263068) [0x7f178000f068]
#9: /usr/lib64/libQt5WebEngineCore.so.5(+0x1263490) [0x7f178000f490]
#10: /usr/lib64/libQt5WebEngineCore.so.5(+0x1453ba7) [0x7f17801ffba7]
#11: /usr/lib64/libQt5WebEngineCore.so.5(+0x14542d2) [0x7f17802002d2]
#12: /usr/lib64/libQt5WebEngineCore.so.5(+0x1245bc5) [0x7f177fff1bc5]
#13: /usr/lib64/libQt5WebEngineCore.so.5(+0x1245e1e) [0x7f177fff1e1e]
#14: /usr/lib64/libQt5WebEngineCore.so.5(+0x124645f) [0x7f177fff245f]
#15: /usr/lib64/libQt5WebEngineCore.so.5(+0x1246716) [0x7f177fff2716]
#16: /usr/lib64/libQt5WebEngineCore.so.5(_ZN15QtWebEngineCore18WebContentsAdapter10setContentERK10QByteArrayRK7QStringRK4QUrl+0x40b) [0x7f177f422b3b]
#17: /usr/lib64/libQt5WebEngineWidgets.so.5(_ZN14QWebEnginePage7setHtmlERK7QStringRK4QUrl+0x45) [0x7f177cc43d95]
#18: /usr/lib64/libQupZilla.so.2(+0x291579) [0x7f17841a5579]
#19: /usr/lib64/libQt5Core.so.5(+0x2bb5b6) [0x7f177e12f5b6]
#20: /usr/lib64/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0xa3) [0x7f177e123d13]
#21: /usr/lib64/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c) [0x7f177e6a592c]
#22: /usr/lib64/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x261) [0x7f177e6ad0e1]
#23: /usr/lib64/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x110) [0x7f177e0f7200]
#24: /usr/lib64/libQt5Core.so.5(_ZN14QTimerInfoList14activateTimersEv+0x48e) [0x7f177e14a71e]
#25: /usr/lib64/libQt5Core.so.5(+0x2d6c41) [0x7f177e14ac41]
#26: /usr/lib64/libglib-2.0.so.0(g_main_context_dispatch+0x2a7) [0x7f177a159677]
#27: /usr/lib64/libglib-2.0.so.0(+0x4d8e0) [0x7f177a1598e0]
#28: /usr/lib64/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7f177a15998c]
#29: /usr/lib64/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f) [0x7f177e14b77f]
#30: /usr/lib64/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0xfa) [0x7f177e0f51ea]
#31: /usr/lib64/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x9c) [0x7f177e0fd95c]
#32: qupzilla() [0x402ed7]
#33: /lib64/libc.so.6(__libc_start_main+0xf1) [0x7f177d54c291]
#34: qupzilla() [0x4031fa]


I had installed debug info package for qupzilla but I'm not completely sure if it's enabled but here is console output running qupzilla through it.

Output - 

[1013/213407:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
QupZilla: 0 extensions loaded
AdBlockSubscription:: loadSubscription invalid format of adblock file "/home/jkoreth/.config/qupzilla/profiles/default/adblock/customlist.txt"
libpng warning: iCCP: known incorrect sRGB profile
Uncaught ReferenceError: qt is not defined
Mixed Content: The page at 'https://www.opensuse.org/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGEMbjGELOEJD5J8DUmxkO-A.ttf'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://www.opensuse.org/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGMw1o1eFRj7wYC6JbISqOjY.ttf'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://www.opensuse.org/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/sourcesanspro/v9/ODelI1aHBYDBqgeIAH2zlNzbP97U9sKh0jjxbPbfOKg.ttf'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://www.opensuse.org/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGNNE-IuDiR70wI4zXaKqWCM.ttf'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://www.opensuse.org/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGMw1o1eFRj7wYC6JbISqOjY.ttf'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://www.opensuse.org/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGLsbIrGiHa6JIepkyt5c0A0.ttf'. This request has been blocked; the content must be served over HTTPS.
Uncaught TypeError: object.unwrapQObject is not a function
Uncaught ReferenceError: qt is not defined
Received signal 11 SEGV_MAPERR 000000000020
#0 0x7fd7fb0beb5e base::debug::StackTrace::StackTrace()
#1 0x7fd7fb0bef19 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7fd7f86c0650 <unknown>
#3 0x7fd7faa68aa5 blink::LayoutObject::isDescendantOf()
#4 0x7fd7faae496c blink::CompositedLayerMapping::containingSquashedLayer()
#5 0x7fd7fab67a8b blink::CompositingLayerAssigner::getReasonsPreventingSquashing()
#6 0x7fd7fab6862e blink::CompositingLayerAssigner::assignLayersToBackingsInternal()
#7 0x7fd7fab683b9 blink::CompositingLayerAssigner::assignLayersToBackingsInternal()
#8 0x7fd7fab683b9 blink::CompositingLayerAssigner::assignLayersToBackingsInternal()
#9 0x7fd7fab68801 blink::CompositingLayerAssigner::assign()
#10 0x7fd7faae9969 blink::PaintLayerCompositor::updateIfNeeded()
#11 0x7fd7faaeac16 blink::PaintLayerCompositor::updateIfNeededRecursive()
#12 0x7fd7fc07e86c blink::FrameView::updateLifecyclePhasesInternal()
#13 0x7fd7fc1b83c8 blink::PageAnimator::updateAllLifecyclePhases()
#14 0x7fd7fa751f92 blink::WebViewImpl::updateAllLifecyclePhases()
#15 0x7fd7faf11702 content::RenderWidgetCompositor::UpdateLayerTreeHost()
#16 0x7fd7fc57a409 cc::ProxyMain::BeginMainFrame()
#17 0x7fd7fc581c15 _ZN4base8internal7InvokerINS_13IndexSequenceIJLm0ELm1EEEENS0_9BindStateINS0_15RunnableAdapterIMN2cc9ProxyMainEFv10scoped_ptrINS6_28BeginMainFrameAndCommitStateESt14default_deleteIS9_EEEEEFvPS7_SC_EJNS_7WeakPtrIS7_EENS0_13PassedWrapperISC_EEEEENS0_8TypeListIJNS0_12UnwrapTraitsISJ_EENSO_ISL_EEEEENS0_12InvokeHelperILb1EvSF_NSN_IJRKSJ_SC_EEEEEFvvEE3RunEPNS0_13BindStateBaseE
#18 0x7fd7fb12f989 base::debug::TaskAnnotator::RunTask()
#19 0x7fd7fb75e174 scheduler::TaskQueueManager::ProcessTaskFromWorkQueue()
#20 0x7fd7fb75e989 scheduler::TaskQueueManager::DoWork()
#21 0x7fd7fb12f989 base::debug::TaskAnnotator::RunTask()
#22 0x7fd7fb0dbd89 base::MessageLoop::RunTask()
#23 0x7fd7fb0dc969 base::MessageLoop::DeferOrRunPendingTask()
#24 0x7fd7fb0dce22 base::MessageLoop::DoWork()
#25 0x7fd7fb0dec89 base::MessagePumpDefault::Run()
#26 0x7fd7fb0f068a base::RunLoop::Run()
#27 0x7fd7fb0db165 base::MessageLoop::Run()
#28 0x7fd7fae453ff content::RendererMain()
#29 0x7fd7fa3037a4 content::RunZygote()
#30 0x7fd7fa303ce4 content::ContentMainRunnerImpl::Run()
#31 0x7fd7fa3022e1 content::ContentMain()
#32 0x7fd7f9757614 QtWebEngine::processMain()
#33 0x000000400733 main
#34 0x7fd7f86ac291 __libc_start_main
#35 0x00000040078a _start
  r8: 0000000000000279  r9: 00000000000001f9 r10: 0000000000000000 r11: 00002edceb018f10
 r12: 0000279c4e0b07a0 r13: 0000000000000001 r14: 0000000000000000 r15: 00002edceb010000
  di: 0000000000000000  si: 00002edceb0226f8  bp: 0000000000000000  bx: 0000000000000000
  dx: 0000000000000001  ax: 00002edceb0135d0  cx: 0000000000000476  sp: 00007fffb04fb7e8
  ip: 00007fd7faa68aa5 efl: 0000000000010293 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000020
[end of stack trace]
Uncaught ReferenceError: qt is not defined
Mixed Content: The page at 'https://www.opensuse.org/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGEMbjGELOEJD5J8DUmxkO-A.ttf'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://www.opensuse.org/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGMw1o1eFRj7wYC6JbISqOjY.ttf'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://www.opensuse.org/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/sourcesanspro/v9/ODelI1aHBYDBqgeIAH2zlNzbP97U9sKh0jjxbPbfOKg.ttf'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://www.opensuse.org/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGNNE-IuDiR70wI4zXaKqWCM.ttf'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://www.opensuse.org/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGMw1o1eFRj7wYC6JbISqOjY.ttf'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://www.opensuse.org/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGLsbIrGiHa6JIepkyt5c0A0.ttf'. This request has been blocked; the content must be served over HTTPS.
Received signal 11 SEGV_MAPERR 000000000020
#0 0x7fd7fb0beb5e base::debug::StackTrace::StackTrace()
#1 0x7fd7fb0bef19 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7fd7f86c0650 <unknown>
#3 0x7fd7faa68aa5 blink::LayoutObject::isDescendantOf()
#4 0x7fd7faae496c blink::CompositedLayerMapping::containingSquashedLayer()
#5 0x7fd7fab67a8b blink::CompositingLayerAssigner::getReasonsPreventingSquashing()
#6 0x7fd7fab6862e blink::CompositingLayerAssigner::assignLayersToBackingsInternal()
#7 0x7fd7fab683b9 blink::CompositingLayerAssigner::assignLayersToBackingsInternal()
#8 0x7fd7fab683b9 blink::CompositingLayerAssigner::assignLayersToBackingsInternal()
#9 0x7fd7fab68801 blink::CompositingLayerAssigner::assign()
#10 0x7fd7faae9969 blink::PaintLayerCompositor::updateIfNeeded()
#11 0x7fd7faaeac16 blink::PaintLayerCompositor::updateIfNeededRecursive()
#12 0x7fd7fc07e86c blink::FrameView::updateLifecyclePhasesInternal()
#13 0x7fd7fc1b83c8 blink::PageAnimator::updateAllLifecyclePhases()
#14 0x7fd7fa751f92 blink::WebViewImpl::updateAllLifecyclePhases()
#15 0x7fd7faf11702 content::RenderWidgetCompositor::UpdateLayerTreeHost()
#16 0x7fd7fc57a409 cc::ProxyMain::BeginMainFrame()
#17 0x7fd7fc581c15 _ZN4base8internal7InvokerINS_13IndexSequenceIJLm0ELm1EEEENS0_9BindStateINS0_15RunnableAdapterIMN2cc9ProxyMainEFv10scoped_ptrINS6_28BeginMainFrameAndCommitStateESt14default_deleteIS9_EEEEEFvPS7_SC_EJNS_7WeakPtrIS7_EENS0_13PassedWrapperISC_EEEEENS0_8TypeListIJNS0_12UnwrapTraitsISJ_EENSO_ISL_EEEEENS0_12InvokeHelperILb1EvSF_NSN_IJRKSJ_SC_EEEEEFvvEE3RunEPNS0_13BindStateBaseE
#18 0x7fd7fb12f989 base::debug::TaskAnnotator::RunTask()
#19 0x7fd7fb75e174 scheduler::TaskQueueManager::ProcessTaskFromWorkQueue()
#20 0x7fd7fb75e989 scheduler::TaskQueueManager::DoWork()
#21 0x7fd7fb12f989 base::debug::TaskAnnotator::RunTask()
#22 0x7fd7fb0dbd89 base::MessageLoop::RunTask()
#23 0x7fd7fb0dc969 base::MessageLoop::DeferOrRunPendingTask()
#24 0x7fd7fb0ddc80 base::MessageLoop::DoDelayedWork()
#25 0x7fd7fb0dec9f base::MessagePumpDefault::Run()
#26 0x7fd7fb0f068a base::RunLoop::Run()
#27 0x7fd7fb0db165 base::MessageLoop::Run()
#28 0x7fd7fae453ff content::RendererMain()
#29 0x7fd7fa3037a4 content::RunZygote()
#30 0x7fd7fa303ce4 content::ContentMainRunnerImpl::Run()
#31 0x7fd7fa3022e1 content::ContentMain()
#32 0x7fd7f9757614 QtWebEngine::processMain()
#33 0x000000400733 main
#34 0x7fd7f86ac291 __libc_start_main
#35 0x00000040078a _start
  r8: 0000000000000279  r9: 00000000000001f9 r10: 0000000000000000 r11: 00007fd7f87f69e0
 r12: 00002043954ba800 r13: 0000000000000001 r14: 0000000000000000 r15: 0000339189810000
  di: 0000000000000000  si: 00003391898226f8  bp: 0000000000000000  bx: 0000000000000000
  dx: 0000000000000001  ax: 00003391898135d0  cx: 0000000000000476  sp: 00007fffb04fb7e8
  ip: 00007fd7faa68aa5 efl: 0000000000010293 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000020
[end of stack trace]
Uncaught ReferenceError: qt is not defined
Received signal 11 SEGV_MAPERR 000000000020
#0 0x7fd7fb0beb5e base::debug::StackTrace::StackTrace()
#1 0x7fd7fb0bef19 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7fd7f86c0650 <unknown>
#3 0x7fd7faa68aa5 blink::LayoutObject::isDescendantOf()
#4 0x7fd7faae496c blink::CompositedLayerMapping::containingSquashedLayer()
#5 0x7fd7fab67a8b blink::CompositingLayerAssigner::getReasonsPreventingSquashing()
#6 0x7fd7fab6862e blink::CompositingLayerAssigner::assignLayersToBackingsInternal()
#7 0x7fd7fab683b9 blink::CompositingLayerAssigner::assignLayersToBackingsInternal()
#8 0x7fd7fab683b9 blink::CompositingLayerAssigner::assignLayersToBackingsInternal()
#9 0x7fd7fab68801 blink::CompositingLayerAssigner::assign()
#10 0x7fd7faae9969 blink::PaintLayerCompositor::updateIfNeeded()
#11 0x7fd7faaeac16 blink::PaintLayerCompositor::updateIfNeededRecursive()
#12 0x7fd7fc07e86c blink::FrameView::updateLifecyclePhasesInternal()
#13 0x7fd7fc1b83c8 blink::PageAnimator::updateAllLifecyclePhases()
#14 0x7fd7fa751f92 blink::WebViewImpl::updateAllLifecyclePhases()
#15 0x7fd7faf11702 content::RenderWidgetCompositor::UpdateLayerTreeHost()
#16 0x7fd7fc57a409 cc::ProxyMain::BeginMainFrame()
#17 0x7fd7fc581c15 _ZN4base8internal7InvokerINS_13IndexSequenceIJLm0ELm1EEEENS0_9BindStateINS0_15RunnableAdapterIMN2cc9ProxyMainEFv10scoped_ptrINS6_28BeginMainFrameAndCommitStateESt14default_deleteIS9_EEEEEFvPS7_SC_EJNS_7WeakPtrIS7_EENS0_13PassedWrapperISC_EEEEENS0_8TypeListIJNS0_12UnwrapTraitsISJ_EENSO_ISL_EEEEENS0_12InvokeHelperILb1EvSF_NSN_IJRKSJ_SC_EEEEEFvvEE3RunEPNS0_13BindStateBaseE
#18 0x7fd7fb12f989 base::debug::TaskAnnotator::RunTask()
#19 0x7fd7fb75e174 scheduler::TaskQueueManager::ProcessTaskFromWorkQueue()
#20 0x7fd7fb75e989 scheduler::TaskQueueManager::DoWork()
#21 0x7fd7fb12f989 base::debug::TaskAnnotator::RunTask()
#22 0x7fd7fb0dbd89 base::MessageLoop::RunTask()
#23 0x7fd7fb0dc969 base::MessageLoop::DeferOrRunPendingTask()
#24 0x7fd7fb0dce22 base::MessageLoop::DoWork()
#25 0x7fd7fb0dec89 base::MessagePumpDefault::Run()
#26 0x7fd7fb0f068a base::RunLoop::Run()
#27 0x7fd7fb0db165 base::MessageLoop::Run()
#28 0x7fd7fae453ff content::RendererMain()
#29 0x7fd7fa3037a4 content::RunZygote()
#30 0x7fd7fa303ce4 content::ContentMainRunnerImpl::Run()
#31 0x7fd7fa3022e1 content::ContentMain()
#32 0x7fd7f9757614 QtWebEngine::processMain()
#33 0x000000400733 main
#34 0x7fd7f86ac291 __libc_start_main
#35 0x00000040078a _start
  r8: 0000000000000240  r9: 00000000000000eb r10: 00000000000001e1 r11: 00000000000004b9
 r12: 00002d9a81ec4320 r13: 0000000000000001 r14: 0000000000000000 r15: 00001a603d610000
  di: 0000000000000000  si: 00001a603d6f60a0  bp: 0000000000000000  bx: 0000000000000000
  dx: 0000000000000001  ax: 00001a603d61f180  cx: 0000000000000309  sp: 00007fffb04fb7e8
  ip: 00007fd7faa68aa5 efl: 0000000000010287 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000020
[end of stack trace]
QupZilla: Crashed :( Saving backtrace in /home/jkoreth/.config/qupzilla/crashlog ...

**Comment by j-koreth** [comment]
Gists if it is more helpful this way...

Backtrace Gist - https://gist.github.com/j-koreth/b7bedf4340284fa597e0614a11751701
Output Gist - https://gist.github.com/j-koreth/d503d8bdfffcbb8bfaa93c8555fe8d58

**Comment by Martii** [comment]
Heh... "Leap" doesn't seem all that stable either. Haven't powered up that VM since my last comment here and this is what I get now:

<img src=""https://cloud.githubusercontent.com/assets/114709/19495088/28bcdba0-953f-11e6-9700-d6fda3237e2f.png" width="320" height="640" />

**Comment by nowrep** [comment]
Same as other similar issue: please use Qt 5.6 or wait for bugfix release of Qt 5.7 (5.7.1). The QtWebEngine in 5.7.0 is buggy and crashes.
