### ISSUE TITLE
Rename RSS to Syndication

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#2097]
Apparently, RSS 2.0 is [copyrighted].  By writing RSS (Feed), QupZilla promotes a non-standard implementation of Syndication (Feed).

[copyrighted]: http://wayback.archive.org/web/20141015100359/http://atompub.org/2005/07/11/draft-ietf-atompub-format-10.html

**Comment by Martii** [comment]
Probably a good idea to rename it but atom feeds is not the best source here as that is their competition. Presumably somewhere at http://www.rssboard.org/rss-specification is a good place to see what their exactly licensing is as of now.

**Comment by GreenLunar** [comment]
In concern to RSS, as long as those responsible for RSS do not bother to update it, or pass this project to other people, it is preferable to deprecate and even neglect it, in favor of standard syndication format such as ATOM.

Even their mailing-list is inactive. That RSS "Advisory" Board website just stands out there as is.

**Comment by nowrep** [comment]
RSS reader is only in 1.9 version, which is now obsolete so I don't think this is really an issue.

**Comment by GreenLunar** [comment]
Web feeds matter. Linking to #458
