### ISSUE TITLE
Frequent Crashes on Tumbleweed

### ISSUE THREAD

**Issue by cmrnt** [QupZilla/qupzilla#2098]
Qupzilla has been my daily driver for that past few months.  It is quick and and sleek.  In the last couple of weeks, it has started to crash frequently.  After the crash, plasma stops responding to mouse input for several seconds.  The behavior began after one of the more recent updates to Tumbleweed.  Output from one such instance is pasted below for qupzilla version 2.0.1 and QtWebEngine version 5.7.0 both from the Tumbleweed repositories.

----------------------
user@hp820:~/.config/qupzilla/crashlog> qupzilla www.thedailybeast.com &
[1] 5159
user@hp820:~/.config/qupzilla/crashlog> Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/emblems/8/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/actions/16/"
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Faenza/apps/16/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/categories/16/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/devices/16/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/emblems/16/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Faenza/mimetypes/16/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/places/16/"
Inva
[Crash-2016-10-14T10:49:19.txt](https://github.com/QupZilla/qupzilla/files/529802/Crash-2016-10-14T10.49.19.txt)
lid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/status/16/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/actions/22/"
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Faenza/apps/22/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/categories/22/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/devices/22/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/emblems/22/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Faenza/mimetypes/22/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/places/22/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/status/22/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/actions/24/"
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Faenza/apps/24/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/categories/24/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/devices/24/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/emblems/24/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Faenza/mimetypes/24/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/places/24/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/status/24/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/actions/32/"
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Faenza/apps/32/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/categories/32/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/devices/32/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/emblems/32/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Faenza/mimetypes/32/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/places/32/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/status/32/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/actions/48/"
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Faenza/apps/48/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/categories/48/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/devices/48/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/emblems/48/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Faenza/mimetypes/48/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/places/48/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/status/48/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/actions/64/"
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Faenza/apps/64/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/categories/64/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/devices/64/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/emblems/64/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Faenza/mimetypes/64/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/places/64/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/status/64/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/actions/96/"
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Faenza/apps/96/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/categories/96/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/devices/96/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/emblems/96/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Faenza/mimetypes/96/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/places/96/"
Invalid Type= "fixed" line for icon theme:  "/usr/share/icons/Faenza/status/96/"
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Faenza/apps/scalable/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Faenza/mimetypes/scalable/"
[1014/104916:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
QupZilla: 0 extensions loaded
Received signal 11 SEGV_MAPERR 000000000020
#0 0x7feb585eab5e base::debug::StackTrace::StackTrace()
#1 0x7feb585eaf19 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7feb55bee650 <unknown>
#3 0x7feb57f94aa5 blink::LayoutObject::isDescendantOf()
#4 0x7feb5801096c blink::CompositedLayerMapping::containingSquashedLayer()
#5 0x7feb58093a8b blink::CompositingLayerAssigner::getReasonsPreventingSquashing()
#6 0x7feb5809462e blink::CompositingLayerAssigner::assignLayersToBackingsInternal()
#7 0x7feb580943b9 blink::CompositingLayerAssigner::assignLayersToBackingsInternal()
#8 0x7feb580943b9 blink::CompositingLayerAssigner::assignLayersToBackingsInternal()
#9 0x7feb58094801 blink::CompositingLayerAssigner::assign()
#10 0x7feb58015969 blink::PaintLayerCompositor::updateIfNeeded()
#11 0x7feb58016c16 blink::PaintLayerCompositor::updateIfNeededRecursive()
#12 0x7feb595aa86c blink::FrameView::updateLifecyclePhasesInternal()
#13 0x7feb596e43c8 blink::PageAnimator::updateAllLifecyclePhases()
#14 0x7feb57c7df92 blink::WebViewImpl::updateAllLifecyclePhases()
#15 0x7feb5843d702 content::RenderWidgetCompositor::UpdateLayerTreeHost()
#16 0x7feb59aa6409 cc::ProxyMain::BeginMainFrame()
#17 0x7feb59aadc15 _ZN4base8internal7InvokerINS_13IndexSequenceIJLm0ELm1EEEENS0_9BindStateINS0_15RunnableAdapterIMN2cc9ProxyMainEFv10scoped_ptrINS6_28BeginMainFrameAndCommitStateESt14default_deleteIS9_EEEEEFvPS7_SC_EJNS_7WeakPtrIS7_EENS0_13PassedWrapperISC_EEEEENS0_8TypeListIJNS0_12UnwrapTraitsISJ_EENSO_ISL_EEEEENS0_12InvokeHelperILb1EvSF_NSN_IJRKSJ_SC_EEEEEFvvEE3RunEPNS0_13BindStateBaseE
#18 0x7feb5865b989 base::debug::TaskAnnotator::RunTask()
#19 0x7feb58c8a174 scheduler::TaskQueueManager::ProcessTaskFromWorkQueue()
#20 0x7feb58c8a989 scheduler::TaskQueueManager::DoWork()
#21 0x7feb5865b989 base::debug::TaskAnnotator::RunTask()
#22 0x7feb58607d89 base::MessageLoop::RunTask()
#23 0x7feb58608969 base::MessageLoop::DeferOrRunPendingTask()
#24 0x7feb58608e22 base::MessageLoop::DoWork()
#25 0x7feb5860ac89 base::MessagePumpDefault::Run()
#26 0x7feb5861c68a base::RunLoop::Run()
#27 0x7feb58607165 base::MessageLoop::Run()
#28 0x7feb583713ff content::RendererMain()
#29 0x7feb5782f7a4 content::RunZygote()
#30 0x7feb5782fce4 content::ContentMainRunnerImpl::Run()
#31 0x7feb5782e2e1 content::ContentMain()
#32 0x7feb56c83614 QtWebEngine::processMain()
#33 0x000000400733 main
#34 0x7feb55bda291 __libc_start_main
#35 0x00000040078a _start
  r8: 00000000000000f5  r9: 0000000000000052 r10: 0000000000000042 r11: 00001a24aae6daa0
 r12: 00001b53a31c4260 r13: 0000000000000009 r14: 0000000000000000 r15: 00000aeb61410000
  di: 0000000000000000  si: 00000aeb61421a48  bp: 0000000000000000  bx: 0000000000000000
  dx: 0000000000000009  ax: 00000aeb61411110  cx: 0000000000000310  sp: 00007ffd54673b98
  ip: 00007feb57f94aa5 efl: 0000000000010297 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000020
[end of stack trace]
QupZilla: Crashed :( Saving backtrace in /home/cwtanner/.config/qupzilla/crashlog ...
Backtrace successfully saved in /home/user/.config/qupzilla/crashlog/Crash-2016-10-14T10:49:19.txt

**Comment by Martii** [comment]
Possibly related to #2096. Most of the diagnostics for "Leap" are there along with the original "Tumbleweed" report. Rolling releases can be incompatible at times on occasion due to their nature... so if "Tumbleweed" has an older snapshot please give that a try.

**Comment by cmrnt** [comment]
TW is living on the edge so an occasional hiccup is not unexpected.  As you suggested, I rebuilt qupzilla from the TW src package.  The result is the same, a crash.  Apologies for the format of the backtrace posting.  Let me know if there is anything else that I can do to help diagnose the issue besides checking back from time to time to see if it just starts working.

With regard to the formatting of the post;  I tried using the upload function, it did not seem to work.  I do not know what a tripple backtick is.  Instructions on quoting are ambiguous.  These are the downsides of reports from the less savvy.

**Comment by Martii** [comment]
<pre>```
something to quote so GitHub doesn't reference issues with a backtrace.
```
</pre>

**Comment by Martii** [comment]
Well when I get back to my dev test station early next week where I can pop out a HDD and put in TW I can test from scratch there but blowing away my ArchLinux on that machine isn't an option ... so it will take me a bit of time.

Also uploading can be hindered by NoScript, or equivalent, as well. Usually I just paste things in.

**Comment by nowrep** [comment]
You can either use Qt 5.6, which is stable enough or wait for bugfix release for Qt 5.7 (5.7.1). Unfortunately, QtWebEngine in Qt 5.7.0 is buggy and crashing a lot.
