### ISSUE TITLE
compile qupzilla

### ISSUE THREAD

**Issue by trazomtg** [QupZilla/qupzilla#2101]
Hi,

Hi,
i am working on Debian 8.5

i still try to install qupzilla and i don't succeed. here is the message
_QupZilla requires at least Qt 5.6_

i have installed Qt 5.6 with the following commands:
_qt-unified-linux-x64-2.0.3-1-online.run
qt-installer-framework-opensource-2.0.1-x64.run
qt-creator-opensource-linux-x86_64-4.1.0.run_

the installation is in /opt/Qt:
_root@debian-lenovo:/opt# ls
Qt  qtcreator-4.1.0_

i have installed : 
_apt-get install libxcb-util0-dev_

please help me!!
Regards

**Comment by trazomtg** [comment]
here is thr result of qmake:
_qmake -v
QMake version 2.01a
Using Qt version 4.8.6 in /usr/lib/x86_64-linux-gnu_

how can i change this?
_Using Qt version 4.8.6 in /usr/lib/x86_64-linux-gnu_
to use :  /opt/Qt/5.6/gcc_64/lib
Thanks

**Comment by trazomtg** [comment]
when i run qmake -r  i get:

root@debian-lenovo:~/qupzilla-2.0.1# qmake  -r
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory

how to use   _/opt/Qt/5.6/gcc_64/lib_  instead?

**Comment by nowrep** [comment]
`/opt/Qt/5.6/gcc_64/bin/qmake -r`

**Comment by trazomtg** [comment]
_root@debian-lenovo:~/qupzilla-2.0.1# qmake -v
QMake version 3.0
Using Qt version 5.3.2 in /usr/lib/x86_64-linux-gnu_

how specify that i want to use Qt 5.6?
thanks

**Comment by trazomtg** [comment]
ok!  thanks

is Qupzilla able to read and manage RSS flux?

**Comment by trazomtg** [comment]
and Podcasts?
