### ISSUE TITLE
Restore tabs does not work correctly.

### ISSUE THREAD

**Issue by konqoro** [QupZilla/qupzilla#2104]
After crash or pc shutting down without qupzilla exiting cleanly, restore dialog appears. However checking which tabs to restore does not bring all the checked tabs, it also restores some unchecked.

**Comment by nowrep** [comment]
What is your QupZilla version?

**Comment by konqoro** [comment]
2.0.1 with qt5.7.0 from manjaro.

**Comment by nowrep** [comment]
Alright, and can you post exact steps to reproduce the issue or it happens randomly?

**Comment by konqoro** [comment]
Sure here you go.
1) open many tabs and crash qupzilla
2) restart qupzilla, deselect some tabs and click restore
3) remember which ones you have chosen and the ones you haven't 
you may see different tabs than expected.

**Comment by nowrep** [comment]
Can't really reproduce, it always restores correct tabs for me.
One thing to be noted is that I use Qt 5.8 and not Qt 5.7.0 which was quite buggy with regard to QtWebEngine. Any chance to test it against other Qt version?

**Comment by DebugReport** [comment]
Confirm. Sometimes restore incorrect.
Application version 2.0.99 (4657fdf60c)
QtWebEngine version 5.7.0
