### ISSUE TITLE
Error on start - Entry point not found

### ISSUE THREAD

**Issue by Beep6581** [QupZilla/qupzilla#2107]
Reproducible: always
Versions affected: tested and reproduced in 2.0.1 and 2.0.2
OS: Windows XP SP3

This error msgbox pops up 8 times when I run Qupzilla:
```
---------------------------
qupzilla.exe - Entry Point Not Found
---------------------------
The procedure entry point strnlen could not be located in the dynamic link library msvcrt.dll. 
---------------------------
OK   
---------------------------
```

There is a second or two delay between popups 4 and 5.

![imgur-2016_10_26-15 33 14](https://cloud.githubusercontent.com/assets/5844619/19727895/880bde64-9b91-11e6-9bfb-1e788c76d59e.png)

**Comment by nowrep** [comment]
Windows XP is not officially supported. It works but unfortunately have this issue.
