### ISSUE TITLE
Crash on close - Memory could not be read

### ISSUE THREAD

**Issue by Beep6581** [QupZilla/qupzilla#2108]
Reproducible: sometimes
Versions affected: tested and reproduced in 2.0.1 and 2.0.2
OS: Windows XP SP3

This error msgbox sometimes shows when I close QupZilla:
```
---------------------------
Portal:Current events - Wikipedia - QupZilla: qupzilla.exe - Application Error
---------------------------
The instruction at "0x6718d9b7" referenced memory at "0x00000004". The memory could not be "read".
Click on OK to terminate the program
Click on CANCEL to debug the program
---------------------------
OK   Cancel   
---------------------------
```

![imgur-2016_10_26-15 32 53](https://cloud.githubusercontent.com/assets/5844619/19727930/baab5caa-9b91-11e6-8415-5afa444fe9d5.png)

**Comment by nowrep** [comment]
Same as previous issue, Win XP is not officially supported.
