### ISSUE TITLE
No 'remember password' prompt when signing into BackBlaze B2

### ISSUE THREAD

**Issue by willbprog127** [QupZilla/qupzilla#2113]
When using Firefox and Chrome to sign into BackBlaze B2, those browsers ask to save the login.  Qupzilla does not.

The URL is: [https://www.backblaze.com/user_signin.htm](https://www.backblaze.com/user_signin.htm)

:information_source: **Version Info**
Application version: 1.8.9
Qt version: 5.6.1
WebKit version: 538.1
Platform: BSD 4.4 (FreeBSD 11.0)

Thanks! :smile:

**Comment by nowrep** [comment]
Works in 2.0

**Comment by willbprog127** [comment]
Version 2.0 is not available on FreeBSD and building it has problems with too low a version of Qt 5.  Guess I'm stuck with 1.8.9 bugs. :cry:
