### ISSUE TITLE
arstechnica.com rendering very poorly

### ISSUE THREAD

**Issue by willbprog127** [QupZilla/qupzilla#2114]
Ars Technica (arstechnica.com) renders very poorly in QupZilla.  Please see images for comparison between QupZilla and Firefox.

QupZilla
![arsrendering-qupzilla](https://cloud.githubusercontent.com/assets/1296250/19980318/c2a8137e-a1ba-11e6-961d-b66c8c1c14df.png)

Firefox
![arsrendering-firefox](https://cloud.githubusercontent.com/assets/1296250/19980317/c2a4e1ae-a1ba-11e6-9e01-89403fb7545b.png)

:information_source: **Version Info**
Application version: 1.8.9
Qt version: 5.6.1
WebKit version: 538.1
Platform: BSD 4.4 (FreeBSD 11.0)

Thanks! :smile:

**Comment by nowrep** [comment]
That's unfortunately issue with QtWebKit. It renders correctly with QtWebEngine.
