### ISSUE TITLE
Plasma Widget

### ISSUE THREAD

**Issue by kaendfinger** [QupZilla/qupzilla#2116]
It would be awesome to be able to use a QupZilla widget in the KDE Plasma desktop.

**Comment by nowrep** [comment]
What kind of widget do you have in mind? What it should do?

**Comment by kaendfinger** [comment]
@nowrep I think having an address bar that is hide-able with the page content is all that would be needed. I personally would use it for playing YouTube.

**Comment by nowrep** [comment]
Plasma already have a "Web Browser" plasmoid that does exactly what you described.
