### ISSUE TITLE
Is oracle java supported?

### ISSUE THREAD

**Issue by acidrop** [QupZilla/qupzilla#2117]
Hello,

Silly question but I'm not able to activate java on Qupzilla 2.0.2 for Linux.
On Firefox all I have to do is to create a symlink for linpjp2.so library file into .mozilla/plugins folder.
Is there something similar supported on Qupzilla?

I created a folder named, plugins (~/.config/qupzilla/profiles/default/plugins) under my home path and then I symlinked library file: libnpjp2.so -> /opt/java/lib/amd64/libnpjp2.so . Then I changed user agent to Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 but no change.

Thank you

**Comment by nowrep** [comment]
You need to use PPAPI plugin, not old NPAPI browser plugins.

https://java.com/en/download/faq/chrome.xml
