### ISSUE TITLE
Close tabs to Right [Feature Request]

### ISSUE THREAD

**Issue by ikidd** [QupZilla/qupzilla#2118]
Love the browser, but I like to be able to keep a few tabs that I pull over to left, then kill the remaining tabs on the right.  Pretty much all other browsers I've used have this feature, I was hoping to see it here too.

**Comment by nowrep** [comment]
e906f6ae206fccdb1c7ead1f07e4b28fee3adf85 will be in next version.

**Comment by ikidd** [comment]
Awesome, ty.
