### ISSUE TITLE
AdBlock > Disable on this page doesn't work

### ISSUE THREAD

**Issue by AcarBurak** [QupZilla/qupzilla#2119]
As the title says.

**Comment by nowrep** [comment]
Your QupZilal version is?

**Comment by AcarBurak** [comment]
Sorry, 2.0.2 in Arch/Fluxbox.

**Comment by nowrep** [comment]
Can you please explain what doesn't work? Adding the rule that should disable blocking on the page or the blocking on the page is not disabled after adding this rule?

**Comment by AcarBurak** [comment]
Yes, blocking is not disabled. Clicking on the statusbar adblock image and chosing either "Disable on xxxx.com" or "Disable only on this page" makes those options checked, but actual blocking is not disabled in either way.

**Comment by AcarBurak** [comment]
Sorry, but it still doesn't work with QupZilla 2.1 on an Arch/Fluxbox system with Qt (5.8) theme set by `qt5ct` if that matters.

**Comment by nowrep** [comment]
So please show me exact steps (with url of page too) how to reproduce the issue.

**Comment by AcarBurak** [comment]
https://www.theguardian.com/international

On that page when I check "disable on guardian.com" instead of adds I see "Advertisement" on a blank frame (as attached); when I uncheck "disable on guardian.com" there's just blank frames instead of adds.

![guardianadds](https://cloud.githubusercontent.com/assets/1426842/22822003/3e8a45de-ef86-11e6-8714-86855f009e29.jpg)

**Comment by AcarBurak** [comment]
Maybe I've got something weird with my system, because I've just installed Firefox and I've seen no adds in either Guardian site or phoronix, for instance. Then I've added/installed addblock extension and disabled blocking on those web pages and it's not honoured just like in QupZilla.
