### ISSUE TITLE
QupZilla reports invalid SSL for any site using "infolinks"

### ISSUE THREAD

**Issue by irondutchess** [QupZilla/qupzilla#2122]
I have three websites that use the infolinks script. All sites work OK in FF, IE, Chrome and Opera. In QupZilla there is a warning.

See screenshot:
![infolinks](https://cloud.githubusercontent.com/assets/23417541/20237954/203c6598-a8d8-11e6-9544-6fcc319d5439.png)

**Comment by nowrep** [comment]
Please update to QupZilla 2.
