### ISSUE TITLE
Wireless Printer - Cannot copy scanned image

### ISSUE THREAD

**Issue by fdservices** [QupZilla/qupzilla#2126]
Qupzilla Application version 2.0.99 (4657fdf60c)
QtWebEngine version 5.7.0
Printer is HP Deskjet 3050 All-in-One J610a
Cannot copy scanned jpeg image - steps to reproduce
1) Browse to printer web page
2) Select Jpeg and Start Scan
3) On completion - "Right-click the image to save the scan on your computer."
4) Right click on image shows Save Page, not Save Image, and saves the whole html page

Cannot copy scanned pdf image - steps to reproduce
1) Browse to printer web page
2) Select PDF and Start Scan
3) On completion - "Click the Save icon to save the scan on your computer."
4) No Save icon appears, but save dialogue pops up which [u]does[/u] save the pdf image.

Andrew

**Comment by nowrep** [comment]
Can you please paste somewhere the html source of the page? Or even better, download the complete page (eg. using QupZilla -> Save Page) and upload it.

**Comment by fdservices** [comment]
So sorry for the delay - here it is:

https://spaces.hightail.com/space/1uwf4

Andrew
