### ISSUE TITLE
XP *sp2* The procedure entry point GetLogicalProcessorInformation could not be located in the dynamic link library KERNEL32.dll. 

### ISSUE THREAD

**Issue by jjanel** [QupZilla/qupzilla#2127]
I have XP sp2 (upg to sp3 not a option, sorry). I get this popup. Any 'fix'? TiA!
qupzilla.exe - Entry Point Not Found
The procedure entry point GetLogicalProcessorInformation could not be located in the dynamic link library KERNEL32.dll.

**Comment by Martii** [comment]
A [maintainer comment](https://github.com/QupZilla/qupzilla/issues/1934#issuecomment-209368978) about XP.

**Comment by nowrep** [comment]
Windows XP SP2 is unsupported.
