### ISSUE TITLE
Bug with inspect element

### ISSUE THREAD

**Issue by DebugReport** [QupZilla/qupzilla#2131]
Can't open Inspect Element in other tabs, if current will be closed.

QIODevice::read (QDisabledNetworkReply): device not open
Uncaught TypeError: Cannot read property 'appendChild' of undefined

**Comment by DebugReport** [comment]
Qupzilla crashed sometimes.
https://gist.github.com/DebugReport/49a485eba9f3e57cd3b365e364332f4c
For reproduce - kill qupzilla, restore session and open Inspect Element. Sometimes i can reproduce this...

**Comment by nowrep** [comment]
cb771352dab8ed80c9ce0d147de40821856fe121
