### ISSUE TITLE
Add Chrome string to user-agent to make recapchas work

### ISSUE THREAD

**Issue by sixsixfive** [QupZilla/qupzilla#2133]
Its actually the only issue that prevents me from using this browser, since its today used almost on any webpage.

https://patrickhlauke.github.io/recaptcha/

**Comment by cranes-bill** [comment]
How this should works!?
If i check „I'm not a robot“, then i can reload the image, using the _button on the bottom_ (see the picture)
![h5yyh](https://cloud.githubusercontent.com/assets/5161278/20859587/60d1a2aa-b96b-11e6-8930-c6ee7d808e81.png)

**Comment by sixsixfive** [comment]
![screenshot_20161203_144718](https://cloud.githubusercontent.com/assets/3780774/20859744/8fec5476-b967-11e6-9e2e-145269eb84cb.png)

**Comment by cranes-bill** [comment]
Works to me on the **WebKit** _version_ as well:
![capture du 2016-12-03 17-24-33](https://cloud.githubusercontent.com/assets/5161278/20860314/c6cfa888-b97d-11e6-8d46-1e29a6268f6f.png)

**Comment by sixsixfive** [comment]
Well I changed the user agent to:

```
Mozilla/5.0 (Linux) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.116 Safari/537.36
```

and it works any reason why id won't work with the default one?

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) QupZilla/1.8.9 Safari/538.1
```

**Comment by nowrep** [comment]
Please upgrade to QupZilla 2, this is working fine with QtWebEngine.
