### ISSUE TITLE
QupZilla hangs when something is put into the clipboard externally

### ISSUE THREAD

**Issue by OlafLostViking** [QupZilla/qupzilla#2138]
Whenever I copy some text in my editor, mail client, whatever with [CTRL]+[C], QupZilla hangs for (currently approx.) 10 seconds! Background tasks live a YouTube video still run (you can hear audio, the video is a still image). The only extension I am using at the moment is the KWallet integration.

ArchLinux AMD64 packages
Application version 2.0.2
QtWebEngine version 5.7.0

**Comment by nowrep** [comment]
Backtrace plase: 

`gdb qupzilla` <kbd>Enter</kbd>
`run` <kbd>Enter</kbd>
 ... wait for hang ... <kbd>Ctrl+C</kbd>
`bt` <kbd>Enter</kbd>

**Comment by OlafLostViking** [comment]
Thanks for answering. Since it's not crashing but only hanging, I cannot get a backtrace. But to be able to attach it to gdb nontheless, I had to make sure no other instance of QupZilla is running and killall'd them. After that, copying is fast again and I currently cannot reproduce it. _Perhaps_ an instance in the background (still running, no visible window) or the communication between them had problems? I'll report back, if I can reproduce it...

(However, my bookmarks still won't show up within just a few seconds (as described in #1679) ;-) )

**Comment by nowrep** [comment]
You can get backtrace, just follow the steps - pres Ctrl+C in terminal window with gdb when QupZilla hangs.

**Comment by OlafLostViking** [comment]
Ah! I'm sorry - now I understand what you expected. I'll keep it in mind until it happens again!
