### ISSUE TITLE
Sometimes we need to click twice to register the click

### ISSUE THREAD

**Issue by rohshall** [QupZilla/qupzilla#2140]
I love the browser. But what is preventing me from using it for all purposes is many a times, I need to click again on a button or a link to register that click. It happens on all sites including gmail, amazon, etc. So, it is not site-specific JS problem.

**Comment by nowrep** [comment]
What is your OS and QupZilla version?

**Comment by rohshall** [comment]
I am using QupZilla 2.0.2 on Arch and Ubuntu (16.04, 17.04).

**Comment by nowrep** [comment]
And your QtWebEngine version? You can find it in About QupZilla.

As to why it wasn't reported before, I have never experienced such issue.

**Comment by rohshall** [comment]
QtWebEngine's version is 5.7.1-1

**Comment by thedummy06** [comment]
I too have experienced this, it wasn't a deal breaker for me, but it happens in arch based systems.

**Comment by cranes-bill** [comment]
I have never faced similar issue in several QupZilla versions with several Qt versions exclude 5.7 (did not try), so perhaps another one Qt 5.7 bug.

**Comment by thedummy06** [comment]
I donno could just be arch lol things tend to break on ocassion

**Comment by nowrep** [comment]
Can you please try again with latest version?

**Comment by rohshall** [comment]
I can confirm that the newest version does not have this problem, and I am typing this from qupzilla. :) Thank you for fixing the bug.

**Comment by liar666** [comment]
Hi,

Indeed, I like QupZilla too, due to its lightness compared to the other bloatwares that call themselves browsers...

Unfortunately, I've just dist-upgraded to Ubuntu 18.04, and I face the same problem.

FYI, the versions are:
Application version 2.1.1
QtWebEngine version 5.9.5
