### ISSUE TITLE
Adblock. Incorrect deleting rules.

### ISSUE THREAD

**Issue by DebugReport** [QupZilla/qupzilla#2141]
To reproduce:
1. Open Adblock Configuration
2. Remove all custom rules
3. Close Adblock Configuration
4. Open again
5. Some rules restored (bag?)

**Comment by nowrep** [comment]
Which rules are restored?

**Comment by nowrep** [comment]
First two whitelist rules for duckduckgo cannot be removed. They are present to allow non-intrusive ads on duckduckgo.com. If you don't like it, you can disable those rules (but not delete them).
