### ISSUE TITLE
Version problem in KDE Neon distro user edition 

### ISSUE THREAD

**Issue by ravisharma1987** [QupZilla/qupzilla#2148]
Hi, 

When I execute this command: 
sudo apt-get install qupzilla

I can only download qupzilla version 1.8.9
I tried to update my sources with this command: sudo apt-get update and still I get the same version. 
How can I download the latest version in KDE Neon distro.

**Comment by cranes-bill** [comment]
The following related threads might help:
#1908
#1956
#1976
#2034
#2065
#2093

**Comment by nowrep** [comment]
http://blog.qupzilla.com/2016/12/qupzilla-2-on-debian-based-distributions.html
