### ISSUE TITLE
Add blocker

### ISSUE THREAD

**Issue by gericom-hummer** [QupZilla/qupzilla#2149]
@nowrep Can you in the future replace this hog Adblock with the opensource lightweight extension uBlock Origin
[https://github.com/gorhill/uBlock](https://github.com/gorhill/uBlock)

**Comment by nowrep** [comment]
If you have any issue with current AdBlock in QupZilla, please report it. It is custom implementation, it has nothing to do with Firefox addons.

**Comment by gericom-hummer** [comment]
No, i don't have any issues, but thought it can be as a wishlist, providing support for both addblockers, as uBlock is way more resource savvy. Thanks :)

**Comment by cranes-bill** [comment]
@gericom-hummer, i think this request should be addresed to [uBlock](https://github.com/gorhill/uBlock) owner, just to make a QupZilla plugin.

**Comment by sjehuda** [comment]
> If nothin changed dramatically QupZillas "AdBlock" has nocthin to do with AdBlock Plus or other wellknown Plugins. It's an own implementation in C++, so it should be (and is) really fast. It only uses AdBlock lists to get up-to-date block rules. So I think this could be closed.

See https://github.com/QupZilla/qupzilla/issues/1578#issuecomment-93736842 by @ff2000
