### ISSUE TITLE
Crash after restore session.

### ISSUE THREAD

**Issue by DebugReport** [QupZilla/qupzilla#2151]
[Crash-2016-12-29T06:07:59.txt](https://github.com/QupZilla/qupzilla/files/676671/Crash-2016-12-29T06.07.59.txt)
To reproduce:
1. Open any website
2. Press Ctrl + U or select 'Show Source Code'
3. Close qupzilla. Don't change tab. Stay on tab with source code.
4. Try to open qupzilla again. It's crashed everytimes.

Application version 2.0.99 (a4d284fa71)
QtWebEngine version 5.7.1

**Comment by nowrep** [comment]
https://bugreports.qt.io/browse/QTBUG-57826
