### ISSUE TITLE
Uncaught SecurityError: for an https site accessing a http frame

### ISSUE THREAD

**Issue by toralf** [QupZilla/qupzilla#2153]
I do wonder why such a case :

`Uncaught SecurityError: Blocked a frame with origin "https://staticxx.facebook.com" from accessing a frame with origin "http://www.eurosport.de".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.
`

is a security error, the opposite I'd understood

**Comment by nowrep** [comment]
What you don't understand? This is not about secure frame accessing unsecure, but same-origin policy https://en.wikipedia.org/wiki/Same-origin_policy

**Comment by toralf** [comment]
The explanation (2nd sentence) does not mention the origin, it is complaining the protocol.
