### ISSUE TITLE
IPv6 doesn't work

### ISSUE THREAD

**Issue by DebugReport** [QupZilla/qupzilla#2157]
For example http://[2001:470:1:18::119]

**Comment by nowrep** [comment]
Care to elaborate? This address is unreachable in both QupZilla and Firefox.

**Comment by DebugReport** [comment]
laptop% firefox 'http://[2001:470:1:18::119]'
laptop% firefox --version
Mozilla Firefox 50.1.0
In Firefox it's work fine. Not in Qupzilla.


> laptop% ping -c 1 ipv6.test-ipv6.com   
PING ipv6.test-ipv6.com(ip119.gigo.com (2001:470:1:18::119)) 56 data bytes
64 bytes from ip119.gigo.com (2001:470:1:18::119): icmp_seq=1 ttl=53 time=193 ms
--- ipv6.test-ipv6.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 193.129/193.129/193.129/0.000 ms

**Comment by nowrep** [comment]
Yeah, I didn't realize that my provider doesn't support ipv6, sorry.

**Comment by DebugReport** [comment]
Hmmm...And how can i help you?

**Comment by DebugReport** [comment]
Maybe I will provide access to wireguard vpn?

**Comment by DebugReport** [comment]
Or you can use Miredo https://www.remlab.net/miredo/

**Comment by DebugReport** [comment]
Now it's work.
Application version 2.0.99 (a4d284fa71)
QtWebEngine version 5.8.0
