### ISSUE TITLE
Try latest QupZilla without installation!

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#2158]
### QupZilla app image

Here is a single file for Linux that contains most recent commit of QupZilla and all the Qt 5.8 libraries needs to run of most x86_64 Linux distributions.
You can just run it _out of the box_, no installation and root access needed.

[ **DOWNLOAD**](https://yadi.sk/d/hC9kgLNB37PBSv)

**Comment by nowrep** [comment]
I've been trying AppImage too, but it needs *ton* of bundled libraries.

Flatpak is now the official method: http://blog.qupzilla.com/2017/01/qupzilla-for-flatpak.html

**Comment by cranes-bill** [comment]
I created it manually, so it just contains only the Qt libraries.

**Comment by nowrep** [comment]
Then it will only work for users with same distro as yours.

**Comment by cranes-bill** [comment]
I compiled QupZilla with "_compatibility_" GlibC header and Qt libraries are precompiled  from the official **Offline Installer**, then i did a test on several distributions (on virtual machine) and it was working. 
May you test it yourself on your distribution, please!

**Comment by Martii** [comment]
> test it yourself on your distribution

Launches under ROSA and I definitely don't have Qt/QtWebEngine 5.8.0 natively. Tested OUJS and YT.

**Comment by cranes-bill** [comment]
@Martii, thanks!

**Comment by iondissonance** [comment]
openSUSE Tumbleweed, all works

**Comment by cranes-bill** [comment]
Thanks a lot! That's a very good news.

**Comment by nowrep** [comment]
Works fine for me too on Arch. The question is whether it'll work on some older Ubuntu...

**Comment by cranes-bill** [comment]
I'm not familiar with Ubuntu versions, but i did a test on Debian 8.6.0 and it was working. I just should try on Debian 7.
Also, due to i don't know which Qt plugins are really in use, i included all off them, but those that are unusable might be removed, furthermore there is some of them with unresolved dependencies.
Then i may try to write a script for auto build.
By the way, the package might be released as self-extracting archive as well.

**Comment by Martii** [comment]
@nowrep 

> Flatpak...

This isn't in my package repository and dev station anywhere so it probably won't be until Plasma become mores stable *(not sure where this is at in the timeline anyhow)*. In general I'd be more inclined to try out an app style package which is very similar to the OS X package I supply for everyone here.

**Comment by cranes-bill** [comment]
Yeah, Flatpak has too much requirements and AFAIK it does not works on kernel lower then 4.X.X
I'm not sure about the compression method in OS X, but i think the _AppImage_ variant is most likely similar.
Regarding the self-extracting archive, i meant [this](https://github.com/megastep/makeself), but the script header should be modified a bit to make possible to accept QupZilla arguments.
:flushed: I really sorry for my bad English, i hope you understand me!

**Comment by probonopd** [comment]
AppImages are always compressed by default. No need to do anything special.

**Comment by nowrep** [comment]
@cranes-bill Can you please share the script used to create the AppImage? I'd like to offer it as a download option with next version.

**Comment by probonopd** [comment]
...but please don't put the AppImage into yet another archive ([rationale](https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages#common-mistake)). Thanks!

**Comment by probonopd** [comment]
Since you are already using [Travis CI](https://github.com/QupZilla/qupzilla/blob/master/.travis.yml), it would probably be best to hook in AppImage generation similar to what [these projects](https://github.com/search?o=desc&q=%22Package+the+binaries+built+on+Travis-CI+as+an+AppImage%22&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93) do.

**Comment by cranes-bill** [comment]
@nowrep, perhaps @probonopd already provides a better solution (i did not test it)
Anyway, i did not use a script. Just used the **ld** to see which _Qt libraries_ are needed. I also included all of _plugins_ and _qml_ dir, but more of them probably are not needed, so it's fine to not be included. 
I also included the `libcrypto.so.10` because the linker looking for it, but it's not present of most of the systems. I think when you compile QupZilla on your system, including of this library will not be needed.
After copying the  libraries, i set the `RPATH`s, but that's not a mandatory if you set the `LD_LIBRARY_PATH` in the startup script, maybe only for QtWebEngineProcess binary.
Please check the extracted folder for full content and `RPATH` sets!
Otherwise, to compile QubZilla i'm using an header generated by [LibcWrapGenerator](https://github.com/probonopd/AppImageKit/tree/master/LibcWrapGenerator)
To create a binary, i'm using the [runtime](https://github.com/probonopd/AppImageKit/blob/appimagetool/master/runtime.c), where even i was lazy to compile and just extracted it from already generated app, then i [manually](https://github.com/probonopd/AppImageKit#appimagetool-usage) generate an app image.
I may try to build a script for all of those procedures, but this probably might be the next week.
You probably might also need to include some licences...
If you find something unreadable in my _excellent English description_ :stuck_out_tongue_winking_eye:, or just have some other questions, you are always welcome to ask me, you know :+1:!


@probonopd 
This is just a _test package_ (_unofficial_ :stuck_out_tongue:), and in a biggest part a provocation of @nowrep :wink: to do it himself, so that's the reason where some rules for upload and included files are not respected.
Sorry for my bad English!

**P.S.:** _The irony here is that i'm even avoid of precompiled packages_ :smile:

**Comment by cranes-bill** [comment]
A quick [job](https://raw.githubusercontent.com/cranes-bill/qupzilla_autobild/master/qupzilla_autobild), but should works.

**Comment by probonopd** [comment]
@cranes-bill wow, it looks you have done by hand everything that [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) is supposed to automate...

**Comment by cranes-bill** [comment]
Actually i was already have done that and thought to make it as self extracting archive. Then i started to looking how to compile QupZilla to be compatible with other distributions and found the Appimage, but to be honest, i was not try the Linuxdeployqt.
Now, since i tested it, it feels good.
> do you see anything that should be changed

Maybe this:
_Linuxdeployqt_ looking for qtwebengine ***.pak** and ***.dat** resources in **libexec** dir, but in Qt 5.8 package [here](http://download.qt.io/official_releases/qt/5.8/5.8.0/), they are in **resources**, so if that's not my fault, you may look at that.

Sorry for the bad English!

**Comment by Martii** [comment]
Just wanted to give a heads up as it is loosely related. Compiled QupZilla with **Qt 5.8** for **OS X** and it's not pretty. Qt 5.7.1 seems to be fine other than a glitch in QupZillas build structure configuration with libraries.

1. Installation screen *(drag QupZilla to Application)* is absent of background and indication to drag and drop to Applications folder.
2. Crashes and optionally sends a report to Apple *(which I did)* on launch.

**Comment by probonopd** [comment]
@cranes-bill 
> Linuxdeployqt looking for qtwebengine *.pak and *.dat resources in libexec dir, but in Qt 5.8 package here, they are in resources, so if that's not my fault, you may look at that.

Yes, that is a known issue being tracked at https://github.com/probonopd/linuxdeployqt/issues/57.

**Comment by nowrep** [comment]
AppImage can now be downloaded from homepage, closing this issue now.

**Comment by probonopd** [comment]
Thanks @nowrep
