### ISSUE TITLE
Audio not playing on Duolingo.com

### ISSUE THREAD

**Issue by Kalimunana** [QupZilla/qupzilla#2163]

**Comment by JuPlutonic** [comment]
You should provide some kind of information like OS, OS version, (Flash\PepperFlash in use in your setup), 

may be this tutorial kind of help for you, if you're a linuxoid: [https://github.com/QupZilla/qupzilla/wiki/Knowledgebase#4-html5-video-support](url)

Now I'll test official Adobe's flash 'cause Duolingo flashes someth. like:
========================
We can't play sound in your browser.
close
Your Flash version is too old. You need Flash version 8 or higher. Go here to download a more recent version.
Sound still not working? Go to the settings page in the top right corner to disable the speaker
========================

**Comment by JuPlutonic** [comment]
Ooops, I thinlk I need to recompile qupzilla after pepperflash installation (I will choose 2.0.2 version of sources).

**Comment by JuPlutonic** [comment]
The problem have gone: recompiled qupzilla, two times restarted the browser.
And Duolingo.com **works** without any flaws!

**Comment by JuPlutonic** [comment]
**QT 5.8.0 Qupzilla 2.0.99 (Master)** pepper flash works without refreshing (no "We can't play sound in your browser" window).

**Comment by JuPlutonic** [comment]
Qt 5.9, d6b142b 2.1.99 ([V] pepper rlugin allowed)- all bad also got theese installed:
`adobe-flash-properties-gtk 1:20170616.1-0ubuntu0.16.04.1amd64
adobe-flashplugin 1:20170616.1-0ubuntu0.16.04.1 amd64
pepperflashplugin-nonfree 1.8.3-0york3~16.04 `
Now trying to remove with `flashplugin-installer`

**Comment by gmng** [comment]
i have still this issue too. 
Win 10 64bit
Browser version 2.2.0
QtWebEngine 5.9.1
