### ISSUE TITLE
Opera 12.15 source code.

### ISSUE THREAD

**Issue by DebugReport** [QupZilla/qupzilla#2165]
Maybe something will be useful?
https://github.com/prestocore/browser

**Comment by DebugReport** [comment]
Mirror - https://bitbucket.org/prestocore-fan/presto/

**Comment by cranes-bill** [comment]
i also do not like the _„Google shits“_, but failed to understand, what is your idea here.
Something as advertisement or .....!?
I think here is not the right place for that.

**Comment by nowrep** [comment]
I don't really care about Opera source code (much less it being apparently stolen), sorry.
