### ISSUE TITLE
Clicking "Show icons only" in bookmarks toolbar, crashes Qupzilla

### ISSUE THREAD

**Issue by cptr13** [QupZilla/qupzilla#2166]
Clicking "Show icons only" in bookmarks toolbar, crashes Qupzilla
Not sude if this helps.  Running Kannolo (Fedora 25, pure kde), Plasma 5.8.5

**Comment by iondissonance** [comment]
All works, openSUSE Tumbleweed

**Comment by nowrep** [comment]
Can you please post backtrace?

**Comment by cptr13** [comment]
ok, wow, thanks for the quick response.  This could very easily be a distro specific issue.  Bug reporting is new to me, so let me know what information you need and I'll happily get it to you.  Here is the backtrace.

[Crash-2017-01-14T11:38:30.txt](https://github.com/QupZilla/qupzilla/files/706068/Crash-2017-01-14T11.38.30.txt)

**Comment by cptr13** [comment]
awesome...mind explaining what it is?  I'd like to fix it on my system.  I'm not that technical...so small words please :)

**Comment by nowrep** [comment]
Dereferencing of unitialized pointer. You will need to build yourself from git latest `master` or wait for new release.

**Comment by cptr13** [comment]
ok.  I'll rebuild.  Thanks!
