### ISSUE TITLE
Default Zoom level is not respected.

### ISSUE THREAD

**Issue by klundry** [QupZilla/qupzilla#2168]
In preferences>browsing when setting the "Default Zoom on Pages" option, the choice of default zoom level does not change the zoom level of web pages.  I can change it to anything other than 100% but when I open a new web page it still loads at 100%.

**Comment by thedummy06** [comment]
I've noticed the default zoom level is respected if you use a speed dial version of the page when it was first set, but if you type the site name again it changes back to default.

**Comment by nowrep** [comment]
Already fixed in `master`, will be in next version.

**Comment by Vistaus** [comment]
I'm currently experiencing this bug with QupZilla Git Master for a while now. Using Qt 5.8 on Solus.
