### ISSUE TITLE
Some crashes

### ISSUE THREAD

**Issue by iondissonance** [QupZilla/qupzilla#2171]
[Crash-2017-01-21T16:25:02.txt](https://github.com/QupZilla/qupzilla/files/721699/Crash-2017-01-21T16.25.02.txt)
[Crash-2017-01-20T12:56:54.txt](https://github.com/QupZilla/qupzilla/files/721701/Crash-2017-01-20T12.56.54.txt)
[Crash-2016-12-16T01:52:45.txt](https://github.com/QupZilla/qupzilla/files/721700/Crash-2016-12-16T01.52.45.txt)

**Comment by iondissonance** [comment]
crashes will occur when more sites opened, most active using is https://vk.com/

**Comment by JuPlutonic** [comment]
I sometimes work with vk.com, m.vk.com and can test it with 2.0.2 version of the browser.
I saw what 2.0.2 in drastically better than 2.0.1 (this version is in your backtraces) on my setups.  Much less glitches and for that moment no crashes.

**Comment by JuPlutonic** [comment]
**Can't reproduce**: [http://i.imgsafe.org/4dfa3eb0d3.png](http://i.imgsafe.org/4dfa3eb0d3.png)

**Comment by JuPlutonic** [comment]
The crush IMO is plugin related: To reproduce use Adblock in the context menu on any place of vk.com.
Qupzilla **2.0.2**, QtWebEngine 5.7.1 
[Crash-2017-01-22T20:45:09.txt](https://github.com/QupZilla/qupzilla/files/722210/Crash-2017-01-22T20.45.09.txt)
[Crash-2017-01-22T20:45:21.txt](https://github.com/QupZilla/qupzilla/files/722211/Crash-2017-01-22T20.45.21.txt)

**Comment by nowrep** [comment]
Can you please get full backtrace with gdb and debugging symbols?

**Comment by JuPlutonic** [comment]
Ok compiling with  _CONFIG += debug_

**Comment by nowrep** [comment]
Great, I'm interested only in the first backtrace, where it crashes inside AdBlock.

**Comment by JuPlutonic** [comment]
It sth. impossible... when I put in cookies from old .config/qupzilla - refresing vk.com and waiting when vk.com start to show ads. Now adblok quikckly removing any ads and, if it could use on ad ContextMenu_Adblock_useOnVk.com in advance non crashes ad will removed with other ads in the same page by adlock.
I think I need to add Greasemonkey Settings and Add ReekAntiAdblockFilter to complete observation and to cutch that crash.

**Comment by JuPlutonic** [comment]
Nothing happened. Can't reproduce at all...

**Comment by iondissonance** [comment]
Elusive bugs. :-(

**Comment by iondissonance** [comment]
Can't debug qupzilla with gdb https://gist.github.com/iondissonance/36b5eba0691afa893a53b98f683814f0

**Comment by nowrep** [comment]
Just type `continue` <kbd>Enter</kbd>

**Comment by iondissonance** [comment]
Thanks, all works, I will always run qupzilla with gdb and wait elusive crashes. Qtwebengine debuginfo and other qt debuginfo packages installed too.

**Comment by iondissonance** [comment]
Wow! Two bugs when disable/enable adblock on http://vk.com/. Different backtraces.
backtrace1 https://gist.github.com/iondissonance/f8a39d2876162dbd861354af19fea87a
backtrace2 https://gist.github.com/iondissonance/e6b507859a1f5b23cdc5294a2c8b21ec

**Comment by iondissonance** [comment]
lol, bug is not reproduce now. magic

**Comment by nowrep** [comment]
With disable/enable adblock, do you mean globally disable/enable AdBlock in settings? Or just setting "disable on vk.com" from contextmenu?

**Comment by iondissonance** [comment]
>setting "disable on vk.com" from contextmenu?

This.

**Comment by iondissonance** [comment]
backtrace3 https://gist.github.com/iondissonance/f35d855f5128da6bc8f43f95cbc77f47
when disable/enable adblock from context menu on **this page**.

**Comment by nowrep** [comment]
Just to be sure, what QupZilla version do you have?

**Comment by iondissonance** [comment]
_qupzilla-2.0.99.git.20170123T091446.7c79858.tar.xz_ now, when i did backtraces version was _qupzilla-2.0.99.git.20170122T204341.7738deb.tar.xz_, _qupzilla-2.0.99.git.20170122T091843.ae44997.tar.xz_, _qupzilla-2.0.99.git.20170121T223651.b5eda4f.tar.xz_

**Comment by iondissonance** [comment]
backtrace4 https://gist.github.com/iondissonance/1973fc44b268e56748e902f99a4a55eb on 24b6db8 build.
this page, disable adblock, enable adblock, disable adblock, F5, enable adblock, disable adblock => crash

**Comment by nowrep** [comment]
Tracked now in #2231
