### ISSUE TITLE
QupZilla leaks local IP address through WebRTC

### ISSUE THREAD

**Issue by theodis171** [QupZilla/qupzilla#2172]
QuZilla reveals the local IP address to websites through WebRTC.
Steps:
1. Start QupZilla
2. Open link https://diafygi.github.io/webrtc-ips/
3. Local IP addresses are shown

Expected behaviour:
There should be nothing to see

Configuration information:
Application version: 2.0.2
Qt version: 5.7.0
Platform: Linux

Additional info:
In Mozilla Firefox, this can be rectified by typing ‘about:config’ into the search bar and browsing to the ‘media.peerconnection.enabled’ option and setting it to FALSE.
In Google Chrome, there is an add-on called WebRTC Leak Prevent. Can be seen here: https://chrome.google.com/webstore/detail/webrtc-leak-prevent/eiadekoaikejlgdbkbdfeijglgfdalml?hl=en

**Comment by DebugReport** [comment]
https://github.com/QupZilla/qupzilla/issues/1926
