### ISSUE TITLE
Q: All things Flash

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla#2177]
So I decided to relook into this for OS X, and perhaps some other platforms soon, and found some information that needs some clarification.

Refs:
1)  https://github.com/QupZilla/qupzilla/issues/1912#issuecomment-204756468 *(dead link now but with https://www.archlinux.org/packages/?sort=&arch=any&q=pepper-flash&maintainer=&flagged= it shows as non-existent)*. Where did it go for ArchLinux?

2) http://www.adobe.com/software/flash/about/
Shows that Chromium/Chrome based browsers are PPAPI now with 24.0.0.194 It was my understanding that backend of QtWebEngine is Chrome/Chromium based. Is this correct or not?

3) `brew install pepper-flash` returns with `No available formula with the name "pepper-flash"`. Also retried without the hyphen. Web ref of http://macappstore.org/pepper-flash/

4) Checked the OS X App Store for anything related to "pepper", "pepper-flash", and "pepperflash" ... nothing found.

I do have Adobe Flash for OS X installed now and it does show up in Moz products *(NPAPI)* and Chrome *(PPAPI... since it is probably embedded... need to see if Chromium exists for Mac to test for non-embedded I think)*... but would be nice to have a more detailed explanation as to QupZilla compatibility with Chromium/Chrome plugins.

5) https://forum.voidlinux.eu/t/chromium-pepper-flash-is-dead-new-template/1500 claims that Adobe is hosting all Flash now for all platforms. So what is QupZilla's next step for support?

I. Why doesn't QupZilla detect the PPAPI version of Adobe Flash *(which is similar and the same wrapper technology to pepper-flash)*?
II. Does Qt support PPAPI plugins natively? *(reminder that pepper-flash is PPAPI)*.
III. Read [the FAQ here](https://github.com/QupZilla/qupzilla/wiki/FAQ#4-qupzilla-is-using-a-lot--of-my-cpu-what-can-i-do-to-cool-it-down) a few times just to ensure that QupZilla was enabling this. But a simple web page test of http://ultrasounds.com shows that it's not loading in QupZilla.

Thanks for some insight.

Historical Refs:
* https://github.com/QupZilla/qupzilla/search?q=flash&type=Issues&utf8=%E2%9C%93

**Comment by cranes-bill** [comment]
When i really need a flash, i'm using it as follow:
`qupzilla --ppapi-flash-path=/path/to/libpepflashplayer.so`

**Comment by JuPlutonic** [comment]
Comment on **3** (how to get pepper flash with Homebrew):

1. `brew tap caskroom/cask` (OR `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null ; brew install caskroom/cask/brew-cask 2> /dev/null` if you don't have Homebrew installed)
2. `brew cask install pepper-flash`

**Comment by nowrep** [comment]
As you can see here: https://doc.qt.io/qt-5/qtwebengine-features.html#pepper-plugin-api

Flash plugin should be in
```
/Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin
```

PPAPI are loaded by the QtWebEngine (Chromium) and there is no way to change the paths where it looks.

**Comment by Martii** [comment]
> there is no way to change the paths where it looks.

There is always a symbolic link if the dereferencing is done correctly in QupZilla, Qt and V8. I'll give it a shot for Adobes PPAPI at that path of `/Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin` hopefully next week since they have taken over the responsibilities for PepperFlash.

So that leaves the question of the missing distribution on AUR... presumably the authors of PepperFlash removed it in favor of Adobe's.

Thanks for some insights everyone.
