### ISSUE TITLE
Tab name not refreshing

### ISSUE THREAD

**Issue by iondissonance** [QupZilla/qupzilla#2179]
When i receive new message on https://vk.com/ in firefox tab name flashing "1 new message", but not in QupZilla.

**Comment by Martii** [comment]
Never seen this in Fx... is this in a clean profile with no add-ons? The tab manager in Moz projects isn't site scriptable with flashing to my knowledge however an add-on may.

**Comment by iondissonance** [comment]
All works, sorry, notifications on vk.com were disabled.

>Never seen this in Fx

Yes, there is without addons and with clean profile. And in QupZilla too. 

Close issue please.

**Comment by Martii** [comment]
I don't have permissions to close but you probably do... Comment and close below.

**Comment by iondissonance** [comment]
thanks
