### ISSUE TITLE
OS X: Some menu icons missing

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla#2180]
I've been away doing other things but slowly getting back into the swing of things here.

The issue is in OS X current head of 24b6db866a7239655d796ae0c53a3ce58ac1a61d

With some of the conversions of PNGs to SVGs they seem to be missing in certain views. This is best shown by the below highlighted image. The VNC viewer is OS X and the image below is the VM of openSUSE *(yes there was a "method to the madness" in getting a platform where I could compile the current HEAD for comparison)*.

<img src="https://cloud.githubusercontent.com/assets/114709/22248245/eb8d8a82-e1fa-11e6-83ec-c42bba1866b7.png" width="102" height="64" title="missing icons"/>

**Comment by nowrep** [comment]
You must include Qt Svg Icon Image Plugin in the bundle.

**Comment by Martii** [comment]
Well if you expect me to do that for distribution then you'll have to walk me through it... the whole Qt 5.7.1 was installed on OS X so it makes it valid. Thanks. I am not using the online installer under OS X since it's basically a blank slate and that's for Linux.

**Comment by nowrep** [comment]
It should be done by `macdeployqt` that is invoked with `mac/macdeploy.sh` script. I'm not sure where exactly the plugins will be, but it is somewhere inside the bundle. So you should take a look and make sure it's there.

In Qt installation they are in `$QTDIR/plugins/` and you specifically want `$QTDIR/plugins/imageformats/libqsvg.dylib`

**Comment by Martii** [comment]
This is the folder dump:

```
$ pwd
/Users/user/Qt/Qt5.7.1/5.7/clang_64/plugins
$ ls
audio/           geoservices/     playlistformats/ sensorgestures/
bearer/          iconengines/     position/        sensors/
canbus/          imageformats/    printsupport/    sqldrivers/
designer/        mediaservice/    qmltooling/
generic/         platforms/       sceneparsers/

$ cd imageformats
$ ls
libqdds.dylib*               libqmacjp2_debug.dylib*
libqdds.dylib.dSYM/          libqmacjp2_debug.dylib.dSYM/
libqdds_debug.dylib*         libqsvg.dylib*
libqdds_debug.dylib.dSYM/    libqsvg.dylib.dSYM/
libqgif.dylib*               libqsvg_debug.dylib*
libqgif.dylib.dSYM/          libqsvg_debug.dylib.dSYM/
libqgif_debug.dylib*         libqtga.dylib*
libqgif_debug.dylib.dSYM/    libqtga.dylib.dSYM/
libqicns.dylib*              libqtga_debug.dylib*
libqicns.dylib.dSYM/         libqtga_debug.dylib.dSYM/
libqicns_debug.dylib*        libqtiff.dylib*
libqicns_debug.dylib.dSYM/   libqtiff.dylib.dSYM/
libqico.dylib*               libqtiff_debug.dylib*
libqico.dylib.dSYM/          libqtiff_debug.dylib.dSYM/
libqico_debug.dylib*         libqwbmp.dylib*
libqico_debug.dylib.dSYM/    libqwbmp.dylib.dSYM/
libqjpeg.dylib*              libqwbmp_debug.dylib*
libqjpeg.dylib.dSYM/         libqwbmp_debug.dylib.dSYM/
libqjpeg_debug.dylib*        libqwebp.dylib*
libqjpeg_debug.dylib.dSYM/   libqwebp.dylib.dSYM/
libqmacjp2.dylib*            libqwebp_debug.dylib*
libqmacjp2.dylib.dSYM/       libqwebp_debug.dylib.dSYM/

$ ls libqsvg*
libqsvg.dylib*       libqsvg_debug.dylib*

libqsvg.dylib.dSYM:
Contents/

libqsvg_debug.dylib.dSYM:
Contents/
```

**Comment by nowrep** [comment]
Yes, that's fine. And now you must move it inside the bundle.

**Comment by Martii** [comment]
> It should be done by `macdeployqt` that is invoked with `mac/macdeploy.sh` script.

It doesn't appear to be doing that which leads me to this issue of you asking:

> And now you must move it inside the bundle.

Please remember that OS X is my least familiar platform. So if it's not in the deploy shell script then that's when the help is needed.

**Comment by nowrep** [comment]
`QupZilla.app` is just directory, so copy the needed plugins to the appropriate place there.

**Comment by Martii** [comment]
Are there any other plugins that I should be placing in there as well?

**Comment by nowrep** [comment]
If everthing else works, then no. Also, the needed plugin is `iconengines/libqsvgicon.dylib`, sorry.

Generally you need only iconengines, platform plugin, sqlite driver and printsupport.
