### ISSUE TITLE
fanpage.it no playing videos: smth going crazy with focus - play button cann't be clicked

### ISSUE THREAD

**Issue by JuPlutonic** [QupZilla/qupzilla#2186]
https://youmedia.fanpage.it/video/aa/WIs6i-Sw5oNkj1FY
etc.
Videos in other browser run in the autoplay mode. On current master Qupzilla doesn't autoplay and if you try to click play button in center of a video, some text near a video will be selected...

**Comment by nowrep** [comment]
You need to build QtWebEngine with proprietary codecs.

**Comment by JuPlutonic** [comment]
Ok

**Comment by JuPlutonic** [comment]
Also need to find out if Videoner 0.2.0 with Media Elements Tab activated [Enable media element support] & [Use custom external application] and self-created file descripted here [QupZilla-Plugins - Wiki -Videoner](https://github.com/QupZilla/qupzilla-plugins/wiki/Videoner#configuration)
