### ISSUE TITLE
http://0.0.0.2/ tab added to the 'restored' ones

### ISSUE THREAD

**Issue by funghetto** [QupZilla/qupzilla#2188]
When I open QupZilla it add a tab with this address to the 'restored' ones.
I attach my configuration informations.
[qu.txt](https://github.com/QupZilla/qupzilla/files/739923/qu.txt)

**Comment by nowrep** [comment]
I don't really understand, what do you mean with "restored" ones? Can you please post screenshot?

**Comment by funghetto** [comment]
I mean that I chose the option 'After launch: Restore Session '.

![2017-02-07_190748_662471797](https://cloud.githubusercontent.com/assets/17205637/22704711/efd71120-ed68-11e6-8cfa-adf3cd9a0540.png)

**Comment by nowrep** [comment]
And if you close the tab and restart the browser, it is still there?

**Comment by funghetto** [comment]
Yes

**Comment by nowrep** [comment]
Unfortunately, I can't really reproduce it and have no idea what could be wrong.
Can you please test with latest QupZilla (2.1.1) and confirm that the issue is still there? Also, can you please try it with new profile?

**Comment by funghetto** [comment]
Whoops, it was a mistake on my alias.
