### ISSUE TITLE
Forward/Back mouse buttons only work when opening sites from speed dial.

### ISSUE THREAD

**Issue by klundry** [QupZilla/qupzilla#2191]
This is a rather odd one.  If I open a new tab and click on a page in speed dial, I can then use the side buttons on my mouse to navigate forward and back as expected. As soon as I type a url or do a search in the URL bar I lose the ability to navigate with the mouse buttons in that tab.

**Comment by nowrep** [comment]
Works fine here, what is your QtWebEngine version?

**Comment by klundry** [comment]
5.7.0

**Comment by nowrep** [comment]
Can you please test again with latest QupZilla (2.1.1) and Qt (5.8)?

**Comment by klundry** [comment]
Yes, forward/back are working as normal now.
