### ISSUE TITLE
[Bundle][20170202]Drop down list cannot be displayed

### ISSUE THREAD

**Issue by lonicerae** [QupZilla/qupzilla#2192]
Hello,

Drop down list cannot be shown correctly. Please see the attachment.

Thanks and Regards,
Flos

**Comment by lonicerae** [comment]
[droplist-not-working.zip](https://github.com/QupZilla/qupzilla/files/749562/droplist-not-working.zip)

**Comment by cranes-bill** [comment]
Hm, that's the same out of the bundle to me, so i need a help here!
May somebody reject (or confirm) this with self-compiled QupZilla and Qt 5.8, please!

**Comment by cranes-bill** [comment]
OK, i tested it on a virtual machine and everything works fine, so my guess the broblem is related to GPU acceleration....

**Comment by nowrep** [comment]
https://bugreports.qt.io/browse/QTBUG-58488

**Comment by lonicerae** [comment]
Confirmed this issue also exists in QT 5.8. I just built the latest qupzilla with official released qt-5.8 bundle.

**Comment by nowrep** [comment]
It should be *only* in Qt 5.8.

**Comment by lonicerae** [comment]
Oh, okay, I originally thought the app bundle was using Qt 5.7.
