### ISSUE TITLE
[bundle][20170202] Qupzilla crashes when closing a tab.

### ISSUE THREAD

**Issue by lonicerae** [QupZilla/qupzilla#2194]
Hello,

It's me again.. Sorry.. :smile: 
Just after reporting the last issue and closing the tabs after the current page, qupzilla crashed. I'm attaching the last log and the crash report. Thank you!

**Comment by lonicerae** [comment]
[qupzilla_lastlog.txt](https://github.com/QupZilla/qupzilla/files/752066/qupzilla_lastlog.txt)
[Crash-2017-02-04T15:09:39.txt](https://github.com/QupZilla/qupzilla/files/752067/Crash-2017-02-04T15.09.39.txt)

**Comment by lonicerae** [comment]
Should be the same issue. One more crash log:
[Crash-2017-02-04T16:25:02.txt](https://github.com/QupZilla/qupzilla/files/752139/Crash-2017-02-04T16.25.02.txt)

**Comment by cranes-bill** [comment]
Sorry about that! Looks like the _**bundle**_ is not quite compatible with your system, but we should wait what @nowrep will say. You may try to build it yourself. Just download Qt 5.8 from [here](http://download.qt.io/official_releases/qt/). Then install it anywhere (you might choose a temporary directory _(no root access will needed)_ like `/tmp/qt58` for example) and run [this](https://raw.githubusercontent.com/cranes-bill/qupzilla_autobild/master/qupzilla_autobild) script.
BTW, may you run the following command `coredumpctl list` and attach the output here, thank you!

**Comment by nowrep** [comment]
Yes, I don't take bugreports for the appimage bundle. I have now released `2.1.0`, it would be great if you can test it against this release.

**Comment by nowrep** [comment]
@cranes-bill Can you please create 2.1.0 appimage and send it to my e-mail? Thanks

**Comment by cranes-bill** [comment]
Sure, it's done.

**Comment by lonicerae** [comment]
Hey @cranes-bill @nowrep , good, I will try to build QT5.8 and the latest qupzilla on my system. And it's more convenient for debugging the coredump file for me. Thanks a lot! :+1:

**Comment by Martii** [comment]
@nowrep 
I can retry to build against Qt 5.8 but it wasn't stable last week and crashed even before it would launch. In releases it would helpful to know what you want me to attempt to build it with before I send you an email for OS X. Thanks.

**Comment by Martii** [comment]
Definitely failing on macdeploy.sh with 5.8 ... this is new... bunch of missing QupZilla resources... building with 5.7.1 for your release. Will upload in a few.

**Comment by Martii** [comment]
Mailed.
