### ISSUE TITLE
Endless spinner when adding new speed dial entry

### ISSUE THREAD

**Issue by gbcox** [QupZilla/qupzilla#2197]
Appears to be similar to #1925 
With 2.1.0 when I try to add a speed dial entry, I get an endless spinner.  When going back into settings what I entered is now blanked out - as if I never entered a URL.

**Comment by nowrep** [comment]
Your QupZilla & QtWebEngine versions?

**Comment by gbcox** [comment]
Application version 2.1.0
QtWebEngine version 5.7.1

This is occurring in the Fedora build for 2.1.0 which is currently in testing.  The production version (2.0.2) does not have this issue.  Here is the Fedora bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1419915

**Comment by nowrep** [comment]
Can you please post terminal output when you try to add entry?

**Comment by gbcox** [comment]
It doesn't say much:

$ qupzilla
QupZilla: 1 extensions loaded

**Comment by kkofler** [comment]
You will probably want to enable the debug output, which is disabled by default in Fedora.
https://brendanwhitfield.wordpress.com/2016/06/08/enabling-qdebug-on-fedora/

**Comment by gbcox** [comment]
Thanks Kevin... just did that... same result.
