### ISSUE TITLE
Sometimes asking for more  memory without reason

### ISSUE THREAD

**Issue by stefonarch** [QupZilla/qupzilla#2199]
> Failed loading page
Something went wrong while loading this page.
Try reloading the page or closing some tabs to make 
more memory available.

One example for  reproduce, tested with clean profile and only one or 2 tabs open:
https://www.pentaxforums.com/lensreviews/ click any link for one of the  lenses

But middle clicking works well indeed, opening always the same link with no error in next tab.

8gb ram, i5 64bit, arch linux, qupzilla git v2.1.0.r0.g4062473e-1

**Comment by nowrep** [comment]
When you see this page (`Something went wrong while loading this page.`) it means that render process crashed. That is, the crash is inside QtWebEngine/Chromium.

**Comment by stefonarch** [comment]
ok, so it crashes in the same tab but not in a new one. Is there a bugtracker for qtwebengine?

**Comment by nowrep** [comment]
https://bugreports.qt.io/browse/QTBUG/component/21421/?selectedTab=com.atlassian.jira.jira-projects-plugin:component-summary-panel

**Comment by stefonarch** [comment]
Not present anymore.
