### ISSUE TITLE
Add support for horizontal scrolling

### ISSUE THREAD

**Issue by drtwisted** [QupZilla/qupzilla#2200]
It would be realy nice to be able to scroll page horizontally not only by using the horizontal scrollbar directly. FF, Chrome, etc., recognize the horizontal scrolling input and behave correspondingly. This doesn't work for me on Linux with SHIFT+ScrollWheel (Qupzilla version 2.1.0, QtWebEngine version 5.8.0)

**Comment by TimothyXL** [comment]
It seems to work fine on Qupzilla version 2.1.2, QtWebEngine version 5.9.1.

**Comment by drtwisted** [comment]
Yes, works for me as well!
