### ISSUE TITLE
High CPU usage with pages containing <animate>

### ISSUE THREAD

**Issue by tsujan** [QupZilla/qupzilla#2201]
QupZilla takes a considerable amount of CPU time when it opens pages whose html codes contain lines like these:
````
  <animate attributeName="y1" values="0%; 100%" dur="1s" repeatCount="indefinite"></animate>
  <animate attributeName="y2" values="100%; 200%" dur="1s" repeatCount="indefinite"></animate>
````
It shows this message too:
````
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
````

This is Linux (Manjaro) with QupZilla 2.1.0 and QtWebEngine 5.8.0 but the problem existed in QupZilla 2.0.x compiled against QtWebEngine 5.7.0 too.

**Comment by nowrep** [comment]
You should report it to Qt bug tracker.
