### ISSUE TITLE
Audio HTML5 issue

### ISSUE THREAD

**Issue by Yaruowsu** [QupZilla/qupzilla#2204]
while using vk.com on W 8.1 website doesnt allow to play HTML5 video/audio content, telling me it need a Flash player, tho any other browser play it no problems without it. Youtube works just fine, somehow. Tried to change user-agent, cleared cashe/cookies, didnt helped

**Comment by cranes-bill** [comment]
Your QtWebEngine version probably don't have **proprietary codecs** support.
Example [test page](http://www.quirksmode.org/html5/tests/video.html)

**Comment by Yaruowsu** [comment]
Well, yeah H.264/MP4 doesnt work on page you linked. How do i fix it? Im on Windows 8.1, running binaries downloaded from main site O-o

**Comment by cranes-bill** [comment]
Sorry. i'm not familiar with Windows!
Even though, **AFAIK** distribution of QtWebEngine with those codecs enabled is illegal, so the only way _(that might sounds „scary“ for some Windows users)_ is to build it yourself.

**Comment by Yaruowsu** [comment]
Id build it if i were using linux, but on windows i guss ill pass it. Linux better for this purpose
