### ISSUE TITLE
hardware acceleration support

### ISSUE THREAD

**Issue by Gibbz** [QupZilla/qupzilla#2207]
Ive given qupzilla a quick whirl. The first thing of note however is how slow it is on my gaming rig. Gave up after that... Looks to have potential though.
Is there planned support for some kind of hardware acceleration?

**Comment by troffasky** [comment]
Given the existence of the --disable-gpu command line parameter, I would say that Qupzilla already thinks it is hardware-accelerated.

**Comment by Gibbz** [comment]
Do i need to enable it? What other reason would there be for the scrolling
to be sluggish?

**Comment by Gibbz** [comment]
ok i found it was the animated scrolling preference making it feel sluggish! disabled that and its good!
