### ISSUE TITLE
feature requests on system integration: on-the-fly detection of password manager plus system dialogs

### ISSUE THREAD

**Issue by kupiqu** [QupZilla/qupzilla#2210]
Congratulations for the nive browser.

With the aim to improve Qupzilla's integration, I would like to propose a couple of features:

1. Password manager detection. Chromium browser has a way to detect password managers in the system, so you can set a flag (--password-store=detect) to trigger it.

2. Native system dialogs for save/open files.

IMO, these two features highly improve system integration, so if this could be set, QupZilla would be used in much more intutitive and less intrusive way.

**Comment by nowrep** [comment]
1. User can always just enable the correct plugin in Preferences.
2. As long as you use correct Qt platform plugin then it uses native file dialogs.

**Comment by kupiqu** [comment]
1. I don't find kwallet in the available options. This seems to need to be set at compiling time, which is not usually set in the packages I use (AppImage, I used debs before and had same issue). I cannot either compile it myself because Qt 5.8 is not available. What I guess I'm really asking is to set it by default, so it would appear in Appimages.

2. Can you please be a bit more explicit in what you mean about Qt platform plugin? Open and save dialogs look Qt-ish here, but they are not as they appear in KDE. Is there sth I could do about this from my side?

Many thanks for your fast response!

**Comment by nowrep** [comment]
1. Yes, currently it is missing in the AppImage available to download on homepage.
2. That only works when you use system version of Qt, so it will not work in AppImage case

**Comment by kupiqu** [comment]
Re 1: Could you please (re-)consider changing the current policy? Not sure if this would have any cons though...

Re 2: I see, thanks. For this, I will wait until Qt 5.8 is available in repos, then. I guess supporting Qt 5.7.1 is not an option, right?

Thanks!

**Comment by nowrep** [comment]
Version 2.1.x (branch `v2.1`) can be built with Qt 5.7.0+, only `master` (which will be eventually 2.2.x) switched to Qt 5.8.0+.

**Comment by kupiqu** [comment]
Oh, I see.
Thanks
