### ISSUE TITLE
Next page sometimes opens at the end

### ISSUE THREAD

**Issue by AcarBurak** [QupZilla/qupzilla#2211]
That is, for instance, in github search for something; scroll down the page and click either "Next" or "2" (page number); sometimes that page opens with the focus at the end of the page rather than the begining, i.e. I'm at the end of page 2, already scrolled down. This is in QupZilla 2.1 on an Arch/Fluxbox system with Qt (5.8) theme set by `qt5ct` if that matters.

**Comment by nowrep** [comment]
Can you please post some page where you can reproduce the issue?
Also please try to disable native scrollbars in preferences.
