### ISSUE TITLE
Default Search not honored when using only address bar to search

### ISSUE THREAD

**Issue by abrouwers** [QupZilla/qupzilla#2212]
In preferences (Other -> manage search engines) I have my default search set to google.  I hide the search box, to have a Chrome-like layout, expecting that entering text in the address bar would default to using this setting to search.  However, regardless of the default engine in preferences, DDG is always used.

**Comment by cranes-bill** [comment]
>In preferences (Other -> manage search engines) I have my default search set to google

But in **Preferences** -> **Tabs** -> _**Addres Bar behaviour**(tab)_ you don't have:   :ballot_box_with_check:  _**Search with default search engine**_ checked

**Comment by abrouwers** [comment]
Wow, I completely missed that!  My apoligies, thanks for the pointer.
