### ISSUE TITLE
screen turns off while watching videos

### ISSUE THREAD

**Issue by Gibbz** [QupZilla/qupzilla#2214]
Ive noticed qupzilla doesnt keep the screen on while watching videos.
This would be a good feature to have when watching longer videos...

**Comment by nowrep** [comment]
Works fine here:
![spectacle w23639](https://cloud.githubusercontent.com/assets/522831/22900752/bdcd697e-f22f-11e6-95d1-9e1f0e0c0f8a.png)

**Comment by cranes-bill** [comment]
@Gibbz, if you are using flash, it does not support screensaver features.

**Comment by Gibbz** [comment]
it happens on youtube.
are they still using flash?

**Comment by cranes-bill** [comment]
[Related](https://github.com/QupZilla/qupzilla/issues/2223#issuecomment-281285208)
