### ISSUE TITLE
SSL certificate errors

### ISSUE THREAD

**Issue by rohshall** [QupZilla/qupzilla#2217]
I get frequent SSL certification errors saying:

> The server's certificate was not disclosed via Certificate Transparency.

I am using the latest master branch on Ubuntu 16.10.
My system:

> $ cat /etc/os-release 
> NAME="Ubuntu"
> VERSION="17.04 (Zesty Zapus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu Zesty Zapus (development branch)"
> VERSION_ID="17.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="http://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=zesty
> UBUNTU_CODENAME=zesty
> 

The errors on the console are:

> [26346:26356:0213/092235:ERROR:nss_ocsp.cc(610)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
> [26346:26356:0213/092235:ERROR:nss_ocsp.cc(610)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
> [26346:26356:0213/092235:ERROR:nss_ocsp.cc(610)] No URLRequestContext for NSS HTTP handler. host: crl4.digicert.com
> [26346:26356:0213/092235:ERROR:nss_ocsp.cc(610)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
> [26346:26356:0213/092235:ERROR:nss_ocsp.cc(610)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
> [26346:26356:0213/092235:ERROR:nss_ocsp.cc(610)] No URLRequestContext for NSS HTTP handler. host: crl4.digicert.com
>

**Comment by nowrep** [comment]
And QupZilla version?

**Comment by rohshall** [comment]
It's the latest bleeding-edge master:

> $ qupzilla -v
> QupZilla 2.1.99 (69193399b4)
>

**Comment by nowrep** [comment]
Alright, and Qt version? Also can you send some url that triggers this issue?

**Comment by rohshall** [comment]
> $ qtchooser -print-env
> QT_SELECT="default"
> QTTOOLDIR="/opt/Qt5.8.0/5.8/gcc_64/bin"
> QTLIBDIR="/opt/Qt5.8.0/5.8/gcc_64/lib"
> 

URL example:
`http://stackoverflow.com/questions/2756798/java-native-memory-usage`

**Comment by nowrep** [comment]
No issues here. Is there anything useful in the terminal output?

**Comment by rohshall** [comment]
The terminal/console output is part of the first comment.

**Comment by nowrep** [comment]
I've seen those errors but it never actually resulted in certificate errors. In any case, issue is in QtWebEngine - probably something is not right with the libnss.

**Comment by rohshall** [comment]
Thanks for taking a look. I upgraded my Qt, and now I no longer see the errors. Thanks for pointing out the culprit.
