### ISSUE TITLE
Not working on windows xp sp3.

### ISSUE THREAD

**Issue by i430vx** [QupZilla/qupzilla#2220]
Does This Project Support XP anymore? because i cant find anything saying so. When trying to open the latest version, it produces an error saying: the procedure entry point aquiresrwlockshared could not be located in kernel32.dll   I have tried removing D3Dcompiler_47.dll, which was a fix for 2.0, but that didn't change anything

**Comment by nowrep** [comment]
No, since switch to QtWebEngine Windows XP is not supported anymore.
