### ISSUE TITLE
Sometimes when the window refresh gets disabled

### ISSUE THREAD

**Issue by rohshall** [QupZilla/qupzilla#2222]
![2017-02-15-222200_1912x1052_escrotum](https://cloud.githubusercontent.com/assets/225175/23009889/5de9d462-f3cd-11e6-8548-5b48f341baa2.png)
As seen in the screenshot, the page refresh goes into "refreshing" state (or "refresh in progress" state), and never comes out of that state. I can always refresh the page by pressing Ctrl+R, so, this is not serious though.

**Comment by nowrep** [comment]
I've seen it too with recent QtWebEngine version, but I can't reliably reproduce it.

**Comment by cranes-bill** [comment]
Is it possible the reason to be some unloaded element where is blocked by **Adblock**!?

**Comment by muesli** [comment]
No, the context menu shows a "Reload" menu item.

**Comment by muesli** [comment]
Disabling AdBlock for YouTube doesn't make a difference. For what it's worth, I can not not reproduce this, in other words this happens on any YouTube page all of the time for me.

**Comment by muesli** [comment]
Confirmed as fixed.
