### ISSUE TITLE
 HTTP Strict Transport Security issue

### ISSUE THREAD

**Issue by Gibbz** [QupZilla/qupzilla#2223]
I get the following error on whirlpool.net.au website (requires a free account).

"You are currently logged in, however your account has not been loaded because you are browsing Whirlpool unsecurely. (HTTP, not HTTPS.) This should never occur because your browser should have honoured our HTTP Strict Transport Security policy. If you are seeing this message it means your computer or web browser may be untrustworthy."

Just wondering if this is anything of concern? 
Works fine on firefox btw.

**Comment by nowrep** [comment]
What version of QtWebEngine do you have?

**Comment by Gibbz** [comment]
according to qupzilla about screen:

WebKit version 538.1

**Comment by cranes-bill** [comment]
> WebKit version 538.1

:smiley:

**Comment by nowrep** [comment]
Please use QupZilla 2.

**Comment by Gibbz** [comment]
i am using qupzilla 2 downloaded from the qupzilla website

**Comment by nowrep** [comment]
Not every download there offers latest version, only the ones hosted on qupzilla.com (with exception of OS/2) is always the latest version.
If you used your distribution to install QupZilla, then it of course depends on version that is available for your distribution. You should try to use the AppImage version (available for download under Other Linux section).
