### ISSUE TITLE
[MASTER] The addressbar GO button does not works

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#2225]
The addressbar _GO button_ does not works to me.
It just turns on to _bookmark button_, but do not go to the address.

**QT 5.8 (Precompiled)**

**Comment by nowrep** [comment]
`master` only?

**Comment by cranes-bill** [comment]
Works on:
**2.0.2 (6e445dc)
Qt 5.6.1**

**Comment by nowrep** [comment]
Can you please check with 2.1.1 appimage?

**Comment by cranes-bill** [comment]
Actually i have tried already, but if it works to you, so something here is wrong and then close the issue please!
Sorry for the delay!

**Comment by cranes-bill** [comment]
Also tried with older appimage which is **2.0.99 (614ac46)** version and there is the same.
