### ISSUE TITLE
New password backend plugin: forms are not filled

### ISSUE THREAD

**Issue by tastytea** [QupZilla/qupzilla#2234]
I'm trying to make a password backend [plugin](https://github.com/tastytea/qupzilla/blob/passplugin/src/plugins/PassPasswords/). getEntries() is called and entries are found, but the Form is not filled. The database (plaintext) backend works with the same site.
I added a [debug statement](https://github.com/tastytea/qupzilla/blob/passplugin/src/plugins/PassPasswords/passpasswordbackend.cpp#L53), which is called twice per site and prints the right data.

I used the [KWalletPasswords](https://github.com/QupZilla/qupzilla/tree/master/src/plugins/KWalletPasswords) plugin as a template and compared my code to databasepasswordbackend.cpp. I found nothing wrong in my code.

I'm using Ubuntu 16.10 with Qt 5.8 (installed with the Qt installer) and g++-6.2.0.

Edit: The debug output is, for example:
`Found:  "pass123\nusername: user123\ncomment: comment123\n"`

**Comment by nowrep** [comment]
It completes pages according to `data` in `PasswordEntry`, so you should implement `addEntry` and return the correct data in getEntries passed to addEntry.

**Comment by tastytea** [comment]
Thanks, that worked.
May I ask why it is designed that way? It makes it impossible to use existing password databases. :-(

**Comment by nowrep** [comment]
Nothing, but it needs to know where to fill in the credentials (form input names), not just login & password pair.
