### ISSUE TITLE
problem with speed dial edit

### ISSUE THREAD

**Issue by SteveStites** [QupZilla/qupzilla#2235]
February 24, 2017

This is a description of a problem in qupzilla version 1.8.9.

I dual boot Linux Mint 17.3 and Linux Mint 18.1.  Both systems are current in 
the package updates.  I do not share /home between the two Linux Mint systems. 

------------------------------------------------------------------------
operating system:  Linux Mint 17.3

Qt version:  5.2.1 and 4:4.8.2 are both installed and qtchooser is installed

I am running qupzilla:  Application version 1.6.0
                                      WebKit version 537.21
------------------------------------------------------------------------        
operating system:  Linux Mint 18.1

Qt version:  5.5.1 and 4:4.8.1 are both installed and qtchooser is installed

I am running qupzilla: Application version 1.8.9
                                      WebKit version 538.1
------------------------------------------------------------------------        

------------------------------------------------------------------------        
                            Bug Description
                              
When I installed quipzilla 1.8.9 on Linux Mint 18.1 I tried to edit my speed 
dial settings.  If I try to add a new entry to the speed dial I get an "Unable 
to load" message.  If I try to edit an existing speed dial entry I get the same 
"Unable to load" message.

I copied the file /home/user/.config/qupzilla/profiles/default/settings.ini 
from Linux Mint 17.3 to Linux Mint 18.1.  Then I booted into Linux Mint 18.1.  
The qupzilla 1.8.9 speed dial then was the same as the one in qupzilla 1.6.0 
and I could go to whatever web page I chose by clicking on the speed dial entry.
However if I tried to add an entry or edit an entry in the qupzilla 1.8.9 speed 
dial I got the "unable to load" message.

I found a method to change the speed dial entries in qupzilla 1.8.9.  I boot 
into Linux Mint 17.3 and make the changes to the speed dial entries in qupzilla 
1.6.0.  I then copy the file 
/home/user/.config/qupzilla/profiles/default/settings.ini from Linux Mint 17.3 
to Linux Mint 18.1 and the changes appear in qupzilla 1.8.9 after I boot into
Linux Mint 18.1.

I also tested the problem by opening a terminal in Linux Mint 18.1 and starting 
qupzilla 1.8.9.  I exercise the problem and then exit quipzilla.  The only 
message in the terminal is "0 extensions loaded".

I think that there is a bug in the qupzilla 1.8.9 speed dial edit routine.
------------------------------------------------------------------------        
Steve Stites

**Comment by SteveStites** [comment]
I apologize for the bold type.  I think that when I copied some lines from the qupzilla help page some html formating tags were accidentaly copied too.

-----------------------------------
Steve Stites

**Comment by cranes-bill** [comment]
>This is a description of a problem in qupzilla version 1.8.9.

That's fixed, but you are using a very old QupZilla version which is not maintained any more, please upgrade it!
