### ISSUE TITLE
URL auto completion popup broken on wayland

### ISSUE THREAD

**Issue by Tobi29** [QupZilla/qupzilla#2236]
Since [e86f968](https://github.com/QupZilla/qupzilla/commit/e86f96878e6853b399c772cb106f4ec01f3ba1bd) the URL auto completion popup no longer shows correctly when typing. On each keystroke the popup shows at an incorrect location and immediatly disappears again, sometimes denying keypresses when typing quickly.

Everything works as expected when running on x11 (both with xorg and xwayland).

Running on Arch Linux (x86_64) using the qupzilla-git AUR package (official one does not include this change yet), with Qt 5.8 (official package, which is patched to work properly with kwin) on Plasma 5.9.2 and `QT_QPA_PLATFORM=wayland` (or just launching through plasma)

**Comment by nowrep** [comment]
This 71b06197ef broke it.
