### ISSUE TITLE
MEGA - QupZilla not able to decrypt downloaded files

### ISSUE THREAD

**Issue by lollox** [QupZilla/qupzilla#2237]
As in title, when I try to download from MEGA the browser seems to not be able to decrypt the downloaded file and you get a sort of RAW data that QupZilla is not able to manage (the download manager gives a generic error and is not able even to get the real name of the file)

**Comment by nowrep** [comment]
Can you please post url to some file on which I can reproduce the issue?

**Comment by lollox** [comment]
here: https://mega.nz/#!2sw12QIJ!7HSo1h6f0vROWtdSi66uzEX8lr1nYA2W_k1QokByQbY

but every link I tried gives the same error

**Comment by regginator729** [comment]
Tested it. Seems to work just fine. Try the latest build.
