### ISSUE TITLE
middle click does not work

### ISSUE THREAD

**Issue by nekoswag** [QupZilla/qupzilla#2238]
The middle click does not work reliably to open links in new tabs. It can take 10 clicks or more before the input is registered. In Firefox on the same machine it works fine.

I'm using Qupzilla 2.1.1 on openSUSE Tumbleweed

**Comment by nowrep** [comment]
What is your QtWebEngine version?

**Comment by nekoswag** [comment]
> QtWebEngine-Version 5.7.1

**Comment by Vistaus** [comment]
I have a similar problem. Middle-clicking a tab doesn't work when I use my trackpad but it works with an external mouse. Never had this problem before on other laptops so not sure what the problem could be.

QtWebEngine version: 5.8.0
QupZilla version: 2.1.99 (latest Git master)
OS: Solus (Linux)

**Comment by Vistaus** [comment]
I can confirm that it works now! Thanks! :smile:

**Comment by kupiqu** [comment]
Will it be backported to the 2.1 branch?

**Comment by nowrep** [comment]
Backported now.
