### ISSUE TITLE
Accents don't work in web page fields

### ISSUE THREAD

**Issue by Vistaus** [QupZilla/qupzilla#2247]
I have a strange little problem with the current Git Master version. Accents, for example ' or even combined with a character like é for example, don't work in web page fields BUT they do work in the address bar and the rest of my system. To clarify: with "web page fields" I mean form fields but also, for example, the YouTube search field.

What could cause this problem and how to solve this?

**Comment by cranes-bill** [comment]
Works to me with [Appimage](https://www.qupzilla.com/download#linux).

**Comment by Vistaus** [comment]
I only now notice that the label QtWebEngine got added. Does that mean it's a QtWebEngine issue rather than a QupZilla issue?

**Comment by Martii** [comment]
@Vistaus 
Perhaps as consolation take a look at the timeline for Qt releases at https://wiki.qt.io/Qt_5.9_Release . They seem to be a little ahead of their schedules usually but means patiently awaiting fixes from "upstream" or "across-the-pond" *(however one looks at this)*

**Comment by Vistaus** [comment]
@Martii Well, I'm gonna update to Qt 5.9 in a few days when the beta is released ('cause by then they will have a Linux installer for it). I'll wait for the 5.9 beta then to see if it's fixed...

**Comment by nowrep** [comment]
Yes, probably QtWebEngine issue. Can you please test with other QtWebEngine browsers (ideally testbrowser from QtWebEngine sources).

**Comment by Vistaus** [comment]
Not fixed in 5.9 beta :cry: Does anyone have any tip?

**Comment by cranes-bill** [comment]
I think that depends of your Qt configuration. Did you try with _Testbrowser_ or _AppImage_? Here is a simple [video](http://sendvid.com/mmp2tj8f) where showing how it works to me with _AppImage_.

**Comment by Vistaus** [comment]
@cranes-bill No offence, but AppImage is a totally different thing then compiling (esp. from Git Master). And I don't want AppImage, I want the latest Git Master code (which also integrates better).

I'll try the test browser ASAP.

**Comment by nowrep** [comment]
@Vistaus How come? It just shows that it works in the configuration of the AppImage. So if you have the same QtWebEngine version as the AppImage, then there is something wrong in your installation.

**Comment by probonopd** [comment]
> which also integrates better

@Vistaus what do you mean by that? How could we improve?

**Comment by Vistaus** [comment]
@nowrep But what else there is to configure during installation? I've installed it as usual.

@probonopd AppImage doesn't respect the platform theme set in qt5ct. (plus there's no daily AppImage containing the latest Git Master code, but that could be made of course)
BUT more importantly: it doesn't integrate into the system because it supplies its own libraries. I like it installed in /usr (or /opt, if explicitly needed)

**Comment by Vistaus** [comment]
@nowrep I tested it in Otter Browser with QtWebEngine and it does work fine there. So that confirms that it's not a QtWebEngine configuration issue.

**Comment by nowrep** [comment]
Did you try it with the AppImage?

**Comment by Vistaus** [comment]
@nowrep Yup, same problem happens in the AppImage for me.

**Comment by nowrep** [comment]
Can you please try if this helps?

```diff
diff --git a/src/lib/webengine/webview.cpp b/src/lib/webengine/webview.cpp
index 7f71aa90..3c78c00a 100644
--- a/src/lib/webengine/webview.cpp
+++ b/src/lib/webengine/webview.cpp
@@ -70,9 +70,9 @@ WebView::WebView(QWidget* parent)
     m_currentZoomLevel = zoomLevels().indexOf(100);
 
     setAcceptDrops(true);
-    installEventFilter(this);
+//    installEventFilter(this);
     if (parentWidget()) {
-        parentWidget()->installEventFilter(this);
+//        parentWidget()->installEventFilter(this);
     }
 
     WebInspector::registerView(this);
@@ -86,7 +86,7 @@ WebView::WebView(QWidget* parent)
                 qCritical() << "Focus proxy is null!";
                 return;
             }
-            m_rwhvqt->installEventFilter(this);
+//            m_rwhvqt->installEventFilter(this);
         });
     });
 }

```

**Comment by Vistaus** [comment]
@nowrep Unfortunately, that doesn't help :(

**Comment by cranes-bill** [comment]
WOW, such a miracle! You have been surviving after try with _AppImage_.
Now what, _AppImage_ works to me, but does not works to you, so what...
I still claim that is a system configuration problem, `QT_IM_MODULE` or so.
Sorry for my very bad English!

**Comment by Vistaus** [comment]
@cranes-bill Just because I survived doesn't mean I like AppImage. I deleted after I noticed it didn't solve my problem.

Also: you claim that it's a configuration issue but then why does Otter from their Git Master work with the SAME Qt that I've been using with QupZilla?

(P.S.: your English is not bad at all! I fully understand you! :smile: )

**Comment by nowrep** [comment]
Then I have no idea, that's the only code that messes with input (and key events).
What is your keyboard layout, so I can try to reproduce it myself? (works fine in Czech layout for me).

**Comment by Vistaus** [comment]
My keyboard layout is chromebook_m English (US - International)

**Comment by nowrep** [comment]
I mean which keyboard layout are you using in X?

**Comment by Vistaus** [comment]
That's the one I'm using in X.

**Comment by nowrep** [comment]
Please paste output of `setxkbmap -print;

**Comment by Vistaus** [comment]
Here you go:

`[15:08:47] vistaus@vistaus-solus /media/MicroSD/Apps/qupzilla (0) 
> setxkbmap -print;
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us(intl)+inet(evdev)+terminate(ctrl_alt_bksp)"	};
	xkb_geometry  { include "pc(pc104)"	};
};
[16:10:04] vistaus@vistaus-solus /media/MicroSD/Apps/qupzilla (0) `

**Comment by cranes-bill** [comment]
@Vistaus
My idea was not to „promote" using of AppImage, just to try with it. Actually, @nowrep already [explained](https://github.com/QupZilla/qupzilla/issues/2247#issuecomment-292711582) what i meant with my comments...

I can also propose if you able to try on any different distribution (live image or virtual machine)

>Here you go:

Mine is similar:
```
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete+ledscroll(group_lock)"	};
	xkb_symbols   { include "pc+us(altgr-intl)+inet(evdev)+group(lalt_lshift_toggle)+terminate(ctrl_alt_bksp)"	};
	xkb_geometry  { include "pc(pc104)"	};
};
```

**Comment by nowrep** [comment]
Well, it works with otter browser (assuming with the same QtWebEngine), so there's no more testing needed. Testing with official QtWebEngine testbrowser would be better, but any other QtWebEngine app should be fine.

**Comment by Vistaus** [comment]
Tried it in the Qt demobrowser (5.9) but accents don't work there either :/

I did notice though that I get this output when trying to insert and accent:

```
js: Uncaught (in promise) TypeError: Cannot read property 'classList' of null
js: Uncaught (in promise) TypeError: Cannot read property 'classList' of null
js: Uncaught (in promise) TypeError: Cannot read property 'classList' of null
js: Uncaught (in promise) TypeError: Cannot read property 'classList' of null
js: Uncaught (in promise) TypeError: Cannot read property 'classList' of null
js: Uncaught (in promise) TypeError: Cannot read property 'classList' of null
[16:46:46] vistaus@vistaus-solus /home/vistaus/Downloads/qtwebengine-opensource-src-5.9.0-beta/examples/webenginewidgets/demobrowser (0) 
> 

```

And as for QupZilla: it gives a similar error:
`
js: Uncaught (in promise) TypeError: Failed to fetch`

**Comment by nowrep** [comment]
That warnings should have nothing to do with it.
Now the question is, what otter does to make it work? Are you sure you used the QtWebEngine (and not QtWebKit) backend of otter?

**Comment by Vistaus** [comment]
I'm 100% sure I did use the QtWebEngine backend of Otter.

Okay, I didn't know those warnings didn't have anything to do with it, but they do only show when trying to insert an accent though. No other thing I do triggers those warnings.

**Comment by nowrep** [comment]
If you try it on simple page (eg. with just `<input type="text">`) without javascript, you should not see any warnings.

**Comment by nowrep** [comment]
I don't see anything in otter code that would affect this issue.

**Comment by Vistaus** [comment]
@cranes-bill Tried QupZilla on Arch with the same Qt version and the issue affects me there as well. So now a configuration issue is definitely ruled out.

**Comment by cranes-bill** [comment]
Some time ago (in the _QtWebkit era_), i had the same issue and the problem has been solved after install of any additional software package, but can't remember now what exactly it was.

**Comment by Vistaus** [comment]
@cranes-bill You might be on to something. Let me know if you suddenly remember :)

**Comment by cranes-bill** [comment]
I think it was something related to **ibus** or **xim** but unfortunately, really can't remember.

**Comment by nowrep** [comment]
If it works in the normal (Qt widgets) input fields and other apps then there is no issue with your configuration, just bug in QtWebEngine.

**Comment by cranes-bill** [comment]
But why AppImage works to me, but does not works for him - the same QtWebEngine library!?

**Comment by cranes-bill** [comment]
@Vistaus 
Now i noticed that your X11 variant is `intl`, you can try to change it to `altgr-intl`.

**Comment by Vistaus** [comment]
@nowrep Okay, I'll see if I can report it upstream then. Thanks for all of your help! :smile_cat: 
@cranes-bill Why would that variant make a difference?

**Comment by Martii** [comment]
Ouch... Qt 5.9 Beta 2 is out and it killed QupZillas Preferences... might want to hold off on updating that.

**Comment by Vistaus** [comment]
@Martii Thanks for the warning! I've actually ditched Qt 5.9 as a whole because it made QupZilla waaaay too buggy. Will wait for the final release and try again. But I'm not sure, QtWebEngine is too immature currently. There's too many bugs that they need to fix still. I think they never should've ditched QtWebKit so fast, they should've waited for QtWebEngine to become more mature.

**Comment by Martii** [comment]
Qt 5.9 Beta 1 did some alterations with Speed Dial as well... the windows were much bigger here and the refresh just spun forever until a restart of the browser... so yah until May'ish release is probably best for QupZilla. I'll still run some tests under my dev *(Linux)* box but I'll be holding off on the Mac until then.

**Comment by Vistaus** [comment]
Btw, this is fixed in Qt 5.9(.1).

**Comment by cranes-bill** [comment]
I still claim this is an environment issue :stuck_out_tongue_winking_eye:

**Comment by Vistaus** [comment]
Hehe, well I did a reinstall of Solus last week so the environment is fresh :wink:

**Comment by cranes-bill** [comment]
>  ...so the environment is fresh

Then the problem disappeared... :smiley:
