### ISSUE TITLE
Theming qupzilla

### ISSUE THREAD

**Issue by Jacobtey** [QupZilla/qupzilla#2251]
Themes can't change all items (center, bottom). Why? What should I do?  ![screenshot_20170314_230337](https://cloud.githubusercontent.com/assets/7997512/23920330/44de3cee-090b-11e7-9d37-fef829a93232.png)

**Comment by nowrep** [comment]
What do you mean with this screenshot? Speeddial is not themeable.

**Comment by Jacobtey** [comment]
Ok. Speeddial is not.

**Comment by Jacobtey** [comment]
Well StatusBarIcon plugin is a part of qupzilla code. Why is it not themeable?

**Comment by nowrep** [comment]
It is, but the icons doesn't have object names so you need to use different css selectors.
