### ISSUE TITLE
qupzilla randomly takes HTML as URL and tries to load it

### ISSUE THREAD

**Issue by mounty1** [QupZilla/qupzilla#2256]
After qupzilla has been run for a while, sometimes when you open a new tab, the content appears but then it's like you click a link to jump to a page, the URL of which is the content of the page.  Close qupzilla and re-open and it's OK again for a while.

The URL text-box shows something like:

`data:text/html;charset=UTF-8,%3Chtml%3E%3Chead%3E%0A%3Cmeta%20http-equiv%3D%22content-type%22%20content%3D%22text%2Fhtml%3B%20charset%3Dutf-8%22%3E%0A%3Ctitle%3EFailed%20loading%20page%3C%2Ftitle%3E%0A%3Cstyle%3E%0Ahtml%20%7Bbackground%3A%20%23dddddd%3Bfont-family%3A%20sans-serif%3Bcolor%3A%20%23525c66%3B%7D%0Ahtml%20%2A%20%7Bfont-size%3A%20100%25%3Bline-heig...`

[Observed in Gentoo Linux.](https://bugs.gentoo.org/show_bug.cgi?id=612674)

This is with two qupzilla windows open;  one showing about 20 tabs and the other, six.

**Comment by Martii** [comment]
> The URL text-box shows something like:
`data:text/html;charset=UTF-8,%3Chtml%3E%3Chead%3E%0A%3Cmeta%20http-equiv%3D%22content-type%22%20content%3D%22text%2Fhtml%3B%20charset%3Dutf-8%22%3E%0A%3Ctitle%3EFailed%20loading%20page%3C%2Ftitle%3E%0A%3Cstyle%3E%0Ahtml%20%7Bbackground%3A%20%23dddddd%3Bfont-family%3A%20sans-serif%3Bcolor%3A%20%23525c66%3B%7D%0Ahtml%20%2A%20%7Bfont-size%3A%20100%25%3Bline-heig` 

Translates approximately to decoded string of:

```
data:text/html;charset=UTF-8,<html><head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<title>Failed loading page</title>
<style>
html {background: #dddddd;font-family: sans-serif;color: #525c66;}
html * {font-size: 100%;line-heig
```

So it looks like it's part of the HTTP Headers. SM has a similar issue sometimes on rare occasions and is pulling from the system clipboard on a middle click.

**Comment by mounty1** [comment]
Yes, hence my report that it is taking the HTTP as a URL.  I'm aware of the middle-click issue and when Qupzilla starts doing this, I sometimes click the back-button then immediately click-away from qupzilla to take focus away.  That occasionally works but not often.

BTW, I elided the URL contents with '...' for brevity;  in fact the entire page content appears as the URL.

At least with 2.1.1 it is possible to Ctrl-Q and restart.  2.0.2 left the tabs etc. data in a dirty state and wouldn't restart.

**Comment by mounty1** [comment]
This is one page that frequently but not always demonstrates the problem.  I quote it here only because it does demonstrate the problem.  [live export](https://www.animalsinternational.org/take_action/live-export-global/)

It may be related to Javascript and focus.  If you start to load the page in a browser window with other tabs open, then quickly switch to another tab, the page loads;  the 'rotating swirl' activity symbol eventually disappears.  If you then click back to 'live export' tab, the page then but only then demonstrates the behaviour reported;  i.e., jumps to URL _data:text/html; charset_ etc.

This is with Qupzilla 2.1.2 now.

**Comment by mounty1** [comment]
Another clue:  if you right-click a link and select _open in new tab_ then immediately click on the new tab before the content has loaded, you can provoke the behaviour reported above.  If you wait for the new page to load fully, **then** click on its tab to show it, it works correctly.

**Comment by nowrep** [comment]
It would be more useful if you post the whole data url, not just snippet. But it looks like it is a Chromium error page, in which case the issue is in QtWebEngine/Chromium.
I haven't seen this myself though.

**Comment by mounty1** [comment]
data:text/html;charset=UTF-8,%3Chtml%3E%3Chead%3E%0A%3Cmeta%20http-equiv%3D%22content-type%22%20content%3D%22text%2Fhtml%3B%20charset%3Dutf-8%22%3E%0A%3Ctitle%3EFailed%20loading%20page%3C%2Ftitle%3E%0A%3Cstyle%3E%0Ahtml%20%7Bbackground%3A%20%23dddddd%3Bfont-family%3A%20sans-serif%3Bcolor%3A%20%23525c66%3B%7D%0Ahtml%20%2A%20%7Bfont-size%3A%20100%25%3Bline-height%3A%201.6%3B%7D%0A%23box%20%7Bbackground%3A%20%23ffffff%3Bmax-width%3A650px%3Bmin-width%3A400px%3Boverflow%3Aauto%3Bmargin%3A%2025px%20auto%2010px%20auto%3Bpadding%3A%2010px%2040px%3Btext-align%3A%20left%3Bdirection%3A%20ltr%3B%7D%0Ahr%20%7Bcolor%3A%20lightgray%3Bwidth%3A%20100%25%3B%7D%0Aimg%20%7Bfloat%3A%20left%3Bmargin-left%3A%20-20px%3Bmargin-top%3A%2015px%3B%7D%0Ah1%20%7Bfont-size%3A%20150%25%3Bfont-weight%3A%20bold%3Bborder-bottom%3A%201px%20solid%20%23f4f4f4%3Bmargin-left%3A%2048px%3Bmargin-right%3A%2050px%3B%7D%0Aul%20%7Bfont-size%3A%2090%25%3Bpadding-left%3A%2048px%3Bmargin%3A%2020px%200%3Bmax-width%3A600px%3B%7D%0Ali%20%7Bpadding%3A%205px%3B%7D%0A%23reloadButton%20%7Bmargin-top%3A%2020px%3Bmin-width%3A%20100px%3B%7D%0A%3C%2Fstyle%3E%0A%3C%2Fhead%3E%0A%3Cbody%3E%0A%20%20%3Cdiv%20id%3D%22box%22%3E%0A%20%20%20%20%3Cimg%20src%3D%22data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAAC0AAAAtCAYAAAA6GuKaAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAEK0lEQVRYhe2Xy24cRRSGv1M9PfFknDBxfIkDQVYIWRAFJAsZgRQSiadAQhAS8RxsWPEOREAU8QCwQQjJIrACNkQoDixQwErs%2BMJcPNfursOix7HHXfa0e3xBkX%2BrNOVT1VXfnPnnVA0c6UjPlmRrQO%2B%2B%2BxmYS4cB45b9Xa58dXNzJJeYo3oJojcOjCmDktDowVPsUo5MWxyuOUQlk5iAVtQ58f8ktz32gLldvIBf%2BxNjBvzUHI8noe0eEBfO4I9OUy6vUtLlwcAdOCYZsgM2hZFX4Z9vOH52mqVKgLXRgGv2g1YdqOnwebT5CBNWMc3H%2BKfOs1INsNZmX7d%2FpjV7E0FOvYKs3gOUfO0ew5OXCS38WwuxajOunSrTNlPT0mW0fB%2F8EnrxI%2FBLmOoDipOvEYYRlbUAtbtdNwW0xaJZ%2Frw8nJiCyhwqguQKqAhebY7C6ZcQP08QWcqNEKvp17WpPG0z%2Bm50Bln6Oc6OAGLiV7WYlV8YfuFNRCAKI2qNEE27j6OauT29W2D%2FBBwbQdcebsTEPO2b%2BkPyJ0bx%2FGEEsNZSb6YET%2BXpLCVp4gos%2FEBviTI963kLdylOXcUYi6BYtTQ7IaqHUfKGJuJsNJ%2F0xjdlGlVoLZLzDLnjZxA0BrdKqx31z3gqe%2Bymnb0Gj2eTcTGJmFmcpTD1DiKKCAgWxRJEUZ99euW6TzsnuiQnX0abS9Ap9w40HqG%2FfQphPf5irqtdxrSX8EsXiMp%2FIAIGQa0SBIqfcx33ydg2nk6RYQGdfBsWZpNjuSKMzcSvW8ZkcZZj564iRjBCN%2Btxcx8%2BKT2tKRoj01C%2Bj4at5FiuiEy8Bbli8tmwhVQekB%2Bf3ngj8caoxj7vWSudpyP6nlIYGHsdXfjJOa71eeyvH6P1eff44o94EzOIeBgUIa4oonG%2Fd68oQei4T0M%2FT8vkVcQvwcXrO87bcY18ify5a0Tz3yEiMXTKG2ym%2B3Tn7%2B8pz30bVzZhY1PAGOlWhm5c6AKte5jePsQZFty5csQcmU4af6t8z1IqKJVGPDf%2BWAVj1iFkC5Bg6P5Pbz9%2Bc3237AOd8oet78FzBaHWisGN6CZg3QKsm4A3%2BjtmeAMoDbR74nbgJ4eEens947JxcHStMxiwWwno6vJf41EYtnd66OT4VN6Y%2BCTwPCgOCY12t652D8J2s0xQX2kLsVV46nN2ZQkvlxvfGsv0izP4emYeeH5zLLJKKwBU6TQraFC9M3Fz8b0s6%2FeTo06nUfKE9AwU8hC09hcYtq3TfbTNlzVoVJCwdnvi5uL7A3LtqGzQjttXu1Gl06zeHv3wyb4CQ%2BZMu4BrX47cePLBXkD108DQ7UaNTuvggCGzPSwKdJo1Oq36gQJDVmirdFprtFtrX5y%2BsXR9b5H2SbU7Ly6v3Br7%2FLA5dqXVW2OfHDbDkY70LOk%2F1PPVdAvRoewAAAAASUVORK5CYII%3D%22%20width%3D45%3E%0A%20%20%20%20%3Ch1%3EFailed%20loading%20page%3C%2Fh1%3E%0A%20%20%20%20%3Cul%3E%0A%20%20%20%20%20%20%3Cli%3ESomething%20went%20wrong%20while%20loading%20this%20page.%3C%2Fli%3E%0A%20%20%20%20%20%20%3Cli%3ETry%20reloading%20the%20page%20or%20closing%20some%20tabs%20to%20make%20more%20memory%20available.%3C%2Fli%3E%0A%20%20%20%20%20%20%3Cinput%20type%3D%22submit%22%20id%3D%22reloadButton%22%20value%3D%22Reload%20page%22%20onclick%3D%22window.location.reload%28%29%22%3E%0A%20%20%20%20%3C%2Ful%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fbody%3E%3C%2Fhtml%3E%0A

**Comment by mounty1** [comment]
Browser window shows:

    Failed loading page

    Something went wrong while loading this page.
    Try reloading the page or closing some tabs to make more memory available.

    [Reload page]

According to KDE system monitor, Qupzilla is using 412488K of memory.  My machine has 8 GiB.  32 bit build.

**Comment by nowrep** [comment]
Then it means the web process crashed for some reason (eg. no more memory, simple crash in engine, ...)

**Comment by mounty1** [comment]
I think it is down to running out of memory.  I've been keeping Qupzilla down to no more than ten tabs, and it has run correctly.  Presumably, somewhere, probably in QtWebEngine, there's an unchecked/unguarded 'new' call.

**Comment by potuz** [comment]
I just started hitting this problem after a recompile of qtwebengine 5.7.1 on Gentoo, can reproduce regularly on some pages even with one tab open on an 8Gb system. I'm at a loss trying to find how to fix this.

**Comment by The-Compiler** [comment]
@potuz Qt 5.7.1 is old and has some bugs causing renderer process crashes. Unfortunately, Gentoo only managed to upgrade from Qt 5.6 to 5.7.1 a few weeks ago, so it'll take a while until they manage to get Qt 5.9 (released in May) which fixes this.

**Comment by potuz** [comment]
I've been running qtwebengine 5.7.1-r1 for months without issues, only today after recompilation to 5.7.1-r2  which is a trivial change in the ebuild that the problem happened so I do not think it is simply an issue with versioning.

**Comment by mounty1** [comment]
_I just started hitting this problem after a recompile of qtwebengine 5.7.1 on Gentoo_

It might be stressed by the Javascript.  https://www.linkedin.com crashes on me regularly for example.  Also, on some systems (can't work out the common pattern), Qupzilla just flickers furiouslyl on startup for a while before crashing.

**Comment by potuz** [comment]
Ok so after that compile of qtwebkit qupzilla started crashing. I got a useless stacktrace but I'll try to compile with debug symbols and post here
```
js: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
js: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Received signal 11 SEGV_MAPERR 000000000020
#0 0x7fc9120c754e <unknown>
.....
```

I apologize if this is not the place to post, but qupzilla was working just fine for months on qtwebengine-5.7.1 and only yesterday it started failing after updating the system (which forced recompilation of qtwebengine and lots of other packages but they all seem irrelevant to me). I  tried recompiling qtwebengine withou ccache to no avail.

**Comment by Chiitoo** [comment]
While it is interesting that it seems to have started after re-compiling, I can't quite think of why that would be either.

I'm also not sure what the best way to fix it would be, aside from patching things in QtWebEngine.  A less frustrating way might be building Qt 5.9.1 from the Qt overlay.  It's still not quite ready for Portage due to the upstream configure changes, but I, and a bunch of others have been using >=5.9 from there since April or so.

**Comment by potuz** [comment]
My guess is that this is due to the upgrade of gcc to 6.4 and the -fno-delete-null-pointer-checks issue. I'm in the process of recompiling with this clause qtwebengine and will post tonight if that solved the issue.

**Comment by potuz** [comment]
That was exactly it, the problem is described in https://gcc.gnu.org/gcc-6/changes.html and is the same bug in issue https://github.com/QupZilla/qupzilla/issues/2008. Gentoo already has a bug reported on qtwebengine in https://bugs.gentoo.org/show_bug.cgi?id=623364. Recompiling qtwebengine with -fno-delete-null-pointer-checks solved the problem for me.
