### ISSUE TITLE
Mac: Custom `make` target of `bundle`

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla#2259]
So almost have a PR ready to upload to GH but have a few questions first:

1. Should the PR be submitted to `master` branch or `v2.1` branch? :question: *(Still unclear when I should be doing one or the other... bug fixes to v2.1 but this is more a RFE/RFC)*
2. Verification for Travis CI from #2245 would be appreciated e.g. Did I miss anything any notes on changes to .travis.yml from that issue? :question:

Ref:
* https://github.com/QupZilla/qupzilla/pull/2226#discussion_r101901152

**Comment by nowrep** [comment]
1. This is not bugfix, so master only

**Comment by Martii** [comment]
> 2. :question:

See https://github.com/QupZilla/qupzilla/pull/2245#discussion_r106724757

**Comment by Martii** [comment]
> 1. This is not bugfix, so master only

K. Going to `master`

**Comment by Martii** [comment]
41d9aa19d88d5c6ab6f290687e41327e7c402378 correction.
