### ISSUE TITLE
Mac: Speed Dial Images absent

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla#2267]
<img src="https://cloud.githubusercontent.com/assets/114709/24093413/501911da-0d19-11e7-89d4-8894c5dc29de.png" alt="About with hash" title="Click to enlarge" width="160" height="80" />

Take a look at this image and look at the speed dial on the Mac *(OS X 10.12.3 (Sierra))*. It's been this way for a really long time although the broken-image image changed. I have nothing special proxy wise e.g. direct TCP/IP and clean profile. Linkage works but just no images on the Mac like there is Linux and Windows. Thanks.

**Comment by Martii** [comment]
@srazi 
> After some testing I found that `qml/QtWebEngine` and `qml/QtQuick` should added to bundle. but they have sub-folders and each sub-folder has a `dylib` that `install_name_tool` should applied on them. :|

If that is the case this is going to be tricky... just to let you know when I did it for the QtSvgIcon.dylib nothing I did with `install_name_tool` would work... so that's why it ended up in the `plugins` folder *(See https://github.com/QupZilla/qupzilla/blob/621ed8ff28d0fde7e946d4b08022497749acacae/mac/macdeploy.sh#L38-L51)*. 

I very much welcome a cross-check though.

**Comment by srazi** [comment]
Well I think I found the solution. We have to run macdeployqt like:
```yaml
macdeployqt QupZilla.app -qmldir=$QUPZILLA_SRC/src/lib/data/data
```

**Comment by Martii** [comment]
> macdeployqt QupZilla.app -qmldir=$QUPZILLA_SRC/src/lib/data/data

`macdeployqt QupZilla.app -qmldir=../src/lib/data/data` works since we're in the `bin` folder [up top](https://github.com/QupZilla/qupzilla/blob/621ed8ff28d0fde7e946d4b08022497749acacae/mac/macdeploy.sh#L20).

Nicely done!!! See I saved the hardest one for you. ;) :)

**Comment by srazi** [comment]
> ...  Now to recheck the svg dylib (UPDATE Still needed with manual file copy)

[deployPlugins()](http://code.qt.io/cgit/qt/qttools.git/tree/src/macdeployqt/shared/shared.cpp#n1015) doesn't take into account `plugins/iconengines` so it seems we have to copy it manually.
I opened a [Qt bug report](https://bugreports.qt.io/browse/QTBUG-59609)

**Comment by Martii** [comment]
> I opened a [Qt bug report](https://bugreports.qt.io/browse/QTBUG-59609)

Awesome. Voted and watching. :)

**Comment by Martii** [comment]
Oooh the Qt bug is in progress statused and there is a patch in the queue. :)
