### ISSUE TITLE
Mac: A few WARNINGs with `macdeployqt`

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla#2268]
So a question asked earlier was related to this... so making an issue for it for discussion.

When running `macdeployqt` this pops up...
```
WARNING: Plugin "libqsqlodbc.dylib" uses private API and is not Mac App store compliant.
WARNING: Plugin "libqsqlpsql.dylib" uses private API and is not Mac App store compliant.
```

**A solution** to squash these Warnings is to add the switch of `-appstore-compliant` to https://github.com/QupZilla/qupzilla/blob/621ed8ff28d0fde7e946d4b08022497749acacae/mac/macdeploy.sh#L54... **however** I don't know what this will **break** *(bookmarks?)*, if anything, as I'm still newer to the project here.

There is also this before it with `macdeployqt`:

``` sh-session
ERROR: no file at "/opt/local/lib/mysql55/mysql/libmysqlclient.18.dylib"
ERROR: no file at "/usr/local/lib/libpq.5.dylib"
```

These are **not** installed by me and as far as I can tell it's something in `macdeployqt` by default... but would be nice to squash if possible.

Cc: @srazi

**Comment by nowrep** [comment]
QtWebEngine itself is not Appstore compliant, so you can just ignore this warnings. Also, you should remove all database plugins except sqlite because they are not used in QupZilla.

**Comment by Martii** [comment]
> you should remove all database plugins except sqlite because they are not used in QupZilla.

So how do I remove something that I never put on the machine? :question: ;)

**Comment by nowrep** [comment]
If it's not in the bundle then you can just ignore it, obviously.

**Comment by Martii** [comment]
I'll see if I can fix it upstream then. Not good to have references in that aren't used. Thanks.
