### ISSUE TITLE
Mac: Theme icon missing

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla#2270]
**Adding** or **removing** a bookmark in OS X 10.12.3 seems to be missing an icon with the default theme... perhaps a typo floating around or non-existent reference.

See:
* <img src="https://cloud.githubusercontent.com/assets/114709/24126228/7c776cbc-0d92-11e7-8ba8-82bad4cb37e2.png" alt="Platforms with icon... some missing" title="" width="126" height="78" />

Refs *(see numbers on attached screen shot)*:
1. Mac OS X 10.12.3 *(Sierra)*
2. ROSA Linux
3. Windows 7 Pro x64

QupZilla 2.1.2 Windows Installer and [tree/`686ad7e`](https://github.com/QupZilla/qupzilla/tree/686ad7eee28d160448f90a218d37a155bf27a005) for Linux and Mac.

---

Known code points:
* [blob/`686ad7e`/src/lib/bookmarks/bookmarkswidget.ui#L17-L26](https://github.com/QupZilla/qupzilla/blob/686ad7eee28d160448f90a218d37a155bf27a005/src/lib/bookmarks/bookmarkswidget.ui#L17-L26)
* [blob/`686ad7e`/src/lib/bookmarks/bookmarkswidget.cpp#L42](https://github.com/QupZilla/qupzilla/blob/686ad7eee28d160448f90a218d37a155bf27a005/src/lib/bookmarks/bookmarkswidget.cpp#L42)
* [blob/`686ad7e`/bin/themes/mac/main.css](https://github.com/QupZilla/qupzilla/blob/686ad7eee28d160448f90a218d37a155bf27a005/bin/themes/mac/main.css) *(possibly missing reference and/or fallback but unusual that other platform themes are showing something without references in their respective CSS)*

Other loosely related issues:
* [blob/`686ad7e`/src/lib/bookmarks/bookmarkswidget.ui#L37](https://github.com/QupZilla/qupzilla/blob/686ad7eee28d160448f90a218d37a155bf27a005/src/lib/bookmarks/bookmarkswidget.ui#L37) *(Image not currently in project tree [blob/`master`](https://github.com/QupZilla/qupzilla/tree/686ad7eee28d160448f90a218d37a155bf27a005))*
* Noticed that button borders aren't being drawn consistently on all platforms.

**Comment by nowrep** [comment]
Not all platforms (or even icon themes on Linux) have all icons, this is not an issue.

**Comment by Martii** [comment]
So INTENDED BEHAVIOR is a much better label, and less curt, for the icons however that doesn't address the missing borders around the button that I amended earlier. :)
