### ISSUE TITLE
32bit AppImage

### ISSUE THREAD

**Issue by QuImUfu** [QupZilla/qupzilla#2278]
I am currently using a 32bit Linux distribution (Tiny Core Linux) and there is no 32bit AppImage on the website.

**Comment by cranes-bill** [comment]
AppImage is based of [precompiled Qt release](https://download.qt.io/official_releases/qt/5.8/5.8.0/) where 32 bit version is also not available.

**Comment by nowrep** [comment]
You should run 64bit distro, there is no reason not to (unless you have ancient hardware, but then it won't run Chromium anyway).

**Comment by QuImUfu** [comment]
@cranes-bill 
Understood, thanks for looking into it. :+1: Will see if someone from Tiny Core Linux can create a package.
@nowrep 
There is another reason: The 64bit Tiny Core Linux does not have all the packages i need and i have no hdd for a different distro in the moment. Additionally Tiny Core Linux 32bit rocks. And why should i need 64bit? 
Additionally i actually have installed chromium on a 32bit PC (old Pentium 4). It runs.

**Comment by Martii** [comment]
@QuImUfu 

> ... ancient hardware ...

can mean "planned obsolescence". 32 bit architecture is being replaced by 64 bit. 32 bit can be faster however usually can't handle larger data and programs.

**Comment by Martii** [comment]
@nowrep 
It is kind of ironic with this issue that the Windows native app is 32 bit still ;)

**Comment by nowrep** [comment]
No, it's not. There is more percentage of 32bit installs on Windows than on Linux. Also, there is no issue with running 32bit apps on 64bit Windows as all 32bit libraries are already all there.

**Comment by Martii** [comment]
I can run 32 bit apps in my Linux distro just fine though. We even have a full mirror set for them.

**Comment by nowrep** [comment]
Yes, but you have to install all 32bit libraries which you already have in 64bit which only wastes disk space. On Windows, you have those from the installation.

**Comment by Martii** [comment]
HDD/SSD's are cheap. :) I've contemplated getting my 3 years chipset hardware, that only supports 2GiB maximum, up and running with Tumbleweed since it doesn't have UEFI *(EFI)* for testing... but of course I would prefer building rather than the universal at this time due to other issues.
