### ISSUE TITLE
pop up blocker

### ISSUE THREAD

**Issue by ralpheeee88** [QupZilla/qupzilla#2285]
is there a built in pop up blocker or an extension/plugin which i can use?

**Comment by Martii** [comment]
Edit &rarr; Preferences &rarr; Privacy &rarr; JavaScript options &rarr; Open popup windows ... ensure **unticked**.

Edit &rarr; Preferences &rarr; Tabs &rarr; Tabs behaviour &rarr; Open popup windows in tabs ... ensure **ticked**.

Testing site... http://www.popuptest.com/

**Comment by ralpheeee88** [comment]
1st option was set up correctly ...2nd option I setup as mentioned and tested....with the test it worked however on certain websites i still receive pop ups in new tabs

**Comment by Martii** [comment]
Would you please give me a site to test against? *(preferably not one that requires a signin)*

**Comment by ralpheeee88** [comment]
https://extratorrent.cc/
(pls dont think less of me:)

**Comment by Martii** [comment]
Hmm... so that site has a popup immediately on load? Not seeing one here with my preferences set as above.

**Comment by Martii** [comment]
Should ask what is your platform and QupZilla version too.

**Comment by ralpheeee88** [comment]
using arch with a tiling window manager (i3wm)

**Comment by Martii** [comment]
Window manager shouldn't matter I think. Tested link under Linux *(ROSA)*, OS X, and Windows with dd6c76f28bfc1cb00399c7715cd79febff11f568 ... still no popup. 

Try a new profile, with those settings, and see if it still shows up? You can always switch back.

**Comment by ralpheeee88** [comment]
no joy....so when you click to download a torrent you dont receive a pop up ?

**Comment by Martii** [comment]
No popup... just the Open or Save File dialog native to Qt.

**Comment by Martii** [comment]
Using Qt 5.8? and all updates for ArchLinux?

**Comment by ralpheeee88** [comment]
well as long as it works for you i will keep working away...thxs for help!!!!! (btw love this browser which needless to say is my default browser....thxs for all your hardwork!!!!)

**Comment by iondissonance** [comment]
Can't confirm all links in this thread.

**Comment by nowrep** [comment]
Built-in adblock also blocks popups.
