### ISSUE TITLE
Windows: sometimes location completer popup is not shown

### ISSUE THREAD

**Issue by srazi** [QupZilla/qupzilla#2287]
... or it is hidden behind the QupZilla window.

1- Type something in address bar and then click on one of items. The popup will be hidden and also the item will not be loaded.
2- Type something in address bar and popup will not be shown.

Maybe we should add "windows" here b95a8be6002d2c1141ef15edf847f963689ece33

**Comment by nowrep** [comment]
> Maybe we should add "windows" here b95a8be

Can you test it if Qt::Popup fixes the issue on Windows?

**Comment by srazi** [comment]
> Can you test it if Qt::Popup fixes the issue on Windows?>

Yes
