### ISSUE TITLE
Default zoom not set on new page.

### ISSUE THREAD

**Issue by pullmoll** [QupZilla/qupzilla#2289]
I'm using a 4K monitor with DPI set to 150 setting in the desktop environment. Scaling in Qupzilla is still way too low, though.

Now when I configure a default zoom of e.g. 150%, the first page after starting Qupzilla or a page opened in a new tab still display with scaling at 100%. I have to increment and then decrement zoom to get what I want.

In other words: the default zoom is not respected when rendering a new page.

**Comment by Vistaus** [comment]
Same thing here (although my laptop has a 1920x1080 monitor, but I do experience this issue).

**Comment by Gibbz** [comment]
Yeah default zoom is not working at all for me on 2.1.2 :(

**Comment by bvbfan** [comment]
Preferences bug is fixed, Qt5.8 zoom factor bug is workarounded. I'm not tested if Qt 5.9 use correct zoom factor. https://github.com/QupZilla/qupzilla/pull/2330

**Comment by pullmoll** [comment]
Thank you!

**Comment by samcv** [comment]
This issue exists on QupZilla 2.1.2 with QT 5.9.2

Similar to before it will be at 100% zoom, then when i zoom in, it will zoom in to slightly more than the zoom had been set to. Can this issue be reopened. Thanks.

**Comment by cranes-bill** [comment]
Why should be opened - because you want to use by any reason version 2.1.2 forever?

**Comment by samcv** [comment]
It was 2.2.0 actually. It looks like the issue I was having was the .so file from 2.1.2 was still on my machine and it was loading that one instead of the 2.2.0 .so file (which was causing it to show the proper zoom at launch but not when I navigated). I purged my installation and now the problem is fixed.
