### ISSUE TITLE
Refresh button on my keyboard doesn't work

### ISSUE THREAD

**Issue by Vistaus** [QupZilla/qupzilla#2290]
I'm using Solus on a Dell Chromebook 13. Chromebooks have a slightly different keyboard layout: at the top there are buttons for back, forward, refresh, etc. Now before you dismiss this as a configuration issue: it's not. The right Chromebook layout is set in the system settings and the refresh key (and the other keys) works fine in other browsers (Vivaldi, Web, Chromium) but not in QupZilla. But the back and forward keys do work in QupZilla. So the refresh key not working's gotta be a QupZilla (or QtWebEngine?) issue. I'm using Qt 5.8.0

**Comment by innermous** [comment]
I think it's not related to webengine either.
I think it's related to key press handlers in Qt. Report a bug upstream, I guess.

**Comment by nowrep** [comment]
Does this helps?

```diff
diff --git a/src/lib/app/browserwindow.cpp b/src/lib/app/browserwindow.cpp
index ccea6a54..6cb65141 100644
--- a/src/lib/app/browserwindow.cpp
+++ b/src/lib/app/browserwindow.cpp
@@ -1128,6 +1128,7 @@ void BrowserWindow::keyPressEvent(QKeyEvent* event)
         }
         break;
 
+    case Qt::Key_Reload:
     case Qt::Key_Refresh:
         if (view) {
             view->reload();

```

**Comment by Vistaus** [comment]
@nowrep YES, that seems to have fixed it! Thank you so much! :smile:
