### ISSUE TITLE
F1 pressed in full-screen  causes qupzilla to be unusable

### ISSUE THREAD

**Issue by drtwisted** [QupZilla/qupzilla#2294]
When watching any HTML5 full-screen video (any YouTube one does the job) if F1 is pressed the about tab is showed, but since no borwser controls are available thus nothing could be done but closing the app by any OS means.

**Comment by Martii** [comment]
Whoops... confirmed... also repeated <kbd>F1</kbd> during video playback in full screen opens additional `qupzilla:about`s. <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>W</kbd> is also greyed out permanently under `File`. 

Linux
dd6c76f28b
Qt 5.8.0

**Comment by drtwisted** [comment]
Thanks for the tips, Martii

> Ctrl + Q seems to work though.

> "Close Tab" shortcut key sequence would be nice to work-around.

I guess it simply should not be showed, since why would anyone ever want to take a look at about section during full-screen video playback? :)

**Comment by Martii** [comment]
>    "Close Tab" shortcut key sequence would be nice to work-around.
>> I guess it simply should not be showed, since why would anyone ever want to take a look at about section during full-screen video playback? :)

Curious if a Content generated popup with no close action is triggered, diverted to a tab in Preferences by the browser, on a site that has embedded video that someone is watching... would it do the same thing and how to get rid of it. That's all. :) But I understand the <kbd>F1</kbd> browser sequence shouldn't be doing that.

**Comment by srazi** [comment]
This enables Escape key to exit fullscreen:
```diff
diff --git a/src/lib/webengine/webview.cpp b/src/lib/webengine/webview.cpp
index f777732..16a8845 100644
--- a/src/lib/webengine/webview.cpp
+++ b/src/lib/webengine/webview.cpp
@@ -1227,6 +1227,7 @@ void WebView::_keyReleaseEvent(QKeyEvent *event)
     switch (event->key()) {
     case Qt::Key_Escape:
         if (isFullScreen()) {
+            requestFullScreen(false);
             triggerPageAction(QWebEnginePage::ExitFullScreen);
             event->accept();
         }
```

**Comment by nowrep** [comment]
@srazi Why isn't `triggerPageAction(QWebEnginePage::ExitFullScreen)` enough?

**Comment by srazi** [comment]
`QWebEnginePage::ExitFullScreen` is triggered if a web element is full screen (it has filled viewport) but when other page e.g. `about page`, `view-source` or `new tab` are opened they have not full-screened element so `triggerPageAction(QWebEnginePage::ExitFullScreen)` will not emit `QWebEnginePage::fullScreenRequested()`

**Comment by srazi** [comment]
I think the correct solution is calling `triggerPageAction(QWebEnginePage::ExitFullScreen)` on changing tab and moreover if `Escape` should do the same as `F11` when window is in fullscreen mode then above diff applies.

**Comment by nowrep** [comment]
> I think the correct solution is calling triggerPageAction(QWebEnginePage::ExitFullScreen) on changing tab

Agree

> and moreover if Escape should do the same as F11 when window is in fullscreen mode then above diff applies.

F11 is bound to BrowserWindow::toggleFullScreen while the above diff is for the Esc key in webview.

**Comment by srazi** [comment]
> Agree

This is my busy week so I hope you will fix it, thanks.

> F11 is bound to BrowserWindow::toggleFullScreen while the above diff is for the Esc key in webview.

Yeah that diff doesn't fix what I meant in correct way.

> and moreover if Escape should do the same as F11 when window is in fullscreen mode then above diff applies.

I meant when window is fullscreen (no html fullscreen) then Esc key do nothing and window fullscreen mode is not toggled. BTW, after testing with Firefox I saw there also Esc key do nothing about non-html fullscreen mode.

**Comment by nowrep** [comment]
> I meant when window is fullscreen (no html fullscreen) then Esc key do nothing and window fullscreen mode is not toggled. BTW, after testing with Firefox I saw there also Esc key do nothing about non-html fullscreen mode.

That's correct and intended. Esc in non-html fullscreen should just stop page loading.
