### ISSUE TITLE
QupZilla configured with Qt 5.9 still identifies as being configured with 5.8

### ISSUE THREAD

**Issue by Vistaus** [QupZilla/qupzilla#2296]
How can I be sure QupZilla really did build with Qt 5.9 when the Configuration Information still says Qt version 5.8.0? Or is that a bug?

**Comment by nowrep** [comment]
Qt version in config page is a runtime Qt version, so there is an issue with your build.

**Comment by Vistaus** [comment]
Hmm, well I did build it with the qmake from 5.9 so why does it utilize 5.8 after building still then?

**Comment by nowrep** [comment]
Probably because your Qt 5.9 is not installed system-wide. QupZilla doesn't set RPATH unless you explicitly tell it to do so (when building with `NO_SYSTEM_DATAPATH`).

**Comment by Vistaus** [comment]
It is installed system-wide into /opt I also had 5.8 in /opt so...

**Comment by nowrep** [comment]
Then you can check which libraries it will load with `ldd libQupZilla.so` and also see RPATH with `chrpath qupzilla`

**Comment by Vistaus** [comment]
chrpath doesn't even exist on my system. Screw this, I'll revert to 5.8 5.9 beta is waaaay too bugged if it doesn't even run properly (which is a shame, 'cause I really wanted to see if a few QupZilla bugs I reported were fixed with 5.9 WebEngine).
