### ISSUE TITLE
QupZilla with Qt 5.9: symbol not defined

### ISSUE THREAD

**Issue by Vistaus** [QupZilla/qupzilla#2299]
Today I did successfully built QupZilla with Qt 5.9 Beta but it doesn't launch and gives this output:

[15:09:06] vistaus@vistaus-solus /media/MicroSD/Apps/qupzilla (127) 
> qupzilla
QupZilla: 5 extensions loaded
qupzilla: relocation error: qupzilla: symbol _Znwm, version Qt_5 not defined in file libQt5WebEngineCore.so.5 with link time reference
[15:09:06] vistaus@vistaus-solus /media/MicroSD/Apps/qupzilla (127) 
> 

How to fix that?

**Comment by Vistaus** [comment]
You know what, I think it's a bug in qmake 'cause I now rebuilt QupZilla with qmake from 5.8 but with all QtWebEngine and whatnot from 5.9 and now it does launch and QupZilla does report that it uses 5.9 now. Closing this and will probably report upstream.

**Comment by Martii** [comment]
@Vistaus 
Would you reference your bug upstream when you get a moment please? Definitely getting this.
