### ISSUE TITLE
QupZilla with Qt 5.9: platform theme not respected

### ISSUE THREAD

**Issue by Vistaus** [QupZilla/qupzilla#2300]
I'm not sure what the culprit is, but with Qt 5.9, QupZilla doesn't respect the platform theme settings from qt5ct. Other apps do so that leads me to think it's a bug in QupZilla... am I right/wrong?

**Comment by nowrep** [comment]
It should work if you build qt5ct with Qt 5.9.

**Comment by Vistaus** [comment]
Yeah, like I hadn't already tried that...
Like I said: other built with Qt 5.9 apps do respect the platform theme of qt5ct built with 5.9 so I fail to see how building qt5ct yet again with the same 5.9 is going to solve this. If other apps do respect it, then QupZilla is the one with the bug here...

**Comment by nowrep** [comment]
Does it work with Qt 5.8?

Also, I can't really do anything with bug report saying that it doesn't work. It may have a lot of reasons. Also, qt5ct works fine on other systems, so it is not a global issue.

There are various reasons why Qt would fail to load the platform plugin (which qt5ct is). You can eg. use `strace` to see if it at least tries to load it and it fails or it just doesn't find it at all.

**Comment by Vistaus** [comment]
It works with Qt 5.8

Will investigate further, thanks.

**Comment by Vistaus** [comment]
Hmm, somehow it got solved now after rebuilding QupZilla yet again. Not sure what solved it but oh well.
