### ISSUE TITLE
QupZilla crashes when restoring view-source tabs

### ISSUE THREAD

**Issue by srazi** [QupZilla/qupzilla#2302]
1- Open a webpage and then in context menu select `Show source code`
2- URL of page should be something like: `view-source:http://blog.qupzilla.com/`
3- Using session manager save current session named for example `test_session`
4- By session manager switch to `test_session`
5- If the current tab of `test_session` was `view-source` tab QupZilla will crash before restoring session.
6- If `view-source` tab is not the current tab of `test_session` then session will load correctly but when you click on `view-source` tab again QupZilla will crash.

Crash happens when [restoring history](https://github.com/QupZilla/qupzilla/blob/master/src/lib/webengine/webview.cpp#L264)

**Comment by nowrep** [comment]
That's QtWebEngine bug fixed in Qt 5.9. Restoring all internal pages leads to crash.
We should workaround it for Qt 5.8 though in `v2.1` branch.
