### ISSUE TITLE
Space saving options

### ISSUE THREAD

**Issue by funghetto** [QupZilla/qupzilla#2303]
It would be nice if there were:

1) A merged title bar like chromium/chrome with tabs and window options in the same line.

2) An UI Scaling options or a space saving theme for netbooks and laptops with a small monitor.

**Comment by Vistaus** [comment]
Well, I don't think 2 needs to be implemented (even though it's nice that Vivaldi has it) because qt5ct already allows you to set the UI scaling of Qt5 apps (like QupZilla).

**Comment by funghetto** [comment]
It doesn't seem available for Windows, Debian or MacOS.

**Comment by nowrep** [comment]
1. That's not possible on Linux (without using client-side decorations), so this will not be implemented.
2. You can hide menubar and also tabbar (with TabManager plugin).

**Comment by Vistaus** [comment]
@funghetto 
Windows: It's available through Windows Control Center.
Debian: It's available, like I pointed out, through qt5ct.
macOS: Not sure. Last time I used macOS there was an option to scale everything in system settings but I don't remember if Qt apps were affected by it.

**Comment by nowrep** [comment]
You don't need qt5ct to use Qt HighDPI scaling, but what @funghetto probably meant was scaling of just UI ("chrome" part of the browser, not also the webpages).

**Comment by Vistaus** [comment]
@nowrep That's also what I'm talking about. You can scale the chrome part of the browser/Qt apps through qt5ct.

**Comment by nowrep** [comment]
And how does that work?

**Comment by funghetto** [comment]
@nowrep How can chromium do this on Linux?

**Comment by nowrep** [comment]
Chromium uses client-side decorations, so they re-implement the window borders and titlebar so it looks and behaves completely different to native windows.
