### ISSUE TITLE
Integrate perceptual ad blocking

### ISSUE THREAD

**Issue by ShalokShalom** [QupZilla/qupzilla#2312]
There is a new technique to block ad`s by its visual content: 

https://chrome.google.com/webstore/detail/perceptual-ad-highlighter/mahgiflleahghaapkboihnbhdplhnchp
https://freedom-to-tinker.com/2017/04/14/the-future-of-ad-blocking/
http://randomwalker.info/publications/ad-blocking-framework-techniques.pdf

The source code is here: https://github.com/citp/ad-blocking

**Comment by nowrep** [comment]
I have no interest in implementing different ad blocking mechanism than already is implemented.
