### ISSUE TITLE
LocationBar: select all text if mouse goes down during selection

### ISSUE THREAD

**Issue by elvisangelaccio** [QupZilla/qupzilla#2316]
This is a Firefox feature that I'm really missing in Qupzilla. It would work like this:

* Start a text selection in the LocationBar with mouse left click
* While the mouse left-button is still pressed, move the mouse down
* The mouse cursor jumps to the end of the QLineEdit, selecting all the text along the way.

**Comment by nowrep** [comment]
That's behavior of GTK apps, you should request this to be added to Qt.

**Comment by elvisangelaccio** [comment]
Ah, interesting. So this feature should go in QLineEdit itself? (I might give it a shot)

**Comment by nowrep** [comment]
Yes

**Comment by elvisangelaccio** [comment]
Thanks. Closing this issue then.
