### ISSUE TITLE
Native scrollbars not working within bugzilla websites

### ISSUE THREAD

**Issue by elvisangelaccio** [QupZilla/qupzilla#2317]
For example, bugs.kde.org or bugs.freedesktop.org. See attached screenshot.
![spectacle e27157](https://cloud.githubusercontent.com/assets/7082518/25339861/42d17894-2904-11e7-9871-145a0ebdd2b6.png)

**Comment by nowrep** [comment]
It only works for main scrollbars (eg. scrolling`<body>`), because it is just a hack - it hides those scrollbars with CSS and moves scrollbar widgets in the appropriate position.
Also, you shouldn't probably use it because #2246

**Comment by elvisangelaccio** [comment]
I see. So QtWebengine does not support themes? :/ Is there an upstream feature request about this?

**Comment by nowrep** [comment]
No, Chromium doesn't support native rendering of UI elements and there are no plans to add it. You can only style the scrollbars with CSS (similar to what plasma-browser-integration does).

**Comment by elvisangelaccio** [comment]
I see, thanks again.
