### ISSUE TITLE
Debian Version Very Old

### ISSUE THREAD

**Issue by gplforever** [QupZilla/qupzilla#2318]
The current version on Debian Stable is 1.6.6 which doesn't appear to have been updated in an age. Please consider updating Qupzilla in Debian and arranging for regular updates. If regular updates would be an issue might it be possible to provide a Flatpack version as Debian supports this system and having that be regularly updated?

**Comment by cranes-bill** [comment]
You should ask [Debian](https://www.debian.org/support) about that.
Flatpak [manifest](https://github.com/QupZilla/qupzilla/blob/master/flatpak/org.qupzilla.QupZilla.json) is provided in the source.
You might also try [AppImage](https://www.qupzilla.com/download#linux).
