### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by jamesqf** [QupZilla/qupzilla#2319]
I get this message when trying to log in to my (new) credit card web site, usbank.com.  I've tried deleting all cookies* that seem related to the account, as suggested in a web search, but that does not help.  The problem does not happen when I use Firefox.  Does anyone know of a fix?

I'm using version 2.1.99 on OpenSuse 42.2.

*Incidentally, is there a way to make the text in the cookie manager (and I presume other system menus) large enough to actually read without a magnifier?

**Comment by nowrep** [comment]
> *Incidentally, is there a way to make the text in the cookie manager (and I presume other system menus) large enough to actually read without a magnifier?

It uses standard font size.
