### ISSUE TITLE
QupZilla doesn't remember password with Tiny Tiny RSS

### ISSUE THREAD

**Issue by fturco** [QupZilla/qupzilla#2321]
I have a personal Tiny Tiny RSS instance at https://tt-rss.fturco.net/. I can successfully log in with my password, but QupZilla doesn't ask me if I want to save it. I'm using QupZilla 2.1.99 (5e12180377) and QtWebEngine 5.8.0 on a Gentoo Linux system. I can create a test account on my Tiny Tiny RSS instance upon request.

**Comment by nowrep** [comment]
Because it uses https://dojotoolkit.org/reference-guide/1.10/dijit/form/Form.html and somehow it changes the form element (on which submit event listener is registered), so that the previously registered event handler gets lost.
