### ISSUE TITLE
Stop action stuck on codereview.qt-project.org

### ISSUE THREAD

**Issue by elvisangelaccio** [QupZilla/qupzilla#2322]
When I go on codereview.qt-project.org with qupzilla, the Stop action gets stuck and never becomes the Reload action (even if the loading finished). If I trigger the Stop action with the mouse, nothing happens.

Screenshot:

![screenshot_20170426_133948](https://cloud.githubusercontent.com/assets/7082518/25432687/be708c1a-2a85-11e7-9336-bcf31399a9a6.png)

**Comment by elvisangelaccio** [comment]
Also, since the Reload action is disabled, it's not possible to use the F5 shortcut.

**Comment by Chiitoo** [comment]
Can't seem to make it happen with the following:

- Application version 2.1.99 (5e12180377)
- QtWebEngine version 5.9.0

(Qt is beyond the beta releases.)

**Comment by nowrep** [comment]
That's a bug in QtWebEngine, hopefully fixed in 5.9 @Chiitoo

**Comment by elvisangelaccio** [comment]
Just upgraded to Qt 5.9 beta2 and I can confirm that fixes the issue!

**Comment by Martii** [comment]
@elvisangelaccio 
Can you go to Edit &rarr; Preferences though?

**Comment by elvisangelaccio** [comment]
@Martii Yes, why?

**Comment by Martii** [comment]
@elvisangelaccio 
Curious... what platform you have if I may ask... Linux distro here bombs out with Beta 2 so no way to do full testing... haven't tried the Mac yet. Sorry about skewing the issue a bit but polling to see what's up with Beta 2 on dev station.

**Comment by elvisangelaccio** [comment]
@Martii I'm running archlinux here, Qt 5.9 is from the kde-unstable repository.

**Comment by Martii** [comment]
@elvisangelaccio 
Recompiled again with the Qt Creator update and blew away my barely used profile... seems to work like yours now. Thanks for the stat... helped me go in a different direction. Profile corruption seems to be a constant between recompiles. :\

**Comment by Martii** [comment]
Correction... clicking Notifications kills it too. Uggh. Still think Qt 5.9 Beta 2 is a bit buggy.

**Comment by nowrep** [comment]
@Martii It has nothing to do with Qt 5.9, just remove/rebuild the testplugin.

**Comment by Martii** [comment]
@nowrep 
This is from a `$ make distclean` and then the usual qmake/make... so if it's not in [the standard build instructions](https://github.com/QupZilla/qupzilla/blob/master/BUILDING.md) then it needs some documentation there. I even checked out the repository from scratch and it still produces that crash. It is a little odd that a test plugin is present. The prior error a few weeks ago was directly on Edit &rarr; Preferences with no other clicks.

**Comment by nowrep** [comment]
> so if it's not in the standard build instructions then it needs some documentation there

No it doesn't, build instructions are fine - your build went fine, this is runtime error. It aborts on loading the plugin, which it shouldn't ideally (it should fail to load the plugin instead).

>  The prior error a few weeks days ago was directly on Edit → Preferences with no other clicks.

With any crash I need a backtrace + terminal output, otherwise it's useless to me.

**Comment by Martii** [comment]
> With any crash I need a backtrace + terminal output, otherwise it's useless to me.

Of course but I also have limited time to do QupZilla. So better documentation is required. I'm also not at dev station so I won't be able to output anything until this weekend.

> which it shouldn't ideally (it should fail to load the plugin instead).

So that would be the error with using Qt 5.9 Beta 2 since it's definitely not present in Qt 5.8.

Additionally the Speed Dial is still bugged in Qt 5.9 Beta 2 versus the last test I did before upgrade from Qt 5.9 Beta 1. Try opening up multiple Speed Dials. My laptop is severely limited on diagnostics not to mention this micro keyboard which makes typing difficult.

If you provide some instructions on manual removal of the "test plugin", or a link, I'd be happy to try that when I get back. :)

**Comment by nowrep** [comment]
> Of course but I also have limited time to do QupZilla. So better documentation is required. I'm also not at dev station so I won't be able to output anything until this weekend.

That's not really an excuse, if you have time to write about the issue you also have time to copy the terminal output and at least also the backtrace that gets automatically generated (although it may not be much helpful).

> So that would be the error with using Qt 5.9 Beta 2 since it's definitely not present in Qt 5.8.

Maybe, maybe not.

> If you provide some instructions on manual removal of the "test plugin", or a link, I'd be happy to try that when I get back. :)

`rm /usr/lib64/qupzilla/libTestPlugin.so`

**Comment by Martii** [comment]
I'll just ignore the demand/excuse part... obviously you don't have as much to do right now as I am doing.

> `rm /usr/lib64/qupzilla/libTestPlugin.so`

Simple enough... will try it when I'm at dev station where the error shows up. Laptop doesn't have the test plugin present so not sure if it's present since it's the same distro. I don't have time to overheat the laptop with a compile *(this thing called real life gets in the way and that's more than a valid "excuse")*... typing is quick unlike debugging a bad Qt release. :)

You might want to take into consideration that other machines may produce different results... just like OUJS dev and pro are slightly different. Qt isn't perfect neither is *nodejs* for hardwarde/platform abstraction.

**Comment by nowrep** [comment]
> obviously you don't have as much to do right now as I am doing.

You can do it when you have time, I never said you need to get the backtrace right now :D

> Laptop doesn't have the test plugin present so not sure if it's present since it's the same distro.

Test plugin is only built in debug mode, so if you ever used debug build then that's where you get it.

> You might want to take into consideration that other machines may produce different results... just like OUJS dev and pro are slightly different. Qt isn't perfect neither is nodejs for hardware/platform abstraction.

You don't need to tell me this, I'm well aware. Just for the record, that error about loading libTestPlugin.so comes from `dlopen` (`man -s3 dlopen`) so it has nothing to do with Qt.

Also, this really has nothing to do with this issue.

**Comment by Martii** [comment]
> ... Qt 5.9 beta2 ...

Everything's related but experience will provide that to you over time. :) Thanks for doing the additional research as to the stability, or lack thereof, of Beta 1 vs Beta 2 *(and Qt 5.8 comparison)*. ... inclusive to this issue. e.g. I still don't recommend Qt 5.9 Beta 2 until they work out some of the valid issues presented... a closed issue as it's already been confirmed/claimed as an upstream issue is relevant... see refs in prior posts here.

Anyhow gotta run... if need be I'll issue isolate things when I do have time. Work, work, work... would be nice to just play here with development instead. :)

**Comment by Martii** [comment]
> `rm /usr/lib64/qupzilla/libTestPlugin.so`

This worked. :) Thank you.

Still buggy with Qt 5.9 Beta 2 and Beta 3 now though.
