### ISSUE TITLE
Compilation error with Openssl 1.1.0

### ISSUE THREAD

**Issue by joseriosneto** [QupZilla/qupzilla#2324]
After upgrading to openssl 1.1.0 I'm experiencing the following error: 

> error: field ‘m_encodeCTX’ has incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’

Digging a bit I found this is happenning because most of libcrypto and libssl internal structures [were made opaque](https://www.openssl.org/news/openssl-1.1.0-notes.html). This [workaround](https://github.com/openssl/openssl/issues/962#issuecomment-208792020) fixes the problem for me.

> QupZilla: 2.1.99 (5e121803)
> QWebEngine: 5.8.0

**Comment by nowrep** [comment]
efc4725e91e10ccfef257143408d3a683e74a866
