### ISSUE TITLE
Can start at archlinux

### ISSUE THREAD

**Issue by gogonkt** [QupZilla/qupzilla#2326]
$qupzilla
qupzilla: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

I searched for a while, but all pointed to openssl :(
any idea?

community/qupzilla 2.1.2-3

**Comment by nowrep** [comment]
Do you have latest `openssl` installed?

**Comment by OlafLostViking** [comment]
Arch recently updated openssl to 1.1. You probably have to install the `openssl-1.0` package in addition.

I am using an up-to-date amd64 system and QupZilla works:
```
$ ldd $(which qupzilla) | egrep "crypto|ssl"
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f8aeef32000)
        libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00007f8ae4316000)
        libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x00007f8ae3ea5000)
$ pacman -Qo /usr/lib/libcrypto.so.1.1
/usr/lib/libcrypto.so.1.1 is owned by openssl 1.1.0.e-1
$ pacman -Qo /usr/lib/libssl.so.1.0.0
/usr/lib/libssl.so.1.0.0 is owned by openssl-1.0 1.0.2.k-3
```

**Comment by OlafLostViking** [comment]
@gogonkt: If this helped you starting QupZilla, please close this issue to keep the issue tracker clean(er).

**Comment by nowrep** [comment]
Arch package works fine for me. Your issue should instead be reported to Arch bug tracker.
