### ISSUE TITLE
Nix/Mac: Speed Dial Abnormalities

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla#2329]
With Qt 5.9 nearing release status from https://wiki.qt.io/Qt_5.9_Release thought I would make this issue to see what is up.

Speed dial changes window thumbnail size on new tabs. This is reproducible however it seems to change depending on browser session. Mac has to have a page opened first, used OUJS, then it does it... Linux is just all over the place.

See attached zipped MP4 video. *(~462.4KiB H.265 HEVC)*
[SpeedDialIssue.zip](https://github.com/QupZilla/qupzilla/files/980365/SpeedDialIssue.zip)

* 54949f94f3d309e633de671205a1691040840cc3 with Qt 5.9 Beta 2 and Beta 3
* Affects Linux and OS X

**Comment by Martii** [comment]
With 92b49be0c2e2e4195e92fc180650056e4e3bff74 and Qt 5.9 **Beta 4** they are always "huge" instead of "small" now in Linux build.

**Comment by nowrep** [comment]
Can you post terminal output or errors from javascript console?

**Comment by Martii** [comment]
Non-debug build opening to Speed Dial and then opening two more Speed Dials:

``` sh-session
$ qupzilla
QupZilla: 1 extensions loaded
js: Uncaught TypeError: Cannot read property 'pagesChanged' of undefined
js: Uncaught TypeError: Cannot read property 'pagesChanged' of undefined
js: Uncaught TypeError: Cannot read property 'pagesChanged' of undefined
```

**Comment by Martii** [comment]
Sorry about that.. mouse veered and closed... reopened.

**Comment by nowrep** [comment]
> js: Uncaught TypeError: Cannot read property 'pagesChanged' of undefined

Looks like QtWebChannel doesn't work / is not setup correctly. Maybe there are some changes in Qt 5.9 how this works (didn't test it myself yet).
This will also affect other things, like password completion, etc.

> Sorry about that.. mouse veered and closed... reopened.

No problem, happens all the time here on github :D

**Comment by nowrep** [comment]
It works fine for me with Qt 5.9 RC.

**Comment by Martii** [comment]
@nowrep 

> It works fine for me with Qt 5.9 RC.

Actually it doesn't work properly still. Tested it when the RC was released last week and it still happens both on Linux and the Mac.

**Comment by nowrep** [comment]
I pushed a fix for that, should work fine now.

**Comment by Martii** [comment]
Will try when I get back to dev. 

With next release are you going to need the .dmg or are you able to nab it from Travis CI?
