### ISSUE TITLE
Java does not work

### ISSUE THREAD

**Issue by Peter2121** [QupZilla/qupzilla#2334]
FreeBSD (PCBSD flavor) 10.3
IcedTea plugin installed and works in another browsers.
Java is activated in QupZilla but does not work.

Configuration Information
Information about version
Application version
1.8.9
Qt version
4.8.7
WebKit version
534.34
Platform
BSD 4.4
Browser Identification
Mozilla/5.0 (X11; BSD Four) AppleWebKit/534.34 (KHTML, like Gecko) QupZilla/1.8.9 Safari/534.34

Paths
Profile
/usr/home/peter/.config/qupzilla/profiles/default
Settings
/usr/home/peter/.config/qupzilla/profiles/default/settings.ini
Saved session
/usr/home/peter/.config/qupzilla/profiles/default/session.dat
Pinned tabs
/usr/home/peter/.config/qupzilla/profiles/default/pinnedtabs.dat
Data
/usr/local//share/qupzilla
Themes
/usr/local//share/qupzilla/themes
Translations
/usr/local//share/qupzilla/locale
Build Configuration
Debug build
Disabled
Portable build
Disabled
Extensions
Name	Version	Author	Description
StatusBar Icons	0.2.0	David Rosca <nowrep@gmail.com>	Adds additional icons and zoom widget to statusbar
Access Keys Navigation	0.4.3	David Rosca <nowrep@gmail.com>	Provides support for navigating in webpages by keyboard shortcuts
AutoScroll	0.1.5	David Rosca <nowrep@gmail.com>	Provides support for autoscroll with middle mouse button
Flash Cookie Manager	0.3.0	Razi Alavizadeh <s.r.alavizadeh@gmail.com>	You can easily view/delete flash cookies stored on your computer. This is a solution for having more privacy.
GreaseMonkey	0.5.2	David Rosca <nowrep@gmail.com>	Provides support for userscripts (www.userscripts.org)
Mouse Gestures	0.4.0	David Rosca <nowrep@gmail.com>	Provides support for navigating in webpages by mouse gestures
PIM	0.1.2	Mladen Pejaković <pejakm@autistici.org>	Adds ability for QupZilla to store some personal data
Tab Manager	0.5.0	Razi Alavizadeh <s.r.alavizadeh@gmail.com>	Adds ability to managing tabs and windows
Shockwave Flash	Shockwave Flash 25.0 r0
Preferences
Option	Value
[AdBlock]
disabledRules	"empty"
enabled	true
lastUpdate	2017-05-15T10:56:37
useLimitedEasyList	true
[AddressBar]
AddCountryDomainWithAltKey	true
CustomProgressColor	#43ace8
ProgressStyle	0
SelectAllTextOnClick	false
SelectAllTextOnDoubleClick	true
ShowLoadingProgress	false
UseCustomProgressColor	false
alwaysShowGoIcon	false
showSuggestions	0
showSwitchTab	true
useInlineCompletion	true
[Bookmarks]
showOnlyIconsInToolbar	false
[Browser-Fonts]
CursiveFont	Noto Sans
DefaultFontSize	15
FantasyFont	Noto Sans
FixedFont	Droid Sans Mono
FixedFontSize	14
MinimumFontSize	10
MinimumLogicalFontSize	10
SansSerifFont	Droid Sans
SerifFont	Noto Serif
StandardFont	Noto Serif
[Browser-Tabs-Settings]
ActivateLastTabWhenClosingActual	false
AlwaysSwitchTabsWithWheel	false
AskOnClosing	false
OpenNewTabsSelected	false
TabsOnTop	true
dontCloseWithOneTab	false
hideTabsWithOneTab	false
newEmptyTabAfterActive	false
newTabAfterActive	true
showCloseOnInactiveTabs	0
showClosedTabsButton	false
showTabPreviews	false
tabPreviewAnimationsEnabled	true
[Browser-View-Settings]
LocationBarWidth	865
SideBarWidth	250
WebSearchBarWidth	253
WebViewWidth	2000
WindowGeometry	QByteArray
WindowMaximised	false
settingsDialogPage	3
showAddTabButton	false
showBackForwardButtons	true
showBookmarksToolbar	true
showHomeButton	true
showNavigationToolbar	true
showReloadButton	true
showStatusBar	true
showWebSearchBar	true
useTransparentBackground	false
[ClickToFlash]
Enable	true
Enabled	true
whitelist	"empty"
[DownloadManager]
CloseManagerOnFinish	false
ExternalManagerArguments	"empty"
ExternalManagerExecutable	"empty"
UseExternalManager	false
defaultDownloadPath	"empty"
useNativeDialog	true
[FileDialogPaths]
WebPage-ChooseFile	/usr/home/peter/Clients/BIMP
[Language]
language	"empty"
[Notifications]
Enabled	true
Position	QPoint(10, 10)
Timeout	6000
UseNativeDesktop	true
[Plugin-Settings]
AllowedPlugins	/usr/local/lib/qupzilla/libStatusBarIcons.so
EnablePlugins	true
[Preferences]
Geometry	QByteArray
[SSL-Configuration]
CACertPaths	"empty"
DisableWeakCiphers	true
IgnoreAllSSLWarnings	false
[SearchEngines]
DefaultEngine	DuckDuckGo
SearchWithDefaultEngine	false
activeEngine	DuckDuckGo
[SessionRestore]
isRunning	true
[Shortcuts]
useSingleKeyShortcuts	false
useSpeedDialNumberShortcuts	true
useTabNumberShortcuts	true
[SpeedDial]
background	"empty"
backsize	auto
pages	url:"http://www.qupzilla.com"|title:"QupZilla";url:"http://blog.qupzilla.com"|title:"QupZilla Blog";url:"https://github.com/QupZilla/qupzilla"|title:"QupZilla GitHub";url:"https://duckduckgo.com"|title:"DuckDuckGo";
pagesrow	4
sdcenter	false
sdsize	231
[Themes]
activeTheme	linux
[User-Agent-Settings]
DomainList	"empty"
UsePerDomainUA	false
UserAgentsList	"empty"
[Web-Browser-Settings]
AllowLocalCache	true
AnimateScrolling	true
AutomaticallyOpenProtocols	"empty"
BlockOpeningProtocols	"empty"
CachePath	/usr/home/peter/.config/qupzilla/profiles/default/networkcache/534.34-Qt4.8.7/
CaretBrowsing	false
CheckUpdates	false
DNS-Prefetch	false
DefaultZoomLevel	8
DoNotTrack	false
HTML5StorageEnabled	true
IncludeLinkInFocusChain	false
LoadTabsOnActivation	true
LocalCacheSize	50
PrintElementBackground	true
SSLv3Sites	centrum.sk,centrum.cz,oneaccount.com,hdi.de,live.com,i0.cz,sermepa.es
SavePasswordsOnSites	true
SendReferer	true
SpatialNavigation	false
UserAgent	"empty"
XSSAuditing	false
allowFlash	true
allowHistory	true
allowJava	true
allowJavaScript	true
closeAppWithCtrlQ	true
deleteHTML5StorageOnClose	false
deleteHistoryOnClose	false
enableFormsUndoRedo	false
maximumCachedPages	3
userStyleSheet	"empty"
wheelScrollLines	3
zoomTextOnly	true
[Web-Proxy]
HostName	"empty"
HttpsHostName	"empty"
HttpsPassword	"empty"
HttpsPort	8080
HttpsUsername	"empty"
PacUrl	"empty"
Password	"empty"
Port	8080
ProxyExceptions	localhost,127.0.0.1
ProxyType	3
UseDifferentProxyForHttps	false
UseProxy	0
Username	"empty"
[Web-URL-Settings]
afterLaunch	3
homepage	qupzilla:start
newTabUrl	qupzilla:speeddial
This page contains information about QupZilla's current configuration - relevant for troubleshooting. Please include this information when submitting bug reports.

**Comment by nowrep** [comment]
QtWebKit (1.x) version is no longer supported.

**Comment by Peter2121** [comment]
The version of QtWebKit indicated in "About" is 534.34, the version of FreeBSD port, installed as QupZilla dependency is 4.8.7. Neither is 1.x. What version is not supported??

**Comment by nowrep** [comment]
QupZilla is 1.x, and that is no longer supported. Only QupZilla 2.x (with QtWebEngine) is supported.

**Comment by Peter2121** [comment]
Nice to know it, so the only version present in FreeBSD ports collection is not supported anymore :(
