### ISSUE TITLE
QupZilla crashing

### ISSUE THREAD

**Issue by joseriosneto** [QupZilla/qupzilla#2335]
QtWebEngine: 5.8.0
QupZilla: 92b49be0c2e2
Plugins: Flash Cookie Manager, ImageFinder, Readability and VimPlugin.

The browser has been crashing for a few days. I still don't know why it's happenning or how to reproduce it but I got a coredump. None of the plugin libs are in the backtrace. 
[qupzilla_core.zip](https://github.com/QupZilla/qupzilla/files/1007303/qupzilla_core.zip)

**Comment by joseriosneto** [comment]
It is happens deterministically when I log into gmail and go to Docs through the top right button on the left of notifications items. I attached a picture of it. 

I have also ran QupZilla with `--private-browsing` and `--no-extensions` to make sure no plugins or profile configuration is involved. 

This is strange. I used to access Docs this way. Has anyone experienced this too? It might be something of my environment.

**Comment by joseriosneto** [comment]
Clicking on the above picture also make the browser crash. I thought it could be some updating on libQtWebEngine but I just recompiled QupZilla and it's still happenning.

I am on Arch Linux, btw.

**Comment by joseriosneto** [comment]
Bug was introduced by 92b49be0c. @bvbfan is the same thing happening to you?

**Comment by bvbfan** [comment]
journalctl --file does not read dump file, can you provide as text?

**Comment by nowrep** [comment]
Can you please post backtrace?
