### ISSUE TITLE
Extraction of appimages are broken

### ISSUE THREAD

**Issue by supriyo-biswas** [QupZilla/qupzilla#2341]
Appimages often can't be run due to the way distros are set up or due to virtualization limitations. However, appimages should still be usable in this situation, as they come with a built-in `--appimage-extract` switch, that spits out all the embedded files into a directory.

Unfortunately, in Qupzilla's appimage it doesn't work, and simply creates an empty directory named `squashfs-root`.

In the [appimages provided](https://bintray.com/probono/AppImages) by the [official project](https://github.com/probonopd/appimagekit), I found out the switch works normally; so this bug is probably caused due to use of an older version of the appimagekit framework. Could this bug be resolved?

**Comment by cranes-bill** [comment]
> ....Could this bug be resolved?

Perhaps in next release.

**Comment by nowrep** [comment]
Will be fixed in next release.
