### ISSUE TITLE
Dragging tab

### ISSUE THREAD

**Issue by neel5481** [QupZilla/qupzilla#2343]
Hi,

How can i drag the tab out of main window and again add new child window to the floating tab as we do in chrome ?

Let me know how to do that in this browser ?

**Comment by dvdn** [comment]
Waiting for this new feature, you can open Qupzilla again to get a 2nd (or third or...) window.

**Comment by nowrep** [comment]
You can only detach tabs (right click on tab -> detach tab). Attaching tabs back to other windows is not implemented.

**Comment by innermous** [comment]
This is a really lacking thing.

**Comment by srazi** [comment]
@innermous As an alternative, after f8873aef7fa4224766a2cace27356d8937a6dbc1, `Tab Manager` plugin supports dragging tabs between windows.

**Comment by innermous** [comment]
@srazi thanks, but I use my own tree-style plugin for tabs :)
I am interested in implementing dragging between windows, though, and I'll implement it definitely.
