### ISSUE TITLE
[Wayland] URL bar dropdown menu misplaced

### ISSUE THREAD

**Issue by elvisangelaccio** [QupZilla/qupzilla#2344]
To reproduce in a Plasma Wayland session:
1. Focus the URL lineedit
2. Type something
3. The dropdown menu will open in a random position, rather than below the line edit.

**Comment by nowrep** [comment]
281919fc4d5af74b6cc82ae

**Comment by elvisangelaccio** [comment]
Oh sorry for the duplicate. Any ETA for a release with that fix?

**Comment by nowrep** [comment]
No ETA, this month I hope.

**Comment by elvisangelaccio** [comment]
I tried the lastest git master, but 281919f doesn't seem to fix this issue. Does the LocationCompleterView have a transient parent QWindow set? With QMenus it's enough to set a parent QWidget, not sure about QListViews...

**Comment by nowrep** [comment]
Obviously it worked before, at least with Qt 5.8 - see #2236. I don't have Qt 5.9 with wayland right now, so I can't test it.

**Comment by elvisangelaccio** [comment]
Yep this with Qt 5.9 RC, and qupzilla git master. I have a patch that fixes it but I'm not sure if this is how you want to fix it: https://paste.kde.org/pmzrhmome

**Comment by nowrep** [comment]
Can this be done in `showPopup` instead, because LocationCompleterView is static so shared also with other windows.

**Comment by elvisangelaccio** [comment]
See https://github.com/QupZilla/qupzilla/pull/2347
