### ISSUE TITLE
Cannot search in Bugzilla based sites

### ISSUE THREAD

**Issue by OlafLostViking** [QupZilla/qupzilla#2349]
When starting a search on bugs.kde.org or bugs.freedesktop.org, Qupzilla shows a black screen with a little white square in it (I guess some GIF animation or so...) but doesn't continue:
![qupzilla_bugzilla](https://user-images.githubusercontent.com/3428075/26977245-71fc960c-4d27-11e7-8e06-3da2d8213e1f.png)

While I may not like this way of building websites, it is what it is and I currently have to use Konqueror to access bugzilla.

**Comment by iondissonance** [comment]
Can't confirm. openSUSE Tumbleweed, last build from 2.1 branch, Qt 5.7.1

**Comment by nowrep** [comment]
Works fine here too (Qt 5.9), anything interesting in terminal output?

**Comment by OlafLostViking** [comment]
Thanks for having a look. I tried building from git, as release as well as debug, on a machine with nvidia and a machine with intel (in this case, the screen was white instead of black....). No output on the console. But I finally found the problem! I had to set the user agent to Firefox because of some other sites misbehaving and by reverting that change, bugzilla works again.

I'm not sure if this can still be considered a QupZilla issue? So I'll close this report for now. In case you still want to have a look into this, this is what the HTTP response looked like:
```
WARNING: YOUR BROWSER DOESN'T SUPPORT THIS SERVER-PUSH TECHNOLOGY.
--------- =_YDsdQHBjqZFDFudkt
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html>
<html>
  <head>
    <title>KDE Bugtracking System is pondering your search</title>
    <link href="skins/standard/global.css?1477425084"
          rel="stylesheet" type="text/css">
  </head>
  <body>
    <h1 id="serverpush_msg">Please stand by ...</h1>

    <p class="center">
      <progress>Data is being retrieved...</progress>
    </p>

  </body>
</html>
--------- =_YDsdQHBjqZFDFudkt
Content-Type: text/html; charset=UTF-8
Set-Cookie: LASTORDER=bug_status%2Cpriority%2Cassigned_to%2Cbug_id; path=/; expires=Fri, 01-Jan-2038 00:00:00 GMT

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bug List</title>

      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<link href="data/assets/047b8eefce3fe5293497ae650dc8314f.css?1491294030" rel="stylesheet" type="text/css">
...
```
