### ISSUE TITLE
Is it possible to support html5 h264 element on Mac OS

### ISSUE THREAD

**Issue by happybrisk** [QupZilla/qupzilla#2350]
Package from [official website](https://www.qupzilla.com/) doesn't work.

I follow the FAQ and install gstreamer (https://gstreamer.freedesktop.org/data/pkg/osx/1.10.4/gstreamer-1.0-1.10.4-x86_64.pkg)
Then I compile from master `016ea1c`, but it doesn't work either.

OS: Mac OS 10.12.6(Beta)
QT: 5.9.0
Qupzilla: 2.1.99(master `016ea1c`)

**Comment by cranes-bill** [comment]
It dosn't use gstreamer. I think [this](https://github.com/QupZilla/qupzilla/issues/1973#issuecomment-227437925) answer is compleately applicable to your issue.

**Comment by happybrisk** [comment]
It seems that I have to build the whole qt from source,  then rebuild my little qupzilla...
I'll have a try...

**Comment by happybrisk** [comment]
Steps:

1. I download Qt from official website and install it to some directory `/Users/xxx/Qt5`
2. I changed directory to `/Users/XXX/Qt5/5.9/Src/qtwebengine` then ran `../../clang_64/bin/qmake WEBENGINE_CONFIG+=use_proprietary_codecs`, then `make`. It took a long long time...
3. I rebuild my qupzilla.

But it didn't work. [html5test](http://html5test.com) says that my browser does not support H264 yet.

Any suggestion?

**Comment by nowrep** [comment]
https://doc.qt.io/qt-5/qtwebengine-features.html#audio-and-video-codecs
