### ISSUE TITLE
Certain elements on reddit pages don't respond to clicks

### ISSUE THREAD

**Issue by abrouwers** [QupZilla/qupzilla#2353]
(Sorry, I'm not certain if this is a QtWebEngine issue vs. qupzilla)

I was browsing reddit, and noticed that some of the buttons used to filter comments don't work; for example:

https://www.reddit.com/r/linux/comments/6gfr7x/kde_frameworks_5350_released/

Clicking the +/- next to a username will normally expand or hide comments.  Also, the filter buttons at the top ("Sorted By") doesn't present the normal drop-down menu.  This is really useful on reddit when one is searching for old posts, and wants to sort the results by date instead of popularity, for example.

I'm running qt-* 5.9.0, and using qupzilla compiled from git (rev 112.g016ea1c9).

**Comment by cranes-bill** [comment]
can't reproduce!
Tried with:
Qt: 5,6 & 5,8 & 5,9
QupZilla: 2.0 & c9a52e59c3

**Comment by samcv** [comment]
@abrouwers I've had this happen sometimes with certain GreaseMonkey scripts. Have you tried disabling all extensions and restarting the browser?

**Comment by abrouwers** [comment]
Wow, sorry for the noise.  I unchecked "allow application extensions to be loaded," (even though I didn't have any of the extensions checked?!), and it works.
