### ISSUE TITLE
Show source incorrectly tries to fetch content from the server for #tags, causing server error

### ISSUE THREAD

**Issue by samcv** [QupZilla/qupzilla#2354]
If you go to this this page [http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02][1]

When you right click and click view-source it takes you to: `view-source:http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html%23tag_18_06_02`

Which shows you:
```html

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02 was not found on this server.</p>
</body></html>
```

It is clear that when you do this, it's literally requesting the site including the `#tag_18_06_02` from the server, which obviously does not exist as a file on the server.

[1]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02

**Comment by nowrep** [comment]
This is already fixed when using QtWebEngine >= 5.8.
