### ISSUE TITLE
GreaseMonkey plugin doesn't implement GM_ storage methods properly.

### ISSUE THREAD

**Issue by SteveDeFacto** [QupZilla/qupzilla#2355]
The source code shows that the GreaseMonkey plugin is using HTML5 local storage to implement the storage methods. This completely voids the purpose of storage in userscripts. The point of functions like GM_getValue and GM_setValue is to store data for each script and not for each domain.

The way it is implemented now causes userscripts that use the same keys to store a variable as another script to crash and also causes many scripts to be useless since they are unable to store data cross domain.

**Comment by nowrep** [comment]
JavaScript can't perform sync calls to C++ side, so that's why this implementation was used.
I plan to implement it properly sometime.

**Comment by SteveDeFacto** [comment]
@nowrep I need this so bad that I will pay you $20 USD worth of your preferred cryptocurrency to reopen this ticket and fix this issue in the next month or so. Does this interest you?

**Comment by nowrep** [comment]
But I did implement it, did you read the commit?

It works correctly if the userscript uses GreaseMonkey 4.0 API. Currently, QupZilla's GM plugin exposes both old and new GM API, but it reports `4.0` version in `GM.info.version`, so userscripts should prefer the new API. If not, you should update userscript or report it to the devs.

I can make the implementation correct also for legacy API, but as I see it now it is just extra work with not much benefits. So if you really want this, you'd need to donate at least 0.1 ETH for me to work on it.

**Comment by SteveDeFacto** [comment]
@nowrep Nice! I didn't see your comment from 6 months ago until you closed the ticket. Updating greasemonkey is fine. Thank you!
