### ISSUE TITLE
Download manager: unable to open file/open folder

### ISSUE THREAD

**Issue by pmargeti34** [QupZilla/qupzilla#2360]
Steps to reproduce:
1. download any file
2. open download manager
3. right click on downloaded file in download manager
4. select open file OR select open folder
5. observe that nothing happens

Running qupzilla from terminal these are the messages generated for Open file and Open folder respectively:
```
Unable to detect a launcher for 'file:///home/anon/Pictures'
Unable to detect a launcher for 'file:///home/anon/Pictures/test.png'
```
Issue started with qt5.9 update.

OS: Archlinux
qupzilla 2.1.2-3
qt5-webkit 5.9.0-1

**Comment by cranes-bill** [comment]
Can't reproduce, works to me as expected.

c9a52e59c3
Qt 5.9

**Comment by pmargeti34** [comment]
Just tried it with qupzilla-git from AUR, still getting the same after saving your avatar picture:
`Unable to detect a launcher for 'file:///home/anon/Pictures/5161278'
Unable to detect a launcher for 'file:///home/anon/Pictures`
Just to make sure we're not misunderstanding each other, the issue here  isn't saving the file. Download works fine, the file I want downloaded is correctly downloaded where I want it to be downloaded. I am however unable to open this file using Download manager.

**Comment by cranes-bill** [comment]
[Sample video](https://www.sendspace.com/file/xi7gq5)

**Comment by pmargeti34** [comment]
Solved by reinstalling xdg-utils package. @cranes-bill thanks for your trouble, you've pointed me in the right direction. Closing.
