### ISSUE TITLE
Can't watch videos on Facebook

### ISSUE THREAD

**Issue by Lombress** [QupZilla/qupzilla#2361]
I know there is currently a "fake" Useragent on Facebook, but it seems it's not enough. I can't watch videos: it says something has "gone wrong" and I have to upgrade Chrome. Gifs are not shown as well, but there is a link to open them in another tab. If I fake the useragent as Firefox 52, it redirects me to the Facebook help page. Furthermore, I don't have useragent for single websites in my preferences, only global useragent settings (I am using version 2.0.1 that's default for Opensuse 42.2, I'm not sure if this issue has been solved on the new version of Qupzilla, but I can't check, there's not any new version for my system)

**Comment by iondissonance** [comment]
Upgrade to Tumbleweed, add my repos and test facebook again:

http://download.opensuse.org/repositories/home:/mephisto:/branches:/KDE:/Qt5/openSUSE_Tumbleweed/ - patched qtwebengine with enabled prop. codecs option

http://download.opensuse.org/repositories/home:/mephisto/openSUSE_Tumbleweed/ - fresh qupzilla from git with debug packages

**Comment by Lombress** [comment]
I don't want to upgrade to Tumbleweed, I'm afraid there would be other issues and I need my computer (which is old and has a bad CPU) for things more important than Facebook.

So, can I use those repos and install only some packages, those I would need, in Opensuse 42.2, without any other issues? Otherwise I'll wait till everything is added to a stable release of Opensuse (it's not even in 42.3, as far as I know)

**Comment by iondissonance** [comment]
This packages just for Tumbleweed.

**Comment by Lombress** [comment]
Ok no, I'll use my phone or Firefox if I really need to watch a video on Facebook, that's the only thing that doesn't work. If it's in Tumbleweed it means something similar will be added to stable releases one day, I hope, but now I can make it with 2.0.1

**Comment by iondissonance** [comment]
Flash plugin installed?

**Comment by Lombress** [comment]
No, as far as I can see. I have it enabled in the "browsing" tab of the preferences but there's no flash plugin in the extensions tab. How can I install it? It doesn't seem to be in the Opensuse repos, unless it's here: [http://software.opensuse.org/package/libqt4-webkit-qupzillaplugins](url)

**Comment by iondissonance** [comment]
```
1. sudo zypper ar -f -n packman http://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_42.2/ packman

2. sudo zypper dup

3. sudo zypper in flash-player flash-player-ppapi
```

**Comment by iondissonance** [comment]
And check flash here http://get.adobe.com/flashplayer/about/

**Comment by Lombress** [comment]
you meant zypper refresh or zypper update and not zypper dup, right?

Anyway, I alread had a packman repository with the same packages as the one you gave me. I installed flash-player-npapi, checked Adobe and Adobe said it is installed, but still can't see any flash plugin in the extension tab and can't see videos on Facebook

**Comment by iondissonance** [comment]
You need flash-plugin-**ppapi** and patched QtWebEngine. Wait a bit, I'm preparing patched QtWebEngine for you.

**Comment by Lombress** [comment]
yes, I did install ppapi, now I corrected. No idea how to make patched Qtwebengine, if you're making it for me thank you very much

**Comment by iondissonance** [comment]
```
1. sudo zypper ar -f -c  http://download.opensuse.org/repositories/home:/mephisto:/branches:/openSUSE:/Leap:/42.2:/Update/openSUSE_Leap_42.2/ patched_qtwebengine

2. sudo zypper **dup** --from patched_qtwebengine

3. Restart QupZilla
```

**Comment by Lombress** [comment]
Still doesn't work...

**Comment by iondissonance** [comment]
https://www.quirksmode.org/html5/tests/video.html

H264 works?

**Comment by Lombress** [comment]
No, neither with your patch nor with the version given by Opensuse (5.6.1-4.2)

**Comment by iondissonance** [comment]
Upgrade package, all works now in virtualbox with leap 42.2

**Comment by iondissonance** [comment]
![image](https://user-images.githubusercontent.com/18717061/27217028-dc6af872-5280-11e7-9ac8-6d05d126c878.png)

**Comment by Lombress** [comment]
done, now it works with your version of Qtwebengine, both on Facebook and on the test website. Thanks

**Comment by cranes-bill** [comment]
Looks like now only _close issue button_ does not works for you ... :smiley:
