### ISSUE TITLE
some inconsistency with cyrillic letters in the adress and search bars

### ISSUE THREAD

**Issue by i4778370** [QupZilla/qupzilla#2364]
second symbol in adress bar always gets typed in english even when russian input is active (using fcitx, fcitx-russian in my case). attached is the showcasing screenshot.
![screenshot_20170618_151025](https://user-images.githubusercontent.com/25922296/27258217-4a57011a-5438-11e7-831b-057d8ed5e809.png)
Note it only happens in the adress and search bars. 
Since it doesn't seem to happen in other apps like Konsole or Kate reported it here.
My setup:
- 4.8.6-1-CHAKRA #1 SMP PREEMPT Sun Nov 6 14:17:46 GMT 2016 x86_64 GNU/Linux, up to date;
-  QupZilla 2.1.2;
- fcitx version: 4.2.9.1
Will be glad to provide further info.
Thanks!

**Comment by cranes-bill** [comment]
I think that's similar to #2247

**Comment by i4778370** [comment]
@cranes-bill 
Hey! Thanks a lot for the quickest reply! I gotta tell, that I don't get that problem after seting up your variables, disabling fcitx and removing it from autostart altogether and switching the keyboard layout with something like 
`setxkbmap -layout ru,us -option grp:alt_shift_toggle`

**Comment by i4778370** [comment]
so i guess it could be closed as not a bug? and it's more like a distro-specific, let's say, "configuration" or "misconfiguration" (maybe related to input method framework)? 
Either way thanks again for your time and efforts guys and good luck with the further development!
