### ISSUE TITLE
Right click context menu lacks necessary items when JS is disabled

### ISSUE THREAD

**Issue by voxxpop** [QupZilla/qupzilla#2366]
When JavaScript is disabled (getting more and more necessary these days) the right click context menu is missing items. Amongst others the following aren't listed when right clicking on links:

Open link in {new tab|new window|private window}
Bookmark link
Save link as ...
Send link ...
Copy link address

This using the Debian produced package; Qupzilla version: 2.0.2; QtWebEngine version: 5.7.1

Cheers

**Comment by iondissonance** [comment]
Can't reproduce - /QupZilla 2.1.99, Qt 5.9, openSUSE Tumbleweed/
Reproduce - /QupZilla 2.0.2, Qt 5.6.1, openSUSE Leap 42.2/

**Comment by nowrep** [comment]
That's expected, querying context menu data without JavaScript only works with QtWebEngine >= 5.7.
That being said, with JavaScript disabled more browser features will not work as those rely on JavaScript now.
