### ISSUE TITLE
Incorrect print preview

### ISSUE THREAD

**Issue by fturco** [QupZilla/qupzilla#2367]
I'm using Qupzilla-2.1.99 (d6b142bba2) on a Gentoo Linux system.

Consider the following Wikipedia article for example: https://en.wikipedia.org/wiki/Smartwatch
If you go to File > Print and select Portrait you have a 3-pages preview with very small text size, totally unreadable. Selecting the printable version article (https://en.wikipedia.org/w/index.php?title=Smartwatch&printable=yes) doesn't help at all.

I think the problem is caused by the "Software" table which is too large in the horizontal direction. Otter browser produces a 7-pages preview instead, but it truncates the table at the right margin.

I'm not trying to actually print the article on paper. I just need to estimate how much time I need to read it, assuming each page takes the same amount of time. So I don't really mind if very large tables are truncated horizontally.

Is there some way to accomplish this? Is this actually a bug at all?

**Comment by nowrep** [comment]
Looks like bug in QtWebEngine printing.

**Comment by nowrep** [comment]
There is no longer a print preview (as it is buggy), so this is actually "fixed".
