### ISSUE TITLE
keyboard shortcuts not working

### ISSUE THREAD

**Issue by JR1994** [QupZilla/qupzilla#2370]
I running Qupzilla under Arch Linux. When I try tab switching using either the ALT+NUM or single key option I am unable to switch tabs.

**Comment by cranes-bill** [comment]
The same as [previous](https://github.com/QupZilla/qupzilla/issues/2369) issue (i think).

**Comment by JR1994** [comment]
My issue is not with a plugin, but a built in feature. For example I can open and close tabs with keyboard shortcut CTL+t and CTL+w, but switching tab feature is not working.

**Comment by nowrep** [comment]
That issue applies also to some built-in shortcuts, it was incorrectly opened in plugins repository.

**Comment by JR1994** [comment]
Ok It look like ALT+letter works to move between tabs. However the setting
for ALT+NUM and just NUM are not working

**Comment by nowrep** [comment]
#2369
