### ISSUE TITLE
Ctrl + F for Edit -> Find , Ctrl +U for Page Source: doesn't work anymore

### ISSUE THREAD

**Issue by DanielPrjct** [QupZilla/qupzilla#2375]
The shortcuts Ctrl + F for Edit -> Find, and Ctrl + U for Source Code, doesn't work anymore on my machines.

Ctrl + other strokes (C, X, V, Z, A, D, etc.) work fine in Qupzilla.

Ctrl + F (for Find) works flawlessly in all my other GUI apps (Qt4|5 or GTK2|3 based) which have this shortcut available.
I don't know if Qupzilla, running on another Linux distro or on Windows, is suffering the same bugs.

Qupzilla data:
Application version 2.1.2
QtWebEngine version 5.9.1

OS data:
Arch Linux, kernel 4.11.7-1-ARCH x86_64, LXQt DE.

Best regards,
Daniel

**Comment by Chiitoo** [comment]
For the 'ctrl_f', see #2351 for example.

As for 'ctrl_u', I never used that before, but indeed, it doesn't seem to be what the context-menu advertises.  (Curiously, it seems to remove all text in the address bar, and/or the web search bar.)

**Comment by nowrep** [comment]
#2369
