### ISSUE TITLE
[Feature Request] Only load last active tab or disable loading of  websites during restore session

### ISSUE THREAD

**Issue by potholiday** [QupZilla/qupzilla#2378]
I open multiple tabs for browsing internet and most of the time closes the browser with these tabs on. I have enabled **restore session** from `General>launching>After Launch` in qupzilla. The current problem with  **restore session**  is when we launch qupzilla, it loads all the website together. This is bad for two reasons 

1) after launching a new session some times only a few previous tabs are necessary  and qupzilla loads unnecessary websites
2) When qupzilla crashes it ask for **restore session** or a **new session** , if we restore then it will also load the website which caused the crash ledding to another crash.

I want **restore session** but I dont want it to automatically load all website when I start a new session but instead it should only load the last active tab. Example if I close qupzilla with open tabs for google, fb, github, cnn news, google play with _google_ tab being the _active_ tab. Then when I launch a new qupzilla session only load google tab and ask for a _inpage_ permission button for loading fb, github, cnn news, goog play separately.

**Comment by nowrep** [comment]
There is option "Don't load tabs until selected" that does just this.

**Comment by potholiday** [comment]
Can you please tell where is the location of that option. I am using 2.1.2 App image version

**Comment by nowrep** [comment]
Preferences -> General -> Launching
