### ISSUE TITLE
my site not rendering correctly

### ISSUE THREAD

**Issue by Gibbz** [QupZilla/qupzilla#2379]
I have been working on a website, but noticed on qupzilla it renders parts wrong.

http://bit-shift.io

- The link colors are wrong.
- There is weird outline around the logo that should not be there. 
- The html5 videos dont play.

Any ideas on how to fix these issues to be compatible with qupzilla?

**Comment by Gibbz** [comment]
ah same happens on chrome, looks like its just a css issue.

Not sure why the videos dont play, but changing them to webm works...

**Comment by nowrep** [comment]
QtWebEngine doesn't support proprietary codecs by default, that's why videos didn't play.
