### ISSUE TITLE
Hotkey Ctrl+C notifies that it is ambiguous hotkey

### ISSUE THREAD

**Issue by NickLion** [QupZilla/qupzilla#2381]
openSUSE Tumbleweed x86_64, KDE Plasma 5, Qt 5.9.1.
QupZilla 2.1.2 and from git.

How to reproduce:
1. Start QupZilla.
2. Open any page (e.g. https://duckduckgo.com/?q=user+agent&t=qupzilla&ia=answer ).
3. Select some text (not in input[type=text] or textarea) and press Ctrl+C.

Actual result:
Dialog with text:
The key sequence 'Ctrl+C' is ambiguous. Use 'Configure Shortcuts'
from the 'Settings' menu to solve the ambiguity.
No action will be triggered.

And nothing copied.

Expecting results:
No such dialog and selected text copied.

**Comment by nowrep** [comment]
Bug in KDE global menu: https://bugs.kde.org/show_bug.cgi?id=375053

**Comment by NickLion** [comment]
Thanks! Just started `KDE_NO_GLOBAL_MENU=1 qupzilla` and Ctrl+C works great!
