### ISSUE TITLE
Hotkey Ctrl+Tab doesn't work if page is focused

### ISSUE THREAD

**Issue by NickLion** [QupZilla/qupzilla#2382]
openSUSE Tumbleweed x86_64, KDE Plasma 5, Qt 5.9.1.
QupZilla 2.1.2 and from git.

How to reproduce:
1. Open at least 2 pages.
2. Be sure page itself is focused.
3. Press Ctrl+Tab.

Actual results:
Nothing happened.

Expected result:
Next tab activation.

NB1: If focus is in URL, Search or search in page text field, Ctrl+Tab works fine.
NB2: Ctrl+Shift+Tab works fine every time.
NB3: Disabling global menu for QupZilla doesn't change anything (unlike Ctrl+C, thanks for the tip!)

**Comment by nowrep** [comment]
Looks like #2369

**Comment by NickLion** [comment]
Maybe. But for some reason Ctrl+Shift+Tab works fine. Strange.

**Comment by nowrep** [comment]
Given the fact that it only occurs when webview is focused, I'm closing it as duplicate. I'll test it again once Qt 5.9.2 is released.
