### ISSUE TITLE
Irratic behaviour with ctrl+alphabets in qupzilla and also feature request

### ISSUE THREAD

**Issue by potholiday** [QupZilla/qupzilla#2383]
I know some body already reported ctrl+F issue but I want to add the irratic behaviour of ctrl+alphabets in qupzilla(ubuntu 14.04). For me some times ctrl+F/A/C/X/Z works and other times they dont work

**Feature Request**
When we select the **text** (wwwDOTgoogleDOTcom ,here DOT is .) of a website and not the hyperlink ([https://google.com](https://google.com)) and use the second mouse key to select options give an other option to  
 **open with new tab**  along with **go to web address** opening

**Comment by nowrep** [comment]
You can press middle mouse button on the "go to web address" action to open it in new tab.
As for the shortcuts, it works if the webpage doesn't steal it (eg. if the webpage doesn't itself specify those shortcuts).

**Comment by potholiday** [comment]
> You can press middle mouse button on the "go to web address"

Dont have a middle mouse button?

**Comment by nowrep** [comment]
In that case Ctrl+ Left button

**Comment by potholiday** [comment]
That worked but a dedicated menu would have been better, faster and efficent. This is just a suggestion.
