### ISSUE TITLE
Shortcut Ctrl+F doesn't work at opening

### ISSUE THREAD

**Issue by Jerome971** [QupZilla/qupzilla#2387]
Hi,

I am under Chakra Linux and the Ctrl+F doesn't work the first time. I have to use the menu to have the search bar. After that i can use the shortcut. But if I close QupZilla and open it again, the shortcut doesn't work. I have to use the menu.
Can u fix that issue ?

Jerome.

**Comment by cranes-bill** [comment]
#2351
#2356
#2358
#2369
#2375
