### ISSUE TITLE
Youtube Live is not working

### ISSUE THREAD

**Issue by potholiday** [QupZilla/qupzilla#2390]
When I tried to watch this live video https://www.youtube.com/watch?v=mEzwHiugitE its giving me this errror
>Your browser currently does not recognise any of the video formats available. 

It seems qupzilla dosent support `H.264` and `MSE & H.264` codecs.

**Comment by cranes-bill** [comment]
#1973
#2009
#2204
#2350

**Comment by potholiday** [comment]
I am using latest version of qupzilla appimage

**Comment by cranes-bill** [comment]
> I am using latest version of qupzilla appimage



Looks like you have not read any of the issues above, where the general conclusion is:

_Due to licence restrictions, QtWebEngine cannot be redistributed with proprietary codecs enabled. If you want to use those codecs, you must compile QtWebEngine yourself!_

**Comment by potholiday** [comment]
sorry I read first two links but didnt understand it properly. Now I got it
