### ISSUE TITLE
HIGH CPU usage with Greasemonkey enabled

### ISSUE THREAD

**Issue by Vistaus** [QupZilla/qupzilla#2394]
QupZilla from latest git master, or more specifically the QtWebEngine process started by QupZilla, uses a huge amount of CPU power when loading any page. And I'm talking about one tab only, I can't even load a second tab. Now before you'll say this is a QtWebEngine bug: Otter Browser with the same QtWebEngine process hardly uses any CPU.

OS: Solus
DE: Budgie (latest)
Qt: 5.9.1
QupZilla: latest git master

How to solve this?

**Comment by Vistaus** [comment]
Hmm, I need to test some more after doing a few reboots but it seems like a bug in the Greasemonkey plugin 'cause now that I've disabled Greasemonkey, everything *seems* to work fine.

**Comment by Vistaus** [comment]
Yup, I can confirm now that Greasemonkey is the culprit. Will change the title.

**Comment by nowrep** [comment]
Any userscript in particular? It's probably issue of one specific userscript rather than the extension itself.

**Comment by Vistaus** [comment]
@nowrep I wasn't running any userscript.

**Comment by nowrep** [comment]
GreaseMonkey does nothing if you don't have any userscript installed.

**Comment by Vistaus** [comment]
That's what I thought but I can still reproduce it.

**Comment by nowrep** [comment]
Alright, depending on your "HIGH CPU usage" definition you may be able to get useful backtrace with `gdb`

**Comment by Vistaus** [comment]
Depends. Of the 5 times I tried to get to the bottom of this today, 4 times I had to kill X (Ctrl+Alt+Backspace). So I'm not sure if I could get anything out of gdb then 'cause if I have to kill X again, there's no backtrace.
