### ISSUE TITLE
Recommendation: Fix Password Import

### ISSUE THREAD

**Issue by jerfly22** [QupZilla/qupzilla#2395]
You may not care about qupzilla adoption rates, so do with this what you will, but you should fix the password import to parse XML files.  If people can bring over their login info from firefox and chrome you may end up seeing more people use the browser.

**Comment by nowrep** [comment]
There is nothing to fix, it is intended to work only with QupZilla exported passwords and it works correctly.

Adding support for importing passwords from other browsers is a different thing.

**Comment by Vistaus** [comment]
Also, most people are using an external password manager like Lastpass, Enpass or Keepass anyway.
