### ISSUE TITLE
[Password Manager] Switch back to plaintext no ask for master password

### ISSUE THREAD

**Issue by sabayonino** [QupZilla/qupzilla#2396]
Hi 

Qupzilla 2.1.2,running on SabayonLinux 
`Application version 2.1.2 , QtWebEngine version 5.7.1`

and

Qupzilla 2.0.2,running on Gentoo Linux 
`Application version 2.0.2 , QtWebEngine version 5.6.2`

Master Password is setup.

1- Database Encrypted
When I switch back to the plaintext database  in Password Manager , no master passowrd is required
This is a security issue. Everybody can switch to the plaintext and all passwords will be showed .

2 - Database Encrypted
if I choose "Show/Hide Passwords" , nothing happens. and/or no master password is required.

**Comment by cranes-bill** [comment]
I can't confirm that. It ask me for the password even immediately when i click on **Password Manager** menu. Perhaps you are doing that in the same active session?

**Comment by nowrep** [comment]
Each backend has its own storage backend, so they do **not** share passwords.

**Comment by sabayonino** [comment]
@cranes-bill 
Yes, It's the same session. If I leave the session opened everybody can switch backends or see my encrypted passwords

I suggest to ask the master password for the same session when I switch from encrypted to plaintext and when I choose to show the passwords (for the encrypted backends)

It works for the same session.from plaintext to encrypted backends but not viceversa 

Another thing I discovered , for the encrypted backends. No password is required when I export password.xml.

Leaving the session opened , a malicious can exported the database and get all passwords from the .xml file.

For me all thiese actions are security issues for the Qupzilla password manager.
In firefox (and master password is setup) when I choose to show the passwords stored , everytime the master psw is required. 

Cheers :)
