### ISSUE TITLE
qupzilla -t from command line opens two tabs 

### ISSUE THREAD

**Issue by marhkb** [QupZilla/qupzilla#2397]
When execting "qupzilla -t" from command line and no qupzilla instance is running, it opens a window with 2 tabs instead of just 1 tab.

**Comment by sabayonino** [comment]
simply run 
`$ qupzilla`

to get one tab :D

`$ qupzilla -h
 -t, --new-tab                Opens new tab.`

Exec once and get new tab and so on...

**Comment by marhkb** [comment]
and that is the problem. I have a global shortcut for opening qupzilla that utilizes the -t option. So when qupzilla is not running that shortcut should open qupzilla with just one tab (I don't save session) and when its running it shall add a tab (what is working correctly). 
I had the same shortcut when I was using firefox and in my opinion firefox behaved correctly by initially NOT openening 2 tabs.
Sure I could script that, but that cannot be expected from the average user. Qupzilla behaves just wrong here.

**Comment by Vistaus** [comment]
QupZilla behaves right. When you open QupZilla, it adds a tab. So when you request a new tab, even if it's not open, it'll add a tab to the existing tab. It'd only be wrong if QupZilla supported tabless windows but it doesn't so the behavior is as expected.

**Comment by marhkb** [comment]
firefox --new-tab google.com opens a new window with just one tab "google.com". So you are saying firefox behaves wrong?

**Comment by Vistaus** [comment]
No. Firefox supports tabless windows, so when you request a new tab, it opens one tab. Now if Firefox didn't support tabless windows (like QupZilla), then it would open two tabs as well.

**Comment by marhkb** [comment]
I don't see this as a point. Regardless whether a browser supports tabless windows or not, from a user's point of view this behavior is weird. It makes no sense to initially open 2 tabs. How do you think it would be technically possible to implement other browsers' behavior?

**Comment by Vistaus** [comment]
"How do you think it would be technically possible to implement other browsers' behavior?"

Easy: you should open up an issue requesting support for tabless windows in QupZilla.

(I'm a user and I think this behavior is normal, btw.)

**Comment by marhkb** [comment]
Ok. 2 persons, 2 opinions. Yeah, maybe support for tabless windows would automatically introduce this behavior. I would love to see a developer stepping in and telling his opinion about what is easier: 
1. Implement tabless windows or
2. Check if no other instance is running and set the initial tab to the URL without opening a second tab

**Comment by Vistaus** [comment]
I don't think it's about being easier, it's about implementation, really. Many modern browsers behave like this (also see my edit in the previous comment).

**Comment by marhkb** [comment]
I can understand your point from a technical point of view.
But as I sad, some users like me have shortcuts (for example open google). So when these shortcuts trigger "qupzilla -t google.com" it just looks unpolished when a browser opens with two tabs. And as I already said before, I can workaround this behavior by starting a shell script that does take care of it, but some others can't.
So in the end let's wait for developer's response about his thoughts. If his opinion is that this behavior is normal then I also would be fine with that.

**Comment by nowrep** [comment]
As already said, this is expected. It **adds** a new tab, so if the app is running this sends message to open new tab and if it is not running then it adds additional tab, and as the standard action is to add 1 tab at start this results in 2 tabs.
