### ISSUE TITLE
Minor glitch when loading specific page/site

### ISSUE THREAD

**Issue by TrentMu** [QupZilla/qupzilla#2402]
If I load this page... 
http://datazone.birdlife.org/species/factsheet/olive-thrush-turdus-olivaceus
it consistently causes
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	QtWebEngineProcess.exe

**Comment by Martii** [comment]
No crash with http://datazone.birdlife.org/species/factsheet/olive-thrush-turdus-olivaceus in 3c60b8417a7e2ab2c831a907aaf54dcd94ab459f with Qt 5.9.1

**Comment by Vistaus** [comment]
No crash here either with Qt 5.9.1 and QupZilla 2.1.99 (latest git master).

**Comment by TrentMu** [comment]
No problem - I am on version 2.1.2, Qt version 5.8.0
I will update. Thanks for the input and the software
