### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by skimj** [QupZilla/qupzilla#2403]
Qupzilla crashes immediately during startup.
HW: ARMv8 Cortex-A53 (Raspberry Pi 3)
OS: ArchLinuxARM Raspberry Pi 2 (ARMv7)

I don't have an ARM build environment so debugging may be hard. Here is the crash log:
```
Qt version: 5.9.1 (compiled with 5.8.0)
QupZilla version: 2.1.2
Rendering engine: QtWebEngine

============== BACKTRACE ==============
#0: qupzilla(_Z23qupzilla_signal_handleri+0x1b4) [0x12ea4]
#1: /usr/lib/libc.so.6(__default_sa_restorer+0) [0x72274aa0]
```

`/usr/lib/libc.so.6 is owned by glibc 2.25-4`

Prior to this point, I was getting this error: `libEGL warning: DRI2: failed to authenticate` which was caused by multiple libEGL.so and libGLESv2.so in different locations. I resolved it by linking to those provided by the RPi libs per this FAQ: [https://pi3d.github.io/html/FAQ.html#glx-dri2-not-supported-or-failed-to-authenticate](url). libc.so doesn't seem to be in the same category but I'm suspect of my libraries.

**Comment by cranes-bill** [comment]
If you are sure the problem is caused by _GL Library_, as workaround you could  try to run QupZilla as follow: 
`qupzilla --disable-gpu`

**Comment by skimj** [comment]
`qupzilla --disable-gpu`
This generates the same crash log.

**Comment by nowrep** [comment]
This is useless report, please try to at least get backtrace from `gdb`. even without symbols is better than this.

**Comment by skimj** [comment]
Well I'm totally flailing here. I did a system upgrade and now I can't reproduce the original crash. Now I'm getting "/usr/bin/qupzilla: relocation error: /usr/lib/libQupZilla.so.2: symbol free, version Qt_5 not defined in file libQt5WebEngineCore.so.5 with link time reference" which seems to be a packaging/lib problem. I'll close this as I'm unable to generate useful feedback.
