### ISSUE TITLE
Open discussion on replacing Konqueror by Qupzilla. Why I think it may be a wrong move.

### ISSUE THREAD

**Issue by kupiqu** [QupZilla/qupzilla#2408]
Just wanted to let you know about this KDE bug I filled for opening discussion about this matter:

https://bugs.kde.org/show_bug.cgi?id=383430

**Comment by kupiqu** [comment]
I'm closing the issue, as I think it's more proper to keep discussion within KDE...

**Comment by nowrep** [comment]
QupZilla will not be renamed to Konqueror, nor merge with it. 
I'm not sure where you got that idea, it's not in the blog post which is currently the only official info about the situation.

**Comment by kupiqu** [comment]
I'm glad to hear that! There was some discussion about this in reddit, including KDE devs, that brought to me to that point...

https://www.reddit.com/r/kde/comments/6svk7w/qupzilla_is_moving_under_kde_and_looking_for_new/

**Comment by nowrep** [comment]
I decided not to take Konqueror name.
Also, reddit comments are nothing to be taken seriously :D

**Comment by smarquespt** [comment]
@nowrep 
What will happen with translations? Will they still be managed in transifex or moved to kde translators?

**Comment by nowrep** [comment]
@smarquespt Moved to KDE infra.

**Comment by smarquespt** [comment]
@nowrep 
Ok, thanks.
