### ISSUE TITLE
can not using ime fcitx with qupzilla 

### ISSUE THREAD

**Issue by netroby** [QupZilla/qupzilla#2409]
I tried other KDE application(I am using KDE plasma workstation) 
They all fine.

Only qupzilla can not type words(chinese) i am using archlinux x64 + kde plasma 5.10 + fcitx-pinyin

**Comment by cranes-bill** [comment]
https://wiki.archlinux.org/index.php/Fcitx

**Comment by Arnie97** [comment]
Confirmed on Debian 9 x64.
Any ideas?

**Comment by cranes-bill** [comment]
> Any ideas?

See #2364

**Comment by netroby** [comment]
Using chrome resolve the problem.
