### ISSUE TITLE
Tab switching shortcuts do not work most of the time

### ISSUE THREAD

**Issue by Zekario** [QupZilla/qupzilla#2410]
I cannot switch tabs via alt+digit. I have done it a few times, but almost every time nothing happens. I thought it may be Greasemonkey, but it persisted even after I disabled it and restarted. Is this a problem with Qupzilla itself, or could it be on my end?

**Comment by nowrep** [comment]
If you use Qt 5.9 then it will be fixed with Qt 5.9.2
