### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by arunsai123** [QupZilla/qupzilla#2412]
`Time: Mon Aug 14 21:02:34 2017
Qt version: 5.9.1 (compiled with 5.8.0)
QupZilla version: 2.1.2
Rendering engine: QtWebEngine

============== BACKTRACE ==============
#0: qupzilla() [0x403352]
#1: /usr/lib/libc.so.6(+0x33940) [0x7f1a55dd7940]
#2: /usr/lib/libQt5Widgets.so.5(_ZN7QWidget4hideEv+0) [0x7f1a56f54c60]
#3: /usr/lib/libQupZilla.so.2(_ZN9TabWidget12restoreStateERK7QVectorIN6WebTab8SavedTabEEi+0x2c6) [0x7f1a5dd02916]
#4: /usr/lib/libQupZilla.so.2(_ZN15MainApplication14restoreSessionEP13BrowserWindow7QVectorIN14RestoreManager10WindowDataEE+0x522) [0x7f1a5dbe9372]
#5: /usr/lib/libQupZilla.so.2(_ZN13BrowserWindow10postLaunchEv+0x7f0) [0x7f1a5dbdaea0]
#6: /usr/lib/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0xe2) [0x7f1a569a91d2]
#7: /usr/lib/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x92c) [0x7f1a56f6c49c]
#8: /usr/lib/libQt5Widgets.so.5(_ZN11QMainWindow5eventEP6QEvent+0x164) [0x7f1a5705e5e4]
#9: /usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c) [0x7f1a56f29e4c]
#10: /usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2a6) [0x7f1a56f31926]
#11: /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x120) [0x7f1a56978bd0]
#12: /usr/lib/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x1f6) [0x7f1a5697b426]
#13: /usr/lib/libQt5Core.so.5(+0x2eaa74) [0x7f1a569d3a74]
#14: /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x2e7) [0x7f1a524aea57]
#15: /usr/lib/libglib-2.0.so.0(+0x4ac88) [0x7f1a524aec88]
#16: /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7f1a524aed1c]
#17: /usr/lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x61) [0x7f1a569d3061]
#18: /usr/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x13b) [0x7f1a56976ffb]
#19: /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x98) [0x7f1a56980048]
#20: qupzilla() [0x402a2b]
#21: /usr/lib/libc.so.6(__libc_start_main+0xea) [0x7f1a55dc44ca]
#22: qupzilla() [0x402d4a]
`

> OS: Arch Linux
> DE: Deepin
> Version: 2.1.2-3

**Comment by nowrep** [comment]
Already fixed in 0148b7aaffb83c4706af446b2f3e9ccf546aeb40
