### ISSUE TITLE
Default zoom page not applied

### ISSUE THREAD

**Issue by AlmAck** [QupZilla/qupzilla#2416]
I set the default page zoom to 200% but when I open a new page the zoom is always 100%.

How to replicate:
1) set an high default zoom level, like 200% for instance
2) open a new page and the level is 100%
with Ctrl+0 the zoom level remains 100%, but if I press Ctrl++ the level goes over 200%, then with Ctrl+0 the zoom is set correctly to 200%

**Comment by cranes-bill** [comment]
#2168

**Comment by AlmAck** [comment]
I'm using qupzilla 2.1.2 on qt5.9.1 with qtwebengine.

The problem is not related to this line? the zoom level for a new page is set to 100?
[ webview.cpp#L70](https://github.com/QupZilla/qupzilla/blob/master/src/lib/webengine/webview.cpp#L70)
instead of
 `zoomLevel(qzSettings->defaultZoomLevel)`

**Comment by nowrep** [comment]
Let me quote what I wrote in the issue linked by @cranes-bill:

> Already fixed in master, will be in next version.

**Comment by AlmAck** [comment]
true, but the issue was closed "on 20 Jan" and since then the new release come out. Version 2.1.2 is from March and I expect that the fix is included, or I'm wrong?

**Comment by swamp-fish** [comment]
I was also searching for the info and found that fix was committed on May 29:
https://github.com/QupZilla/qupzilla/commit/16f9b2fde996376f45df4effdc67961dc87bd410
And 2.1.2 version came out in March 15.

> QupZilla 2.3 will be released when Qt 5.9.2 is released (currently listed as August 2017).

Qt will be most likely released by the end of this month as they usually do (https://wiki.qt.io/Qt_5.9_Release). So hopefully a week or two till we see the fix.
