### ISSUE TITLE
Problem: Windows 10 and QupZilla as a default browser

### ISSUE THREAD

**Issue by virious** [QupZilla/qupzilla#2417]
I'm trying to set Qupzilla as my default browser. In System settings it says that it's done.
![image](https://user-images.githubusercontent.com/1451898/29366156-8b92fbea-8299-11e7-9640-dcada517a964.png)

But when I launch QupZilla I get message with information that it is not my default browser and if I would like it to be set as a default one.

Second issue that I have is when clicking on links in other applications I get this error instead browser opening requested site.

![image](https://user-images.githubusercontent.com/1451898/29366265-d73ffdcc-8299-11e7-8053-a1097615072f.png)

Version I'm using is:
**Application version 2.1.2
QtWebEngine version 5.8.0**

What am I missing?

**Comment by srazi** [comment]
Windows 10 does not set QupZilla (or any other browser) as default FTP browser. But our code checks if QupZilla is also default FTP browser or not.

Right now there are two workarounds for this issue:
1- Go to preferences of QupZilla and uncheck : `check to see if QupZilla is the default browser on startup`, or
2- Go to Windows default app settings and select `set defaults by app` then select `QupZilla` from list and then select `Set this program as default`.

![image](https://user-images.githubusercontent.com/1328454/29515226-d02cecf8-8680-11e7-8d9f-a3e4fb4741c9.png)

**Comment by virious** [comment]
> Windows 10 does not set QupZilla (or any other browser) as default **FTP** browser. But our code checks if QupZilla is also default **FTP** browser or not.

You meant regular internet browser, not FTP client, right?

**Comment by srazi** [comment]
> You meant regular internet browser, not FTP client, right?

I mean, when we set QupZilla as default web browser (where you set it in your first picture) Windows doesn't set it as default handler for FTP protocol.

> Tried both solutions and my problem still occurs 😢 

Humm... workarounds are just related to your first issue.
I am not sure what is the cause of second issue. Maybe, a bad/mixed installation.

**Comment by nowrep** [comment]
Do we really need to register as FTP handler?

**Comment by srazi** [comment]
Yeah, it should not set it as default FTP handler and also no check if it is set or not. But, I think adding to list is good, since Windows shows it to user as an option to choose.

**Comment by nowrep** [comment]
Well, the FTP support is not really good, and if that fixes this issue I say we remove it.

**Comment by srazi** [comment]
OK 🙏 
Also, I think the way that Firefox make itself as default is better. When user clicks on `Make Default`, Firefox just shows the `Default app` settings window, instead of setting it by using API calls that sometimes (always?) needs administrator right. But I don't know what WIN API is called to show the settings window, maybe we have to find it in firefox source codes.

**Comment by nowrep** [comment]
But that only works on Win10?

**Comment by srazi** [comment]
Don't know... will try to find out more about it.
