### ISSUE TITLE
audio playback problem

### ISSUE THREAD

**Issue by tsifra** [QupZilla/qupzilla#2419]
when i try to open https://www.bfm.ru/broadcasting/player
browser freezes. If i use "close" button of the window os closes it, but process still alive. so i have to kill it manually.
OS ubuntu 16.04 32 bit

**Comment by cranes-bill** [comment]
I'm guessing that you are using very old QupZilla version.

**Comment by tsifra** [comment]
You,re right. I've checked version - 1.8.9 (it comes with ubuntu 16.04)
PPA https://launchpad.net/~nowrep/+archive/ubuntu/qupzilla by David Rosca also has only 1.8.9
Current version is 2.1.2 according to https://www.qupzilla.com/ Have to build from source?

**Comment by tsifra** [comment]
Oh there is no way to build from source. New version requires qt 5.8 It's not in repo.
http://download.qt.io/official_releases/online_installers/qt-unified-linux-x86-online.run also doen't give options to install 5.8 Can anybody help with this? 2 more weeks on firefox will drive me crazy

**Comment by cranes-bill** [comment]
I found some [Debian (Sid) packages](http://ftp.fr.debian.org/debian/pool/main/q/qupzilla/), so you might try if they will work on your system.
Also, you might use [Appimage](https://www.qupzilla.com/startdownload?appimage).

**Comment by tsifra** [comment]
Dibian package cant be installed even on ubuntu 17.04 because of old libs. Bad news.
