### ISSUE TITLE
QupZilla 2.1.2 crashes frequently

### ISSUE THREAD

**Issue by fturco** [QupZilla/qupzilla#2421]
I'm running QupZilla 2.1.2 on a Gentoo Linux system. QupZilla crashes very frequently but unfortunately I haven't been able to pinpoint the exact problem. I obtained a backtrace with GDB after having rebuilt some packages with debug symbols. I have not been able to rebuild QtWebEngine because it took forever and my hard disk went under heavy stress during the process (probably not enough RAM).

Package versions:
* `www-client/qupzilla-2.1.2`
* `dev-qt/qtwebengine-5.7.1-r2`

I experienced a similar level of instability when I had installed `www-client/qupzilla-9999` and `dev-qt/qtwebengine-5.9.1`, but it may be due to a different underlying cause.

My system is pretty stable overall. QupZilla seems to be the only main application that gives me headache unfortunately...

Please tell me if you need other info.

[qupzilla-basic.txt](https://github.com/QupZilla/qupzilla/files/1236323/qupzilla-basic.txt)
[qupzilla-full.txt](https://github.com/QupZilla/qupzilla/files/1236324/qupzilla-full.txt)

`qupzilla-basic.txt` was obtained with the `bt` GDB command.
`qupzilla-full.txt` was obtained with the `thread apply all bt full` GDB command.
Both command were issued in the same debugging session.

**Comment by Chiitoo** [comment]
I don't suppose you're doing anything specific with the browser whenever it occurs?

Here it usually only crashes when I close a tab (sometimes), but I haven't really looked into it properly yet.  I'm also using Gentoo, with Qt 5.9.1 (QupZilla tends to be up-to-date with git master).

From a quick peek-see, your backtraces don't look similar to what I have under '$HOME/.config/qupzilla/crashlog', so it could be something completely different indeed.

**Comment by nowrep** [comment]
@fturco Your QtWebEngine is very old

@Chiitoo Can you please post those backtraces?

**Comment by fturco** [comment]
Updated to Qt 5.9.1 and QupZilla from git. This time QupZilla crashed while I was typing "github.com" in the address bar.

[qupzilla-basic.txt](https://github.com/QupZilla/qupzilla/files/1238310/qupzilla-basic.txt)
[qupzilla-full.txt](https://github.com/QupZilla/qupzilla/files/1238311/qupzilla-full.txt)

**Comment by nowrep** [comment]
@fturco This should fix it

**Comment by Chiitoo** [comment]
I'm not entirely sure if the latests ones I have are from what I described, and I've not had it happen again during this time (of course!) while having 'gdb' attached, but I'll hopefully get to making proper notes about it soon, and get you the backtraces in one way or the other.  :]

For now, here's one that looks like it could be it (the latest there is):

[Crash-2017-08-15T17:17:45.txt](https://github.com/QupZilla/qupzilla/files/1238593/Crash-2017-08-15T17.17.45.txt)

**Comment by fturco** [comment]
@nowrep Another crash after having updated qupzilla to latest git version this morning. I don't know if it's due to the same issue.

[qupzilla-basic.txt](https://github.com/QupZilla/qupzilla/files/1243279/qupzilla-basic.txt)
[qupzilla-full.txt](https://github.com/QupZilla/qupzilla/files/1243280/qupzilla-full.txt)

**Comment by fturco** [comment]
No longer crashes here with `=www-client/qupzilla-2.2.3` and `=dev-qt/qtwebengine-5.9.3`. What about you, @Chiitoo?

**Comment by Chiitoo** [comment]
Pretty sure this got fixed a good while ago, yeah.

I'm on Qt 5.10.0 and Falkon git master though, which had some other crashes, but that has been gone now as well after a recent change.  :]
