### ISSUE TITLE
Refuse to start videos besides youtube

### ISSUE THREAD

**Issue by redirkules41** [QupZilla/qupzilla#2422]
i updated to version 2.1.2 and updated qtwebengine to 5.9.1.
so far so good.
but besides youtube i can't open any videos on other websites like vimeo. 
i can see the single frames when i move the mouse pointer over the time line of the video, but qupzilla refuses to start the video. i had this issue on several websites. with the old qupzilla version (1.8.9) from ubuntu repositiries it works. is that related to the new qtwebengine?
thanks in advance.

regards
helge

**Comment by cranes-bill** [comment]
> ...is that related to the new qtwebengine?

Yes, it's related to any QtWebEngine.
You need to build QtWebEngine with proprietary codecs.

**Comment by redirkules41** [comment]
just to get it right.
i installed qt 5.9.1. i thought the webengine is part of that framework. but it seems i have to additionally install qt-weengine with proprietary codecs?

thanks

**Comment by cranes-bill** [comment]
Not to install, to build it yourself.
QtWebEngine can not be redistributed with proprietary codecs due to licenses issue, so the only way to enable those codecs, is to build QtWebEngine yourself.

**Comment by redirkules41** [comment]
sorry, that is what i meant and actually do right now. takes a long time.
hope that it works than. do i have to link it somehow to qt-folder or somewhere else?

**Comment by cranes-bill** [comment]
Yeah, it takes very long time as any other Google shit.
The best way to remove the old version and install the new one.

**Comment by redirkules41** [comment]
the build crashes after 3h due to some undefined declarations. after googling it seems that this issue is known but there was no real solution. i deleted my actual qt and right now i install it from source. i configured the build and than build it with the prefix for proprietary codecs. was this the correct way? or do i have to build webengine in a second step. sorry for all the questions but i really want to continue using qupzilla and not switch again to firefox.

**Comment by cranes-bill** [comment]
If QtWebEngine is included in this build, you no need to build it again. Just do install!
Keep in mind that you may need to buld QupZilla again if the new Qt libraries are different version.

**Comment by cranes-bill** [comment]
Maybe [here](https://github.com/qt/qtwebengine/commit/95ca17c45aea718cade487640edc63e08bc23820), see _**Important Changes**_ section.
And just a suggestion - you might append the following `-j$(getconf _NPROCESSORS_ONLN)` after _**make**_ command next time, to speed up build process!

**Comment by redirkules41** [comment]
finally i made it. your link was gold. from qt 5.9.0 on you must enable the proprietary codecs during configuration with prefix. puh that was tough. 
the official qt documentation is false because in their how-to description they still advise to use config prefix when making.

thanks a lot mate.

regards
helge

**Comment by cranes-bill** [comment]
You are welcome!
Well, so you may close the issue.
