### ISSUE TITLE
Full screen video support disabled in private browsing mode

### ISSUE THREAD

**Issue by mysticfall** [QupZilla/qupzilla#2427]
Even though _Qupzilla_ can play _Youtube_ videos in full screen mode (in _HTML5_ player) without a problem, it doesn't seem to work in private browsing mode.

In private browsing mode, the full screen button on _Youtube_ player shows up as disabled, with a link to instructions about using correct version of _Adobe Flash_ player.

**Comment by benisameme** [comment]
I'm not sure if this is just with me but It dosen't seem to work in regular browsing mode, the sign in page is a bit buggy too

**Comment by cranes-bill** [comment]
> I'm not sure if this is just with me ...

I'm sure that it's just with you, unless you are using old QupZilla version.

**Comment by nowrep** [comment]
https://bugreports.qt.io/browse/QTBUG-65537

**Comment by mysticfall** [comment]
Great to see it fixed. Thanks! 👍
