### ISSUE TITLE
Autohide option for navigation, status and side bars, tabs

### ISSUE THREAD

**Issue by swamp-fish** [QupZilla/qupzilla#2436]
An option to autohide option for navigation, status and side bars, tabs. Show on mouse hover or key pressed, configure time delay for show/hide.

**Comment by nowrep** [comment]
You can get this behavior in fullscreen, outside of fullscreen it makes no sense.

**Comment by swamp-fish** [comment]
I wasn't talking about hiding all of it right away but each thing separately. Fullscreen doesn't give you an option to switch in a differen program as easily as windowed one. This feature can save some space on smaller screens. There're multiple extensions on Firefox that do just that, so people find this kind of features useful.
