### ISSUE TITLE
feature request:  tabs on side

### ISSUE THREAD

**Issue by labatts** [QupZilla/qupzilla#2438]
I would love to have the ability to move the tabs to the left (or right).  It is a huge space saver both vertically and horizantally (can have more tabs without cramming space).

**Comment by swamp-fish** [comment]
Seconded

**Comment by srazi** [comment]
You can use `Tab Manager` plugin as a replacement of tab bar.

![image](https://user-images.githubusercontent.com/1328454/29834103-0bbfd6da-8d03-11e7-9f64-ef8ed13935dc.png)

Also if you set its view type as `window` it will consume no space of main window. And you can open it by shortcut `Ctrl+Shift+M` or by clicking on its icon on statusbar or from `Extension` submenu in `Tools` menu.

**Comment by labatts** [comment]
That is nice that you can do that, but it is a little lacking.

**Comment by nowrep** [comment]
And what exactly is lacking?

**Comment by labatts** [comment]
Don't mean to be argumentative.  Unless I am missing something, using the tab manager makes it into a tree structure.  While this is functional, it is visually appealling (I do understand that this is subjective).  It detracts from a browser that is very nice looking.  

Also, it seems to require two clicks to switch tabs.  That may not seem like much, but it is a bit of a hassle.

**Comment by nowrep** [comment]
>  It detracts from a browser that is very nice looking.

And how would you want it to look instead?

> Also, it seems to require two clicks to switch tabs. That may not seem like much, but it is a bit of a hassle.

Already fixed (will be in next release).

**Comment by labatts** [comment]
![tabs](https://user-images.githubusercontent.com/18312126/29843807-211c5fc6-8cdb-11e7-85a7-02c0f386b75d.png)

Not sure if this is working, maybe no png?

**Comment by labatts** [comment]
basically just normal tabs but on the side.  BTW, great news that you are now part of kde!

**Comment by nowrep** [comment]
Of course, but the main issue here is that QTabBar tabs do not support this mode (above each other), so the result may not look good if we try to draw it like that.
The look of the "tabs" in TabManager can be changed, but if something like your screenshot is done, it means that less tabs will fit there without the need to scroll, which defeats one advantage of this plugin.
Also to be honest, anything shown in the sidebar is distracting to me, be it nicely drawn tabs or current tree widget.

**Comment by labatts** [comment]
I am pretty sure I can get 30 or so tabs this way, but I think you may be right that there are those that want more than this.  And these may be the ppl that use the plugin.  I do not know, though.

**Comment by labatts** [comment]
Although, perhaps you could maintain two?  Not sure if that would really make things more difficult or not.

**Comment by Vistaus** [comment]
I second this. Tab Manager is really lacking and even in QupZilla/Falkon git master, you still have to double-click each tab. But aside from that, it looks horrible and you can't really do actions (for example, dragging tabs doesn't work).

**Comment by j0hny666** [comment]
I also second this. Tab Manager is no really usable in this way, it lacks ability to close the tab with one click, pin it, mute it, close other tabs, close to the left (top) etc. Maybe if these features were added to the extension as optional, it could work. I don't really care about apperance, I even like the tree structure (using TreeStyleTab in Palemoon), but the functionalities are really vital to be able to use this as a replacement for the main tab bar. I'm sorry I can't help with the developement, qt is not really my area, so suggestions are really the only way I can contribute right now :-)
