### ISSUE TITLE
password storage function works wrong way

### ISSUE THREAD

**Issue by tsifra** [QupZilla/qupzilla#2439]
I'm on 2.1.2 Password storage causes some problems. when site has simple auth(web-server level) + webapp level password i can't store them both for future reuse. In fact i can, but i can't use them. Browser will try to insert first password stired to every login-password window. 

So feature request: save password and autofill them for simple auth and web-form auth separately. if site has several passwords stored for one level(for example for web form) form should be empty after load so user can choose login from popup

**Comment by tsifra** [comment]
Also #2069 ticket (from aug 2016) is very important for security reasons

**Comment by tsifra** [comment]
the browser also offers to store credit card info as password. not sure it's good idea

**Comment by nowrep** [comment]
Can you at least write on which page you had this issue, otherwise I can't see what's wrong.

**Comment by tsifra** [comment]
It's not public-available web-site. For single company use only. Self-signed cert (#2069) is also important for this site, because CA doen't gurantee privacy in some cases. Maybe i can explain problem with password storage other way. Web-site has two levels of authenificatin:
1. web-server based login-password ( apache <Location />...AuthType Basic..</Location> ) login and password are entered in browser popup
2. web-app cokie-based auth (login and password are entered on html page)
there is no situation when web-server based auth uses the same password as web-app cookie-based auth. But i still need to store both passwords. Hope this helps. Can provide screenshots, if you need.

**Comment by tsifra** [comment]
One more problem. If i enter wrong password on html page several times qupzilla creates popup line at the top and offers to save each one

**Comment by nowrep** [comment]
Firefox doesn't offer to save password on https://www.avangard.ru/login/www/ibank_enter.php either.
