### ISSUE TITLE
crashsafari.com crashes the browser

### ISSUE THREAD

**Issue by nekoswag** [QupZilla/qupzilla#2443]
The website crashsafari.com will crash the browser. I can't embed the code here because it breaks formatting unfortunately.

**Comment by cranes-bill** [comment]
This site eats all of my memory and needs more, so i'm not sure the problem is in QupZilla. :scream:

**Comment by mrnhmath** [comment]
It crashes even Firefox on Android, so not Qupzilla's issue.

**Comment by Chiitoo** [comment]
It /is/ in the name... or well, at least a part of it.  :]

So, working as intended?

<snickers a little>

**Comment by Chiitoo** [comment]
In all seriousness, though, I'm not sure if we can protect against this kind of things in QupZilla/Falkon?  Might be something for QtWebEngine/Chromium though.

**Comment by IsaiahPatton** [comment]
This is why antivirus is used for, to protect users.

![image](https://user-images.githubusercontent.com/16439221/30014276-70ddd02a-9119-11e7-927c-bae66496d9aa.png)
