### ISSUE TITLE
Window size/geometry not remembered on Linux 

### ISSUE THREAD

**Issue by sebaro** [QupZilla/qupzilla#2444]
On both Plasma 5 and FVWM, on start the window geometry is always the same no matter what size it had when closed.
Application version: 2.1.2
Qt version: 5.7.1
Platform: Linux x86_64, Gentoo

**Comment by nowrep** [comment]
It works fine here.

**Comment by sebaro** [comment]
It works when using WM's close button but not when using the Quit button (Ctrl+Q).
Application version 2.2.0
Qt version 5.9.2

**Comment by nowrep** [comment]
Yes, that's it! Thanks for the update, will fix it now.
