### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by liar666** [QupZilla/qupzilla#2447]
Hi,

On the page: https://qupzilla.com/ when I click "Download **[version 2.1.2]**" then select "Ubuntu", I read:
Ubuntu (and other Ubuntu-based linux distros) users can install QupZilla by running these commands
      sudo apt-get install qupzilla
But this installs **version 1.x** which is more than **outdated** and cannot open many sites.

I've found a page that explains how to compile manually 2.x ( https://www.linuxhint.com/install-qupzilla-browser-linux/ ) , but then updating to a new version is more than annoying, particularly on a distro that is supposed to have the ease of using packages...

I thought I reported this issue on the launchpad, but I cannot find the entry anymore...

**Comment by cranes-bill** [comment]
So what you expect here!? Somebody to compile QupZilla especially for your distribution, when you even did not describe which version is it...

_**And just IMO:**_

> ... supposed to have the ease of using packages...


That's just an ad trick, like in any other commercial garbage.

**Comment by liar666** [comment]
For a start, that the qupzilla website stops its "commercial garbage", and does not announce that version 2.1.2 can be installed on Ubuntu by using apt-get install...

**Comment by nowrep** [comment]
Then don't use outdated distribution if you want up-to-date software?

See https://blog.neon.kde.org/index.php/2017/08/29/great-web-browsing-coming-back-to-kde-with-falkon-new-packaging-formats-coming-to-kde-with-snap/
