### ISSUE TITLE
Ctrl+f only works after clicking the menu

### ISSUE THREAD

**Issue by AlvaroMartinez** [QupZilla/qupzilla#2450]
every time i want to search within the page, i have to go MENU -> Find for the first time.

QT 5.9.1, qupzilla 2.1.2

**Comment by ellul-ezra** [comment]
Same issue here in qupzilla 2.1.2, on KDE (Manjaro 64bit). In my case merely clicking the hamburger menu icon will bring the keyboard shortcut 'back to life' (only when the menu bar is hidden - clicking a menu in the menu bar does not have the same effect). On a side note, it would be nice to have the option to close the 'find' field when Ctrl+F is pressed again, if it has focus (and when it works!)

**Comment by nowrep** [comment]
Fixed in Qt 5.9.2
