### ISSUE TITLE
[Kind Request] Post a SHA256 underneath appimage downloadlink on homepage

### ISSUE THREAD

**Issue by Plasmoner** [QupZilla/qupzilla#2451]
@nowrep I always feel uneasy about binaries without a checksum. Originally, cryptographic hashes were designed to verify data integrity but to me they also fulfill the scope of verifying data authenticity. Yeah, I know about gpg, but neither is that one bullet proof because it also boils down to trust. Trust is a matter of choice, hence it's always subjective.
***
Should you not desire to post a sum on the homepage, then please post a sum right here so we can close this issue. Just make sure it's a SHA256 (no MD5, SHA1). Also, make sure you don't edit your post.
***
Much appreciated in advance. QupZilla is great. Glad to hear about the KDE story.
***
https://qupzilla.com/download#linux

![screenshot_20170909_200306](https://user-images.githubusercontent.com/29124716/30242377-09e1eac6-959e-11e7-98d6-21d497aaecd9.png)

Again, thanks.

**Comment by nowrep** [comment]
Done
