### ISSUE TITLE
Can't disable address bar search suggestions 

### ISSUE THREAD

**Issue by elcste** [QupZilla/qupzilla#2452]
The address bar shows search suggestions (from the search engine, not history) even when **Preferences → Tabs → Address Bar behaviour → Enable inline suggestions** is unchecked. 

I'm using the KDE Neon Snap [app version 2.1.99 (ca377a0d65), QtWebEngine 5.9.1], and I've see the issue with a fresh profile and DDG and after changing the search engine to Google.

**Comment by elcste** [comment]
I finally have a "real" build where I know this occurs: Application version 2.2.0, QtWebEngine version 5.9.1, built from source on Ubuntu MATE 17.10.

**Comment by nowrep** [comment]
You can disable searching from address bar which will also disable suggestions.
There is no special option to just disable suggestion.

**Comment by elcste** [comment]
OK, I think I misunderstood what the preference I listed above is for.

Thanks for working on QupZilla/Falkon!

**Comment by elcste** [comment]
Just in case someone sees this, the feature I had mistaken, disabling seach suggestions, was [implemented recently](https://github.com/QupZilla/qupzilla/commit/c4f0786cc31831d25710f7a2777ab1d2db1b8edc).
