### ISSUE TITLE
[Falkon] Entry is not indicated as pointed

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#2454]
I'm guessing that's an another one Qt issue, anyway i do report:
„_Location completer_“ entry is not marked (`:hover`) when the mouse pointer is over it.

### Falkon 2b3b95ae36 Qt 5.9.1:
![capture du 2017-09-17 18 58 32](https://user-images.githubusercontent.com/5161278/30522671-a22762f4-9bdc-11e7-863a-9c505c4f0e1e.png)

### QupZilla-2.1.2.AppImage:
![capture du 2017-09-17 19 00 36](https://user-images.githubusercontent.com/5161278/30522679-be679eca-9bdc-11e7-880f-ca218299f21c.png)

**Comment by nowrep** [comment]
That's actually a feature of Qt Fusion widget style. So now it behaves correctly (you don't get hover effect on any other list widgets).

**Comment by cranes-bill** [comment]
Does the search engine list is different element? Also, entry in „completer“ is hovered if i use keyboard keys to select it. And the Appimage style also is Fusion.

**Comment by nowrep** [comment]
Yes, searchbar completer is the same widget and it now looks exactly the same as addressbar completer.

**Comment by cranes-bill** [comment]
> Yes, searchbar completer is the same widget and it now looks exactly the same as addressbar completer.

But the pointer is hovering the entryes there!

**Comment by nowrep** [comment]
Not on my system :D

**Comment by cranes-bill** [comment]
Oh yes, typical Qt behavior. On different systems, works differently.
![capture du 2017-09-17 20 24 37](https://user-images.githubusercontent.com/5161278/30523263-e8005114-9be6-11e7-92d1-2aae8fef434f.png)

**Comment by nowrep** [comment]
Oh not this one, I meant the completer (eg. that popup that opens with search suggestions).

**Comment by cranes-bill** [comment]
Ah, probably i was not clear, sorry!
Have a good night!
