### ISSUE TITLE
No PRNG support

### ISSUE THREAD

**Issue by betsythefc** [QupZilla/qupzilla#2462]
Qupzilla currently doesn't seem to support [PRNG (Pseudo Random Number Generator)](https://en.wikipedia.org/wiki/Pseudorandom_number_generator).

You can see this at https://protonmail.com/compatibility

**Comment by cranes-bill** [comment]
![capture du 2017-09-22 07 50 01](https://user-images.githubusercontent.com/5161278/30729769-b2b19306-9f6a-11e7-9691-ec8df5f1c6dd.png)

**Comment by betsythefc** [comment]
Interesting...

I'm running an Ubuntu laptop (ARM), and I can't log into ProtonMail at all, because it just 'locks' up. Is there a proper way to debug a website in QupZilla?

I'm using version 1.8.9, installed via `sudo apt-get install qupzilla`

**Comment by betsythefc** [comment]
When installed on my mac, the page runs fine, however when installed on this linux box, it does not. It never auto-checks, and I can't figure out why. Javascript is enabled. Would this be an issue with such an 'old' version? On Ubuntu, how can I update to the latest?

**Comment by cranes-bill** [comment]
> Would this be an issue with such an 'old' version? 

Exact.

> On Ubuntu, how can I update to the latest?

When you want to use this distribution, the only way is to compile it yourself!

**Comment by betsythefc** [comment]
Okay thanks!
