### ISSUE TITLE
Aaklist asking to subscribe every time I restart qupzilla?

### ISSUE THREAD

**Issue by potholiday** [QupZilla/qupzilla#2465]
I have qupzilla appimage latest version and I also have subscribed to aaklist https://reek.github.io/anti-adblock-killer/ . The problem is everytime I restart qupzilla its asking me to subscribe to aaklist `
It seems that you have not subscribed or disabled AakList. Subscribe or Disable this alert`. I tried to remove aaklist from `adblock configuration>Option> remove subscription` but even after that when I restart qupzilla its asking me to subscribe to aaklist

**Comment by cranes-bill** [comment]
How it asks you, with pop up message!? That's not typical for QupZilla ad-blocker. You should have some script installed or so. I'm recommending you to completely clean the QupZilla profile.

**Comment by potholiday** [comment]
Yes, you are correct I have installed a greasmonkey script. after deleting no pop up messages came.
