### ISSUE TITLE
The browser opening an empty page when „restore last session“ is set as „start up action“

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#2467]
Focused window does'n load the last session even if i click „REFRESH“ button
Steps to reproduce:
Start with completely clean profile
Go to some address 
Close the browser
Start the browser again
Expected: to load the last page
Actual: the address is only on the address-bar, but the page is empty (see screenshot). Also click on „REFRESH“ button doing nothing

**QupZilla fe393af6fd
Falkon 4c827be
Qt 5.9.2**

![capture du 2017-10-06 17 09 41](https://user-images.githubusercontent.com/5161278/31282612-c5077d34-aabb-11e7-9b61-97b316c2cafc.png)

**Comment by srazi** [comment]
Please check if this fixes it:
```diff
diff --git a/src/lib/tabwidget/tabwidget.cpp b/src/lib/tabwidget/tabwidget.cpp
index 40ac617..871dc09 100644
--- a/src/lib/tabwidget/tabwidget.cpp
+++ b/src/lib/tabwidget/tabwidget.cpp
@@ -829,9 +829,7 @@ bool TabWidget::restoreState(const QVector<WebTab::SavedTab> &tabs, int currentT
     setCurrentIndex(currentTab);
     QTimer::singleShot(0, m_tabBar, SLOT(ensureVisible(int,int)));
 
-    // WebTab is restoring state on showEvent
-    weTab()->hide();
-    weTab()->show();
+    weTab()->tabActivated();
 
     return true;
 }

**Comment by cranes-bill** [comment]
Yup, now it works as expected.
_I'm leaving the issue opened and hope you will close it when needed, thank you!_
