### ISSUE TITLE
Setting "delete Locally Storage ... on close" does not delete anything

### ISSUE THREAD

**Issue by sciamano** [QupZilla/qupzilla#2472]
I experience the issue with the latest 2.1.2 version (win-portable downloaded from the site and debian package installed from sid repo). Starting with a fresh qupzilla profile, first go to "Preferences -> Browsing -> Local Storage" Tab and uncheck "allow local storage of HTML..." option. Then visit e.g. github.com or yandex.ru and examine the profile folder: no Local Storage folder will be created and that is of course expected. 
Now go to the settings again, but this time check  "allow local storage of HTML..." and "delete locally stored ... on close" options. Visiting github.com or yandex.ru leads to the Local Storage folder inside profile with files like https_github.com_0.localstorage or https_yandex.ru_0.localstorage. 
And after closing the qupzilla, the files are still present at the disk with all the content...
That obviously contraticts with the meaning of "delete locally stored ... on close" setting.

The issues is especially critical because it gives users a wrong feeling, that the program will care about their privary when in fact it will not.

**Comment by joseriosneto** [comment]
Yes. Same thing happens for me. Qt creates a 'Local Storage' dir while QupZilla (sorry.. Falkon :) tries to delete a 'LocalStorage' dir. I bet this probably changed in some qt versions.
