### ISSUE TITLE
[Question] About printing

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#2477]
I know it's a Qt related, but i really need to know what does makes that difference?
So, compare the both pdf files [here](https://yadi.sk/d/UpT1Cb4D3Nh2B5). 
The „**good.pdf**“ is a „real“ document, when you can click on the links, select text and so on... It was created with **QupZilla 2.1.2 Qt 5.8**. The „**sucks.pdf**“ is just embedded bad quality image, which drive me crazy. It was created with **QupZilla 2.2.0 Qt 5.9.2**
I was facing this early in some Qt beta versions (i think), but now Qt is an official release...

..........................................................................offtopic.....................................................................
_@nowrep by the way, the download link on the web page still refers to the old Appimage version._

**Comment by nowrep** [comment]
sucks.pdf is created with QPrinter, while good.pdf is created with printToPdf.

**Comment by cranes-bill** [comment]
Thanks a lot!
