### ISSUE TITLE
Feature Request: Do not hide spellcheck preferences if language list is empty

### ISSUE THREAD

**Issue by potuz** [QupZilla/qupzilla#2478]
I couldn't find the preference pane anywhere to look for the directories mentioned in the wiki. I had to run the program through gdb to find out where qupzilla was expecting the .bdic files then create those directories and finally I'll see the preference pane.

**Comment by cranes-bill** [comment]
Waht!!!???
It is not hidden:
![capture du 2017-10-12 21 37 41](https://user-images.githubusercontent.com/5161278/31513182-2722ab36-af96-11e7-9a73-012431c96211.png)

**Comment by nowrep** [comment]
As @cranes-bill said, the only thing that should hide is the language combobox, which makes sense as it should be empty in that case.

**Comment by potuz** [comment]
This is really weird! I had no preference pane for spell-check as described until I created the directory, I even raised a bug in Gentoo regarding this. After reading your comment went back to remove the directory in order to take a screenshot without the pane but the pref pane is still there!. I have no explanation for this and now I cannot reproduce this so I guess it should be closed, but I am really puzzled by this.

**Comment by nowrep** [comment]
Unless you used old build the Preferences category is always there.

**Comment by potuz** [comment]
Nope, just checked my logs and qupzilla was built and linked after qt 5.9.2. I'm astonished. I guess I apologize for the noise.
