### ISSUE TITLE
Tab loading animation doesn't stop with Qt 5.10

### ISSUE THREAD

**Issue by antonio-rojas** [QupZilla/qupzilla#2479]
When running on Qt 5.10, the tab loading animation (throbber) is never replaced by the page icon for some websites. It seems to affect mostly pages that auto-refresh, such as twitter or facebook. No issues with Qt 5.9.

**Comment by nowrep** [comment]
Hm, so I guess loading signals are broken again on 5.10

**Comment by Chiitoo** [comment]
Looks like QTBUG-65223: [[REG 5.9 -> 5.10] loadStarted is emitted twice when loading link with anchor](https://bugreports.qt.io/browse/QTBUG-65223)

**Comment by The-Compiler** [comment]
FWIW you can listen to `loadProgress` (with progress 100) instead of `loadFinished` as a workaround: https://github.com/qutebrowser/qutebrowser/pull/3427/files

Also, if you (plural) have a Qt JIRA account, maybe vote for the bug in the hope someone actually looks at those :wink:

**Comment by nowrep** [comment]
@The-Compiler Thanks for the workaround! Voted on the bug.

**Comment by antonio-rojas** [comment]
Any reason why this is only enabled for 5.10.0? The issue is still not fixed in qtwebengine 5.10.1 and the workaround no longer works

**Comment by Martii** [comment]
@antonio-rojas

> It seems to affect mostly pages that auto-refresh, such as twitter or facebook. 

...

> The issue is still not fixed in qtwebengine 5.10.1 and the workaround no longer works

Any particular twitter feed that you care to share for testing purposes. I just tested a known one with my Linux distro and the twitter page tab throbber does stop on the twitter favicon. OS X will be next after its massive download and recompile.

Thanks.

**Comment by cranes-bill** [comment]
> Any reason why this is only enabled for 5.10.0?

Because only that version was available when the bug was fixed (workaround).
Since **5.10.1** has been released just few days ago and the issue persists (i can confirm that), it will be adjusted for the new version as well.

**Comment by antonio-rojas** [comment]
> Because only that version was available when the bug was fixed (workaround).

Sure, but generally fixes are made future-proof. Would the workaround have any side effects if it were used with a version of Qt that doesn't have this issue? (I'd be interested to know in case this is fixed in Qt and I want to backport the fix)

**Comment by nowrep** [comment]
Yes, it have side effects - loadFinished is emitted twice on pages where it would work correctly without a workaround.

**Comment by The-Compiler** [comment]
Might be more than twice - for example, on https://translate.google.com/ it's triggered every time the URL changes because a character was entered.

**Comment by Martii** [comment]
> for example, on https://translate.google.com/ it's triggered every time the URL changes because a character was entered.

Ahh good a test target and one that triggers it here. Thank you. 😸 

Linux distro at effcd37 CONFIRMED

OS X latest at 64c8e9b NOT PRESENT
Linux distro at 64c8e9b NOT PRESENT
