### ISSUE TITLE
Typing text in the location bar sometimes inputs text on the autocompletion popup

### ISSUE THREAD

**Issue by antonio-rojas** [QupZilla/qupzilla#2480]
Sometimes when typing text in the location bar, the text suddenly start being written in the highlighted autocompletion popup item instead of the location bar input field. Once this happens, the location bar gets into a corrupted state that doesn't accept any input until the current tab is closed. 
 Unfortunately I don't have a way to reliably reproduce it, but it happens quite often.

**Comment by nowrep** [comment]
Can you test it with wm (kwin?) compositing off?

**Comment by antonio-rojas** [comment]
Haven't seen this in over a week since I updated to 2.2.1, so let's assume it's fixed
