### ISSUE TITLE
Qupzilla v2.2.0 keeps crashing

### ISSUE THREAD

**Issue by shaygover** [QupZilla/qupzilla#2481]
Had to downgrade back to 2.1.2.

Logs:
[Crash-2017-10-13T01:30:47.txt](https://github.com/QupZilla/qupzilla/files/1380998/Crash-2017-10-13T01.30.47.txt)
[Crash-2017-10-13T01:31:12.txt](https://github.com/QupZilla/qupzilla/files/1380999/Crash-2017-10-13T01.31.12.txt)
[Crash-2017-10-13T02:04:01.txt](https://github.com/QupZilla/qupzilla/files/1381000/Crash-2017-10-13T02.04.01.txt)
[Crash-2017-10-13T02:11:49.txt](https://github.com/QupZilla/qupzilla/files/1381001/Crash-2017-10-13T02.11.49.txt)

**Comment by nowrep** [comment]
Can you try to downgrade Qt to 5.9.1 instead of downgrading QupZilla? All those crashes are entirely in Qt (QtWebEngine+QtWebChannel).

**Comment by shaygover** [comment]
That will probably break kde...
qt5-base version is 5.9.2

**Comment by Martii** [comment]
@shaygover 
If you install the Qt Unified Installer it should allow you to have multiple versions then you should be able to tell QupZilla to build first with `/opt/Qt/5.9.1/gcc_64/bin/qmake` *(or whatever architecture you have and no need for environment variable changes)* then `make`. My current distro doesn't even have Qt 5.x and that's how I make it. Same with the Mac *(different home directory start than `/opt`)* since it has no Qt period.

**Comment by shaygover** [comment]
I don't want to break my distro for a browser.

Anyway, usually library problems happen when old software use newer library. But here I have old software with new library and everything is OK.
Is there such abig difference between 5.9.1 and 5.9.2?

**Comment by cranes-bill** [comment]
QupZilla must be compilled with the same Qt version you have installed!

**Comment by Martii** [comment]
@shaygover 
> I don't want to break my distro for a browser.

You won't. You don't seem to understand the Unified Installer and the point of it. You can have **all versions** installed if you want. If you use distro packages you can have some issues though and if you set a global environment variables that can kill things. So reference `qmake` directly for QupZilla and it will use that specific version that you installed with the Unified Installer.

Anyhow read up on it on Qt's site and you'll see that you can even try the snapshot of Qt 5.10 Beta on a system that has some other Qt 5.x in use. I have 4 and 5 on my main distro in use but I can try all of them period. If you still have any reservations look into VMs.

**Comment by abucodonosor** [comment]
Well -> Qt version: 5.9.2 (compiled with 5.9.1) .. that's the problem here ...

**Comment by Martii** [comment]
@abucodonosor 
Did find that a little unusual in the about Qt of QupZilla. Not sure how to interpret that one.

My distros base is Qt 5.6.1 and I've use the Unified Installer since Qt 5.8 and it's happy on every version since with calling qmake directly from it's respective `bin` folder. :)

Should ask @shaygover what is your distro and version?... so when I get home I can try it in a VM if available.

**Comment by shaygover** [comment]
@Martii arch linux x64

**Comment by samcv** [comment]
I was getting crashes when I had mismatching qupzilla binary and the qupzilla .so file. May or may not be what you are seeing.

**Comment by Martii** [comment]
@shaygover 
So installed Arch, Qt Unified Installer *(QtUI)*, built QupZilla...

Arch has a default Qt base of 5.9.2 at `qmake-qt5` with Plasma... however QtUI performed as it does on my main distro *(Host)*. Only immediate thing I can see is that GM doesn't actually install scripts here. Had to create them manually in the scripts folder. Will examine that at some point.

Anyhow... I'm in QupZilla with 2.2.0 tag built using QtUI 5.9.2 on the VM *(Guest)*. So far no crashes on GH nor OUJS. Any particular place you had in mind? *(no required login sites please)*.

Refs:

``` sh-session
$ qmake-qt5 -v
QMake version 3.1
Using Qt version 5.9.2 in /usr/lib

$ /opt/Qt/5.9.2/gcc_64/bin/qmake -v
QMake version 3.1
Using Qt version 5.9.2 in /opt/Qt/5.9.2/gcc_64/lib

$ /opt/Qt/5.9.1/gcc_64/bin/qmake -v
QMake version 3.1
Using Qt version 5.9.1 in /opt/Qt/5.9.1/gcc_64/lib
```

**Comment by Martii** [comment]
Do see this:

``` sh-session
$ sudo pacman -Q openssl
openssl 1.1.0.f-2
```

from trying to install GM scripts with console output of:

``` sh-session
$ qupzilla
QupZilla: 1 extensions loaded
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: Incompatible version of OpenSSL
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
GreaseMonkey: Cannot download script "Error creating SSL context (error:140A90C4:SSL routines:func(169):reason(196))"
```

OpenSSL issue with their distro package... possibly being too new?

**Comment by nowrep** [comment]
Please do not sidetrack this issue.

I can't myself reproduce this crash with Qt 5.9.2 (I have Arch too), but I got multiple reports of this exact crash. What are you doing when the crash happens? In other report, the crashes were happening when typing into address bar (even though the backtrace is completely inside QtWebEngine).

It would be great if you can downgrade to Arch Qt 5.9.1 and test it, but I understand if it's a problem. You can also use Qt prebuilt binaries as already suggested, but in this case you need to build QupZilla yourself.

@Martii You can make it work with installing openssl 1.0 and either uninstalling openssl 1.1 or fixing the library symlinks.

**Comment by Martii** [comment]
@nowrep 
Already figured that out. I can't make it crash either so venturing out on other nearby possibilities and openssl can be a factor of crashing Qt... so it's on topic Thank You. :P

**Comment by nowrep** [comment]
Fixed https://bugs.archlinux.org/task/56024

**Comment by Martii** [comment]
@shaygover 
> What that means?

It means they built it differently and it's a new release that fixes whatever was issued. I presume that it will show up for everyone at some point. I do find it interesting that it's a custom/modified build from development. I wonder what they changed? *(rhetorical question here)*
