### ISSUE TITLE
qupzilla does not save passwords on some sites

### ISSUE THREAD

**Issue by andr222** [QupZilla/qupzilla#2486]
Although I have been able to save passwords for 3 sites, for many other sites, qupzilla does not demand to save a password not yet saved.
I'm trying to transfer passwords saved by mozilla seamonkey, with little success.
One example is tomtop.com.
The only passwords savable so far are for zonesudoku.com ; bugs.documentfoundation.org, and www.androidpit.fr

I'm using qupzilla version 2.02 with qtwebkit engine 5.6.1, compiled and packaged by Mageia (linux)

**Comment by cranes-bill** [comment]
First, this version is no longer supported.
Even though, i'm using it as well as Qt 5.6.1 and don't have such a problem.

**Comment by andr222** [comment]
No longer maintained ?
Strange, the site says that it is the latest version.

Did you try the example given, tomtop.com ?
And the password was saved ?
If not, please try it, to confirm the problem.
Note that not all sites use the same code for requesting passwords.
Mozilla Seamonkey (and Firefox & Thunderbird, which use the same routine) are able to detect & save a password on that particular site.

Note from my report that SOME passwords ARE detected and saved, but many aren't.
For instance, passwords for callcameroon.com are saved.

**Comment by cranes-bill** [comment]
> Strange, the site says that it is the latest version.


Which site says that it's the latest version? qupzilla.com says the latest version is 2.1.2, but **the latest version even is 2.0**, so if you have precompiled binary downloaded from any other site it is your own problem.
No, i did not try tomtop.com and will not create profile just to try something where nonsense, because the **issues about version 2.0.2 will not be resolved**.
You just can try with clean profile first, or just try the [AppImage](https://www.qupzilla.com/uploads/QupZilla-2.2.0.AppImage) (**also with clean profile**) to see the issue if persists in latest version.

_Sorry for my bad English!_

**Comment by andr222** [comment]
It was one of the qupzilla pages (maybe on github) that said that my version of qupzilla and qt were the latest released.  So apparently the page wasn't up to date.

As far as testing tomtop.com, please note that not all sites use the same way of asking for passwords.
For some reason the method used by tomtop is not yet recognized by my version of qupzilla.
It would be in the interest of qupzilla (/falkon) to recognize the method used by tomtop.
So it would make sense to test that site in the lastest version of qupzilla, just to make sure it works.
BTW, I already tested that site with a clean profile (with my installed version), with the same results.

Could you explain what you mean by Appimage ?
If that lets me test the latest version, I'd be glad to test all the sites that haven't worked.
Note that I am running  qupzilla on Linux, and don't have access to another operating system.

In passing, I am interested in contributing to qupzilla, when I have more time. 
Don't worry about the quality of your English.  It is a common (very minor) problem in lots of open source projects.
Regards :)

**Comment by cranes-bill** [comment]
**QupZilla Appimage** is _precompiled binaries_, bundled against Qt libraries and can run on most Linux distributions (64 bit) without installation. I have been posting a direct link to the latest version in my comment above.
About the Appimage, you can find more [here](https://github.com/AppImage).

**Comment by andr222** [comment]
Thanks for the info about appimage.
I'll use it to test those sites to see if the latest qupzilla is still affected by the problem.
(I'd like to try using appimage to package some of my favorite apps, to make them portable.)

**Comment by nowrep** [comment]
QupZilla 2.02 is old, there were quite a lot of improvements to autofill, so this issue might have already been fixed in latest version.
Please test with 2.2.0.

**Comment by andr222** [comment]
OK, will test with 2.2.0, in next few days.
Thanks for developping QupZilla :)

**Comment by andr222** [comment]
Just a further observation.   Passwords for most sites ARE saved (with my older version).  I just happened to encounter the few sites that aren't saved.
I haven't let tried the latest version, but will soon.

**Comment by andr222** [comment]
I just logged into tomtop.com (successfully) with the appimage that I downloaded yesterday, and Qupzilla did not ask to save my password.
I don't remember the other sites with the same problem, but for the numerous other sites I've tried since reporting the problem, Qupzilla has correctly asked to save the password  (if it wasn't already saved).
Tomtop.com and the other problem sites that I had encountered were all sites for which mozilla seamonkey was able in the past to successfully save the password.
A thought, maybe the problem sites have changed their code since seamonkey was able to save the passwords, so saving passwords no longer works with these sites ?  I don't know how to see what code sites use when asking for a password.  In any case, it affects none of the sites I regularly use.

**Comment by andr222** [comment]
BTW, that was the appimage of Qupzilla 2.2.1

**Comment by nowrep** [comment]
Saving password on tomtop.com doesn't work with Firefox either.

**Comment by andr222** [comment]
If it doesn't work for Firefox now, it wouldn't work for Seamonkey now either, which uses the same code (the Gecko engine).  So it isn't worth "fixing".
It is the only problem site that I have used in the last few months.  The others were just trying to transfer old passwords.
