### ISSUE TITLE
[Feature Request] Disable java script for selected websites?

### ISSUE THREAD

**Issue by potholiday** [QupZilla/qupzilla#2490]
I want to disable java scripts in selected websites. Latest qupzilla appimage has only allow or disallow whole web traffic (edit>preference>web config>Allow javascript). Need  a way to prevent some websites from loading java scripts.

**Comment by cranes-bill** [comment]
The way is calling „**Adblock**“!

**Comment by nowrep** [comment]
It's not possible to implement it reliably with QtWebEngine.

**Comment by potholiday** [comment]
@cranes-bill  How should I use adblock to block javascript? Can you elborate a little?

**Comment by cranes-bill** [comment]
I didn't try, but Adblock has a script blocking option, so it should works with javascripts as well.

**Comment by potholiday** [comment]
@cranes-bill  I tried to write custom rules in adblock for blocking javascript
`||website.com^ $script`
This does not seem to work in qupzilla.

@nowrep Because there is no posiblity of solving this problem I am closing my issue.

**Comment by Martii** [comment]
> This does not seem to work in qupzilla.

Didn't block any scripts for OUJS when I added our domain. :\ Reconfirmed rule syntax with one from EasyList. New issue time?

**Comment by nekoswag** [comment]
<nowrep> It's not possible to implement it reliably with QtWebEngine.
I'm using this workaround:

Enable JavaScript in QupZilla settings, but add some custom Adblock rules:

This will block JavaScript on all sites except "example.net", "example.com" and "example.xyz"
`*$script,domain=~example.net|example.com|example.xyz`

This blocks 3rd party JS on all sites except "example.net" and "example.xyz:
`*$script,third-party,domain=~example.net|example.xyz`

It's a little cumbersome, but it works. Couldn't this be implemented in an easier way, like a list?

**Comment by nowrep** [comment]
@nekoswag That will only block externally loaded scripts, but not JavaScript in html source.

Actually, there seems to be a way to do this with QtWebEngine so it could be implemented.

**Comment by nekoswag** [comment]
I didn't know that, thanks for telling.
JavaScript is a big attack vector on the web nowadays, many people use Firefox just because it has uMatrix that lets you set JS rules comfortably. Having a similar feature in QupZilla would be great :)

**Comment by nowrep** [comment]
Well, then someone needs to implement it for QupZilla (well, Falkon). That someone may eventually be me, of course :D

**Comment by potholiday** [comment]
@nekoswag Thank you for sharing your solution
>JavaScript is a big attack vector on the web nowadays, many people use Firefox just because it has uMatrix 
I was going to ask for the same thing. 
@nowrep Can I ask will Falkon support other linux machines than KDE especially the appimage? When is the possible release date?
