### ISSUE TITLE
Wrong theme folder

### ISSUE THREAD

**Issue by liar666** [QupZilla/qupzilla#2493]
I'm on Ubuntu 17.10. I have installed the software as indicated here (after installing Qt5.9 manually): https://github.com/QupZilla/qupzilla#compiling

When I start qupzilla, I get error:
Cannot load theme  "chrome"
 
Thanks to the Menu>Help>Config>Path trick found here:
https://github.com/QupZilla/qupzilla/wiki/Themes#testing-in-qupzilla

I discovered that the default path for the themes is /usr/bin/themes , whereas the themes where installed in /usr/share/qupzilla/themes/ by the makefile
```
$ locate main.css | grep qupzilla
/usr/share/qupzilla/themes/breathe/main.css
/usr/share/qupzilla/themes/chrome/main.css
/usr/share/qupzilla/themes/linux/main.css
/usr/share/qupzilla/themes/mac/main.css
/usr/share/qupzilla/themes/windows/main.css
```

Also, there are some access rights problems as files under /usr/share/qupzilla/themes/ are readable only by root (might be due to the fact it's the installation user and has a restricted umask)

Would be great if the "make install" procedure would be corrected so that the software runs out-of-the-box.

Thanks

**Comment by nowrep** [comment]
Don't use NO_SYSTEM_DATAPATH option when building and installing it system-wide.
