### ISSUE TITLE
Accentuated characters printed as diamond<?> (�)

### ISSUE THREAD

**Issue by liar666** [QupZilla/qupzilla#2502]
Hi again,

Since qupzilla 2 is not available in the (ubuntu/debian) repositories, I've manually compiled it:
Application version 2.2.0 (db26f24)
QtWebEngine version 5.9.0

I'm using a French Keyboard, but in a generic en_US locale, using a mixture of US/fr setup:
LC_ALL=
LC_MEASUREMENT=fr_FR.UTF-8
LC_PAPER=fr_FR.UTF-8
LC_MONETARY=C
LC_NAME=fr_FR.UTF-8
LC_COLLATE=C
LC_CTYPE=en_US.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_NUMERIC=C
LC_MESSAGES=en_US.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_TIME=C

In qupzilla 2, everytime I type an accentuated char that is on the French keyboard (e.g. é), it works. When I need to compose several keys (e.g. ^ and o) to get an accentuated char, I get: � (diamond<?>).

When I was using qupzilla 1, I solved the same problem by runing with:
 LC_MONETARY=en_US.ISO8859-1 LC_NUMERIC=en_US.ISO8859-1 LC_ALL=en_US.ISO8859-1 LC_MESSAGES=en_US.ISO8859-1 LC_COLLATE=en_US.ISO8859-1 LC_CTYPE=en_US.ISO8859-1 LC_TIME=en_US.ISO8859-1 /usr/bin/qupzilla

This does not work now.

I've also tried with:
LC_MEASUREMENT=fr_FR.UTF-8 LC_PAPER=fr_FR.UTF-8 LC_MONETARY=C LC_NAME=fr_FR.UTF-8 LC_COLLATE=C LC_CTYPE=en_US.UTF-8 LC_ADDRESS=fr_FR.UTF-8 LC_NUMERIC=C LC_MESSAGES=en_US.UTF-8 LC_TELEPHONE=fr_FR.UTF-8 LC_IDENTIFICATION=fr_FR.UTF-8 LC_TIME=C /usr/bin/qupzilla

with no more success...

For your information, I just did:
$ cat -tev
�   <- the character inserted by Qupzilla when hitting ^+o
M-oM-?M-=$
ô     <- the character inserted on the commandline (xterm+bash) when hitting ^+o
M-CM-4$

**Comment by cranes-bill** [comment]
See (that)[https://github.com/QupZilla/qupzilla/issues/2364#issuecomment-309260731]!

**Comment by liar666** [comment]
Thanks for the quick response.

I already had read #2247, but found no solution apart reinstalling a complete system.

Reading the post you recommend, I tried setting the 3 vars and resetting my keyboard with `setxkbmap fr -option ctrl:swapcaps` and it does not work :{ I've configured the MultiKey with xmodmap, and all the chars it generates appear as �.

FYI, fcitx and imsettings are not installed on my system.

**Comment by cranes-bill** [comment]
Try `LC_ALL=fr_FR.utf8` or `LANG=fr_FR.utf8`!

**Comment by liar666** [comment]
Same problem
https://imgur.com/a/4qTRZ

**Comment by cranes-bill** [comment]
The problem for sure is in your environment, but not in QupZilla.

**Comment by liar666** [comment]
Everything is working fine with all the other applications (X, Gnome, etc.). They apparently better follow the system/env configuration as Qt.

Since I don't have time to waste with the Qt config mess, I'll just forget about using QupZIlla for the moment.

Thanks for your help and sorry for the waste of time.
