### ISSUE TITLE
Autoscroll works partially on image files

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#2503]
The autoscrol plugin works **UP** and **DOWN** only, but not to **LEFT** and **RIGHT**, when the file is an image, but not web page.

_2.2.1 (e228635)
Qt 5.9.2._

**Comment by nowrep** [comment]
Yeah, that extremely clever JavaScript code that detects scrollbars unfortunately fails in this case. I have no idea how to fix it though.

**Comment by cranes-bill** [comment]
It works in **v1.8** with Qt 5.6.* _(just for information if can be in help)_.

**Comment by nowrep** [comment]
Not really, the implementation is completely different in QtWebKit and QtWebEngine versions.

**Comment by cranes-bill** [comment]
Oh, i meant version **2.0.2**, sorry!

**Comment by cranes-bill** [comment]
Also in addition to above, i forgot to mantion that it shows **scroll_vertical** image instead of **scroll_all**, but works.

**Comment by cranes-bill** [comment]
He he, i was sure you will catch it, thanks!
