### ISSUE TITLE
Visual C++ Redistributable Missing File

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla#2505]
So I was in my Win10 x64 vbox and was updating QupZilla from 2.1.2 to 2.2.1 and encountered this *(MSVCR120.dll)*:

<img src="https://user-images.githubusercontent.com/114709/32888911-18e5df4c-ca86-11e7-8707-1b504c4d9889.png" alt="Missing MSVCR120.dll" title="Click to enlarge" width="97" height="44" />

From lots of past experience I realize that this can usually be remedied by installing [the Visual C++ Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/download/details.aspx?id=40784) but I was wondering if QupZilla is supposed to distribute these with the application?

**Comment by nowrep** [comment]
What version did you installed?

**Comment by Martii** [comment]
@nowrep 
> What version did you install? 

&nbsp;

> ...my Win10 x64 vbox...

This would indicate the 64 bit version [from above](https://github.com/QupZilla/qupzilla/issues/2505#issue-274483345). :)

> ... updating QupZilla from 2.1.2 to 2.2.1...

Also [from above](https://github.com/QupZilla/qupzilla/issues/2505#issue-274483345). 

I didn't get this message on a clients machine with Windows 7 x64 *(but he is also running VS of many versions so it's probably already there)*... just in this clean VM of Windows 10.

**Comment by srazi** [comment]
Indeed, it is loaded by OpenSSL.

![image](https://user-images.githubusercontent.com/1328454/32969724-6c406c22-cbfb-11e7-8f70-de28fbd23e66.png)

I will try to find a fix without hard coding DLL version.

**Comment by srazi** [comment]
Fixed by 78a72629174351708b2c5052c6e367718f79f8f1
@nowrep Other issues of Windows installer also are fixed and now Windows builds use Qt-5.9.2. So, if you want to re-push tag v2.2.1 to update installers then please at first delete installers from [release v2.2.1](https://github.com/QupZilla/qupzilla/releases/tag/v2.2.1).

**Comment by nowrep** [comment]
@srazi I'll just make new version, thanks.
