### ISSUE TITLE
Outdated version string

### ISSUE THREAD

**Issue by nekoswag** [QupZilla/qupzilla#2507]
The version string on Qupzilla 2.2.1 on openSUSE Tumbleweed says 2.2.0.

I guess it's line 11 in defines.pri.

**Comment by Martii** [comment]
@nekoswag 
I think this is already fixed in 4c2a114cf91613edd42c836a8303ed59bf8a4f27

I do know that the tag was in the prior commit so use this hash to build 2.2.1 with `$ git checkout 4c2a114` *(using the short)*

**Comment by nowrep** [comment]
I made a bad tag and only fixed it few hours after, sorry.
