### ISSUE TITLE
api-ms-win-crt-runtime-l1-1-0.dll error

### ISSUE THREAD

**Issue by mehmetulukaya** [QupZilla/qupzilla#2508]
In windows7 x64 system I am getting this error as a pop-up. I tried some fixing but not solved what should I do?

The message is "api-ms-win-crt-runtime-l1-1-0.dll is missing"

**Comment by Martii** [comment]
Have you tried the url I suggested at https://github.com/QupZilla/qupzilla/issues/2505#issue-274483345 . Ensure that you pick the x64 version when you get that from Microsoft. This is a workaround not a fix.

**Comment by srazi** [comment]
@mehmetulukaya Download and install `vc_redist.x64.exe` from [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-in/download/details.aspx?id=48145).
Please report result here.

**Comment by mehmetulukaya** [comment]
[1A4C:1CB8][2017-11-24T11:54:37]e000: Error 0x80070666: Cannot install a product when a newer version is installed.
I think there is a problem with my computer's settings or permissions.

**Comment by Martii** [comment]
Ref:
* https://developercommunity.visualstudio.com/content/problem/14701/visual-c-redistributable-for-visual-studio-2015-ca.html
