### ISSUE TITLE
Falkon - it's not possible to build with translations

### ISSUE THREAD

**Issue by pavbaranov** [QupZilla/qupzilla#2513]
As in the title. 
There are translations for Falkon in sources, but CMakeLists.txt haven't any instructions to compile them. I've tried to change CMakeLists, but without success. So, is translations implemented or not?

**Comment by cranes-bill** [comment]
Try the following, should works:
_(From the Falkon source directory)_
```
mkdir locale
for TSNAME in $(ls translations | sed 's/\.ts//g'); do for QMNAME in "$(find -name "${TSNAME}.ts")" ; do lrelease-qt5 ${QMNAME} -qm "locale/${TSNAME}.qm" ; done ; done
```
Then move the „locale“ folder in the same directory where the „theme“ folder is located.

**Comment by pavbaranov** [comment]
I know how to convert ts to qm, but it's a bug in CMakeLists.txt in Falkon, because translations should be convert automatically. 
Second bug is that even if I convert ts to qm and move it to /usr/share/falkon/locale/, translation is shown in Falkon, but when I choose it, Falkon is still in English.

**Comment by nowrep** [comment]
Translations are not yet sorted out in Falkon. You should keep using QupZilla until there is first Falkon release.

**Comment by cranes-bill** [comment]
> Second bug is that even if I convert ts to qm and move it to /usr/share/falkon/locale/, translation is shown in Falkon, but when I choose it, Falkon is still in English.

 Works to me, even with symlink to QupZilla translations directory.
