### ISSUE TITLE
Very unstable on Qt5.10 system

### ISSUE THREAD

**Issue by pavbaranov** [QupZilla/qupzilla#2514]
Qupzilla 2.2.1 builds on Qt5.9.2 is very unstable on system (linux; x86-64) with Qt5.10 (now rc2). Crashes without any logs in ~/.config/qupzilla/crashlog (so any logs). Crashes are nonreproduceable without that if qupzilla crashes with several tabs open, there's another crash after restore session. 
Unfortunetly there isn't possible to build Qupzilla on Qt5.10.

**Comment by nowrep** [comment]
What's wrong with building on Qt 5.10?
Also please provide gdb backtrace with crash reports.

**Comment by pavbaranov** [comment]
Ok, I read your answer, then I'll report first problem on Qt's bugzilla.
Crash report, but only with restore session:
`Starting program: /usr/bin/qupzilla 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffd6d77700 (LWP 3599)]
[New Thread 0x7fffc3cb9700 (LWP 3600)]
[New Thread 0x7fffc32a6700 (LWP 3601)]
[New Thread 0x7fffc28a0700 (LWP 3602)]
[New Thread 0x7fffc209f700 (LWP 3603)]
[New Thread 0x7fffc189e700 (LWP 3604)]
[New Thread 0x7fffc109d700 (LWP 3605)]
[New Thread 0x7fffc089c700 (LWP 3606)]
[New Thread 0x7fffa3fff700 (LWP 3607)]
[New Thread 0x7fffa3358700 (LWP 3608)]
[New Thread 0x7fff98988700 (LWP 3609)]
[New Thread 0x7fff8ffff700 (LWP 3611)]
[New Thread 0x7fff8f7fe700 (LWP 3612)]
[New Thread 0x7fff8effd700 (LWP 3613)]
[New Thread 0x7fff8e7fc700 (LWP 3614)]
[New Thread 0x7fff8dffb700 (LWP 3615)]
[New Thread 0x7fff8d7fa700 (LWP 3616)]
[New Thread 0x7fff8cff9700 (LWP 3617)]
[New Thread 0x7fff6ffff700 (LWP 3618)]
[New Thread 0x7fff6f7fe700 (LWP 3619)]
[New Thread 0x7fff6effd700 (LWP 3620)]
[New Thread 0x7fff6e7fc700 (LWP 3621)]
[New Thread 0x7fff6dffb700 (LWP 3622)]
[New Thread 0x7fff6d7fa700 (LWP 3623)]
[New Thread 0x7fff6cff9700 (LWP 3624)]
[New Thread 0x7fff4ffff700 (LWP 3625)]
[New Thread 0x7fff4f7fe700 (LWP 3626)]
[New Thread 0x7fff4effd700 (LWP 3627)]
[New Thread 0x7fff4e7fc700 (LWP 3628)]
[New Thread 0x7fff4dffb700 (LWP 3629)]
QupZilla: 0 extensions loaded
[New Thread 0x7fff4d7fa700 (LWP 3633)]
[New Thread 0x7fff4cff9700 (LWP 3634)]
[New Thread 0x7fff4d7fa700 (LWP 3635)]
[Thread 0x7fff4d7fa700 (LWP 3633) exited]
[New Thread 0x7fff27fff700 (LWP 3637)]
[New Thread 0x7fff272ea700 (LWP 3645)]
[New Thread 0x7fff26ae9700 (LWP 3647)]
[New Thread 0x7fff25445700 (LWP 3682)]
[Thread 0x7fff25445700 (LWP 3682) exited]
[New Thread 0x7fff25445700 (LWP 3683)]
[New Thread 0x7fff24c44700 (LWP 3687)]
[Thread 0x7fff24c44700 (LWP 3687) exited]
[New Thread 0x7fff24c44700 (LWP 3688)]
[New Thread 0x7fff1ffff700 (LWP 3692)]
[Thread 0x7fff1ffff700 (LWP 3692) exited]
[New Thread 0x7fff1ffff700 (LWP 3693)]
[New Thread 0x7fff1f7fe700 (LWP 3697)]
[Thread 0x7fff1f7fe700 (LWP 3697) exited]
[New Thread 0x7fff1f7fe700 (LWP 3698)]
[New Thread 0x7fff1effd700 (LWP 3702)]
[Thread 0x7fff1effd700 (LWP 3702) exited]
[New Thread 0x7fff1effd700 (LWP 3703)]
[New Thread 0x7fff1e7fc700 (LWP 3704)]
[Thread 0x7fff1e7fc700 (LWP 3704) exited]
[New Thread 0x7fff1e7fc700 (LWP 3708)]
[Thread 0x7fff4d7fa700 (LWP 3635) exited]
[Thread 0x7fff1effd700 (LWP 3703) exited]

Thread 1 "qupzilla" received signal SIGSEGV, Segmentation fault.
0x00007fffef306760 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
(gdb) bt
#0  0x00007fffef306760 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#1  0x00007fffef27cf00 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#2  0x00007fffedad4caf in QMetaObjectPublisher::handleMessage(QJsonObject const&, QWebChannelAbstractTransport*) () from /usr/lib/libQt5WebChannel.so.5
#3  0x00007ffff6b49b2f in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQt5Core.so.5
#4  0x00007fffedada8b5 in QWebChannelAbstractTransport::messageReceived(QJsonObject const&, QWebChannelAbstractTransport*) () from /usr/lib/libQt5WebChannel.so.5
#5  0x00007fffef27cdfb in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#6  0x00007fffef27d153 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#7  0x00007fffefb9e60b in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#8  0x00007fffefab0a38 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#9  0x00007fffefabf01e in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#10 0x00007fffefaa4086 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#11 0x00007ffff0f143a3 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#12 0x00007ffff065fee2 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#13 0x00007ffff05f7548 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#14 0x00007ffff05f8528 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#15 0x00007ffff05f8993 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#16 0x00007fffef239028 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#17 0x00007ffff6b4a40b in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#18 0x00007ffff70d4e3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff70dc816 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff6b191e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---q
`

**Comment by nowrep** [comment]
Crashes entirely in QtWebEngine.

**Comment by pavbaranov** [comment]
It looks, like rebuild Qupzilla aganist of Qt5.10 solved this problem. I hope so. Any crashes since about two hours.
