### ISSUE TITLE
Tab manager extension settings sometimes stop being respected

### ISSUE THREAD

**Issue by andr222** [QupZilla/qupzilla#2520]
With AppImage 2.2.2 (& before) on Mageia (Linux) 64bit.
This occurs usually after a crash, and at least once after I uploaded crash reports for another issue.
I don't recall this happening in other circumstances, and usually tabs display correctly on starting Qupzilla.
My tab manager settings are :
(1) **view in side bar** , and (2) **+ replace main tab bar**.
The parameter settings of tab manager remain correct, but the side bar is not displayed.
At least once the extensions were all disabled (after the last crash with AppImage 2.2.2),
but not usually (for previous crashes with AppImage 2.2.2 & before, or after uploading crash reports).

Changing the setting to **view in window**, closing tab manager settings, then changing back to
**view in side bar**, corrects the display for the current window.
This must be redone to correct each window.

**Comment by nowrep** [comment]
Is this still happening with 2.2.4?

**Comment by andr222** [comment]
Yes.
It is now much worse with AppImage 2.2.4.
When Qupzilla is loaded, with 5 windows, none respect the tab manager setting to side bar.
I can still use setting a window to the window option of tab manager, exiting, re-entering, and resetting to side bar option.  This displays correctly for the visible window, as it did before.
However, when I correct a second window, the first window no longer respects the side bar setting.
BTW, the window setting of tab manager doesn't seem to do anything.  At least, no separate window for tabs is created when that option is selected.
/tmp/qupzilla-andr/ directory is empty.
~/.cache/qupzilla/andr/ directory contains only Cache/ with 122 entries.
~/.cache/QupZilla/ contains only PluginMetadataCache.bin
~/.config/qupzilla/crashlog/ contains 4 recent entries, the previous entry being 17 days earlier.  Attached.
~/.config/qupzilla/profiles/andr/ contains many files.
... sessions/ is empty
[Crash-2018-01-22T00:22:06.txt](https://github.com/QupZilla/qupzilla/files/1651006/Crash-2018-01-22T00.22.06.txt)
[Crash-2018-01-21T21:21:34.txt](https://github.com/QupZilla/qupzilla/files/1651007/Crash-2018-01-21T21.21.34.txt)
[Crash-2018-01-21T21:20:05.txt](https://github.com/QupZilla/qupzilla/files/1651008/Crash-2018-01-21T21.20.05.txt)
[Crash-2018-01-21T21:19:44.txt](https://github.com/QupZilla/qupzilla/files/1651009/Crash-2018-01-21T21.19.44.txt)






I exited Qupzilla using the quit option, and then re-entered, only to find that my previous sessions were lost.  The first time that this happened.
I would like to try to recover the lost sessions, if you can tell me where to look.  It will be otherwise difficult to regenerate the lost tabs.

**Comment by cranes-bill** [comment]
@andr222 You should not run the AppImage when you have running another QupZilla version!

**Comment by nowrep** [comment]
You can't mix QupZilla versions (particularly you can't go back to older version without losing profile data - you will be warned about this on startup).

Is that what happens here? You say that you use 2.2.4 but your crash logs all show 2.0.2.

**Comment by andr222** [comment]
I wasn't trying to run 2 versions at the same time, but since Appimage 2.2.4 was inutilisable (most tabs not visible), I closed it and tried Appimage 2.2.2.
Since that showed no sessions saved, I closed it and tried the current version for my distro release, 2.0.2.
I forgot when I was making the report, but the crashes for 2.0.2 are because qt was updated to 2.6.2 from 2.6.1, and the (relatively new) Mageia packager had made Qupzilla 2.0.2 depend on exactly qt 2.6.1 instead of 2.6.*.

If the profiles are erased if one goes back to a previous version, one should be warned and there should be a documented workaround.  I didn't see any warning about losing profile info.  Such a warning should have required input from the user, to ensure that it is seen.
(Bookmarking all tabs before going back should have worked.)

I had about 50 tabs loaded, and I used session manager to keep track of them.
Until this problem where I was forced to go back to a previous version, it worked very well.  It will take me some time to recover from the lost tabs.

When I think about it, tabs kept by session manager should be an exception to erasing the profile, since tabs aren't inherently version dependant.

**Comment by nowrep** [comment]
Alright, sorry - that behavior was actually removed and it no longer warns you about it and you will lose your session (because older versions doesn't understand new session file format).

I will bring the warning back. So this issue is only about you going back to older version which is not supported.

But please note, you will only lose your default session, if you manually backed up session in session manager (those are stored in `sessions` directory in profile), those should not be touched at all.

**Comment by andr222** [comment]
It must have been a glitch due to first time using (Appimage) v2.2.4.
Maybe due to changed format of tab manager sessions.
In any case, the lateral tab bar is now respected in 2.2.4, after starting with no tabs saved.  (Since they were all lost.)
I'm seeing a lot of nice little improvements.
My next post here will be with Qupzilla again.
