### ISSUE TITLE
Enable proprietary codecs option

### ISSUE THREAD

**Issue by maximus321** [QupZilla/qupzilla#2521]
It is not possible to play netflix video or other DRM video with this nice browser.
However, it is possible to do :
http://blog.qt.io/blog/2016/06/03/netflix-qt-webengine-5-7/

It would be nice if the browser was built with the option enabled by default, and we just had to drop the plugins/codecs in the release folder so it would work out of the box (widevineCdm for example).

Really appreciate the project!

**Comment by cranes-bill** [comment]
It would bi nice if you read the quoted link content, where pretty well is explained that you should do that yourself!
