### ISSUE TITLE
Google input text lose focus after a while when logged in

### ISSUE THREAD

**Issue by asasga** [QupZilla/qupzilla#2525]
Qupzilla: 2.2.0
QtWebEngine: 5.9.2
Tested: Chakra and KaOS

Google text input focus is lost after a while even if I am writting.
The issue only happens when I am logged in with my google account.

To reproduce the issue:

1) Log in into a google account.
2) Load Google web site: https://www.google.es/?gws_rd=ssl
3) The input text is focuses by default.
4) Wait a moment until input text lose the focus.

Great job guys

**Comment by nowrep** [comment]
Fixed in new QtWebEngine
