### ISSUE TITLE
Making any change to default config causes pages to not load with "There is no Internet connection"

### ISSUE THREAD

**Issue by antnythr** [QupZilla/qupzilla#2527]
I've just installed QupZilla 2.2.2 on Arch and I'm having an issue that I don't know how to resolve.

On a clean profile the browser loads pages as expected. Any modification to any setting however causes the browser to display a grey page stating "There is no Internet connection". Closing and re-opening the browser doesn't fix the issue.

If I delete the profile and start a new session, things go back to working.

Any ideas?

**Comment by cranes-bill** [comment]
When you experience this again, please check out **Menu » Preferences » Navigation » Proxy configuration**
If it is set to _Manual configuration_, just change it!

**Comment by antnythr** [comment]
That fixed the problem, thanks!

**Comment by cranes-bill** [comment]
@nowrep, after aa9f3ef the default proxy settings are set to _Manual configuration_, but as you can see, this might be a bit annoying for the people who are not familiar with the settings.....?
