### ISSUE TITLE
Add Extension Password Hasher Plus

### ISSUE THREAD

**Issue by raneon** [QupZilla/qupzilla#2528]
The Password Hasher Plus (https://github.com/simu/passwordhasherplus) extension is my favourite one in Firefox. I don't want to store and sync my passwords on any computer or mobile. It would be nice if QupZilla could support this extension too.

**Comment by cranes-bill** [comment]
That what i still fail to understand is - **why the people are making requests for third party software here**!!!
Have you asked them to contribute in QupZilla?
