### ISSUE TITLE
Context menu is missing "open link"-entries when JS disabled

### ISSUE THREAD

**Issue by WellMayBe** [QupZilla/qupzilla#2529]
Can't open links in new windows or tabs anymore when javascript is disabled, because these menu-entries are gone.

And if someone thinks this is sellable as a feature - believe me you can't. Not capable to open a link in a new window/tab is a show stopper for many people - and you guys do not have such a large number of users to allow you to lose of of these.

**Comment by nowrep** [comment]
You are using old version.

It works without JavaScript in new versions.
