### ISSUE TITLE
No Inspect Element

### ISSUE THREAD

**Issue by PlayerW** [QupZilla/qupzilla#2531]
I find the "Inspect Element" function to be essential to a browser, so after searching, I found the fix on
https://github.com/QupZilla/qupzilla/wiki/FAQ#16-there-is-no-web-inspector-in-qupzilla-20
to be not working.

Latest packages installed on Manjaro.

**Comment by nowrep** [comment]
It does work:

    QTWEBENGINE_REMOTE_DEBUGGING=12345 qupzilla

of course selected port must not be taken.

**Comment by PlayerW** [comment]
Okay, so closing the browser, and executing the command you posted here does open qupzilla with IE perfectly, but is there any way of making this change permanent? If I close QZ and restart it it's gone again

**Comment by nowrep** [comment]
Sure, you can for example change your launcher (.desktop) to execute this command instead of just `qupzilla`, or you can export that env variable globally for the whole session (not recommended), ...
