### ISSUE TITLE
Spectre vulnerability?

### ISSUE THREAD

**Issue by AcarBurak** [QupZilla/qupzilla#2533]
Is QupZilla vulnerable to [Spectre](https://www.theregister.co.uk/2018/01/04/intel_amd_arm_cpu_vulnerability/) as [Chrome](https://support.google.com/chrome/answer/7623121?hl=en-GB) and [Firefox](https://www.ghacks.net/2017/11/22/how-to-enable-first-party-isolation-in-firefox/) seem to be?

**Comment by nowrep** [comment]
Yes, everything is vulnerable.

**Comment by AcarBurak** [comment]
So can we do such things as Chrome and Firefox do to mitigate it?

**Comment by nowrep** [comment]
Yes, but you need to wait for updated QtWebEngine.

**Comment by AcarBurak** [comment]
In the meantime, does disabling js globally and enabling it when necessary mitigate against it, or am I being paranoid?
