### ISSUE TITLE
Push string changes to Transifex

### ISSUE THREAD

**Issue by smarquespt** [QupZilla/qupzilla#2536]
@nowrep 

Can you please push string changes to transifex before new release and wait maybe 2-3 days, merge them and after it publish the new version?

I would like to have a full localized application if possible and I think that most users would to.

Regards

**Comment by nowrep** [comment]
I'll try this time.

Ideally the bugfix releases should not change strings, so there is plenty of time to finish translation and have it complete by next bugfix release. But right now the situation is different, sorry.

**Comment by smarquespt** [comment]
@nowrep 

Ok, thanks for your reply .

**Comment by nowrep** [comment]
I'll be releasing new version tomorrow (16.) or the day after (17.), is that okay for you?

**Comment by smarquespt** [comment]
Fine by me. Thanks for letting me know.
