### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#2537]
Crash when trying to open youtube link from embeded video 
![capture du 2018-01-06 21 45 08](https://user-images.githubusercontent.com/5161278/34643450-1c3ccd5c-f32d-11e7-9f33-e8a7da567635.png)

[Crash-2018-01-06T21:37:35.txt](https://github.com/QupZilla/qupzilla/files/1609171/Crash-2018-01-06T21.37.35.txt)
[gdb_backtrace_include_garbage.txt](https://github.com/QupZilla/qupzilla/files/1609172/gdb_backtrace_include_garbage.txt)

**QupZilla 2.2.3 (748aa31)
QtWebEngine 5.9.3**

**Comment by nowrep** [comment]
Can you reproduce it?

**Comment by cranes-bill** [comment]
Absolutely, also with clean profile.

**Comment by cranes-bill** [comment]
@nowrep It is non reproducible with disabled Adblock.

**Comment by nowrep** [comment]
Yeah I can reproduce it myself.

**Comment by nowrep** [comment]
Alright, apply this for now and I'll fix it tomorrow.

```diff
diff --git a/src/lib/adblock/adblockicon.cpp b/src/lib/adblock/adblockicon.cpp
index 86fc6035..11b03d59 100644
--- a/src/lib/adblock/adblockicon.cpp
+++ b/src/lib/adblock/adblockicon.cpp
@@ -40,7 +40,7 @@ AdBlockIcon::AdBlockIcon(QObject *parent)
     connect(this, &AbstractButtonInterface::clicked, this, &AdBlockIcon::clicked);
     connect(this, &AbstractButtonInterface::webPageChanged, this, &AdBlockIcon::webPageChanged);
     connect(AdBlockManager::instance(), &AdBlockManager::enabledChanged, this, &AdBlockIcon::updateState);
-    connect(AdBlockManager::instance(), &AdBlockManager::blockedRequestsChanged, this, &AdBlockIcon::blockedRequestsChanged);
+    // connect(AdBlockManager::instance(), &AdBlockManager::blockedRequestsChanged, this, &AdBlockIcon::blockedRequestsChanged);
 }
 
 QString AdBlockIcon::id() const
```

**Comment by cranes-bill** [comment]
Ah, thanks! It is not important, i just wanted to inform you.
Have a good night!

**Comment by cranes-bill** [comment]
@nowrep Everything looks fine at all, but the browser generates a back-trace on close. 
[Crash-2018-01-07T20:48:49.txt](https://github.com/QupZilla/qupzilla/files/1610094/Crash-2018-01-07T20.48.49.txt)

**Comment by nowrep** [comment]
@cranes-bill Yeah, I've already fixed that but didn't push yet.

**Comment by cranes-bill** [comment]
Aaah, sorry!
