### ISSUE TITLE
Site has only blue arrow

### ISSUE THREAD

**Issue by hhgoten** [QupZilla/qupzilla#2538]
https://www.google.de/aclk?sa=l&ai=DChcSEwjLrcuI8MXYAhVOnhsKHQGGBbYYABAGGgJ3bA&sig=AOD64_2NzXNrAO6icZczsQE40zwuy6GeDQ&ctype=5&q=&ved=0ahUKEwj9msaI8MXYAhXRzaQKHf7qAxUQ9aACCDM&adurl=

Firefox show site with pictures from a dealer of officeware.
QupZilla only a small blue square and a blue arrow

**Comment by cranes-bill** [comment]
Disable Adblock!

**Comment by nowrep** [comment]
That one is blocked by EasyList, for a good reason.

**Comment by hhgoten** [comment]
Thank you for your fast answer !
Best Regards
H.Herwig

2018-01-07 14:34 GMT+01:00 David Rosca <notifications@github.com>:
