### ISSUE TITLE
Backdrop Filters

### ISSUE THREAD

**Issue by Diablopc** [QupZilla/qupzilla#2542]
Is there able to enable [this](https://webkit.org/blog/3632/introducing-backdrop-filters/) in qupzilla?

**Comment by nowrep** [comment]
Did you try it?

**Comment by Diablopc** [comment]
I have tried them in opera - looks nice. But here i cant find how to try them ((

**Comment by cranes-bill** [comment]
Try with:
`--enable-experimental-web-platform-features`

**Comment by Diablopc** [comment]
@cranes-bill you mean to start qupzilla with this?

**Comment by nowrep** [comment]
Yes

**Comment by Diablopc** [comment]
Nope, no changes ((

**Comment by nowrep** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter

**Comment by Diablopc** [comment]
I had to read this
But...
Here is the result of working filters:
![](http://i.piccy.info/i9/2e1ba22116fd6a9c38ca62da1ae7f00f/1515679723/121917/1199641/Screenshot_20180111_155644.png)

And here, this same page, opened in qupzilla
![](http://i.piccy.info/i9/ce91da27fffec95255b949df98677273/1515679778/91941/1199641/Screenshot_20180111_155730.png)
..........

**Comment by cranes-bill** [comment]
But there is a filter, just looks **different**. But the images also are **different**, so perhaps they are have **different** settings.

**Comment by Diablopc** [comment]
@cranes-bill both screenshots was made on the same page ([from here](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter#Example))with the same code, just with different pics uploaded from dynamically generated source.

Here is on-eye exemple with local files:
![](http://i.piccy.info/i9/ad1eddb782638797d8fc53b2020803ea/1515685035/454174/1199641/Screenshot_20180111_173623.png)

**Comment by cranes-bill** [comment]
Ah, i don't know, i'm not familiar with this.
But the same page says whether Chrome is not supported. Also see the [Chromium bug](https://code.google.com/p/chromium/issues/detail?id=497522) link on that page. So probably the Opera is based of newer Chromium version, where that is fixed.
And finally the very odd is whether everything works [here](https://www.w3schools.com/cssref/css3_pr_filter.asp).

**P.S:** _Sorry for the bad English!_
