### ISSUE TITLE
Bad „Speed Dial“ opening

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#2544]
If i have only one page opened in the window, when i close it, the browser should open „Speed Dial“ because i have :ballot_box_with_check:  _**Don't close window upon closing last tab**_ option set, but it opens an empty „Speed Dial“ instead. _(The „Speed Dial“ settings are by default)_.
![capture du 2018-01-12 22 12 07](https://user-images.githubusercontent.com/5161278/34893519-3666c558-f7e6-11e7-90fd-74d58f9f6e14.png)

**Comment by Diablopc** [comment]
Have U tried https://github.com/QupZilla/qupzilla/pull/2539#issuecomment-357351396 ?

**Comment by nowrep** [comment]
Does it also happen when you try to "close" some `qupzilla:` internal page like `qupzilla:start` ?

**Comment by cranes-bill** [comment]
@nowrep - It  **does not**, i have also tried with `qupzilla:about` and `qupzilla:config`

@Diablopc I will try it right after it will be merged.

**Comment by cranes-bill** [comment]
@nowrep  Perhaps QtWebEngine issue, because it is non reproducible with AppImage as well as @Diablopc can't reproduce it?

**Comment by nowrep** [comment]
What is your QtWebEngine version?

**Comment by nowrep** [comment]
Please send me terminal output when closing last tab.

```diff
diff --git a/src/lib/webengine/webpage.cpp b/src/lib/webengine/webpage.cpp
index 8039bf5e..69a76598 100644
--- a/src/lib/webengine/webpage.cpp
+++ b/src/lib/webengine/webpage.cpp
@@ -377,6 +377,7 @@ void WebPage::setupWebChannelForUrl(const QUrl &url)
 
 bool WebPage::acceptNavigationRequest(const QUrl &url, QWebEnginePage::NavigationType type, bool isMainFrame)
 {
+    qDebug() << url << type << isMainFrame;
     if (!mApp->plugins()->acceptNavigationRequest(this, url, type, isMainFrame))
         return false;
 

```

**Comment by cranes-bill** [comment]
Sorry for the late response (which is nonsense already ;D), i've had something other to do....!
Thanks!
