### ISSUE TITLE
Lagging scrolling with native scrollbars

### ISSUE THREAD

**Issue by NickLion** [QupZilla/qupzilla#2545]
When native scrollbars are on scrolling becomes not smooth, like some lag between scrollbar scroll and page scroll. If native are off and standard chromium scrollbars are used, scroll is fine.

I can't say when problem appeared. But It looks like after some of last QupZilla update (I'm using git). But there was also Qt update to Qt 5.10 some time ago, maybe it has something with that, but it seems (though unsure) after Qt update it was ok.

openSUSE Tumbleweed x86_64, KDE Plasma 5.11.5, KDE Frameworks 5.41.0, Qt 5.10 (xcb), X11, not Wayland.

**Comment by nowrep** [comment]
#2246

**Comment by NickLion** [comment]
Sorry, I have searched but somehow missed it.
