### ISSUE TITLE
Tabs are misplaced sometimes

### ISSUE THREAD

**Issue by NickLion** [QupZilla/qupzilla#2546]
I haven't found 100% reproducible scenario, but it happens quite often, sometimes tab is shown in wrong place and it's valid place is just empty. Can't reproduce that on Falkon (almost the same as QupZilla 2.1.99).
After windows size change or click on empty tab place or changing some tab name everything becomes fine.
<img width="656" alt="screenshot_20180113_121206" src="https://user-images.githubusercontent.com/744015/34905219-e6a534ba-f85c-11e7-89cd-af2ad9d52aa8.png">

openSUSE x86_64, KDE Plasma 5.11.5, Qt 5.10, QupZilla from git 20180109T204351.4d9a9af6.

PS most commonly misplacing happens after tab changes it's title.

**Comment by nowrep** [comment]
What is your Qt style? Is that Breeze?

**Comment by NickLion** [comment]
Yes, Breeze.

**Comment by NickLion** [comment]
Tabs are aligned left everywhere.

**Comment by nowrep** [comment]
Does it happen also with Windows theme?

**Comment by NickLion** [comment]
I've checked Fusion, Windows and Kvantum, can't reproduce problem anywhere except Breeze. But also can't reproduce on Falkon with Breeze.

**Comment by nowrep** [comment]
Hmm that's weird, it should be exactly the same code. Do you also build Falkon from source or use snap?

**Comment by NickLion** [comment]
Both QupZilla and Falkon are built from git sources in my home repository:
https://build.opensuse.org/project/show/home:NickLion:qt5:Unstable
And I'm installing them as regular RPM's.

**Comment by nowrep** [comment]
Your Falkon doesn't have all the recent commits, so that's why you can't reproduce it there. When you update it should be the same as QupZilla.

**Comment by NickLion** [comment]
Yes, I know. So problem is somewhere in those commits, right?

**Comment by nowrep** [comment]
Yes. Can you please post your Breeze style config? Animations enabled, animations duration, center tabs (you don't have it afaic see from the screenshot).

**Comment by NickLion** [comment]
Can't find where they are stored, so just from gui:
General:
[-] Center tabbar tabs
[+] Draw toolbar item separators
[+] Draw focus indicator in lists
[+] Draw slider tick marks
[+] Enable extended resize handles
Keyboard accelerators visibility: Show Keyboard Accelerators When Needed
Windows' drag mode: Drag from all empty areas

Animations:
[+] Enable animations
Animations duration: 100ms

Frames:
All off

Scrollbars: Top and bottom: No Buttons.

---

Menu as button on titlebar but off for QupZilla using *.desktop
Exec=KDE_NO_GLOBAL_MENU=1 QTWEBENGINE_REMOTE_DEBUGGING=12345 qupzilla %u

**Comment by NickLion** [comment]
It looks like it have something to tabs without icon. Tab without icon after reload moved roughly twice more than it should.

**Comment by NickLion** [comment]
Speed Dial page doesn't look affected though. But http://example.com/ and https://build.opensuse.org/project/show/home:NickLion are.

**Comment by nowrep** [comment]
If the tab title is too long, it will shift a little to the left when tab icon (loading animation) is hidden. I don't see a problem here?

**Comment by nowrep** [comment]
Can you test with Breeze animations disabled?

**Comment by nowrep** [comment]
Oh, I just finally reproduced it.

**Comment by NickLion** [comment]
It fixed, thanks!
