### ISSUE TITLE
databases-incognito directory is created in user's home directory

### ISSUE THREAD

**Issue by elcste** [QupZilla/qupzilla#2547]
Sometimes after using a private window I find the `databases-incognito` directory in my home directory. It's easy enough to delete, but should it be created somewhere under `~/.config/qupzilla` (or maybe `~/.cache/qupzilla`) (for Linux and the appropriate places under Win/Mac)?

**Comment by nowrep** [comment]
It should not be created at all, what is your QtWebEngine version?

**Comment by elcste** [comment]
Sorry, I should have included that. It's 5.9.1 from Ubuntu 17.10. (QupZilla I built from source earlier in the week if it matters.)

**Comment by cranes-bill** [comment]
That also occurs to me and really annoying me.
**5.9.3 QtWebEngine**

**Comment by nowrep** [comment]
Any particular site on which it happens? I can't reproduce it here with QtWebEngine 5.10.

**Comment by cranes-bill** [comment]
I don't know, it really happens from time to time.

**Comment by cranes-bill** [comment]
Reproduced it with youtube (second tab), but after closing QupZilla, the directory was deleted, so maybe it is fixed already?

**Comment by Chiitoo** [comment]
I remember seeing it in the past, too, but since deleting it some time ago, it doesn't seem to have re-appeared.

Currently on QtWebEngine 5.10.0, with Falkon 2.1.99 (26307bd3).

**Comment by cranes-bill** [comment]
https://bugreports.qt.io/browse/QTBUG-62957

**Comment by elcste** [comment]
Thanks @cranes-bill. I will start searching that bugtracker when I suspect the issue could be with QtWebEngine.
