### ISSUE TITLE
Undefined address bar behaviour with disabled "inline suggestions"

### ISSUE THREAD

**Issue by Diablopc** [QupZilla/qupzilla#2550]
While "Enable inline suggestions" option is unchecked it going not to entered url but to first bookmark if it exists or to default search engine with empty string.
When this option enabled - all works as defined.
 if what:
qtwebengine & qt == 5.10.0
Builded from 7c320a0296d5b044409c870875d47cd1b4490018

- Here is full  config: https://pastebin.com/8LRAhswY

**Comment by cranes-bill** [comment]
This is the default behavior. It shows **History & Bookmarks**. You can change it to:
**History**
**Bookmarks**
**Nothing**

**Comment by Diablopc** [comment]
@cranes-bill You want say that behavior[ like this](https://youtu.be/KUDspWPjG_U) - that ok?

**Comment by cranes-bill** [comment]
Ah, my bad, sorry! I thought you have disabled :white_medium_square: **Show search suggestions**
That really looks as bug.
