### ISSUE TITLE
Default zoom on pages not working

### ISSUE THREAD

**Issue by cribari** [QupZilla/qupzilla#2554]
I run Qupzila version 2.2.4 under Arch Linux + KDE Plasma, qt5 version 5.10.0. Problem: Changing the value in "Default zom on pages" (say, from 100% to 150%) makes no difference. That is: Default zoom is not working.

**Comment by nowrep** [comment]
It only works for new tabs.

**Comment by elcste** [comment]
> It only works for new tabs

<kbd>Ctrl</kbd>+<kbd>0</kbd> (View → Reset) works for me with existing tabs
