### ISSUE TITLE
Falkon mouse gestures

### ISSUE THREAD

**Issue by DoctorSubtilis** [QupZilla/qupzilla#2555]
How can I activate mouse gestures in Falkon?
 Thank you

**Comment by nowrep** [comment]
Same as in QupZilla: Preferences -> Extensions -> enable Mouse Gestures.

**Comment by DoctorSubtilis** [comment]
But I don't see any extension in Preferences -> Extensions (I have Kubuntu 17.10 and Falkon via snap)

**Comment by nowrep** [comment]
Then it's broken and you should report it on KDE bugtracker.

**Comment by nowrep** [comment]
Also honestly, you shouldn't really use the snap version as there is a lot of other issues too.

**Comment by DoctorSubtilis** [comment]
Witch other version can I use, with Kubuntu? Thank you

**Comment by nowrep** [comment]
AppImage (from homepage), may work better for you.

**Comment by DoctorSubtilis** [comment]
Could you tell my the url?, thank you

**Comment by nowrep** [comment]
https://www.qupzilla.com/download#linux

**Comment by DoctorSubtilis** [comment]
This is qupzilla, I have already, but I'd like get falkon (better with same video): there is not a falkon appimage?

**Comment by nowrep** [comment]
No, there is not.

**Comment by DoctorSubtilis** [comment]
OK thank you. I follow your work with much interest. I hope we will get soon a complet Falkon realease. Thank you
