### ISSUE TITLE
video not showing

### ISSUE THREAD

**Issue by DoctorSubtilis** [QupZilla/qupzilla#2557]
When I try to play a video I get this error message: "#11 INVALID STREAMTYPE AND/OR STREAMSERVER SETTINGS FOR THIS IS PROJEKKTOR."
F.e. [http://www.raiscuola.rai.it/articoli/gravity-immaginare-luniverso-dopo-einstein/39672/default.aspx](this url)

**Comment by cranes-bill** [comment]
You must compile QtWebEngine yourself with **PROPRIETARY CODECS** option enabled!
There is a lot of threads about that here...

**Comment by DoctorSubtilis** [comment]
Too difficult. I will wait for a Falkon browser appimage :)

**Comment by cranes-bill** [comment]
> ...I will wait for a Falkon browser appimage 

Which also will not have this feature. ;D

**Comment by DoctorSubtilis** [comment]
No, with Falkon I **can** see that video

**Comment by cranes-bill** [comment]
You are funny.
Good luck!

**Comment by nowrep** [comment]
It has nothing to do with Falkon or QupZilla, it depends on your QtWebEngine. AppImage builds use official Qt builds (am I right @cranes-bill ), which does not have enabled proprietary codecs (due to licensing issues).

**Comment by DoctorSubtilis** [comment]
But with Falkon I see [http://www.raiscuola.rai.it/articoli/gravity-immaginare-luniverso-dopo-einstein/39672/default.aspx](http://www.raiscuola.rai.it/articoli/gravity-immaginare-luniverso-dopo-einstein/39672/default.aspx)

**Comment by cranes-bill** [comment]
@nowrep You are always absolutely right. ;)

**Comment by Chiitoo** [comment]
One possibility that comes to mind, is that the site is serving Flash video when the proprietary codecs are not available, but one of the browsers doesn't quite see that either.

**Comment by DoctorSubtilis** [comment]
Solved! With Qupzilla.appimage I don't see that video, but with Qupzilla provided by Ubuntu I can. Sin is the 2.1.2 :(
