### ISSUE TITLE
How to save or print page ?

### ISSUE THREAD

**Issue by andr222** [QupZilla/qupzilla#2562]
Qupzilla 2.0.2 on Linux 64bit (Mageia)
I'm trying to save (or print to file) a page loaded in Qupzilla, and since I didn't know how to do it in Qupzilla, I tried with another application using the URL, which gives me another page.
It seems this is because the page I want to save is password protected, and the other application doesn't give me the option of entering the password.
However, the password is saved in Qupzilla.
Is there a way of saving (or printing to file) a page with Qupzilla ?
If it is with a later version, maybe I can reload the page under Qupzilla with the latest version, but I'm not sure.
Thanks in advance for any help

**Comment by nowrep** [comment]
Please update to more recent version.

**Comment by andr222** [comment]
I downloaded the latests appimage (v2.2.4) and wow !
Tremendous improvements.
Including a convenient print to pdf option :)
Thanks to everyone who contributed !
