### ISSUE TITLE
Add option to unload tabs

### ISSUE THREAD

**Issue by SGOrava** [QupZilla/qupzilla#2563]
Hello,
I am using a lot of tabs, i don't bother closing them and in some sort using them is bookmarks.
Because of this behaviour i would like to unload right now unneeded tabs which are only eating a lot of memory.
When simplified one tab eats 200MB and i have at least 20 of them it eats 4GB which is half of my memory.

So i would like to be able to unload tabs. (keep them in the same state as not opened tabs when restoring previous session)
And if there is this option also add it to TabManager.

**Comment by andr222** [comment]
Suggestion : bookmark such tabs in a temporary folder (maybe by date), then unload them.
Or bookmark all current tabs in a special folder by date, unloading those not currently needed.  This I have done from time to time in a previous browser (when I had a lot less memory available).
