### ISSUE TITLE
Adjust searchbar behaviour

### ISSUE THREAD

**Issue by SGOrava** [QupZilla/qupzilla#2564]
I would like to see these things:

- Option to load search results in new tab
- Option to not trigger search when switching search engine in toolbar
- Also button to erase the field #2483

**Comment by nowrep** [comment]
* shift+enter
* right click to search bar -> uncheck "search on engine change"
* #2483

**Comment by SGOrava** [comment]
Thank you...
1. I tried that and it did not work.... after some trial and error i found out that in ArchLinux package it is `ALT+ENTER`
2. Thank yuo

**Comment by nowrep** [comment]
Sorry you are right, <kbd>Shift+Enter</kbd> is for ignoring "Switch to tab".
