### ISSUE TITLE
Adblock is gone or am I missing it somewhere?

### ISSUE THREAD

**Issue by pegasusearl** [QupZilla/qupzilla#2567]
So.. I don't remember how but now I can't access adblock configuration. I think I have access to it from Preferences some time ago but now I can't found it anywhere.
And when I want to whitelist a site I need to right click and adblock menu will appear there but now it's not. 

screenshoot
https://pasteboard.co/H4pL6ps.jpg

I wonder if it's the right place to post that. I'm sorry if It wasn't.

**Comment by nowrep** [comment]
It's in the "Tools" button in navigation toolbar. You can also move it somewhere else with "Configure Toolbar".
