### ISSUE TITLE
Manage Search Engines in Tools menu?

### ISSUE THREAD

**Issue by elcste** [QupZilla/qupzilla#2568]
If you have the search bar hidden, the only way to manage the search engines is **☰** → **Preferences** → **Other** → **Search Engines Manager** or unhiding the search bar, both of which are many clicks away. My suggestion is to add a **Manage Search Engines** entry to the **Tools** menu below **Configure Toolbar**. (It could even show up only if the search bar is hidden, if that's easy to do.)

**Comment by SGOrava** [comment]
You can use keywords to select search engines when you are typing in address bar.

**Comment by elcste** [comment]
@SGOrava 

Yes, I use keyword search engines so much I was suggesting an easier way to manage them ;-)
