### ISSUE TITLE
Sessions lost if older version loaded automatically

### ISSUE THREAD

**Issue by andr222** [QupZilla/qupzilla#2569]
I have been using the latest Appimage, since the version from the current release of my distro is 2.02.
Unfortunately the last time I rebooted, the version from my distro (still installed) loaded automatically.
The saved sessions were automatically deleted.   (It was quite a few hours trying to recover from the previous loss.)
We need a prompt warning of deleting saved configuration including sessions **before** anything is deleted.
Something which requires a response, like
`This version of Qupzilla is older than the last version executed.  If you continue, all saved configuration and saved sessions will be deleted.`
`C= continue and delete saved configuration,  A=abort and keep saved configuration`

(I might not encounter this problem again, but I'm sure that others will if it isn't fixed.)

**Comment by nowrep** [comment]
I already said it in last issue, it is fixed, but only in new versions. I can't obviously fix it in old versions.

**Comment by andr222** [comment]
Sorry for the noise.  I should have realised that it wouldn't be active in versions <= 2.2.4.
Thanks for all your ongoing improvements.
Qupzilla is already a lot better/easier to work with than my previous browsers.
