### ISSUE TITLE
Bug in „Location completer“

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#2570]
Clicking on the selected address of „**Location completer**“ does not perform an action. If i use the middle click, it just opening an empty page.
_(The search icons are working as expected)_
...........................
a5e058f Qt 5.9.3

**Comment by nowrep** [comment]
I can't reproduce it.

Type something to location bar -> popup completion opens -> click on some entry and it loads.

**Comment by cranes-bill** [comment]
Yes, if type something to location bar and then select the entry it works, but the problem is when i use the **down-arrow** 
![capture du 2018-01-26 10 30 19](https://user-images.githubusercontent.com/5161278/35431132-fe0c6bb0-0283-11e8-99d2-dac9006fdc95.png)
