### ISSUE TITLE
[Feature request] Change window color/style in private mode

### ISSUE THREAD

**Issue by Diablopc** [QupZilla/qupzilla#2575]
The great thing will be ability to change (permanently in config) window color or maybe theme for private browsing. Because at current point only one thing can help to differ standart window from private, there is hint in window name, but it not visible while used long site title or while windows decorations not used.

**Comment by nowrep** [comment]
`BrowserWindow` gets property `private` set to `true` in private mode, so you can use that to change the color.

**Comment by cranes-bill** [comment]
Let me tell you what i think also would be „great thing“ here - if people who make pull requests are focusing to complete'em, instead of opening non sense issues.

**Comment by nowrep** [comment]
Something like this can be done for Linux theme:

```css
#mainwindow
{
    background : palette(dark)
}
```

**Comment by cranes-bill** [comment]
@nowrep sorry, i'm just not a fan of „paint job“ ideas, furthermore if there is something other to do!
