### ISSUE TITLE
No way to disable User Style Sheet

### ISSUE THREAD

**Issue by elcste** [QupZilla/qupzilla#2576]
I can't find a way to disable using a User Style Sheet once you set it in **Preferences → Other**, except by setting it to a different file.

Maybe it needs a checkbox to enable/disable it, like the Spell Check preferences?

**Comment by nowrep** [comment]
Just clear the input with stylesheet path?

**Comment by elcste** [comment]
Yes, of course. I think editing the path directly (rather than using the file open dialog) is less common in Mac/GTK+ apps, which is my background
