### ISSUE TITLE
Unable to add new passwords / usernames with encrypted backend

### ISSUE THREAD

**Issue by SGOrava** [QupZilla/qupzilla#2577]
Hello,
I am using Encrypted backend in Password Manager and i am unable to add new entries to it.
When it was set to plain text backend i was able to add one username/password combination and after that i changed and converted stored passwords to encrypted backend. After that there is no prompt or anything which would allow me to save passwords.

**Comment by nowrep** [comment]
Works fine here, try to do clean build.

**Comment by SGOrava** [comment]
What do you mean by "clean build" ?
I installed qupzilla (2.2.5) from repozitory (Archlinux)
Do you mean i should try to create new profile or something ?

**Comment by nowrep** [comment]
Alright, I assumed you were building from source.

On which site you are trying it?

**Comment by SGOrava** [comment]
Well i built it from source in order to play with it...
Few times when i was figuring how to set the environment for it (variable...) it started with my normal profile instead of local one for the build

well ... any, namely
- aliexpress
- kissanime
- google
- test page from irc

**Comment by nowrep** [comment]
I can reproduce it now.
