### ISSUE TITLE
problem build with qt 5.9.4

### ISSUE THREAD

**Issue by redirkules41** [QupZilla/qupzilla#2583]
hi.

i have a problem building the newest release. when i want to make, i always get the following error:
++
Project ERROR: Unknown module(s) in QT: webenginecore webenginewidgets
Makefile:46: die Regel für Ziel „sub-src-lib-make_first“ scheiterte
make: *** [sub-src-lib-make_first] Error 3
++
i checked my qt installation and everything looks okay and for previous releases it worked.
does anybody had already this error? i guess it is qt related but google couldn't help me so far.

thanks in advance

**Comment by nowrep** [comment]
You need to install QtWebEngine.
