### ISSUE TITLE
building kdwallet-plugin

### ISSUE THREAD

**Issue by redirkules41** [QupZilla/qupzilla#2586]
hi.

i wanted to build qupzilla-2.2.5 with kdwallet-plugin. i added "DEFINES *= KDE_INTEGRATION" to the defines.pri-file or i tried the method to export variable KDE_INTEGRATION="true" before i qmake. but still this plugin is not present in the binary. i read the build manual. i couldn't find a reason. perhaps my syntax is wrong? i don't get any warnings oder errors during the build. so i assume all libs are installed.

thanks in advance and regards
helge

**Comment by nowrep** [comment]
It also needs kf5-wallet-dev.

**Comment by redirkules41** [comment]
hi.
it is definitely installed. i tried to build with the gnome-keyring plugin. same result, it is not installed. when i look in the src file, i see that just the default plugins like greasemonkey etc are modified, not the folders of kwallet or keyring. i think i do sth wrong setting up the build. my routine is:
export KDE_INTEGRATION="true"
qmake
make 
make install
in the folders of e.g. kwalletpasswords there is no makefile after build.

regards
helge

**Comment by nowrep** [comment]
`qmake -r` ?

**Comment by redirkules41** [comment]
i get the following error message. but even there no word about kwallet.
#####
Reading /opt/qupzilla-2.2.5/src/lib/lib.pro
Project MESSAGE: ===========================================
Project MESSAGE: Using following defines:
Project MESSAGE: QUPZILLA_SHAREDLIBRARY QUPZILLA_VERSION=\"2.2.5\" QT_NO_URL_CAST_FROM_STRING QT_USE_QSTRINGBUILDER KDE_INTEGRATION USE_LIBPATH=\"/usr/lib/x86_64-linux-gnu\" USE_DATADIR=\"/usr/share/qupzilla\" QZ_WS_X11
Reading /opt/qupzilla-2.2.5/src/main/main.pro
Reading /opt/qupzilla-2.2.5/src/plugins/plugins.pro
 Reading /opt/qupzilla-2.2.5/src/plugins/AutoScroll/AutoScroll.pro
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/ar_SA.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/bg_BG.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/ca_ES.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/cs_CZ.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/da_DK.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/de_DE.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/el_GR.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/es_ES.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/es_MX.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/eu_ES.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/fi_FI.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/fr_FR.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/he_IL.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/hr_HR.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/hu_HU.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/id_ID.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/is.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/it_IT.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/ja_JP.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/lt.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/lv_LV.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/nb_NO.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/nl_NL.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/nqo.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/pl_PL.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/pt_BR.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/pt_PT.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/ro_RO.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/ru_RU.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/sk_SK.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/sl_SI.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/sr@ijekavianlatin.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/sr@ijekavian.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/sr@latin.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/sr.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/tr_TR.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/uk_UA.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/zh_CN.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/zh_HK.qm'
RCC: Error in 'autoscroll.qrc': Cannot find file 'locale/zh_TW.qm'
 Reading /opt/qupzilla-2.2.5/src/plugins/FlashCookieManager/FlashCookieManager.pro
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/bg_BG.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/ca_ES.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/cs_CZ.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/da_DK.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/de_DE.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/el_GR.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/es_ES.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/es_MX.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/eu_ES.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/fa_IR.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/fi_FI.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/fr_FR.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/he_IL.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/hr_HR.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/id_ID.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/is.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/it_IT.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/ja_JP.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/lt.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/lv_LV.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/nb_NO.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/nl_NL.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/pl_PL.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/pt_PT.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/ro_RO.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/ru_RU.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/sl_SI.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/sr@ijekavianlatin.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/sr@ijekavian.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/sr@latin.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/sr.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/tr_TR.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/uk_UA.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/zh_CN.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/zh_HK.qm'
RCC: Error in 'flashcookiemanager.qrc': Cannot find file 'locale/zh_TW.qm'
 Reading /opt/qupzilla-2.2.5/src/plugins/GreaseMonkey/GreaseMonkey.pro
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/ar_SA.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/bg_BG.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/ca_ES.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/cs_CZ.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/da_DK.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/de_DE.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/el_GR.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/es_AR.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/es_ES.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/es_MX.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/es_VE.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/eu_ES.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/fa_IR.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/fi_FI.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/fr_FR.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/gl_ES.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/he_IL.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/hr_HR.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/hu_HU.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/id_ID.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/is.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/it_IT.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/ja_JP.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/ka_GE.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/lt.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/lv_LV.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/my_MM.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/nb_NO.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/nl_NL.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/nqo.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/pl_PL.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/pt_BR.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/pt_PT.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/ro_RO.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/ru_RU.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/sk_SK.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/sl_SI.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/sr@ijekavianlatin.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/sr@ijekavian.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/sr@latin.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/sr.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/sv_SE.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/tr_TR.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/uk_UA.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/uz@Cyrl.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/uz@Latn.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/zh_CN.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/zh_HK.qm'
RCC: Error in 'greasemonkey.qrc': Cannot find file 'locale/zh_TW.qm'
 Reading /opt/qupzilla-2.2.5/src/plugins/ImageFinder/ImageFinder.pro
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/bg_BG.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/ca_ES.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/da_DK.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/de_DE.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/el_GR.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/es_ES.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/es_MX.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/eu_ES.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/fr_FR.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/hr_HR.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/hu_HU.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/id_ID.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/is.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/it_IT.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/ja_JP.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/lt.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/nb_NO.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/nl_NL.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/pt_PT.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/ru_RU.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/sl_SI.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/tr_TR.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/uk_UA.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/zh_CN.qm'
RCC: Error in 'imagefinder.qrc': Cannot find file 'locale/zh_TW.qm'
 Reading /opt/qupzilla-2.2.5/src/plugins/MouseGestures/MouseGestures.pro
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/ar_SA.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/bg_BG.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/ca_ES.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/cs_CZ.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/da_DK.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/de_DE.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/el_GR.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/es_ES.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/es_MX.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/es_VE.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/eu_ES.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/fa_IR.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/fi_FI.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/fr_FR.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/gl_ES.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/he_IL.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/hr_HR.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/id_ID.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/is.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/it_IT.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/ja_JP.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/ka_GE.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/lt.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/lv_LV.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/nb_NO.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/nl_NL.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/nqo.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/pl_PL.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/pt_BR.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/pt_PT.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/ro_RO.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/ru_RU.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/sk_SK.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/sl_SI.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/sr@ijekavianlatin.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/sr@ijekavian.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/sr@latin.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/sr.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/sv_SE.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/te.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/tr_TR.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/uk_UA.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/uz@Cyrl.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/uz@Latn.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/zh_CN.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/zh_HK.qm'
RCC: Error in 'mousegestures.qrc': Cannot find file 'locale/zh_TW.qm'
 Reading /opt/qupzilla-2.2.5/src/plugins/PIM/PIM.pro
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/ar_SA.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/bg_BG.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/ca_ES.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/cs_CZ.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/da_DK.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/de_DE.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/el_GR.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/es_ES.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/es_MX.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/es_VE.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/eu_ES.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/fa_IR.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/fi_FI.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/fr_FR.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/gl_ES.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/he_IL.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/hr_HR.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/hu_HU.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/id_ID.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/is.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/it_IT.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/ja_JP.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/ko_KR.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/lt.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/lv_LV.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/nb_NO.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/nl_NL.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/nqo.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/pl_PL.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/pt_BR.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/pt_PT.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/ru_RU.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/sk_SK.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/sl_SI.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/sr@ijekavianlatin.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/sr@ijekavian.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/sr@latin.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/sr.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/tr_TR.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/uk_UA.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/uz@Cyrl.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/uz@Latn.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/zh_CN.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/zh_HK.qm'
RCC: Error in 'PIM_res.qrc': Cannot find file 'locale/zh_TW.qm'
 Reading /opt/qupzilla-2.2.5/src/plugins/StatusBarIcons/StatusBarIcons.pro
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/ar_SA.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/bg_BG.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/ca_ES.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/cs_CZ.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/da_DK.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/de_DE.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/el_GR.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/es_ES.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/es_MX.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/es_VE.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/eu_ES.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/fa_IR.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/fi_FI.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/fr_FR.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/he_IL.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/hr_HR.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/id_ID.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/is.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/it_IT.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/ja_JP.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/lt.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/lv_LV.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/nb_NO.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/nl_NL.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/nqo.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/pl_PL.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/pt_PT.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/ru_RU.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/sk_SK.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/sl_SI.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/sr@ijekavianlatin.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/sr@ijekavian.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/sr@latin.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/sr.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/tr_TR.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/uk_UA.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/uz@Cyrl.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/uz@Latn.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/zh_CN.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/zh_HK.qm'
RCC: Error in 'statusbaricons.qrc': Cannot find file 'locale/zh_TW.qm'
 Reading /opt/qupzilla-2.2.5/src/plugins/TabManager/TabManager.pro
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/ar_SA.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/bg_BG.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/ca_ES.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/da_DK.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/de_DE.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/el_GR.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/es_ES.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/es_MX.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/eu_ES.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/fa_IR.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/fr_FR.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/he_IL.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/hr_HR.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/id_ID.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/is.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/it_IT.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/ja_JP.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/lt.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/lv_LV.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/nl_NL.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/nb_NO.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/pl_PL.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/pt_PT.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/ru_RU.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/sl_SI.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/sr@ijekavianlatin.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/sr@ijekavian.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/sr@latin.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/sr.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/tr_TR.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/uk_UA.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/zh_CN.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/zh_HK.qm'
RCC: Error in 'tabmanagerplugin.qrc': Cannot find file 'locale/z
#####
am i right he is missing the translations?

**Comment by nowrep** [comment]
You can ignore those and build now.

**Comment by redirkules41** [comment]
nais. not it works. the -r addition was the key.
thanks man for the quick and steady help.

regards
helge
