### ISSUE TITLE
How to enable java?

### ISSUE THREAD

**Issue by jamesqf** [QupZilla/qupzilla#2587]
In my actually working version of qupzilla (1.8.9), there is an option to enable java under Preferences->Browsing.  Under the version (2.0.1) packaged with OpenSuSE 42.3, the option is not there.  (I can't run the latest version, due to appimage problems mentioned in another issue.)  But java needs to be enabled to install the NVidia graphics drivers (from https://www.geforce.com/drivers ). How do I enable it?

**Comment by jamesqf** [comment]
I did.  It's there - at least there's a java and all the usual (IIRC) java executables in /usr/bin.  But the NVidia website still says that I need to install java to autodetect my card.

This has become moot, for the present, anyway, since I found a different way to install the drivers using some hidden stuff in OpenSuSE's YAST.  At least I hope it will install them...

**Comment by nowrep** [comment]
NPAPI plugins (which is Java plugin) are no longer supported by ani modern browsers.

You can either download the installer directly from nvidia, or use your distribution packages, there is no need for Java.
