### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla#2591]
Clipped session:
``` sh-session
...
cd VerticalTabs/ && ( test -e Makefile || /opt/Qt/5.10.0/gcc_64/bin/qmake -o Makefile /home/user/repo/git/QupZilla/martii/qupzilla/src/plugins/VerticalTabs/VerticalTabs.pro ) && make -f Makefile 
make[2]: Entering directory '/home/user/repo/git/QupZilla/martii/qupzilla/src/plugins/VerticalTabs'
/opt/Qt/5.10.0/gcc_64/bin/uic -no-stringliteral verticaltabssettings.ui -o build/ui_verticaltabssettings.h
Could not create output file
make[2]: *** [Makefile:1799: build/ui_verticaltabssettings.h] Error 1
make[2]: Leaving directory '/home/user/repo/git/QupZilla/martii/qupzilla/src/plugins/VerticalTabs'
make[1]: *** [Makefile:253: sub--home-user-repo-git-QupZilla-martii-qupzilla-src-plugins-VerticalTabs-make_first] Error 2
make[1]: Leaving directory '/home/user/repo/git/QupZilla/martii/qupzilla/src/plugins'
make: *** [Makefile:97: sub-src-plugins-make_first] Error 2
```

9e632e8
Linux

**Comment by nowrep** [comment]
Works on CI https://travis-ci.org/QupZilla/qupzilla

**Comment by Martii** [comment]
Doesn't appear to have built under Qt 5.10.0 there except for OS X.

**Comment by nowrep** [comment]
Yeah right, works on my machine with Qt 5.10.

Show me full output of
```
/opt/Qt/5.10.0/gcc_64/bin/uic -no-stringliteral verticaltabssettings.ui -o build/ui_verticaltabssettings.h
```

**Comment by Martii** [comment]
Not much to show.

``` sh-session
$ /opt/Qt/5.10.0/gcc_64/bin/uic -no-stringliteral verticaltabssettings.ui -o build/ui_verticaltabssettings.h
File 'verticaltabssettings.ui' is not valid
```

**Comment by nowrep** [comment]
It's valid for me, what Qt 5.10 you have? Is it some rc/beta/alpha?

**Comment by nowrep** [comment]
Also you need to be in correct directory so the `verticaltabssettings.ui` path is valid.

**Comment by Martii** [comment]
Plain release via Qt Unified Installer. *(5.10.0-0-201712041258)* Project was building a little while back, not exactly sure at what point... did an upstream master to my master merge and this appeared.

**Comment by Martii** [comment]
> Also you need to be in correct directory so the `verticaltabssettings.ui` path is valid.

Project root here of `qupzilla`.

**Comment by Martii** [comment]
Okee I see... it's night time for me... hold.

**Comment by Martii** [comment]
``` sh-session
cd build
$ /opt/Qt/5.10.0/gcc_64/bin/uic -no-stringliteral verticaltabssettings.ui -o build/ui_verticaltabssettings.h
Could not create output file
```

**Comment by nowrep** [comment]
Alright, great :D No idea then, it is valid XML file and there is no obvious issue with it.

**Comment by nowrep** [comment]
`build` directory doesn't exists, right? 

`/home/user/repo/git/QupZilla/martii/qupzilla/src/plugins/VerticalTabs/build`

**Comment by Martii** [comment]
Reinitialized my local master *(entire tree)* from a fresh checkout... something must have burped from my SSD to HDD... builds now. Probably some OS issue and/or clone issue since I moved up to 2TiB HDD. 

Sorry for the noise... weird error that cropped up though.
