### ISSUE TITLE
2.2.5: GIFs cannot be saved to disk

### ISSUE THREAD

**Issue by OVasily** [QupZilla/qupzilla#2593]
Right mouse click on the GIF and picking the menu item "Save Media To Disk" causes  QupZilla crash under Win7 32x

**Comment by OVasily** [comment]
... and using "Save Image as" right mouse button click menu item too. QupZilla crashes.

**Comment by srazi** [comment]
@OVasily I can not reproduce it on Win10 64Bit. Please give some test links and steps to reproduce it.

**Comment by OVasily** [comment]
I have no Win10 64x but **# Win7 32x**

Any site. Any image and any GIF. Absolutly any.
Even here right click your avatar picture and choose Save image as... menu item. QupZilla crashes.

**Comment by srazi** [comment]
Unfortunately, I don't have access to a Win7 32bit right now. If you know how to use a debugger on windows (e.g. WinDbg) then maybe stack trace when crash occurs can help us.

**Comment by OVasily** [comment]
Where can I find the QupZilla debug build with full debug info? 
I have no possibility to build it myself from source codes under Windows.

Release build 2.2.5 for Windows 32x under Delphi debugger gives me
`Project C:\Program Files\QupZilla\qupzilla.exe faulted with message: 'access violation at 0x6aaf93cb: read of address 0x00000000'. 
`

**Comment by OVasily** [comment]
OK. It seems to be the 
https://github.com/QupZilla/qupzilla/issues/2590
Maybe. Where can I find today build for testing purposes?

**Comment by srazi** [comment]
Well, there is not a debug build available. But WinDbg always give me some info in call stack even with release build.

No, the issue 2590 is not related (but you can find qupzilla.exe and qupzilla.dll of its portable build [here](https://ci.appveyor.com/project/srazi/qupzilla-utoeb/build/2.2.5.348-master/job/omd5rx4x0d1ckdld/artifacts). I don't know if they work for you).

Did you try to run QupZilla with a fresh profile?

**Comment by OVasily** [comment]
> (but you can find qupzilla.exe and qupzilla.dll of its portable build here. I don't know if they work for you)
But this one pair of exe+dll works fine - no crash!

**Comment by Martii** [comment]
@srazi 
> Unfortunately, I don't have access to a Win7 32bit right now.

See https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ if you do VM's. That SSD toasted itself so I can't test this myself just yet... still recovering.

**Comment by OVasily** [comment]
I think no need. In latest build (2.2.5.348-master) all OK.

**Comment by srazi** [comment]
> I just rewrite them in %program files%\QupZilla directory and try to reproduce the error.
> No problem!

Good! :D
But, the path `%program files%\QupZilla` is not writable and the portable version of QupZilla try to create profile directory there. That is impossible.

I think your issue was resolved since you are now using a fresh profile.

**Comment by OVasily** [comment]
It's all OK with admin rights. It has all write privileges in %PF%
I didn't try it under not privileged user. 
> I think your issue was resolved since you are now using a fresh profile.
Supposed to be.  I'll try it when 2.2.6 relase will be done.
