### ISSUE TITLE
Pages not loading

### ISSUE THREAD

**Issue by musger** [QupZilla/qupzilla#2595]
Hi,
quite a few webpages do not load (no progress is indicated, no URL is resolved etc.) on Debian testing's qupzilla 2.2.5 with Qt 5.9.2. This does not happen with a fresh profile, yet all I did to my profile was to change settings in the preferences, no extensions are enabled, disabling adblock does not help.
Please let me know how I can help further.

**Comment by SGOrava** [comment]
Is it something like #2578  ?

**Comment by musger** [comment]
* Juraj Oravec <notifications@github.com> [2018-02-09 13:09]:
> Is it something like #2578  ?
Darn, it is! Thank you! My mistake was to only search open issues in the
tracker, not the closed ones. Please close this, one #2595 as it is a
duplicate.

P
