### ISSUE TITLE
Can't restore last closed tab  

### ISSUE THREAD

**Issue by Diablopc** [QupZilla/qupzilla#2596]
When last tab is closed (with "Don't close window" enabled) it  cannot be restored with  Ctrl+Shift+T, and it not appears in "History" -> "Last closed tabs"

**Comment by SGOrava** [comment]
Based on my small test, last tab is not closed but address is changed to new empty page (start/speed dial).
Just hit the back button.

PS: I agree that this is not ideal solution.
