### ISSUE TITLE
Google Toolbar "tools" 

### ISSUE THREAD

**Issue by ralftze** [QupZilla/qupzilla#2600]
Dear All,
on my first ubuntu system i used I installed qupzilla 1.8.9, WebKit-Version: 538.1
On this version if I use google search engine results will be shown and on left side of the results
there's an additional "toolbar" of the google "Tools" menu where I can filter the results very fast by just clicking at it - sorry for hardcopying german version....
![img_20180211_131852kl](https://user-images.githubusercontent.com/36367917/36073527-a5e0e428-0f32-11e8-93d7-b8c0f97d9eba.jpg)
Now I have new ubuntu version and new qupzilla qupzilla 2.2.5, WebKit-Version: 5.10.0 and
the filter toolbar is at the normal position again.
![img_20180211_131852klnew](https://user-images.githubusercontent.com/36367917/36073582-722ad728-0f33-11e8-8c0c-9853ec7e3f56.jpg)
How can I have this google tools toobar on left side back because I loved it very much and also my colleague want to have it
Thanks in advance!
Regards
Rafl

**Comment by cranes-bill** [comment]
Try to change **USER AGENT**!

**Comment by ralftze** [comment]
Dear cranes-bill,
thanks for your advice.
Old status: No specific user agent
New status: Choosed 1st User Agent: "Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16"
Toolbar is back! Problem solved!
The other 3 user agent I'm able to choose will not solve problem.
But nevertheless thanks for helping me!
Regards
Ralf
