### ISSUE TITLE
Is such a thing worth having in Qupzilla?

### ISSUE THREAD

**Issue by AcarBurak** [QupZilla/qupzilla#2603]
https://github.com/keraf/NoCoin

**Comment by SGOrava** [comment]
Can it be solved by new list in adblock ?

> How does it work?
> 
> The extension is simply blocking a list of blacklisted domains in blacklist.txt. Clicking on the icon will display you a button to pause/unpause No Coin. If you are aware of any scripts or services that provide coin mining the browser, please submit a PR.

**Comment by nowrep** [comment]
You can add eg. `uBlock filters – Resource abuse​​​​​` to QupZilla AdBlock.

**Comment by potholiday** [comment]
@nowrep I tried to add `uBlock filters – Resource abuse​​​​​` from  [here](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt) , when I tried to `Add Subscription` its giving this error `Cannot load subscription`

**Comment by cranes-bill** [comment]
@potholiday This subscription is for uBlock but not for Adblockplus. You must edit it if really want to use it!

**Comment by nowrep** [comment]
https://github.com/QupZilla/qupzilla/commit/d2bd668e32bef696917af5129ded6df8618e4cd9
