### ISSUE TITLE
QZ_REGISTER_EVENT_HANDLER undefined

### ISSUE THREAD

**Issue by HJarausch** [QupZilla/qupzilla#2606]
I have qt-5.9.1 installed on my Gentoo system.
Compile the GIT version of Qupzilla fails due to

copytitle.cpp:55:5: error: 'QZ_REGISTER_EVENT_HANDLER' was not declared in this scope
     QZ_REGISTER_EVENT_HANDLER(PluginProxy::MousePressHandler);

**Comment by cranes-bill** [comment]
Do you really need this plugin?

**Comment by HJarausch** [comment]
Hopefully, I've fixed the problem with

sed -e 's|QZ_REGISTER_EVENT_HANDLER(PluginProxy::MousePressHandler)|\
    // Registering this plugin as a MousePressHandler.\
    // Otherwise mousePress() function will never be called\
    mApp->plugins()->registerAppEventHandler(PluginProxy::MousePressHandler, this)|'  src/plugins/CopyTitle/copytitle.cpp

**Comment by nowrep** [comment]
Should be fixed now.
