### ISSUE TITLE
Feature  request: Printing to PDF with the page title

### ISSUE THREAD

**Issue by test666v2** [QupZilla/qupzilla#2608]
**Feature  request: Printing to PDF with the page title**

Printing to PDF now defaults to "print.pdf". If possible, please restore the capabilitiy to automatically insert the page title as the filename.

Keep up the good work. Thank you.

**Comment by TARPTAEYA** [comment]
created a PR for the same.

**Comment by nowrep** [comment]
5372944860da8b93d9cd755f3cb782a4122b6181
