### ISSUE TITLE
Autoscroll plugin does not honor some links

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla#2616]
On some pages like [that](https://git.videolan.org/?p=vlc.git;a=summary) for example, when the Autoscroll plugin is enabled,  a middle click over the link activates the auto scrolling instead of open link in new tab.
By the way i solved that as follow:
```diff
diff --git a/src/plugins/AutoScroll/autoscroller.cpp b/src/plugins/AutoScroll/autoscroller.cpp
index 65da1d1..63a3743 100644
--- a/src/plugins/AutoScroll/autoscroller.cpp
+++ b/src/plugins/AutoScroll/autoscroller.cpp
@@ -220,7 +220,7 @@ bool AutoScroller::showIndicator(WebView* view, const QPoint &pos)
 {
     const WebHitTestResult res = view->page()->hitTestContent(pos);
 
-    if (res.isContentEditable() || !res.linkUrl().isEmpty() || res.tagName().endsWith(QL1S("frame"))) {
+    if (res.isContentEditable() || !res.linkUrl().isEmpty() || res.tagName().endsWith(QL1S("frame")) || res.tagName() == QL1S("a")) {
         return false;
     }
 
```
but perhaps some better solution is possible?

**Comment by cranes-bill** [comment]
The issue is now affects the **_thumbnail links_** :innocent:

**Comment by nowrep** [comment]
What?

**Comment by cranes-bill** [comment]
Activate autoscroll and do middle click on some image where refers to some address. For example the github logo on top of the page!

**Comment by nowrep** [comment]
Sorry, fixed.

**Comment by cranes-bill** [comment]
Perfect, thanks!
