### ISSUE TITLE
Feature request: Enable going back to the start page via the back button

### ISSUE THREAD

**Issue by l3u** [QupZilla/qupzilla#2620]
I recently switched from Opera to QupZilla, and I'm missing one tiny feature (which possibly could be implemented quite easily, I haven't looked into the code yet though):

I had set Opera to display the speed dial site when starting. If one clicks on such a bookmark, one can go back to the speed dial via the "back" button (or a respective mouse gesture). This makes it easy to check several bookmarks.

This is not possible (yet) in QupZilla. To achieve the same, I have to open a new tab (displaying the speed dial) and close the currently open one.

Would be nice if one could navigate back to the speed dial page :-)

**Comment by l3u** [comment]
Well, as I read now, this should probably rather go into the KDE Falkon repository …

**Comment by cranes-bill** [comment]
> If one clicks on such a bookmark, one can go back to the speed dial via the "back" button (or a respective mouse gesture). This makes it easy to check several bookmarks.

And how about to use a middle click just to open the bookmark in new tab?

**Comment by l3u** [comment]
Surely a workaround, but the possibility to use the "Back" button would be nicer. The project surely won't stand and fall with this – it would just be a tiny but nice improvement imo.

**Comment by AcarBurak** [comment]
Another workaround would be setting Home to speeddial (`qupzilla:speeddial`) and clicking Home instead of Back button.

**Comment by l3u** [comment]
I'll check if I can submit a patch implementing this.

**Comment by nowrep** [comment]
61678e98619617b0d6d46ff229df830e07803e36

**Comment by l3u** [comment]
Thanks a lot :-) This will be also be forward(?)-ported to the Falkon repository, won't it?

**Comment by nowrep** [comment]
Yes, it was actually *back*ported from falkon.

**Comment by l3u** [comment]
Nice :-) And all the kudos for putting so much effort in this awesome project!
