### ISSUE TITLE
Where are all of my bookmarks gone?!?!?! Falkon upgrade

### ISSUE THREAD

**Issue by Jakecheslekov** [QupZilla/qupzilla#2622]
Guys all of my bookmarks are GONE! What gives?!?! THOSE WERE ALL VERY IMPORTANT!!!! OMG!
How is it the upgrade didn't add all of my bookmarks?!?! I NEED MY BOOKMARKS BACK!!! Ridiculous!!!

**Comment by Jakecheslekov** [comment]
Copy/pasting bookmarks.json and database.db from ~/.config/qupzilla/profiles/default/ to ~/.config/falkon/profiles/default/ has restored my bookmarks. That was TERRIFYING. 
Please be more mindful of your users' bookmarks & etc next time, as many of us rely on those bookmarks for work.

**Comment by nowrep** [comment]
There is no auto migration from QupZilla to Falkon.

**Comment by cranes-bill** [comment]
![sedrftg](https://user-images.githubusercontent.com/5161278/36748759-761df9e8-1c01-11e8-82bd-af9cb9651778.gif)
