### ISSUE TITLE
QupZilla crashes (Void Linux Live)

### ISSUE THREAD

**Issue by Beatzekatze** [QupZilla/qupzilla#2623]
I've been testing the Void Linux live image with lxqt desktop environment starring QupZilla as browser. Sadly QupZilla crashes only few seconds after I launch it. When startet from the console these are the lines which pop up in the console:

```
AdBlockSearchTree: Inserting rule with filter len  <= 0!
AdBlockSearchTree: Inserting rule with filter len  <= 0!
AdBlockSearchTree: Inserting rule with filter len  <= 0!
AdBlockSearchTree: Inserting rule with filter len  <= 0!  # als that  appears at startup
qupzilla: pushbf.c:727: nouveau_pushbf_data: Assertion `kref' failed.
Aborted
```

I found this (unresolved?) bug: https://bugs.launchpad.net/oxide/+bug/1499419 , which sound like it might be the cause.
Running `qupzilla --disable-gpu` as suggested in https://github.com/QupZilla/qupzilla/issues/2589 allows to work with qupzilla for a while, but after 15~20 minutes when opening multiple tabs the entire system freezes, with only option being a reboot. 
I understand that the problem can just as likely arise from the live image (and it probably does), but I want to work from top to bottom. (I will add more info about the system specs asap)

**Comment by cranes-bill** [comment]
How about if you boot with the following kernel parameters?
`nouveau.modeset=0 rd.driver.blacklist=nouveau` 
**Note:** This will disable nouveau driver.

**Comment by nowrep** [comment]
You answered yourself, nouveau is to blame here and partly also QtWebEngine.
