### ISSUE TITLE
Problem when compiling to windows

### ISSUE THREAD

**Issue by hubuga** [QupZilla/qupzilla#2624]
When I try to compile on Windows MSVC 2015 I get an error:

> qupzilla-2.2.5\src\lib\tools\aesinterface.h:26: error: C1083: Cannot open include file: 'openssl/evp.h': No such file or directory

I don't know how to link the openssl in the project, I tried to look the `pro` file in order to see if there's a `INCLUDEPATH` or something like that but it doesn't have so I'm kinda lost on how to compile.

**Comment by srazi** [comment]
Run qmake with openssl added to `INCLUDEPATH` and `LIBS`:
```
qmake INCLUDEPATH+=PATH_TO_OPENSSL_DIR\include LIBS+=-LPATH_TO_OPENSSL_DIR\lib QupZilla.pro
make
```
