### ISSUE TITLE
qupzilla will not load gmail in https in first try?

### ISSUE THREAD

**Issue by ghost** [QupZilla/qupzilla#2625]
I am using qupzilla V 2.2.5 appimage version. When I used qupzilla to load `gmail.com` it goes to the unencrypted version of gmail login `http://gmail.com` instead of the encrytped version `https://gmail.com` but when I reloaded it then it will redirect to the encrypted page of gmail. I tried with private browsing and also with newly created profile in qupzilla and in both cases the problem exists. Only qupzilla have this problem and other browsers seems to work properly.

**Comment by cranes-bill** [comment]
I was noticed that for some other sites too, but the weird here is that `http` stands even after reload to me.

**Comment by potholiday** [comment]
The other thing I noticed is that whenever I visit a `http` site qupzilla warns me with a pop up but here it doesnt warn us. weird!!!

**Comment by TARPTAEYA** [comment]
Have you checked the url from site info (`Main Menu -> Tools -> Site info`)? Is it `https`?

**Comment by cranes-bill** [comment]
@TARPTAEYA Nope, it's `http`
As additional information - that's only accours when i call some address from _address-bar_! 
For example, if you select `qupzilla.com` >> context menu >> Go to web address, it will open **https://qupzilla.com**, but if you type `qupzilla.com` in the address-bar end hit **enter**, it will load **http://qupzilla.com**

**Comment by nowrep** [comment]
It can't load `http://qupzilla.com`, there is a permanent redirect to HTTPS.

**Comment by cranes-bill** [comment]
Does it possible that to be caused by **libcrypto**?

**Comment by nowrep** [comment]
Those errors maybe, but I meant that qupzilla.com server will not serve anything (except the 302 redirect page) over HTTP, so this is only a visual issue.

**Comment by cranes-bill** [comment]
Actually, first time i did try with `larousse.fr` and it showing http in site info, but now as i tried with `qupzilla.com`, it's only **http** on addres-bar but site info shows **https**

**Comment by nowrep** [comment]
What about with current qupzilla `master`?

I'm going to make final release now, so if it doesn't fix it, it would need to go to falkon.

**Comment by cranes-bill** [comment]
All of those tests i did with Falkon :-D

**Comment by nowrep** [comment]
Alright, this didn't fix it 61678e98619617b0d6d46ff229df830e07803e36

To make it clear, if locationbar has focus, it will not update url from page. So if the locationbar gets focused (either by user interaction - clicking on it, or by a bug by itself) it will not update the url. You can still press <kbd>ESC</kbd> to manually update it.

**Comment by cranes-bill** [comment]
Yeah, <kbd>ESC</kbd> updating the address :+1:
