### ISSUE TITLE
CLI option to start a new session

### ISSUE THREAD

**Issue by Houkime** [QupZilla/qupzilla#2626]
I'm currently trying to automate window arrangement for streams and stuff via wmctrl and xdotool, and everything is fine except for the fact that Qupzilla CLI doesn't allow to discard current session and start fresh new from the shell.
I mean, even when you do 
`qupzilla -u <url>`
which intuitively should start fresh clean window, it still tries to restore your last session if you have restoration enabled.

Which makes you do manual cleanups after spawning stuff with script.

I don't want to disable restoration or jump between profiles, I want an option to make a new clean window even if it discards a session.

**Comment by nowrep** [comment]
Delete `$PROFILE/session.dat` before running `qupzilla -u <url>` if you really want to lose your session.
This is, however, not how it should behave by default.
