### ISSUE TITLE
Wish: session recovery page: save session to file

### ISSUE THREAD

**Issue by the-Arioch** [QupZilla/qupzilla#2629]
It is sadly typical for QZ/win to crash when trying to recover

And you cannot try to detect which tabs initiate the crahs by unchecking this or that ones, because after succesfull loading - the crashed session woudl be just lost. There is no place to retrieve list of pre-crash tabs if you already loaded QZ past recovery page.

So i wish the recovery paeg had an option to save tabs list as session file that can be loaded later, into notepad at very least

**Comment by nowrep** [comment]
> because after succesfull loading - the crashed session woudl be just lost.

Can you please elaborate?

**Comment by the-Arioch** [comment]
> It is sadly typical for QZ/win to crash when trying to recover

that makes the loop, the only exit out of which is to avoid recovering tabs, all or most of them.

if you can not load QZ with the tabs open, then you only can load it without those tabs, loosing information which tabs were opened forever.

**Comment by Jau-nee** [comment]
I am used to have a huge number of tabs open. When I have to restart after a crash or hang up of the computer, I have to start QupZilla, close and start again... 

But in the past two years I have lost all the session about three or four times, when I was not able to get a copy of the old session.dat to start again.

So, there is that session.dat in ~/.config/qupzilla/profiles/default/session.dat and .../session.dat.old and .../session.dat.old1, but a hex editor seams of limited use...

**Comment by the-Arioch** [comment]
So, `session.dat` is binary? Guess it better be made textual, like in old Opera...

**Comment by nowrep** [comment]
What is the difference between text and binary? You can edit both if you want.
