### ISSUE TITLE
History window and BACK button

### ISSUE THREAD

**Issue by the-Arioch** [QupZilla/qupzilla#2631]
I opened a page from the History windows (Ctrl+Shift+H) by double click

Unexpectedly it did not opened new tab but overwritten the current tab - the action potentially dangerous, as it would for example destroy user input in web forms (forum messages, etc).

I wanted to click "back" button - but the back button was disabled !
Alt+Left hotkey worked though.
Inconsistency.

**Comment by nowrep** [comment]
Will be fixed in Falkon 3.0.1
