### ISSUE TITLE
qwe-launch without execute bit

### ISSUE THREAD

**Issue by Jau-nee** [QupZilla/qupzilla#2632]
I have just installed sudo snap install kde-frameworks-5 and sudo snap install falkon --edge on a XFCE desktop. Falkon is in the XFCE start menue, but can not be started. From a terminal I got:
/snap/bin$ snap run falkon
/snap/falkon/36/kf5-launch: line 123: /snap/falkon/36/qwe-launch: Permission denied
/snap/falkon/36/kf5-launch: line 123: exec: /snap/falkon/36/qwe-launch: cannot execute: Permission denied

The script /snap/falkon/36/qwe-launch is not marked executable, but the /snap directory is read only...

**Comment by nowrep** [comment]
Falkon bugs should be reported at bugs.kde.org.
