### ISSUE TITLE
Reddit and twitch videos are not working?

### ISSUE THREAD

**Issue by potholiday** [QupZilla/qupzilla#2637]
Reddit and twitch videos are not working in qupzilla but works in other browser. 
https://www.reddit.com/r/WatchPeopleDieInside/comments/89i7fa/boyfriend_proposes_to_daughter_in_front_of_father/

Tried with new profile still not working. 

@nowrep  Is there a new appimage for version 2.2.6 availabe for this issue https://github.com/QupZilla/qupzilla/issues/2628

**Comment by cranes-bill** [comment]
Those sites need **PROPRIETARY CODECS**!
These codecs are not available in the QtWebEngine bundled with Appimage.
The video are working if the codecs are available:
![capture du 2018-04-04 09 43 52](https://user-images.githubusercontent.com/5161278/38292884-224e74e2-37ee-11e8-90b0-c0e5a0492e51.png)

**Comment by potholiday** [comment]
In falkon it works but falkon is not yet released in ubuntu or other linux distros. @cranes-bill  should I close this issue or keep it open?

**Comment by cranes-bill** [comment]
Works in QupZilla as well, i just posted screen from Falkon because it was already running.
Falkon is released in most distros.
There is a lot of issues about proprietary codecs here and thеy are marked as invalid, but the choice is yours...
