### ISSUE TITLE
QupZilla Portable vulnerable to Spectre

### ISSUE THREAD

**Issue by apometron** [QupZilla/qupzilla#2638]
![image](https://user-images.githubusercontent.com/4054252/38407741-0e0826d6-3951-11e8-88a8-e9218bd75d57.png)

https://i.imgur.com/Gc5MOeT.png

https://xlab.tencent.com/special/spectre/spectre_check.html

The version of my QupZilla is from PortableApps.com, 2.2.5.

**Comment by cranes-bill** [comment]
Official QupZilla Portable packages are [this](https://github.com/QupZilla/qupzilla/releases/download/v2.2.6/QupZilla.2.2.6.Portable.Installer.exe) and [this](https://qupzilla.com/startdownload?windows_portable)
So why do you expect somebody here to be responsible for packages downloaded from _**somewhere other**_!?
