### ISSUE TITLE
Does qupzilla patched for Meltdown and spectre vulnerabilities?

### ISSUE THREAD

**Issue by potholiday** [QupZilla/qupzilla#2639]
Some user has recently posted about spectre vulnerability in a portable qupzilla packaged by a third party
https://github.com/QupZilla/qupzilla/issues/2638 . I went and searched about Meltdown and spectre; it seems [desktop and laptop users are more vulnerable](https://insights.ubuntu.com/2018/01/24/meltdown-spectre-and-ubuntu-what-you-need-to-know) to this issue. This is what the link says
````
browser-hosted Javascript is an important attack vector, with advisories and updates being issued for both Mozilla/Firefox and Chrome browsers.
````
Is qupzilla vulnerable for these attacks and if yes, is there a patch available?

**Comment by NickLion** [comment]
1. My QupZilla built from git in OBS without special patches is not vulnerable.
2. Final release of QupZilla was out about month ago. There wouldn't any new QupZilla releases. 2.2.6 is final. QupZilla is over, move to Falkon now. Anyway, both of them aren't vulnerable according to that site.

**Comment by nowrep** [comment]
QtWebEngine 5.9.4 and 5.10.1 are not vulnerable.
