### ISSUE TITLE
Qupzilla crashes right at launch

### ISSUE THREAD

**Issue by vkmaheshbhat** [QupZilla/qupzilla#2643]
I am running Qupzilla on Ubuntu 17.10 64-bit machine. When I launch qupzilla:

```
mahesh@mahesh-Dell:~$ qupzilla
QupZilla: 0 extensions loaded
AdBlockSearchTree: Inserting rule with filter len <= 0!
AdBlockSearchTree: Inserting rule with filter len <= 0!
AdBlockSearchTree: Inserting rule with filter len <= 0!
AdBlockSearchTree: Inserting rule with filter len <= 0!
AdBlockSearchTree: Inserting rule with filter len <= 0!
AdBlockSearchTree: Inserting rule with filter len <= 0!
QupZilla: Crashed :( Saving backtrace in /home/mahesh/.config/qupzilla/crashlog ...
Backtrace successfully saved in /home/mahesh/.config/qupzilla/crashlog/Crash-018-04-28T09:46:45.txt
```
[Crash-2018-04-28T09:46:45.txt](https://github.com/QupZilla/qupzilla/files/1957435/Crash-2018-04-28T09.46.45.txt)

The crash report is attached.

**Comment by nowrep** [comment]
This is too old version, please update to 2.2.6, or even better, to Falkon.

**Comment by vkmaheshbhat** [comment]
@nowrep : Thank you! Upgrading to Falkon fixed the isue. Should have tried this before even reporting I guess. Lesson for the future...
