### ISSUE TITLE
Possible to remove the tilte bar?

### ISSUE THREAD

**Issue by mcdoubleyou** [QupZilla/qupzilla#2644]
I want to use the browser as central for all messenger apps: WhatsApp, Telegram, Slack, and so on.
Because of that I try to minimize the bars, I deactivate search and the menu, but I couldn't find an option to hide the title bar.

Thanks!

**Comment by nowrep** [comment]
You can use window manager that allows to disable title bars on Linux.

**Comment by mcdoubleyou** [comment]
I'm on Windows, any option to make it work here also? Couldn't find a Window Manager Plugin in QupZilla or Fallon.

Thx
