### ISSUE TITLE
Need an UI improvement

### ISSUE THREAD

**Issue by trmdi** [QupZilla/qupzilla#2646]
Look at the UI comparison between Firefox and Falkon:

![image](https://user-images.githubusercontent.com/11857205/39639512-91dd8e70-4ff3-11e8-8f44-ccba4789be72.png)

Can you reduce Falkon's `tabbar/toolbar/address bar/bookmark bar` height a bit ? It's a waste of vertical space.

**Comment by nowrep** [comment]
Did you read that message that is displayed when opening new issue?
