### ISSUE TITLE
Vertical tabs (preferably tree)

### ISSUE THREAD

**Issue by ralesk** [QupZilla/qupzilla#330]
There’s an excellent plugin for Firefox called Tree Style Tab, which allows us to put the tabs on the left or right side of the browser _and_ organise them in a tree — a tab you open from a link in another tab will appear as the child of that tab.

Having tabs in a sidebar is very useful on today’s wide but short displays.

**Comment by dotancohen** [comment]
Here is the Qt feature request for a vertical tab widget:
https://bugreports.qt.io/browse/QTBUG-22488

As noted in that feature request, the KDE IRC app Quassel (erroneously called Konversation in the report) has implemented a custom vertical tab widget. As it is open source, perhaps it could be used in Qupzilla. The following page suggests using a QListView along with QStackedWidget/QStackedLayout for vertical tabs:
http://www.qtcentre.org/threads/55361-QTabWidget-vertical-tabs
