### ISSUE TITLE
Navigation Bar Customisation

### ISSUE THREAD

**Issue by krzd** [QupZilla/qupzilla#440]
It should be possible to rearrange or even remove items from the navigation bar, for example one might like to remove the search bar in favor of the search shortcuts or one might one the reload button behind the input field.

**Comment by ikem-krueger** [comment]
I want to reorder the navigation bar icons and want to hide the tab bar "new tab" icon.

I looked at the comment from "pejakm" and his pastebin, but the pastebin is gone.

I also tried some "main.css" hackery, but I have my problems with qt css dialect.

I tried:

    #tabwidget-button-addtab
    {
        qproperty-visible: false;
    }

    #tabwidget-button-addtab
    {
        qproperty-isVisible: false;
    }

    #tabwidget-button-addtab
    {
        qproperty-setVisible: false;
    }

    #tabwidget-button-addtab
    {
        qproperty-isHidden: true;
    }

But nothing works.

So how do I achieve that?

**Comment by GreenLunar** [comment]
Also offer to add buttons of other options such as Allow Java/Javascript etc.

**Comment by nowrep** [comment]
Navigation Bar is now customizable.
