### ISSUE TITLE
not remembering zoom settings when revisiting the page

### ISSUE THREAD

**Issue by anshul1886** [QupZilla/qupzilla#454]
It is not remembering zoom settings.   When I zoom in the page and close the browser then it forgets the zoom in and I have to zoom in it again everytime I open that page.

**Comment by johnfound** [comment]
> and won't be available.

Why? And how about through a plugin? In the recent high dpi monitors many web sites are simply not readable. Others are properly designed. This way one global setting is simply not enough. One possible approach is to have some kind of auto-zoom feature.
