### ISSUE TITLE
Password Import

### ISSUE THREAD

**Issue by AndyM48** [QupZilla/qupzilla#686]
I have read this report https://github.com/QupZilla/qupzilla/issues/144 and tried to import my passwords (388) from Firefox, however the file layout used by https://addons.mozilla.org/en-US/firefox/addon/password-exporter/ seems to have changed and bears no apparent similarity to Qupzilla's password export file. In any case, although Qupzilla says that it has imported the file, the passwords are not imported.

I like the slim and speedy nature of Qupzilla, biut it would be handy to be able to import the passwords and would not add bloat to the software.

Thanks and congratulations on an excellent development.

Andrew

**Comment by azzamsa** [comment]
thanks.
