### ISSUE TITLE
No sound for calls through imo.im with qupzilla.

### ISSUE THREAD

**Issue by cdysthe** [QupZilla/qupzilla#718]
When I place voice call on Imo.im I hear the rings, but when the call is picked up it's total silence. I have tried numerous times to no avail. This works fine in all other browsers I have installed: Firefox, Chrome, Opera and Midorri.

**Comment by hmxahjadoon** [comment]
When I place voice/video call on Imo I hear the rings, but when the call is picked up it's total silence. how can I solve this problem plz help me in sorting out this ............
