### ISSUE TITLE
"Always add to this service" checkbox when adding rss feeds

### ISSUE THREAD

**Issue by Thra11** [QupZilla/qupzilla#881]
When adding an rss/atom feed (by clicking the rss icon in the address bar), it always shows a bar with a popup menu to choose which service to add the feed to. If the user only uses one rss reader (quite likely), it would be nice to have a checkbox to say, "Always add the new feed to the selected service without asking". (Ideally, I'd like a single click to add the feed to my chosen reader. Currently, it takes 3 clicks)

There would presumably need to be an option somewhere to get the popup menu to show if necessary. This could be an option in the preferences dialog.

**Comment by nowrep** [comment]
RSS reader is no longer available since QupZilla 2.
